### ISSUE TITLE
Auto merge with imported CSV

### ISSUE THREAD

**Issue by sulazix** [hitobito/hitobito#10]
When importing a CSV, the merge is based on Name and Surname, if somebody is allready in database with same name & surname they're only 2 options :
1. Update user and add an extra Role to this user (related to the targeted group)
2. Do nothing (don't update and leave user unupdated) 
   It should be great to be able to create a new user as a 3rd option

**Comment by codez** [comment]
For the moment, please contact your organisation's application responsible directly for feature requests.

**Comment by RolandStuder** [comment]
Actually merges can depend on more factors often more is defined in the wagons, for example usually it takes birth dates into account if they are available. We have not received any more interest on this, so I mark this issue as stale.
