### ISSUE TITLE
Kursbeschreibung vom Adminbereich beim Kurs abfüllen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#100]
IST: Es kann im Adminbereich zu einem Kurstyp eine Kursbeschreibung erfasst werden (Text unter Allgemein Informationen). Allerdings wird diese nirgendwo angezeigt.

SOLL:
- Die Kursbeschreibung aus dem Adminbereich soll wird unbenannt auf "Standardbeschreibung"
- Sobald ich ich auf dem Formular Kurs editieren oder Kurs erstellen den Kurstyp wähle, wird das bestehende Beschreibungsfeld automatisch ausgefüllt, sofern es leer ist.
- Wenn es nicht leer ist und ich den Kurstyp wähle, dann erscheint bei der Beschreibung ein Link "Standardbeschreibung einsetzen", der Text im Feld Beschreibung wird Standardtext ergänzt (hinter den bestehenden Text).
- Sicherstellen, dass die Beschreibung damit jetzt nicht irgendwo dupliziert wird (z. B. bei PBS).

![](https://wearecube.mybalsamiq.com/mockups/5129949.png)

edit: https://wearecube.mybalsamiq.com/projects/hitobito/edit/100%20Standardkursbeschreibung

---
### Originaltext vom Issue:

Mein Favorit:
- Sobald ich Kurstyp wähle, automatisch Beschreibungsfeld ausfüllen, wenn es leer ist.
- Wenn es nicht leer ist und ich den Kurstyp wähle, dann erscheint bei der Beschreibung ein Link "Standardtext einsetzten", der Text im Feld Beschreibung wird dann vom Standardtext überschrieben.

Günstigste Variante: 
- Einfach beim Kurs in einem zusätzlichen Bereich den "Standardtext" anzeigen, allerdings lässt sicher dieser dann nicht ändern.

Originalissue:
http://feedback.jubla.ch/issues/60

**Comment by fossil12** [comment]
@RolandStuder Wir finden deinen Favorit super!

**Comment by codez** [comment]
Die Allgemeinen Informationen zur Kursart haben doch nur bedingt mit der Beschreibung des Kurses zu tun? Bei der PBS werden diese Informationen, falls vorhanden, direkt unter der Kursart dargestellt. Ich würde auch hier für eine einheitliche Lösung plädieren.

**Comment by fossil12** [comment]
Ich bin nicht direkt in den entsprechenden Gremien dabei, darum weiss ich nur bedingt wie es funktioniert, aber so wie ich das verstanden habe werden die Beschreibungen von der Bulei and die Ast geschickt und dann dort 1:1 für jeden Kurs von Hand eingetragen. Dies sollte mit dieser Lösung verhindert werden. Die Beschreibungen sind je nach Kursart verschieden (wenn ich mich da nicht irre).

**Comment by RolandStuder** [comment]
@codez Das habe ich mir angeschaut, bei der PBS wird das gar nicht verwendet. Das Feld ist auch nicht nachvollziehbar, was damit passiert, deshalb migrieren wir dies zur neuen Funktion. Das Feld heute hat eigentlich gar keine wirklich Zweck :laughing:

**Comment by RolandStuder** [comment]
Das war bereits Diskussion in #27

**Comment by RolandStuder** [comment]
Umgesetzt in https://github.com/hitobito/hitobito_jubla/pull/4

**Comment by codez** [comment]
@RolandStuder Soll das nur in den Jubla Wagon und nicht in den Core?

**Comment by RolandStuder** [comment]
@dinuu Das sollte in den Core.

**Comment by codez** [comment]
Merged, wird nächstens auf die Integrationsumgebung deployt (ab Version 1.14).

**Comment by RolandStuder** [comment]
Fertig für Review.

Meine Beobachtungen:

* Link heisst nur "Standardbeschreibung" und ist damit nicht selbst erklärend -> sollte sein "Standardbeschreibung einsetzen"
* Link erscheint auch, wenn gar keine Standardbeschreibung für den Kurstyp vorhanden ist. Besser wäre, wenn nur bei vorhandener Standardbeschreibung der Link erscheinen würde.
