### ISSUE TITLE
Mailabos auf Multitenant-Umgebung funktionieren nicht

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#1007]
Hallo zämä

Die Mailabos auf den MT-Instanzen funktionieren nicht. Ich denke, dass es sich um ein generelles Problem handelt, da sowohl beim Kunden wie auch bei mir keine Mails zugestellt wurden.

Mit folgenden Listen haben wir getestet:
- passiv.mg@youngstarswiki.hitobito.com
- mitarbeiter@team.hitobito.com

**Comment by amaierhofer** [comment]
Tenants list jetzt ebenfalls den `X-Original-To` Header
