### ISSUE TITLE
Teilnehmerimport bei Events

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#101]
SOLL:

## Ablauf

- rechts vom Button "Person hinzufügen, erscheint ein Button "Liste importieren"
- Auf den Klick erscheint eine Ansicht analog zu: http://pbs.puzzle.ch/de/groups/1/csv_imports/new
- Das Mapping kann gleich definiert werden, wie beim Personenimport, auch die Rolle wird heir ausgewählt. http://pbs.puzzle.ch/de/groups/1/csv_imports/define_mapping (mit allen Attributen)
- Nach Bestätigung der Zuordnung kommt die Übersicht mit der Zuordnung, gleich wie bei: http://pbs.puzzle.ch/de/groups/1/csv_imports/preview
- Dann dieselbe Rückmeldung wie beim Personenimport

## Verhalten

- gilt für alle Typen von Events
- Bei Kursen erscheint die Möglichkeit auf der Seite Anmeldungen, nicht auf der Seite Teilnehmer -> es wird immer mit der Rolle Teilnehmer hinzugefügt.
- der Benutzer weist CSV Spalten den selbstdefinierten Anmeldefelder zu
- Spalten mit selbstdefinierten Anmeldefeldern mit der Möglichkeit von Mehrfachauswahl, werden kommagetrennt deklariert.
- Das Anfrageverfahren muss dabei wie gewöhnlich respektiert werden.
- Für die hinzugefügten Personen wird kein Rolle erstellt, ausser bei Jubla (gleiches Verhalten wie bei "externer Anmeldung)
- Ein Eintrag bei dem Pflichtangaben fehlen, werden trotzdem importiert. Und dann mit der Bemerkung "Pflichtangaben fehlen" versehen (gleich wie bisher).
- Personen mit ungültigen Werte werden nicht importiert. Eine Warnung erscheint auf der Previewseite.

![](https://wearecube.mybalsamiq.com/mockups/5138335.png)

[edit](https://wearecube.mybalsamiq.com/projects/hitobito/edit/101%20Teilnehmerimport%20bei%20Events)

Wir empfehlen entweder eine vollständige Implementation oder dann gar keine. Zwischenlöscungen erscheinen mir nicht sinnvoll.
 
###  Alte Spezifikation:

--- 

SOLL: Import von Teilnehmerlisten ermöglichen, analog zum Personenimport.

Herausforderungen:
- Muss ein Benutzer, die selbst definierten Felder, die man bei der Anmeldung verlangen kann, auch im Import abfüllen können?
- Validieren wir importierte Daten für die selbst definierten Felder.
- Wie gehen wir mit fehlenden obligatorischen Antworten um?

Originalissue: http://feedback.jubla.ch/issues/26

**Comment by fossil12** [comment]
Wir finden dass selbst definierte Felder grundsätzlich auch importiert werden sollen, da sonst das Ziel des Feature verfehlt wird. Wir sind uns aber unsicher wie Multiple Choice Antworten (Radiobuttons, Checkboxes, ...) importiert werden sollen. Wir freuen uns auf Ideen diesbezüglich.

Die importierten Daten sollen genau so validiert werden wie wenn sie im Textfeld eingeben werden.

**Comment by codez** [comment]
Hier besteht die Herausforderung, dass Personen ja nicht neu erstellt werden sollen, sondern nur (?) bestehende Personen aus der Datenbank dem Anlass hinzugefügt werden. Die Personendaten selbst wären wohl nötig, um die richtige bestehende Person zu finden, dürfen aber (bisher) von einem Anlassorganisator nicht verändert werden.

**Comment by fossil12** [comment]
Es wäre am besten, wenn sowohl die bestehenden Personen gematched werden und aber auch neue Personen zur Gruppe des Veranstalters hinzugefügt werden.

Ich sehe nicht ganz wieso da eine Schreibberechtigung vorhanden sein muss. Werde die zusätzlichen Felder zu einem Event in der Person und nicht unabhängig gespeichert?

**Comment by codez** [comment]
Die zusätzlichen Felder zu einem Event werden nicht in der Person gespeichert, aber Name, Adresse, Ort, E-Mail usw.

**Comment by fossil12** [comment]
Okay. Dann würde ich bei bestehenden Personen nur die zusätzlichen Felder importieren und bei neuen alles.

**Comment by RolandStuder** [comment]
Ich habe die Beschreibung angepasst:

SOLL:

## Ablauf

- rechts vom Button "Person hinzufügen, erscheint ein Button "Liste importieren"
- Auf den Klick erscheint eine Ansicht analog zu: http://pbs.puzzle.ch/de/groups/1/csv_imports/new
- Das Mapping kann gleich definiert werden, wie beim Personenimport, auch die Rolle wird heir ausgewählt. http://pbs.puzzle.ch/de/groups/1/csv_imports/define_mapping (mit allen Attributen)
- Nach Bestätigung der Zuordnung kommt die Übersicht mit der Zuordnung, gleich wie bei: http://pbs.puzzle.ch/de/groups/1/csv_imports/preview
- Dann dieselbe Rückmeldung wie beim Personenimport

## Verhalten

- gilt für alle Typen von Events
- Bei Kursen erscheint die Möglichkeit auf der Seite Anmeldungen, nicht auf der Seite Teilnehmer -> es wird immer mit der Rolle Teilnehmer hinzugefügt.
- der Benutzer weist CSV Spalten den selbstdefinierten Anmeldefelder zu
- Spalten mit selbstdefinierten Anmeldefeldern mit der Möglichkeit von Mehrfachauswahl, werden kommagetrennt deklariert.
- Das Anfrageverfahren muss dabei wie gewöhnlich respektiert werden.
- Für die hinzugefügten Personen wird kein Rolle erstellt, ausser bei Jubla (gleiches Verhalten wie bei "externer Anmeldung)
- Ein Eintrag bei dem Pflichtangaben fehlen, werden trotzdem importiert. Und dann mit der Bemerkung "Pflichtangaben fehlen" versehen (gleich wie bisher).
- Personen mit ungültigen Werte werden nicht importiert. Eine Warnung erscheint auf der Previewseite.

![](https://wearecube.mybalsamiq.com/mockups/5138335.png)

[edit](https://wearecube.mybalsamiq.com/projects/hitobito/edit/101%20Teilnehmerimport%20bei%20Events)

Wir empfehlen entweder eine vollständige Implementation oder dann gar keine. Zwischenlöscungen erscheinen mir nicht sinnvoll.

**Comment by fossil12** [comment]
Danke für die Ausarbeitung. Für mich hört sich das so super an! 👍🏻

**Comment by RolandStuder** [comment]
Aktuell können nur Personen Kontaktdaten ändern, wenn sie diese Berechtigung auch sonst auf diese Persone haben. Durch ein Hinzufügen eines Teilnehmers erhält ein Leiter noch keine Berechtigung. Das müssten wir ändern.

**Comment by RolandStuder** [comment]
Jubla hat das zuoberst priorisiert, dass Anlässe besser genutzt werden können.

Frage der Schreibberechtigung auf Anlässe war bisher kaum ein Thema.

Empfehlung von uns ist, das aufs nächste Jahr zu verschieben und mit Puzzle Softwarearchitekt anzugehen.

**Comment by fossil12** [comment]
@RolandStuder Das dies komplizierter erscheint, als ich mir dachte finde ich das okay.

Ich glaube das wirkliche Hauptproblem, welches mit dieser Lösung versucht wird zu lösen ist das schnelle hinzufügen von mehren Personen zu einem Anlass (z.B. Lager). Da will z.B. der Lagerleiter/die Lagerleiterin alle Anmeldungen (die er/sie per Post erhalten hat) auf einmal eintragen und da sind es einige Klicks die es pro Person braucht.

**Comment by RolandStuder** [comment]
Ein Import hat diverse Probleme, wenn etwas zu machen ist, dann wäre das eher, dass man schnell meherer Personen erfassen kann, ohne für diese immer die Anmeldeangaben machen zu müssen, siehe #117
