### ISSUE TITLE
Password Policy

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#1013]
Es wird heute nur eine minimale Länge von 6 Zeichen verlangt, keine Sonderzeichen, Zahlen und Gross- / Kleinschreibung
    
- [OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#implement-proper-password-strength-controls) und [NIST](https://pages.nist.gov/800-63-3/sp800-63b.html#5111-memorized-secret-authenticators) empfehlen nur Mindestlänge, keine Zeichenvorgaben. [Sogar der Autor der vorgeschlagenen Regeln würde das heute nicht mehr vorschlagen.](https://www.wsj.com/articles/the-man-who-wrote-those-password-rules-has-a-new-tip-n3v-r-m1-d-1502124118)

- Vorschlag: Für neue Passwörter mindestens 11 Zeichen verlangen. 
- Wird lediglich beim Ändern des Passworts verlangt.
- Nur diese eine Ziele abändern: https://stackoverflow.com/a/29600389

**Comment by chrusu** [comment]
@luca-bruegger bitte changelog-eintrag hinzufügen.
@luca-bruegger tests auf allen wagons durchlaufen lassen
