### ISSUE TITLE
bypass auth für bilder/attachments

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#1019]
ist der URL bekannt, kann ohne Authentifizierung auf Bilder/Attachments zugegriffen werden. 

Künftig soll es nur noch für authentifizierte User möglich sein auf Bilder zuzugreifen. Profilbilder können nur geladen werden für Personen auf die man Zugriff hat. 

Die Bilder/Attachments werden heute von nginx ausgeliefert. 

Dateien über Backend künftig ausliefern?

**Comment by olibrian** [comment]
Vorsicht: bei Events, welche für Externe zugänglich sind, sollen auch Attachements vom Event angezeigt werden. Da ist der User noch nicht angemeldet

**Comment by kronn** [comment]
Seit die Bilder und Anhänge via ActiveStorage gespeichert sind, ist das zwar technisch immer noch so, aber die URLs sind deutlich schwerer zu raten. Daher schliesse ich dieses Issue hier erstmal.
