### ISSUE TITLE
Zugeteilte Coaches sollen Leseberechtigung auf Lager oder allgemeiner Events erhalten.

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#102]
SOLL: Der Coach, der einem Lager zugeteilt ist, soll die Daten der Lagerteilnehmenden einsehen und exportieren können, insbesondere als csv für den direkten Import in die SportDB.
(Diese Berechtigung hat er nur, wenn er dem Lager zugeteilt ist. Er hat sie nicht, wenn er bei der Schar als Coach hinterlegt ist.)

übernommen aus: http://feedback.jubla.ch/issues/54

Zur vorgeschlagenen eigenen Übersichtsseite  legen wir ein separates Issue an.

Referenzen:

LKB (Advisor) Berechtigungen:
https://github.com/hitobito/hitobito_jubla/blob/6c9ce439e2144ed5c9aa24a0c681b4ecb5135ceb/app/models/event/course/role/advisor.rb

Coach: 
https://github.com/hitobito/hitobito_jubla/blob/master/app/models/event/camp/role/coach.rb

**Comment by RolandStuder** [comment]
Die PBS hat ähnliches im Sinn: Sie reden dort aber nur über LKBs und wollen dann eher gleich Schreibrechte erteilen. Wäre gut, wenn wir hier eine einheitliche Lösung finden. siehe https://github.com/hitobito/hitobito_pbs/issues/23

**Comment by adriananderegg** [comment]
Lager / Coach unterstützen wir wie hier beschrieben. Hier geht es darum, dass der Coach einer Gruppe Zugriff auf die Lager dieser Gruppe hat. 

Kurs / LKB ist ein ähnliches Szenario, aber nicht dasselbe. Beim LKB geht es um den Kurs, welchem der LKB zugeordnet ist. Also eine andere Zuordnungskonstellation.

**Comment by wichertj** [comment]
Sorry, da war das Originalissue etwas missverständlich formuliert.

Die Klammerbemerkung (also der oben genannte IST-Zustand) war als weitere Präzisierung der Anforderung gemeint. Aktuell kann der Coach (zumindest in der jubla.db) die Teilnehmerdaten nicht einsehen/exportieren, selbst wenn er als Coach dem Lager zugeteilt ist.
Dass er die Daten einesehen kann, wenn er der Schar/Abteilung zugeordnet ist, erachten wir als nicht so wichtig, da der zugeteilte Coach ja beim Neuerstellen eines Lagers automatisch vorgeschlagen wird.

Betreffend LKB: In der jubla.db hat dieser bereits Leserechte, also besteht hier akut kein Handlungsbedarf.
Aber ich bin auch der Meinung, dass sich eine einheitliche Lösung finden lassen sollte. Bitte mit Oli4/Bernhard/Lea abstimmen.

**Comment by RolandStuder** [comment]
Danke für die Präzisierungen. Wie ich sehe, ist das Lagerwesen getrennt bei PBS und Jubla, wir müssen das im Moment pro Organisation lösen.

Wahrscheinlich braucht der coach einfach ein zusätzliche Permission. Analog zum LKB.

Referenzen:

LKB (Advisor) Berechtigungen:
https://github.com/hitobito/hitobito_jubla/blob/6c9ce439e2144ed5c9aa24a0c681b4ecb5135ceb/app/models/event/course/role/advisor.rb

Coach: 
https://github.com/hitobito/hitobito_jubla/blob/master/app/models/event/camp/role/coach.rb

**Comment by RolandStuder** [comment]
Umgesetzt in https://github.com/hitobito/hitobito_jubla/pull/2
