### ISSUE TITLE
Fehlende Daten in der GroupHealth Schnittstelle

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1026]
Siehe PR für den GroupHealth-Endpunkt https://github.com/hitobito/hitobito_pbs/pull/157

Beim Testen der externen Applikation hat sich herausgestellt, dass keine vergangenen Rollen aus der Schnittstelle ankommen: Der "Roles"-Endpoint liefert keine Rollen mit "deleted_at" Datum. Diese Rollen sind für das Projektteam sehr relevant, da wir ohne keine historischen Daten aufbereiten können.

Mögliche Ursache:

> Das "Role" model wird mit dem gem "ActsAsParanoid" so erweitert, das Rollen nicht gelöscht, sondern mit "delete_at" als gelöscht markiert werden. Die als gelöscht markierten Datensätze werden dann ausgeschlossen, wenn die Datensätze normal abgefragt werden ("Role.joins..") - sie müssen spezifisch mit "with_deleted" inkludiert werden (siehe Doku https://github.com/ActsAsParanoid/acts_as_paranoid). Dies ist im HealthCheck Endpoint nicht der Fall.

Bitte die Schnittstelle so anpassen, dass die gelöschten Rollen ebenfalls ankommen.

Liebe Grüsse
Michael

**Comment by carlobeltrame** [comment]
Braucht ihr dann wirklich nur die gelöschten Rollen, oder auch die Personen die via die gelöschten Rollen früher in der Gruppe tätig waren?

**Comment by Michael-Schaer** [comment]
Antwort vom Entwickler: 
> Beides wäre sehr wichtig (Rollen und Personen), denn wir aggregieren die Daten bei uns so, dass wir einen Historischen verlauf haben und dafür sind die deleted_at Felder bei Rollen und Personen wichtig.
> 
> Beispielsweise wird dann ersichtlich, dass eine Person eine Qualifikation in einer spezifischen Gruppe, zu einem spezifischen (auch vergangenen) Zeitpunkt hatte. 

Merci fürs Nachhaken, Carlo!

**Comment by carlobeltrame** [comment]
Ist auf Integration testbar.
