### ISSUE TITLE
Frontend Zukunft – the next steps

### ISSUE THREAD

**Issue by hupf** [hitobito/hitobito#1027]
Follow-up von #996

- [ ] NPM Dependencies aktualisieren soweit möglich
- [ ] Browserkompatibilität für Babel (Transpilation für ES2015+), Autoprefixer (CSS Vendor Prefixes) gemäss Projektanforderungen konfigurieren (`.browserslistrc` ist im Moment auf [defaults](https://github.com/browserslist/browserslist#full-list), ev. ist dies auch gut so?)
- [ ] [compass-mixins](https://www.npmjs.com/package/compass-mixins) ausbauen – wir verwenden kein Compass mehr und dies ist ein "Port" der Compass-Mixins für libsass. Wir verwenden nur wenige Mixins, die auch in Plain CSS umgesetzt werden können.
- [ ] Bestehender JavaScript Code auf Stimulus migrieren (allenfalls ohne die Verwendung von jQuery, nur mit nativen APIs)
- [ ] Aufteilung in sinnvolle Chunks: gewisse Features wie der WYSIWYG Editor werden nur in spezifischen Bereichen (z.B. für Admins) verwendet, und müssen nicht von allen Usern heruntergeladen werden.
- [ ] [Chosen](https://github.com/harvesthq/chosen) ersetzen (wird nicht mehr weiterentwickelt), z.B. mit [Selectize](https://github.com/selectize/selectize.js) oder einer anderen (jQuery-unabhängigen) Alternative.
- [ ] Bootstrap 2 updaten oder ersetzen (letzte Version ist von 2013) – allenfalls im Zusammenhang mit einem UI Rebrushing. Wir haben z.B. bereits die Grids und Flexbox Klassen von Bootstrap 4 reingezogen, auf längere Sicht sind wir in einer Sackgasse.

**Comment by carlobeltrame** [comment]
Wird in #1325 weitergeführt.
