### ISSUE TITLE
Für Coaches und Leiterkursbetreuer betreute Kurse auf der Personenübersicht zeigen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#103]
## SOLL: 

Die Rolle als Coach in einem Lager wird auf der Personenansicht angezeigt. Sie wird unter "Meine Betreuungen" angezeigt (ab der Zuteilung bis 1 Monat nach Abschluss des Lagers).

Die Rolle als Leiterkursbetruere in einem Kurs wird anlog auch dort aufgeführt.

* Die Überschriften rechts auf der eigenen Übersichtsseite werden sinnvoller geordnet. Vorschlag: Aktive Rollen - Meine nächsten Anlässe - Meine Anmeldungen - Meine Betreuungen - Qualifikationen - Ehemalige Rollen.
* Das gilt nur für die explizit zugeteilten Rollen Coach und nicht wenn man allgemein als Coach hinterlegt ist.

Originalissue: http://feedback.jubla.ch/issues/54
Berechtigungsteil abgedeckt in #102

**Comment by fossil12** [comment]
Was ist der unterschied zwischen "Meine nächsten Anlässe" und "Meine Anmeldungen"?

Ich würde sagen, dass man als Coach nur das Lager sieht wenn man auch als Coach für dieses Lager eingetragen ist.

**Comment by RolandStuder** [comment]
Ok, danke, das ist sicher viel einfacher, wenn wir nur die direkten Zuweisungen betrachten. Muss wohl im Jubla Wagon gemacht werden. Daher ist nicht klar, ob wir die Reihenfolge problemlos umstellen können. Vermutlich können wir es erst nach Qualifikationen aufführen, wenn wir nicht zusätzlichen Aufwand investieren wollen.

**Comment by fossil12** [comment]
Okay. In demfall ist diese Reihenfolge fest im Core und nicht flexibel anpassbar?

**Comment by RolandStuder** [comment]
Die Reihenfolge ist insofern eingeschränkt, dass zuerst Core Elemente und dann Wagon Elemente kommen, ausser man baut einen neuen Bereich ein, wo man sich einhaken kann. Wir könnten evtl. mit Flexbox die Reihenfolge anpassen. Aber wir machen es erst mal möglichst einfach.

**Comment by RolandStuder** [comment]
Umgesetzt in https://github.com/hitobito/hitobito_jubla/pull/3

**Comment by richardjubla** [comment]
**Bug**: Durch eine Externe Anmeldung für einen Event (Lager) eine Anmeldung gemacht, bekommt das neu erstellte Profil eine Anmeldung als Teilnehmer*in, ein Profil mit der Rolle "Extern" in der Ebene/Gruppe.  Auf der Personenübersicht gibt es aber keinen Grund, im den Event als betreuten Kurs (Meine Betreuungen) anzuzeigen:



![image](https://github.com/hitobito/hitobito/assets/95908537/38d6f666-f5d2-4244-a35a-f52cca773344)
![image](https://github.com/hitobito/hitobito/assets/95908537/69f424e2-5052-4e87-8182-d1a9d25cf187)
![image](https://github.com/hitobito/hitobito/assets/95908537/78ace2c3-00ba-4e10-b2a2-c6bdf08bbc82)
