### ISSUE TITLE
Mailchimp Export schlägt im Dev Container fehl

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1038]
Beim Testen des MailChimp-Exportes in meiner Entwicklungsumgebung (ohne Änderungen) ist mir folgendes aufgefallen:
Wenn die Option "Alle Versandadressen synchronisieren" aktiviert ist, schlägt der Export fehl (der Status auf dem Abo wird als "Fehlgeschlagen" angezeigt).

Auf Produktion und im Integrationssystem der PBS scheint dies nicht der Fall zu sein. Ich frage mich darum, ob sich die Code-Basis verändert hat oder die Dev-Umgebung etwas anders macht als die Int und Prod Instanzen.

#### Mein System
- Ubuntu 20.04
- Docker-Setup wie in hitobito/developement beschrieben, Wagons youth und pbs

#### Problem nachstellen
- Abo erstellen, einige Rollen im Kanton BE hinzufügen
- MailChimp Keys eintragen
- Option "Alle Versandadressen synchronisieren" aktivieren
- Export -> MailChimp anstossen

**Comment by kronn** [comment]
WIr haben am 2020-08-27 eine Default-Einstellung geändert. Seither wird im Development-Setup nicht mehr der Mailchimp-Export ausgeführt. Dies soll verhindern, dass man versehentlich beim Debuggen mit produktiven Daten mit Mailchimp kommuniziert.

Das Setting ist in `config/settings/development.yml` und sollte in `config/settings/development.local.yml` überschrieben werden, wenn man es braucht.

Das hier sollte helfen:

```yaml
# config/settings/development.local.yml
mailchimp:
  enabled: true
```

**Comment by olibrian** [comment]
Issue moved to [hitobito/development #22](https://github.com/hitobito/development/issues/22) via [**ZenHub**](https://www.zenhub.com/)
