### ISSUE TITLE
Personen Filter - tags - Styling typeahead, dropdown

### ISSUE THREAD

**Issue by psunix** [hitobito/hitobito#1039]
Wäre gut wenn wir die Darstellung noch verbessern könnten. Momentan wird das Tag Dropdown (typeahead) vom container verdeckt. Es wäre gut, wenn das überhalb vom Container auftauchen würde. 
Zudem scheint mir das typeahead für Tags auf der Persone Seite nicht optimal aufzutauchen (mal oben, mal unten ..), eventuell kannst du das auch mit Julian anschauen.

![tags_verdeckt](https://user-images.githubusercontent.com/180780/94260461-84d0a200-ff30-11ea-9244-319b102ff3e3.png)

das gleiche Dropdown wird auch unter Abos verwendet: 

![image](https://user-images.githubusercontent.com/655627/94661005-c2ee0d00-0306-11eb-8d04-b691316323d6.png)

dropdown werden abgeschnitten:

![image](https://user-images.githubusercontent.com/655627/94661118-edd86100-0306-11eb-960b-0da98c49f0ae.png)

_Originally posted by @amaierhofer in https://github.com/hitobito/hitobito/pull/1028#issuecomment-698870278_

**Comment by psunix** [comment]
ich hatte das mit der Darstellung kurz mit Hupf angeschaut. Leider verwenden wir eine uralte Bootstrap Version und irgendwie wurde bei diesen Selects viel gebastelt. Leider sind all meine Versuche hier das Styling zu fixen fehlgeschlagen. 
das Styling ist ja auch bei dem bestehenden Tags Filter bereits broken. Darum habe ich jetzt mal die Changes gemerged und dieses Ticket hier erstellt. Vielleicht kann @ninfaj hier etwas anpassen.

View: https://github.com/hitobito/hitobito/blob/master/app/views/people_filters/_tag.html.haml#L12

wir verwenden den select_tag helper was das Anpassen des Stylings nicht einfacher macht.

**Comment by ninfaj** [comment]
Habe hier mal etwas Kleines gemacht:
https://github.com/hitobito/hitobito/compare/collapse-overflow-fix?expand=1

![image](https://user-images.githubusercontent.com/157533/94907181-0a5bd100-04a0-11eb-963b-2677e87fd241.png)


Evtl. müsste man das noch kurz anschauen und sicherstellen, dass es keine unerwünschten Nebeneffekte hat

**Comment by psunix** [comment]
bei chromium klappt es kurz so extrem lange auf, dann ist ok.

![image](https://user-images.githubusercontent.com/655627/95166367-0be20d80-07ae-11eb-9110-026b5e22b69f.png)

bei firefox scheint der fix für den overflow nicht zu funktionieren. 

![image](https://user-images.githubusercontent.com/655627/95166470-3d5ad900-07ae-11eb-9907-cdf275d1d91d.png)
