### ISSUE TITLE
Berechtigungsanpassung Kalei Mitglieder

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#104]
Auf Ebene Kantonsleitung wird in den Rollen
- Mitglied
- Präses
  die Berechtigung "group_read" durch "layer_and_below_read" ersetzt.

**Comment by fossil12** [comment]
Was ist genau der Unterschied zwischen "group_read" und "layer_and_below_read"?

**Comment by RolandStuder** [comment]
@fossil12

layer_and_below_read berechtigt zu:
"Alles Lesen und Schreiben auf dieser Ebene und allen darunter liegenden Ebenen. Erstellen von Anlässen und Abos auf dieser Ebene." (in diesem Fall ist die Ebene der Kanton).

group_read: berechtigt zu:
"Lesen und Schreiben auf der Gruppe. Erstellen von Anlässen und Abos auf der Gruppe." (in diesem Fall nur die Gruppe der Kalei).

**Comment by fossil12** [comment]
@RolandStuder: Danke für die Erläuterung.

@wichertj: Wenn ich das Ganze richtig verstehe bedeutet dies, dass die Kalei auch jedes Releimitglied bearbeiten kann. War dies in der Diskussion so gewünscht?

**Comment by wichertj** [comment]
@RolandStuder: Ich bin der Meinung, dass die obige Erläuterung die Rechte layer_and_below_**full**, respektive layer_**full** beschreibt. 

layer_and_below_read ist meiner Meinung nach: "Alles Lesen auf dieser Ebene und allen darunter liegenden Ebenen."

group_read bedeutet meiner Meinung nach: "Lesen auf der Gruppe."

Kann das sein?

@fossil12: Nein, es ist nicht die Absicht, dass die Kalei-Mitglieder die Relei-Mitglieder bearbeiten können. Es geht darum, dass sie sämtliche Leiter des Kantons sehen können. Bis anhin können die Kalei-Mitglieder-und Präses nämlich nur jene Leiter sehen, die auch das contact_data-Recht haben. (z. Zt. SL, LL, Präses, Kassier)

**Comment by fossil12** [comment]
@wichertj Okay. Das macht sinn für mich.

**Comment by RolandStuder** [comment]
@wichertj  Ah, ja, ich habe nicht gut gelesen.

**Comment by Oli4Berger** [comment]
Es wäre gut, wenn diese Erweiterung der Leseberechtigung sowohl auf Kantons, wie auch auf Regionalebene erfolgen würde, also auch für Mitglied und Präses Regionalleitung

**Comment by ivonu** [comment]
Auf Regional-Ebene ist das jetzt schon der Fall:
- Regionalleitung
- - Leitung: [:layer_and_below_full, :contact_data]
- - Mitglied: [:layer_and_below_read, :contact_data]
- - Präses: [:layer_and_below_read, :contact_data]

**Comment by RolandStuder** [comment]
Ist in commit https://github.com/hitobito/hitobito_jubla/commit/9602c7fd69ff626ff91fd774261ed49b58c0a1e3 umgesetzt.
