### ISSUE TITLE
OAuth AccessToken für API-Calls

### ISSUE THREAD

**Issue by MartinGantenbein** [hitobito/hitobito#1040]
Wenn ich die Dokumentation richtig verstanden habe, dann benötige ich für API-Calls mit den Berechtigungen eines Users ein "personal token". Eine interaktive Drittapplikation kann an ein solches Token gelangen, indem sie den User nach seinem Hitobito-Usernamen (E-Mail) und Passwort fragt und dann den {{/users/sign_in.json}} POSTed. Das ist unschön, so gelangt die Drittapplikation an die Credentials des Users. Es ist (scheinbar) auch unnötig, da Hitobito ja ein OAuth-Provider ist, die Drittapplikation könnte das Userlogin somit an Hitobito delegieren und erhält bei erfolgreichem Login ein AccessToken, ohne das Passwort des Users je zu sehen.

Leider kann ich aber mit diesem OAuth-AccessToken die APIs nicht nutzen (oder mache ich etwas falsch?). Vorzugsweise möchte ich die APIs aufrufen können mit Authorization Header = "Bearer " + access_token (dafür wäre mindestens ein zusätzlicher Scope notwendig).

Ich kann nicht abschätzen, was hier Sache ist:
1. Ich mache etwas falsch und API-Calls mit OAuth-Token ist bereits unterstützt
1. Mit einer kleinen Anpassung kann man API-Calls mit OAuth-Token ermöglichen
1. Es wäre ein grosser Umbau nötig, um API-Calls mit OAuth-Token zu ermöglichen

Im Fall von (2) wäre ich froh um einen entsprechenden Hint, dann kann ich versuchen, das umzusetzen.

**Comment by carlobeltrame** [comment]
Soweit ich weiss ist der OAuth profile endpoint bisher der einzige der mit dem OAuth token abgerufen werden kann. Für generelle Logins sowie die persönlichen API Tokens und die service account Tokens verwenden wir devise. Für OAuth hingegen doorkeeper. Das äussert sich auch darin, dass der OAuth::ProfilesController der einzige ist, der die Methode `doorkeeper_authorize!` verwendet: https://github.com/hitobito/hitobito/blob/master/app/controllers/oauth/profiles_controller.rb#L12

Alle anderen Controller verwenden (meist implizit vererbt) die zentralisierte Methode [`authenticate_person!`](https://github.com/hitobito/hitobito/blob/master/app/controllers/concerns/authenticatable.rb#L59). Es könnte sein dass man dort drin als dritte Art neben `user_sign_in` und `service_token_sign_in` noch doorkeeper einfügen könnte.

Allgemein gibt es Stimmen aus der Community [[1]](https://github.com/hitobito/hitobito/issues/961#issuecomment-646254623) [[2]](https://trello.com/c/J0Z574uy/29-midata-z-31-schnittstellen-erweitern-alte-api-angleichen) die verlangen, die personenbasierten API-Tokens früher oder später zu entfernen, vor allem wegen CORS-Problemen mit diesen. Wenn wir also OAuth-Tokens akzeptieren wäre es zukunftsgerichtet sinnvoll, wenn wir irgendwie auch für diese definieren können, welche Origins im Access-Control-Allow-Origins Header zurückgegeben werden, so wie das für Service Tokens [der Plan](https://github.com/hitobito/hitobito/issues/961#issuecomment-672011636) ist. Denkbar wäre es für mich, dies direkt bei den OAuth-Applikationen in den Einstellungen zu ergänzen.

**Comment by carlobeltrame** [comment]
Fixed in #1115. Thanks again!
