### ISSUE TITLE
Bessere Filter für die Kursansicht (3d)

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1041]
Liebe Community der Jugendverbände

Die PBS wünscht sich bessere Filter für die verfügbaren Kurse. Wir sind aber nicht die einzigen, die Kurse in hitobito verwalten. Darum die Frage an euch: Was haltet ihr von einer Lösung des beschriebenen Problems im Youth-Wagon? 

Achtung: Die Rede ist von der Kursansicht (Hauptmenu links -> Kurse) und nicht von der Kurs-Liste innerhalb der Gruppen. 

Merci für eure Rückmeldungen!

---

### Ausgangslage
Bei der PBS werden geeignete Kurse teilweise von den Teilnehmenden selber ausgesucht und teilweise durch die Ausbildungsverantwortlichen vermittelt. Sowohl die Teilnehmenden als auch die Ausbildungsverantwortlichen haben also das Bedürfnis, kommende Kurse sinnvoll filtern zu können.

Es besteht bereits eine Ansicht "Verfügbare Kurse", die einen Filter für Jahr und Gruppe anbietet. Die Ansicht hat allerdings das Problem, dass zu viele Kurse auf einer Seite angezeigt werden, so dass die weitere Auswahl manuell erfolgt. Bei der Ansicht "Alle Gruppen" sind ausserdem die Ladezeiten so hoch, dass sie vermieden wird.

#### Pagination 
Die Resultate werden in Seiten gegliedert.
#### Filter
- Ebene
- Jahr
- Saison: Frühling, Sommer, Herbst, Winter (mit Mehrfachwahl)
- Kursart und Kurskategorie (neu)
- Kursstatus
- Nur Kurse mit freien Plätzen (Ja/Nein)
#### Kategorien
Die Kursarten werden in Kategorien aufgeteilt, um die Liste der Kursarten übersichtlich zu halten. Kursarten können konfigurativ den Kurskategorien zugeordnet werden.
#### Ebene
Die Filter werden beim Aufruf der Seite sinnvoll gesetzt. Für die Betrachtenden werden erst einmal Kurse der eigenen Ebene angezeigt. Darüberliegende Ebenen sind direkt anwählbar. Andere Ebenen können frei ausgewählt werden (~).

### Skizze
Die folgende Skizze zeigt eine erste Idee, wie der Kursfilter aus Sicht der PBS aussehen könnte:
<img src="https://user-images.githubusercontent.com/1799621/94462172-66caa200-01bb-11eb-8886-ae5c87567ea0.jpg" alt="kursfilter Skizze" width="60" height="39">

**Comment by nchiapol** [comment]
Vielen Dank für die Anfrage und Sorry für die lange Reaktionszeit. 
Von Seiten Cevi war das bisher kein dringendes Anliegen.
Wir finden den Vorschlag aber grundsätzlich gut und unterstützen eine Implementation im Youth-Wagon.

**Comment by anna-s-jubla** [comment]
Vielen Dank für die Anfrage. Für uns ist diese Erweiterung denkbar. Ich möchte dies jedoch zuerst noch mit der Fachgruppe anschauen und diskutieren (wir treffen uns am 9. November). Ich melde mich anschliessend noch einmal.

**Comment by amaierhofer** [comment]
- Kurskategorieren, Zuordnung zu Kursart (5h) 
- Anpassung der Navigation, Nesting (5h)
- Navigation Ebenen (5h)
- Filter Quartal (8h), Kursart (1h), Freie Plätze (3h)

**Comment by ninfaj** [comment]
Hier wäre eine grobe Skizze wie das aussehen / funktionieren könnte:
![image](https://user-images.githubusercontent.com/157533/102495082-f292f280-4075-11eb-962b-73ce87eb93ac.png)

**Comment by Michael-Schaer** [comment]
Merci für das tolle Mockup! Ein paar Punkte, die uns aufgefallen sind:

## Selectbox "Ebene"
- Wenn ich einen Kantonalverband aufklappe, sollten darunterliegende Ebenen (Regionen und Abteilungen) zur Auswahl angezeigt werden. Unter den Regionen dann auch die Abteilungen
- Ein Minuszeichen könnte anzeigen, dass eine Teilmenge der untergeordneten Gruppen ausgewählt ist
- Die Suche ist super!

## Auswahl Jahreszeit / Jahre
Hier fehlt die Anforderung, dass man beispielsweise 2020:Winter und 2021:Frühling kombinieren kann. Gibt es eine Darstellung, die diese Einstellung erlauben würde? Gleichzeitig sollte es auch möglich sein, ältere Kurse zu finden (z.B. bis zu 4 Jahre zurück). 

## Defaults
Ev. wäre ein Button "Standardeinstellungen" hilfreich, um zurück zu den Voreinstellungen zu kommen.

Wir stellen uns folgende Defaults vor:
**Ebene** -> Meine Hauptebene
**Saison** -> Die nächsten 4 "Quartale" (Jahreszeiten)
**Status** -> "Zur Anmeldung offen"

**Comment by chrusu** [comment]
Hey Michael, vielen Dank für deine Inputs, hier noch ein paar Überlegungen unsererseits
### Selectbox "Ebene"
Das sind super Inputs und ich werde mit den Entwicklern schauen, ob dies im gegebenen Zeitrahmen möglich ist. Ich werde mich diesbezüglich wieder bei dir melden. Wir finden auf alle Fälle eine Lösung.

### Auswahl Jahreszeit / Jahre
Bezüglich der Auswahl von Jahreszeit/Jahre haben wir uns noch etwa die Köpfe zerbrochen und fragen uns, ob ein klassischer Datepicker (mit Date-Range-Funktion, Standardmässig wären dann die nächsten 12 Monate ausgewählt) nicht die bessere Funktionalität darstellt. Wir sehen darin folgende Vorteile:
- Bekanntes Pattern --> Die User kennen das Prinzip von diversen anderen Web-Applikationen und finden sich schnell zurecht.
- Grössere Flexibilität --> Der Benutzer kann genauer einstellen, welchen Zeitraum das ihn interessiert
- Keine Missverständnisse --> Was genau bedeutet Frühling? Wann hört der Sommer auf? etc.
Falls es aber gute Gründe für eine Auswahl nach Jahreszeit/Jahren gibt, bilden wir dies natürlich gerne so ab wie gewünscht.
![datepicker](https://user-images.githubusercontent.com/17568539/103070941-ee5d5c80-45c2-11eb-8964-13c3b478d5c5.png)

**Comment by Michael-Schaer** [comment]
Danke für den Vorschlag. Der Date-Picker ist sicher die einfachere Lösung, die auch ziemlich universell und ausserhalb der PBS sinn macht. Für mich stimmt das so.

**Comment by chrusu** [comment]
Die Anforderungen wurden im Issue #1152 zusammengefasst
