### ISSUE TITLE
OAUTH: Layout der OAuth-Dialoge (2d)

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1044]
### Hintergrund
Am letzten Hackathon haben wir die OAuth-Dialoge unter die Lupe genommen. Wir haben dabei zwei Unschönheiten gefunden:
- Die Login-Seite fürs OAuth sieht genau gleich aus wie die übliche MiData-Login-Seite. Anwender*innen verstehen womöglich nicht, warum sie auf die MiData-Loginseite verweisen werden.
- Die Oauth-Login-Seite enthält keinen Hinweis über das Ziel bzw. die darauffolgende Weiterleitung

### Lösungsansatz
Um das Benutzer-Erlebnis zu verbessern, stellen wir uns folgende Anpassung vor:
- Eigenes Layout für die Dialoge "OAuth Login" und "OAuth Autorisierung" 
- Unnötige Elemente aus dem Dialog entfernen (Menu, Suche, Info "Die Daten in der Mitgliederdatenbank dürfen nur...")
- Erwähnung der Ziel-Applikation beim OAuth Login
- Hinweis "Mit MiData einloggen"
- Optional: Logo pro OAuth-App hinterlegen können

### Skizze
Die Dialoge könnten angelehnt an bekannte Dienste von Google oder Microsoft werden: 

**OAuth Login**
![OAuth-Login](https://user-images.githubusercontent.com/1799621/95092156-9df30300-0727-11eb-96a3-12719fc40da3.jpg)

**OAuth Autorisierung**
![OAuth-Auth](https://user-images.githubusercontent.com/1799621/95092183-a64b3e00-0727-11eb-9250-a6e433ed0035.jpg)

## Techspec
- Neue OAuth Login Seite mit geforderten Layout und Informationen, redirect auf basis HTTP_REFERER (8h)
- Customization bestehender OAuth Authorizations Seite (5h)
- Icon für OAuth Application (3h)

**Comment by amaierhofer** [comment]
- Neue OAuth Login Seite mit geforderten Layout und Informationen, redirect auf basis `HTTP_REFERER` (8h)
- Customization bestehender OAuth Authorizations Seite (5h)
- Icon für OAuth Application (3h)

**Comment by Michael-Schaer** [comment]
Hallo Matthias

Cool, ich freue mich zu testen, wie die neuen Seiten aussehen!

Ich habe kurz versucht, von unserem Portal mit dem Testsystem MiData einzuloggen. Dabei erhalte ich jetzt eine Fehlermeldung. Ist das ein Zufall oder hat das etwas mit dem Issue hier zu tun? ;)

![image](https://user-images.githubusercontent.com/1799621/107767101-c5408900-6d34-11eb-829a-e7aabe3bd2df.png)

Problem nachstellen:
 - https://pbsportal.itds-test.ch öffnen
 - Login über MiData wählen

**Comment by carlobeltrame** [comment]
Ich kann das Problem bestätigen. Es tritt nur auf, wenn man auf hitobito noch nicht eingeloggt ist, und sich dann versucht via hitobito OAuth bei einer (beliebigen) externen Applikation anzumelden. Ist man in hitobito bereits zuvor eingeloggt, tritt das Problem nicht auf.

Dem Fehler der in den Logs auftaucht (seltsamerweise nicht in Sentry) zufolge reicht es möglicherweise, wenn wir in https://github.com/hitobito/hitobito/blob/master/app/views/devise/sessions/_oauth_info.html.haml#L8 `Doorkeeper::Application` durch `Oauth::Application` ersetzen. Ich konnte das aber noch nicht testen.

**Comment by kronn** [comment]
Ich schaue es mir an.

**Comment by kronn** [comment]
Danke, @Michael-Schaer für den ersten Test und die Fehlermeldung. Danke auch an @carlobeltrame für den Hinweis für die Lösung.

Der technische Hintergrund hat mich kurz zum Lachen gebracht. Sowohl `Doorkeeper::Application` wie auch `Oauth::Application` nutzen die gleichen Daten aus der Datenbank. Da aber der Logo-Upload bei der `Oauth::Application` eingebaut ist, kann auch nur diese das Logo wieder gut darstellen. Schon spannend, wie die gleichen Daten in anderen Kontexten sinnvoll sind oder auch nicht.

Die Integration ist aktualisiert, für mich funktioniert der Login jetzt.

**Comment by Michael-Schaer** [comment]
Super, merci für das schnelle Beheben! Sieht richtig chic aus jetzt!
