### ISSUE TITLE
Sichtbarkeit von Anlässen, Kursen und Lagern

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1047]
### Glossar 
| Begriff             | Erklärung                                     |
|---|---|
| Events              | Anlässe, Kurse und Lager (alle drei)          |
| Eine Rolle kann […] sehen | Benutzer*innen mit der Rolle können […] sehen |

### Hintergrund
Das Dokument „Datennutzung“ der PBS beginnt mit dem Leitsatz „So viel wie nötig, so wenig wie möglich“. Dieses Prinzip ist auch im Berechtigungssystem von Hitobito wiederzuerkennen. So haben beispielsweise die Gruppenleiter*innen nur Zugriff auf die Mitglieder ihrer eigenen Gruppe. Oder eine Person im Kanton «A» sieht keine Daten innerhalb des Kantons «B».

Dieses Grundprinzip wurde bei Anlässen, Kursen und Lagern jedoch nicht übernommen. Stattdessen sind alle Events grundsätzlich für alle Benutzer*innen der Datenbank sichtbar. Dieses Verhalten stimmt nicht mit dem Leitsatz der Datennutzung überein. Deshalb erhofft sich die PBS, durch diese Anpassung die Berechtigungen ans restliche Berechtigungssystem anzugleichen.

Die Personendaten der Teilnehmenden selber sind mittlerweile besser geschützt. Diese sollen nicht Thema dieses Issues sein, sondern zu einem späteren Zeitpunkt wieder aufgegriffen werden.

#### Kompatibilität innerhalb des Youth-Wagons
Die Änderung wird zwangsläufig auch den «Youth-Wagon» und damit die weiteren Jugendverbände betreffen. Damit das neue System für alle Kunden weiterhin funktioniert, soll die Sichtbarkeit in der ganzen Datenbank wahlweise pro Anlass und Lager eingeschaltet werden können. So ist es auf Wunsch auch möglich, das bestehende Verhalten grösstenteils beizubehalten.

### Ist-Zustand
Aktuell sind alle Events (Anlässe, Kurse und Lager) für alle Benutzer*innen der Mitgliederdatenbank sichtbar. 

### Soll-Zustand
Rollen mit Lese- oder Schreibrechten auf einer Ebene oder Gruppe sollen keine Events «neben ihrer Ebene» sehen können. «Neben der Ebene» bedeutet für eine Abteilung eine andere Abteilung, für eine Region eine andere Region und für einen Kanton einen anderen Kanton. Beispiel: Ein*e Adressverwalter*in eines Kantons soll keine Events eines anderen Kantons mehr sehen. Die Events des eigenen Kantons sollen aber weiterhin sichtbar bleiben.

Für Ebenen unterhalb der eigenen Ebene gibt es ebenfalls eine Anpassung: Rollen mit «group_read» oder «group_full» Berechtigung sollen nur noch die Events der eigenen Gruppe sehen. Rollen mit «layer_and_below_read» oder «layer_and_below_full» sollen weiterhin die Events unterhalb der eigenen Ebene sehen können.

Die Berechtigungen werden also entsprechend ihrem Namen eingesetzt. «Layer and below» heisst, dass der Zugriff auch unterhalb der Ebene möglich ist. «Group» heisst, dass sich die Berechtigung auf diese Gruppe beschränkt.

Als Ergänzung soll ein Flag "sichtbar für die ganze Datenbank" auf dem Event eingeführt werden. Wird dieses Flag aktiviert, so entspricht die Sichtbarkeit dem heutigen Verhalten. Der Event ist dann also im ganzen System für alle Personen sichtbar.

#### Kurse
Für Kurse gelten dieselben Bestimmungen wie für Anlässe und Lager. Auch technisch soll die Sichtbarkeit gleich umgesetzt werden wie bei Anlässen und Lagern. 

In Zusammenhang mit dem Ausbildungsmodell müssen Kurse bei der PBS für alle potentiellen Teilnehmenden sichtbar sein. Entsprechend muss eine kleine Anpassung vorgenommen werden: Das Flag "sichtbar für die ganze Datenbank" soll im UI beim Erstellen/Bearbeiten eines Kurses versteckt werden und immer auf "ja/sichtbar" gesetzt sein. Auch in der Datenmigration sollen die bestehenden Kurse das Flag erhalten.

#### Spezifische Rollen
Mit der Änderung verlieren die aktuellen Rollen mit "group_read" den Zugriff auf Lager und Anlässe unterhalb ihrer Ebene. Bei der PBS gibt es einige Rollen, die aber weiterhin genau diesen Zugriff brauchen. Die entsprechenden Rollen sollen in einer Liste geführt werden, damit sie im Rahmen dieser Änderung mit «layer_and_below_read» ausgestattet werden können.

####  Eigene Teilnahme
Anlässe und Lager, an denen ich teilnehme: Es muss gewährleistet werden, dass ich in jedem Fall die Anlässe und Lager sehen kann, zu denen ich hinzugefügt wurde oder mich zuvor angemeldet hatte.

#### Sichtbarkeit unter Abteilungen mit engem Austausch
Bei der PBS gibt es häufig einen Austausch zwischen zwei Abteilungen der gleichen Region. Damit diese Abteilungen auch Anlässe oder Lager austauschen können, soll eine klassische «Link-Sharing» Funktion eingebaut werden. Über den geteilten Link können die Event-Angaben eingesehen werden und eine Anmeldung ist möglich. Die Links enthalten einen zufälligen Hash, damit sie nicht berechnet werden können.

### Abnahmekriterien
- [x] Kurse sind weiterhin in der ganzen Datenbank sichtbar
- [x] Rollen mit Lese- oder Schreibrechten sehen keine Anlässe und Lager neben ihrer Ebene
- [x] Rollen mit Berechtigung auf der Gruppe sollen keine Anlässe und Lager unterhalb ihrer Ebene mehr sehen
- [x] Rollen mit Berechtigung auf der Ebene und darunter sollen weiterhin Anlässe und Lager unterhalb ihrer Ebene sehen
- [x] Anlässe und Lager können per Checkbox für die ganze Datenbank sichtbar gemacht werden
- [x] Die Standardeinstellung für die Sichtbarkeit in der ganzen Datenbank kann konfigurativ ein/aus geschaltet werden
- [x] Die Sichtbarkeit in der ganzen Datenbank wird in der Migration mit einbezogen (wahlweise altes oder neues Verhalten für bestehende Anlässe/Lager)
- [x] Definierte Rollen werden mit «layer_and_below_read» ergänzt
- [x] Events, an denen ich teilnehme, sind in jedem Fall für mich sichtbar
- [x] Events können per Link geteilt werden (Sichtbarkeit und Anmeldung beachten)  / (Leute können per Link mit Hash-Token an einem Kurs teilnehmen, welchen sie sonst mit den neuen Berechtigungsregeln nicht sehen könnten)

## Techspec
- [x] Neues Datenbankfeld, bei Kursen fixer Wert (Flag "Sichtbar für die ganze Datenbank" Boolean)
- [x] Specs für die neuen Abnahmekriterien erstellen und anpassen (Tests)
- [x] Änderungen an Abilities
- [x] Globale Sichtbarkeit auf Event-Ebene einstellbar machen (CRUD, MVC, Specs)
- [x] In verschiedenen Wagons Rollen anpassen
- [x] Link-Sharing ähnlich wie bei Kalender-Feed
- [x] Wagons testen (insbesondere die Wagons mit eigenen Event-Unterklassen)
  - SBV
  - SJAS
  - ... ?
- [x] Kurse nicht als Ausnahme behandeln, sondern **für die PBS** in der DB auf "global sichtbar" setzn

**Comment by nchiapol** [comment]
Die Neuerung macht in meinen Augen völlig Sinn und sollte auch bei uns keine Probleme verursachen. Vielen Dank fürs Ausarbeiten des Vorschlags.

**Comment by anna-s-jubla** [comment]
Vielen Dank für die Anfrage. Für uns ist diese Erweiterung denkbar. Ich möchte dies jedoch zuerst noch mit der Fachgruppe anschauen und diskutieren (wir treffen uns am 9. November). Ich melde mich anschliessend noch einmal.

**Comment by carlobeltrame** [comment]
Schätzung:
* Neues Datenbankfeld, bei Kursen fixer Wert: 3h
* Änderungen an Abilities: 4h
* In verschiedenen Wagons Rollen anpassen: 2h
* Link-Sharing ähnlich wie bei Kalender-Feed: 3h
* Bestehende Specs anpassen und neue schreiben: 6h

Offene Fragen / Ergänzungen
1. PBS Lagerhierarchien für abteilungsübergreifende Lager -> soll die Suche nach übergeordnetem Lager so belassen werde wie bisher? Wenn ja sind Anlässe im Status "Erstellt", welche Unterlager zulassen, weiterhin via diese Suche sichtbar.
1. Für spezielle Personenfelder wie LKB, Coach, AL auf einem Anlass sollte ein Anlass / Kurs / Lager auch sichtbar bleiben nehme ich an.
1. Umsetzung wo? @olibrian Falls im Core, müsste man mit anderen Wagons abklären, mir fällt gerade SBV (Musikfeste) ein.

**Comment by chrusu** [comment]
Antwort zu 3: Tendenziell im Core machen, es sei denn es spricht programmiertechnisch etwas dagegen. (SBV)

**Comment by kronn** [comment]
@Michael-Schaer Es ist die Rede von "bestimmten Rollen", die Zugriff benötigen. Die Liste der aktuellen Rollen ist im README der jeweiligen Wagons ersichtlich, für die PBS also hier: https://github.com/hitobito/hitobito_pbs/blob/master/README.md

Leider ist mir nicht klar, welche Rollen jetzt angepasst werden sollen. So, wie das Feature umgesetzt ist, kann man dies noch anpassen, wenn man das Feature für den jeweiligen Wagon aktiviert.

**Comment by Michael-Schaer** [comment]
Ja, die sind nur schwer zu erraten ;) Ich habe dabei an die folgenden gedacht:

```
Bund: Mitglied Krisenteam
Bund: Grossanlass Coach
Bund: Mediensprecher
KV: Leiterkursbetreuer
KV: Verantwortlicher Betreuung
KV: Verantwortlicher Lagermeldung
KV: Verantwortlicher Krisenteam
KV: Mitglied Krisenteam
KV: Mediensprecher
Region: Leiterkursbetreuer
Region: Verantwortlicher Betreuung
Region: Verantwortlicher Lagermeldung
Region: Verantwortlicher Krisenteam
Region: Mitglied Krisenteam
Region: Mediensprecher

```
