### ISSUE TITLE
Abmeldung von Anlass ermöglichen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#105]
## SOLL:

- Grüne Info erscheint immer
- Button zum Abmelden erscheint nur, wenn die Anmeldung offen ist und das Anmeldezeitfenster offen ist.
- Es sollen die gleichen Personen über Abmeldung informiert werden, wie über Anmeldung
- die Participation wird gelöscht (es gibt keine abgemeldet Status)
- pro Anlass kann bei den Anmeldeoptionen per Checkbox konfiguriert werden, ob sich Personen auch abmelden dürfen. Default:  Nicht erlaubt
- auf dem Eventtyp (im Code) legen wir fest, ob das überhaupt möglich ist.

![](https://wearecube.mybalsamiq.com/mockups/5141063.png)
[edit](https://wearecube.mybalsamiq.com/projects/hitobito/edit/105%20von%20Anlass%20abmelden)

### original

---

Originalquelle: http://feedback.jubla.ch/issues/4

PDF im Anhang ist für mich nicht zugänglich. Ich nehme an, es geht um die Möglichkeit einer Abmeldung für einen Event, wo ich mich angemeldet habe.

Bitte ergänzen.

**Comment by Oli4Berger** [comment]
Hier der Link zur Originalquelle auf dem alten Feedbacktool. pdf war im Prinzip diese Seite http://jubla_db.idea.informer.com/proj/?ia=66474

**Comment by RolandStuder** [comment]
Um Bild ergänzt und ein paar Details, passt das so?

## SOLL:

- Grüne Info erscheint immer
- Button zum Abmelden erscheint nur, wenn die Anmeldung offen ist und das Anmeldezeitfenster offen ist.
- Personen mit Permission :event-full erhalten per E-Mail eine Information zur Abmeldung. (Hauptleiter und Hilfleiter)
- die Participation wird gelöscht (es gibt keine abgemeldet Status)

![](https://wearecube.mybalsamiq.com/mockups/5141063.png)
[edit](https://wearecube.mybalsamiq.com/projects/hitobito/edit/105%20von%20Anlass%20abmelden)

**Comment by Oli4Berger** [comment]
Finde ich eine gute Lösung.

**Comment by codez** [comment]
Wie verhält sich dies bei den verschiedenen Event Typen der verschiedenen Wagons? Gilt das nur für einfache Events, ohne Kurse und Lager?

**Comment by RolandStuder** [comment]
Ergänzung:

- pro Anlass kann bei den Anmeldeoptionen per Checkbox konfiguriert werden, ob sich Personen auch abmelden dürfen. Default:  Nicht erlaubt
- auf dem Eventtyp (im Code) legen wir fest, ob das überhaupt möglich ist.

**Comment by fossil12** [comment]
Da es sowieso optional ist würde ich es auch für Lager & Kurse anbieten, obwohl ich mir nicht sicher bin ob es da einen Anwendungsfall gibt. Falls dies nicht viel mehr (oder sogar weniger?) Programmieraufwand ist.

**Comment by RolandStuder** [comment]
@fossil12  Problem ist, dass am Kurs vielleicht zu viel dran hängt, das ist das Anmeldeverfahren etwas komplexer (da gibt es ja die Unterscheidung Anmeldung / Teilnahme). Auf Lager sollte es kein Problem sein.

Deshalb hatte ich gedacht, es vielleicht besser, das im Code abzubilden auf EventTyp. Dann können wir das z. B. bei Kursen abstellen, falls es damit Probleme gibt. Aber wenn Zeilenwerk kein Problem sieht, können wir es einfach für alle Events zulassen. Wichtig ist zu sehen, ob wir auch beim Kurs jeweils adäquat Personen darüber benachrichtigen können.

Wir schauen es an.

**Comment by codez** [comment]
> Es sollen die gleichen Personen über Abmeldung informiert werden, wie über Anmeldung

Im Core wird nur der TN selbst über die Anmeldung informiert. Dasselbe also auch für die Abmeldung.
Bei der PBS Lagern werden ebenfalls die Lagerleiter informiert.

**Comment by codez** [comment]
Soweit implementiert. PBS Lager haben bereits eine sehr ähnliche Funktionalität, dort habe ich diese hier deaktiviert. Sonst ist sie überall aktiv, auch bei den Kursen. Es wird überall auch einzig ein Bestätigungs E-Mail an den TN selbst geschrieben.

Die ganzen An-/Abmeldeoptionen/-Fristen/Status/Rollen/Anlasstyp/Wagons Varianten sind inzwischen dermassen vielfältig, dass daran kaum mehr Erweiterungen vorgenommen werden können, ohne das irgendwelche Spezialfälle vergessen gehen. Entsprechend muss dieses Issue in möglichst vielen Konstellationen getestet werden.

**Comment by RolandStuder** [comment]
@codez Danke für den Hinweis. Grundsätzlich müssen wir bei weiteren Änderungen wohl schauen, dass wir stärker konsolidieren und Dinge eher konfigurierbar machen.
