### ISSUE TITLE
Frei definierbare Felder auf Gruppen

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#1054]
Für den generic Wagon sollen auf Gruppen zusätzliche Felder frei definiert werden können. Mit welchem Aufwand ist da grob zu rechnen?

- Platzieren der Felder im Info-Tab, unterhalb "Social Media"
- Labels in Einstellungen mehrsprachig verwalten können
- Anzeige der Felder in der Übersicht bei "Weitere Angaben"
- Miteinbezug in CSV Untergruppen-Auswertung auf den verschiedenen Ebenen

**Comment by olibrian** [comment]
Duplicate: https://github.com/hitobito/hitobito/issues/338
