### ISSUE TITLE
SUISA-Modul separat verfügbar machen

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#1055]
Was würde es in etwa an Aufwand bedeuten, den SUISA-Teil aus dem SBV-Wagon separat verfügbar zu machen?

- als Add-on auf einer Multitenant-Instanz
- als separate Instanz (allenfalls auch interessant für die SUISA?)

Ich denke, es gibt bei beiden Varianten noch die eine oder andere Frage zu klären. Ich brauche erstmal eine grobe Einschätzung, was die Trennung des Codes bedeuten würde.

**Comment by olibrian** [comment]
Accordeon.ch setzt auf die Lösung vom SBV.
