### ISSUE TITLE
Anlässe > Tab "Anmeldungen" erzeugt 500-Error

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito#1059]
Ruft man bei einem Anlass den Tab "Anmeldungen" auf, erzeugt dies sowohl auf dem Produktiv- als auch auf dem Integrationssystem einen 500er Error (Bsp.: https://db.windband.ch/de/groups/1/events/716 oder https://sbv.puzzle.ch/de/groups/1/events/50)

**Comment by olibrian** [comment]
Danke @betsim für die Rückmeldung. Sowohl auf Events wie Kurse gibt es ein `group_participations`. Beides führt zu einem Fehler.
