### ISSUE TITLE
Beziehungen bei Abo berücksichtigen können

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#106]
Originalissue: Intelligente Listen bei Abos http://feedback.jubla.ch/issues/5

IST: Leider ist es nicht möglich Familienbeziehung (Kinder - Eltern) abzubilden. Es ist daher auch nicht möglich eine Adressliste für Ettiketten zu drucken, mit welcher pro Haushalt nur ein Brief geschickt wird. (Schar Wunsch)

SOLL: Aus unserer Sicht, wäre es mega praktisch wenn die Jubla DB eine Funktion hätte um bei einem Scharversand die Geschwister zusammen zu nehmen, so dass der Brief in jeden Haushalt nur einmal kommt…

## Offene Fragen:

- Die Beziehungen, die wir in hitobito theoretisch abbilden können, sind (hier nicht als Familienverhältnisse zu verstehen, sonder nur als logische Verknüpfungen), Parent - Child (1-N), Sibling (N), Relation (N-N). In jedem Fall müssten wir eine sinnvolle Auswahl anbieten können.
- Sollen die Beziehungen nur als Filter dienen, damit Mehrfachversänden vermieden werden können, indem man diese zusammenfasst? Das ist wohl geht ist es wohl relativ gut machbar. Wenn Personen zusätzlich in den Versand aufgrund der Beziehung eingeschlossen werden sollen, wird es sehr komplex. Ich werde versuchen, dies mit dem einen oder anderen Beispiel noch etwas besser zu erklären.
- Komplexität der Queries: Die Aboanfragen sind jetzt schon relativ komplex und werden durch das addieren von Tagging Filter auf die Abos nochmals komplexer. Hier haben wir allenfalls Issues mit der Performance.
- Wie soll das im UI dargestellt werden?

**Comment by RolandStuder** [comment]
- Was soll übrigens passieren wenn sich die Adressen unterscheiden?
- Was passiert mit den restlichen Daten vom Aboexport wo wir vielleicht unterschiede haben zwischen den Personen?

**Comment by fossil12** [comment]
Das erkennen von doppelten Adressen bei der Erzeugung von Etiketten ist schon Teil von Hitobito und wurde mit PR #97 verbessert. Da ich finde dass bei verschiednen Adressen kein Zusammenführen stattfinden soll, müsste die aktuelle Lösung die meisten Bedürfnisse schon abdecken.

Ich würde bei allen anderen Exports die Daten sowieso nicht zusammenführen, ausser wenn die gleiche Email Adresse vorhanden ist, da so oder so es keinen Sinn macht die gleiche Mail mehrere male an die gleiche Adresse zu schicken.

**Comment by RolandStuder** [comment]
Die Duplikatserkennung in Nummer #97 deckt nicht ganz alle Fälle ab, und vor allem funktioniert sie nur für den Etikettenexport. Wenn ich selbst etwas machen will mit einem CSV, dann klappt das nicht. Man könnte aber die bestehende Möglichkeit auf den Adresslistenexport ausweiten.

**Comment by fossil12** [comment]
@RolandStuder Das stimmt, aber wie schon erwähnt finde ich, dass es keine Duplikatserkennung für andere Exports als Adressetiketten braucht. Ich würde erwarten, dass eine exportiere CSV Liste alle Personen einzeln aufführt. Wobei die Duplikatserkennung ja ein extra Haken ist. Dann würde es vielleicht doch Sinn machen dies dort auch optional anzubieten.

**Comment by nchiapol** [comment]
Da die Duplikatserkennung optional ist, würden wir sie bei allen Exporten begrüssen. Wir haben einen konkreten Anwendungsfall beim Versand unserer Mitgliederzeitschrift. Dort senden wir die Adressen als Tabelle an die Druckerei.

Allgemein teile ich die Einschätzung von fossil12, dass die aktuelle Implementation die Bedürfnisse weitestgehend abdeckt. Einzig beim Vergleich der Adresse wäre es evtl. praktisch wenn "strasse" und "str." als identisch erkannt würden.

**Comment by RolandStuder** [comment]
Mit Haushalten abbilden #218 Sind hier die eigentlichen Bedürfnisse abgedeckt.Ich schliesse es deshalb.
