### ISSUE TITLE
Lagermeldung Formular - Seitenabstände

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1061]
Im PDF für die Lagermeldung werden in manchen Fällen sehr viele Seitenabstände eingefügt. Bei der Entsprechenden Person sehe ich keine aussergewöhnlich lange Adresse oder ähnlich. 
Können die Seitenabstände etwas optimiert werden?

Beispiel:
http://db.scout.ch/groups/238/events/13705/camp_application

**Comment by diegosteiner** [comment]
@Michael-Schaer dafür bin vermutlich ich verantwortlich. Kannst du mir noch ein Beispiel schicken, welches ich einsehen kann (z.B. auf der Testumgebung oder als PDF)?

**Comment by Michael-Schaer** [comment]
Lieber Filou

Merci für deinen Fix und merci @kronn fürs Mergen!

Ich habe heute ein paar Lager auf der Testumgebung durchgeklickt. Ich habe nur in einem eher seltenen Fall noch PDFs mit überflüssigen Seitenumbrüchen gefunden, und da sind es jetzt maximal vier Seiten pro PDF, also deutlich besser als vorher.
 
Konkret ist das bei Lagern, die keine Lagerleiter*in unter den Teilnehmenden eingetragen haben. Also nicht beim Tab "Betreuung" sondern "Teilnehmende".

Hier ein Beispiel:
Keine Lagerleiter*in: https://pbs.puzzle.ch/de/groups/69/events/1331
Eine Lagerleiter*in: https://pbs.puzzle.ch/de/groups/69/events/1526
