### ISSUE TITLE
Export als CSV/Excel schlägt fehl bei Anlässen

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito#1070]
**Produktivsystem**
Bei Anlässen schlägt neuerdings der Export als CSV oder Excel fehl, d.h. die Meldung "Die Downloads werden vorbereitet, bitte warten." erscheint zwar, aber der Download startet nie. Der Export als PDF, Etiketten und Email-Adressen funktioniert.

**Integrationsumgebung**
Auf der Integrationsumgebung sbv.puzzle.ch funktioniert der Export.

**Comment by kronn** [comment]
Leider konnte ich das Problem nicht nachvollziehen. Bei welchem Verein oder welchem Anlass funktioniert es denn nicht?

Ich habe die folgenden Exporte stichprobenartig geprüft: 
- Liste der Anlässe einer Gruppe (und den Untergruppen) als CSV
- Teilnehmer eines Anlasses als CSV

**Comment by betsim** [comment]
Das Problem ist zusammen/gleichzeitig mit #1071 gelöst worden. Betroffen waren war u.a. die Anmeldung NJBO 2021.

**Comment by kronn** [comment]
danke für die Rückmeldung.
