### ISSUE TITLE
Mailinglisten SBV funktionieren nicht

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito#1071]
E-Mails an Mailinglisten SBV werden nicht mehr ausgeliefert. Es erfolgt - zumindest zeitnah - auch keine Fehlermeldung. Die Mailinglisten funktionierten bis vor wenigen Tagen noch einwandfrei.

**Comment by kronn** [comment]
Das Problem wurde behoben. Die Mailinglisten sollte jetzt wieder funktoinieren. Nach meinem Monitoring sind derzeit alle Mails bearbeitet.
