### ISSUE TITLE
 Umbenennung NDBJS -> NDS

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1075]
Das Baspo hat offenbar das Naming für die NDBJS geändert. Siehe z.B. auf dieser Seite: https://www.jugendundsport.ch/de/infos-fuer/eltern.html

Dazu die folgenden beiden PRs:
https://github.com/hitobito/hitobito_youth/pull/11
https://github.com/hitobito/hitobito_pbs/pull/180

Könnt ihr das so mergen? FR und IT würde ich dann im Transifex nachtragen.

**Comment by kronn** [comment]
@Michael-Schaer ich habe in den italienischen Übersetzungen "NDBJS" zu "NDS" geändert. Im Französischen haben ich die Zeichen "NDBJS" nicht gefunden. Die beiden PRs sind gemerged.
