### ISSUE TITLE
Eigenes CSS / Layoutfarben für Kunden unabhängig vom Wagon definierbar

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#108]
Organisationen sollen selbst einige SASS-Variablen festlegen können, welche unabhängig vom Wagon sind. Eine Lösung, wo diese in der Umgebung und nicht in der DB definiert ist, ist auch denkbar.
- Einige Farben
- Fonts

Evtl. muss dafür das allgemeine CSS teilweise etwas überarbeitet werden. Temporär wäre auch eine Lösung denkbar, wo wir direkt CSS hinterlegen. Der Kunde muss das im ersten Schritt noch nicht direkt selbst machen können. Aber wir müssen es vom Wagon entkoppeln können. 
## Fragen:
- Ist ein Kompilieren von SASS at runtime überhaupt sinnvoll möglich? Also können wir das im Admin-Bereich lösen?
- Ist das vielleicht über Environment Variablen einfach lösbar?
- Bessere Lösungen?

Bitte Überarbeitung SASS separat vom Rest schätzen.

**Comment by RolandStuder** [comment]
Einige Referenzen für eine mögliche technische Umsetzung:

- http://matteodepalo.github.io/blog/2013/01/31/how-to-create-custom-stylesheets-dynamically-with-rails-and-sass/
- http://stackoverflow.com/a/4729522/2037537

**Comment by codez** [comment]
Das sieht ja abenteurlich aus. Habe spontan auch keine bessere Idee.

Estimate:
* Umstellung SASS Kompilierung von Jenkins auf Server: 2-4PT
* SASS Variablen im Admin Bereich verwalten und in File schreiben: 0.5-1PT
* Zusätzliches SASS für Fonts, ... (Validierung nötig?): 1PT 

Überarbeitung bestehendes CSS kannst du wohl besser schätzen als ich.

**Comment by RolandStuder** [comment]
@KunoKunz Weiss nicht ob das ein Thema ist, Theming ist sicher nicht prioritär, wenn es um Konfigurierbarkeit geht, ich schliesse daher das Issue.
