### ISSUE TITLE
Alternative zu Travis-ci.org

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1088]
**Fact:** 
travis-ci.org will be officially closed down completely no later than December 31st, 2020

**Varianten:**
* Migration zu travis-ci.com (Free for open source. )
* Alternative evaluieren

**Comment by kronn** [comment]
Man könnte Github-Actions analog zu https://github.com/puzzle/puzzletime anschauen.

**Comment by carlobeltrame** [comment]
Mir gefällt die Vorstellung, das Puzzle-weit ähnlich zu machen.

GitHub Actions haben aktuell in der gratis-Version ein [Limit](https://github.com/pricing) von 2000 min pro Monat. Ein durchlaufender Build von hitobito core auf Travis dauert aktuell ca. 12 Minuten (weniger wenns früher failt), und seit 3 Monaten zähle ich im Core ca. 123 Builds pro Monat, also brauchen wir schätzungsweise 1467 Minuten pro Monat für den Core. Das würde also aktuell gerade noch ausreichen. Dann haben wir noch die Wagons, aber die haben weniger lange Builds als der Core und das Limit ist soweit ich verstehe pro Repository.

Es gibt auch alternative CI-Runner ohne Minuten-Limits (z.B. [Cirrus CI](https://cirrus-ci.org/faq/#are-there-any-limits)), aber solche würde ich erst vom Techboard absegnen lassen.

**Comment by maede97** [comment]
Für public repos ist Github Actions komplett gratis. ;-)

**Comment by olibrian** [comment]
Aktuell haben wir zu travis-ci.com migriert.
