### ISSUE TITLE
QR-Code-Rechnung validiert ausgeblendetes Feld Kontonummer

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito#1095]
**IST**
Ändert man den Einzahlungsschein auf "QR Rechnung" in den Rechnungseinstellungen, werden dafür nicht benötigte Felder ausgeblendet (z.B. Kontonummer) – beim Speichern ("Rechnungseinstellungen aktualisieren") wird dann aber das Feld "Kontonummer" validiert und das Speichern scheitert mit einer inkorrekten Prüfziffer:

![image002](https://user-images.githubusercontent.com/1453303/100129631-12256980-2e82-11eb-9706-03b79d55f90e.jpg)

**SOLL**
Ausgeblendete Felder werden nicht validiert und ihr Inhalt ignoriert.

**Comment by amaierhofer** [comment]
Kann ich aktuell nicht reproduzieren. Scheint zwischenzeitlich behoben worden zu sein, wahrscheinlich im Zuge von #943.
