### ISSUE TITLE
Rechnungseinstellungen Feld "IBAN" als Pflichtfeld?

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito#1096]
**IST**
Zur Zeit ist das Feld "IBAN" als Pflichtfeld definiert, aber visuell nicht so ausgezeichnet (* fehlt). Damit ist es aber nicht möglich, die Zahlungsinformationen zu löschen (z.B. wenn man zu Testzwecken eine fremde IBAN eingesetzt hat, kann man diese nicht mehr löschen, sondern nur durch eine andere gültige IBAN ersetzen).

![Bildschirmfoto 2020-11-23 um 22 14 19](https://user-images.githubusercontent.com/1453303/100130602-333a8a00-2e83-11eb-9be6-cdfaa6e767d5.png)

**SOLL**
Sinnvollerweise ist IBAN nur Pflicht, wenn auch ein Einzahlungsschein gewählt wurde (evtl. sogar nur, wenn QR Rechnung gewählt ist).

**Comment by amaierhofer** [comment]
IBAN ist nur Pflicht, wenn QR Rechnung ausgewählt wurde.
