### ISSUE TITLE
Anmeldungen nicht mehr anzeigen, wenn Event ohne Zuteilung vorbei ist

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#110]
aus: http://jubla_db.idea.informer.com/proj/?ia=66474

"Ausserdem löschen sich offene Anmeldungen nach dem Anlass nicht immer selber. Ich habe immer noch eine Anmeldung für einen Kurs offen, der schon längst stattgefunden hat. (Ich durfte wegen Überbelegung mit Externen nicht teilnehmen.)"

Kommt aus dem Issue: https://github.com/hitobito/hitobito/issues/105
## SOLL

Ist ein Event vorbei, für den eine Anmeldung vorliegt, sollte diese Anmeldung automatisch gelöscht werden, wenn das entsprechende Event vorbei ist

**Comment by fossil12** [comment]
Ich kann nicht genau nachvollziehen was hier falsch läuft. Ich finde, dass alle Events für die eine Person angemeldet ist auch nach dem Event noch mit der Person verknüpf sein sollten. Nur sollten diese nicht mer im "Profil" auf der Info Seite, sondern nur auf der Verlauf Seite erscheinen.

**Comment by RolandStuder** [comment]
Dieses Issue war inaktiv, falls das immer noch Thema ist, bitte zurückmelden.
