### ISSUE TITLE
Probleme mit HelpText bei der MT Umgebung

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito#1103]
ActionView::Template::Error: Mysql2::Error: Table 'kcbm.help_texts' doesn't exist bei https://kcbm.hitobito.com/de/users/password/new

Eventuell ein Problem  beim starten der Applikation oder nach dem Anlegen eines neuen Tenants? 

Scheint momentan nicht mehr aufzutreten

siehe
https://sentry.puzzle.ch/pitc/hitobito-backend/issues/21412

**Comment by olibrian** [comment]
Nicht reproduzierbar
