### ISSUE TITLE
Rechnungen an mehr als 50 Personen stellen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1105]
**Ausgangslage:**
Wenn in einer Gruppe z.B. https://desk.insieme.ch/de/groups/362/people?returning=true (569 Personen) eine Rechnung erstellt wird, wird nur für die ersten 50 Personen eine Rechnung generiert.
Möglicherweise hat dies mit der Pagination auf der Personenansicht zu tun.

**Soll**
Rechnung soll an alle Personen in der jeweiligen Gruppe erstellt werden.

**Comment by amaierhofer** [comment]
Ja, das liegt an dem Multiselect. Die Auswahl betrifft immer jeweils nur die erste Seite und ist für alle Aktionen gültig. Zur Verdeutlichung hier noch ein Screenshot. 

![screenshot_9](https://user-images.githubusercontent.com/180780/101597207-aea94900-39f6-11eb-9e57-6f2b0bb76dfe.png)

Ich kann mir 2 Use Cases bei dem Multiselect vorstellen: 

- Aktion auf der ganzen Liste (so wie eingangs in dem Ticket formuliert)
- Aktion auf mehreren (den meisten) Personen auf dieser Liste, wo ich zuerst alle anwähle und dann einzelnen Personen wieder abwählen 

@ninfaj hast du da noch Input? @olibrian wollen wir uns für einen der Use Cases fix entscheiden oder beide unterstützen. Falls ja, was wäre eine gute UI Ergänzung um alle Personen der Liste anzuwählen

**Comment by ninfaj** [comment]
Vermutlich würde ich beide Use Cases unterstützen.
Spontan wäre mein Vorschlag:
- mit der "Alle wählen" Checkbox werden alle sichtbaren Elemente auf dieser Seite auswählt
- hat es mehrere Seiten wird eine Meldung angzeigt, die mit einer Aktion erlaubt alle Elemente über mehrere Seiten auszuwählen
- sind alle Elemente über mehrere Seiten markiert, kann die Meldung wieder verschwinden (über die Anzeige 275 Personen markiert ist es dann klar) und die "Alle abwählen" Checkbox würde die komplette Selektion wieder aufheben

![Pagination select all](https://user-images.githubusercontent.com/157533/101732351-5e48ee80-3abd-11eb-9638-2c8c050a3f46.png)

**Comment by betsim** [comment]
+1 für den Vorschlg von @ninfaj  GMail macht das glaublich auch so.

**Comment by olibrian** [comment]
Ursprung des Issue war, wenn keine Personen selektiert sind und eine Rechnung generiert wird, werden auch nur die ersten 50 Einträge genommen.

**Comment by olibrian** [comment]
Wurde via #1112 geschlossen
