### ISSUE TITLE
Zahlungsinformation in QR-Rechnungen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1113]
**Ausgangslage**
Zahlungsinformation kann nicht mitgegeben werden:
Rechnung: 216501

Fehlermeldung:
![Screenshot from 2020-12-18 20-31-14](https://user-images.githubusercontent.com/9592347/102654024-2baf8d80-4170-11eb-91f6-eb62598dba46.png)

Verwendeter Validator: https://www.swiss-qr-invoice.org/

Ohne Eingabe der Zahlungsinformation scheint es zu funktionieren.

**Soll**
- [ ] Bei Eingabe von Zahlungsinfo sollte auch eine gültige Rechnung erstellt werden.

**Comment by olibrian** [comment]
Zahlungszweck: Wieso wird was bezahlt. (z.b. Jahresabo)
Zahlungsinformation: Ist eher wann oder wie wird was bezahlt (z.b. 30 Tage netto)
Daher würde ich in diesem Feld auf der QR Rechnung den Zahlungszwecks erwarten. Zahlungsinformationen ist nur auf der Rechnung aufgedruckt.

**Comment by olibrian** [comment]
Passt. 
Wenn jetzt noch unter bearbeiten einer Rechnung (https://htbt-cvp-prod.appuioapp.ch/groups/1/invoices/216499/edit) das Feld Zahlungszweck wieder kommt, bin ich glücklich und der komplette Teil kann von mir aus in den Master gemerged werden.

**Comment by amaierhofer** [comment]
Das Feld Zahlungszweck ist jetzt bei QR Rechnungen editierbar
