### ISSUE TITLE
UX-Issue: Status "Angemeldet" ist verwirrend

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1121]
Aufgefallen bei der SJAS, wahrscheinlich aber ein allgemeines Issue.

Wenn sich ein Benutzer für ein Lager angemeldet hat, sieht er folgende Meldung:
![Screenshot from 2021-01-06 11-17-40](https://user-images.githubusercontent.com/17568539/103757484-1d3af000-5011-11eb-977c-1f1ed500b937.png)

Für den Benutzer ist nicht klar, dass er (wie in diesem Beispiel) nur auf der Anmeldeliste ist und kein Teilnehmer.
![Screenshot from 2021-01-06 11-17-49](https://user-images.githubusercontent.com/17568539/103757599-478cad80-5011-11eb-8108-ef62517b4370.png)
![Screenshot from 2021-01-06 11-17-57](https://user-images.githubusercontent.com/17568539/103757606-49ef0780-5011-11eb-9b20-6788550e811c.png)

Technisch ist alles korrekt, doch der Benutzer geht bei einer Meldung "Du bist für diesen Anlass angemeldet." und dies noch grün Hinterlegt, wohl davon aus, dass er am Lager teilnehmen kann und nicht, dass er auf der Warteliste ist.

**Vorschlag**
Wenn der Benutzer angemeldet, aber noch nicht auf der Teilnehmerliste ist, kommt folgende Meldung, Orange hinterlegt:
"Du bist auf der Warteliste für diesen Anlass."

**Comment by carlobeltrame** [comment]
Landet man nicht in jedem Fall zuerst in dieser "Warteliste" wenn man sich selber für einen Anlass anmeldet? Ich fände es auch unintuitiv wenn auf dem Event steht "3 von 20 Plätzen besetzt", dann melde ich mich an und es steht "Du bist auf der Warteliste". Wie wäre es stattdessen mit etwas ähnlichem wie "Deine Anmeldung wurde empfangen und wird bald vom Veranstalter bestätigt."?

**Comment by chrusu** [comment]
Zumindest bei den SJAS-Lagern landet man direkt auf der Teilnehmerliste, insofern es Platz hat. Bin mir aber nicht sicher ob dies eine Standardeinstellung ist.

**Comment by carlobeltrame** [comment]
Es kann auch sein dass das mit dem Extra-Schritt nur so ist, wenn auf dem Event "Der/Die Gruppenleiter/-in wird informiert und muss die Anmeldung bestätigen" aktiviert ist. Das müsste man jedenfalls auch berücksichtigen.

**Comment by kronn** [comment]
Wenn (wir bei der PBS) sowohl die Warteliste wie auch die Priorisierung aktiv ist, kommt man auf die Anmeldeliste und wird ggf. als Teilnehmer zugeteilt. Ohne die Priorisierung, aber mit Warteliste ist man direkt Teilnehmer, sofern noch Plätze vorhanden sind.

Das Verhalten, dass man mit der Anmeldung direkt einen Platz bekommt, es aber auch eine Warteliste gibt, wenn alle Plätze belegt sind, ist aktuell nur bei der SJAS so aktiv.

**Comment by ThomasEllenberger** [comment]
Wurde meines Erachtens durch https://github.com/hitobito/hitobito/issues/1927 gelöst.

Wenn das Lager voll ist und man auf der Warteliste landet sieht man neu die folgende Information:
![grafik](https://user-images.githubusercontent.com/100761305/227717178-a84d6dab-cc2c-4630-a317-c6791e36eced.png)

-> Closed
