### ISSUE TITLE
Zugriff Catch-All Konten für Kunden

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#1122]
Heute haben die Kunden keinen Zugriff auf die Catch-All Mailkonten ihrer Instanz. Die Prüfung von Mails z.B. im SPAM Folder erfolgt durch den Betreiber. 

Technisch wäre es möglich den Zugriff auf die Catch-All-Mailkonten in Hitobito zu integrieren. Die Credentials für den Zugriff sind bereits auf jeder Instanz für das Abholen der Mails vorhanden. 

Benutzer mit entsprechender Berechtigung sehen an einem zentralen Ort die Inbox sowie den Spam Folder:
- Mails die im SPAM Folder landen, können entweder gelöscht oder als Nicht-SPAM markiert werden.
- Mails die in der INBOX hängen, können ein einen nicht sichtbaren Folder zur Analyse durch den Betreiber verschoben werden.

Anbindung via IMAP

**Comment by olibrian** [comment]
Abschlussarbeiten sind im Ticket https://github.com/hitobito/hitobito/issues/1329 definiert.
