### ISSUE TITLE
Übersetzungen von Gruppennamen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1136]
Gruppennamen sollen übersetzbar sein.

Herangehensweise:

- [ ] Group#name -> Globalize
- [ ] vorhandene Fixtures anpassen
  - [ ] Core
  - [ ] Wagons
- [ ] Group-Fixture extractor anpassen (`rake fixtures:group`)
- [ ] ...

Auswirkungen:

- [ ] Anzeige in der Navigation
- [ ] Sortierung der Navigation
- [ ] Suche nach Gruppenname
- [ ] ...

**Comment by ThomasEllenberger** [comment]
Umsetzung im Moment nicht geplant.
Issue closed.
