### ISSUE TITLE
Speichern von Texten schlägt fehl mit speziellem Apostroph (ʼ) (500-Error)

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1137]
![image](https://user-images.githubusercontent.com/17568539/105835396-0c581b80-5fcc-11eb-8272-0711f74b26b5.png)
![image](https://user-images.githubusercontent.com/17568539/105835679-61942d00-5fcc-11eb-8534-34396254da0a.png)

**Comment by ThomasEllenberger** [comment]
Bug konnte nicht mehr nachgestellt werden.
-> Closed
