### ISSUE TITLE
Performance in grossen Listen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1149]
Umfangreiche Listen haben jeweils lange zu laden (3-5s). Dies wird aus Benutzersicht als not-so-user-experience wahrgenommen.

Aufgefallen bei Layer mit grossen Personenliste (Die MItte). Ursache ist, dass bei grossen Personenliste jeweils pro Person abgefragt wird, ob diese überhaupt angezeigt werden darf. Dies sowohl für die Anzeige der Liste wie die anzeige der Anzahl Personen. Hier hilft das verwendete Pagination nur bedingt.

Möglichkeiten:

- Performance optimierungen
- GUI anpassen

**Comment by ThomasEllenberger** [comment]
Wird in https://github.com/hitobito/hitobito/issues/1712 weiterverfolgt.
-> Closed
