### ISSUE TITLE
Teilnehmerliste und Personenlisten um Filtern Ein- / Ausblenden von Spalten / Sortierungsmöglichkeit erweitern (72h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#115]
# Lösungsansatz

Statt fixe Tabelleneinträge auswählbar machen, was auf der Liste angezeigt werden soll. Auf Teilnehmerlisten

* Einstellung pro Benutzer speichern (aber nicht pro Tabelle)

Siehe:
http://filamentgroup.github.io/tablesaw/demo/toggle.html

![image](https://user-images.githubusercontent.com/194364/46725763-234c9580-cc7d-11e8-9649-48f2c33672bd.png)

# Akzeptanzkriterien

## Anzeige

* [ ] Auf einer **Personenliste** kann ich jedes mit Leseberechtigung sichtbare Personenattribut einblenden / ausblenden. (16h)
* [ ] Nach jedem Attribut soll sortiert werden können (8h)
* [ ] Inklusive Attribute aus Wagon (4h)
* [ ] Auf einer **Teilnehmerliste** kann ich jedes Personenattribut einblenden / ausblenden (8h)
* [ ] Die benutzerdefinierten Angaben (Administrationsangaben oder Anmeldeangaben) können ein- ausgeblendet werden. (12h)
* [ ] Einstellungen werden pro Benutzern gespeichert, alle Tabellen werden mit diesen Angaben ausgegeben (kann auch clientseitig sein). (4h)
* [ ] Beide Varianten sind akzeptabel, bei Click auf eine Checkbox sofort die View zu ändern, oder ein Submit Button (ersteres ist allerdings zu bevorzugen).

## Export

* [ ] Eine Exportoption für CSV / Excel exportiert nur die Spalten, welche ich für die Anzeige ausgewählt habe. (12h)
  _=> Diese müsste allerdings zusätzlich zum bestehenden sein, sonst wird ein Export für alle Daten recht mühsam (haben wir da nicht teilweise auch zusätzliche Spalten drin, welche keine direkten Attribute sind?). Kann das mit dem bestehenden Dropdown sinnvoll abgebildet werden?_

## Attribute die höhere Berechtigung erfordern

* [ ] Attribute anzeigen, die mehr Berechtigung erfordern (z. B. Geburtsdatum) (8h)

## Zu bedenken / überprüfen

* [ ] Sowohl bei Export als auch Anzeige gibt es Customizations, z. B. für die Mitglieder - ID oder PBS Export mit Hauptebenen-ID, dies müssten wir berücksichtigen. Am besten wohl bei der Auswahl dies ermöglichen, und dann den Export ohne Customizations machen (wobei dies wohl eher aufwändiger ist).
* [ ] Wir haben kombinierte Spalten, die nicht direkt auf ein einzelnes Attribut mappen (Rollen, E-Mails, Telefonnummern, es könnte Sinn machen, dass ich z. B. auswähle nur Primäre e-Mailadresse anzuzeigen.

**Comment by fossil12** [comment]
Meinst du mit "Listenansicht" die "Info" Seite?

Ich finde die Idee sehr interessant aber kann auch sehr schlecht abschätzen was die wirklichen Bedürfnisse sind. Denn ein guter Default sollte trotz Anpassungsmöglichkeiten gewährleistet werden, da nicht jeder Nutzer oder jede Nutzerin sich damit befassen will.

**Comment by RolandStuder** [comment]
Eine Schätzung dazu liegt vor https://github.com/hitobito/hitobito_cevi/issues/5

**Comment by RolandStuder** [comment]
# Offene Punkte

* [ ] Export grundsätzlich mal funktionieren lassen.
* [ ] Permissions
  * [ ] AHV-Nummer
  * [ ] Participations haben weniger Zugriff
* [ ] Anmeldeangaben / Adminangaben einzeln selektiert machen (die sind pro Event unterschiedlich)
* [ ] Anmeldeangaben / Adminangaben sortierbar machen
* [ ] Export neue Option oder bestehende ersetzen?
* [ ] Export schon genau so sortiert

**Comment by RolandStuder** [comment]
Mit dem SBV Wagon habe ich eine Fehler erhalten: 

> `/Users/rstuder/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method': undefined method `order_by_type_stmt' for class `#<Class:0x007faccce809d8>' (NameError) from /Users/rstuder/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method_chain' from /Users/rstuder/Sites/hitobito/all-wagons/hitobito_sbv/app/models/sbv/group.rb:42:in `singleton class'`

To fix:

* [ ] breaks responsive table out of container
* [ ] Haupt e Mail Adresse sollte verlinkt sein.
* [ ] PBS Wagon Anrede, zeigt nicht Wert and sondern irgendeinen Key
* [ ] Klick auf Export, setzt Sortierung in View zurück
* [ ] anmelde / Administrationsangaben stehen nicht zur Spaltenauswahl bereit.

**Comment by KunoKunz** [comment]
Auch im Zusammenhang mit #721:

Punkte, die es zu berücksichtigen gilt: Bei Teilnehmerlisten an sich: wer soll grundsätzlich was sehen? Gibt es sensitive Attribute (auch nur in einzelnen Waggons), die nur eingeschränkt sichtbar sein sollen?

**Comment by RolandStuder** [comment]
Offene Punkte:

- [ ] PBS: Auf Teilnehmerliste dürfen Teilnehmer die Fragen und Administrationsangaben nicht sehen
- [ ] Permissions von Participation UND Person beachten für TableDisplay
- [ ] evtl. includes optimieren

Bemerkungen / Infos an Kunden:

- Geschützte Attributen z. B. AHV werden zur Auswahl angeboten
- Exportierte files können nicht die Sortierung übernehmen

**Comment by RolandStuder** [comment]
@KunoKunz Ich weise dir das zu. Ich will es noch grad nicht schliessen, weil ich nicht weiss, ob es abgenommen wurde.

**Comment by nchiapol** [comment]
Wir haben eben auf unserer Testinstanz das Ändern der Spalten bei einer Personenliste getestet. Das funktioniert sowiet gut. Gefehlt hat uns die Möglichkeit die Standardspalten auszublenden. Schön wäre, wenn auch diese im Spaltenmenu enthalten aber einfach vorausgewählt wären.

**Comment by Michael-Schaer** [comment]
Wir haben hier auch noch einen Wunsch:

Die zwei horizontalen Scrollbars machen die Navigation sehr schwierig. Besser wäre eine fixe Breite für den Scrolling-Bereich, oder 100% der Tabelle anzuzeigen, damit ein Balken wegfällt. In der Mobile-Ansicht scheint das zu klappen.

![Scrollbars](https://user-images.githubusercontent.com/1799621/58082778-f455b500-7bb7-11e9-89dc-f9e3652060cc.png)

**Comment by btemperli** [comment]
@nchiapol hat hier am 20. Mai noch kommentiert, dass uns die Möglichkeit fehlt, bestehende Spalten (Standardspalten) auszublenden. So macht es zum Beispiel nicht viel Sinn, die _Haupt-E-Mail_ einzublenden, wenn die Standard-Spalte _Email_ bereits angezeigt wird. Dort wird die _Haupt-E-Mail_ bereits als erster Eintrag angezeigt. Dieser Kommentar blieb leider unbeantwortet und bei uns auf der Testumgebung hat sich seither nichts geändert.

Ist es weiter möglich, die Anordnung der Spalten irgendwie zu ordnen? Thematisch oder alphabetisch? Ich komme mit der momentanen Anordnung nicht wirklich klar. Dies ist aber viel unwichtiger als der obere Punkt mit dem Ausblenden der Standardspalten.

<img width="214" src="https://user-images.githubusercontent.com/3005632/64640834-1f843e80-d40b-11e9-81d0-0c0e82d31016.png">

**Comment by olibrian** [comment]
Umgesetzt. Standardspalten können zur Zeit nicht ausgeblendet werden. Ich schliesse diese Ticket trotzdem mal.
