### ISSUE TITLE
Rechnung: Tage bis Fällig lässt sich nicht ändern.

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1151]
In den Rechnungseinstellungen kann das Feld `Tage bis Fällig` nicht geändert werden. Beim Speichern wird der Wert nicht aktualisiert, sondern es bleibt immer 30 bestehen.

**Comment by ThomasEllenberger** [comment]
Konnte den bug nicht mehr reproduzieren.
Funktioniert bei mir nun korrekt.
-> Closed
