### ISSUE TITLE
EVENTS: Besserer Filter für die Kursansicht (Basis, Datepicker)

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#1153]
## Originalticket: 
#1041, #1152

Die Resultate werden in Seiten gegliedert.

Es soll künftige mehrere Filter eingebaut werden können. Im ersten Schritt wird nach Zeitraum gefiltert mit einem Datepicker

## künftige Filter

- Ebene
- Kursart und Kurskategorie (neu)
- Kursstatus
- Nur Kurse mit freien Plätzen (Ja/Nein)

## Default

Ab jetzt 1 Jahr

## Mockup

![image.png](https://images.zenhubusercontent.com/601915a50c7c845d2798be7c/6169f651-e22f-49ac-836d-4cab17623d42)

## Techspec

- [x] bisher ist die Auflistung im [Event::ListsController] (https://github.com/hitobito/hitobito/blob/master/app/controllers/event/lists_controller.rb#L25) umgesetzt (minimale Filter)
- [x] Basis für neue Filter einbauen (FilteredList wie bei sweb)
- [x] Eigener controller event/courses oder einfach courses mit #index action (simple crud controller ?)
- [ ] Route anpassen: /courses ?
- [x] Filter nach Zeitraum einbauen
- [ ] Filter mit Datepicker-UI versehen
- [ ] gründlich Testen

**Comment by kronn** [comment]
@carlobeltrame ich habe die mal die PRs hierzu zugewiesen und erwarte dein Feedback. Die Display-Sache habe ich noch hinbekommen, was letztlich recht leicht. Das DatePicker-UI habe ich bewusst recht simple gelassen. Wenn wir das weiter mit JQuery-UI machen (wie sonst überall), dann ist mein weiterer Ansatz in #1233 beschrieben. Andernfalls habe ich noch Ideen, die aber vermutlich alle ein Upgrade mehrere JS-Komponenten bedingen und daher vielleicht etwas mehr Aufwand sind.

**Comment by carlobeltrame** [comment]
@Michael-Schaer @nchiapol @anna-s-jubla Die Kursfilter von #1041 sind jetzt implementiert und auf der Integration verfügbar.

Allerdings ist dadurch der BSV-Export kaputt gegangen. Ihr müsst mir hier fachlich aushelfen, wie sich das Ganze verhalten soll, weil wir jetzt ähnliche Filter auf der Kursliste haben wie schon im BSV-Export-Dialog.

![Screenshot from 2021-06-04 11-32-05](https://user-images.githubusercontent.com/7566995/120780717-aa369680-c528-11eb-98b0-22cde288521c.png)

Grundsätzliche Frage: Soll der BSV-Export überhaupt die Kursfilter miteinbeziehen oder ist der unabhängig? Wenn unabhängig, könnte es vielleicht unintuitiv werden, weil sich die exportierte BSV-Liste jetzt noch stärker von der angezeigten Kursliste unterscheidet. Wenn miteinbeziehen, dann bitte für alle Kursfilter definieren, wie die im BSV-Export wirken sollen.

### Datumsfilter
Bisher hat der BSV-Export eigene Datumsfilter, die nach **Abschlussdatum** der Kursteile filtern. In der Kursliste haben wir neu Datumsfilter, die nach **Überschneidung** der Kursteile filtern. Dieser subtile Unterschied wird in der folgenden Grafik dargestellt:

![datumsfilter](https://user-images.githubusercontent.com/7566995/120775864-e5829680-c523-11eb-9b34-19adc24c5990.png)

**Bitte abklären**: Brauchts den BSV-Datumsfilter noch? Wenn ja, sollen beim BSV-Export beide Datumsfilter gleichzeitig gelten, oder nur der BSV-Datumsfilter aus dem Dialog?

### Gruppenfilter / Veranstalter
Bisher konnte man auf der Kursliste nur die Kurse einer einzelnen Gruppe anzeigen. Im BSV-Export wurde diese Gruppe dann ebenfalls berücksichtigt.
Mit den neuen Kursfiltern kann man nun nach mehreren Gruppen gleichzeitig filtern.

**Bitte abklären**: Soll für den BSV-Export weiterhin genau die gleiche Gruppenauswahl verwendet werden wie für die Kursliste? Oder brauchts auf dem BSV-Export-Dialog noch eine Auswahl für eine einzige Gruppe die dann tatsächlich exportiert wird?

### Filter nach Kursstatus
Der BSV-Export bezieht nur Kurse im Status "Abgeschlossen" mit ein.

**Bitte abklären**: Ich nehme an das soll weiterhin so gelten, unabhängig vom Kursstatus-Filter der auf der Kursliste gerade ausgewählt ist. Sonst bitte melden.

### Filter nach verfügbaren Plätzen / Anmeldung
**Bitte abklären**: Ich gehe davon aus, dass dieser Filter für den BSV-Export ignoriert werden soll. Sonst bitte melden.

### Filter nach Kurskategorie
Kurskategorien sind ein komplett neues, optionales Konzept das die PBS eingeführt hat, um z.B. Nicht-J+S-Kurse von J+S-Kursen zu unterscheiden. Zum Beispiel wären dann die Kursarten "J+S-Leiterkurs" und "J+S-Lagerleitermodul" zusammen in der Kurskategorie der "J+S-Kurse". Die Kurskategorien sind durch euch Admins im UI definierbar, ich kann also nicht im Code des BSV-Exports davon ausgehen, dass eine Kurskategorie "J+S-Kurse" existiert.
Auf der Kursliste können entweder alle Kurse, oder nur Kurse aus einer Kategorie angezeigt werden. Auf dem BSV-Export-Dialog gibt es bisher eine Auswahl von Kursarten, die exportiert werden sollen.

**Bitte abklären**: Soll die aktuell ausgewählte Kurskategorie den BSV-Export in irgendeiner Weise beeinflussen? Oder gilt für den BSV-Export nur genau die Kursart-Auswahl die im Dialog gemacht wird?

**Comment by Michael-Schaer** [comment]
Merci für die Zusammenstellung und die wichtigen Fragen.

Grundsätzlich soll der Export nicht abhängig vom Filter der Kursliste sein. Der Export wird zwei mal pro Jahr für die BSV-Abrechnung über alle Gruppen eingesetzt.

Achtung: Für den Erweiterten BSV-Export gilt das selbe: Wir exportieren jeweils alle Gruppen und filtern nur über die Felder in der eigens dafür vorgesehenen Maske.

### Datumfilter
Kurse dürfen jeweils nur in einem Semester erfasst werden. Dabei ist das Abschlussdatum relevant.

Mit dem neuen Datumsfilter wären viele Kurse in zwei verschiedenen Semester aufgelistet, das wäre also problematisch. Bitte hier den Datumsfilter beim Export auf die alte Logik zurückstellen.

### Gruppenfilter
Wichtig ist, dass ein Export aller Gruppen möglich ist. So wie ich das sehe, ist das jetzt der Fall, wenn keine Gruppe im Suchfeld eingetragen wird.

Wir haben uns gefragt, ob ein Button "alle Gruppen" etwas klarer wäre. Dieser würde einfach das Suchfeld leeren...

### Kursstatus
Ja, weiterhin nur abgeschlossene Kurse berücksichtigen!

### Verfügbare Plätze
Ja, verfügbare Plätze sollen ignoriert werden!

### Kurskategorie
Ja, die Kategorie soll ignoriert werden!

**Comment by carlobeltrame** [comment]
Also verstehe ich das richtig, dass ihr für den BSV-Export die neuen Filter nach Datum, Kursstatus, verfügbaren Plätzen und Kurskategorie komplett ignorieren wollt, aber die Gruppenfilter dennoch gelten sollen? Wäre es nicht intuitiver, wenn der BSV-Export-Dialog die neuen Kursfilter alle komplett ignoriert?

Müsst ihr denn beim BSV-Export jemals die Kurse von spezifischen Gruppen exportieren, statt von allen Gruppen gleichzeitig? Wenn ja, könnten wir nicht einfach einen Gruppenfilter auf dem BSV-Export-Dialog ergänzen, um klarzustellen dass das eine komplett unabhängige Filterung ist?

**Comment by Michael-Schaer** [comment]
Ja, das ist sicher klarer, wenn die UI-Filter komplett ignoriert werden. Bei uns gibt es keinen Use Case für einen BSV-Export der Kurse pro Gruppe.

**Comment by Michael-Schaer** [comment]
Das Testing durch die Fachpersonen hat folgendes ergeben:

#### Status
Gibt es die Möglichkeit einer Mehrfachauswahl? Als Default sollten dann alle ausser "Abgesagte" angezeigt werden.

#### Pagination / Performance
Ist die Ansicht noch performant genug, wenn PBS-Kurse über z.B. ein ganzes Jahr auf einer Seite angezeigt werden? Falls nein, sollte Pagination, Lazy Loading oder ähnlich eingebaut werden.

#### Veranstalter 
- Könnte gemäss Ausbildungswording «Kursträger» genannt werden.
- Per Default sollten alle Gruppen von der eigenen Hauptgruppe aufwärts (bspw. Abteilung -> Region-> Kantonalverband -> Bundesebene) angewählt sein.
- Für die Sortierung der Liste könnten Kantonalverbände zuerst und dann Regionen kommen. 
- In der Schnellwahl sollten alle übrigen Gruppen stehen, in denen man eine Rolle hat. Zusätzlich wäre eine Option "Alle Gruppen" nützlich, die entsprechend das Suchfeld leert.

**Comment by chrusu** [comment]
Status: ca. 1 PT

Pagination / Performance: sollte nicht langsamer sein als heute

Veranstalter:
* Kursträger: 0.5h
* Defaultwerte: ca 1.PT
* Sortierung: Liste der Resultate? oder Liste der Veranstalter (1h)?
* alle gruppen meiner Rollen: ca. 1 PT
* Option "Alle Gruppen": Clear All ca. 0.5 PT

**Comment by Michael-Schaer** [comment]
Noch zwei Ergänzungen:
### Labels
 Gut wäre noch zwei Labels für die Datumsfelder ("Von" & "Bis")

### On-Change / Autoloading
Sehr im "Nice-To-Have" Bereich. Bitte nur Umsetzen, wenn es Performance-mässig auch Sinn macht
- Reload on change bei jeder Änderung
- Suchen-Button entfernen

Priorität sonst wie mit @chrusu telefonisch besprochen nach einfacher Umsetzung.

**Comment by chrusu** [comment]
Folgetickets: #1347, #1348
