### ISSUE TITLE
EVENTS: Kursfilter: Kurskategorien erstellen + Filtern (Seitenleiste)

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#1154]
## Originalticket: 
#1041, #1152

## Filter
 
- Kursart und Kurskategorie (neu)

## Kategorien

Die Kursarten werden in Kategorien aufgeteilt, um die Liste der Kursarten übersichtlich zu halten. Kursarten können konfigurativ den Kurskategorien zugeordnet werden.

Die Filter werden visuell über die Seitenleiste gesteuert, analog zur Gruppennavigation.

## Mockup

![image.png](https://images.zenhubusercontent.com/601915a50c7c845d2798be7c/e342a3e7-df8a-4197-be68-30ed90d47957)

## Techspec

- [x] CRUD zur Verwaltung von `event_kind_categories` anlegen (unter globalen Settings)
- [x] `Event::Kind belongs_to Event::KindCategory`
  - migration
  - `event/kind#edit` anpassen
- [x] Hierarchische Darstellung in Seitenleiste
- [x] Filter nach Kursart/Kurskategorie einbauen

**Comment by chrusu** [comment]
@Michael-Schaer : Reicht es, wenn eine Kursart je nur einer Kurskategorie zugehört?

**Comment by Michael-Schaer** [comment]
> 
> 
> @Michael-Schaer : Reicht es, wenn eine Kursart je nur einer Kurskategorie zugehört?

Ja, das reicht!

**Comment by chrusu** [comment]
Noch Fehlend: Tests und Review
