### ISSUE TITLE
EVENTS: Weitere Filter für Kursansicht

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#1155]
![image.png](https://images.zenhubusercontent.com/601915a50c7c845d2798be7c/69dce7d2-eb15-4deb-8c3d-acb209b62da3)## Originalticket: 
#1041, #1152

## Filter

- Ebene
- Kursstatus
- Nur Kurse mit freien Plätzen (Ja/Nein)

## Ebene

Es werden erst einmal Kurse der eigenen Ebene angezeigt. Darüberliegende Ebenen sind direkt anwählbar. Andere Ebenen können frei ausgewählt werden (~).

Dropdown "Ebene"

Wenn ich einen Kantonalverband aufklappe, sollten darunterliegende Ebenen (Regionen und Abteilungen) zur Auswahl angezeigt werden. Unter den Regionen dann auch die Abteilungen. Ein Minuszeichen könnte anzeigen, dass eine Teilmenge der untergeordneten Gruppen ausgewählt ist.

## Defaults

Ebene -> Meine Hauptebene
Status -> "Zur Anmeldung offen"

## Mockup

![image.png](https://images.zenhubusercontent.com/601915a50c7c845d2798be7c/7933914e-2677-4818-ae30-8be45d985a8a)

![image.png](https://images.zenhubusercontent.com/601915a50c7c845d2798be7c/ed658016-cb7a-4f34-9f43-951dd4575995)

## Techspec

- [x] Kursstatus -> Dropdown mit konfigurierten Stadien
- [x] Nur Kurse mit freien Plätzen -> Checkbox `Event#places_available?`
- [x] Ebene -> siehe oben

## Update 25. März 2021 Sprintplanning
Es ist noch unklar, wie einfach es ist, die Links rechts vom Eingabefeld in das Eingabefeld einzufügen. Falls es sich als zu kompliziert herausstellt, wird wieder die ursprünglich angedachte Lösung umgesetzt.

**Comment by chrusu** [comment]
Hey @Michael-Schaer 

Wir haben uns noch gefragt, ob wir den Ebenenfilter auch folgendermassen lösen könnten und ob das für eure Ansprüche schon gut genug sein könnte. Hintergrund ist, dass wir diesen Controller bereits in hitobito eingebaut hätten und so viel Zeit sparen könnten, was Schlussendlich auch wieder der PBS zugute kommen würde.

Wenn aber die komplexere Filterung nötig ist, können wir dies natürlich gerne so umsetzen.

Wenn du möchtest können wir dies auch kurz in einem Video-Call besprechen.

Wie siehst du das?

![image](https://user-images.githubusercontent.com/17568539/111612874-37960480-87de-11eb-8c3e-a4adc9f4e713.png)

**Comment by Michael-Schaer** [comment]
Die ursprüngliche Idee war ja, dass ich meine eigene Ebene und die Darüberliegenden direkt auswählen kann. Weitere Ebenen per Suchfeld waren da eine zusätzliche Option für erweiterte Suchen.

Stellt euch vor, dass eine Abteilungs- oder Regionsleitung nicht zwingend präsent hat, wie die Ebenen über und unter ihnen genau heissen. Ich fände es also nicht passend, wenn da einfach ein leeres Textfeld steht, wo man nicht so recht weiss, was man eintippen kann.

Ich könnte mir folgendes vorstellen: Über dem Textfeld hat es verschiedene Optionen zur Auswahl: 
- PBS
- übergeordneter KV
- übergeordnete Region
- Meine Abteilung

Beim Klick auf eine dieser Optionen wird das Textfeld direkt damit abgefüllt. Es ist aber auch möglich, per Freitext andere Ebenen hinzuzufügen, wie von dir beschrieben.

Je nach Hauptebene des Benutzers fallen die Ebenen Abteilung, Region und KV in der Ansicht weg.

Wäre so etwas möglich?

**Comment by chrusu** [comment]
Hey @Michael-Schaer 

Meinst du so was? Ich denke das sollte möglich sein, was meinst du @carlobeltrame ?

![image](https://user-images.githubusercontent.com/17568539/111645413-f7944900-8800-11eb-9bf5-029f6ec888e1.png)

**Comment by Michael-Schaer** [comment]
Ja genau so etwas. Und wenn keine Ebene ausgewählt ist, werden alle Ebenen durchsucht. Das wäre sicher auch ein Use Case.

**Comment by carlobeltrame** [comment]
@Michael-Schaer bisher konnten Personen die in keiner Ebene `:layer_full` oder `:layer_and_below_full` Berechtigung haben nur Kurse auflisten die in ihrer eigenen Hierarchie (eigene Ebene aufwärts bis zum Dachverband) angehängt sind, aber nicht die Kurse beliebiger anderer Ebenen. Ich glaube mich zu erinnern dass der Grund dafür ist, dass die Anmeldung bei fremden Ausbildungsregionen via Ausbildungsverantwortliche laufen soll.
Ich gehe davon aus, dass das weiterhin so sein soll, und setze das entsprechend um. Das Autocomplete-Dropdown bietet für diese Personen dann halt immer nur genau die selben Einträge an wie die "Links" daneben. Falls es diesen Personen neu auch möglich sein soll, beliebige Kurse anderer Ebenen aufzulisten, zu denen sie nicht gehören, können wir das dann noch separat anpassen.
