### ISSUE TITLE
TECH: pain points development setup

### ISSUE THREAD

**Issue by psunix** [hitobito/hitobito#1166]
wir haben seit einigen Monaten ein standardisiertes Tool zur Entwicklung von Hitobito: https://github.com/hitobito/development

es gibt noch einige pain points die die Entwicklung behindern. Die Punkte die am meisten schmerzen wollen wir angehen!

- ungewünschte Änderungen schema.rb
- changes Gemfile.lock
- wagon/core switchen innerhalb rails/rails-test container

**Comment by lucashabersaat** [comment]
Einige Punkte, die uns aufgefallen sind, beim Versuch Tests lokal auszuführen
* `rspec` statt `rails spec`
    * findet rails sonst nicht im container (?)
* kann sein, dass Tests failen wegen fehlenden Assets
    * `rake assets:precompile` im core ausführen
* für die Wagontests, im Wagonfile neben `:development`, `:test` hinzufügen
* beim Wechseln von core zu wagon test oder umgekehrt:
    * `rails db:test:prepare` im jeweiligen Verzeichnis
* sicherstellen, dass db/schema.db alle Migrations beinhaltet

Kann gut sein, dass wir auch einfach sonst etwas falsch gemacht haben, aber mit diesen Tips geht es.

**Comment by carlobeltrame** [comment]
Folgendes hat funktioniert als ich es das letzte Mal versucht habe:
```bash
docker-compose exec rails-test bash
rails spec
```

Folgendes aber nicht:
```bash
docker-compose exec rails-test rails spec
```
Das hatte ich in https://github.com/hitobito/development/issues/4 schon mal gemeldet. @psunix hat dann nachgeforscht und gesagt dass das nicht möglich ist, ich selber bin aber noch nicht ganz überzeugt. Müsste es nicht möglich sein, die $PATH Variable im Dockerfile zu ergänzen?
