### ISSUE TITLE
Rechnungen: € Symbol taucht teilweise auf anstelle von CHF

### ISSUE THREAD

**Issue by CalvinYMCA** [hitobito/hitobito#1168]
Siehe Screenshot
![image](https://user-images.githubusercontent.com/79665466/109214439-1ed39980-77b2-11eb-902c-403d9c89edbb.png)

**Comment by olibrian** [comment]
Wurde in der Zwischenzeit behoben:
![image](https://user-images.githubusercontent.com/9592347/128681852-9dc127c1-f31a-467d-9bba-a53f550881f5.png)
Getestet in der Cevi Integrationsumgebung. Danke trotzdem für die Meldung. Falls du noch ein Eurozeichen siehst, bitte melden. :-)
