### ISSUE TITLE
SMS Nachrichten testen

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1170]
Bei uns ist der Nachrichten-Tab im Testsystem aufgetaucht. Gibt es einen Provider, den ich eintragen kann, um die Funktion zu testen (nicht das SMS selber, sondern der Umgang von hitobito damit)?

Bzw. wie komme ich zum SMS-Verschicken-Dialog?

**Comment by psunix** [comment]
Hoi Michael

sehr gut ist dir der Nachrichtentab aufgefallen :)

zurzeit ist SMS Versand mit aspsms.ch möglich. Damit SMS versendet werden können müssen wir aber noch in eurem Wagon die Einstellung entsprechend einfügen. Dann könnt ihr auch Briefe schreiben im Abo.

**Comment by Michael-Schaer** [comment]
Hallo Pascal, merci für die Rückmeldung! Wenn das kein grosser Aufwand ist, würden wir das gerne testen.

**Comment by Michael-Schaer** [comment]
Etwas ähnlich scheint für die Adress-Verfolständigung der Fall zu sein. Der Request wird beim Tippen abgesetzt, aber angezeigt wird nichts im GUI. Fehlt da noch ein Flag in der Config oder ähnlich? https://github.com/hitobito/hitobito/pull/1087

![image](https://user-images.githubusercontent.com/1799621/109662878-d0d0e400-7b6b-11eb-95d2-cee442fdbaa2.png)

**Comment by psunix** [comment]
![image](https://user-images.githubusercontent.com/655627/109786755-c830ea00-7c0d-11eb-8eae-496e79f31d01.png)

das SMS feature ist auf der integration jetzt aktiv. bitte beachte das es noch ziemlich beta ist. wir freuen uns aber natürlich auf feedback von dir. 

damit SMS gesendet werden können, musst du auf der Gruppe des Abos unter Einstellungen die Aspsms Credentials hinzufügen.

**Comment by psunix** [comment]
@TheWalkingLeek wird das mit der Adressvervollständigung noch bei euch auf der Integration aktivieren. Er meldet sich sobald das funktioniert.

**Comment by TheWalkingLeek** [comment]
Für die Addressvervollständigungen haben nur die Adressdaten gefehlt. Habe die nun auf Integration importiert und die Vervollständigung ist jetzt aktiviert :)

**Comment by Michael-Schaer** [comment]
Super, das hat beides geklappt. Dann melde mich wieder mit dem Feedback! Merci und lg
