### ISSUE TITLE
Event-Name nicht mehr Pflicht

### ISSUE THREAD

**Issue by Vento-Nuenenen** [hitobito/hitobito#1173]
Ich hab mich mal wieder im PBS-Test-System umgesehen.
Aktuell können alle Events ohne Namen erstellt werden. Wenn man dann einen Event, Lager oder Kurs ohne Namen erstellt, funktioniert die Anmeldung, die Freigabe & die Anzeige teils nicht mehr sauber.

JFYI, @Michael-Schaer

**Comment by carlobeltrame** [comment]
Danke für die Meldung, ich habe mich schon gefragt weshalb wir in Sentry Fehler bekommen die von fehlenden Event-Namen verursacht werden.
Ich schätze das dürfte mit #1135 zusammenhängen.
