### ISSUE TITLE
Ausschliessen von Personen mit folgenden Tags funktioniert bei Listen nicht

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito#1174]
Die neue Funktion "Ausschliessen von Personen mit folgenden Tags" funktioniert zwar bei den Personenfiltern, nicht aber bei den Listen. Sobald ich bei einer Liste ein Tag wähle bei "Ausschliessen von Personen mit folgenden Tags", ist der Empfängerkreis leer (ersichtlich beim leeren Export der Liste). 

Die Funktion "Hinzufügen von Person mit Tags" funktioniert bei den Listen.

**Comment by olibrian** [comment]
Verifikation in der puzzle.hitobito.com umgebung. Funktioniert auch mit dem Abo.
