### ISSUE TITLE
EVENTS: Fallback verhalten von Sprachen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1180]
## Aktuelles Verhalten

Wenn ein Event auf Französisch oder Italienisch erfasst wird, aber keine deutsche Bezeichnung hat, wird als die URL als Name angezeigt: /de/groups/3/events/17

## Gewünschtes Verhalten

Falls keine deutsche Bezeichnung vorhanden ist, soll zuerst die französische Bezeichnung angezeigt werden. Als weiteren Fallback wäre dann die italienische Bezeichnung.

Definiertes Fallback nach folgender Priorität:

1. Deutsch
2. Franzöisich
3. Italienisch
4. Englisch

## Schritte zum reproduzieren

Beispiel vom Event: https://cvp.puzzle.ch/de/groups/3/events/17/edit

# Tech-Spec

Achtung: Dies betrifft ev noch mehrere Felder als nur die Bezeichnung welche internationalisiert sind.

- ...
- https://github.com/hitobito/hitobito/

**Comment by simfeld** [comment]
Ich kann das im dev setup nicht nachvollziehen, nur auf den Integrationsumgebungen. Eventuell überschreibt https://github.com/hitobito/hitobito/blob/1172e57d76bddf13002a66dd88c807aceb5e3e15/config/environments/production.rb#L76 die fallback config in https://github.com/hitobito/hitobito/blob/b256049896b91ad041661e0daacb0cfb291323c9/config/application.rb#L45-L51 ?

**Comment by psunix** [comment]
wird mit #1211 gefixt. schliesse dieses Ticket mal.
