### ISSUE TITLE
PERSON_DUPLICATES: No route matches error

### ISSUE THREAD

**Issue by psunix** [hitobito/hitobito#1196]
## Aktuelles Verhalten

Auf PBS int kann die person_duplicates index Seite nicht aufgerufen werden.

## Gewünschtes Verhalten

Person Duplicates werden auf dem aktuellen Layer angezeigt.

## Schritte zum reproduzieren

1. Klick auf Personen Tab einer beliebigen Ebene
2. Button 'Duplikate' klicken
3. Bäng!

# Tech-Spec

- sentry error: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/29705/?query=is%3Aunresolved

**Comment by carlobeltrame** [comment]
Duplikat von #1175, wird in #1182 gelöst
