### ISSUE TITLE
Unsubscribe Link Bug

### ISSUE THREAD

**Issue by luca-bruegger** [hitobito/hitobito#1199]
## Aktuelles Verhalten

Mail einer Mailingliste sollten eine Unsubscribe url enthalten falls man diese Abonnieren kann und Deabonnieren möchte. Dieser wird jedoch nicht der Email angehängt.

## Gewünschtes Verhalten

Der Unsubscribe link wird als Clickable Link dem Mail als anchor-tag hinzugefügt, sollte es HTML sein und sonst als Text.

## Schritte zum reproduzieren

1. Neues Mail einer Subscribable Mailingliste erstellen.
2. Im Footer des Mails sollte dieser Link nun vorhanden sein.

# Tech-Spec

- https://github.com/hitobito/hitobito/blob/master/spec/domain/mail_relay/lists_spec.rb#L215

**Comment by carlobeltrame** [comment]
Da die Mailinglisten-Mails nicht von hitobito sondern von den Usern versendet werden, müssten wir dafür den Mail-Inhalt des Users abändern. Das würde allfällig präsente [DKIM-Mailsignaturen](https://en.wikipedia.org/wiki/DomainKeys_Identified_Mail) ungültig machen, und so potenziell dazu führen, dass die hitobito-Mailserver von anderen Mailservern als unzuverlässig eingestuft werden und Mails via hitobito öfter als Spam klassifiziert werden. Da die Mailserver mit ganz Appuio geteilt sind, hätte das einen negativen Effekt sogar über hitobito hinaus.

Für professionelle Mailkampagnen würde ich die MailChimp-Anbindung empfehlen. Für kleinere Vereine hingegen fände ich es sinnvoll, wenn wir auf der Mailingliste den Unsubscribe Link anzeigen würden (oder ein Template dafür mit Platzhaltern für die Empfänger-spezifischen Teile), welchen die User selber direkt in ihre handgestrickten Mailkampagnen einbauen können.

**Comment by psunix** [comment]
ich habe den commit mit dem unsubscribe link erst mal wieder entfernt.
es scheint keine gute Idee den Body eines mails zu manipulieren. merci @carlobeltrame für die inputs.
im Moment haben wir zu viel anderes, darum schliesse ich das ticket hier mal wieder. 
vielleicht finden wir ja in Zukunft eine elegantere Lösung für das Ganze.
