### ISSUE TITLE
Etiketten export 3x8

### ISSUE THREAD

**Issue by J0hn5mith** [hitobito/hitobito#12]
Hallo Zusammen

Wenn ich Etiketten exportiere im Format 3x8 auf einer Seite, dann passt die Vorlage auf die bedruckbaren Etiketten. Im oberen rechten ecken stimmen sie noch knapp je weiter es aber gegen unten links geht, desto weniger passen sie. 
Sollte eigentlich einfach zu beheben sein. 

Liebe Grüsse

Jan 

![img_1552_2](https://cloud.githubusercontent.com/assets/856276/11099992/cfddc168-88ae-11e5-91b7-d9197129f0f5.jpg)

**Comment by codez** [comment]
Die Etikettenformate werden im User Interface verwaltet. Bitte melde dich bei deinen Datenbankverantwortlichen, um genaueres über die konfigurierten Formate und die entsprechenden Etikettenbögen zu erfahren.
