### ISSUE TITLE
FRONTEND: Kalender-Style greift nicht mehr

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#1202]
## Aktuelles Verhalten

Auf der Integration wird der aufklappbare Kalender (z.B. beim Erfassen einer neuen Person in einer Gruppe) mit den standard-Bootstrap-Styles angezeigt.

![Screenshot from 2021-03-09 13-56-55](https://user-images.githubusercontent.com/7566995/110474167-a3da7f00-80df-11eb-89dc-2e2729e7f9ba.png)

## Gewünschtes Verhalten

Die extra an hitobito angepassten Styles sollten weiterhin greifen. Hier ein Screenshot aus einer Produktionsumgebung:

![Screenshot from 2021-03-09 13-56-58](https://user-images.githubusercontent.com/7566995/110474173-a6d56f80-80df-11eb-810c-7018b7ed0a5d.png)

## Schritte zum reproduzieren

1. Nach dem Login auf das Personen Tab einer beliebigen Gruppe
2. Auf Button "Person hinzufügen" klicken
3. Ins "Von" Datumsfeld klicken

# Tech-Spec

**Comment by chrusu** [comment]
@carlobeltrame @kronn @luca-bruegger @TheWalkingLeek Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Development-601915cf57bc050017cf9a8c/issues/hitobito/hitobito/1202?planning-poker)
