### ISSUE TITLE
TECH: KON Analyse Clean-Up Devise

### ISSUE THREAD

**Issue by psunix** [hitobito/hitobito#1205]
rund um Devise gibt es historisch bedingt einige Aufräumarbeiten damit der Code wieder clean und verständlich ist. 

siehe auch: https://github.com/hitobito/hitobito/issues/1083
siehe auch dieser PR, der schon Dinge in Bezug auf API Authentication aufräumt: https://github.com/hitobito/hitobito/pull/1198

Ziel dieser Story ist eine Analyse sowie das Zusammentragen der zu bereinigenden Code Elemente. 

Ticket #1083 soll entsprechend verfeinert werden.

- Devise upgrade?
- Devise doku studieren und mit Hitobito implementation vergleichen, möglichst an Devise Standard halten
- GLP 2FA Erweiterung anschauen (dort werden weitere Teile customized)
- Gibt es andere Wagons mit Anpassungen rund um Devise?

# Tech-Spec

**Comment by TheWalkingLeek** [comment]
#1083 entsprechend erweitert
