### ISSUE TITLE
Gruppen: Massen-Edit "Zu Veranstaltung hinzufügen" findet keine Veranstaltungen

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito#1209]
## Aktuelles Verhalten

1. Auf der Cevi-Integrationsumgebung eine Gruppe mit Anlässen und/oder Kursen auswählen.
2. Alle Personen auswählen
3. auf "Zu Veranstaltung hinzufügen" klicken
4. korrekten Typ wählen
5. In Suchfeld Name eintippen
6. es werden keine Resultate gefunden

## Gewünschtes Verhalten
6. Resultate werden gefunden und angezeigt

**Comment by carlobeltrame** [comment]
Könnte möglicherweise mit https://github.com/hitobito/hitobito/pull/1164 zusammenhängen

**Comment by carlobeltrame** [comment]
Oder laut @kronn wohl eher mit https://github.com/hitobito/hitobito/pull/1135

**Comment by psunix** [comment]
duplicate #1278, closing
