### ISSUE TITLE
EVENTS: Übersetzung

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1211]
## Aktuelles Verhalten
Wenn ein Event (z.B. ein Lager) in einer Sprache erfasst wird, erscheint in den anderen Sprachen kein nützlicher Event-Name. Siehe Screenshots (weiter unten) der Stellen, wo mir das Verhalten aufgefallen ist.

Background: Ich gehe davon aus, dass Events weiterhin primär in einer Sprache erfasst werden. Bei Bundeskursen und grösseren Lagern wird sich eine Mehrsprachigkeit womöglich einspielen. Der Standardfall ist aber, dass man einen Event in seiner eigenen Sprache erfasst. 

## Gewünschtes Verhalten

Nach mir müsste da derjenige Name ausgegeben werden, der gesetzt ist. Beispiel: Wenn der Name nur in IT gesetzt ist, müsste bei der Ansicht DE und FR auch der IT-Name erscheinen.

## Schritte zum reproduzieren

1. Sprache IT wählen
2. Lager erstellen
3. Sprache FR wählen
4. Verschiedene Ansichten öffnen:

![1](https://user-images.githubusercontent.com/1799621/111757733-ee0bef00-889b-11eb-9fa6-dfba5943163c.PNG)

![2](https://user-images.githubusercontent.com/1799621/111757732-ed735880-889b-11eb-98bb-cacdc123f843.PNG)

![3](https://user-images.githubusercontent.com/1799621/111757731-ed735880-889b-11eb-8669-43ca4134ecd1.PNG)

Export:
![4](https://user-images.githubusercontent.com/1799621/111757729-ecdac200-889b-11eb-97d9-9b0c4c104e67.PNG)

# Tech-Spec

- I18n Fallback config prüfen: https://github.com/hitobito/hitobito/blob/b256049896b91ad041661e0daacb0cfb291323c9/config/application.rb#L45-L51
- https://github.com/hitobito/hitobito/blob/1172e57d76bddf13002a66dd88c807aceb5e3e15/config/environments/production.rb#L76
- Laut https://github.com/hitobito/hitobito/issues/1180#issuecomment-792083117 ist das Problem lokal nicht vorhanden, in Prod/integration schon

**Comment by carlobeltrame** [comment]
Duplikat von #1180

**Comment by carlobeltrame** [comment]
Ich habe mal einen versuchsweisen Fix basierend auf der Analyse von @simfeld implementiert und auf der PBS Integration deployed. Selber kann ich das Problem jetzt nicht mehr reproduzieren. @Michael-Schaer könntest du mal testen?

**Comment by carlobeltrame** [comment]
Ich schliesse dieses Ticket mal. Falls noch etwas auffällt gerne wieder eröffnen.
