### ISSUE TITLE
PERSON: Adressvervollständigung testen

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1213]
Tolle Funktion - Wir freuen uns! Zwei Dinge fallen mir auf:

### Nicht gefundene Adressen
Einige Adressen sind nicht bekannt, bzw. erscheinen nicht im Autocomplete. Beispiele: 

- Seftigenstrasse 10b, 3007 Bern
- Stoossstrasse 2, 3008 Bern

![image](https://user-images.githubusercontent.com/1799621/111763927-f156a900-88a2-11eb-9f58-e6594d5b30ab.png)
'
## Analyse-Task
- [x] Setup Doku Adressvervollständigung erstellen bzw. ergänzen falls bereits vorhanden
- [x] Prüfen, warum die oben genannten Adressen nicht korrekt importiert werden.
- [x] In den Übersetzungen von den Tags "Addresse befindet sich nicht im Verzeichnis" --> "Adresse befindet sich nicht im Verzeichnis"
- [x] Prüfen, warum bei der PBS-Integrationsumgebung die "falschen" Adressen nicht getagt werden.
  - https://pbs.puzzle.ch/de/groups/1/people/777.html
    - fehlerhafte Adresse, doch kommt kein Tag 
    - Ev. auch mit dem Buchstabenproblem gelöst
- [x] Entweder fixen, wenn kleine Sache, oder deaktivieren für Release PBS

**Comment by chrusu** [comment]
@TheWalkingLeek Wie besprochen, kannst du da kurz reinschauen?

**Comment by Michael-Schaer** [comment]
Ich habe auf dem Integrationssystem mit zwei Adressen getestet. Die beiden Adressen haben weiterhin kein Autocomplete:

Stoossstrasse 2
Sulgenrain 4

Vielleicht bin ich aber auch noch zu früh mit dem testen?

**Comment by kronn** [comment]
@Michael-Schaer Dein Test-Zeitpunkt war vermutlich okay. Ich schaue es mir heute nochmal an.

**Comment by chrusu** [comment]
mir scheint, dass das autocomplete mit hausnummer erst ab der zweiten getippten zahl einspringt

so klappt sulgenrain 1 nicht, aber sulgenrain 11 hingegen schon.
