### ISSUE TITLE
EVENTS: Sichtbarkeit von Anlässen

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1214]
## Aktuelles Verhalten

Für mich nicht sichtbare Events werden weiterhin in der Liste angezeigt (betrifft Lager und Anlässe). Wenn einer dieser Anlässe angeklickt wird, erscheint eine Fehlermeldung und ich werde auf meine Hauptebene weitergeleitet.

## Gewünschtes Verhalten

 - [x] Die Events sollten ganz versteckt werden.  (MUST)
 - [ ] Parallel zu anderen Ansichten soll angezeigt werden, wie viele Events für mich nicht sichtbar sind. (CAN)

![mockup Anlässe](https://user-images.githubusercontent.com/1799621/111767328-e1d95f00-88a6-11eb-8f9a-f295215867bb.png)

## Schritte zum reproduzieren

1. Person aus KV X impersonieren
2. Lager im KV Y anschauen (eines ohne Globale Sichtbarkeit wählen)
-> Fehlermeldung betreffend fehlender Berechtigung

# Tech-Spec
- Die ähnliche Anzahl versteckte Einträge ist für Personenlisten hier bereits implementiert: https://github.com/hitobito/hitobito/blob/master/app/views/people/_list.html.haml#L17
- Um die Liste zu filtern verwenden wir bei Personenlisten eine Domainklasse [Person::Filter::List](https://github.com/hitobito/hitobito/blob/master/app/controllers/people_controller.rb#L255). Diese bietet dort aber auch noch die Möglichkeit, die Personenliste nach benutzerdefinierbaren Kriterien zu filtern, was bei den Anlässen vorerst nicht nötig ist.
- Schätzung für Must, falls zeitlich ausreichend und einfach umsetzbar, Can umsetzten.

**Comment by kronn** [comment]
Der "Kann"-Part wurde nicht umgesetzt. Man könnte (no pun intended) jedoch `entries` und `visible_entries` als helper_method deklarieren und damit im View die informationen anzeigen. Der Aufwand wäre dann, Übersetzung, HTML und ggf. Design anzupassen.
