### ISSUE TITLE
EVENTS: Teilnehmer-rolle löschen, bei hinzufügen einer Leiterrolle

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1220]
see: https://github.com/hitobito/hitobito_cevi/issues/8

Wenn einem Kurs-Teilnehmer eine andere Rolle (z.B. Kursleiter oder Küche) zugeteilt wird, soll die Möglichkeit bestehen, die Teilnehmerrolle im selben Schritt zu entfernen.

Unseren Ausbildungsverantwortlichen haben noch gewünscht, dass wir ihnen ein paar Klicks sparen. Könnt ihr den "Rolle hinzufügen"-Dialog um eine Checkbox "Teilnehmer/-in Rolle entfernern" ergänzen (default selected), so dass die Rolle gleich mitgelöscht werden kann?

# Mockup

![image.png](https://images.zenhubusercontent.com/601915a50c7c845d2798be7c/9a5dc57e-66c8-4e71-8752-a30583645286)

# Tech-Spec

Gemäss meinem Gespräch mit @kronn  gibt es 2 Möglichkeiten dies umzusetzen:

Variante 1 (ca. 1 PT):
Eine Checkbox mit dem Vermerk "Allfällige Teilnehmer*Innen-Rolle entfernen".  In diesem Fall kann beim erstellen des Formulars die aufwändige Überprüfung wegfallen, ob der Ausgewählte Teilnehmer auch wirklich die Rolle Teilnehmer besitzt.

Variante 2 (> 2PT):
Es werden alle Rollen (dieses Kurses) des Teilnehmers aufgelistet mit vorausgewählten Checkboxen. Der Kursleiter hat dann die Möglichkeit, die Rollen zu entfernen, welche nicht mehr gewünscht werden.

![image.png](https://images.zenhubusercontent.com/601915a50c7c845d2798be7c/70233179-2193-4581-9ca3-1d971dbd6d67)

**Comment by nchiapol** [comment]
Grundsätzlich wäre für uns Variante 1 völlig ok.
