### ISSUE TITLE
MIGRATIONS: error in migration when creating new tenant

### ISSUE THREAD

**Issue by psunix** [hitobito/hitobito#1221]
## Aktuelles Verhalten

Neue Tenants können auf multitenant-prod nicht erstellt werden

## Gewünschtes Verhalten

Neue Tenants können über das Webinterface admin erstellt werden

## Schritte zum reproduzieren

1. Login multitenant admin
2. Unter Einstellungen > Tenant neuen Tenant anlegen

# Tech-Spec

- https://github.com/hitobito/hitobito/blob/master/db/migrate/20121119092332_create_events_groups_and_some_fields.rb#L15
  - Wenn Zeilen 15-17 auskommentiert werden, läuft die Migration durch und der Tenant kann angelegt werden.
- Migration wird beim Tenant Create getriggert
- Es scheint so das beim Aufruf von Event.find_each irgendwelche DB-Felder erwartet werden:
  - events.application_contact_id
  - weitere?
- ggf. ist es einfach Save die Zeilen 15-17 zu entfernen. Es sollte ja keine bestehende Instanzen mehr geben die noch auf so einem tiefen Migration Stand sind.
- https://sentry.puzzle.ch/pitc/hitobito-backend/issues/35782/?query=is%3Aunresolved

```
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Unknown column 'events.application_contact_id' in 'field list'
```

**Comment by kronn** [comment]
Ich bin dafür, den fraglichen Part der Migration mit SQL zu schreiben. In jedem Fall bitte auch den `down`-Part anpassen, damit es symmetrisch bleibt.
