### ISSUE TITLE
DEVISE: ArgumentError in Devise::Sessions#new Entwicklungsumgebung

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#1223]
## Aktuelles Verhalten

Im Development-Setup kommt immer wieder mal ein Devise-Error und der Rails Server muss neu gestartet sowie die Session Cookies gelöscht werden damit man sich noch einloggen kann. 

![image](https://user-images.githubusercontent.com/655627/112423405-d9fc3d80-8d32-11eb-9264-925a1a3c2855.png)

Soweit ich das bisher gesehen habe hat es nichts mit dem docker development setup zu tun. Kommt also auch vor wenn man den Rails Server lokal laufen lässt.

## Gewünschtes Verhalten

Kein Session Problem mehr und es kann ohne Unterbrüche gearbeitet werden.

## Schritte zum reproduzieren

1. Lokalen Development Server starten
2. Mit einem Benutzer einloggen
2. Warten bis Session abläuft? Bin mir nicht sicher ob das immer der Fall ist oder ob es evtl. noch andere Faktoren gibt die zu diesem Fehler führen.

# Tech-Spec

- https://github.com/heartcombo/devise

**Comment by carlobeltrame** [comment]
Das ist mir jetzt schon länger nicht mehr passiert. @mtnstar ist das immer noch ein Problem?

**Comment by TheWalkingLeek** [comment]
Ich hatte das insbesonders wenn ich das Login getestet hatte (der Fehler selbst kam glaub meist bei/nach dem Logout)
Konnte es jetzt aber auch nicht nochmal provozieren

**Comment by ThomasEllenberger** [comment]
@mtnstar @carlobeltrame @TheWalkingLeek ist das noch ein Problem für euch? Sollten wir uns dem einmal annehmen und versuchen zu beheben, oder können wir dieses Issue schliessen?

**Comment by carlobeltrame** [comment]
Habe ich schon lange nicht mehr gehabt. Kann von mir aus geschlossen werden.
