### ISSUE TITLE
Personen endgültig Löschen mit :admin Berechtigung

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#123]
- Ganz normales Destroy auf die Person, für alle mit :admin Berechtigung.
- Confirm Dialog: "Willst du {Vorname} {Nachname} wirklich löschen?
- Button auf Person wie auf untenstehendem auf Personenansicht
- Abern ohne den elaborierten Modaldialog!

![](https://wearecube.mybalsamiq.com/mockups/5216199.png)

**Comment by RolandStuder** [comment]
@adriananderegg Ready for Testing auf http://pbs.puzzle.ch/

**Comment by PBS-MichaelBurkhardtKauri** [comment]
Der oben skizzierte Dialog erscheint nicht, ich kann keine Optionen auswählen. Lediglich ein Pop-up mit der Frage, ob die Person gelöscht werden soll.
Ich weiss allerdings nicht, was ein "elaborierter Modaldialog" ist…

**Comment by RolandStuder** [comment]
@PBS-MichaelBurkhardtKauri Ja, alles was du grafisch siehst, fällt unter den Punkt "elaborierter Modaldialog". Ich schlage aber, vor dass wir den Button noch rot färben, damit klarer ist, dass man hiermit als Admin etwas "schwerwiegendes" tut.
