### ISSUE TITLE
MAILTRAP: Update STARTTLS and API Endpoint

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1257]
## Aktuelles Verhalten

We have two announcements to share with you.

    SMTP/POP3 STARTTLS traffic version 1.0 and 1.1 will be deprecated starting from July 1st, 2021. 
    These protocol versions are considered less secure than TLS 1.2 or 1.3; that's why we stop supporting
    them.

    Action required: check if the third-party libraries and tools you use to connect to SMTP by STARTTLS 
    already use TLS 1.2/1.3. If not, please configure them to connect using TLS 1.2 or 1.3 or plain text
    connection.

    API endpoint to retrieve mail headers was updated. It returns all email headers, where strings with
    headers names are normalized to lowercase and underscore. So if your mail has the headers:

    X-Mailer: Super SMTP client
    X-Category: Password Reset 

    the API will return

    {        
        "headers": {
             "x_mailer": "Super SMTP client",
             "x_category": "Password Reset"
         }
    }

    This format allows for backward compatibility and provides you with consistent header names to 
    use in your automation.

    Before that, our API returned the fixed set of headers, regardless of their presence in the mail.

    Action required: check if your code or tests rely on the fixed set of headers returned by Mailtrap API. 
    if yes, update them to rely only on the headers present in your email and don’t forget to use the
    normalized headers' format.

    Check our knowledge base to get more information on API integration.

Hat diese Anpassung einen Einfluss auf unser Projekt?

## Gewünschtes Verhalten

Mails können weiterhin zu Mailtrap geschickt werden.

# Tech-Spec

- [x] Prüfen, ob das Mailversand-gem (mail, version 2.7.1 und `Net::SMTP`, ruby 2.5 core) TLS 1.2 oder TLS1.3 unterstützt
- [x] ggf. aktualisieren oder zumindest Zielversion klären
- [x] Prüfen, ob wir irgendwo Mails von Mailtrap via API holen. Nach meinem Kenntnisstand ist das nicht der Fall. Hier müsste man aber mal durch die Integrations-Umgebungenen gehen und die `RAILS_MAIL_RETRIEVER_CONFIG` ansehen.
- [x] nötigenfalls neues Ticket erstellen, wenn umfangreiches (Ruby-, Rails-) Update nötig ist.

**Comment by kronn** [comment]
Wir verwenden die aktuelle Version des Gems. Dessen Default beim Versand ist, dass nach Möglichkeit STARTTLS verwendet wird. Es wird dabei nicht das Protokoll eingeschränkt. Ruby 2.5 unterstützt auch TLS 1.2 und TLS 1.3.

Wir verwenden nicht die Mailtrap-API und überschreiben die Defaults bei uns nicht.

Die Umstellungen von Mailtrap haben daher keine negative Auswirkung auf uns.
