### ISSUE TITLE
MESSAGE: Generieren von Briefen funktioniert nicht

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1261]
## Aktuelles Verhalten

Beim erstellen von Briefen wird dieser neu im Background geladen. Vermutlich seit dieser Umstellung können gar keine Briefe mehr generiert werden. Auch Briefe mit sehr wenig Adressaten (4) werden auch nach längerer Zeit (30min) nicht geladen.

Meldung `Die Downloads werden vorbereitet, bitte warten. Downloads abbrechen` erscheint aber es wird nichts geladen.

Beispiel: https://die-mitte.puzzle.ch/de/groups/1/mailing_lists/9/messages/50

## Gewünschtes Verhalten

Briefe werden wieder im PDF generiert.

## Schritte zum reproduzieren

1. Generieren von einem PDF von einem Brief: https://die-mitte.puzzle.ch/de/groups/1/mailing_lists/9/messages/50
2. PDF anzeigen

# Tech-Spec

- ...
- https://github.com/hitobito/hitobito/

**Comment by kronn** [comment]
Der Fehler lag in der OpenShift-Konfiguration. Die hochgeladenen Bilder waren nicht im Background-Worker verfügbar. Dies habe ich angepasst.
