### ISSUE TITLE
SPEC: People::Merger

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#1262]
## Aktuelles Verhalten

```
F

  1) People::Merger merge people merges all role attrs
     Failure/Error: expect(person_roles.count).to eq(2)
     
       expected: 2
            got: 3
     
       (compared using ==)
     # ./spec/domain/people/merger_spec.rb:149:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/exe/rspec:4:in `<main>'
```

## Gewünschtes Verhalten

```
.
```

## Schritte zum reproduzieren

1. rspec ./spec/domain/people/merger_spec.rb:126 # People::Merger merge people merges all role attrs
2. bei anderen parallelen Spec-Runs auf der gleichen Codebase war alles grün und lief erfolgreich durch.

# Tech-Spec

- https://github.com/hitobito/hitobito/blob/master/app/domain/people/merger.rb
- https://github.com/hitobito/hitobito/blob/master/spec/domain/people/merger_spec.rb

**Comment by psunix** [comment]
1) People::Merger merge people does not merge role if same role already present on destination person
     Failure/Error: expect(person_roles.count).to eq(1)
     
       expected: 1
            got: 2
     
       (compared using ==)
     # ./spec/domain/people/merger_spec.rb:89:in `block (3 levels) in <top (required)>'
     # /opt/bundle/gems/rspec-core-3.9.1/exe/rspec:4:in `<top (required)>'
     # /opt/bundle/bin/rspec:23:in `load'
     # /opt/bundle/bin/rspec:23:in `<top (required)>'
     # /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
     # /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
     # /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
     # /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
     # /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     # /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
     # /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
     # /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
     # /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
     # /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
     # /usr/local/bundle/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
     # /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
     # /usr/local/bundle/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
     # /usr/local/bundle/bin/bundle:23:in `load'
     # /usr/local/bundle/bin/bundle:23:in `<main>'

**Comment by psunix** [comment]
```
Failures:

  1) People::Merger merge people does also merge deleted roles
     Failure/Error: expect(person_roles.count).to eq(2)
     
       expected: 2
            got: 3
     
       (compared using ==)
     # ./spec/domain/people/merger_spec.rb:118:in `block (3 levels) in <top (required)>'
     # /opt/bundle/gems/rspec-core-3.9.1/exe/rspec:4:in `<top (required)>'
     # /opt/bundle/bin/rspec:23:in `load'
     # /opt/bundle/bin/rspec:23:in `<top (required)>'
     # /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
     # /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
     # /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
     # /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
     # /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     # /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
     # /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
     # /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
     # /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
     # /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
     # /usr/local/bundle/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
     # /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
     # /usr/local/bundle/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
     # /usr/local/bundle/bin/bundle:23:in `load'
     # /usr/local/bundle/bin/bundle:23:in `<main>'

Finished in 1.34 seconds (files took 2.14 seconds to load)
8 examples, 1 failure

Failed examples:

rspec ./spec/domain/people/merger_spec.rb:96 # People::Merger merge people does also merge deleted roles
```
