### ISSUE TITLE
Untergruppe verschieben in die oberste Gruppe

### ISSUE THREAD

**Issue by MartinGantenbein** [hitobito/hitobito#127]
In der Funktion "Gruppe verschieben" steht die oberste Gruppe (die Gruppe, in der ich die Admin-Rolle habe) nicht als Ziel zur Verfügung, es sind nur Untergruppen als neue Parent-Gruppe zur Auswahl

**Comment by codez** [comment]
Danke für den Hinweis. Sinnvollerweise müsste noch das `authorize!(:create)` in der `perform` Methode auf die zu verschiebende Gruppe mit der neuen `parent_id` geändert werden. 

Kannst du einen Pull Request dafür machen?

**Comment by codez** [comment]
Doo, habe den Pull Request #128 erst jetzt gesehen. Könntest du die Anpassung noch machen?

**Comment by codez** [comment]
Pull Request gemerged.
