### ISSUE TITLE
Analyse Old Bugs

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1273]
Analyse of all bugs older than 6 Months --> close if already fixed, rough estimate of the others --> impact vs. effort

https://github.com/hitobito/hitobito/issues?q=is%3Aissue+is%3Aopen+label%3Abug+created%3A%3C2020-11-01+

**Comment by olibrian** [comment]
habe mal etwas aufgeräumt.. still ongoing

**Comment by chrusu** [comment]
Timebox: Pro Bug max. 15 min aufwenden.

**Comment by olibrian** [comment]
Noch einige Tickets geschlossen.
