### ISSUE TITLE
EVENTS: Anmeldung über Multiselect macht Fehler.

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1278]
## Aktuelles Verhalten

Das Type-Ahead bei der Gruppenanmeldung funktioniert nicht mehr und im Hintergrund gibt es eine 500er Fehlermeldung.

![image](https://user-images.githubusercontent.com/17568539/117767231-f1cf4880-b230-11eb-8111-316e2c36b72e.png)
![image](https://user-images.githubusercontent.com/17568539/117767260-fbf14700-b230-11eb-953e-da886a2e1e76.png)

https://sentry.puzzle.ch/pitc/hitobito-backend/issues/32120/?query=is%3Aunresolved

## Gewünschtes Verhalten

Beim Anmelden von mehreren Personen, werden im Type-Ahead-Feld automatisch die verfügbaren Kurse angezeigt.

## Schritte zum reproduzieren

https://jubla.puzzle.ch/groups/1/people?returning=true

# Tech-Spec

- wohl im Zusammenhang mit: #1135

**Comment by olibrian** [comment]
Siehe Ticket https://github.com/hitobito/hitobito/issues/1209
