### ISSUE TITLE
Bump Activerecord to 6.0.3.5

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1283]
https://github.com/hitobito/hitobito/security/dependabot/Gemfile.lock/activerecord/open

**Comment by carlobeltrame** [comment]
This issue doesn't affect us because we don't use Postgres. But some other users of hitobito might.

**Comment by chrusu** [comment]
good to know. 
would it be possible to do something, that it doesn't appear in here?
https://github.com/hitobito/hitobito/security/dependabot
is it needed by other dependencies (and therefore could it still affect our security), or could it be removed from the gems?

**Comment by carlobeltrame** [comment]
We definitely need activerecord, it's a very important core part of Rails. But like most projects, we don't need all of its features. Dependabot cannot know this, but the affected "feature" is one we and our dependencies don't use (i.e. Postgres DB support).
So to remove it from the list, you or someone else with write access can trigger and merge the automated fix PR (once the tests are green).
