### ISSUE TITLE
MODULE: Kurse - NAME ist auf DE und IT leer, wenn Kurs als FR erfasst wurde

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito#1284]
## Aktuelles Verhalten

Wird ein neuer Kurs in der Sprache FR erfasst, wird der Kurs-Name in der Sprache DE und IT nicht angezeigt (z.B. bei den Kursdetails) und es erscheint teilweise (z.B. in der Kursübersicht) stattdessen der Link zum Kurs statt der Name:
![Bildschirmfoto 2021-05-23 um 17 12 57](https://user-images.githubusercontent.com/1453303/119266303-88651780-bbea-11eb-9b04-07d7602d5a1c.png)

## Gewünschtes Verhalten

Ist keine Übersetzung vorhanden, soll die Originalsprache angezeigt werden. (So verhält es sich z.B. korrekt wenn der Kurs auf DE erfasst und nicht übersetzt wurde, nicht aber, wenn der Kurs auf FR erfasst und nicht übersetzt wurde.)

## Schritte zum reproduzieren

siehe https://db.windband.ch/de/groups/1/events/course?returning=true

**Comment by carlobeltrame** [comment]
Duplikat von #1211, ist bereits gefixt. Wenn du bestätigen kannst dass es auf der Integrationsumgebung nicht mehr auftritt brauchts nur noch ein Produktiv-Deployment.

**Comment by betsim** [comment]
Ja, kann ich bestätigen: auf der Integrationsumgebung läuft alles. Sorry, hab ich vergessen zu kontrollieren.

Wäre super, wenn zeitnah deployed würde.
