### ISSUE TITLE
EVENTS: Datum fehlt in API response

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito#1295]
## Aktuelles Verhalten

Im API response fehlt das Datum des Anlasses:

```
{
            "id": "611",
            "type": "events",
            "name": "Concerto di Gala CMO 2021",
            "description": "Concerto di Gala Corpo Musicale Olivonese 2021",
            "motto": "",
            "cost": "",
            "maximum_participants": null,
            "participant_count": 0,
            "location": "Olivone, Sala patriziale",
            "application_opening_at": null,
            "application_closing_at": null,
            "application_conditions": null,
            "state": null,
            "teamer_count": 0,
            "external_application_link": "https://db.windband.ch/de/groups/6855/public_events/611",
            "links": {
                "dates": [
                    "689"
                ],
                "groups": [
                    "6855"
                ]
            }
        }

```
## Gewünschtes Verhalten

Der API response sollte die gleichen Infos/Daten enthalten, wie der CSV-Export des events, zumindest aber zwingend das Datum des Events.

**Comment by carlobeltrame** [comment]
Ein Anlass kann mehrere Daten haben. Die Daten sind beim Anlass verlinkt: `"links": { "dates": [ "689" ] }`. Weiter unten in der API Response, unter `"linked": { "event_dates": [ { "id": "689", "start_at": ... ] }` sind dann die Eckpunkte des verlinkten Anlass-Datums zu finden.

Dieses Format folgt einer etwas älteren Version des [JSON:API](https://jsonapi.org/) Standards.

**Comment by betsim** [comment]
Danke für die Aufklärung, hab ich übersehen!
