### ISSUE TITLE
PERSON: Login-Status in Personenliste und Profil

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1296]
### Personenliste
Eine neue Spalte "Login-Status" in der Personenliste soll aufzeigen, ob eine Person ein Login hat oder nicht. 
Login-Zustand ist sichtbar für alle mit Schreibberechtigung auf der angezeigten Person.
Die verschiedenen Zustände werden durch ein Symbol angezeigt:
 
* Login ist aktiv (login ist vorhanden) (ICON: user-check)
  * mit 2FA vorhanden (ICON: user-shield)
* Einladung wurde verschickt (aber noch nicht angenommen) (ICON: user-clock)
* Kein Login und keine gültige Einladung (mehr) vorhanden / Zugriff entfernt (ICON: user-alt-slash)

Die Spalte soll nur zusätzlich erscheinen, nicht in der Standardansicht. Beim Export ("Spaltenauswahl") soll die Information in Text-Form ausgegeben werden.

Beim "Hovern" mit der Maus, wird in Tooltip-Form ausgegeben, was der Status ist.

![image](https://user-images.githubusercontent.com/1799621/121020842-0e638f80-c7a1-11eb-8910-4e23dd5787f7.png)
*Mockup Personenliste*

### Profil
Der Login-Zustand soll auch im Profil ersichtlich sein. (kann auch bei weitere Angaben sein, muss nicht neben dem Namen ersichtlich sein)
Login-Zustand ist sichtbar für alle mit Schreibberechtigung auf der angezeigten Person.

![image](https://user-images.githubusercontent.com/1799621/121021481-ba0cdf80-c7a1-11eb-818d-e8f525053cd9.png)
*Mockup Profil*

Siehe auch https://github.com/hitobito/hitobito/blob/master/app/helpers/people_helper.rb#L53

# Tech-Spec

Bedingungen für Status:
```ruby
return 'Login ist aktiv' if person.password?
return 'Einladung verschickt aber noch nicht angenommen' if person.reset_password_sent_at.present?
'Kein Login und keine Einladung vorhanden'
```
* Prüfen ob es noch spezielle Status gibt im Zusammenhang mit PR #1586

**Comment by betsim** [comment]
Für den SBV ist dieses Feature zwar nicht vordringlich, aber wir wären daran ebenfalls interessiert.
