### ISSUE TITLE
PERSON: Benutzer-Zugang entfernen

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1297]
Es soll möglich sein, den Zugang eines Benutzers wieder rückgängig zu machen, ohne die E-Mail-Adresse zu löschen. Ausserdem soll eine Person nur durch eine erneute Einladung wieder den Zugang erhalten, wenn dieser mal entzogen wurde. (bzw. soll ein Reset des Passwords nur noch für aktive Accounts möglich sein).

Eine gesperrte Person kann über den Button (Login schicken) wieder entsperrt werden.

OAuth-Anmeldung berücksichtigen.

Bei Anmeldung mit einer "gesperrten" Email-Adresse soll ein Hinweis erscheinen, dass das Login gesperrt wurde. (Externe Eventanmeldung berücksichtigen)
@Michael-Schaer --> Hinweistext bitte liefern

![image](https://user-images.githubusercontent.com/1799621/121025054-13c2d900-c7a5-11eb-839d-77d89000e849.png)
*Mockup Zugang entfernen*

Siehe auch: https://github.com/hitobito/hitobito/issues/1296

## Tech Spec
- [ ] neues Attribut auf Person "locked_permanentely", check devise doc.
  - [ ] ~ev. "locked_temporary"?~ es gibt bereits ein locked_at das für Anti Bruteforce verwendet wird. Der Begriff permanentely soll zeigen das der User gerade vollständig gesperrt ist. Vielleicht gibt es aber auch bereits einen Machano von Devise für diesen fall. Darum der Hinweis check devise doc
- [ ] Offene Frage: Berechtigung?

**Comment by carlobeltrame** [comment]
Weshalb reicht es nicht aus, dass man die Haupt-Mailadresse als weitere Mailadresse eintragen kann? Könnte der neue Button auch einfach das machen?

**Comment by Michael-Schaer** [comment]
Wir möchten eine klare Trennung zwischen der Datenerfassung und der Zugriffssteuerung erreichen.

Als Beispiel zwei verschiedene Use Cases:
- Ich möchte die Angaben von einem Pio in meiner Abteilung erfassen
- Ich möchte einem Pio den Zugriff auf die MiData ermöglichen

Wir können den Zugriff zwar, wenn wir das wissen, über die Haupt-E-Mail steuern. Aber wir wissen nie, ob jemand per Zufall eine E-Mail-Adresse bei der Person einträgt (mit der Absicht, die Daten zu aktualisieren). So wird die Zugriffsverwaltung auch ein Stück weit dem Zufall überlassen.

Unser anliegen ist hier, die Usability-Sicht einzunehmen und die Zugriffssteuerung möglichst einfach und klar zu präsentieren. Eine Abkoppelung des Zugriffs vom Eintrag der Haupt-E-Mail ist denke ich ein wichtiger Teil davon.

**Comment by nchiapol** [comment]
Ein weiterer Punkte die aus meiner Sicht für @Michael-Schaer's Lösung sprechen: 
  - Eine weitere Mailadresse müsste immer auch für den Versand markiert werden.
  - Die Haupt-Mailaddresse ist soweit ich weiss ein wichtiger Teil der Dubletten-Erkennung.

**Comment by carlobeltrame** [comment]
Gute Argumente, merci. Wir werden sehr gut überlegen und testen müssen, dass kein Schlupfloch übrig bleibt mit dem man sich dann doch wieder ein Login erstellen kann, oder mit dem man sich selber oder andere unbefugt "ausschliessen" kann. Bisher war die Annahme bei allen Features und Berechtigungen immer, dass Haupt-E-Mail = Möglichkeit zum Login bedeutet, das muss man hier nun alles aufräumen.

**Comment by nchiapol** [comment]
Auch hier haben wir eben diskutiert und wir sind skeptisch ob diese Trennung von "Haupt-E-Mail" und "Möglichkeit zum Login wirklich sinnvoll ist. Wann ist das wirklich nöitg? Wieso sollte ich ein Login des Pio verhindern wollen? (Und lässt sich das eigentliche Ziel nicht durch korrekte Rollenvergabe erreichen?)
Und was passiert, wenn der Pio sonst noch an einem Ort aktiv ist, dort aber ein Login braucht?

Am ehesten sehen wir eine solche Funktion bei jüngeren TN - aber dort ist die korrekte Lösung der Elternzugang. Dann brauchen die TN auch keine  Haupt-E-Mail mehr und haben also auch kein Login.

**Comment by carlobeltrame** [comment]
@Michael-Schaer Bei der Berechtigung ist mir das gewünschte Vorgehen schon noch nicht so klar. Den Login schicken dürfen bisher praktisch alle allen: Sobald man die andere Person sieht kann man ihr den Login schicken lassen (könnte man vielleicht mal ändern, aber das müssen wir wohl zuerst mit allen hitobito-Nutzerorganisationen abklären, damit wir da keine bestehenden Workflows kaputt machen).

Es dürfen wohl aber sicher nicht alle allen den Zugriff entziehen oder? Sonst könnte ich als Gruppenleiter ja meinen AL ausschliessen / erpressen. Dein Argument mit "vielleicht habe ich der falschen Person den Zugriff erteilt" kann in dieser Form also nicht gelten.
* Via Hauptebene finde ich nicht so toll, so könnte ich ja jemand der rechtmässigen Sperrung entrinnen, indem ich eine Rolle in einer anderen, weniger strengen Ebene als Hauptebene markiere. Die Hauptebene hat bisher soweit ich weiss keinerlei Auswirkungen auf Berechtigungen, sondern nur für visuelle UX-Verbesserungen (Gruppe die nach dem Login offen ist, vorausgewählte Kurs-Gruppen, etc.). Ich verstehe nicht ganz, was du mit "via Gruppenanfragen regeln" meinst.
* Alle Personen die meine Haupt-E-Mail ändern dürfen wäre die konservative Variante, sie entspricht am ehesten dem was wir bisher haben. Aber dann kann es Situationen geben in denen das niemand kann (die Regel ist glaube ich dass man auf alle Rollen Schreibrechte haben muss). Ist also in mindestens den gleichen Situationen nicht ausreichend wie die Variante mit der Hauptebene.
* Wir könnten den manuellen Zugriffsentzug ganz weglassen, und doch nur die Automatisierung laufen lassen. Aber soweit ich verstanden habe ist das Ziel dieser Änderung doch, Missbrauch zu verhindern oder? Für jemanden der Missbrauch betreiben möchte ist das aber dann doch kein Hindernis, diese Person kann sich ja regelmässig einloggen damit die Automatisierung nie greift. Nur legitime User welche hitobito selten verwenden leiden darunter.
* Meine bisher unproblematischste Idee: Alle Personen, welche Schreibrechte auf mich haben dürfen mir den Login entziehen. Ich bin aber noch nicht sicher ob damit der Fall "AL wird ausgeschlossen" wirklich nicht möglich ist.

**Comment by Michael-Schaer** [comment]
Danke für die Ausführung. Eigentlich hätten wir mit der Manuellen Freigabe / Rollenanfrage ja schon ein super Feature, um solche Situationen zu verhindern. Das Feature könnten wir gut auch wieder mal promoten (zumindest die pbs möchte das sowieso machen). 

Wenn das für die Community keine gute Lösung ist, ist es denke ich eher *Alle die meine Haupt-E-Mail ändern dürfen* . Dort entstehen m.E. keine Nachteile im Vergleich zum jetzigen Verhalten.

**Comment by Michael-Schaer** [comment]
Um in diesem Thema wieder etwas Übersicht zu erhalten, habe ich die folgenden Tickets erstellt. Sie sollen das Ticket hier ablösen:

- Sicherheits-Übersicht über Profil https://github.com/hitobito/hitobito/issues/1541
- Passwort-Reset erzwingen https://github.com/hitobito/hitobito/issues/1542
- Bewusste Vergabe von Berechtigungen https://github.com/hitobito/hitobito/issues/1543
- Temporär gesperrte Accounts freigeben https://github.com/hitobito/hitobito/issues/1544
