### ISSUE TITLE
PERSON: Umgang mit inaktiven Benutzerkonten

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1298]
Den Benutzern, die während 3 Monaten kein Login getätigt haben, sollen eine Warnung erhalten, dass der Zugang bald entzogen wird. Nach 5 Monaten ohne Aktivität soll das Login automatisch entzogen werden.

OAuth auch beachten. (z.B. wird last_sign_in_at auch bei OAuth aktualisiert? wie lange ist ein OAuth Token gültig?)

Siehe auch: https://github.com/hitobito/hitobito/issues/1297

**Comment by chrusu** [comment]
@Michael-Schaer gilt dies für alle Benutzerstufen oder erst ab einer bestimmten Berechtigungsstufe?
Als "gewöhnlicher" Pio, der sich einmal im Jahr bei einem Kurs anmeldet fände ich das recht Mühsam.
So werden sehr viele Leute aktiv aus der Midata ausgeschlossen, welche ev. selber ihre Adresse pflegen würden im Falle eines Umzugs und dies so leider nicht mehr können.

**Comment by Michael-Schaer** [comment]
Merci für die Rückmeldung. Vielleicht könnt ihr für die Schätzung auch etwas in der Art überlegen:

- Nach 3 Monaten: Warnung
- Nach 5 Monaten: Passwort wird randomisiert, kann per Reset/Mail wiederhergestellt werden ("zweite Warnung")
- Nach 14 Monaten: Entzug des Logins (braucht Neuzuweisung durch berechtigte Person)

**Comment by Michael-Schaer** [comment]
Wird hier weitergeführt: https://github.com/hitobito/hitobito/issues/2069
