### ISSUE TITLE
2FA: TOTP fertigstellen

### ISSUE THREAD

**Issue by TheWalkingLeek** [hitobito/hitobito#1303]
Im Rahmen der IPA von @TheWalkingLeek wurde 2FA mit TOTP als Faktor eingebaut https://github.com/hitobito/hitobito/tree/feature/2fa_totp
Dieser Branch hat noch ein paar Improvements und Todos, anschliessend soll er gemerged werden.

# Mockup

Visuelle Komponenten sind bereits implementiert

# Tech-Spec

- [x] Rebase
- [x] Generischer SecondFactorAuthenticationController, statt TotpController
  - Authentifizierung/Code Überprüfung in Domain Klasse pro Authentifizierungsfaktor
- [x] Naming konsistent machen
  -  two_factor_authentication -> two_factor_auth
  -  forced -> enforced || required
  - Authentifizierung/Code Überprüfung in Domain Klasse pro Authentifizierungsfaktor
- [x] Benutzerdokumentation ergänzen (ggf. aus IPA von Nils extrahieren)
- [x] sollte zu root redirected werden wenn eingeloggt und eingerichtet: https://github.com/hitobito/hitobito/blob/feature%2F2fa_totp/app/controllers/totp_controller.rb

TOTP kann per Rolle erzwungen werden, indem in den Settings der role type eingetragen werden
- [x] Neu ein class_attribute auf der Rolle gesetzt werden, welche das TOTP enforcen
- [x] Bisher bestehende Lösung mit Settings ausbauen

Das Reset und Deaktivieren des TOTP verläuft aktuell per action auf dem PeopleController
- [x] Actions in eigene Controller extrahieren

IPA liegt im Gitlab: nrauch/ipa

Feature Request PBS https://github.com/hitobito/hitobito/issues/1300

**Comment by chrusu** [comment]
Wieder geöffnet, weil 2FA zwar aktiviert werden kann, beim Login (zumindest auf pbs.puzzle.ch) aber nicht abgefragt wird.

**Comment by carlobeltrame** [comment]
2FA funktioniert jetzt auf pbs.puzzle.ch :+1:
Ab morgen auch auf allen anderen Integrationsumgebungen.
