### ISSUE TITLE
Mail Retreiver Job - connection timeouts

### ISSUE THREAD

**Issue by psunix** [hitobito/hitobito#132]
ein Delayed Job holt in Hitobito im Minutentakt per POP3 die Mails aus einem Catch-All-Konto ab. 

Es kommt beinahe täglich vor das es beim Verbinden Timeouts gibt die dann schlussendlich in einer Exception enden und wir Entwickler dann unnötig mit Nachrichten überflutet werden.

Man könnte den Job so anpassen das er bei einem Connection Timeout erst mal einen Moment wartet und dann einige weiter Male versucht die Verbindung herzustellen. Eine Exception wird dann erst nach einigen Versuchen und einer gewissen Zeit geworfen.

`Errno::ECONNRESET:` Connection reset by peer - SSL_connect

https://github.com/hitobito/hitobito/blob/master/app/jobs/mail_relay_job.rb

**Comment by RolandStuder** [comment]
War nicht mehr Thema, markiere dieses Isseu als `stale`
