### ISSUE TITLE
ABO: Mail Client Web App go live

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#1329]
Der Mail Client ist nun mal auf PBS integration aktiv. 

![image](https://user-images.githubusercontent.com/655627/123978604-489b0800-d9c0-11eb-95bd-640d1e8f90f7.png)

- [x] Testen des Mail Clients durch PBS, Cevi, usw.
- [x] ggf. Verbesserungen umsetzen
- [ ] Benutzeranleitung erstellen / Info im Gui
- [x] In Prod Releasen (Retriever Config anpassen -> Tech-Spec)
- [x] Übergabe der mail Prüfung/Verschiebung vom Wochenverantwortlichen Puzzle/Hitobito zu Admin Benutzer Instanzen

# Tech-Spec

- Damit der IMAP Client funktioniert muss der Server in der Retriever Config von pop3.hitobito.com auf mail.puzzle.ch geändert werden. Gibt sonst einen SSL Cert Error.

**Comment by olibrian** [comment]
Bitte noch weiter konzipieren für Ready. Wer könnte dieses Feature noch kurz im Team vorstellen?

**Comment by chrusu** [comment]
@luca-bruegger 
kannst du genauer spezifizieren, wie der Ablauf eines solchen Tests funktioniert?

**Comment by luca-bruegger** [comment]
@chrusu ja sicher. Soweit ich es verstehe, handelt dieser Test davon die Funktionalität des Features nach dem ändern der Retriever Config zu testen. Also um danach sicherzugehen dass der Imap Client funktioniert wie geplant.

**Comment by chrusu** [comment]
@luca-bruegger gestern ist carlo und mir noch aufgefallen, dass mails von sendern, welche nicht zugelassen sind im Eingang landen, aber (korrekterweise) nicht bearbeitet werden.
Das ist für den Benutzer sehr verwirrend.
Ich bin gerade etwas unschlüssig, was damit passieren sollte. Ab in den Spam-Folder? In Fehlgeschlagen?
Nach einem verschieben nach "Eingang" müsste die Mails dann gesendet werden, obwohl sie eigentlich nicht dürfen?

**Comment by luca-bruegger** [comment]
@chrusu mein Vorschlag wäre das Mail, wie du bereits geschrieben hast, im Eingang zu lassen. Ich würde zusätzlich, damit dem Benutzer der Stand des Mails bereitgestellt werden kann, einen Status hinzufügen. Etwas in der Art von "Sender nicht zugelassen". Was meinst du dazu?

**Comment by chrusu** [comment]
@luca-bruegger das wäre wahrscheinlich die beste Lösung!

**Comment by luca-bruegger** [comment]
@chrusu Toll, dann passe ich das noch an.
