### ISSUE TITLE
Erstellte PDFs von Etiketten werden per Default in gewissen Printdialogen herunterskaliert.

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#133]
# IST:

Wenn ich Etiketten erstelle, z. B. mit http://pbs.puzzle.ch/de/label_formats/5/edit

Beispiel PDF: http://pbs.puzzle.ch/de/groups/10/people.pdf?condense_labels=false&kind=layer&label_format_id=5&name=Gesamte+Ebene&role_type_ids=86-88-71-83-110-84-82-79-72-76-87-85-111-78-80-73-77-94-109-103-104-108-102-90-91-92-93-95-96-97-98-99-100-101-105-106-107-89-67-68-69-70-65-66

Dann erhalte ich ein korrektes PDF, dass den vorgegebenen Massen entspricht.

Wenn ich z. B. auf Mac OS X (10.11.6) das PDF im Print-Dialog öffne, will OS X das PDF nicht mit 100% Skalierung drucken, ausser ich ändere diesen Wert.

<img width="329" alt="pastedgraphic-1" src="https://cloud.githubusercontent.com/assets/194364/20836140/4bff89fa-b89e-11e6-94c1-0133646695a2.png">

[beispiel fake data.pdf](https://github.com/hitobito/hitobito/files/627271/people.mit.fake.data.pdf)

# SOLL

PDFs sollten immer per Default mit 100% Skalierung gedruckt werden. Woran könnte das liegen? OS X scheint das PDF als "Bild" zu interpretieren. Was können wir tun?

**Comment by codez** [comment]
Habe nur https://github.com/prawnpdf/prawn/blob/master/manual/document_and_page_options/print_scaling.rb gefunden. Besteht bei den beiden PDFs ein Unterschied?

[people_default.pdf](https://github.com/hitobito/hitobito/files/637207/people_default.pdf)
[people_none.pdf](https://github.com/hitobito/hitobito/files/637206/people_none.pdf)

**Comment by RolandStuder** [comment]
@codez Nein, ich habe keinen Unterschied gefunden.

**Comment by codez** [comment]
Müssen wir in dem Fall in einem nächsten Sprint anschauen, ob wir überhaupt auf dies Einfluss nehmen können. In Prawn habe ich keine weiteren Optionen gefunden. Bis dahin nehme ich mein Assignement wieder weg.

**Comment by RolandStuder** [comment]
Wir haben hier zu wenig Kontrolle, das hängt von Druckereinstellungen und Betriebssystemen ab. Am PDF selbst können wir da nicht schrauben.
