### ISSUE TITLE
TESTS: IMAP Client Tests fixen

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#1332]
## Aktuelles Verhalten

Tests auf master failen

## Gewünschtes Verhalten

Tests auf master laufen durch

## Schritte zum reproduzieren

https://github.com/hitobito/hitobito

# Tech-Spec

Siehe Diskussion in https://github.com/hitobito/hitobito/pull/1268

**Comment by kronn** [comment]
ggf. https://relishapp.com/rspec/rspec-core/docs/command-line/bisect verwenden, um die abhängigen Specs zu finden.
