### ISSUE TITLE
Verlängerung der Qualifikationen (2021)

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1344]
Hallo zusammen

Ich habe heute von der PBS-Ausbildung erfahren, wie die J+S-Anerkennungen in diesem Jahr verlängert werden sollen. Können wir das wieder zusammen angehen?

Die Infos, die ich erhalten habe, sind die folgenden:

### Verlängerung der Einsatzberechtigung von J+S-Leiterinnen und -Leitern
Auf Grund des Verbots von Kontaktunterricht und Versammlungen konnten J+S-Ausbildungskurse und -Weiterbildungsmodule nicht oder nur eingeschränkt stattfinden. Der Bundesrat hat aus diesem Grund entschieden, die Einsatzberechtigung von J+S-Leiterinnen und -Leitern, welche zuletzt im 2019 eine J+S-Aus- oder Weiterbildung erfolgreich absolviert haben (Status 4), ausserordentlich bis 31.12.2022 zu verlängern. In der Nationalen Datenbank für Sport (NDS) wird das im 3. Quartal operativ umgesetzt und der Status der betroffenen Leiterinnen und Leiter auf «gültig bis 31.12.2022» mutiert.

Nicht betroffen von diesem Entscheid sind J+S-Expertinnen und -Experten, J+S-Coaches sowie J+S-Leiterinnen und -Leiter, welche zuletzt 2018 oder früher eine J+S-Aus- oder Weiterbildung absolviert haben. Wir bitten die Organisatoren der J+S-Kaderbildung, diese Leiterinnen und Leiter bei überbuchten Modulen prioritär zu behandeln.

### Anforderung Datenanpassung
- Alle Qualifikationen «J+S Leiter*in LS/T Jugendsport», die gültig sind «bis 31.12.2021» sind neuerdings gültig «bis 31.12.2022».
- Alle Qualifikationen «J+S Leiter*in LS/T Kindersport», die gültig sind «bis 31.12.2021» sind neuerdings gültig «bis 31.12.2022».

---

@chrusu @carlobeltrame, @nchiapol, @anna-s-jubla

Tech-Spec
---------

- siehe #959
- [x] Datenmigration schreiben
	- [x] Jubla
	- [x] PBS
	- [x] CEVI
- Vormalige Migration (nicht 1:1 kopierbar): https://github.com/hitobito/hitobito_pbs/blob/master/db/migrate/20200706153000_prolong_j_s_qualifications.rb

**Comment by carlobeltrame** [comment]
Ich glaube das beschriebene Vorgehen wird nicht ganz zum richtigen Resultat führen. Da wir letztes Jahr alle diejenigen Anerkennungen auf Dezember 2021 [verlängert haben](https://github.com/hitobito/hitobito/issues/959), welche in den Jahren 2018, 2017 und 2016 vergeben wurden, können wir nun nicht mehr einfach anhand des Enddatums unterscheiden, ob jemand wirklich in 2019 zuletzt eine Aus- oder Weiterbildung absolviert hat.

Da alle drei Jugendverbände die meisten relevanten Kurse in hitobito führen, würde ich stattdessen vorschlagen, bei der Datenanpassung die betroffenen Qualifikationen wirklich via die durchgeführten Kurse zu suchen. Ich kann noch mit dem NDBJS-Entwicklungsteam abklären, ob das tatsächlich möglichst nahe an der Umsetzung in der NDBJS ist.

**Comment by nchiapol** [comment]
Hoi zämä

Wir sind definitiv an einer gemeinsamen Umsetzung interessiert. 

Ein Lösung via Kurse sollte bei uns ziemlich gut funktionieren. Allfällige Spezialfälle könnten ja immer noch von Hand nachgeführt werden.

**Comment by Michael-Schaer** [comment]
Merci fürs Mitdenken! Über die Kurse sollte es bei uns auch klappen!

Die Frage kam noch auf, ob auch Leitungs-Anerkennungen, die durch Expert*innen-Kurse verlängert wurden, betroffen sind. Vielleicht hast du das bereits mit dem NDS herausgefunden, @carlobeltrame ?

**Comment by carlobeltrame** [comment]
Die Verlängerung wurde soweit ich sehe bei der NDS noch nicht umgesetzt, ich würde sicher noch bis dann abwarten.

Bisher scheinen die Bedingungen wie folgt zu sein:
- Person hat als TN eine Ausbildung/Weiterbildung (Jugendsport, Kindersport, Expert) in 2019 gemacht<sup>1</sup>
- Nur Leiteranerkennungen werden verlängert
- Nur Anerkennungen weggefallen seit 01.01.2018, 01.01.2019, 01.01.2020, 01.01.2021 und gültig bis 31.12.2021 werden bis 31.12.2022 verlängert.

Insbesondere werden also die Leitenden der Ausbildung-/Weiterbildungsmodule ihre Anerkennungen nicht verlängert bekommen. Coach- und Experten-Anerkennungen sowie Erwachsenensport-Anerkennungen werden nicht verlängert. Anerkennungen die vor 2017 komplett weggefallen sind (also nicht einfach reaktivierbar) werden nicht verlängert.

<sup>1</sup> Ich sehe widersprüchliche Angaben dazu, ob das Modul bestanden sein muss. Die zeitlich zuletzt gemachte Aussage ist "Egal ob bestanden oder nicht. TN muss im Kurs anwesend gewesen sein." Daher würde ich noch auf die tatsächliche Umsetzung in der NDS warten.

**Comment by tobijuon** [comment]
@carlobeltrame
Habe soeben nachgesehen und bin inzwischen sicher, dass es in der NDS bereits umgesetzt ist.

Unten noch der Text, den J+S am 23. Juli an die Coaches versendet hat:

> **Systematische Verlängerung der Einsatzberechtigung von J+S-Leiterinnen und -Leitern**
> Auf Grund des Verbots von Kontaktunterricht und Versammlungen konnten J+S-Ausbildungskurse und -Weiterbildungsmodule seit April 2020 nicht oder nur eingeschränkt stattfinden. Der Bundesrat hat aus diesem Grund entschieden, die Einsatzberechtigung von J+S-Leiterinnen und -Leitern, welche zuletzt im 2019 eine J+S-Aus- oder Weiterbildung erfolgreich absolviert haben, ausserordentlich bis 31.12.2022 zu verlängern. Die Verlängerung der Anerkennung(en) «gültig bis 31.12.2022» der betroffenen J+S-Leiterinnen und -Leiter wurde in der Nationalen Datenbank für Sport (NDS/SPORTdb) bereits operativ umgesetzt.Da es sich um eine technische Verlängerung der Einsatzberechtigung handelt, die nicht mit einer J+S-Weiterbildung gekoppelt ist, erfolgt keine automatische Aktualisierung des Status in der SPORTdb. Aus diesem Grund müssen Sie alle J+S-Leiterinnen und -Leiter, welche vor der Verlängerung der Einsatzberechtigung im Status «weggefallen» waren und von einer Verlängerung profitiert haben, in jedem Kurs oder Lager entfernen und neu hinzufügen. Ansonsten sind diese J+S-Leiterinnen und -Leiter nicht berechtigt, durch ihre Tätigkeit mit Kindern und Jugendlichen Subventionen auszulösen. Zudem werden sie bei der Kontrolle des Leiter-Teilnehmer-Verhältnisses (Gruppengrösse) nicht mitgerechnet.Nicht betroffen von diesem Entscheid sind J+S-Expertinnen und -Experten, J+S-Coaches sowie J+S-Leiterinnen und -Leiter, welche zuletzt 2018 oder früher eine J+S-Aus- oder -Weiterbildung absolviert haben. Diese Personen müssen im 2021 eine Weiterbildung besuchen, um ihre J+S-Anerkennung zu erneuern/zu verlängern.

**Comment by remojubla** [comment]
Sorry, dieser Thread ging bei der Jubla unter. Wir sind natürlich auch an einer gemeinsamen Umsetzung interessiert!

Bezüglich der Frage (@Michael-Schaer ), ob auch Leitungsanerkennungen, die durch die Teilnahme am Expert*innenkurs verlängert wurden, betroffen sind: Meine Stichproben auf der NDS bei Personen, welche den ExpK im 2019 besucht haben und ansonsten im 2019/2020/2021 keine Weiterbildungen mehr gemacht haben, sagen JA.

**Comment by Michael-Schaer** [comment]
Bitte asap angehen oder bei Fragen melden - merci.

**Comment by remojubla** [comment]
Was ist hier der aktuelle Stand bez. technischer Umsetzung? Braucht ihr noch was von uns? Merci für ein kurzes Update zur Situation.

**Comment by mtnstar** [comment]
Liebe PBS, Jubla und Cevi

wir haben das Datenscript soweit erstellt und die Verlängerung wird automatisch beim nächsten Release eurer Produktionsumgebungen gemacht. 

wollt ihr mit @olibrian oder @chrusu schauen wann ihr den nächsten Release machen wollt?

**Comment by carlobeltrame** [comment]
Es wurden bei der Umsetzung fälschlicherweise auch Qualifikationen von Leitungspersonen verlängert. Diese müssen noch rückgängig gemacht werden.

**Comment by kronn** [comment]
@carlobeltrame Den Code finde ich okay und die Migration läuft bei mir lokal sauber durch. Ich bin unsicher, ob du dieses Issue noch als "Deployment"-Erinnerung haben willst.
