### ISSUE TITLE
EVENTS: Fix BSV-Export

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1348]
Originalticket: #1153 

## Aktuelles Verhalten
Der BSV-Export ist kaputt, weil dessen Filter beim Upgrade der Kursfilter nicht beachtet wurden.

## Gewünschtes Verhalten

Grundsätzlich soll der Export nicht abhängig vom Filter der Kursliste sein. Der Export wird zwei mal pro Jahr für die BSV-Abrechnung über alle Gruppen eingesetzt.

Achtung: Für den Erweiterten BSV-Export gilt das selbe: Wir exportieren jeweils alle Gruppen und filtern nur über die Felder in der eigens dafür vorgesehenen Maske.

### Datumfilter
Kurse dürfen jeweils nur in einem Semester erfasst werden. Dabei ist das Abschlussdatum relevant.

Mit dem neuen Datumsfilter wären viele Kurse in zwei verschiedenen Semester aufgelistet, das wäre also problematisch. Bitte hier den Datumsfilter beim Export auf die alte Logik zurückstellen.

### Gruppenfilter
Wichtig ist, dass ein Export aller Gruppen möglich ist. So wie ich das sehe, ist das jetzt der Fall, wenn keine Gruppe im Suchfeld eingetragen wird.

Wir haben uns gefragt, ob ein Button "alle Gruppen" etwas klarer wäre. Dieser würde einfach das Suchfeld leeren...

**Ja, das ist sicher klarer, wenn die UI-Filter komplett ignoriert werden. Bei uns gibt es keinen Use Case für einen BSV-Export der Kurse pro Gruppe.**

### Kursstatus
Ja, weiterhin nur abgeschlossene Kurse berücksichtigen!

### Verfügbare Plätze
Ja, verfügbare Plätze sollen ignoriert werden!

### Kurskategorie
Ja, die Kategorie soll ignoriert werden!

## Schritte zum reproduzieren

1. Kursliste aufrufen
2. BSV-Export / Erweiterter BSV-Export durchführen
3. Im CSV kontrollieren, ob alles stimmt

# Tech-Spec

- BSV-Filter mit neuem Kursfiltersystem umsetzen
- Achtung beim Datumsfilter, dieser muss sich subtil anders verhalten als der Datumsfilter auf der grossen Kursliste.
- Umsetzung im Youth Wagon

**Comment by chrusu** [comment]
@nchiapol Beim bisherigen BSV-Export konnte man diesen auch nur für eine Gruppe machen. 
Im Rahmen der erweiterten Kursfilter müssen wir die Filterung überarbeiten.
Die Pfadi sieht für die Filterung nach Gruppe keinen Einsatzzweck. Wie sieht das bei der CEVI aus? Braucht ihr dies? Oder könnte man dies weglassen?

**Comment by nchiapol** [comment]
Ich glaube nicht, dass das bei uns im Moment pro Gruppe genutzt wird. Ich frage da aber sicherheitshalber noch bei unseren Geschäftsstellen nach.
