### ISSUE TITLE
RECHNUNGEN: EBICS Vertrag erstellen

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1349]
Matthias schaut mit Stefan, dass wir eine PartnerID kriegen.

Kunde informieren, dass er einen Vertrag abschliessen kann.

**Comment by olibrian** [comment]
Testnetz der PF: https://isotest.postfinance.ch/corporates/user/settings/ebics

**Comment by olibrian** [comment]
Stefan ist informiert.
