### ISSUE TITLE
API: Service Token sieht nicht alle Rollen einer Person

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#1355]
## Aktuelles Verhalten

Gemäss Davide von Ampersand sieht man in der API nur eine Rolle (oder nur Rollen der Gruppe in der URL?) wenn man mit einem Service Token eine Person abruft. Nutzt man hingegen ein persönliches Access Token, sieht man alle Rollen der abgerufenen Personen.

## Gewünschtes Verhalten

Auch Service Tokens können alle (sichtbaren) Rollen sehen.

## Schritte zum reproduzieren

TODO

# Tech-Spec

**Comment by TheWalkingLeek** [comment]
Konnte das lokal so reproduzieren
