### ISSUE TITLE
Restrict Notes visibility

### ISSUE THREAD

**Issue by MartinGantenbein** [hitobito/hitobito#136]
The administrator (:group_and_below_full, :layer_full or :layer_and_below_full) of a group should be able to create a note which is not visible for other administrators (especially for administrators of other groups - a note taken by the administrator of group A should not be visible by the administrator of group B in case the respective person is member in both groups).

**Possible solutions**
- "private" flag on notes: when the flag is selected the note will only be visible to the creator of the note
- Creator of the note can select who (individual persons, groups/roles - same selection criteria as for subscriptions) should be able to see the note

**Comment by RolandStuder** [comment]
Thank you for the suggestion. I agree wholeheartedly that we need better controls here. To have something that scales well. I would suggest something along the lines of:

* Private Note: Only I can see it.
* Layer Note: People with write access from the "current" layer can see it.
* General Note: Also people from other layers can see it.

**Comment by MartinGantenbein** [comment]
@RolandStuder The suggestion sounds fantastic. Rules for "Private" and "General" notes seem to be clear, with "Layer notes" (which would be a wonderful feature!) things might get trickier: Is there a simple (and comprehensible) way to define the "current" layer?

**Comment by RolandStuder** [comment]
How about this @MartinGantenbein 

* You can create private notes, only visible for you
* General notes visible for everybody
* Then notes restricted to a layer one which the person has a role (can be multiple as seen on the mockup)

![image](https://cloud.githubusercontent.com/assets/194364/21134369/e0032e7c-c11d-11e6-92e4-90e2dcdb0dfc.png)

**Comment by MartinGantenbein** [comment]
Looks good but there's still some room for misunderstanding in "layer on which the person has a role":
- does this include any role or only `layer_full` and `layer_and_below_full`?
- in case of `layer_and_below_full`: does this only include the layer with the role or all the layers below?

For the layers (if I have access to more than one) it would probably be preferrable to have checkboxes instead of radio buttons, such that I can select more than one layer (e.g. "Region Bern" and "Region Burgdorf" but not "Region Thun").

I have to mention that layer visibility is only a nice-to-have feature for us, we would be perfectly happy with _private_ and _general_ notes. The added complexity for _layer_ visibility only make sense if other organizations are interrested.

**Comment by RolandStuder** [comment]
Still think this would be a worthy improvement, but marking this as inactve.
