### ISSUE TITLE
Gendering auf Demo Umgebung

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1394]
![image](https://user-images.githubusercontent.com/17568539/134347160-ec1002c0-3bf4-44b5-a36e-e7ac625b7c44.png)

**Comment by olibrian** [comment]
Kannst du noch https://github.com/hitobito/hitobito_generic/blob/master/README.rdoc aktualisieren?

**Comment by TheWalkingLeek** [comment]
README ist aktualisiert: https://github.com/hitobito/hitobito_generic/commit/adec0dc1ec87654ebb0ea07087ba8d2980ac67f1
