### ISSUE TITLE
MESSAGING: Improvements Brieftool 2

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1403]
Weitere Rückmeldungen:
- Das Logo soll noch etwas grösser sein #1410 
- Bei «eigener Versand» soll der Absender ebenfalls auf dem Strich angezeigt sein, einfach ohne «Post CH AG» und ohne «P.P». #1411
  - Der Briefkopf ist somit überflüssig
- P.P. anzeige muss nach Vorgaben der Post sein. Ich nehme an, da haltet ihr euch an die Dokumentation der Post. Jedoch ist gerade A-Priority sehr lange und dann ist nicht mehr der ganze Absender sichtbar. Der Absender muss immer ganz (Adresse, Plz, Ort und Name) ersichtlich sein, sonst ist er sinnlos. (im [Factsheet der Post](https://www.post.ch/-/media/portal-opp/pm/dokumente/briefe-pp-frankieren-factsheet.pdf?vs=7&sc_lang=de&hash=E8B6C39FEB37F83F6C077D62C6F5D084) auf Seite 5 steht, dass für Inland auch P.P.A. funktioniert.) Falls möglich, also bitte lieber P.P.A. damit für den Absender mehr Platz ist. #1414 
- Die PDFs kommen so raus, dass jedes zweite anders aussieht. Beispiel beiliegend zuerst A-Priority dann normale Adresse und so weiter. #1415

Bei beiden Briefen muss aus meiner Sicht der Absender neben dem Logo nicht mehr sein, da ja der Absender zwingend oberhalb des Adressfeldes stehen muss für Kuvert Sichtfenster links.

Wenn sollte nur z.B. «Freundeskreis» « Vereinigung sowieso « stehen und dann das Logo rechts.

Wird standartmässig das «neutrale Logo» hinterlegt, müsste links davon z.B. Die Mitte Kanton St.Gallen oder eben Vereinigung ehemalige Kantonsräte stehen = 1. Zeile des Absenders

# Mockup

![image.png](https://images.zenhubusercontent.com/601915a50c7c845d2798be7c/083d8c9b-b2e4-4aa0-a405-ef55213489ae)

[Test Brief_A-Post.pdf](https://github.com/hitobito/hitobito/files/7243087/Test.Brief_A-Post.pdf)
[Test Brief eigener Versand.pdf](https://github.com/hitobito/hitobito/files/7243088/Test.Brief.eigener.Versand.pdf)

# Tech-Spec

* `LOGO_BOX` vergrössern auf fast die ganze Seitenbreite, und prawn beibringen dass es das Logo nur wenn nötig verkleinern sollte, nicht vergrössern. So können wir auch kleinere Logos unterstützen.
* 

Siehe auch https://github.com/hitobito/hitobito/issues/1405 für weitere Improvements

**Comment by chrusu** [comment]
Muss noch weiter verfeinert werden, im PDF sind noch weitere Anforderungen zu sehen

**Comment by carlobeltrame** [comment]
Wird in den einzelnen Issues #1410, #1411, #1414 und #1415 weitergeführt.
