### ISSUE TITLE
RECHNUNG: Fehlerhafte QR-Codes auf dem Einzahlungsschein.

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1406]
## Aktuelles Verhalten

Bei folgendem Beispiel schlug das einscannen des QR-Codes fehl.
[QR-EZ_Wick A..pdf](https://github.com/hitobito/hitobito/files/7257606/QR-EZ_Wick.A.pdf)

## Gewünschtes Verhalten

Korrekte QR-Codes auf den Rechnungen

## Lösungsbeschrieb

Die Empfängeradresse kann in hitobito als Freitextfeld ausgefüllt werden. Bisher füllt hitobito dann die erste Zeile als "Name", die zweite Zeile als "Adresszeile 1" und die dritte Zeile als "Adresszeile 2" in den QR Code ein. Jetzt ist aber im Standard von SIX festgelegt, dass "Name" optional ist, aber "Adresszeile 1" und "Adresszeile 2" beide zwingend ausgefüllt werden müssen. Das wurde in hitobito bisher nicht berücksichtigt, und führt dann wohl je nach Bank dazu, dass die auf diese Art ungültigen QR-Codes akzeptiert oder eben nicht akzeptiert werden.

Wir müssen uns hier eine Lösung überlegen. Entweder wir füllen die Zeilen quasi von unten her ein: Wenn nur zwei Zeilen ausgefüllt werden lassen wir den Namen weg. Oder wir validieren dass wenn die Rechnung eine QR-Rechnung ist, dass dann auch die Empfängeradresse dreistellig ist. Oder wir tragen für die erzwungenen Zeilen einfach "-" ein. Ich muss mich noch etwas mit der Dokumentation von SIX auseinandersetzen bevor ich mich entscheiden kann was die beste Option ist. Was denkst du?

An den bereits versendeten Rechnungen kann ich leider nichts mehr ändern, die QR Codes sind ja fix so gedruckt. Für zukünftige Rechnungen müsste es schon helfen, wenn die Sekretariate immer eine dreizeilige Adresse (eine Zeile Name, eine Zeile Strasse + Hausnr., eine Zeile PLZ + Ort) in hitobito eingeben.

## Antwort vom Kunden

Grundsätzlich ist mir jede Lösung recht, bei der die Anwender nichts falsch machen können.

Die Adressen werden aber wohl immer in der Logik so eingegeben:
Parteiname
Strasse
PLZ Ort

Offenbar gibt es aber auch Adressen ohne Strasse also würde von unten auffüllen wohl gut klappen.

Ich wäre froh um einen Lösungsansatz, wenn du die Dokumentation durch hast.

Danke jedenfalls bereits für die Antwort.

# Tech-Spec

- ...

- https://github.com/hitobito/hitobito/

**Comment by nchiapol** [comment]
related: https://github.com/hitobito/hitobito_cevi/issues/89

**Comment by olibrian** [comment]
fixed by #https://github.com/hitobito/hitobito/issues/1825
