### ISSUE TITLE
MESSAGE: Datum und Ort auf Briefen

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#1408]
Oberhalb der Betreffzeile in Briefen und Rechnungsbriefen soll optional eine Zeile für Datum und Ort stehen können.

Siehe auch #1405

# Mockup

![Screenshot from 2021-10-05 13-54-18](https://user-images.githubusercontent.com/7566995/136017622-aa9b4dc7-f15f-4a43-ba00-b913480f18e7.png)

# Tech-Spec

- Umsetzung im Core
- Neues optionales einzeiliges Freitextfeld auf Briefen und Rechnungsbriefen, welches beim Drucken des Briefs oberhalb der Betreffzeile ins PDF gerendert wird.
- Wenn das Feld leer ist soll auch auf dem PDF kein Platz dafür verschwendet werden
- Kein dynamischer Inhalt nötig, beim PDF rendern auch diesen Teil stampen aus Performancegründen

**Comment by kronn** [comment]
PR wurde reviewed und gemerged, Feature lokal getestet
