### ISSUE TITLE
SportDB Export macht ungewollte Überschreibungen bei leeren Feldern

### ISSUE THREAD

**Issue by sihu** [hitobito/hitobito#1413]
## Aktuelles Verhalten

Wenn ich als Coach einen SportDB-Export von TNs eines Lagers mache, wird bei allen TN ohne AHV Nummer die bestehende AHV-Nummer auf der SportDB überschrieben. Dies ist sofern problematisch, als dass Änderungen auf der SportDB nicht mehr selbst rückgängig gemacht werden können sondern via Kantonales Sportamt bestätigt oder abgelehnt werden müssen, sobald man das J+S-Angebot abschliesst.

## Gewünschtes Verhalten

Leere Felder werden nicht überschrieben.

## Schritte zum reproduzieren

1. Zu Lager navigieren
2. Export > CSV > SportDB
3. Import auf SportDB
4. TN übernehmen ankreuzen

# Tech-Spec

Ich denke, ich habe das Problem bereits gefunden. Wenn man die Beispieldatei herunterlädt, so werden leere Felder nur durch `;` getrennt:

```csv
NDBJS_PERS_NR,GESCHLECHT,NAME,VORNAME,GEB_DATUM,AHV_NR,STRASSE,PLZ,ORT,LAND,NATIONALITAET,ERSTSPRACHE,KLASSE/GRUPPE
,m,Huber,Simon,1.1.1900,,Test,8,8,8,8,8,8
```

wenn ich den Export auf MiData mache, werden leere Felder so exportiert:

```csv
NDBJS_PERS_NR,GESCHLECHT,NAME,VORNAME,GEB_DATUM,AHV_NR,STRASSE,PLZ,ORT,LAND,NATIONALITAET,ERSTSPRACHE,KLASSE/GRUPPE
"",m,Huber,Simon,1.1.1900,"",Test,8,8,8,8,8,8
```

Das wird vom SportDB-Import offensichtlich anders gehandhabt. Wie mir gerade telefonisch vom Kt. Sportamt GR bestätigt wurde, besteht das Problem nicht, wenn man das obere CSV verwendet.

Ich denke, dass der Fix relativ dringend ist, da viele Coaches sonst Daten auf der SportDB ungewollt überschreiben. Leider bekommt man keinen Hinweis, welche Felder überschrieben werden.

**Comment by carlobeltrame** [comment]
Merci für die detaillierte Beschreibung, habs gleich gefixt. Sollte nach dem nächsten Produktivdeployment behoben sein. Testen kannst dus morgen auf der Testumgebung.

**Comment by sihu** [comment]
@carlobeltrame hammer! Danke. Könnte es bei weiteren Feldern ebenfalls noch der Fall sein? e.g. `entry.j_s_number.to_s.try(:gsub, /\D/, '')` => `entry.j_s_number.to_s.try(:gsub, /\D/, nil)`? ich denke dort it's nicht so problematisch, da sie nicht überschrieben werden kann.

**Comment by carlobeltrame** [comment]
Bin mir nicht sicher:
- NDBJS_PERS_NR kann man glaube ich nicht überschreiben
- GESCHLECHT ist ein Pflichtfeld
- NAME unsicher, aber ich sehe keinen Grund wieso das jemand nicht in hitobito aber schon in der NDS haben möchte
- VORNAME unsicher, aber ich sehe keinen Grund wieso das jemand nicht in hitobito aber schon in der NDS haben möchte
- GEB_DATUM ist ein Pflichtfeld
- AHV_NR haben wir behandelt
- STRASSE unsicher, aber ich sehe keinen Grund wieso das jemand nicht in hitobito aber schon in der NDS haben möchte
- PLZ unsicher, aber ich sehe keinen Grund wieso das jemand nicht in hitobito aber schon in der NDS haben möchte
- ORT unsicher, aber ich sehe keinen Grund wieso das jemand nicht in hitobito aber schon in der NDS haben möchte
- LAND unsicher, aber ich sehe keinen Grund wieso das jemand nicht in hitobito aber schon in der NDS haben möchte
- NATIONALITAET ist ein Pflichtfeld
- ERSTSPRACHE könnte allenfalls betroffen sein
- KLASSE/GRUPPE könnte allenfalls betroffen sein

**Comment by sihu** [comment]
@carlobeltrame danke für die übersichtliche Zusammenstellung. bin absolut einverstanden. Ich glaube auch nicht, dass man es in der NDS haben möchte aber nicht auf hitobito. Es kann aber aus meiner eigenen Coach-Erfahrung gut sein, dass jemand aus einem anderen Verein bereits erfasst ist, aber wir diese Infos noch nicht in der MiData haben. Sofern würde es vielleicht schon Sinn machen, Felder eben nicht leer sondern einfach als null-Value zu übergeben `;;`

**Comment by carlobeltrame** [comment]
Guter Punkt @sihu. Habe jetzt sichergestellt dass alle leeren Strings als `nil` rausgehen.
