### ISSUE TITLE
PERSON: "digitale Korrespondenz" Flag der PBS im Haushalt teilen

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#1416]
Bei der PBS haben wir ein Flag "prefers_digital_correspondence" auf jeder Person. Damit kann die Person angeben dass sie lieber digital (via E-Mail) angeschrieben wird statt via Briefpost. Das Flag wird dann in Abo-Exporten mitexportiert, sodass die Versender von Briefen und Zeitschriften es wenn möglich berücksichtigen können.

Bei Haushaltsexporten, was bei der PBS für Zeitschriften inzwischen weit verbreitet ist, gibt es dieses Flag bisher nicht, weil unklar ist, wie das Flag kombiniert werden soll wenn die Mitglieder des Haushalts sich nicht einig über die digitale Korrespondenz sind. Als Lösung soll das Flag ähnlich wie die Adresse nur noch für den ganzen Haushalt gesetzt werden können.

@Michael-Schaer hat in [einem Branch](https://github.com/hitobito/hitobito_pbs/compare/master...Michael-Schaer:digital_correspondence_to_household) bereits mit der Implementation begonnen. Diese Implementation soll nun noch fertiggestellt werden.

Siehe auch hitobito/hitobito_die_mitte#166, wo wir gerade den Haushalts-Export umbauen sodass mehr als nur der Name kombiniert werden kann.

# Mockup

![Screenshot from 2021-10-07 08-49-28](https://user-images.githubusercontent.com/7566995/136333678-0a9a33f1-7cae-4c02-94be-134b111bd1bc.png)

# Tech-Spec

- Basieren auf https://github.com/hitobito/hitobito_pbs/compare/master...Michael-Schaer:digital_correspondence_to_household
- Umsetzung im PBS Wagon
- Im Core in app/views/contactable/_address_fields.html.haml muss noch ein `render_extensions` eingefügt werden
- In Javascript sicherstellen dass das "digitale Korrespondenz"-Flag zusammen mit dem Haushalt aktualisiert wird (noch unklar wie im Wagon das JS vom Core erweitert werden kann, allenfalls via [Events](https://developer.mozilla.org/en-US/docs/Web/Events/Creating_and_triggering_events))
- Im Households-CSV-Export der PBS das "digitale Korrespondenz"-Flag eines beliebigen Mitglieds des Haushalts exportieren (hitobito_pbs/app/domain/pbs/export/tabular/people/households_full.rb)
- Aufräumen / finishing touches
- Tests

**Comment by chrusu** [comment]
Timebox von 1.5 PT

**Comment by severinraez** [comment]
PRs:

* [Core](https://github.com/hitobito/hitobito/pull/1467)
* [Wagon](https://github.com/hitobito/hitobito_pbs/pull/209)
