### ISSUE TITLE
EBICS: weitere Banken bereitstellen

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#1427]
EBICS wurde erstmal exemplarisch mit der Postfinance integriert.

Neu sollen jetzt auch weitere Schweizer Banken vorkonfiguriert werden, um eine breitere Nutzung des Features zu ermöglichen.

Banken:
- Kantonalbanken (24)
- UBS
- Raiffeisen
- CreditSuisse
- weitere?

Tech Spec
---------

- Es sollte ausreichen, wenn die Hashwerte in die settings.yml übernommen werden.
- Vielleicht kann man kurz prüfen, ob eine Extraktion in eine eigene Datei oder sogar
	in die DB sinnvoll ist. Ziel ist aber erstmal, die weiteren Banken hinzuzufügen.
- Aktuell baut eine erfolgreiche Bankenanbindung darauf auf, dass die Auftragsart
	Z54 unterstützt wird. Die bitte jeweils kurz prüfen.
- Siehe auch #1334

Alternative: Config in die DB verschieben, UI bauen und den Kunden die Daten
eintragen lassen. Vorkonfiguration und Update wäre über Production-Seeds
möglich. 

Umsetzungsplan "settings erweitern"
-----------------------------------

- [x] Bankdaten hinzuzufügen
	- [ ] Kantonalbanken
		- [ ] Aargau/Solothurn (https://www.akb.ch/)
		- [ ] Appenzell (http://www.appkb.ch/)
		- [x] Tessin (https://www.bancastato.ch/)
		- [ ] Genf (https://www.bcge.ch/)
		- [ ] Jura (https://www.bcj.ch)
		- [ ] Neuenburg (https://www.bcn.ch)
		- [ ] Waadt (https://www.bcv.ch)
		- [ ] Basel Stadt (https://www.bkb.ch)
		- [ ] Basel Land (https://www.blkb.ch/)
		- [x] Bern (https://www.bekb.ch)
		- [ ] Freiburg (https://www.bcf.ch)
		- [ ] Glarus (https://glkb.ch/)
		- [ ] Graubünden (https://www.gkb.ch/)
		- [x] Luzern (https://www.lukb.ch/)
		- [ ] Nidwalden (https://www.nkb.ch/)
		- [ ] Obwalden (https://www.okb.ch/)
		- [ ] Schaffhausen (https://www.shkb.ch/)
		- [ ] Schwyz (https://www.szkb.ch/)
		- [x] St. Gallen (https://www.sgkb.ch/)
		- [x] Thurgau (https://www.tkb.ch/)
		- [ ] Uri (https://www.ukb.ch/)
		- [ ] Wallis (https://www.bcvs.ch/)
		- [x] Zug (https://www.zugerkb.ch/)
		- [ ] Zürich (https://www.zkb.ch/)
	- [x] UBS (https://www.ubs.com/ch/de/corporates/payment-solutions/cash-management/connection-ubs/ebics.html)
	- [x] Raiffeisen (https://www.raiffeisen.ch/rch/de/firmenkunden/liquiditaet-und-zahlungsverkehr/electronic-banking/ebics.html)
	- [x] CreditSuisse (https://www.credit-suisse.com/media/assets/microsite/docs/zv-migration/verbindungsparameter-de.pdf)
- [x] CHANGELOG-Eintrag hinzufügen

Umsetzungsplan "Self-Service UI"
--------------------------------

- Config komplett in die DB verschieben
	- [ ] Migration/Model PaymentProvider hinzuzufügen
		- name (varchar 255, not null)
		- url (varchar 255, not null)
		- host_id (varchar 255, not null)
		- encryption_hash (varchar 255, not null)
		- authentication_hash (varchar 255, not null)
	- [ ] Validation
		- url ist eine gültige URL
		- host_id besteht nur aus Grossbuchstaben
		- encryption_hash ist E002-Hash (SHA256)
		- authentication_hash ist X002-Hash (SHA256)
	- [ ] Hinweis, dass "EBICS 2.5" unterstützt wird
	- [ ] Controller für CRUD-Interface, um PaymentProvider zu verwalten
	- [ ] In Einstellungen verorten
	- [ ] Zugriff für Personen mit `:admin`-Permission
- [ ] bisherige settings in seeds verschieben
- [ ] evtl weitere Banken hinzufügen (siehe Umsetzungsplan "settings erweitern")
- [ ] CHANGELOG-Eintrag hinzufügen

**Comment by olibrian** [comment]
Präferenz liegt auf Settings erweitern, da die Anzahl Banken wohl eher statisch sind und ein Benutzer mit dem GUI überfordert ist.
