### ISSUE TITLE
Einladungen bei Anlässen: Bei Kursen deaktivieren

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1430]
Die neue Funktion "Zu Anlässen einladen" der CEVI findet die PBS grundsätzlich super, aber nicht für die Kurse.

https://github.com/hitobito/hitobito/issues/1276

Bitte im PBS-Wagon deaktivieren, aber nur für die Kurse, nicht für alle Anlässe.

## Tech spec
- class_attr `has_invitations` o.ä. auf `Event` und Subklassen einführen
- In `InvitationAbility` und `EventAbility` die Berechtigungen für Einladungen von diesem class_attr abhängig machen
- Im PBS-Wagon dieses class_attr für Kurse (Event::Course) auf `false` setzen

**Comment by Michael-Schaer** [comment]
Hier stimmt etwas nicht mehr: Die Einladungen sind bei Kursen wieder drin.
