### ISSUE TITLE
Tags: AddressValidator schlägt fehl

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#1431]
## Aktuelles Verhalten

Gleich wie bei #1321 schlägt der AddressValidator fehl, wenn das Tag bereits vorhanden ist.

## Gewünschtes Verhalten

AddressValidator (und andere Mechanismen die automatisiert Tags vergeben) schlagen nicht fehl wenn das Tag bereits vergeben ist.

## Schritte zum reproduzieren

Informationen zu einem spezifischen Fall auf Sentry: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/43791/

# Tech-Spec

- https://github.com/hitobito/hitobito/blob/master/app/domain/contactable/address_validator.rb#L51 nutzt `find_or_create_by!`, was dann aber zu folgendem Validierungsfehler führt:

`ActiveRecord::RecordInvalid: Gültigkeitsprüfung ist fehlgeschlagen: Tag ist bereits vergeben`

Dabei nutzen wir ja `find_or_create_by!` genau darum, um kein neues Tag zu erstellen wenn schon eines existiert. Vermutlich sind unsere Such-Parameter zu streng, und wir sollten eher etwas ähnliches wie folgt machen:
```ruby
ActsAsTaggableOn::Tagging
        .find_or_create_by!(taggable: person, tag: tag)
        .tap do |t|
          t.update!(hitobito_tooltip: email, context: :tags)
        end
```
- [ ] Überprüfen ob dasselbe Problem noch an anderen Stellen existiert

**Comment by njaeggi** [comment]
Will be fixed with #1431
