### ISSUE TITLE
EVENTS: Kurs-Liste ist z.T. gepaged

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito#1449]
## Aktuelles Verhalten

https://db.cevi.ch/groups/3030/events/course?sort=name&sort_dir=asc&year=2022
und 
https://db.cevi.ch/groups/3030/events/course?sort=dates_full&sort_dir=asc&year=2022

zeigen eine unterschiedliche Anzahl von Einträgen. Im zweiten Link fehlen alle Termine ab Ende Mai. 
Die werden angezeigt via:
https://db.cevi.ch/groups/3030/events/course?sort=dates_full&sort_dir=asc&year=2022&page=2

Via API wird die Liste gepaged unabhängig von der Sortierung - im Json ist "total_pages" aber 1...

Leider funktioniert aktuell der Workaround mit`page=2` nicht mehr - weder im Webinterface, noch via API. Entsprechend lassensich nun nicht mehr alle Kurs via API auslesen.

## Gewünschtes Verhalten

Es werden immer alle Kurse angezeigt/exportiert oder eine Seitennavigation angezeigt und unterstützt.

Es sollte hier die einfachste Lösung gewählt werden um die Kurse wieder zugänglich zu machen. Eine saubere Lösung kann in einem weiteren Issue erledigt werden (Issue muss noch erstellt werden).

# Tech-Spec

* https://github.com/hitobito/hitobito/blob/master/app/controllers/events_controller.rb#L60

# ToDo

- [ ] Fix implementieren damit alle Kurse via API zurückgegeben werden, entsprechender spec ergänzen
- [ ] Follow-Up Ticket erstellen für saubere/performante Lösung falls Bedarf

**Comment by kronn** [comment]
ich habe es so angepasst, dass nicht mehr kaminari nach der gesamtzahl der Seiten gefragt wird. Wenn eine Seite 0 Ergebnisse liefert, dann zeige ich die erste an. eine echte lösung wäre, kaminari wieder die richtige Seitenzahl finden zu lassen.

**Comment by daniel-illi** [comment]
das pagination geht anscheinend durch das `.with_group_id(relevant_group_ids)` im filter scope kaputt.
`Event::Filter#scope`
