### ISSUE TITLE
PERSONEN: Etikettenexport schlägt fehl

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1454]
## Aktuelles Verhalten

![image.png](https://images.zenhubusercontent.com/601915a50c7c845d2798be7c/d06ad0bd-45f5-44e5-be78-bbef4850596a)

Fehlermeldung beim Etikettendruck.

https://puzzle.hitobito.com/de/groups/1/people.pdf?household=true&label_format_id=2&returning=true

## Gewünschtes Verhalten

Etiketten können wieder gedruckt werden.

Specs sind vorhanden.

## Schritte zum Reproduzieren

1. https://puzzle.hitobito.com/de/groups/1/people?returning=true
2. ![Screenshot_20211101_093918.png](https://images.zenhubusercontent.com/601915a50c7c845d2798be7c/74c98c14-81db-45e2-bba8-fe2dfe165c17)
3. hitobito.com - Version 1.26.28

## Sentry

- https://sentry.puzzle.ch/pitc/hitobito-backend/issues/45009

**Comment by maede97** [comment]
Auch beim Cevi in der Produktion.
Mit `https://db.cevi.ch/groups/92/events/2479/participations.pdf?household=true&label_format_id=6&returning=true` gibts 500, ohne Haushalte (household=false) gehts.
