### ISSUE TITLE
PEOPLE: Benutzer "Ohne Rollen" erscheinen nicht in der Gruppe "Ohne Rollen"

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1456]
## Aktuelles Verhalten

Werden bei einer Person alle Rollen gelöscht, erscheint sie nicht in der Gruppe "Ohne Rollen" der Hauptsektion.

## Gewünschtes Verhalten

Person erscheint in der Gruppe "Ohne Rollen"

## Schritte zum reproduzieren

1. auf https://db.svse.ch/de/groups/161/people?returning=true eine beliebige Person auswählen und alle Rollen löschen
2. Gruppe "Ohne Rollen" aufrufen

Beispiel einer Person, welche nicht in "Ohne Rollen" erschien.
https://db.svse.ch/de/groups/49/people/3128/history

## Fragen

- [ ] Sind die Rollen vllt noch zu "jung"? (siehe `Settings.role.mininum_days_to_archive`, Vorgabe: 7 Tage).
- [ ] Ist "Ohne Rollen" eher "Ohne aktive Rollen"?
- [ ] Braucht es ggf. besondere Rechte, um dort Personen anzuzeigen (-> virtuelle Gruppe ggf. nicht anzeigen)

**Comment by chrusu** [comment]
@TheWalkingLeek hast du hier bereits was gemacht? Scheint wieder zu funktionieren...

**Comment by TheWalkingLeek** [comment]
Zumindest nicht bewusst, nein.

**Comment by chrusu** [comment]
Das Problem besteht weiterhin, die "zu junge" Rolle, welche am Anfang erfolgsversprechend aussah, scheint zumindest nicht die gesamte Lösung zu sein.
Muss weiter analysiert werden

**Comment by olibrian** [comment]
Wir schliessen dieses Ticket und gehen aktuell davon aus, dass die Rollen noch zu "jung"? (siehe Settings.role.mininum_days_to_archive, Vorgabe: 7 Tage) waren. Falls das Problem wieder auftritt, kann dieses Ticket wieder geöffnet werden.
