### ISSUE TITLE
Testpipeline für DEV-Setup

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1461]

**Comment by carlobeltrame** [comment]
Machen wir das nicht? Gibts da ein anderes Issue?

**Comment by olibrian** [comment]
Habe es gestern mit Tobias besprochen und wir wussten beide nicht mehr was hier das Ziel war, da es keine Beschreibung im Ticket gibt.

**Comment by carlobeltrame** [comment]
Es geht darum, eine Art Unit Tests fürs development-Repo zu machen, um sicherzustellen dass das jederzeit problemlos gemäss Dokumentation funktioniert
