### ISSUE TITLE
Verifizierung Lager einreichen für Lagerleitung

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1465]
Timebox: 12h

Beim Lager-Prozess kommt es häufig vor, dass die Lagerleitung nicht alle notwendigen Felder ausfüllt. Trotzdem informiert sie den Coach, dass das Lager eingereicht werden kann. Beim Klick auf "Einreichen" werden dem Coach dann alle fehlenden Informationen in der Fehlermeldung angezeigt.

Diese Fehlermeldung könnte aber auch schon der Lagerleitung angezeigt werden. So könnte sie die Infos komplett einfüllen, bevor sie den Coach informiert. Dies würde den beiden viel Kommunikation ersparen.

### Änderungswunsch

~Ein Button «Überprüfen» soll für Lagerleiter eingebaut werden. Dieser sendet die Lagermeldung nicht wirklich ab (dies darf nur der Coach) sondern er führt lediglich die Verifizierung der Daten aus und zeigt die entsprechenden Fehlermeldungen an.~

Die Flashmessage soll immer auf Lager#Show angezeigt werden wenn Lagerleiter/Coach die Seite besucht. (ohne Button wie im Mockup)

Flashmessage wird nur angezeigt, wenn nicht bereits ein Flash-Warning vorhanden ist.

#### Negatives Resultat
![Ueberpruefen](https://user-images.githubusercontent.com/1799621/140335191-39d1dde9-74b2-4773-ad84-3480ee474b2c.png)

#### Positives Resultat
![Ueberpruefen2](https://user-images.githubusercontent.com/1799621/140345337-3f6fdc4f-c2c9-41d4-923d-143f2017f3b6.png)

## Hintergrund
Originales Ticket: https://trello.com/c/iy1OcVTm/230-verifikation-lagermeldung-f%C3%BCr-lagerleitung-zug%C3%A4nglich-machen

## Tech-Spec

- im pbs wagon
- https://github.com/hitobito/hitobito_pbs/blob/master/app/controllers/pbs/events_controller.rb

**Comment by chrusu** [comment]
@Michael-Schaer Wie wäre es damit, jeweils beim Anzeigen des Info-Tabs ein "Warning" zu zeigen mit den fehlenden Infos. Analog Screenshot, aber in gelb/orange.
Somit könnte auf den Button verzichtet werden, zusätzlich ist es etwas aufdringlicher.

**Comment by simfeld** [comment]
> @Michael-Schaer Wie wäre es damit, jeweils beim Anzeigen des Info-Tabs ein "Warning" zu zeigen mit den fehlenden Infos. Analog Screenshot, aber in gelb/orange. Somit könnte auf den Button verzichtet werden, zusätzlich ist es etwas aufdringlicher.

Finde ich auch gut 👍

**Comment by Michael-Schaer** [comment]
Ja, sollte so passen.
