### ISSUE TITLE
EBICS: Log für Hintergrundaktivität

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1472]
:warning: vor Umsetzung dieses Feature berücksichtigen: https://github.com/hitobito/hitobito/issues/1840
konzeption anpassen

Falls EBICS eingerichtet ist, werden nächtlich via Background Job Zahlungsinformationen abgerufen. 
Damit dies nachvollziehbar ist, sollte wir dies logen. Interessant könnte sein:
* Ist der Job gelaufen
* Wie viele Zahlungen wurden abgerufen
* Wie viele Zahlungen konnten einer Rechnung zugewiesen werden
* Welche Zahlungen konnten nicht zugewiesen werden (Datum, Betrag, Name, etc)

# Plan
Erster Schritt wäre diese Informationen im Hintergrund zu loggen
Weitere Schritt: die Informationen dem Benutzer sichtbar zu machen.

# Tech-Spec

- PUB/SUB mit `ActiveSupport::Notifications`
- https://edgeguides.rubyonrails.org/active_support_instrumentation.html
- Zuerst nur Logging der EBICS-Jobs
- Mit geringem Aufwand erweiterbar, um auch andere Hintergrundjobs zu loggen
	- SphinxIndexing
	- AddressValidation
	- AddressImport
	- ...
- Mehrere Events:
	- `job_started.hitobito`: Nur den Namen und die ID des jobs als Payload, um das Objekt anzulegen
	- `job_finished.hitobito`: Payload enthält neben Name und ID des jobs auch inhaltliche Informationen, die erst nach der Abarbeitung des Job bekannt sind
	- `job_runtimes.hitobito`: Wrapper um alles herum, um started_at und finished_at korrekt setzen zu können
- die Gruppen-ID wird optional mitgegeben, wenn ein Job etwas auf einer Gruppe macht. Für die spätere Darstellung in der richtigen Gruppe ist dies notwendig.
- `BackgroundJobLog`s ohne Gruppen-ID müssen dann ggf. in einem zentralen Ort angezeigt werden.

# Umsetzungsplan Schritt 1

- [x] `BackgroundJobLog`
	- [x] Migration
		- `job_id` int NOT NULL
		- `job_name` varchar NOT NULL
		- `started_at` timestamp
		- `finished_at` timestamp
		- `payload` mediumtext
		- `group_id` int
		- "timestamps"
	- [x] Payload ist ein serialisiertes Hash
- Ebics::ImportJob erweitern:
	- [x] `ActiveSupport::Notifications.instrument 'job_started.hitobito', name: self.class.name, id: self.id`
	- [x] `ActiveSupport::Notifications.instrument 'job_finished.hitobito', name: self.class.name, id: self.id, count:, success:, errror:, whatever:`
	- [x] `ActiveSupport::Notifications.instrument 'job_runtimes.hitobito', name: self.class.name, id: self.id { JOB_PERFORM }`
- Domain-Objekt `BackgroundJobLogger` erstellen
	- [x] 3x `ActiveSupport::Notifications.subscribe EVENT_NAME { |event| HANDLING_BLOCK }`

**Comment by chrusu** [comment]
Timebox: 4h

**Comment by kronn** [comment]
Mit #1583 werden Fehlermeldungen, die während des Setup passieren, unterdrückt. Diese könnte eventuell auch im Log landen, damit man sieht, dass da etwas passiert ist, wenngleich nicht erfolgreich.
