### ISSUE TITLE
PEOPLE: Benachrichtigung bei Selbstregistrierung

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#1483]
Mit #1441 soll neu eine Benutzerregistrierung realisiert werden.

Ergänzend dazu soll eine entsprechende Benachrichtigung per E-Mail an eine oder mehrere Personen erfolgen falls sich jemand neu registriert.

Neues Feld auf Gruppe: E-Mail Benachrichtigung Registrierung an

# Tech-Spec

- Neues Feld auf Group: self_registration_notification_email, string, default: nil
- validieren auf gültige E-Mail (true mail)

**Comment by carlobeltrame** [comment]
> Wer soll benachrichtigt werden?

Die Idee im originalen Issue ist:
> Angabe E-Mailadresse, welche über eine neue Registration informiert werden soll, pro registrierbare Gruppe.

Also an demselben Ort wo ich freie Registration für meine Gruppe aktiviere, sollte ich auch eine Benachrichtigungs-Mailadresse angeben können.
