### ISSUE TITLE
Einladen zu Kurs funktioniert nicht

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1495]
![image](https://user-images.githubusercontent.com/17568539/143241358-4430dd09-4039-4c97-9eb9-7f06d27f9fd0.png)

https://svse.puzzle.ch/de/groups/26/events/24/invitations

![image](https://user-images.githubusercontent.com/17568539/143241447-e878525a-0d86-4545-904d-a97c9c656833.png)

### Tech spec
- Die Berechtigung zum Anzeigen des Buttons (ist aktuell wohl zu freizügig): https://github.com/hitobito/hitobito/blob/master/app/views/event/invitations/_actions_index.html.haml#L6
- Die Berechtigung zum eigentlichen Interagieren mit Einladungen: thttps://github.com/hitobito/hitobito/blob/master/app/views/event/invitations/_actions_index.html.haml#L6
- InvitationAbility: https://github.com/hitobito/hitobito/blob/master/app/abilities/event/invitation_ability.rb

**Comment by nchiapol** [comment]
Das Problem tritt auch bei uns auf. Ich als Admin der Datenbank kann einladungen erstellen, die Mitarbeiter der Geschäftsstelle haben dieses Recht aber nicht. Genauer eingeschränkt haben wir das Problem noch nicht.

**Comment by chrusu** [comment]
Auch wir haben es noch nicht eingeschränkt. Es scheint, wie du ja bereits selber andeutest ein Berechtigunsproblem zu sein.
