### ISSUE TITLE
Header "Daten" in Confimation PDF is spelled wrong

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#150]
For some reason the date label is set to downcase, should not be like that, it leads to this spelling

![image](https://cloud.githubusercontent.com/assets/194364/21356647/b81514ba-c6d2-11e6-8944-f792fb3caf39.png)

should be probably changed here:
https://github.com/hitobito/hitobito/blob/92db15a8e375d93f9634c3138335169e8dd6b76a/app/domain/export/pdf/participation/person_and_event.rb#L69

**Comment by kronn** [comment]
This seems to be done with https://github.com/hitobito/hitobito/commit/8f25f2635c3982f541f46672b6f8d58e9906585f, which is in `master`.
