### ISSUE TITLE
TECH: Demo Umgebung wird gefühlt alle 2 Minuten zurückgesetzt und man wird ausgeloggt.

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1511]
# ToDo

- [x] Demo Umgebung Releasen (bugfix seeding)
- [ ] Problem analysieren
- [ ] Problem beheben :smiley: 

# Tech-Spec

* Puzzle Openshift 3, hit-demo-prod
* Ist evtl. noch der alte dj job vorhanden der die Daten früher resettet hatte?
* https://gitlab.puzzle.ch/pitc_hit/hitobito-configmanagement/-/blob/master/overlays/hit-demo-prod/nightly-db-reset.yaml

**Comment by carlobeltrame** [comment]
Vielleicht ein Zusammenhang mit https://github.com/hitobito/hitobito_cevi/issues/75 ? Auch bei der PBS wurde der schnellere Logout bemerkt.

Devise hat einen Standard-Session-Timeout von 30 Minuten, falls man `:timeoutable` auf dem Person Model aktiviert hat. @TheWalkingLeek hat das am 18.03.2021 auf Person aktiviert. Vielleicht mal in initializers/devise.rb `config.timeout_in` auf 2 Stunden setzen, wie in #1018 vorgeschlagen?

**Comment by mtnstar** [comment]
auf demo prod ist der timeout auf 30 minuten gesetzt (default Devise)

`Person.first.timeout_in`

die Session auf der Demo-Umgebung läuft aber viel früher ab, gefühlt nach 5min

**Comment by mtnstar** [comment]
interessant: der Name der Person mit der E-Mail 'admin@hitobito.ch' ändert ständig, also immer dann wenn die session abgelaufen ist.
irgendwas scheint hier schon immer neu zu seeden.

**Comment by mtnstar** [comment]
weiteres Finding ... der migration job im openshift projekt ist schon wieder auf Pending.
Vermutung: es gibt beim Seeden eine Exception ... dann restartet der Migration Container wieder ...
oder triggert irgendwas sonst die migrations?

**Comment by mtnstar** [comment]
ich habe im rails pod die commands: `rails db:seed` sowie `rails wagon:seed` ausgeführt.
beide laufen ohne exception sauber durch
