### ISSUE TITLE
INVOICES: Analyse und Doku

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1512]
Timebox: 4h

Eine Dokumentation erstellen, wie die Invoices technisch funktionieren und welche Abhängigkeiten bestehen.

Hier noch einige Hints wo INVOICE entwickelt wurde

Fachliche Dokumentation ist grob hier beschrieben: https://hitobito.readthedocs.io/de/latest/invoices.html
Sammelrechnungen: https://github.com/hitobito/hitobito_die_mitte/issues/54
Briefe allgemein: https://github.com/hitobito/hitobito_die_mitte/issues/8
Briefe mit Rechnung: https://github.com/hitobito/hitobito_die_mitte/issues/87
Erstellen der Sammelrechnung und Einzelrechnungen https://github.com/hitobito/hitobito_die_mitte/issues/90

Beispiel Modul-Doku https://github.com/hitobito/hitobito/blob/master/doc/architecture/modules/01_messages.md als inspiration

# ToDo

- [x] INVOICES modul doku unter: https://github.com/hitobito/hitobito/tree/master/doc/architecture/modules
- [x] Verlinken unter Module in https://github.com/hitobito/hitobito/tree/master/doc/architecture/README.md

**Comment by olibrian** [comment]
Hier noch einige Hints wo INVOICE entwickelt wurde

Fachliche Dokumentation ist grob hier beschrieben: https://hitobito.readthedocs.io/de/latest/invoices.html
Sammelrechnungen: https://github.com/hitobito/hitobito_die_mitte/issues/54
Briefe allgemein: https://github.com/hitobito/hitobito_die_mitte/issues/8
Briefe mit Rechnung: https://github.com/hitobito/hitobito_die_mitte/issues/87
Erstellen der Sammelrechnung und Einzelrechnungen https://github.com/hitobito/hitobito_die_mitte/issues/90

**Comment by mtnstar** [comment]
@TheWalkingLeek  ich habe 3.75 von den 4h timebox gebraucht.
machst du noch ein kurzes Review? 
und vielleicht auch gleich noch ein Follow-Up ticket bei dem man die ganze Zahlungsgeschichte inkl. EBICS noch ergänzen kann?
