### ISSUE TITLE
INVOICE: Ablösung ESR

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1513]
die klassischen roten Einzahlungsscheine laufen im September 2022 aus.

In diesem Issue sollen die Abhängigkeiten geklärt werden, sowie ein Plan für den "Ausstieg" aus den ESR in Hitobito geschmiedet werden.

**Comment by olibrian** [comment]
will be fixed by https://github.com/hitobito/hitobito/issues/1982
