### ISSUE TITLE
PEOPLE: Benachrichtigung beim Hinzufügen in neuer Gruppe

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito#1517]
Ab und zu äussern unsere Mitglieder (Datenschutz-) Bedenken, dass ihre persönlichen Daten von fremden Personen eingesehen werden könnten, sobald sie bei einem fremden Verein hinzugefügt würden. 

Würde es eventuell Sinn machen, dass Personen automatisch eine E-Mail erhalten, sobald sie zu einem anderen Verein (technisch: Gruppe) hinzugefügt werden? So könnte man das missbräuchliche Hinzufügen zwar nicht verhindern, aber es würde sofort entdeckt werden. 

Was meint ihr?

# Tech-Spec

- https://github.com/hitobito/hitobito

**Comment by carlobeltrame** [comment]
hitobito hat bereits genau so einen Mechanismus wie du beschreibst, sogar einen noch strengeren. Auf dem Anfragen-Tab jedes Layers (Verein o.ä.) kann man "Manuelle Freigaben" einschalten. Ich beschreibe das Szenario etwas detaillierter:
1. Simon will Zugriff auf die Personendaten von Person X bekommen. Dazu fügt Simon die Person X in einer Gruppe hinzu, auf die er Lesezugriff hat.
2. Wenn die Haupt-Rolle von Person X in einem Verein ist welcher manuelle Freigaben aktiviert hat (oder wenn die Person X keine aktiven Rollen mehr hat aber die letzte Rolle in so einem Verein war), dann wird die Person nicht direkt in der Gruppe hinzugefügt. Stattdessen sieht Simon folgende Nachricht:
![pending-role-approval](https://user-images.githubusercontent.com/7566995/144573308-887a3aa5-1212-4c0c-a896-cf59d678cd97.png)
3. Gleichzeitig gehen E-Mails raus an Person X (falls Person X ein Passwort gesetzt hat) und alle Personen die auf dem Anfragen-Tab der Gruppe ausgewählt sind. Diese Personen können dann aufs Anfrage-Tab gehen und die Zugriffsanfrage akzeptieren oder ablehnen:
![approvals-tab](https://user-images.githubusercontent.com/7566995/144573853-ad973836-7736-45e8-aaa9-943bcf011ab3.png)

Falls die Gruppe die manuellen Freigaben nicht aktiviert hat, oder falls Simon sowieso schon Zugriff auf Person X hat, wird dieses Anfrage-System übersprungen. Leider verlangt dieses System manuelle Konfiguration bei jeder Gruppe (man muss einstellen wer die Mails bekommen soll), daher sind die manuellen Freigaben standardmässig deaktiviert.

Da dieses Issue jetzt schon die dritte Anfrage zu diesem Thema innert einem Monat ist (über verschiedene Kanäle von verschiedenen hitobito-Nutzerorganisationen), scheint mir dieses Feature nicht ausreichend dokumentiert zu sein. Ich schlage auf hitobito-Seite folgendes vor:
* [ ] Dokumentation zu den manuellen Freigaben auf https://hitobito.readthedocs.io/de/latest/ ergänzen
* [ ] Manuelle Freigaben für neu erstellte Layers von nun an standardmässig aktivieren

Das stärkste Instrument gegen diese Bedenken ist aber nach wie vor, dass ihr bei euren Vereinen Werbung macht, die manuellen Freigaben zu aktivieren. Wenn gewünscht können wir diese auch bei allen Vereinen aufs Mal mit einer einfachen Datenbankmigration aktivieren, mit dem Risiko dass dann etwas zu viele Personen solche Anfrage-Mails bekommen.

**Comment by betsim** [comment]
Vielen Dank für deine Ausführungen @carlobeltrame Ich habe das Feature "Anfrage" natürlich schon ausprobiert, aber ich sah nicht den von mir gewünschten Effekt bzw. das was du beschreibst. Ich gehe aber aufgrund deiner Ausführungen davon aus, dass dies daran liegt, dass ich das mit meinem eigenen User probiert habe, welcher hitobito-Admin ist und ohnehin auf alle Personen Zugriff hat. 

Was du beschreibst, geht in die Richtig, was ich suche. Ich frage mich aber: Macht das Sinn, dass diese Funktion an einen Verein gekoppelt ist? Würde es nicht mehr Sinn machen, wenn jedes Mitglied diese Option bei seinen persönlichen Einstellungen de-/aktivieren könnte und nur er/sie selber eine Benachrichtigung erhält? Sollte er/sie noch keinen Login haben, könnte dem Anfragesteller dies ja angezeigt werden, so dass dieser sich an jemanden wenden könnte, der bereits Zugriff auf die Person hat (in diesem Fall wird diese Anfrage ja offenbar umgangen).

**Comment by carlobeltrame** [comment]
Soweit ich verstehe ist einer der Gründe dass es an einen Verein gekoppelt ist, dass so die Mail-Benachrichtigungen genügend aktive hitobito-Nutzende erreichen und damit die Anfragen in nützlicher Frist akzeptiert oder abgelehnt werden können. Auch so noch erlebe ich es in der Praxis immer wieder, dass solche Anfragen von den Nutzenden (Verantwortlichen in den Vereinen und betroffene Personen selber) nie oder sehr lange nicht bearbeitet werden.

Würden wir es an die Person koppeln wie du vorschlägst, könnten das zudem ja nur Personen verwalten, die sich in hitobito einloggen können. Im Allgemeinen haben viele Personen keinen Login, müssen aber trotzdem zu neuen Gruppen, Anlässen und Abos hinzugefügt werden können.

Was du dann zur Lösung als manuellen Prozess beschreibst (sich an jemanden wenden der bereits Zugriff hat) ist in der aktuellen Implementation erstens immer noch möglich (falls der Antragssteller schon weiss an wen er sich wenden soll) und zweitens automatisiert (falls der Antragssteller nicht weiss an wen er sich wenden muss, was in der Praxis vermutlich öfter vorkommt).

Kannst du mir konkrete Vorteile nennen die du siehst, wenn wir die Verantwortlichkeit der manuellen Freigaben auf Einzelpersonen verschieben würden? Im Moment überwiegt für mich der Nachteil dass man dann sämtliche Nutzenden (mit oder ohne Login) über dieses Feature informieren müsste, statt wie aktuell nur mindestens jemanden pro Verein.

**Comment by betsim** [comment]
Ok, ich sehe, dass die Gründe für ein Koppeln an einen Verein überwiegen. Meine Idee war, dass wir Datenschutzbedenken noch besser entgegnen könnten, wenn das jeder selber einstellen könnte (z.B. wenn sich ein Verein weigert, das zu tun). Aber vielleicht wäre es eine Überlegung wert, diese Option standardmässig zu aktivieren. Bin unschlüssig.

**Comment by betsim** [comment]
Ich bin immer noch unschlüssig, ob dieses Feature standardmässig aktiviert werden sollte. Aber schliesse das Ticket mal.
