### ISSUE TITLE
Travis einbauen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#153]
Neu automatisiert Tests laufen lassen.

- Muss für jeden Wagon gemacht werden.
- Sollen Test ausgeführt werden, rake ci task verwenden.
- Sollen noch andere Analyzer drin sein? Eher später.

Wagons:

- [x] core
- [x] generic
- [x] dsj
- [x] cevi
- [x] pbs
- [x] jubla
- [x] insieme
- [x] pro natura

**Comment by kronn** [comment]
Alle aktuell auf github in der Organisation hitobito vorhandenen Wagons werden nun auf travis getestet. Der youth-Wagon wird aktuell lediglich implizit getestet, wenn die darauf aufbauenden Wagons getestet werden.

**Comment by RolandStuder** [comment]
Super vielen Dank!
