### ISSUE TITLE
Evaluieren Umstellung von Gitlab auf Github

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#154]

**Comment by kronn** [comment]
Im Kern habe ich zwei Lösungen gefunden:

1. "manuell" die Änderungen von Github ziehen, siehe http://serverfault.com/a/532231/87587
2. GitLab Enterprise Edition 8.2 oder höher einsetzen, was jedoch 39$/User/Jahr kostet, siehe https://about.gitlab.com/products/

Man könnte noch einen Webhook in den jeweiligen Repos einrichten, um gitlab über pushes zu informieren. Ich vermute, dass es jedoch deutlich mehr Aufwand ist, den entsprechenden endpoint zur Verfügung zu stellen.

**Comment by kronn** [comment]
Wir haben Variante 1 umgesetzt. Es wurde während der Einrichtung einmalig manuell synchronisiert, künftig wird es stündlich synchronisiert.

**Comment by RolandStuder** [comment]
Awesome!

**Comment by kronn** [comment]
hitobito-core und alle wagons, die auf github sind, werden durch den Gitlab-Server von Github geholt. Die Pipeline zur Erstellung der puzzle-RPMs ist damit intakt.
