### ISSUE TITLE
EVENT: Notifizierung Kontaktperson bei einer Anmeldung zu einem Event

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1540]
# Ausgangslage

Aktuell erhält bei einer Anmeldung die Person eine Anmeldebestätigung. Diese kann unter `custom_contents` definiert werden.

# Ziel

Beim Event kann bei der Kontaktperson eingestellt werden, ob diese Person per Mail über eine neue Anmeldung informiert werden soll. Im Idealfall wird diese Box nur angezeigt, wenn eine Kontaktperson ausgewählt ist. 

[Dokumentation](https://github.com/hitobito/user_documentation) ergänzen: Wann eine Person per Mail informiert wird.

# Mockup

Mögliche Umsetzung:

![image](https://user-images.githubusercontent.com/9592347/145773540-a59863d6-d16e-40fd-ad4d-c66e316fd9c0.png)

# Tech-Spec

* Default: Checkbox auf `false`
* nur anzeigen, wenn Kontaktperson vorhanden
* Schreibfehler vermeiden ;-)
* CHANGELOG-Eintrag
* beim PBS-Wagon nachschauen, was schon an Notifications vorhanden ist
* custom content seeded
* Neu bei Anmeldung -> (weitere) Mail an Kontaktperson

# Umsetzungsplan

- [x] Migration
	- [x] `notify_contact boolean DEFAULT false NOT NULL`
- [x] View
	- [x] Checkbox per JS anzeigen, wenn Kontaktperson vorhanden.
	- [x] Checkbox wieder ausblenden, wenn Kontaktperson gelöscht wird
	- [x] locale anpassen
- [x] Custom Content db/seeds/custom_contents.rb
	- [x] mandatory placeholders: event_name, particpant_name
	- [x] optional placeholders: event_url, participation_details
- [x] Mailer
	- [x] notify_contact
	- [x] nur versenden, wenn Kontakt eine email hat. 
- Housekeeping
	- [x] [Dokumentation](https://github.com/hitobito/user_documentation) ergänzen, wann eine Person per Mail informiert wird.
	- [x] CHANGELOG-Eintrag

**Comment by severinraez** [comment]
Doku ist noch offen, bin mir nicht sicher, wo das am besten hin kommt.

**Comment by richardjubla** [comment]
Frage zu Changelog Version 1.27 von jubla.puzzle.ch

Zwischen produktiv und V 1.27 sind die Hilfstexte verlorengegangen.  
Unsere Hilfstexte, insbesondere für "Anlass", "Kurs", "Person" etc. sind davon betroffen. 

Müssen diese Hilfstexte alle neu erfasst werden? gehen die bei einem Update (test -> live) verlohren?



Produktiv
<img width="635" alt="image" src="https://user-images.githubusercontent.com/95908537/173309369-0a242158-ba6e-4b0a-a108-70d51fe4802f.png">

Test (1.27)
![image](https://user-images.githubusercontent.com/95908537/173309147-bf748ab1-4dd9-40e4-9542-eceacf161d83.png)

Hilfstexte Produktiv
![image](https://user-images.githubusercontent.com/95908537/173310683-0aec5412-cff5-44cf-8399-9c85478d4bcd.png)

Hilfstexte Test (1.27)
![image](https://user-images.githubusercontent.com/95908537/173310745-bd2e2b2d-8ac5-4568-9add-b50366122389.png)

**Comment by carlobeltrame** [comment]
@richardjubla Bist du sicher dass ihr die Hilfetexte auf der Integration mal erfasst hattet? Hilfetexte werden intern als "Daten" gehandhabt, genau wie Personendaten und Gruppendaten. Sie sind nicht automatisch zwischen Testumgebung (=Integration, jubla.puzzle.ch) und Produktion geteilt / gespiegelt. Hilfetexte werden nie automatisch erstellt oder migriert, und ich sehe auch keinen plausiblen Grund wie die hätten verloren gehen können.

Die Daten (Datenbank) der Testumgebung und der Produktion sind komplett separiert, und die produktiven Hilfetexte sollten auch bei einem Update nicht verloren gehen. Wenn doch, müssten wir sie aus einem Backup wiederherstellen. Gleiches gilt auch für die Gruppenstruktur, die Einstellungen wie Kursarten etc., und eigentlich alles was man via Browser bearbeiten und verwalten kann. Die Testumgebung kannst du dir wie eine komplett unabhängige zweite jubla.db vorstellen.

In dem Sinn müsst ihr, wenn ihr dieselben Hilfetexte auf der Testumgebung wie auf der Produktion möchtet, die einmalig von Hand auf der Testumgebung einfügen.

Hilft dir das weiter?

**Comment by richardjubla** [comment]
> Hilft dir das weiter?
Ja, sehr. Die Hilfstexte gehen demnach nicht verloren. Neu entstandene Felder können optional auf der produktiven Umgebung erfasst werden.
