### ISSUE TITLE
PERSON: Sicherheit und Usability

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1541]
Dieses Ticket ist aus den Diskussionen rund um https://github.com/hitobito/hitobito/issues/1297 entstanden.

Die Sicherheitskonzepte von Hitobito sollen den Benutzern verständlich und einfach aufgezeigt werden. Damit sollen zuständige Personen befähigt werden, aktiv mit der Sicherheit von Accounts umzugehen.

Dieses Ticket berücksichtigt auch Funktionen, die es nicht (oder noch nicht) gibt. Diese Elemente sollen jeweils in den dazu gehörigen Tickets diskutiert werden.

## Account und Sicherheits-Übersicht auf Ebene Profil
Personen, die eine Person bearbeiten können, sehen auch eine Account-Übersicht auf dem Profil. Dort sind verschiedene Erklärungen und Aktionen vorhanden:

- Entsperren von temporär gesperrten Accounts (https://github.com/hitobito/hitobito/issues/1544)
- Login Infos (siehe auch https://github.com/hitobito/hitobito/issues/1296) und Login schicken
- 2FA (https://github.com/hitobito/hitobito/issues/1300)
- Erzwingen einer Passwort-Änderung (https://github.com/hitobito/hitobito/issues/1542)
- Löschen von Rollen
- Entfernen der Haupt-E-Mail

### Mockup

![Mockup Sicherheits-Übersicht(3)](https://user-images.githubusercontent.com/1799621/149759124-4eb5c6de-c02c-4372-b9d2-85512bc2754f.png)

## Bessere Erklärungen und Hilfetexte
Die Haupt-E-Mail soll entsprechend ihrer Funktion beschrieben werden.

![Haupt-Mail](https://user-images.githubusercontent.com/1799621/149759155-13c294e0-b37f-4600-b777-e6327acf25a4.PNG)

**Comment by nchiapol** [comment]
Die Vorschläge sehen sehr vielversprechend aus. Danke für die Arbeit und die Diskussionen. 

Ein paar Gedanken/Ideen:
  * Beim Cevi werden seit https://github.com/hitobito/hitobito_cevi/issues/51 Daten im Log aus Datenschutz-Überlegungen nur noch 3 Monate angezeigt. D.h. die alte E-Mail-Adresse wäre nicht mehr in jedem Fall sichtbar. (Da das Log aber nur ausgeblendet, nicht aber gelöscht ist, könnte man die falls nötig trotzdem an geeigneter Stelle anzeigen.)
  * Ich finde es auch wichtig, dass alle relevanten Personen über einen Vorfall informiert werden. Ich würde es deshalb begrüssen, wenn diese automatisch passieren könnte. Idealerweise hätte der User die Möglichkeit das jeweils zu unterbinden, nicht dass er deswegen ganz auf die Funktion verzichtet. Mögliche Ideen:
    * Wenn sicher "Haupt-E-Mail löschen" evtl. auch "Rollen entfernen oder Anpassen" genutzt wird, werden alle Adressverwalter von anderen Layern in denen die Person eine Rolle hat informiert. (Welche Aktion, durch wen ausgeführt.)
    * Wenn die Haupt-E-Mail über den entsprechenden Knopf gelöscht wurde, sollte das wohl beim editieren der Person angezeigt werden (z.B. "Die Haupt-E-Mail wurden am ... von ... aus Sicherheitsgründen gelöscht. Besprich die Situation bitte mit den relevanten Personen, bevor du wieder eine Haupt-E-Mail einträgst.").
  * Der Text zu "Haupt-E-Mail löschen" müsste wohl heissen "Willst du die Person ganz aus **MiData** ausschliessen? [...]". Das betrifft ja eben nicht nur die eigenen Gruppen.
  * Ich finde die aktuelle Erklärung zur Haupt-E-Mail ("Wird als Login verwendet") nicht viel weniger klar. Falls der ergänzt wird, würde ich auch die Versande und weiteren Mails explizit erwähnen. (z.B. "E-Mails von Abos oder bei Anmeldungen werden im Normalfall an die Haupt-E-Mail gesendet. Wenn dieses Feld ausgefüllt ist, kann sich die Person zudem einloggen. Was sie in dem Fall genau sehen kann, hängt von den zugewisenen Rollen ab.")
  * Evtl. wäre es hilfreich, wenn via Account-Übersicht auch eine Darstellung der Zugriffsrechte der Person verfügbar wäre.

**Comment by Michael-Schaer** [comment]
Merci Carbon für deine Rückmeldungen! Ich habe die Mockups angepasst!

>- Ich finde es auch wichtig, dass alle relevanten Personen über einen Vorfall informiert werden. Ich würde es deshalb begrüssen, wenn diese automatisch passieren könnte. Idealerweise hätte der User die Möglichkeit das jeweils zu unterbinden, nicht dass er deswegen ganz auf die Funktion verzichtet. Mögliche Ideen:
> 
>   - Wenn sicher "Haupt-E-Mail löschen" evtl. auch "Rollen entfernen oder Anpassen" genutzt wird, werden alle Adressverwalter von anderen Layern in denen die Person eine Rolle hat informiert. (Welche Aktion, durch wen ausgeführt.)
>   - Wenn die Haupt-E-Mail über den entsprechenden Knopf gelöscht wurde, sollte das wohl beim editieren der Person angezeigt werden (z.B. "Die Haupt-E-Mail wurden am ... von ... aus Sicherheitsgründen gelöscht. Besprich die Situation bitte mit den relevanten Personen, bevor du wieder eine Haupt-E-Mail einträgst.").

Sehr guter Hinweis, das ist denke ich wichtig bei Personen mit mehreren Ebenen! Rolle entfernen ist denke ich nicht nötig, wenn dies nur die eigene Ebene betrifft. Bzw. sollte es freiwillig sein, andere Personen zu benachrichtigen.

> - Evtl. wäre es hilfreich, wenn via Account-Übersicht auch eine Darstellung der Zugriffsrechte der Person verfügbar wäre.

Kann ich mir noch nicht ganz vorstellen. Was ist hier der Unterschied zur Rollenübersicht im Profil?

**Comment by nchiapol** [comment]
Ja, bei Personen mit Rollen nur in einer Ebene ist die Situation wohl nicht so kritisch. Aber selbst da müssen wir verhindern, dass sich die Person einfach bei einer anderen Ebene meldet und so wieder eine Haupt-E-Mail eingetragen bekommt.

Betreffend Freiwillig: Da bin ich völlig einverstanden. Das wollte ich mit meiner Möglichkeit die Info zu unterbinden erreichen. Ich stelle mir da einen Dialog vor

```
Bösewicht hat in weiteren Ebenen Rollen. Welche Adressverwalter sollen über deine Massnahme informiert werden?
[ ] Hans Muster (Dachverband)
[ ] Manuela Beispiel (Sektion Z)
[ ] Urs Tester (Abteilung X)
```
Die genaue Formulierung des Dialogs, der Inhalt der Nachricht und die Vorauswahl der Empfänger müsste sicher noch optimiert und gegenseitig abgestimmt werden.

Darstellung der Zugriffsrechte: Grundsätzlich ist in der Rollenübersicht natürlich die gleiche Info enthalten. Allerdings muss ich dabei die Rechte diverser Rollen (möglicherweise auch aus mir fremden Ebenen) kennen und mental konsolidieren.

Mögilche Probleme lassen sich in
```
Sektion Z
  Administrator/-in 		
Sektion Z / Vorstand
  Präsidium 		
Sektion Z / Ressort Ausbildung
  Leitung (Vorstand) 		
Sektion Z / Delegierte Dachverband
  Leitung 		
Sektion Z / Webteam
  Mitglied 		
Abteilung X
  Coach 		
Verein X
  Mitglied (J&S Coach) 		
Dachverband / Gruppe DB
  Mitglied (Z) 		
Sektion Z / Fachgruppe S
  Leitung 		
Abteilung J
  Freie/-r Mitarbeiter/-in
```
sicher weniger rasch erkennen als in 

```
* Dachverband > Gruppe DB: lesen der Gruppe
* Sektion Z: lesen und schreiben der Eben und aller darunterliegenden Ebenen
  * Abteilung X: lesen und schreiben der Ebene
  * Verein X: lesen der Ebene
* Abteilung J: lesen der Gruppe
```

**Comment by Michael-Schaer** [comment]
Die Idee gefällt mir mit dem Benachrichtigungs-Dialog!

Die Darstellung der Zugriffsrechte würde ich auch unterstützen. Ich möchte aber zuerst die anderen Punkte angehen. Wir haben auch noch ein verwandtes Feature im PBS-Wagon, das vielleicht günstiger eingebaut wäre: https://github.com/hitobito/hitobito_pbs/pull/196

**Comment by Michael-Schaer** [comment]
Weitere Ideen:

- Wann hat sich die Person zuletzt eingeloggt?
- Welche Person hat die Person zuletzt bearbeitet?

**Comment by Michael-Schaer** [comment]
Den Tab gibt es und vermutlich werden nach und nach neue Infos dazukommen. Ich denke, das Ticket hier kann geschlossen werden.
