### ISSUE TITLE
PEOPLE: Bewusste Vergabe von Berechtigungen ermöglichen

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1543]
### Problembeschreibung
Bei einigen Rollen ist nicht klar, ob Leserechte notwendig sind oder nicht. Gerade, wenn eine Person hauptsächlich in einem Verteiler erscheinen soll, werden heute in jedem Fall auch Leserechte vergeben. Aus Security-Sicht sollte jedoch jeder Zugriff auf Daten bewusst vergeben werden (Vergleich ISO 27001). In so einem Fall wäre es darum gut, eine Option zu haben, um keine Leserechte zu vergeben.

Dabei stehen beispielsweise bei der PBS Rollen mit ausschliesslicher Leseberechtigung auf Ebene Abteilung zur Diskussion:

- Spezialfunktion
- Materialwart*in
- Beisitzer*in
- Präses
- Präsident*in Elternrat
- Präsident*in APV
- (Heimverwalter*in)

### Lösung
Diese Rollen sollen neu mit einer Checkbox "Leserechte Ja/Nein" erweitert werden. So kann die Berechtigung beim Erfassen der Person bzw. der Rolle wahlweise vergeben werden oder nicht.

![Mockup Lese-Flag](https://user-images.githubusercontent.com/1799621/145986062-117a07a9-1777-4451-b48c-c692fcfb82aa.png)

# ToDo

- [ ] Feature konzipieren und in neuem Issue festhalten
- [ ] Aufwand schätzen und an Michael via PL Hitobito kommunizieren

**Comment by carlobeltrame** [comment]
Warum wurde das geschlossen? Gibt es ein Follow-up Ticket? @kronn war doch heute Morgen noch da dran?

**Comment by kronn** [comment]
Das wurde in Absprache mit mir geschlossen :-) @chrusu bespricht das weiter mit Michael

**Comment by Michael-Schaer** [comment]
Werden wir im 2023 wieder aufgreifen. Gerne noch offen lassen.
