### ISSUE TITLE
MESSAGES: Aktivierung der neuen BulkMail implementation

### ISSUE THREAD

**Issue by luca-bruegger** [hitobito/hitobito#1545]
Mittels einer Umgebungsvariable soll der neue BulkMail Stack aktiviert werden können. 

# Tech-Spec
Abgeschlossen wenn:
- [ ] Umgebungsvariable mit dem namen: ___ den alten BulkMail Stack deaktiviert und die neue aktiviert.

**Comment by mtnstar** [comment]
wird über neue mail.yml gelöst.
