### ISSUE TITLE
HOUSEHOLDS: Leere Haushalte in HouseholdList

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#1553]
## Aktuelles Verhalten

Bisher nur aufgetreten auf PBS Produktion beim Sarasani-Export. Die Domain-Klasse `HouseholdList` welche die Personen in Haushalte gruppiert und in Batches zur Weiterverarbeitung liefert, liefert dort manchmal leere Haushalte. Normale Haushalte werden als Array von einer oder mehreren Personen geliefert, aber manchmal ist dieses Array leer, was eigentlich gar nicht möglich sein sollte.
Vielleicht hängt das mit ausgeschlossenen Personen im Abo zusammen? Das Problem konnte leider lokal bisher nicht reproduziert werden, da nur das Sarasani-Abo den Fehler aufweist, und der SQL Query beim Sarasani-Abo lokal ewig braucht. Auf der PBS Produktion tritt der Bug erstmals ca. 5 Minuten nach Start des `HouseholdsFull` Exports auf (und später noch weitere Male).

Bei der Mitte wurde in einem `Messages::LetterDispatch` vermutlich etwas ähnliches beobachtet. Dort jedoch ohne Haushalte. https://github.com/hitobito/hitobito/blob/master/app/domain/messages/letter_dispatch.rb#L37

## Gewünschtes Verhalten

Die `People::HouseholdList#households_in_batches` gibt nie ein leeres Array als Teil eines Batches aus.

## Schritte zum reproduzieren

1. Auf PBS Produktion den `Pbs::Export::Tabular::People::HouseholdsFull` ausführen, bzw. den Export-Job unter https://db.scout.ch/de/groups/2/mailing_lists/763/subscriptions.xlsx?household_details=true starten
2. Export schlägt fehl, weil in der `HouseholdRow` aus einem leeren Haushalts-Array kein `entry` = `household.first` gefischt werden kann, und dann der `entry` keine Adresse hat, weil er `nil` ist.

# Tech-Spec

- Der betroffene Export `HouseholdsFull` ist [PBS-spezifisch](https://github.com/hitobito/hitobito_pbs/blob/master/app/domain/pbs/export/tabular/people/households_full.rb), aber das eigentliche Problem tritt schon auf bevor PBS-spezifischer Code läuft
- https://github.com/hitobito/hitobito/blob/master/app/domain/people/household_list.rb

**Comment by Michael-Schaer** [comment]
Merci Carlo fürs Erfassen! Kann ich hier irgendwie unterstützen? Wird z.B. eine spezifische Person geloggt, bei der die leere Zeile auftaucht?

**Comment by carlobeltrame** [comment]
Das Problem ist eben gerade dass ich noch nicht weiss, bei welchem spezifischen Haushalt keine Personen kommen.
Wenn du vorig Zeit hast könnte es helfen wenn du mit einem kleinen Abo mit Haushalten und ausgeschlossenen Personen rumspielst und siehst ob du es auch im kleinen Rahmen reproduzieren kannst. Aber ansonsten machen wir das dann mal.

**Comment by Michael-Schaer** [comment]
Ich habe etwas probiert, konnte den Fehler jedoch nicht nachstellen. Eine leere Namenszeile habe ich hinbekommen, das scheint aber problemlos exportiert zu werden:

Daten:
https://db.scout.ch/de/groups/2/mailing_lists/5950/subscriptions
https://db.scout.ch/de/people/98098
https://db.scout.ch/de/people/98080

Export:
https://db.scout.ch/de/groups/2/mailing_lists/5950/subscriptions.xlsx?household_details=true

**Comment by TheWalkingLeek** [comment]
Ich hab das mal angeschaut und konnte leider auch nicht viel mehr herausfinden..
Ich vermute aber dass es an diesem `select` liegt: https://github.com/hitobito/hitobito/blob/master/app/domain/people/household_list.rb#L42
Könnte es sein dass `household.key` mal nicht als String entgegen kommt? In den Specs ist das nie der Fall aber das wäre so eine Idee :/
