### ISSUE TITLE
MESSAGES: BulkMail: Dispatch Versand

### ISSUE THREAD

**Issue by luca-bruegger** [hitobito/hitobito#1556]
Timebox: 8h

Der Versand baut auf die [Dispatch Basis](https://github.com/hitobito/hitobito/issues/1546) auf.

Mittels diesem sollen die Mails an die Empfänger von MailingListen gesendet werden.

Zu beachten gilt:
* Der Status der Message wird auf Failed gesetzt sobald die fünf retries aufgebraucht wurden.
* Im `RCPT TO` (Recipient To) Teil von SMTP befinden sich alle Empfänger Emails

# Tech-Spec / ToDo

Abgeschlossen wenn:
- [x] Mails Batchweise verschickt werden (bisherige Anzahl)
- [x] Message Recipients `state` laufend aktualisiert wird (`:sending`, `:sent || :failed`) 
- [x] Ein BulkMail Versand pro job (job wird immer wieder neu enqueued mit den nächsten n Empfängeradresse)
- In `Messages::BulkMailDispatch`
  - [x] `Messages::BulkMail::MailFactory`
    - [x] Aufgrund der `Message` eine `Mail::Message` bauen
  - [x] Message aktualisiert wird (state: `:processing`, `:finished || :failed`) und success_count, failed_count aktualisiert wurde.
  - [x] Nach dem erfolgreichen Versand an alle Empfänger, raw_source von `Message::BulkMail` auf nil setzen. 
  - [x] Sind die fünf retries aufgebraucht: failed_count reset und Job sauber beenden (ohne Exception) evtl. Log Entry.
    - Alle Recipient entries welche nicht bereits status :sent haben, auf status :failed setzen
    - Job wird in diesem fall nicht mehr neu enqueued
    - BulkMail message status auf :failed
    - Siehe `# TODO fail cleanly` in `bulk_mail_dispatch.rb`
- [x] Doku updaten: https://github.com/hitobito/hitobito/blob/master/doc/e-mail/abo_mails.md

Mail headers:
| header      | Definiton                                          | Wert                                |
| ----------- |:-------------------------------------------------- |:----------------------------------- |
| sender      | Absenderadresse von hitobito                       | asdf42@hitobito.example.com   |
| to          | Adresse der MailingList                            | asdf42@hitobito.example.com                  |
| from        | Absenderadresse Original Mail                      | luca@example.com                    |
| Reply-To    | Antwortadresse  | luca@example.com                     |
| Return-Path | Wenn unzustellbar zurück an die definierte adresse | luca@example.com                     |

Es wird keine Bounce Adresse mehr geben. Antwort erfolgt via Return-Path wie hier empfohlen: https://stackoverflow.com/a/154794

## Bestehend
Aktuelle [BulkMail](https://github.com/hitobito/hitobito/blob/master/app/domain/mail_relay/bulk_mail.rb) implementation sowie zugehöriges [spec](https://github.com/hitobito/hitobito/blob/master/spec/domain/mail_relay/bulk_mail_spec.rb) die abgelöst werden soll.

## Erweitern
app/domain/message/bulk_mail_dispatch.rb

**Comment by severinraez** [comment]
Arbeiten sind in `feature/dispatch/delivery` und gemergt nach `feature/bulk-mail`
