### ISSUE TITLE
EBICS: Ergänzen Valiant Bank

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1558]
Die bestehenden Bankverbindungen sollen durch eine zusätzliche Bank erweitert werden.

Valiant: [EBICS Info](https://www.valiant.ch/geschaeftskunden/services-ebics)

# Tech-Spec

- Point: config/settings/payment_providers.yml
- Ergänzen von der [User Doku](https://github.com/hitobito/user_documentation/blob/beta/ebics.rst)
- Kann direkt mit dem Raiffeisen Typo gemerged werden: https://github.com/hitobito/hitobito/pull/1582

**Comment by TheWalkingLeek** [comment]
Valiant scheint aktuell keinen Z54 anzubieten, sondern C54. 
Bei dieser Auftragsart ist mir nicht ganz klar ob sie nur Transaktionen per ESR anbieten. Konkret steht:
"C54	Gutschrifts-/Belastungsanzeigen im CAMT.054 Format (Zip Archiv) ESR"

**Comment by TheWalkingLeek** [comment]
https://github.com/hitobito/user_documentation/commit/131fce27e8ec0b383730af5ae29043b7b6692555
