### ISSUE TITLE
Analyse: Cypress-Setup der PBS analysieren

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1581]
Timebox: 8h?

Im Rahmen der regelmässigen Releases möchten wir unser Test-Setup ausbauen. 

Dabei sind End-to-End-Tests mit Cypress eine Option. Die PBS hat bereits in diese Richtung experimentiert.

Ziel dieses Issues ist es, den aktuellen Stand der PBS zu analysieren um besser abschätzen zu können, ob dies der Weg ist, welchen wir gehen wollen.

https://github.com/scout-ch/midata-cypress

**Comment by olibrian** [comment]
Redundant zu #1645
