### ISSUE TITLE
Rollenfilter für Personenliste auf bestimmten Zeitraum beziehen. (12h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#159]
## IST:

Der Rollenfilter funktioniert gut, lässt allerdings nicht in die Vergangenheit zurückzublicken, z. B. ist es interessant, wer beim Kantonalverband sein Amt abgegeben hat und vielleicht für andere neue Tätigkeiten offen wäre. Wir wurden schon einige Male angefragt, ob es möglich ist so eine Liste zu erstellen.

## SOLL:

Uns bekannte Use Cases haben sich insbesondere dafür interessiert, bei welche Personen ein Rolle terminiert / angefangen wurde oder aktiv war.

## Voraussetzungen

#303

## Akzeptanzkriterien

* [ ] Im CORE umgesetzt
* [ ] Beim Rollenfilter kann ich ein Start oder Enddatum angeben
* [ ] Startdatum ist optional, wenn keines angegeben, dann sucht es seit Anfang
* [ ] Enddatum ist optional, wenn keines angeben, dann sucht es bis in die Zukunft
* [ ] Kann abgespeichert werden
* [ ] Ich sehe nur Personen, auf die ich aktuell eine Zugriffsberechtigung habe

### Optionen für den Zeitraum

* [ ] Benutzer wählt, auf was sich der Zeitraum bezieht (Single Choice)
  * [ ] Aktiv - Person hatte eine der gewählten Rollen in diesem Zeitraum aktiv.
  * [ ] Terminiert - Person hatte eine Rolle mit einem Enddatum in diesem Zeitraum
  * [ ] Begonnen - Person hat/hatte eine Rolle mit einem Startdatum im diesem Zeitraum.

## Hinweise

* Das ermöglicht so herauszufinden, welche Rollen abgegeben worden sind, aber nicht, ob eine Person keine der gewählten Rollen mehr innehat. Ich kann also Wechsel nicht von Austritten unterscheiden.

**Comment by codez** [comment]
Berechtigungen? Bisher wurden in der Personenliste nur Personen aufgeführt, auf welche eine Leseberechtigung bestand. Diese ist allenfalls erloschen, wenn eine Rolle gelöscht wurde. Entsprechend müsste die Personenliste ebenfalls noch angepasst werden (Performance für Berechtigungsprüfung für jede Person).

Sollen diese Filter ebenfalls abgespeichert werden können?

Gutes UI wichtig für Verständnis.

**Comment by codez** [comment]
Schätzung: 2PT + 0.5 für beide Optionen zusammen

**Comment by amaierhofer** [comment]
Aktuell sind gelöschte Rolle nicht im `default_scope`. Das hat zur folge, dass wir an diversen Stellen manuel Rolen mit Gruppen joinen müssten. Was macht mehr Sinn, diesen Spezial Fall nur in der Suche zu behandeln oder den default scope umzustellen?
