### ISSUE TITLE
PEOPLE: Adressvorschläge Personen edit/new funktionieren nicht richtig

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#1598]
@Michael-Schaer hat festgestellt das das Typeahead für die Adresse von Personen nicht richtig funktioniert. Getestet wurde mit folgenden beiden Adressen:

* Bahnhofstrasse 44 in Erlenbach
* Seestrasse 78 in Erlenbach

## Schritte zum Reproduzieren
1. "Bahnhofstrasse 44 Erle" eintippen.
2. Im Adressvorschlag fehlt die Hausnummer

![grafik](https://user-images.githubusercontent.com/17568539/155111898-578acc10-3526-4f42-b890-9f656e554156.png)

Auf der DB in der Address Table sind die Einträge aber vorhanden: (pbs prod)

`Address.where("street_long like '%Bahnhofstrasse%' and town like '%Erlenbach%'") `

```
#<Address:0x0000000003224040
 id: 471153,
 street_short: "Bahnhofstrasse",
 street_short_old: "Bahnhofstrasse",
 street_long: "Bahnhofstrasse",
 street_long_old: "Bahnhofstrasse",
 town: "Erlenbach ZH",
 zip_code: 8703,
 state: "ZH",
 numbers:
  ["1",
   "12",
   "14",
   "15",
   "17",
   "18",
   "19",
   "2",
   "20",
   "21",
   "22",
   "23",
   "24",
   "25",
   "26",
   "28",
   "29",
   "33",
   "33a",
   "33b",
   "37",
   "4",
   "40",
   "42",
   "44",
   "49",
   "6"]>
```
# Gewünschtes Verhalten

Die Adressvorschläge funktionieren für alle vorhandenen Adressen.

# Tech-Spec

- https://github.com/hitobito/hitobito/blob/master/doc/features/address-completion.md

# ToDo

- [ ] Analyse Problem
- [ ] Fix it :wink:

**Comment by chrusu** [comment]
@kronn does not seem to work in pbs.puzzle.ch
