### ISSUE TITLE
INVOICES: Rechnung an Gruppe stellen

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#1610]
Bisher ist es nur möglich, Rechnungen an Personen zu stellen. Zusätzlich soll es möglich sein, auch einer Gruppe eine Rechnung zu stellen. Szenario: Mitgliederbeitrags-Rechnung vom Kantonalverband an seine Vereine aufgrund der in hitobito eingetragenen Mitglieder.

# Tech-Spec

Konzept kommt vom vorgängigen Konzeptions-Ticket #1518
Umsetzung im SBV-Wagon

- [x] Auf allen Gruppen auf dem Tab wo auch die Untergruppen angezeigt werden neuer Button "Vereinsrechnungen erstellen"
- [x] Button öffnet als erstes einen Dialog, ähnlich wie es bei den [Multiselect-Actions](https://github.com/hitobito/hitobito/blob/master/app/views/role_lists/new.js.haml) auf Personenlisten gemacht wird
  - [x] Auf diesem Dialog sind alle Untergruppen inkl. rekursiv Unter-Untergruppen usw. mit Checkboxen auswählbar
  - [x] Ausserdem hat es (falls angebracht) Buttons / Checkboxen um alle Vereine, alle Regionalverbände etc. aufs Mal an- oder abzuwählen
  - [x] In Warnung im Dialog anzeigen, welche konkreten Vereine keinen Rechnungskontakt eingetragen haben, ev. mit Hinweis dass stattdessen Vorstand -> Kassier oder Vorstand -> Präsident oder Administrator verwendet werden
- [x] Dialog Submit Button leitet zum Sammelrechnungsformular mit einem dynamischen Rechnungsposten (via Query-Parameter, siehe #1617) und auf irgendeine Art die Liste von ausgewählten Gruppen
  - [x] Dieser dynamische Rechnungsposten "Mitgliederbeitrag" soll seinen Betrag basierend auf den Mitgliederzahlen (berechnet oder manuelles Feld) berechnen
  - [x] Der dynamische Rechnungsposten hat einen Parameter "Stichdatum", die aktiven Mitglieder an diesem Datum zählen für die Berechnung des Betrags
  - [x] Genaue Berechnungslogik: Betrag * (Anzahl Aktivmitglieder der Gruppe am Stichdatum ODER Anzahl manuell geführte Mitglieder der Gruppe heute)
- [x] Die Sammelrechnung soll (basierend auf der vom Dialog weitergegebenen Information) als Empfänger die Rechnungskontakte der ausgewählten Gruppen verwenden, oder falls kein Rechnungskontakt gesetzt ist, soll Vorstand -> Kassier oder Vorstand -> Präsident oder Administrator verwendet werden. Falls diese auch nicht existieren, wird keine Rechnung an diese Gruppe ausgelöst. Diese Logik sollte vermutlich in einer Domainklasse abgekapselt werden.

**Comment by carlobeltrame** [comment]
Bevor wir das umsetzen können müssen wir in hitobito auf erweiterbare Art die technischen Grundlagen schaffen für Rechnungsartikel die ihren Betrag dynamisch berechnen können.
Den Teil mit der Auswahl welche Gruppen die Rechnung bekommen sollten, sowie die Rechnungskontakte aller Gruppen könnten wir zwar schon unabhängig umsetzen, aber es würde euch glaube ich noch wenig Vorteile bringen, solange alle gestellten Rechnungen immer genau denselben Rechnungsbetrag enthalten. Sehe ich das falsch?

**Comment by betsim** [comment]
Nein, das siehst du richtig. 

Einfach für das Verständnis: für den SBV hat dieses Feature wirklich sehr hohe Priorität.

**Comment by carlobeltrame** [comment]
Alles klar, dann wissen wir wie wir das in den kommenden Sprints einpriorisieren sollen. Wir hatten heute ein Konzeptionsmeeting für die technischen Grundlagen, und ich habe daraus folgend das Ticket #1617 erstellt. Sobald dieses Ticket gelöst ist können wir darauf aufbauend die Gruppenrechnungen implementieren.

**Comment by betsim** [comment]
Input:
- [ ]   Im Wizard kann das Datum gewählt werden, auf welches sich die Anzahl Aktivmitglieder bezieht. Damit kann z.B. auch im Februar noch eine Rechnung generiert werden mit der Anzahl Aktivmitglieder mit Stand 1. Januar.

**Comment by carlobeltrame** [comment]
@betsim bei der genaueren Konzeption sind noch folgende Fragen aufgetaucht:
- Auf welchen Gruppen / Ebenen soll es möglich sein, für die Untergruppen / Vereine eine Mitgliederrechnung zu erstellen?
- Wie berechnet sich der geforderte Betrag genau, basierend auf den Mitgliederzahlen eines Vereins?
- Wie gehen wir vor um sicherzustellen dass jede Gruppe einen Rechnungskontakt hat? Wird bei euch bisher bereits irgendeine Rolle oder ein Feld dafür eingesetzt, die Kontaktperson eines Vereins zu erfassen?
- Ich nehme an ihr möchtet bei Vereinen die ihre Mitgliederzahlen manuell führen auch diese manuell angegebene Mitgliederanzahl für die Rechnung berücksichtigen. In diesen Vereinen ist aber dann das Stichdatum wie du es beschrieben hast nicht möglich, da wir den Inhalt dieses Felds "Manuell erfasste Mitglieder" nicht historisieren. Wie möchtet ihr da vorgehen?

**Comment by betsim** [comment]
> * Auf welchen Gruppen / Ebenen soll es möglich sein, für die Untergruppen / Vereine eine Mitgliederrechnung zu erstellen?

Auf allen Gruppen, d.h. der SBV soll seinen Mitgliedsverbänden (Kantonalverbänden) Rechnung stellen können, die Kantonalverbände ihren Regionalverbänden, Letztere ihren Vereinen.

> * Wie berechnet sich der geforderte Betrag genau, basierend auf den Mitgliederzahlen eines Vereins?

Ja. Massgebend sind die Anzahl Aktivmitglieder, welche hitobito bereits heute automatisch berechnet (Ausnahme siehe unten) und im Info-Tab jeder Gruppe anzeigt.

> * Wie gehen wir vor um sicherzustellen dass jede Gruppe einen Rechnungskontakt hat? Wird bei euch bisher bereits irgendeine Rolle oder ein Feld dafür eingesetzt, die Kontaktperson eines Vereins zu erfassen?

Gute Frage. Mir schwebt da eine Kaskadenordnung vor (ich denke jetzt nur mal laut): falls vorhanden geht die Rechnung an die Person mit der Rolle "Vorstand --> Kassier", sonst an "Vorstand --> Präsident" und als Fallback an einen Administrator der Gruppe. Existiert nicht einmal ein Administrator, dürften wohl auch keine Mitglieder erfasst sein und hat diese Gruppe ohnehin ein Problem, das behoben werden muss...

Alternativ könnte ich mir auch vorstellen, dass Rechnungen nur an jene Gruppen geschickt werden können, die auch die Rolle "Vorstand --> Kassier" vergeben haben. Dazu müsste man aber eine Übersicht haben, welche Gruppen das haben oder an welche Gruppen die Rechnung nicht verschickt werden konnte. 

Überhaupt: Wird man selektieren können, an welche Gruppen die Rechnung geht oder geht sie immer an alle (direkten) Untergruppen einer Gruppe?

> * Ich nehme an ihr möchtet bei Vereinen die ihre Mitgliederzahlen manuell führen auch diese manuell angegebene Mitgliederanzahl für die Rechnung berücksichtigen. In diesen Vereinen ist aber dann das Stichdatum wie du es beschrieben hast nicht möglich, da wir den Inhalt dieses Felds "Manuell erfasste Mitglieder" nicht historisieren. Wie möchtet ihr da vorgehen?

Muss ich abklären...
