### ISSUE TITLE
Application Market Duplicate entry

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito#162]
Bei der Zuteilung der Anmeldungen zu einem Kurs tritt selten der folgende Fehler auf:

> https://db.scout.ch/de/groups/1580/events/772/application_market/9161/participant
> 
> Mysql2::Error: Duplicate entry '772-8972' for key 'index_event_participations_on_event_id_and_person_id'
> 
> Bei https://github.com/hitobito/hitobito/blob/master/app/domain/event/participant_assigner.rb#L28

Mögliche Konstellation: Person ist für diesen und einen anderen Kurs angemeldet aber noch nicht zugeteilt. Bei der Zuteilung wird die Participation des anderen Kurses verwendet, welches den Konflikt erzeugt. Vielleicht aber auch was anderes.

Könnte wohl durch Anpassung von #creatable? (https://github.com/hitobito/hitobito/blob/master/app/domain/event/participant_assigner.rb#L20) gelöst werden.

**Comment by hupf** [comment]
Gefixt, trat tatsächlich im Zusammenhang mit Prioritäten und Warteliste auf, z.B. bei folgendem Szenario:
* Person X meldet sich bei Kurs A an
* Person X kann bei Kurs A nicht teilnehmen, wird auf die Warteliste gesetzt
* Person X meldet sich bei Kurs B an
* Kursleiter von Kurs B möchte Person X von der Warteliste hinzufügen, übersieht, dass sie sich schon direkt angemeldet hat.
