### ISSUE TITLE
TECH: Frequent restart of migrations container

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#1626]
### Aktuelles Verhalten

der migrations container in der demo prod und auch allen anderen Hitobito Openshift Projekten startet alle paar Minuten neu. Dort hatte sich das bemerkbar gemacht indem alle 5min die Demo Seeds neu geladen wurden. Die Demo seeds werden jetzt neu direkt aus dem cronjob aktiviert und dort geseedet.

### Gewünschtes Verhalten

der migrations container sollte nicht mehr dauernd neu starten, nur wenn ein neues rails image vorhanden ist.

### Schritte zu reproduzieren

beobachten des migrations containers in einem hitobito openshift projekt.

### Organisation

demo

**Comment by chrira** [comment]
Es könnte dieses Problem sein: https://access.redhat.com/solutions/3517821

OCP Container Garbage Collection räumt sehr wahrscheinlich die Init Container weg.
Darum werden nur die Init-Container neu ausgeführt und nicht der Main Container.

Das Problem wird auf dem OCP Cluster analysiert und wenn möglich behoben.

**Comment by chrira** [comment]
Die Init Container sollten erweitert werden, dass sie nichts machen, wenn das Image nicht geändert hat.
Pods können im OCP zu jedem Zeitpunkt verschoben werden. Z.B bei Wartungsarbeiten. Da werden die Init Container auch wieder ausgeführt.

**Comment by chrira** [comment]
Für diesen UseCase wäre ev. für den Pod die `restartPolicy` `OnFailure` besser.
Dann sollte er nur beim Rollout und bei Fehlern neu gestartet werden.

https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#detailed-behavior

**Comment by carlobeltrame** [comment]
Der migrate-Befehl macht bereits jetzt nur etwas, wenn auch wirklich neue Datenbankmigrationen da sind. Das entspricht dem init container Konzept gut.

Das Problem sind aber glaube ich die Datenbank-Seeds. Diese sind nicht an ein Docker-Tag gebunden, sondern sollen z.B. täglich laufen, auch wenn sich am Image nichts geändert hat. Da wäre es vielleicht passender, die in einem Kubernetes-Job o.ä. auszuführen. Ich weiss nicht gerade aus dem Stegreif was es da für Konzepte dafür in OpenShift 3/4 gibt.

**Comment by mtnstar** [comment]
die db seeds müssen ja nur in der demo umgebung täglich applied werden.
das machen wir aber jetzt mit einem eigenen job. 
diese anforderung ist also obsolet meines erachtens.

**Comment by chrira** [comment]
Laut meiner Analyse wird der Pod selbst nicht neu gestartet.
Zum Verglich wäre es noch gut einen identischen Pod ohne Init-Container laufen zu lassen.
Dann sehen wir ob es am Container selbst oder an den Init-Container liegt.

**Comment by kronn** [comment]
Das Problem scheint nicht mehr aufzutreten. Wir haben jetzt Alerts für Restarts und können daher sagen "We are monitoring the situation".
