### ISSUE TITLE
Auf der Pfadi Instanz kann ein Person kein Lager erstellen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#163]
Auf https://db.scout.ch/de/groups/812/events/new?event%5Btype%5D=Event%3A%3ACamp kann der Abteilungsleiter kein Lager erstellen.

Es kommt die Meldung "Groups nicht gültig" 
![image001](https://cloud.githubusercontent.com/assets/194364/22013498/9c4a0a1a-dc99-11e6-8707-a55daeaeed87.png)
![image002](https://cloud.githubusercontent.com/assets/194364/22013501/9f0a2636-dc99-11e6-8d38-eb3b9dcefed0.png)

@codez Bitte fixen, respektive Feedback an mich.

**Comment by RolandStuder** [comment]
Gemeldet von René Brugger, Feedback zurück an ihn.

**Comment by codez** [comment]
Der Gruppenkontakt hatte einen Leerschlag in der PLZ, was zu einem Validierungsfehler geführt hat. Ist in der nächsten Version gefixt.

Habe den die PLZ korrigiert, Lager erstellen sollte jetzt klappen.
