### ISSUE TITLE
PERSON: Login-Button with no options

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1638]
### Aktuelles Verhalten

![Leeres Login-Menu](https://user-images.githubusercontent.com/1799621/154048828-cbb1a21d-dfc0-45e9-8ed3-477e357d0f87.png)

Wenn eine Person keine Haupt-E-Mail hat, ist das Login-Menu leer.

### Gewünschtes Verhalten

Login-Button ausblenden, wenn keine Elemente
Oder ausgrauen? 

### Schritte zu reproduzieren

Person ohne Haupt-E-Mail öffnen.

### Wann ist der Fehler aufgetreten?

15.02.2022

### Organisation

PBS

**Comment by carlobeltrame** [comment]
Merci für die Meldung, ich fixe das gleich im Rahmen von #1296
