### ISSUE TITLE
PERSON: Passwort setzen

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1639]
### Aktuelles Verhalten

Auf dem Testsystem ist mir zweimal eine Fehlermeldung aufgefallen, die etwas verwirrend ist.

Und zwar erscheint diese, wenn ich für eine Person eine E-Mail-Adresse eintrage und das Login verschicke. Dann setzte ich über den Link ein Passwort und erhalte diese Fehlermeldung:

![nach dem passwort setzen](https://user-images.githubusercontent.com/1799621/154050307-aab51425-d5ab-41ff-bab2-4dc5a87e5404.png)

Das Passwort wurde zwar korrekt gesetzt und ich kann mich danach einloggen. Aber der Fehler wirkt so, als hätte das mit dem Passwort nicht geklappt.

### Gewünschtes Verhalten

Wenn das Passwort korrekt gesetzt wird, soll keine Fehlermeldung erscheinen. Stattdessen soll eine Meldung "Passwort wurde erfolgreich gesetzt" erscheinen.

### Schritte zu reproduzieren

- Testsystem öffnen
- Eine Person ohne Haupt-E-Mail auswählen
- Haupt-E-Mail setzen
- Login verschicken
- Mailtrap -> Passwort-Link öffnen
- gültiges Passwort setzen (Achtung 12 Zeichen)
- Fehlermeldung erscheint

### Wann ist der Fehler aufgetreten?

15.02.2022

### Organisation

PBS

**Comment by chrusu** [comment]
@carlobeltrame hängt dies möglicherweise mit der neuen Email-Verfication zusammen?

**Comment by carlobeltrame** [comment]
Ja, auf jeden Fall. Ich konnte es reproduzieren und in 184f12a463e8632e56c437c46eacddcdc98a3e3f gleich fixen.
