### ISSUE TITLE
Optimierung "Mehrfachsendungen vermeiden"

### ISSUE THREAD

**Issue by MartinGantenbein** [hitobito/hitobito#164]
Da bei vielen Familien nicht alle Mitglieder den selben Nachnamen haben, funktioniert "Mehrfachsendungen vermeiden" beim Etikettenexport nicht optimal (es wird nach Adresse und Nachname gruppiert). Ausserdem ist unglücklich, dass beim Gruppieren der Adresse das Land mitberücksichtigt wird ohne Defaultland (wenn bei einem Familienmitglied "Schweiz" gesetzt ist und bei einem anderen ist Land leer, dann werden 2 Etiketten erzeugt).

Idee zur Optimierung:
- Einführung eines optionalen Felds "Familienname", das für die Gruppierung genutzt wird (Gruppierung dann mit `coalesce(familyname, lastname)`).
- Je nach Export kann es vorkommen, dass alle Personen einer Familie mit gesetztem `familyname` doch den gleichen Nachnamen haben (z.B. der Export umfasst nur die Kinder), in diesem Fall soll der Nachname auf die Etikette gedruckt werden. Sobald die Gruppierung aber Personen mit unterschiedlichen Nachnamen umfasst, wird für den Druck auf `familyname` gewechselt.

Eine Alternative zum obigen Vorschlag könnte auch sein, Adressen/Personen miteinander zu verknüpfen (über eine Adress-ID oder über eine Mapping-Tabelle). Der Aufwand und die Herausforderungen mit einer solchen Lösungen scheinen mir aber deutlich grösser als mit obigem Vorschlag.

**Comment by RolandStuder** [comment]
Hallo Martin

Möglichkeiten diesbezüglich wurden schon mehrfach  intern und mit anderen diskutiert. Eine ganz einfach Möglichkeit gibt es wohl nicht. Grundsätzlich gibt es bereits ein Model für die Verknüpfung von Personen. Das wird im Wagon der PBS auch benutzt, siehe 

https://github.com/hitobito/hitobito_pbs/commit/b366a9f9d8ac8cec9cbfb8a29cd60a19934d5ab1

Man könnte damit auch andere Beziehung abbilden. Dann könnte man einfach auf der Adressliste einfach die Personen zusammenfassen, die eine Beziehung und die gleiche Adresse haben. Das wäre nicht die einfachste Lösung aber eine die mir robuster scheint.

**Comment by MartinGantenbein** [comment]
Hoi Roland
Personen-Verknüpfungen sind gut geeignet für Beziehungen zwischen 2 Personen. Es wird aber komplex sobald mehr Personen involviert sind:
- Müssten für eine 6-Personen-Familie alle 15 Beziehungen erfasst werden oder reichen 5?
  - Sind Beziehungen transitiv oder nicht?
- Wie wird ein vernünftiger Adressdatenexport gemacht (insbesondere: wie wird der "Nachname" zusammengestellt)?

## Beispiele und Fragen zum Thema "transitiv"
### Beziehungen nur teilweise erfasst
- Andrea, Beat und Cécile sind Geschwister im gleichen Haushalt
- Andrea - Beat und Beat - Cécile sind erfasst, Andrea - Cécile fehlt
- Wie viele Datensätze werden exportiert, wenn
  - eine Gruppe exportiert wird, wo alle 3 dabei sind?
  - eine Gruppe exportiert wird, wo nur die beiden Mädchen (Andrea und Cécile) dabei sind?

Wenn man hier optimale Zusammenfassung des Exports haben möchte, dann müssten die Beziehungen transitiv definiert sein, so dass die Beziehung zwischen Andrea und Cécile implizit vorhanden wäre.

### Andere Beziehungen
- Dominik und Daniela sind Geschwister und haben daher eine Geschwister-Beziehung. Sie leben im Haushalt D
- Esther wohnt im Haushalt E
- Fritz wohnt im Haushalt F
- Haushalte E und F haben die gleiche Postadresse aber unterschiedliche Briefkästen
- Fritz ist Dominiks bester Freund, deshalb ist für die beiden eine BestFriend-Beziehung erfasst
- Esther ist Danielas beste Freundin, deshalt ist für die beiden eine BestFriend-Beziehung erfasst
- Wie viele Datensätze werden exportiert, wenn eine Gruppe exportiert wird, in der Fritz und Esther dabei sind?

Wenn Beziehungen transitiv wären, dann würden Fritz und Esther fälschlicherweise zusammengefasst.

## Schlussfolgerung
Für mich sind diese vielen Fragen ein Zeichen dafür dass das Datenmodell "Personenbeziehung" nicht die richtige Abbildung der Wirklichkeit ist und damit zu unnötiger Komplexität führt. Es löst auch nicht die Problematik von unterschiedlich geschriebenen gleichen Adressen (Hauptstr. bzw. Hauptstrasse). Wäre es eventuell eine Idee, in Richtung "Eigene Entität 'Haushalt'" oder "Vererbung 'Adresse'" nachzudenken:
- Variante eigene Entität: Adressdaten werden nicht mehr pro Person erfasst sondern pro Haushalt, jede Person wird einem Haushalt zugeordnet.
- Variante Vererbung: Adressdaten können auf der Person erfasst werden, es ist aber auch möglich, seine Adressdaten von einem anderen Personendatensatz zu erben.

Vorteil eigene Entität: Darauf könnten auch Regeln erfasst werden, wie der Name beim Datenexport zusammengestellt werden soll.
Vorteil Vererbung: geringere Veränderungen am aktuellen Datenmodell.

**Comment by RolandStuder** [comment]
@MartinGantenbein Ah, vielen Dank für die ausführliche Beschreibung. Das sind Herausforderungen, an die ich nicht gedacht hatte.

Super Vorschläge.

Eigene Entität, wäre durchaus von Interesse, weil manche Organisationen beginnen hitobito wie ein CRM zu benutzen. Und es wäre quasi gäbig. Personen zusammenfassen zu können als Haushalt / Firma oder was auch immer. So dass ich z. B. 5 Personen vom Tagesanzeiger in einer Einheit Tagesanzeiger zusammenfassen kann. 

Das ist z. B. ein Wunsch vom DSJ https://github.com/hitobito/hitobito/issues/187

Vererbung wäre natürlich einfacher zu machen. Ist aber nicht unbedingt einfach vom mentalen Modell für die Benutzer.

**Comment by RolandStuder** [comment]
Ich schliesse dieses Issue, da wir das Feature #218 umgesetzt haben. Und das bezüglich Versand die meisten Probleme adressiert. Wenn jemand Use Cases hat, die damit nicht abgedeckt sind, dann eröffnen wir dafür neue Issues.
