### ISSUE TITLE
TECH: Cypress-Setup der PBS anschauen

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1645]
Bisher testet hauptsächlich der Kunde von Hand auf der Integrationsumgebung neue Features. Dabei werden aber längst nicht alle Auswirkungen abgefangen.

Im Rahmen der regelmässigen Releases möchten wir ein automatisiertes End-to-End-Testing aufbauen.

In diesem Rahmen soll das bereits bestehende Cypress-Setup der PBS analysiert werden, ob und wie sich dies im Core bewähren würde.

https://github.com/scout-ch/midata-cypress

# ToDo

- [ ] Issue für Umsetzung erstellen
- [ ] Workflow des Features beschreiben
- [ ] ggf. Mockup erstellen
- [ ] Tech-Spec ergänzen
- [ ] ToDo für Umsetzung definieren

**Comment by mtnstar** [comment]
ich habe diverse Punkte abgeklärt und bin zum Schluss gekommen das es im Moment keinen Sinn macht unsere Capybara Feature Specs durch Cypress zu ersetzen. 

- Die Integration in Rails von Capybara ist viel besser als die von Cypress (test db reset, clean)
- Das Setup von Cypress on Rails auf dem CI Server aufwändig
- Es gibt bereits einige Feature Specs in Hitobito
- Es macht gerade wenig Sinn einen weiteren end-to-end test stack zu integrieren

Einfach nur eine neue Technologie für e2e testing einzuführen verändert nichts an der code qualität. Wenn schon sollte man vermehrt Feature Specs mit Capybara schreiben um die Testabdeckung zu erhöhen.

**Comment by carlobeltrame** [comment]
In dem Fall sollten wir wohl https://github.com/hitobito/hitobito/pull/1506 vorwärts treiben, oder?
