### ISSUE TITLE
"Mehrfachsendungen vermeiden" auch beim CSV-Adressexport

### ISSUE THREAD

**Issue by MartinGantenbein** [hitobito/hitobito#165]
Analog zum Etikettenexport wäre es sehr nützlich, auch beim CSV-Adressexport die Option "Mehrfachsendungen vermeiden" zur Verfügung zu haben. So könnte ein Arbeitsschritt beim Erstellen von adressierten Outputs (z.B. Vereinszeitschriften) eingespart werden.

**Comment by RolandStuder** [comment]
Einverstanden. Das wäre wohl sehr praktisch und könnte insgesamt viel Kosten sparen.

**Comment by RolandStuder** [comment]
Wuurde durch #329 abgelöst und ist somit resolved.
