### ISSUE TITLE
EVENTS: Anhänge auch im Ausgeloggten Zustand anzeigen.

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1651]
@chrusu commented on [Thu Feb 17 2022](https://github.com/hitobito/hitobito_svse/issues/63)

Bisher werden Anhänge bei Anlässen nur angezeigt, wenn der Benutzer eingeloggt ist.

Neu sollen diese auch angezeigt werden, wenn der Benutzer nicht eingeloggt ist.

- [x] Partial `_attachments.html.haml` auch bei `public_events_controller#show` rendern
- [x] Zusätzlich einen Erklärungstext unter die Checkbox "Externe Anmeldungen erlauben" schreiben ala "Wenn externe Anmeldungen aktiviert sind, sind auch alle Anhänge öffentlich zugänglich."
- [ ] ~~Im AttachmentsController muss die Permission korrekt überprüft werden: Nur wenn der Event externe Anmeldungen erlaubt, darf auch das Attachment heruntergeladen werden.~~

![image.png](https://images.zenhubusercontent.com/601915a50c7c845d2798be7c/b49613ab-8d6e-4f48-b39e-b5d6f59ce19b)

Fix im Core umsetzen.

---

@olibrian commented on [Thu Feb 17 2022](https://github.com/hitobito/hitobito_svse/issues/63#issuecomment-1043152793)

Auch seitens Saas war dies schon ein Thema.

---

@chrusu commented on [Tue Feb 22 2022](https://github.com/hitobito/hitobito_svse/issues/63#issuecomment-1047811109)

Issue moved to [hitobito/hitobito #1650](https://github.com/hitobito/hitobito/issues/1650) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Michael-Schaer** [comment]
Ich denke wichtig ist, dass die Anpassung im GUI ersichtlich ist.

"Variante Null" wäre wohl, den Hilfetext bei der Checkbox "Externe können sich für diesen Anlass anmelden." zu erfassen. Das können alle selber machen.

Schöner wäre eine Info bei den Anhängen. Diese müsste ja nur erscheinen, wenn die Option zur externen Anmeldung aktiviert ist.

**Comment by TheWalkingLeek** [comment]
Anpassung an Ability nicht nötig, da Uploads aktuell öffentlich zugänglich sind: https://github.com/hitobito/hitobito/issues/1019
