### ISSUE TITLE
Wagon-Versionsinfo und -Changelog in der Fusszeile

### ISSUE THREAD

**Issue by MartinGantenbein** [hitobito/hitobito#166]
Wagons sollten die Möglichkeit haben, die Versionsangabe in der Fusszeile zu ergänzen mit Wagon-Bezeichnung, Version und Link zum Changelog des Wagons.

**Comment by RolandStuder** [comment]
Kannst du das noch etwas genauer beschreiben? Kannst du mir ein Szenario angeben, wie du dir das vorstellst. Grundsätzlich werden heute ja die Changelogs von Wagon und Core gemerged.

**Comment by MartinGantenbein** [comment]
Die Release-Zyklen von Hitobito-Core und Hitobito-Wagon stimmen nicht überein. Ich kann für einen Wagon neue Versionen releasen, ohne dass sich die Core-Version ändert. Deshalb wäre es nett, wenn in der Fussnote nicht nur "1.13" stehen würde, sondern daneben auch noch "XYZ 2.7", damit ich unterscheiden kann zwischen 1.13 / 2.7 und 1.13 / 2.8.

**Comment by RolandStuder** [comment]
Ok. Ich verstehe. Wir haben das Changelog halt vor allem für die Endanwender gemacht, die nicht sollen unterscheiden müssen zwischen was vom Core und was vom Wagon kommt.  Das Changelog soll die beiden eben zusammenfassen. 

Aber für dich würde es reichen, wenn du unterschiedliche Versionsnummern hast aber ein vereintes Changelog?

**Comment by MartinGantenbein** [comment]
Mir würde es genügen, wenn ich auch die Wagon-Version sehen könnte, vereintes Changelog ist in Ordnung.

**Comment by RolandStuder** [comment]
Ist für uns nicht so wichtig, da wir alles mit composition repos machen, ein Pull Request wäre aber nach wie vor willkommen. Schliesse dieses Issue aufgrund von Inaktivität.
