### ISSUE TITLE
PERSON: Serverfehler bei Suche mit Tag

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1660]
### Aktuelles Verhalten

Serverfehler, Tritt auf dem Testsystem auf; Produktion ist ok.

![fehler1](https://user-images.githubusercontent.com/1799621/156150458-ef6e4f73-8fa1-4277-93f2-77bb67f71e83.PNG)

![fehler2](https://user-images.githubusercontent.com/1799621/156150463-f1877d36-49a4-4ec1-a3a3-cd87ac4a8e1b.PNG)

### Gewünschtes Verhalten

Suche wird gestartet

### Schritte zu reproduzieren

1. https://pbs.puzzle.ch/de/groups/1/people_filters/new?education=false
2. Beliebigen Tag auswählen
3. Suchen

### Wann ist der Fehler aufgetreten?

01.03.2022

### hitobito version

1.27.5

### Organisation

PBS/MiData

**Comment by carlobeltrame** [comment]
Das tritt nur auf wenn die neue Login-Spalte bei den weiteren Spalten angewählt ist. Ich schaus mir an. Im Moment kannst du weiterarbeiten wenn du diese Spalte abwählst.
