### ISSUE TITLE
DSJ invalid salutation value for person

### ISSUE THREAD

**Issue by psunix** [hitobito/hitobito#167]
on production there was an invalid salutation set for some people. this causes an error when accessing the person's show site or exporting a list of people. 

maybe the invalid salutation was created by an csv import. 

to fix this, add a validator in the person model which validates the salutation's value.

https://github.com/hitobito/hitobito_dsj/blob/master/app/models/dsj/person.rb

**Comment by RolandStuder** [comment]
I guess there were no new occurences, marking this issue as `stale`
