### ISSUE TITLE
Rollen wieder entziehen

### ISSUE THREAD

**Issue by akdehof** [hitobito/hitobito#168]
Rollen sollten Personen auch wieder entzogen werden  dürfen!

**Comment by RolandStuder** [comment]
Das ist bereits möglich.

In einem Fall ist es aber nicht möglich. Du kannst keine Rollen löschen, welche dir selbst eben diese Berechtigung gibt, diese Rolle zu löschen. 

Es geht darum, dass ein Administator sich nicht einfach seine eigene Rolle löscht und seinen Zugriff verliert. Sie muss von einer anderern Person gelöscht werden.

![image](https://cloud.githubusercontent.com/assets/194364/24049693/15c5e23a-0b2d-11e7-8ace-4a85d57f4d60.png).

**Comment by akdehof** [comment]
Hi, 
Folgendes Scenario: Als Administrator möchte ich jemanden aus dem Vorstand nehmen.
Ich habe dieses Icon nicht: entweder ist seit caedd4671a5b01f2e5a2de3c077f436fe58db3dd diesbezüglich etwas passiert ODER ich habe mein hito falsch konfiguriert. In beiden Fällen wären weiterführende Hinweise nett.

**Comment by RolandStuder** [comment]
@akdehof damit ich beurteilen kann, was passsiert musst du mir etwas mehr Informationen geben:

* hast du ein öffentliches Repo vom Wagon das ich mir ansehen kann?
* Dann gib mir bitte an, in welcher Gruppe, du welche Rolle du hast...
* und welche Rolle von welcher Gruppe du entfernen möchtest.
