### ISSUE TITLE
SERVER: IP-Adressen limitieren

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1690]
### Hintergrund
Gehen wir davon aus, dass jemandem ein Angriff auf die Hitobito Systeme gelingt und so unerlaubt Daten unserer Mitglieder aus Hitobito exportiert würden. Wenn dieser Angriff aus der Schweiz kommt, können wir Anzeige erstatten, rechtlich vorgehen und eine Löschung der Daten erzwingen. Kommt der Angriff hingen von irgendwo auf der Welt, so haben wir kaum Möglichkeiten, im Nachhinein zu reagieren. Aus diesem Grund wünscht die PBS eine Limitierung der erlaubten IP-Adressen für den Zugriff auf Hitobito.

Da eine Limitierung auf Schweizer Adressen einige Schwierigkeiten mit sich bringt, schlagen wir in einem ersten Schritt vor, die umliegenden Länder der Schweiz mit dazu zu nehmen.

### Idee

- Eine Allowlist enthält alle IP-Adressen-Ranges der Schweiz, Italien, Frankreich, Deutschland, Österreich und Lichtenstein
- Die Allowlist wird (z.B.) einmal wöchentlich automatisiert aktualisiert. (Für Nginx Plus gibt es Module, die das können.)
- Der Webserver blockiert Zugriffe von IP-Adressen, welche nicht in der Allowlist vorkommen
- Es sollen auch eingehende Verbindungen auf das API blockiert werden
- In einer Testphase sollen die IP-Adressen zunächst nur geloggt und nicht blockiert werden

Optional:
- Die PBS verwaltet eine Liste von weiteren Ausnahmen (z.B. in einem öffentlichen GitHub-Repository). Diese Ausnahmen werden als zusätzliche Quelle bei der wöchentlichen Aktualisierung mit einbezogen.
- Outbound-Verbindungen (z.B. Hitobito kontaktiert MailChimp) sollen ebenfalls in einer Allowlist geführt und eingeschränkt werden.

**Comment by simfeld** [comment]
Wording-Vorschlag: Allowlist anstelle Whitelist

**Comment by carlobeltrame** [comment]
### Umsetzungsplan

1. Die übliche IP-Adressliste kann von MaxMind bezogen werden: https://dev.maxmind.com/geoip/geolite2-free-geolocation-data
    - gratis, braucht aber eine Lizenz
    - wird wöchentlich geupdatet
    - Bei ca. 96% der IP-Adressen die in der Schweiz liegen, wird eine Location im Umkreis von 250km der Schweiz zugeordnet: https://www.maxmind.com/en/geoip2-city-accuracy-comparison?country=CH&resolution=250&cellular=all. Die restlichen 4% der schweizer IP-Adressen sind keinem Land zugeordnet. Keine schweizer IPs werden weiter als 250km daneben lokalisiert.
2. Optional: Ausnahmen aus einem beliebigen PBS-kontrollierten Git-Repository während dem Docker Image Build mit einem Go-Skript in die bezogene IP-Datenbank einbauen https://blog.maxmind.com/2020/09/enriching-mmdb-files-with-your-own-data-using-go. Idee ist es, die ausnahmsweise erlaubten IPs einem neuen fiktiven Land von Ausnahmen (z.B. AA, PB, MI, OK oder ZZ wären noch frei) zuzuordnen
3. Von da aus gibts zwei Ansätze:
    - **WAF Regel** Die WAF hat bereits eine [optionale Regel](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-910-IP-REPUTATION.conf#L52), mit der high risk countries ausgeschlossen werden können. Analog dazu könnte man eine Regel machen, die jeden Request blockt, der **nicht** aus einem allowlisteten Country (CH, DE, FR, IT, LI, AT und ggf. das fiktive Land mit den zusätzlichen Ausnahmen) kommt. Für Logging auf Integration aber Blocking auf Produktion könnte diese Rule auf Integration eine tiefere Anomaly Score auslösen als auf der Produktion. Ausnahmen für einzelne Endpoints (URLs, z.B. `/oauth/profiles`) wären auch denkbar.
    - **nginx Config** statt in der WAF könnte man ein ähnliches Blocking-Verhalten auch mit Nginx-Konfiguration erreichen: https://www.dsw123.net/2021/11/26/nginx-geoip2-configuration-and-blocking-by-country/. Ausnahmen für einzelne Endpoints (URLs) wären denkbar. Für Logging und unterschiedliches Verhalten auf INT und PROD müssten noch Lösungen gefunden werden.

Bei beiden Ansätzen ist ein Update der IP-Regeln mit einem Build und Release verbunden. Bei der Variante WAF wäre die Downtime voraussichtlich etwas kürzer als bei der Variante nginx. Wir tendieren zum Ansatz WAF, falls diese tatsächlich auf Produktion eingeführt wird.

### Risiken
:warning: OAuth Applikationen die im Ausland gehostet sind werden standardmässig mal nicht mehr funktionieren, wegen dem Request im Hintergrund der von der externen Applikation an hitobito abgesetzt werden muss. Applikationen die keine kritischen Daten von hitobito lesen, aber ein Login via MiData anbieten sind besonders davon betroffen. Eine solche OAuth-Applikation könnte mit einer Ausnahme für eine IP-Adresse wieder zum Laufen gebracht werden, wobei es aber z.B. nicht ratsam wäre, die Heroku-Server o.ä. freizugeben. Alternativ könnte man eine Ausnahme für den OAuth-Profile-Endpunkt `/oauth/profile` erstellen.
:warning: Wenn wir die umliegenden Länder zulassen, bedeutet dass, das auch z.B. die IP von jemandem in Dänemark nahe der deutschen Grenze zugelassen werden könnte.
:warning: User sind generell nicht technisch versiert, und VPN ist nicht trivial und gratis einzurichten. Wenn ein AL in den Ferien ist, kann es schon vorkommen dass kein VPN eingerichtet ist und die User auch keine Chance haben eines einzurichten. In Fällen wie Auslandlagern etc. empfehlen wir daher, dass die PBS sich überlegt, ob sie ein VPN-Angebot bereitstellt.
:warning: 4% der legitimen schweizer IP-Adressen werden von der IP-Adressliste nicht erkannt, und werden erst mal blockiert. Ausnahmen für diese können bei Bedarf ergänzt werden, falls der optionale Teil umgesetzt wird.
:warning: Outbound Traffic kann mit beiden Ansätzen nicht eingeschränkt werden, hier brauchts einen komplett separaten Approach.

:warning: Beim Ansatz WAF Regel: Die WAF ist bisher nicht produktiv im Einsatz, und es ist noch unklar, wie viele unvorhersehbare Einschränkungen sie in der Praxis dann mit sich bringt. Falls später entschieden wird, die WAF wieder von der Produktion zu entfernen wird damit auch das IP-Blocking entfernt.
:warning: Beim Ansatz nginx Config: Das Geo-Blocking würde dann erst nach der WAF passieren. Alle Anfragen aus dem Ausland "belasten" die WAF weiterhin und tauchen in den WAF-Logs auf, was Analysen komplizierter machen kann.

**Comment by Michael-Schaer** [comment]
Merci Carlo für diese genaue Analyse!

Ich sehe zwei wirklich kritische Punkte:

>  Optional: Ausnahmen aus einem beliebigen PBS-kontrollierten Git-Repository während dem Docker Image Build mit einem Go-Skript in die bezogene IP-Datenbank einbauen

Aufgrund der nicht zugeordneten IP-Adressen müssen wir wohl zwingend eine Möglichkeit haben, geblockte IP-Adressen in der Liste aufzunehmen. Ich denke, das wird zu einem Must-Kriterium bei der Lösung.

> Bei beiden Ansätzen ist ein Update der IP-Regeln mit einem Build und Release verbunden.

Das ist nochmal ein kritischer Punkt. Kann das Release einmal wöchentlich automatisiert stattfinden, ohne dass dabei andere Änderungen am System einfliessen?

Weitere Punkte, die mir auffallen:

> Die restlichen 4% der schweizer IP-Adressen sind keinem Land zugeordnet

4% false-negatives (in Bezug auf die Erlaubnis, eine Verbindung herzustellen) sind doch recht viele. Ich habe noch gesehen, dass die Genauigkeit auf 2% erhöht werden kann, wenn die Lizenz auf "GeoIP2" anstatt GeoLite2 verwendet wird. Können wir diese Lizenz auch in Erwägung ziehen?

> WAF Regel Die WAF hat bereits eine [optionale Regel](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-910-IP-REPUTATION.conf#L52), mit der high risk countries ausgeschlossen werden können

Falls diese Lösung fast gratis mit der WAV mitkommt, bitte melden. Das könnte ev. auch ein erster Schritt sein, bevor wir obengenanntes angehen. Ebenfalls interessant: Könnte die WAV auch nur die Länder überprüfen und andere Funktionalitäten vorerst deaktiviert werden?

**Comment by carlobeltrame** [comment]
> > Bei beiden Ansätzen ist ein Update der IP-Regeln mit einem Build und Release verbunden.
> 
> Das ist nochmal ein kritischer Punkt. Kann das Release einmal wöchentlich automatisiert stattfinden, ohne dass dabei andere Änderungen am System einfliessen?

Ja, sollte bei beiden Varianten möglich sein. Bei der Variante WAF auf jeden Fall, da die WAF komplett separat von Rails läuft. Bei der Variante nginx Config müsste während dem Deployment vermutlich die Rails-Applikation kurz mit neugestartet werden. Aber neue Code-Änderungen und Features würden da trotzdem nicht automatisch mitkommen (auch wenn wir eigentlich sowieso in Richtung regelmässigere, automatischere Releases möchten ;) )


> 4% false-negatives (in Bezug auf die Erlaubnis, eine Verbindung herzustellen) sind doch recht viele. Ich habe noch gesehen, dass die Genauigkeit auf 2% erhöht werden kann, wenn die Lizenz auf "GeoIP2" anstatt GeoLite2 verwendet wird. Können wir diese Lizenz auch in Erwägung ziehen?

Klar, wir können auch die nicht-Lite GeoIP2 Country Datenbank verwenden. Die Lizenz dafür ist dann aber nicht mehr gratis, sondern kostet die PBS 24 USD pro Monat, gemäss [Pricing Page](https://www.maxmind.com/en/geoip2-country-database) von MaxMind. Diese Liste wird dann von MaxMind sogar zwei Mal wöchentlich aktualisiert.


> > WAF Regel Die WAF hat bereits eine [optionale Regel](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-910-IP-REPUTATION.conf#L52), mit der high risk countries ausgeschlossen werden können
> 
> Falls diese Lösung fast gratis mit der WAV mitkommt, bitte melden. Das könnte ev. auch ein erster Schritt sein, bevor wir obengenanntes angehen. Ebenfalls interessant: Könnte die WAV auch nur die Länder überprüfen und andere Funktionalitäten vorerst deaktiviert werden?

Egal welchen der beiden Ansätze wir wählen, die IP-Datenbank von MaxMind brauchen wir trotzdem. Die WAF darf aus Lizenzgründen die IP-Datenbank auch nicht einfach mitliefern, sondern verlässt sich darauf, dass wir die IP-Datenbank an einem bestimmten Ort platzieren wo die WAF sie lesen kann. Also Download und Aktualisierung der IP-Datenbank müssen wir selber machen (das ist Schritt 1 des Umsetzungsplans).
Mit der WAF nur die Länder zu überprüfen (und sonst nichts) wäre möglich, aber scheint mir [mit Kanonen auf Spatzen geschossen](https://xkcd.com/2021/). Dann wäre die Variante mit nginx deutlich effizienter, und vermutlich simpler zu maintainen.

**Comment by Vento-Nuenenen** [comment]
Es gibt NGINX geoip plugins, die ein Auto-Update bieten. Welches Plugin für NGINX würde denn eingesetzt  und geht das da auch?
Dann wäre es natürlich mega, wenn es einen Job-Container geben würde, der regelmässig Updates von der MMDB und der Allow-Liste macht und das Auto-Reload entsprechend konfiguriert wird.
Ich kann aber nicht beurteilen ob das Technisch umsetzbar ist und ob das Stabil läuft.

**Comment by carlobeltrame** [comment]
Das plugin das du vermutlich meinst das gleich noch blocking etc. machen kann gibts soweit ich gefunden habe nur für nginx plus, die bezahlte variante von nginx. Wenn wir bei der pbs nginx plus einzusetzen beginnen entfernen wir uns weiter von den anderen hitobito-instanzen, was die wartungskosten und das potenzial für bugs erhöht weil es komplexer wird, immer noch an den spezialfall zu denken.

Das modul das für die gratis-variante von nginx existiert ist exakt das was wir in der variante nginx config vorgesehen haben.

Was du mit job-container beschreibst würden wir stattdessen als regelmässig laufenden multi-stage image build umsetzen, um weniger komplexität mit read-write-pvs managen zu müssen. Aber rein vom Verhalten für Endbenutzer her wirds ungefähr so sein wie du beschreibst.

**Comment by Michael-Schaer** [comment]
Drei Ergänzungen:
- Bitte Variante nginx Config bevorzugen.
- Bitte zuerst nur Loggen, die IP-Adressen also nicht direkt sperren. Nach einer Testphase muss vermutlich noch etwas angeglichen werden, bevor wir das Feature scharf stellen können.
- Bitte erste Option (GitHub-Repository der PBS o.ä.) mit einbeziehen

**Comment by Michael-Schaer** [comment]
Nach dem Gespräch vom Dienstag haben wir uns noch einmal zu dem Thema beraten. Wir würden gerne wie folgt vorgehen: 

### Schritt 1:
- IP-Adressen auf Ebene nginx loggen (möglichst einfach, Zugriff durch Puzzle muss möglich sein)
- Optional, falls einfach möglich: Die IP-Adresse vom letzten Login soll ebenfalls in der MiData im Profil / Sicherheit angezeigt werden.

### Schritt 2:
- Auswertung der Logs im nginx
- Blockieren der Länder, die am meisten unnötige Requests verschicken

**Comment by simfeld** [comment]
> Optional, falls einfach möglich: Die IP-Adresse vom letzten Login soll ebenfalls in der MiData im Profil / Sicherheit angezeigt werden.

Korrektur: Nicht im UI anzeigen, sondern im rails log schreiben, damit dort ein Mapping von user auf IP möglich ist. Nach meinem Verständnis sollte dies einfach möglich sein, indem die im nginx-proxy bereits vorhandene Information als Header an die Applikation weitergeschickt wird.

@Michael-Schaer please confirm :-)

**Comment by patrickuhlmann** [comment]
Ich bin etwas skeptisch ob wir durch die Massnahme IP-Adresse limitieren effektiv Sicherheit gewinnen. Es scheint mir trivial als Angreifer via VPN oder auch Tor eine IP-Adresse aus der Schweiz oder umliegenden Ländern zu nutzen. 

Falls man Angriffe und Datenabflüsse verhindern möchte scheint es mir geeigneter etwas in Richtung Verhaltensanalyse zu machen wo man einen Benutzer temporär sperrt sofern dieser ungewöhnlich viele Exporte/Aufrufe ausführt oder beispielsweise Exporte ab einer gewissen Grösse von einer zweiten Person (die nicht von der ausführenden Person angelegt wurde) validiert werden müssen etc.

**Comment by Michael-Schaer** [comment]
Danke @patrickuhlmann für deine Rückmeldung. Deinen zweiten Punkt sind wir tatsächlich auch gerade am Umsetzen ([2FA Zwang für Rollen mit layer_and_below_full](https://github.com/hitobito/hitobito/issues/1300)). 

Ich verstehe, dass es etwas banal erscheint, die Bot-Zugriffe zu analysieren und zu versuchen, diese rein anhand der IP einzuschränken. Deshalb werden wir diese Funktion jetzt erst mal in einer sehr einfachen Form angehen und auswerten, wie viel wir überhaupt abwehren können.

**Comment by mtnstar** [comment]
Tickets #2084 und hitobito/hitobito_pbs#269 erstellt

**Comment by kronn** [comment]
This issue seems closed as follow-ups have been created.
