### ISSUE TITLE
INVOICE: Gelöschte Sammelrechnungen werden weiterhin gezählt

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1691]
### Aktuelles Verhalten

Wenn Sammelrechnungen gelöscht werden, werden sie zwar korrekterweise nicht mehr in der Liste angezeigt. In der Übersicht werden sie aber weiterhin als Zähler aufgeführt.
![grafik](https://user-images.githubusercontent.com/17568539/158568020-26bf48f3-5329-476b-b2aa-559df5d8970e.png)
![grafik](https://user-images.githubusercontent.com/17568539/158568065-6012704e-8385-41fd-9501-dad6cbef73a4.png)

### Gewünschtes Verhalten

Der Zähler soll die gelöschten Rechnungen nicht mehr anzeigen.

### Schritte zu reproduzieren

1. Als Root-User einloggen (oder ein anderer User, welcher bei Soldanella die Rechnungen sehen kann)
2. https://db.svse.ch/de/groups/41/invoice_lists/21/invoices besuchen, sollte leer sein
3. https://db.svse.ch/de/groups/41/invoice_lists besuchen, dort steht bei den Empfängern "70", obwohl alle Rechnungen gelöscht wurden.
4. Ebenso stimmt der Preis nicht, dort sollte 0 stehen statt 1'400.-

### Wann ist der Fehler aufgetreten?

genaues datum unbekannt, Mail kam am 09.03.2022

### hitobito version

1.27.3

### Organisation

SVSE

**Comment by olibrian** [comment]
Entspricht https://github.com/hitobito/hitobito/issues/1771
