### ISSUE TITLE
Links in footer are broken

### ISSUE THREAD

**Issue by TheNeikos** [hitobito/hitobito#17]
The links in the footer are broken, right now they redirect to: `http://hitobito.com/%22http://www.puzzle.ch//%22` 

Which is obviously not intended. 

I was unable to pinpoint the place where this happens though as [searching for "and designed with"](https://github.com/hitobito/hitobito/search?utf8=%E2%9C%93&q=and+designed+with) did not find anything.

It seems though that it is meant to be found [here](https://github.com/hitobito/hitobito/blob/master/app/views/layouts/application.html.haml#L90) but is not? Are the sources here older?

**Comment by RolandStuder** [comment]
@TheNeikos Hi  thanks for reporting this. We escaped some stuff wrongly.

You did not find the issue, because, the website is in a seperate repository. See https://github.com/hitobito/hitobito.github.io/tree/source if you are interested.

Thanks, and have a wonderful week!

**Comment by TheNeikos** [comment]
Alright, that explains it, thanks.
