### ISSUE TITLE
 fehlende Möglichkeit Link auf externes Anmeldungsinterface zu setzen (Event wird von extern organisiert)

### ISSUE THREAD

**Issue by akdehof** [hitobito/hitobito#171]

**Comment by RolandStuder** [comment]
@akdehof Kannst du mir bitte eine ausführlicherer Beschreibung geben, was du meinst? Ich kann aus dem Titel alleine nicht erschliessen, was dein Anliegen ist.

**Comment by akdehof** [comment]
Für die Mitglieder meines Vereins würde ich gerne einen Kurs eintragen, der aber von einer anderen Institution gehalten wird. In der Anmelde-Info gibt es neben Anmeldestart/ende auch einen Link zum Anmelden, der zeigt aber immer auf demo.hitobito (wenn Anmeldung für extern freigegeben)
Das ist vermutlich anders gedacht :-) , Ich würde aber gerne auf eine externe Konferenz verlinken können

**Comment by RolandStuder** [comment]
Ah, ich verstehe. Es ist genau umgekehrt gedacht. Das aktivierne von "externen Anmeldungen" soll erlauben, dass sich irgendwelche Personen, welche den Link haben, sich eben anmelden können, auch wenn sie nicht zum Verein gehören.

Ich denke für den vorliegenden Fall ein extra Feature zu bauen, macht wenig Sinn. Aber wir könnten einstellen, dass Links in der Beschreibung zumidnest anklickbar wären. Dann könntest du einfach einen Anlass erfassen mit abgelaufenem Anmeldedatum. Dann kommt nämlich auch kein Anmelden Button.

**Comment by RolandStuder** [comment]
Keine Aktivität mehr auf diesem Issue, schliesse es deshalb. Und ein Workaround ist beschrieben.
