### ISSUE TITLE
History not updating properly (8h)

### ISSUE THREAD

**Issue by peschmae** [hitobito/hitobito#172]
After issuing a password reset, and logging in to hitobito, I see a change to my user, but the person issuing to change, is the last person that edited my record.

Even though it might make sense, to now show password reset attempts, they either shouldn't show up in the changes, or should show up as anonymous user, since you don't need to be logged in, to issue the password reset link.

**Comment by RolandStuder** [comment]
@peschmae Am I correct in assuming you mean the change indication on the detail view of a person?

![image](https://cloud.githubusercontent.com/assets/194364/23353670/f049ef0a-fccd-11e6-97a2-c44670e8967a.png)

Might be not such a quick fix, as I assume the date shown is based on the person models last_edited which is controlled by rails. We will see, but it's maybe not worth fixing. 

So two possibilites:

* don't show passwort reset attempt as a change.
* Show anonymous user or "passwort reset" as a user

Thank you for the report

**Comment by hairmare** [comment]
That looks like what we where seeing, I think it was in the "Log" tab as well. 

At a glance, in the history tag it looked like the last editor had triggered the password reset. I feel this might confuse someone who does not have any experience with the inner workings of hitobito.

I think displaying it as "anon" or "password reset" makes most sense.

**Comment by RolandStuder** [comment]
Ok. I see. Thanks for describing the issue. I see it, but we don't see it as a priority. But should be easy enough to fix. As Papertrail provides the possibility to set a "whodunnit" manually.

**Comment by codez** [comment]
The password reset happens in Devise, so we have to adjust the behavior there.

**Comment by codez** [comment]
Schätzung: bis 1PT

**Comment by RolandStuder** [comment]
Marking this issue as inactive, as there has been no further discussion and it has no priority.
