### ISSUE TITLE
MODULE: Membership verify token

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito#1744]
### Aktuelles Verhalten

Wenn in der Personenübersicht die anzuzeigenden Spalten ausgewählt werden, dann erscheint die Auswahlmöglichkeit "Membership verify token". Dies ist aber offensichtlich nicht erwünscht.

### Gewünschtes Verhalten

Das "Membership verify token" sollen in der Spaltenauswahl nicht mehr erscheinen.

### Schritte zu reproduzieren

1. Eine Gruppe auswählen.
2. In den Personen-Tab wechseln.
3. In der rechten oberen Ecke auf "Spalten" klicken.
4. "Membership verify token" ist auswählbar.

### Wann ist der Fehler aufgetreten?

Fr. 13. Mai

### hitobito version

1.27.6

### Organisation

SKV

### Screenshots, weiterer Kontext

![image](https://user-images.githubusercontent.com/69250571/169760495-d50dc4c8-c8c2-467d-98c7-7cd281cefd50.png)

**Comment by carlobeltrame** [comment]
Die geschilderten Symptome werden in #1695 gefixt. Trotzdem sollten wir dieses Feld noch in den Person::INTERNAL_ATTRS eintragen.
