### ISSUE TITLE
PERSON: after_destroy-Hooks auf Role laufen sofort statt zum Löschzeitpunkt

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#1748]
### Aktuelles Verhalten

Seit #1714 kann das Enddatum einer Rolle in der Zukunft gesetzt werden. Dazu wurde das paranoia Gem modifiziert, weil dieses den Use Case nicht unterstützen [will](https://github.com/rubysherpas/paranoia/issues/480).

Die Rolle gilt jetzt erst am eingegebenen Löschdatum als gelöscht. Jegliche `before_destroy` / `after_destroy` / `before_save` / `after_save` Hooks auf Model und Controller laufen aber trotzdem direkt zu dem Zeitpunkt an dem die Rolle bearbeitet wird, nicht am eingegebenen Löschdatum.

Im Core sind das folgende Aktionen:
- RolesController#last_primary_group_role_deleted
- Role#reset_contact_data_visible
- Role#reset_primary_group

Zumindest im Jubla Wagon verlässt man sich zudem bei den automatisch erstellten Ehemaligen-Rollen sehr auf die korrekte Funktionalität der `after_destroy` Hooks.
Ausserdem ist erstmals beim SBV ein Bug aufgetreten, dass Personen nicht aus der globalen Suche verschwinden, wenn ihre letzte Rolle via Zukunftsdatum gelöscht wird (und möglicherweise danach noch einmal eine primary group gesetzt wird).

Um das zu beheben könnten diese Hooks in scheduled Jobs ausgelagert werden, wenn ein Löschdatum in der Zukunft gesetzt wird. An [anderen Orten in hitobito](https://github.com/hitobito/hitobito_pbs/issues/273) sowie in anderen Rails-Projekten tendieren wir aber für solche Zwecke eher zu einem regelmässig laufenden Aufräum-Job, weil es bei einzelnen Jobs z.B. schwierig werden kann, wenn die Rolle dann doch wieder reaktiviert wird etc.

### Gewünschtes Verhalten

Die Logik der Hooks läuft erst zu dem Zeitpunkt ab dem die Rolle wirklich als gelöscht gilt.

### Schritte zu reproduzieren

Beispiel mit primary group (mit Stern markierte Rolle):
1. Als eine Person mit mehreren Rollen einloggen
2. Stern bei einer löschbaren Rolle setzen
3. Diese Rolle bearbeiten und ein Enddatum in der Zukunft setzen und speichern
4. Es kommt eine Flash Message "Hauptgruppe auf xyz geändert.", wobei xyz die Gruppe der gerade bearbeiteten Rolle ist. Die Rolle ist noch da und ist immer noch primary, also macht die Message keinen Sinn (der entsprechende Code in RolesController#last_primary_group_role_deleted sollte korrekterweise noch nicht laufen)
5. Das eingegebene Enddatum abwarten
6. Die Person hat jetzt eine ungültige primary group, weil die markierte Rolle inzwischen als gelöscht gilt.

### Wann ist der Fehler aufgetreten?

24.5.2022

### hitobito version

1.27.21

### Organisation

alle, speziell Jubla, vielleicht noch andere Wagons

#### Kontext und Vorüberlegungen
Da Wagons noch weitere `after_destroy` Hooks einführen können, brauchen wir ein System, das auch in den Wagons verwendet werden kann.
Ausserdem könnten noch weitere Hooks betroffen sein (gibt es z.B. `before_destroy`? Wird in ActiveRecord sonst noch ein Model Hook während `destroy` getriggert?). Diese sollten durch unser System auch gleich abgedeckt werden können.
Wenn ein Rollen-Enddatum in der Zukunft ist, und dann die Rolle bearbeitet wird und das Löschdatum in die Vergangenheit verschoben wird, dann müssen die Hooks ebenfalls laufen.
Zusätzlich ist es absehbar, dass bald auch ein Rollen-Startdatum in der Zukunft ermöglicht wird, was noch einmal mehr Anforderungen an das hier entwickelte System stellen wird.

#### Vorgeschlagener Fix
- [ ] Neue Spalte `deletion_processed_at` auf `Role` anlegen
- [ ] Neue class methods `after_future_destroy`, `before_future_destroy` etc. für alle betroffenen Hooks erstellen, welche ein Callback akzeptieren (bessere Namen würden begrüsst werden)
- [ ] Täglich laufenden DelayedJob erstellen, der **in_batches** Rollen sucht, deren `deleted_at` in der Vergangenheit ist, und deren `deletion_processed_at` entweder `nil` ist oder vor `deleted_at` liegt
  - [ ] Callbacks ausführen, Hook-Reihenfolge beachten (`before_destroy` kommt vor `after_destroy`)
  - [ ] `deletion_processed_at` ausfüllen
- [ ] Wenn die Rolle bearbeitet wird, und `deleted_at` vorher nicht in der Vergangenheit war (also `nil` oder in der Zukunft war) und neu in die Vergangenheit gesetzt wurde, dann die Callbacks auch direkt ausführen, um bisheriges Verhalten zu replizieren. Das kann vielleicht auch erreicht werden, indem in den neuen `after_future_destroy` etc. Hooks intern doch noch `after_destroy` aufgerufen wird, mit Zusatzbedingung dass `deleted_at` in der Vergangenheit liegen muss
- [ ] In allen Wagons nach relevanten Hooks auf `Role` und Subtypen suchen und diese mit dem neuen Mechanismus ersetzen
- [ ] Specs möglich? Zeitreise simulieren und Job im Test manuell triggern?

#### Vorschlag 2
Siehe Kommentare https://github.com/hitobito/hitobito/issues/1748#issuecomment-1752017234 und https://github.com/hitobito/hitobito/issues/1748#issuecomment-1752163965

**Comment by kronn** [comment]
Vielleicht ist paranoia nicht mehr das richtige Gem für den Use-Case, den wir haben. Man könnte zu explizitem "als gelöscht markieren" mit [Discard](https://github.com/jhawthorn/discard) wechseln. Bedingt natürlich ein paar Umbauarbeiten, wenn wir viel mit den Hooks machen, könnte es da aber wert sein.

**Comment by carlobeltrame** [comment]
Ich sehe gerade nicht, inwiefern das neue Gem unsere Situation verbessern würde. Soweit ich sehe ist Discard einfach ein Rewrite von paranoia, der ein paar [fundamentale Probleme](https://github.com/jhawthorn/discard#why-not-paranoia-or-acts_as_paranoid) anders zu lösen versucht, nicht aber unseres. Auch bei Discard wird [`discard_column == nil`](https://github.com/jhawthorn/discard/blob/master/lib/discard/model.rb#L17) als nicht gelöscht und [`discard_column.present?`](https://github.com/jhawthorn/discard/blob/master/lib/discard/model.rb#L106) als gelöscht betrachtet.

Einziger praktischer Unterschied für uns wäre die Terminologie "gelöscht" vs. "weggeworfen". Und allenfalls wäre man dort offener, eine offizielle [Extension](https://github.com/jhawthorn/discard#extensions) für in der Zukunft liegende Discards zu führen. Aber bis da hin wäre es noch ein weiter Weg.

**Comment by mtnstar** [comment]
Alternativ könnte man ein :future_delete_at Datum einführen.
Dieses Feld wird befüllt wenn eine Rolle auf ein Datum in der Zukunft terminiert wird, das :deleted_at Feld wird in diesem Fall leer gelassen.
Ein regelmässiger Job (täglich, stündlich) würde dann am Tag auf dem die Rolle via :future_delete_at terminiert wurde, diese Rolle dann mit role.destroy! effektiv löschen. So würde alle destroy hooks entsprechend mit getriggert.

**Comment by daniel-illi** [comment]
Ich finde den Vorschlag von @mtnstar gut. So funktionieren die callbacks immer noch wie gewohnt. Und es scheint mir semantisch auch korrekter, wenn das `deleted_at` erst gesetzt wird wenn die Rolle gelöscht wird. Z.B. funktionieren die Paranoia scopes dann auch so wie man es erwartet.

**Comment by carlobeltrame** [comment]
Können wir machen. Die Komplexität bleibt gleich, aber unsere Modifikationen an Paranoia in #1739 müssen wir dann reverten. Nicht zu vergessen sind aber die Edge Cases, wenn man ein bereits gesetztes `future_deleted_at` bearbeitet und in die Vergangenheit setzt, und umgekehrt. Bei PaperTrail sollten wir ebenfalls kontrollieren, dass alles verständlich angezeigt wird.

**Comment by mtnstar** [comment]
merci @amaierhofer, ich denke das ist auf dem richtigen Weg so.

könnten wir evtl. einfach auch einen Clean-Up Job Schedulen sobald ein delete_on datum in der Zukunft gesetzt wird? Anstatt einen Cronjob zu haben?
bzw. der CronJob läuft vielleicht nur 1 mal täglich um noch aufzuräumen.

**Comment by carlobeltrame** [comment]
> könnten wir evtl. einfach auch einen Clean-Up Job Schedulen sobald ein delete_on datum in der Zukunft gesetzt wird? 

Diese Idee habe ich schon beim Refinement verworfen, weil es praktisch unmöglich ist, den geschedulten Job abzuräumen oder abzuändern, wenn das Rollenenddatum später nochmals geändert wird. Der regelmässige Job ist der einzige sinnvolle Weg. Siehe zu diesem Thema auch die Diskussion die ich im devruby-Chat angefangen habe: https://chat.puzzle.ch/channel/devruby?msg=JStAmsADNi2D3qNP5
