### ISSUE TITLE
PERSON: Keine zusätzlichen Angaben nach Filter

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito#1749]
### Aktuelles Verhalten

Bei der Personenübersicht in einer Gruppe kann das Feld "zusätzliche Angaben" angezeigt werden.
Wird aber auf die Übersicht ein Filter angewandt, so erscheint dieses Feld leer.

### Gewünschtes Verhalten

Der Inhalt des Feldes "zusätzliche Angaben" soll auch angezeigt werden, wenn ein Filter auf die Personenübersicht angewendet wird.

### Schritte zu reproduzieren

1. Nach dem Login auf das Personen-Tab einer beliebigen Gruppe.
2. Bei der Spaltenauswahl "zusätzliche Angaben" anwählen.
3. Unter "Weitere Ansichten" ein "Neuer Filter..." erstellen. (Getestet mit Filter nach Personen mit einem bestimmten Tag)
4. Die Spalte der "zusätzlichen Angaben" bleibt bei den nun angezeigten Personen leer.

### Wann ist der Fehler aufgetreten?

Fr. 13. Mai

### hitobito version

1.27.6

### Organisation

Alle (SKV)

**Comment by carlobeltrame** [comment]
Das ist exakt das Problem das in #1695 gelöst wird.
