### ISSUE TITLE
Anpassung Kursfilter: Kantonsübergreifende Sichtbarkeit von Kursen

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#1757]
Die Jubla möchte Anpassungen am Kursfilter vornehmen, damit Mitglieder selbst ausserkantonale Kurse einfacher finden können.

Neu sollen Kurse, welche das Flag "Anlass ist für die ganze Datenbank sichtbar" aktiviert haben, auch von Mitgliedern aus anderen Kantonsverbänden unter dem Tab "Kurse" gefunden werden.

Diskussion: Ist dies etwas, was sich im ganzen Youth-Wagon entsprechend ändern lässt? Was sind hier die Interessen insbesondere der PBS, welche dieses Feature einst so designt hat, dass die einzelnen Mitglieder möglichst nur das sehen, was sie sehen müssen.

# Tech-Spec
- Nur im Jubla Wagon (Cevi auch interesse? -> https://github.com/cevi/hitobito_cevi/issues/150)
- Alle Personen ab Ebene Leitungsperson sollen sollen die Kursübersicht analog einer Abteilungsleitung bei der PBS dargestellt erhalten.
    - Standardmässig alle Ebenen mit Involvierung (die eigene Ebene und die darüberliegenden) anzeigen lassen
    - als Option mit dem drop-down-Menü auch alle anderen Kursorganisatoren auswählen können – oder durch Klick auf «Alle Gruppen» direkt alle Kurse anzeigen lassen
- Als weitere Spalte (z.B. zwischen Datum und Anmeldestand) soll der Hauptorganisator (= Kanton, in welchem der Kurs erfasst wurde) ersichtlich sein.

**Comment by nchiapol** [comment]
Ist hier wirklich der Cevi gemeint?
Wir hatten kürzlich ein ähnliches Problem: https://github.com/cevi/hitobito_cevi/issues/150
Wir sind damit aber noch nicht auf euch zugekommen... ;-) 

Da ich annehme, dass auch die Suche mit dieser Einstellung verknüpft ist, darfst du aber das abel interest-cevi gerne wieder ergänzen.

**Comment by ThomasEllenberger** [comment]
Hatte hier bei der Erstellung ein bischen ein Durcheinander mit den Jugendverbänden.  :)
Der Task wird durch die Jubla in nächster Zeit noch genauer definiert und ausformuliert werden, kann das Cevi label aber gut bereits wieder ergänzen und wir können sobald dies konkreter wird nochmals anschauen, ob sich evtl. euer Problem damit auch beheben lassen würde.

**Comment by Michael-Schaer** [comment]
Hallo zusammen, bei der PBS hat die Einschränkung der Sichtbarkeit noch einen fachlichen Hintergrund.

Und zwar haben die kantonalen Ausbildungsverantwortlichen (AV) gewünscht, dass Teilnehmer*innen sich nicht selber für Kurse anmelden, die nicht im eigenen Kanton stattfinden. Stattdessen sollen die Teilnehmer*innen jeweils die AVs des eigenen Kantons informieren, diese verteilen dann die Personen auf (ausserkantonale) Kurse.

Bitte für die PBS nicht ändern oder eine Lösung suchen, die für uns auch funktioniert. Wir helfen gerne mitdenken, wenn es konkreter wird.

**Comment by richardjubla** [comment]
> Und zwar haben die kantonalen Ausbildungsverantwortlichen (AV) gewünscht, dass Teilnehmer_innen sich nicht selber für Kurse anmelden, die nicht im eigenen Kanton stattfinden. Stattdessen sollen die Teilnehmer_innen jeweils die AVs des eigenen Kantons informieren, diese verteilen dann die Personen auf (ausserkantonale) Kurse.
> 
Der Filter sollte die Berechtigungen des User (Sieht Kurse im Verband oder "nur" Kurse in seinem Kanton/ seiner Stufe) und die Einstellungen des Kurses (Einstellung: Anlass ist für die ganze Datenbank sichtbar) berücksichtigen.

Diese Option sehe ich bei der Jubla nicht aber bei der Pfadi


<img width="1076" alt="image" src="https://user-images.githubusercontent.com/95908537/172347189-97a12e79-fd97-468d-a6c9-d8e885ada6d7.png">





![image](https://user-images.githubusercontent.com/95908537/172347435-899c01e5-bb0d-4407-aae1-691c388c5ccb.png)

**Comment by richardjubla** [comment]
> Die PBS hat diese Option auch, sie haben sie sogar selber entwickeln lassen: #1047. Sie ist nur bei Kursen ausgeblendet und immer aktiviert, mit folgender Begründung:
> 
> > In Zusammenhang mit dem Ausbildungsmodell müssen Kurse bei der PBS für alle potentiellen Teilnehmenden sichtbar sein. Entsprechend muss eine kleine Anpassung vorgenommen werden: Das Flag "sichtbar für die ganze Datenbank" soll im UI beim Erstellen/Bearbeiten eines Kurses versteckt werden und immer auf "ja/sichtbar" gesetzt sein. Auch in der Datenmigration sollen die bestehenden Kurse das Flag erhalten.

Ihr macht alle Kurse in der gesamten DB sichtbar, um dann den Filter um genau diese Eigenschaft wieder einzuschränken? Vielleicht sehe ich das zu einfach: Hier wurde aber evtl. ein eigener "Bug" produziert.
Kurse welche in der ganzen Datenbank sichtbar sein sollen, sollten doch auch in der Kursübersicht für alle erscheinen. Kurse mit Einschränkungen können nur von den jeweils berechtigten Personen bewirtschaftet werden. 


_Wenn wir den Standard-Filter für den User auf seine Ebene als Start-Einstellung festlegen, würden hier zuerst nur die Kurse im eigenen Kanton angezeigt._ 
 
Kurse können nur über die öffentliche Anmeldung und ihre Sichtbarkeit eingeschränkt werden. Wenn die Pfadi also die Anmeldung für Kurse pro Kanton einschränken will, solle hier eine andere Lösung gefunden werden?

**Comment by richardjubla** [comment]
`
Wir haben uns mit dem Thema weiter beschäftigt und präsentieren einen Vorschlag, der lediglich die Berechtigungen (und Filtermöglichkeiten) der Jubla DB betrifft. Wir gehen davon aus, dass wir damit eine eigenständige, aber Hitobito-fähige Lösung finden.
`




**ZIEL:**
_Als Datenbank-Nutzer*in der Jubla möchte ich die für mich relevanten Kurse in der Kursübersicht sehen und filtern können. Die Kursorganisatoren möchten den Nutzenden eine einfachere Übersicht der ausserkantonalen Kurse bieten, um auch alternative Angebote zu sehen und sich dafür anmelden zu können. Kursteilnehmende melden sich in der Jubla immer selber für Kurse an. _


**IST-ZUSTAND:**
Wenn ich bei der Jubla als Scharleitung angemeldet bin, dann werden als Auswahl nur die Ebenen mit meiner Involvierung (die eigene Ebene und die darüberliegenden) dargestellt, andere kann ich gar nicht auswählen. Der Klick auf «Alle Gruppen» zeigt nur diese verfügbaren Gruppen an. Dieselbe Kursübersicht wird auch einer Gruppenleitung dargestellt:
![image](https://user-images.githubusercontent.com/95908537/175995597-6d878a0b-fcf2-46ae-9fba-957e13bb63cd.png)

 
Wenn ich bei der Pfadi als Abteilungsleiter*in angemeldet bin, werden alle Kursträger als Auswahl dargestellt (als direkte Auswahl zum Anklicken mit dem + sind die Ebenen mit Involvierung und als drop-down können alle weiteren ausgewählt werden – oder direkter Klick auf «Alle Gruppen», dann werden auch effektiv alle Gruppen dargestellt):
 


Wenn ich bei der Pfadi als Stufenleiter angemeldet bin, dann werden als Auswahl nur die Ebenen mit meiner Involvierung dargestellt, andere kann ich nicht auswählen (analog zur Jubla):
![image](https://user-images.githubusercontent.com/95908537/175995690-f1ccf1dd-d43b-43b8-b6e3-2009b219f8e7.png)


**SOLL-ZUSTAND**
Die Kursübersicht der Pfadi soll für die verschiedenen Rollen so beibehalten werden wie sie jetzt ist (gemäss Absprache mit Philippe Keller).

Die Kursübersicht für die Jubla soll angepasst werden: Alle Personen ab Ebene Leitungsperson sollen die Kursübersicht analog einer Abteilungsleitung dargestellt erhalten; sprich: Standardmässig alle Ebenen mit Involvierung (die eigene Ebene und die darüberliegenden) anzeigen lassen; aber als Option mit dem drop-down-Menü auch alle anderen Kursorganisatoren auswählen können – oder durch Klick auf «Alle Gruppen» direkt alle Kurse anzeigen lassen.


**ERWEITERUNG**
Um in der Übersicht trotzdem noch klar zu sehen, von welchem Kanton der Kurs organisiert wird, sollte als weitere Spalte (z.B. zwischen Datum und Anmeldestand) der Hauptorganisator (= Kanton, in welchem der Kurs erfasst wurde) sichtbar sein, damit sie sehen, in welchem Kanton sie sich anmelden. 
(Hintergrund: In der Jubla werden alle Module für alle Kantone ausgeschrieben, so werden dann in der ersten Spalte diverse Kantone aufgeführt. Und bei der Übersicht über alle Kurse soll der Hauptorganisator trotzdem klar erkennbar sein.)
 
![image](https://user-images.githubusercontent.com/95908537/175995936-6a78f53a-6888-4bde-91b5-a1b2b87ca36b.png)
Hauptorganisator = graues Kästchen mit Haken; sprich Gruppe, in welcher der Kurs angelegt wurde.

**ASPEKTE**
- Abhängigkeit der Berechtigungen (Sichtbarkeit) von Kursen beachten. (Kurse können auch global für alle sichtbar veröffentlicht werden) Die Option "Anlass ist für die ganze Datenbank sichtbar" beachten/bedenken nach Möglichkeit weiterhin funktional halten (Filter-Berechtigungen, Sichtbarkeit und Berechtigungen)
- Klären, ob eine Unterscheidung zwischen "sichtbar" und "anmeldbar" besteht und oder nötig oder gewünscht ist

**Comment by kronn** [comment]
Wird in Issue 1813 erledigt.
