### ISSUE TITLE
Feld "Firma" soll automatisch vorgeschlagen werden. (4h)

### ISSUE THREAD

**Issue by jharari** [hitobito/hitobito#176]
IST: -

SOLL: Wenn ich im Feld Firma (Personenattribut) etwas eingebe, werden aus den bestehenden Einträgen bei Firma die bereits verwendeten Bezeichnung vorgeschlagen.

## Erweiterung falls genug Zeit übrig

Partial Matching nicht unbedingt nötig. Aber wenn mit ca. 2h machbar, dann sicherstellen, dass z. B. bei Eingabe von `BSV` auch `Bundesamt für Sozialversicherungen` vorschlägt.

* Matched wenn diese Buchstaben in gleicher Reihenfolge

**Comment by RolandStuder** [comment]
@jharari bitte Abnehmen, du kannst es ausprobieren auf: http://dsj.puzzle.ch (Partial Matching ist nicht implementiert)

Wenn alles OK ist: Bemerkung "OK, abgenommen" hinterlegen.
Wenn nicht OK, Bemerkung "Nicht OK: " und was inkorrekt ist.

Als Erinnerung den Integrationsumgebungen werden keine echten Mails verschickt, diese werden an https://mailtrap.io verschickt und können dort überprüft werden.

**Comment by jharari** [comment]
Ok, abgenommen.
