### ISSUE TITLE
EVENTS: Zeilenabstände in der Beschreibung nicht vorhanden

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1763]
### Aktuelles Verhalten

In der Beschreibung von Anlässen, Kursen und Lagern werden Zeilenabstände nicht dargestellt.

![image](https://user-images.githubusercontent.com/1799621/174541359-577e9a3c-47cb-4633-8435-3e48cc1c560a.png)

Im Bearbeitungsmodus sind die Zeilenabstände drin und werden richtig angezeigt. Erst bei der Anzeige des Anlasses tritt der Fehler auf.

### Gewünschtes Verhalten

Zeilenabstände werden im Feld Beschreibung angezeigt.

### Schritte zu reproduzieren

Beispiel: https://pbs.puzzle.ch/de/groups/920/events/1787

### Wann ist der Fehler aufgetreten?

20.06.2022

### hitobito version

1.27.26

### Organisation

PBS/MiData, vorhanden im Core

**Comment by carlobeltrame** [comment]
Vermutlich eine Folge von #1669

**Comment by tschuepbach** [comment]
Bei der Cevi tritt dieses Problem anscheinend nur bei der externen Kurs-Übersicht auf. Sobald jemand eingeloggt ist, scheint das Problem nicht mehr zu bestehen.

**Comment by carlobeltrame** [comment]
Bei den Redirect URIs von OAuth Applikationen tritt esebenfalls auf.

**Comment by tschuepbach** [comment]
Betrifft bei Cevi auch das Feld "Ort / Adresse" auf Events

**Comment by Michael-Schaer** [comment]
Merci fürs Beheben!

**Comment by tschuepbach** [comment]
Bei uns scheint das Problem noch nicht behoben zu sein...
See: https://cevi.puzzle.ch/groups/6/public_events/1161 (extern) / https://cevi.puzzle.ch/groups/6/events/1161
