### ISSUE TITLE
EVENT: Upload von einem File

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1770]
### Aktuelles Verhalten

Wenn bei einem Event eine Datei hochgeladen wird, erscheint nicht der korrekte Filename:

![image](https://user-images.githubusercontent.com/9592347/176175341-e0fc3533-a25a-4200-a2e6-b4f20585b7ad.png)

File ist aber korrekt hochgeladen und kann via Link heruntergeladen werden.

### Gewünschtes Verhalten

Filename wird in der Meldung korrekt angezeigt

### Schritte zu reproduzieren

1. File auf einem Event hochladen
2. Meldung anschauen

### Wann ist der Fehler aufgetreten?

28.06.2022

### hitobito version

1.27.27

### Organisation

Core, getestet in der SWW Umgebung

### ToDos

Ansätze:
- [ ] Möglichkeit finden, AttachedOne mit vernünftigem `.to_s` zu versehen
- [ ] Meldung für Uploads manuell anpassen
	- Event-Attachments
	- Gruppenlogo
	- Profilbild
	- OAuth-Logo
	- Bild für PDFs in GroupSettings

**Comment by kronn** [comment]
In der aktuellen Version kommt gar keine Benachrichtigung. Daher tritt auch der Darstellungsfehler nicht auf. Ich finde das erstmal okay so. Wenn nicht, dann bitte wieder eröffnen.
