### ISSUE TITLE
INVOICE: InvoiceList update total nach Löschung

### ISSUE THREAD

**Issue by TheWalkingLeek** [hitobito/hitobito#1771]
### Aktuelles Verhalten

Wenn in einer Sammelrechnung eine Rechnung gelöscht wird, aktualisiert sich "Empfänger insgesamt" & "Betrag insgesamt" der Sammelrechnung nicht

### Gewünschtes Verhalten

Eine Sammelrechnung soll, nach dem update/destroy einer Rechnung innerhalb, aktualisiert werden. 

### Schritte zu reproduzieren

1. Sammelrechnung anlegen
2. Rechnung in erstellter Sammelrechnung löschen
3. "Empfänger insgesamt" & "Betrag insgesamt" der Sammelrechnung ansehen

### Wann ist der Fehler aufgetreten?

29.06.2022

### hitobito version

1.27.28

### Organisation

Core

### Screenshots, weiterer Kontext

Sammelrechnung wird mittels `update_total` aktualisiert:
https://github.com/hitobito/hitobito/blob/master/app/models/invoice_list.rb#L62

### ToDos

ToDo

- [ ] Mittels model hooks (oder ähnlichem) `invoice_list.update_total` aufrufen
- [ ] Specs erweitern/schreiben
- [ ] SWW informieren

**Comment by tschuepbach** [comment]
Funktioniert leider nur, wenn eine einzelne Rechnung gelöscht (storniert) wird. Via Mehrfachauswahl -> Stornieren werden die Zahlen auf der Übersicht nicht aktualisiert..

Ich kann aktuell leider keine Testrechnungen verlinken, da ich auf unserer Test-Umgebung lauter 500er erhalte.. (#2119)

**Comment by tschuepbach** [comment]
Bei uns immer noch nicht gefixt!

Test-Case: https://cevi.puzzle.ch/groups/334/invoice_lists/18/invoices
Folgende Person imitieren: https://cevi.puzzle.ch/groups/335/people/3086

Kann dieses Ticket wieder geöffnet werden?

**Comment by nchiapol** [comment]
@thomasellenberger

**Comment by nchiapol** [comment]
@thomasEllenberger: alles klar
@tschuepbach: kannst du dich um ein neues Ticket kümmern?
