### ISSUE TITLE
PERMISSION: Berechtigung für Rechnungen auf der Person personal_invoices

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1776]
### Aktuelles Verhalten

Was sind die Bedingungen/Berechtigung, damit ich auf einer Person das Tab Rechnungen `personal_invoices` sehe?

Meine Vermutung: Aktuell wird das Tab nur angezeigt, auf Personen welche selber auch für eine `finance` Ability verfügen.

### Gewünschtes Verhalten

Personen mit `finance` Ability sehen das Tab bei Personen im ganzen Layer (ohne Layer unterhalb)
Auf der eigenen Person ist diese Tab immer sichtbar.

### Schritte zu reproduzieren

1. In einem Layer wo ich selber `finance` Ability habe
2. Person mit `finance` Ability anschauen (z.b. Kassier)
3. Person ohne `finance` Ability anschauen (z.b. Mitarbeitende)

![Rechnungstab3](https://user-images.githubusercontent.com/9592347/177573546-98f1c169-7143-40e5-bce1-836fd6e274c5.gif)

### Wann ist der Fehler aufgetreten?

06.06.2022

### hitobito version

1.27.30

**Comment by kronn** [comment]
Zusammen in "Die Mitte 205"
