### ISSUE TITLE
PEOPLE: Personen ohne Rollen unterhalb des Dachverbands löschen können

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#1780]
### Aktuelles Verhalten

Auf allen Layers existiert eine Gruppe "Ohne Rollen" (deleted_people). Auf dieser Liste wurde in hitobito/hitobito_kljb#7 ein Lösch-Button hinzugefügt, den Admins drücken können um die rollenlose Person direkt hart zu löschen.
Auf der entsprechenden Seite "Ohne Rollen" des Dachverbands funktioniert das wie gewünscht. Aber auf Layers unterhalb der Root-Gruppe kommt bei der Verwendung ein 404. Logs:
```
ActiveRecord::RecordNotFound (Couldn't find Person with 'id'=112989 [WHERE `roles`.`deleted_at` IS NULL AND `roles`.`group_id` = ?]):

app/controllers/crud_controller.rb:118:in `find_entry'
app/controllers/people_controller.rb:127:in `find_entry'
app/controllers/crud_controller.rb:108:in `entry'
```

Grund ist, dass im people_controller eine Ausnahme für die Root-Gruppe existiert: https://github.com/hitobito/hitobito/blob/master/app/controllers/people_controller.rb#L127

### Gewünschtes Verhalten

Der Lösch-Knopf funktioniert auf allen Layers korrekt.

### Schritte zu reproduzieren

1. Einer Person in einem Sub-Layer die letzte Rolle wegnehmen
2. Auf die Ansicht "Ohne Rollen" gehen
3. Den Lösch-Knopf der soeben bearbeiteten Person drücken

### Wann ist der Fehler aufgetreten?

7.7.2022

### hitobito version

1.27.19.2

### Organisation

Die Mitte

### Screenshots, weiterer Kontext

https://help.puzzle.ch/#ticket/zoom/4246

**Comment by richardjubla** [comment]
Des Verhalten ist auf jubla.db reproduzerbar

[Version 1.28.0](https://db.jubla.ch/changelog)
hitobito ([6356086a](https://github.com/hitobito/hitobito/commits/6356086a2534240b0c5f049beb3bb844367e9ce0))
hitobito_jubla ([9a8af77d](https://github.com/hitobito/hitobito_jubla/commits/9a8af77d8de66459714e6f28cd29b24becc21aa0))
hitobito_youth ([e8d680ae](https://github.com/hitobito/hitobito_youth/commits/e8d680ae86bc70acd827619601418d92c309f4e0))

![image](https://user-images.githubusercontent.com/95908537/181000784-3a1c782e-f1a2-45e1-aa82-9c5d63fbfac7.png)

**Comment by KunoKunz** [comment]
Das habe ich heute auch bei den Multitenants (piraten) erlebt und wollte es gerade melden ;-)
