### ISSUE TITLE
PERSON: Login senden für Passwort-Reset funktioniert nicht bei Abos

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito#1792]
### Aktuelles Verhalten

Wir haben in der DB einen Krisen-User (https://db.cevi.ch/groups/2350/people/27464, Rolle Mitarbeiter der Geschäftsstelle), der den Mitgliedern des Krisenteams zugriff auf die Datenbank gibt. Der User hat als Hauptmail-Adresse das Abo des Krisenteams eingetragen und ein zufälliges Passwort. Im Krisenfall wird dann via "Passwort vergessen" ein neues Passwort gesetzt. 

Ich habe eben versucht diesem User in der einen "Passwort-Reset-Link" zu senden in dem ich auf der Person unter Login auf "Login senden" geklickt habe. 

Gemäss Tooltip: "Person hat ein Login. Diese Aktion sendet ihr einen Link, damit sie ihr Passwort neu setzen kann."

Das Mail mit dem Link wurde aber nie versendet. (Taucht nie in den Nachrichten des Abos auf).

Eben hatte ich noch die Richtige Intuition: Das Mail landet im Spam...
![image](https://user-images.githubusercontent.com/1123483/180518509-d81eb32a-9230-4413-9f96-f394ec02e6aa.png)
Ich habe die Mails eben gelöscht, da ich mir das Mail via "Passwort vergessen" beim Login unterdessen selbst zu gestellt habe.

Alles in allem ist das kein grosses Probelm - aber doch etwas überraschend, dass Hitobito seinen eigenen Mails nicht traut ;-)
Und möglicherweise greift der selbe Effekt auch noch an anderen unerwarteten Orten...

### Gewünschtes Verhalten

Das Mail wir korrekt zugestellt.

### Schritte zu reproduzieren

Das Problem ist reproduzierbar für diesen User, tritt aber für meinen normalen User nicht auf (habe mir via imitieren ebenfalls einen Link gesendet) und in der Integration scheint das sowohl für User mit einer normalen Adresse, wie auch für mit einem Abo nicht auf.

### Wann ist der Fehler aufgetreten?

heute zwischen 21:00 und 22:00 (Timestamp beim Spam sind falsch...)

### hitobito version

1.28.0

### Organisation

Cevi

**Comment by kronn** [comment]
Die Spam-Beurteilung wird nicht von hitobito selbst gemacht, sondern findet auf dem Mailserver statt. Normalerweise sieht der Mailserver solche "Passwort zurücksetzen"-Mails nicht und es ist auch ungewöhnlich, dass Mails von hitobito auf dem Mailserver landen. Es ist ja auch unüblich, wenn man zu Hause klingelt :-)

Es kann hier helfen, wenn man die Mails in den Eingang verschiebt. Damit wird der Spamfilter trainiert und kann künftige Mails besser einsortieren.
