### ISSUE TITLE
EVENTS: Sichtbarkeit Anlass ist für die ganze DB sichtbar

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito#1793]
In unserer hitobito-Instanz und täglichen Arbeit ist uns aufgefallen, dass die Option bei einem Anlass "Sichtbarkeit: Anlass ist für die ganze Datenbank sichtbar" nicht zum für uns erwarteten Effekt führt.

![Bildschirmfoto 2022-07-24 um 20 15 48](https://user-images.githubusercontent.com/1453303/180660629-54bfd710-fb9e-41e4-8daf-e3ed72320d2a.png)

Wir erwarten spontan, dass solche Anlässe allen Benutzern von hitobito angezeigt werden, wenn diese im Menü links unter Anlässe schauen. Dies ist jedoch nicht der Fall. (Beispiel-Event: https://sbv.puzzle.ch/de/groups/86/events/61 ist nicht sichtbar für die Person https://sbv.puzzle.ch/de/groups/1592/people/16366.html)

Was bewirkt diese Option eigentlich ganz genau?

# ToDo, nachdem die Diskussion ein Ergebnis hat

- [ ] Diskussionsergebnisse zusammenfassen
- [ ] Issue für Umsetzung erstellen
- [ ] ggf. Mockup erstellen
- [ ] Tech-Spec ergänzen
- [ ] ToDo für Umsetzung definieren

**Comment by carlobeltrame** [comment]
Siehe auch die verwandte aktuelle Diskussion in #1757

**Comment by kronn** [comment]
Wird in Issue 1813 erledigt.
