### ISSUE TITLE
TECH: Mails für Mailinglisten Integrationsumgebungen funktionieren nicht mehr

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#1795]
### Aktuelles Verhalten

Mails an eine beliebige Mailingliste einer beliebigen Puzzle Hitobito Integrationsumgebung werden nicht mehr zugestellt seit der Umstellung auf Openshift 4.

### Gewünschtes Verhalten

Mails werden zu Testzwecken in die Mailtrap.io Box der jeweiligen Integrationsumgebung zugestellt.

### Schritte zu reproduzieren

1. Mail an Mailingliste Integrationsumgebung. z.B. blabli@hgh.integration.example.com
2. Mail wird nicht zugestellt da aktuell kein MX record

### ToDos

- [x] Neuen Domain inkl. MX Entry für die Integrationsumgebungen erstellen: cname.integration.hitobito.com
- [x] Alle Subdomains der Integrationsumgebungen per CNAME auf die neue Domain zeigen lassen

**Comment by kronn** [comment]
https://gitlab.puzzle.ch/pitc_sys/pitc-dns/-/merge_requests/815

**Comment by kronn** [comment]
MX Record wurde hinzugefügt, mails kommen an. Nicht verwunderlich, aber schön. :-)
