### ISSUE TITLE
Filter auf Reiter Notizen (1h)

### ISSUE THREAD

**Issue by jharari** [hitobito/hitobito#181]
Auf Tab Notizen, will ich auswählen können, ob ich nur Personennotizen  / nur Gruppennotizen oder beides sehen kann.

Vorbedingung: #147

**Comment by jharari** [comment]
Gruppen-Notizen sollen nach Jahr dargestellt werden analog "Anlässe".

**Comment by RolandStuder** [comment]
Filter Nur Ebene / Gruppen

**Comment by codez** [comment]
Unklar. Was sind Gruppennotizen? Welches ist das Datum des Kontaktes? Filter "Nur Ebene / Gruppen" ist wohl "Nur Gruppe / Gesamte Ebene"? Skaliert eine Paginierung nach Jahr, wie viele Notizen pro Ebene und Jahr werden erwartet?

**Comment by RolandStuder** [comment]
@codez Ah, sorry, Gruppennotizen wären ein neues Feature siehe #147

**Comment by codez** [comment]
Schätzung: 1PT
