### ISSUE TITLE
PERSON: Zugriffsprüfung bei Rollen-Enddatum in der Zukunft

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#1821]
### Aktuelles Verhalten

Wird auf einer Rolle ein Enddatum in der Zukunft festgelegt, dann gilt die Rolle seit #1714 erst ab diesem zukünftigen Datum als gelöscht, nicht ab sofort.
In Personenlisten und Abos haben wir aber eine Zugriffsprüfung die direkt in der Datenbank berechnet wird, verkapselt in die `PersonFetchables` Klasse und deren Subklassen. Diese Klassen verwenden immer noch den alten Check `deleted_at != NULL` um zu bestimmen ob eine Rolle gelöscht ist oder nicht. Das kann dazu führen, dass Personen mit zukünftigen Rollen-Enddaten in Personenlisten, Abos und Exporten fälschlicherweise nicht mehr auftauchen.

Möglicherweise gibt es auch noch andere Stellen im Code wo der Null-Check noch verwendet wird.

### Gewünschtes Verhalten

* Die Logik mit erlaubten zukünftigen Löschdaten soll überall im Code konsistent umgesetzt werden.
* Konkret sollten zumindest die `PersonFetchables` und Subklassen zukünftige Löschdaten als "noch nicht gelöscht" ansehen.

### Schritte zu reproduzieren

1. Auf einer Personenrolle ein Löschdatum in der Zukunft setzen
2. Eine Personenliste aufrufen, in der die Person wegen dieser Rolle auftauchen sollte
3. Die Person taucht nicht auf

### Wann ist der Fehler aufgetreten?

22.8.2022

### hitobito version

1.28.x

### Organisation

Alle

### Screenshots, weiterer Kontext

Verwandtes aber separates Ticket zu den `after_destroy` Hooks die ebenfalls sofort statt erst in der Zukunft laufen: #1748

**Comment by richardjubla** [comment]
Ergänzung: Neu zugewiesene Rollen und Abos scheinen nicht korrekt zu funktionieren, wenn Rollen mit einem Termin versehen sind. Siehe dazu https://help.puzzle.ch/#ticket/zoom/4296

Fehler: Person Rolle mit Enddatum zuweisen -> Person bekommt keine Mitteilungen von Abo mit zugewiesener Rolle 
Aktueller Fix: Rolle muss ohne Enddatum erstellt werden. -> Abo anpassen/aktualisieren -> Rolle wieder mit Enddatum versehen
