### ISSUE TITLE
2FA: erster Versuch schlägt meist fehl

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito#1830]
### Aktuelles Verhalten

Wenn ich mich mit 2FA einlogge ist mein One-time-Passwort regelmässig erst im zweiten Anlauf gültig.

### Gewünschtes Verhalten

Ein frisches Passwort wird bereits im ersten Versuch akzeptiert.

### Schritte zu reproduzieren

Bei mir mit 80% zuverlässigkeit:
1. Login auf Hitobito mit 2FA aktiviert
2. Erzeugen des OTP via yubico-authenticator
3. OTP sofort ins entsprechende Feld kopieren und absenden
-> login schlägt fehl
4. OTP noch einmal ins Feld einfügen und absenden
-> login funktioniert

### Wann ist der Fehler aufgetreten?

seit OTP bei mir aktiviert ist (2-3 Monate)

### hitobito version

1.28.0

### Organisation

Cevi

**Comment by carlobeltrame** [comment]
Ist deine Uhr auf dem Handy auf die Sekunde genau korrekt eingestellt? Könnte es vielleicht an der app liegen? Ich verwende die andOTP app und hatte ebenfalls seit der Einführung noch nie Probleme

**Comment by nchiapol** [comment]
Ist nicht mein Handy, ist mein Computer + YubiKey. Ich gehe auch davon aus, dass die Uhr das Problem ist - aber da ich mit der gleichen App nur bei der CeviDB Probleme habe gehe ich davon aus, dass die Toleranz bei euch erhöht werden sollte. 

(Ich bin wohl soweit ein Spezialfall, als dass ich den OTP-code per copy paste eingebe und deshalb wohl oft < 1s brauche zwischen generieren und einfügen.)

**Comment by carlobeltrame** [comment]
Hier ist die Doku der TOTP Library die wir verwenden, wo beschrieben wird wie man "drift", also sozusagen Toleranz, hinzufügen kann: https://github.com/mdp/rotp#verifying-a-time-based-otp-with-drift
Achtung: Es könnte sein dass z.B. mit 10s Drift das alte Token noch 10s länger gültig ist, aber dafür ein brandneues Token erst mal für 10s noch nicht gültig ist. Da müsste man die Doku noch genauer lesen, um die Möglichkeiten abzuklären.

Die Änderung müsste [hier](https://github.com/hitobito/hitobito/blob/master/app/domain/people/one_time_password.rb#L30) beim Aufruf von `authenticator.verify(token)` gemacht werden. Entweder im Wagon die ganze Methode überschreiben, oder im Core die Parameter einfügen und mit einem Setting befüllen (`Settings.foo.bar.baz`, Wert in config/settings.yml im Core und/oder Wagon setzen).

**Comment by cleverer** [comment]
> Ist nicht mein Handy, ist mein Computer + YubiKey. Ich gehe auch davon aus, dass die Uhr das Problem ist - aber da ich mit der gleichen App nur bei der CeviDB Probleme habe gehe ich davon aus, dass die Toleranz bei euch erhöht werden sollte.
> 
> (Ich bin wohl soweit ein Spezialfall, als dass ich den OTP-code per copy paste eingebe und deshalb wohl oft < 1s brauche zwischen generieren und einfügen.)

Bist jedenfalls nicht der einzige Spezialfall ;)

Hab das selbe Problem und das nun am Hitobito-Hackathon angeschaut.
