### ISSUE TITLE
BUCHUNGSBELEG: Falsche Berechnung einer Zeile

### ISSUE THREAD

**Issue by TheWalkingLeek** [hitobito/hitobito#1839]
### Aktuelles Verhalten

Bei den SWW ist ein Bug aufgetreten, dass eine Zeile nicht korrekt berechnet wurde.
Dadurch ist dann auch die Spenden-Zeile falsch. Das ist aber eher ein Folgefehler, statt das Ursprungsproblem.
Die Daten sahen eigentlich sauber aus, ich konnte bei kurzer Analyse nicht erkennen wo genau der Fehler liegt.
-> https://help.puzzle.ch/#ticket/zoom/5211

### Gewünschtes Verhalten

Die Berechnung sollte wie erwartet stimmen

### Schritte zu reproduzieren

Siehe Ticket

### Wann ist der Fehler aufgetreten?

14.09.2022

### hitobito version

1.28.15

### Organisation

SWW

### Screenshots, weiterer Kontext

Siehe Ticket

### ToDos

- [ ] Lokal reproduzieren (DB Dump oder anderswie)
- [ ] Fixen
- [ ] Specs anpassen

**Comment by daniel-illi** [comment]
LGTM :thumbsup
