### ISSUE TITLE
COURSE LIST: Error 500

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#1861]
### Aktuelles Verhalten

Auf der Kursliste kann es zu 500er Fehlern kommen.
Bisher nur auf Jubla Integration aufgetreten, Cevi und PBS sind (zumindest bisher) nicht betroffen.

https://jubla.puzzle.ch/list_courses?filter%5Bsince%5D=28.09.2022&filter%5Buntil%5D=28.09.2023&filter%5Bstates%5D%5B%5D=&filter%5Bstates%5D%5B%5D=created&filter%5Bstates%5D%5B%5D=confirmed&filter%5Bstates%5D%5B%5D=application_open&filter%5Bstates%5D%5B%5D=application_closed&filter%5Bstates%5D%5B%5D=assignment_closed&filter%5Bstates%5D%5B%5D=completed&filter%5Bstates%5D%5B%5D=closed&filter%5Bplaces_available%5D=0&filter%5Bgroup_ids%5D%5B%5D= 
![image](https://user-images.githubusercontent.com/95908537/192703903-d92dcf56-835b-4b53-97b5-4e7b2153f4e6.png)

_Originally posted by @richardjubla in https://github.com/hitobito/hitobito/issues/1813#issuecomment-1260446651_
      

### Gewünschtes Verhalten

Kurse können normal durchsucht werden.

### Schritte zu reproduzieren

1. In der linken Seitennavigation auf "Kurse" klicken
2. Alle "Veranstalter" löschen und auf "Suchen" klicken.
3. Error 500 tritt auf Jubla Integration auf

### Wann ist der Fehler aufgetreten?

2022-09-28

### hitobito version

1.28.19

### Organisation

Jubla

### Screenshots, weiterer Kontext

Sentry-Meldung: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/58085/

**Comment by richardjubla** [comment]
Der gleiche "Bug" erscheint bei der Auswahl von "allen" oder von "keinen" gruppen.

**Comment by richardjubla** [comment]
Auf [Version 1.30.20](https://jubla.puzzle.ch/changelog) erfolgreich getestet -> OK
