### ISSUE TITLE
Vernetzung Firma und Personen (4h)

### ISSUE THREAD

**Issue by jharari** [hitobito/hitobito#187]
* [x] Neues Tab auf Person mit Titel "Mitarbeiter"
* [x] Tab erscheint nicht, falls kein Firmenname eingetragen ist.
* [x] Gezeigt werden alle Personen, welche denselben Firmennamen eingetragen haben.
* [x] Personen auf die ich keinerlei Zugriff habe, werden nur mit Bild / Vor- / Nachname dargestellt.
* [x] Personen auf welche ich Zugriff habe, werden als vollständige Zeil mit Kontaktangaben dargestellt.
* [x] Umsetzung im Core
* [x] Paginated Liste
* [x] Sortiert nach Nachname

## Optionen

Falls das gratis mit Personenliste mitkommt:

* [x] Sortierbarkeit zulassen

![image](https://cloud.githubusercontent.com/assets/194364/26578570/ab0a8674-4530-11e7-9d21-e429a3af1435.png)

**Comment by RolandStuder** [comment]
@jochanen Unklar, ob es einzig darum geht, darzustellen, dass alle Personen von X zu einer Firma / Organisation gehören.

* Oder geht es darum, das auch bei Exporten nur konsolidiert auszugeben. Nur 1 Kontakt pro Firma
* Notizen zusammenfassen pro Firma, wenn man die Firma anschaut...

**Comment by RolandStuder** [comment]
@jharari Unklar, ob es einzig darum geht, darzustellen, dass alle Personen von X zu einer Firma / Organisation gehören.

* Oder geht es darum, das auch bei Exporten nur konsolidiert auszugeben. Nur 1 Kontakt pro Firma
* Notizen zusammenfassen pro Firma, wenn man die Firma anschaut...

**Comment by jharari** [comment]
es geht hauptsächlich mal darum, darzustellen, dass alle Personen von X zu einer Firma gehören. 
die weiteren Details (Export, Notizen) kann man zu einem späteren Zeitpunkt anschauen.

**Comment by codez** [comment]
Kann mit Personenbeziehungen gelöst werden.

**Comment by codez** [comment]
Schätzung: 0.5PT

**Comment by psunix** [comment]
review ok

**Comment by RolandStuder** [comment]
@jharari bitte Abnehmen, du kannst es ausprobieren auf: http://dsj.puzzle.ch

Wenn alles OK ist: Bemerkung "OK, abgenommen" hinterlegen.
Wenn nicht OK, Bemerkung "Nicht OK: " und was inkorrekt ist.

**Comment by jharari** [comment]
Ok, abgenommen.
