### ISSUE TITLE
EVENTS: Warnung fehlende Qualifikation wird nicht angezeigt

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#1870]
### Aktuelles Verhalten

bezieht sich auf das Feature welches mit #1640 umgesetzt wurde.

1. Kurs mit Qualifikationsart welche als Vorbedingung  "muss gültig sein" hat
   ![image](https://user-images.githubusercontent.com/655627/193804993-b4c3831b-fb57-4881-914c-61dc4b4e6b4a.png)
2. Eine Person mit abgelaufener Qualifikation als TeilnehmerIn einem Kurs mit dieser Qualifikationsart hinzufügen
3. Es wird keine Warnung auf der Teilnehmerseite angezeigt

Beispiel Jubla Integration:

1 - Teilnehmerin hat gar keine Qualifikation -> Warnung wird angezeigt 
https://jubla.puzzle.ch/groups/1/events/623/participations/3941

2 - Teilnehmerin hat Qualifikation die abgelaufen ist -> Warnung wird NICHT angezeigt
https://jubla.puzzle.ch/groups/1/events/623/participations/4086

### Gewünschtes Verhalten

Wenn die Qualifikationsart die Vorbedingung  "muss gültig sein" hat, muss auch eine entsprechende Warnung bei betroffenen TeilnehmerInnen angezeigt werden.

### Schritte zu reproduzieren

1. Qualifikationsart mit Vorbedingung "muss gültig sein" erstellen
2. Kurs mit dieser Qualifikationsart erstellen
3. Teilnehmerin hinzufügen bei welcher die Qualifikations abgelaufen ist

### Wann ist der Fehler aufgetreten?

https://github.com/hitobito/hitobito/issues/1640#issuecomment-1255955076

### Organisation

Jubla

**Comment by mtnstar** [comment]
das Verhalten ist abhängig davon ob die Option 'reaktivierbar' auf der Quali Art gesetzt ist oder nicht:

![image](https://user-images.githubusercontent.com/655627/195584859-22999f88-290d-4089-8100-d28ac8f27545.png)

ich verstehe nicht warum reaktivierbar Einfluss auf die Vorbedingung haben sollte. 

@ThomasEllenberger merci fürs klären

**Comment by mtnstar** [comment]
WIP auf branch: bug/1870_qualification_warnings

**Comment by ThomasEllenberger** [comment]
Meines Erachtens handelt es sich hier tatsächlich um einen bug.
Die Reaktivierbarkeit soll neu keinen Einfluss mehr auf die Warnung welche auf einer Person angezeigt wird.

Hat ein Kurs als Bedingung "Muss gültig sein" so muss die entsprechende Qualifikation gültig sein!
Ist die Qualifikation abgelaufen, befindet sie sich im Reaktivierbarkeits Zeitfenster, oder wurde nie eine Qualifikation vergeben soll eine entsprechende Warnung angezeigt werden.

Hat ein Kurs als Bedingung "Muss gültig oder weggefallen sein" so muss die Person die Qualifikation irgendwan erhalten haben. Es spielt jedoch keine Rolle, ob die noch gültig ist, oder sich im reaktivierbaren Zeitraum befindet, oder ungültig ist. Nur wenn nie eine Qualifikation vergeben wurde, soll hier eine Warnung angezeigt werden.

**Comment by richardjubla** [comment]
Fehler:

Wird eine bestehende Vorbedingung bearbeitet, zeigt es die drei Optionen korrekt an. Wird eine neue Vorbedingung hinzugefühgt, zeigt es "undefined" statt "Muss gültig oder reaktivierbar sein" an.

![image](https://user-images.githubusercontent.com/95908537/199975775-b83036d6-29a4-4a81-bb9a-3b8578c66cbe.png)

**Comment by richardjubla** [comment]
Fehler: 

Unterscheidung der Warnungen "abgelaufen" oder "fehlt" (im Profil / im Kurs) wird nicht korrekt ausgegeben. 
Beziehend auf auf https://github.com/hitobito/hitobito/issues/1640#issuecomment-1266803386 


Beispiel:
https://jubla.puzzle.ch/groups/1/events/623/participations/4086
![image](https://user-images.githubusercontent.com/95908537/199981870-0e439bcd-5538-4674-8ec6-5e1860e4c84c.png)
Bei dieser Person ist die Qualifikationen abgelaufen, wird in den Warnungen aber als fehlend angegeben. Die
 Kursadministration kann so anhand der Warnung nicht direkt Auskunft geben oder reagieren. Die Unterscheidung von abgelaufen/fehlt spielt hier eine Rolle uns ist nur über einen Aufruf der einzelnen Person herauszufinden. 

![image](https://user-images.githubusercontent.com/95908537/199980053-dff5a174-826b-45c3-8eec-350357dc3694.png)

Optional korrekter Text welcher den Status der Qualifikation nicht berücksichtigen würde: 
`Folgende Qualifikationen fehlen oder sind abgelaufen: J+S Leiter*in LS/T Jugendsport`

**Comment by ThomasEllenberger** [comment]
> Fehler:
> 
> Wird eine bestehende Vorbedingung bearbeitet, zeigt es die drei Optionen korrekt an. Wird eine neue Vorbedingung hinzugefühgt, zeigt es "undefined" statt "Muss gültig oder reaktivierbar sein" an.
> 
> ![image](https://user-images.githubusercontent.com/95908537/199975775-b83036d6-29a4-4a81-bb9a-3b8578c66cbe.png)
> 
> Betrifft wohl [d0b1a21](https://github.com/hitobito/hitobito/commit/d0b1a2158a346948ca7b909ea42251389146d392) @carlobeltrame

Wurde behoben und wird nun korrekt angezeigt.

**Comment by richardjubla** [comment]
Präzisierung zu https://github.com/hitobito/hitobito/issues/1870#issuecomment-1303540549

Wir gehen wir mit dem generischen Textvorschlag, der unabhängig vom Zustand der Qualifikation ist:
```
Folgende Qualifikationen fehlen oder sind abgelaufen: J+S Leiter*in LS/T Jugendsport
Folgende Qualifikationen fehlen oder sind abgelaufen: {Variablen aller fehlenden Qualis}
```

**Comment by richardjubla** [comment]
Fehler mit "undefined" (https://github.com/hitobito/hitobito/issues/1870#issuecomment-1305655507) getestet und **als gelöst befunden**.

**Comment by ThomasEllenberger** [comment]
> Präzisierung zu [#1870 (comment)](https://github.com/hitobito/hitobito/issues/1870#issuecomment-1303540549)
> 
> Wir gehen wir mit dem generischen Textvorschlag, der unabhängig vom Zustand der Qualifikation ist:
> 
> ```
> Folgende Qualifikationen fehlen oder sind abgelaufen: J+S Leiter*in LS/T Jugendsport
> Folgende Qualifikationen fehlen oder sind abgelaufen: {Variablen aller fehlenden Qualis}
> ```

Wir haben deinen Textvorschlag so übernommen. Nun wird dieser immer angezeigt, unabhängig von fehlenden oder abgelaufenen Qualifikationen.
Dies ist aktuell nur in der Deutschen Sprache der Fall, wenn ihr, oder @nchiapol die Cevi oder @Michael-Schaer die PBS dies auch in anderen Sprachen möchten, müsst ihr das im Transifex noch entsprechend übersetzen.

**Comment by richardjubla** [comment]
@mtnstar @ThomasEllenberger 


![image](https://github.com/hitobito/hitobito/assets/95908537/e60335bd-7165-4d7a-8855-5f03c1c3d8a8)


In der Version [Version 1.30.20](https://jubla.puzzle.ch/changelog) sind die Formatierungsfehler (noch/wieder?) drin. 
In der produktiven Umgebung ([Version 1.28.30.2](https://db.jubla.ch/changelog)) gibt es den Fehler nicht.


Es geht um:
https://github.com/hitobito/hitobito/issues/1640#issuecomment-1266803386 

Ging dies Vergessen? 
![image](https://github.com/hitobito/hitobito/assets/95908537/76d23288-b52e-4ae6-89b9-1acfe711cfce)
