### ISSUE TITLE
EVENTS: Error 500 bei Administrationsangabe ohne Inhalt

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1874]
### Aktuelles Verhalten

Bei einigen Kursen werden die Teilnehmenden nicht angezeigt, sondern ein Serverfehler (Error 500).

Beispiel:
https://db.scout.ch/de/groups/238/events/20539/participations?returning=true

### Gewünschtes Verhalten

Die Teilnehmerliste wird dargestellt.

### Schritte zu reproduzieren

1. Login als eine Rolle mit Berechtigung auf die Kurse
2. Link öffnen: https://db.scout.ch/de/groups/238/events/20539/participations?returning=true
3. Der Fehler erscheint

### Wann ist der Fehler aufgetreten?

06.10.2022

### hitobito version

1.28.19

### Organisation

PBS/MiData

**Comment by Michael-Schaer** [comment]
Merci für den Tipp, das hat geklappt! Ja, ein Fix oder eine nützliche Fehlermeldung wäre aus Benutzersicht sicher besser!

Ich habe den Titel angepasst, damit das Issue etwas besser erkennbar ist.

**Comment by carlobeltrame** [comment]
Das wurde in #1880 behoben soweit ich sehe.
