### ISSUE TITLE
EVENTS: SLRG Export

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1875]
Liebe Youth-Community

Bei uns wurde Ende letztes Jahr noch das Bedürfniss nach einem SLRG-Export diskutiert. Wie steht ihr dazu? @richardjubla @nchiapol

---

Die Assistenz Aussbildung meldet die Kursteilnehmenden von spezifischen Kursen direkt nach der Durchführung an die SLRG. Für diese Datenweitergabe wäre ein massgeschneiderter Export direkt aus der MiData nützlich. Betroffen sind 15 Kurse pro Jahr. Womöglich wäre auch Cevi und Jubla an der Funktion interessiert.

Es handelt sich um die Kurse «Modul im Sicherheitsbereich Wasser», «Modul Wasser», «SLRG Brevet Basis Pool», «SLRG Modul Fluss» und «SLRG Modul See».

### Anforderungen
- Export der Kursteilnehmenden pro Kurs mit Spalten nach Vorlage "Tocco" (Zweites Sheet "Import")
- Nur Kursteilnehmende ohne Leitung
- Spalte "Geschlecht" mehrsprachig als Text 
- Spalte "Sprache" mit Werten "de", "fr" und "it"
- Spalten "SLRG-Nr." und "Status" werden leer gelassen
- Optionale Spalten (Anrede, Telefon, Bemerkung) werden leer gelassen
- Wenn möglich Spaltennamen oben analog Vorlage
- Optimal: Direkt in die entsprechende Excel-Vorlage, damit nichts mehr rüberkopiert werden muss

### Abgrenzung
- Nur Spalten unter "Person" und "Adresse" (Blau und Grau). Rote kommen nicht aus der MiData
- kein Export über mehrere Kurse (oder alle SLRG-Kurse)
- Keine Drop-Downs oder andere Logik
- Umsetzung per Schnittstellentool oder innerhalb MiData

**Links:**
[Import_Vorlage_Tocco_V4.xlsx](https://github.com/hitobito/hitobito/files/9724230/Import_Vorlage_Tocco_V4.xlsx)

**Comment by nchiapol** [comment]
Bei uns scheinen nicht viele SLRG-Kurse angeboten zu werden. Für uns hat deshalb ein entsprechender Export sehr tiefe Priorität. Wenn der existiert würde der aber sicher auch genutzt.
