### ISSUE TITLE
PERSON: E-MAIL und Selbstregistrierung

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1878]
### Aktuelles Verhalten

Bei der Selbstregistrierung gibt es einen Serverfehler, wenn eine ungültige E-Mail eingetragen wird.

### Gewünschtes Verhalten

Bei einer ungültigen E-Mail kommt eine nützliche Fehlermeldung im GUI.

### Schritte zu reproduzieren

- Private Tab öffnen
- https://pbs.puzzle.ch/de/groups/428/self_registration
- E-Mail "test841203@bluewin.ch" eingeben

![image](https://user-images.githubusercontent.com/1799621/194892264-dedac425-d7bb-4614-b6bf-8e4591771d11.png)

### Wann ist der Fehler aufgetreten?

10.10.2022

### hitobito version

[Version 1.28.20](https://pbs.puzzle.ch/de/changelog)

### Organisation

PBS

### Screenshots, weiterer Kontext

Ich wollte es auch auf demo.hitobito.com testen, jedoch ist dort die Version nicht die gleiche.

**Comment by kronn** [comment]
@TheWalkingLeek hast du diesen Fehler nicht letztens behoben?

**Comment by TheWalkingLeek** [comment]
Jup genau das wird innerhalb https://github.com/hitobito/hitobito/pull/1981 gelöst :)
