### ISSUE TITLE
INVOICE: Bei Veränderung einer Position wird Total nicht aktualisiert

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito#1885]
### Aktuelles Verhalten

1 * 10 != 100
![image](https://user-images.githubusercontent.com/1123483/196380565-d086d98f-dfe5-4584-b429-590024693805.png)

### Gewünschtes Verhalten

Das Total wird korrekt nachgeführt.

### Schritte zu reproduzieren

1. Rechnung erstellen
2. Position mit beliebigem Betrag erfassen
3. Rechnung speichern
4. Rechnung bearbeiten
5. Position ändern (Anzahl oder Preis)
6. speichern

### hitobito version

1.28.21

### Organisation

Cevi

**Comment by nchiapol** [comment]
Der Betrag wird korrekt aktualisiert, wenn die alte Position gelöscht und eine neue erfasst wird.

**Comment by ThomasEllenberger** [comment]
Ich konnte das Verhalten nachstellen, es scheint jedoch sehr selektiv zu sein.

Ich habe auf der Cevi Integration eine neue Rechnung erstellt, und das Verhalten war wie oben beschrieben. 
Ich habe den Betrag auf einer älteren, bereits existierenden Rechnung geändert und der Betrag hat sich korrekt geändert.
Auch konnte ich den Bug auf der Hitobito Praesentations Umgebung nicht nachstellen, dort hat es für mich in jedem Fall korrekt funktioniert. Auf anderen Testumgebungen hat es jedoch auch wieder funktioniert... Bug nur auf Integrationsumgebungen?

**Comment by TheWalkingLeek** [comment]
https://github.com/hitobito/hitobito/tree/bug/1885_update_invoice_total

After update hook eingefügt um die invoice zu recalculaten

Manuelles Testing fehlt noch
