### ISSUE TITLE
ABOS: Anlässe hinzufügen, älter als 1 Jahr

### ISSUE THREAD

**Issue by tschuepbach** [hitobito/hitobito#1888]
### Aktuelles Verhalten

Ich habe versucht ein Abo für bestimmte Anlässe der letzten ~4 Jahre zu erstellen. Die Suche innerhalb vom Abo findet aber nur Anlässe vom Jahr 2021 und 2022. Ältere werden nicht gefunden oder angezeigt.

Ich habe auf alle relevanten Events Schreibrechte.

### Gewünschtes Verhalten

Suche innerhalb vom Abo findet alle gewünschten Events, unabhängig vom Durchführungsjahr. 

### Schritte zu reproduzieren

1. Nach dem Login auf beliebiger Ebene/Gruppe Abo erstellen
2. Versuchen nach Events zu suchen, welche älter als ein Jahr sind (Jahrzahl ist massgebend)

### Wann ist der Fehler aufgetreten?

20.10.2022

### hitobito version

1.28.0

### Organisation

Cevi

### Screenshots, weiterer Kontext

![S1](https://user-images.githubusercontent.com/40494600/197410322-970509bd-f3c1-4833-8252-078331e120f0.png)

![S2](https://user-images.githubusercontent.com/40494600/197410331-9a49efcf-ad06-4fcd-bb96-90258921a821.png)

**Comment by carlobeltrame** [comment]
It's not a bug, it's a feature ;)
https://github.com/hitobito/hitobito/blob/master/app/models/subscription.rb#L102
Das ist explizit so ausprogrammiert, dass da frühestens Anlässe von Anfang letztem Jahr kommen.
Grund ist tatsächlich ein Berechtigungsproblem. Weitere Details gebe ich dir gerne per Mail, inklusive verschiedenen Optionen wie wir vorgehen könnten. Dann könnt ihr intern diskutieren und nochmals ein Issue mit dem gewünschten Vorgehen eröffnen.
