### ISSUE TITLE
Readthedocs: Übersetzung FR & IT

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#1894]
Die PBS übersetzt die Hitobito Benutzeranleitung auf Italienisch und Französisch.

Wenn man jedoch beispielsweise [https://hitobito.readthedocs.io/it/latest/roles.html ](https://hitobito.readthedocs.io/it/latest/roles.html) aufruft, ist dort noch gar keine Seite vorhanden.

Durch dieses Ticket soll evaluiert werden, wass alles zu tun ist, um Readthedocs für die Mehrsprachigkeit vorzubereiten.

Zuvor wurde bereits eine Konfigurationsdatei für Transifex erstellt: https://github.com/hitobito/user_documentation/pull/6
Darin ist aber noch kein automatischer Sync von / zu Transifex enthalten, und readthedocs ist überhaupt noch nicht darauf [konfiguriert](https://docs.readthedocs.io/en/stable/localization.html) die Übersetzungsdateien zu nutzen.

**Comment by betsim** [comment]
Der SBV hat sein [Handbuch](https://hitobito-manual-sbv-de.readthedocs.io/de/latest/) unter Readthedocs ebenfalls auf Französisch übersetzt (Italienisch kommt noch).

Wir haben für jede Sprache ein Git-Repo erstellt: `hitobito-manual-fr` und `hitobito-manual-de`. Das ist m.E. notwendig, damit man mit Readthedocs verschiedene Sprachen bewirtschaften kann.

Die Primärsprache ist Deutsch. Die Übersetzungen machen wir mit GitLocalize. GitLocalize kann aber nur mit einem Git-Repo arbeiten, also werden die übersetzten Files in einem Unterverzeichnis von `hitobito-manual-de` gespeichert. Und immer wenn sich was ändert an den Übersetzungen, müssen diese Dateien ins Repo `hitobito-manual-fr` kopiert werden. Dann erstellt Readthedocs automatisch einen neuen Build. 

Den Schritt mit dem manuellen Kopieren könnte man wohl mit [COPYCAT](https://github.com/marketplace/actions/copycat-action) automatisieren. Ich hab das aber noch nicht hingekriegt.

Grosser Nachteil dieser Variante: Der Übersetzer wird nicht automatisch über Änderungen informiert (oder ich hab zumindest keine Option dafür gefunden).

Bin gespannt, ob ihr einen einfacheren/besseren Workflow findet 😄

**Comment by carlobeltrame** [comment]
@betsim Merci schon mal für die Inputs! Ohne mich jetzt stark da reinvertieft zu haben hoffe ich dass wir das manuelle Kopieren via Transifex lösen können.

**Comment by Michael-Schaer** [comment]
Merci fürs Abklären. Und danke @betsim für deine Erfahrungen! 

Was können wir hier vorgehen? Die italienischen Texte haben wir bereits vollständig im Transifex erfassen lassen. Es wäre schade, wenn wir diese nicht brauchen könnten.

**Comment by olibrian** [comment]
Readthedocs kann mit mehreren Sprachen im gleichen Repo umgehen. Siehe dazu: https://github.com/hitobito/user_documentation/issues/21

**Comment by Michael-Schaer** [comment]
So wie ich @betsim verstehe, müssten wir da einen kleinen Umzug machen:
- Text aus Transifex Backupen (insbesondere Italienisch)
- Repo richtig mehrsprachig einrichten
- Texte richtig importieren

@ThomasEllenberger Es pressiert nicht mega, aber können wir hier einen Zeithorizont definieren? 
Bei der Automatisierung würde vorerst vielleicht auch eine Benachrichtigung reichen. Aber wenn wir die jetzigen Inhalte dreisprachig hätten, wäre ich schon froh.

**Comment by kronn** [comment]
Nach dem, was ich gesehen habe, gibt es zwei Ansätze für mehrsprachige Dokumentationen.

Der Ansatz des SBV ist "mehrere Projekte mit je einer Sprache". 

Ich habe den Ansatz "mehrere Sprachen in einem Projekt" verfolgt, da dies schon durch die bestehende transifex-integration vorbereitet war. Ich habe einen Pull-Request erstellt, der dies weiter treibt. Die vorhandenen italienischen Übersetzungen im transifex habe ich zusammengefasst und neu strukturiert. 

Ich habe die Vorabversion mal (versteckt, aber aktiv) erzeugen lassen, um die Integration zu verifizieren: https://hitobito.readthedocs.io/it/translated-documentation/roles.html. Durch die Aktualisierung der Quellen ist aktuell leider nicht alles italienisch, aber der Weg ist schonmal vorgezeichnet.
