### ISSUE TITLE
Allgemein: Implementation von Jemalloc für Hitobito

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#1895]
Bei anderen Applikationen konnte durch die Einführung von Jemalloc massiv Leistung eingespart werden.

Gerne würden wir Jemalloc auch für Hitobito nutzen.
Durch dieses Issue soll eine Mögliche Einführung von Jemalloc für Hitobito konzipiert werden.

### Infos von Robin:

Wir müssen folgende zwei Zeilen an der richtigen Stelle im richtigen Dockerfile einbauen:
`ARG RUN_PACKAGES="libjemalloc-dev libjemalloc2"` (packages in die Liste einfügen, damit sie später installiert werden)
`ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2` (das müsste ein drop-in replacement für das normale malloc sein)

Mehr Infos:
* https://www.speedshop.co/2017/12/04/malloc-doubles-ruby-memory.html -> Der wohl beste generelle Memory Usage Artikel
* https://andresakata.medium.com/benchmark-of-memory-allocators-on-a-multi-threaded-ruby-program-354ec4dc2e7e -> Benchmarking (in anderen Puzzle-Projekten wurden nicht gleich hohe Performance Unterschiede beobachtet und sie können von Projekt zu Projekt extrem unterschiedlich sein)
* https://engineering.binti.com/jemalloc-with-ruby-and-docker/ -> Jemandem sein Prozess beim ersetzen
* https://www.reddit.com/r/ruby/comments/dnt7pm/downsides_to_using_jemalloc/ -> Diskussion über die Downsides (TLDR: some CPU cycles and not easy to use on Alpine Images)

Es wird bereits in mehreren Puzzle-Applikationen eingesetzt, für Rails und für DelayedJob. Eine davon braucht anstatt 8Gb Ram einfach nur noch 1.2Gb im Schnitt (oder in einem anderen Projekt die Hälfte des Ram). Die 95% percentile sind genau gleich wie vorher und vom "Look-and-Feel" wurde bisher kein Unterschied bemerkbar.

### ToDo

- [ ] Issue für Umsetzung erstellen
- [ ] Workflow des Features beschreiben
- [ ] ggf. Mockup erstellen
- [ ] Tech-Spec ergänzen
- [ ] ToDo für Umsetzung definieren

**Comment by TheWalkingLeek** [comment]
Habe es versucht in unser aktuelles Dockerfile aufzunehmen. War nicht so leicht wie gedacht, da bei den bisherigen Applikationen das Ruby Base Image verwendet wurde und wir bei Hitobito noch ein centos S2I haben.
Da wir sowieso auf dem Weg zu besagtem Base Image sind, habe ich ein Issue für dieses gemacht und Jemalloc dort als ToDo eingefügt: https://github.com/hitobito/hitobito/issues/1914
