### ISSUE TITLE
PEOPLE: Verfügbare Abos

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito#1899]
Kann mir jemand erklären, welche Abos ich im Tab "Abos" unter dem Title "Verfügbare Abos" sehe? Mir erschliesst sich nicht, welche Abos dort erscheinen und welche nicht.

![Bildschirm­foto 2022-11-01 um 16 44 20](https://user-images.githubusercontent.com/1453303/199275750-13d52dbd-15b6-460a-9475-79a65ea31b6b.png)

**Comment by carlobeltrame** [comment]
Es sind alle Abos die das Häkchen "Abonnenten dürfen sich selbst an-/abmelden" aktiviert haben, und bei denen du noch nicht abonniert bist.

**Comment by betsim** [comment]
Danke für die Klarstellung.
