### ISSUE TITLE
Allgemein bessere Filtermöglichkeit auf Personenlisten und Abos

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#19]
Aktuell sind die beiden Möglichkeiten zu Filter unterschiedlich bei Personen und bei Abos, in beiden Fällen decken sie nicht alles gewünschte ab, weiter sollten sie flexibel erweiterbar sein und auch das Filtern nach Attributen erlauben (z. B. für verschiedensprachige Versände oder Differenzierung nach Alter).

Vorschläge hierzu sind sehr willkommen.

**Comment by jesuistouriste** [comment]
In unserem Fall möchte der Nutzer für das Zusammenstellen von Abos gewisse Filter auf Attribute anwenden:
- Geschlecht
- Alter
- Sprache

Ähnlich der Auswahl von Rollen / Gruppen sollte er einen Konfigurationsbaum mit den verschiedenen Attributen haben. Die Personenliste würde dann additiv zuerst in Bezug auf die Rollen zusammengestellt und danach nach diesen Attributen mit gefiltert.

**Comment by RolandStuder** [comment]
@jesuistouriste Seid ihr koordiniert mit uns. Wir arbeiten auch an einem Filter für ein spezifisches berechnetes Attribute siehe #600

**Comment by RolandStuder** [comment]
Ist teilweise umgesetzt in https://github.com/hitobito/hitobito/commit/c8e67e9d5faf17266a4e3d2d10ec194cb1980482, es kann nach Textfilter gefiltert werden. Booleans und Datumsfelder fehlen aber noch.

@jesuistouriste Habt ihr da etwas in GLP Wagon dazu umgesetzt?
