### ISSUE TITLE
Feld für Geldgeber (wer hat wann wie viel bezahlt) (4h)

### ISSUE THREAD

**Issue by jharari** [hitobito/hitobito#190]
Einfaches Attribut mit Textarea auf Personen

### Erhaltene finanzielle Unterstützung

* **Label**: "Finanzielle Unterstützung"
* **Darstellung**: Mehrzeiliges Textfeld
* **Validierungsregeln**: keine
* **Besonderheiten**: keine
* **Wo Berücksichtigen?:**
  * CSV Adressliste: Nein
  * CSV Export _Alle Angaben_: Ja
  * CSV Export bei Abos: Ja
  * JSON API Index: Nein
  * JSON API Person Detail: Ja
  * Auffindbarkeit in Volltextsuche: Nein

**Comment by RolandStuder** [comment]
@jharari Ist das auf Gruppen oder Personen anzugeben? Oder sogar spezifisch nur für die JUPAs?

**Comment by jharari** [comment]
Nein, nicht nur für JUPAs. 
Ist auf Personen anzugeben.

**Comment by RolandStuder** [comment]
@jharari 
- Bitte überprüfen, ob meine Vorschlag Sinn macht, wo das Attribut ausgegeben wird und wo nicht
- Wie soll das Label zum Attribut heissen?

**Comment by codez** [comment]
Schätzung: 0.5PT

**Comment by jharari** [comment]
CSV Export bei Abos: Ja
Label: "Finanzielle Unterstützung"

**Comment by RolandStuder** [comment]
@jharari Der Export bei der Adressliste und auf dem Abo ist derselbe. 

Braucht ihr das Attribut Finanzieller Support wirklich beim Abo Export? 

Dann wäre es einfach auch im normalen Adressexport verfügbar.

Also willst du das Attribut sowohl beim Aboexport als auch beim Adressexport dabei haben, oder bei keinem der Beiden? (Wichtig, somit könnten Leute mit :contact_data Zugriff dieses Feld exportieren).

**Comment by RolandStuder** [comment]
@jharari bitte Abnehmen, du kannst es ausprobieren auf: http://dsj.puzzle.ch

Wenn alles OK ist: Bemerkung "OK, abgenommen" hinterlegen.
Wenn nicht OK, Bemerkung "Nicht OK: " und was inkorrekt ist.

**Comment by jharari** [comment]
Ok, abgenommen.
