### ISSUE TITLE
DEMO: Zusätzliche Rolle Kassier*in für Admin

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#1911]
Wenn sich jemand auf demo.hitobito.com als Administrator einloggt, möchte er sämtliche Funktionen von Hitobito sehen und ausprobieren können. Zum aktuellen Zeitpunkt sind sämtliche Rechnungsfeatures nicht ersichtlich, da der Admin Account nirgends eine Kassier*in Rolle hat.

Neu soll der User mit der Mailadresse admin@hitobito.ch auf der demo.hitobito.com Umgebung auch die Rolle Kassier*in in der Gruppe Dachverband / Geschäftsstelle bekommen. Dies soll so implementiert werden, dass die Rolle wenn die Umgebung in der Nacht resettet wird bestehen bleibt.

# Mockup

![image](https://user-images.githubusercontent.com/100761305/201293031-d8cd440e-1732-4069-91da-13a99576f8fe.png)

# Tech-Spec

- Alle Funktionen von hitobito sollen demonstriert werden

# ToDo

- [x] Rolle vergeben
- [ ] Demo releasen
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by kronn** [comment]
Siehe https://github.com/hitobito/hitobito_generic/commit/a8f02a29e94d6b78aec621bc7e6daf9014502013
