### ISSUE TITLE
KURSE: Darstellung Aufnahmebedingungen via Kurs 

### ISSUE THREAD

**Issue by tschuepbach** [hitobito/hitobito#1931]
### Aktuelles Verhalten

Unter Einstellungen -> Kursarten können die Aufnahmebedingungen pro Kursart hinterleget werden. Diese erscheinen anschliessend automatisch auf den entsprechenden Kurs-Übersichtsseiten.

Werden zusätzlich via Kurs Aufnahmebedingungen definiert, werden diese bei den vordefinierten Bedingungen, nahtlos hinten angehängt.

Beispiele:
![image](https://user-images.githubusercontent.com/40494600/204994682-d69592cc-4669-42e3-b0dc-ea54c0095060.png)

![image](https://user-images.githubusercontent.com/40494600/204994733-deaf3279-fc75-4a99-bd3d-db9195033d7a.png)

Damit die zusätzlichen Aufnahmebedingungen via Kurs "richtig" dargestellt werden, muss vor den Bedingungen ein Absatz eingefügt werden.

Beispiele:
<img width="554" alt="image" src="https://user-images.githubusercontent.com/40494600/204994953-53488c5c-0301-4fb5-b2b1-69b341076674.png">

<img width="279" alt="image" src="https://user-images.githubusercontent.com/40494600/204995083-213dcfee-6497-45ee-9912-df157ca69602.png">

see [#cevi101 (comment)](https://github.com/cevi/hitobito_cevi/issues/101#issuecomment-1169713120)

### Gewünschtes Verhalten

Die zusätzlichen, via Kurs hinzugefügten Aufnahmebedingungen werden auf der Kurs-Übersichtsseite korrekt dargestellt.

Dass die vordefinierten Aufnahmebedingungen via Kurs nicht reduziert resp. angepasst, sondern nur ergänzt werden können, finden wir richtig.

Hängt allenfalls mit hitobito/hitobito#1763 zusammen

### Schritte zu reproduzieren

1. Aufnahmebedingen auf Kursart definieren
2. Kurs erstellen, entsprechende Kursart auswählen
3. Auf Kurs, zusätzliche Aufnahmebedingungen definieren (ohne Absatz in erster Zeile) 

see https://cevi.puzzle.ch/groups/6/events/1161

### Wann ist der Fehler aufgetreten?

01.12.2022

### hitobito version

1.28.32

### Organisation

Cevi

**Comment by njaeggi** [comment]
This issue is getting fixed in https://github.com/hitobito/hitobito/issues/2360
