### ISSUE TITLE
NDS-Kurs Export - Leitungsteam

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1937]
Uns ist aufgefallen, dass der NDS-Export für Kurse alle Personen beinhaltet (Leitungsteam und Teilnehmende). Tatsächlich brauchen wir für den Import aber immer nur die Teilnehmenden ohne Leitungsteam. Zusätzlich ist es nur telefonisch möglich, die Leitungspersonen in der NDS wieder zu löschen wenn sie mal drin sind. Deshalb ist es ein Problem, wenn im Export standardmässig alle Personen enthalten sind.

Wir würden uns deshalb dafür aussprechen, beim NDS-Kurs-Export nur noch die Teilnehmenden zu exportieren, egal welche Ebene oben angewählt ist.

![grafik](https://user-images.githubusercontent.com/1799621/205931584-3047fa87-05bc-49f5-8bae-d1b40e2b9903.png)

Achtung, dies gilt nur für den NDS-Kurs Export, nicht jedoch für den NDS-Lager Export.

@nchiapol @richardjubla Wie ist das bei euch?

https://github.com/hitobito/hitobito/issues/1733

**Comment by tschuepbach** [comment]
Antwort Cevi

Vielen Dank fürs erfassen. Dein Vorschlag macht Sinn. Aktuell (und wohl auch in naher Zukunft) besteht auf der NDS beim Kurskader keine Option für einen Import zur Verfügung. Diese müssen sowieso manuell hinzugefügt resp. erfasst werden. Sollte dies mal geändert werden, können wir den Export für Leitende ja entsprechend anpassen.

**Comment by richardjubla** [comment]
> @nchiapol @richardjubla Wie ist das bei euch?
> #1733

Kann ich aktuell nicht beantworten, habe aber die Frage intern weitergereicht. 
(Antwort Mitte Januar)

**Comment by richardjubla** [comment]
@Michael-Schaer 
Rückfrage: Die Ansicht wie auch der Export kann auf "Alle", "Leitungsteam", "Teilnehmende" eingestellt und auch entsprechend exportiert werden. (Ein kurzer Test auf der Testdb war erfolgreich)

Müsste einfach der Export NUR für Teilnehmende freigegeben werden?

**Comment by Michael-Schaer** [comment]
@richardjubla Den Export normalerweise zu verstecken und nur anzuzeigen, wenn oben Teilnehmende ausgewählt ist, wäre m.E. recht verwirrlich.

Deshalb der Vorschlag, in jedem Fall nur die TN zu exportieren, egal was oben gewählt ist.

**Comment by richardjubla** [comment]
> @richardjubla Den Export normalerweise zu verstecken und nur anzuzeigen, wenn oben Teilnehmende ausgewählt ist, wäre m.E. recht verwirrlich.
> 
> Deshalb der Vorschlag, in jedem Fall nur die TN zu exportieren, egal was oben gewählt ist.

Aus unserer Sicht ist das Verhalten "logisch", wenn die Auswahl ( "Alle", "Leitungsteam", "Teilnehmende") **immer** auch den Export direkt beeinflusst. Für die NDS muss halt (weil so benötigt) die Spalte Teilnehmende ausgewählt werden. 
Meine Frage bezog sich auf die Möglichkeit, den NDS Export für die Ansicht "All" gar nicht anzubieten, damit er nicht versehentlich gemacht wird.

**Comment by Michael-Schaer** [comment]
> Aus unserer Sicht ist das Verhalten "logisch", wenn die Auswahl ( "Alle", "Leitungsteam", "Teilnehmende") **immer** auch den Export direkt beeinflusst. Für die NDS muss halt (weil so benötigt) die Spalte Teilnehmende ausgewählt werden. Meine Frage bezog sich auf die Möglichkeit, den NDS Export für die Ansicht "All" gar nicht anzubieten, damit er nicht versehentlich gemacht wird.

Ich verstehe deine Sichtweise auch, dass die Auswahl oben auch den Export beeinflussen soll. Meine Sorge ist halt, dass die Einstellung "Alle" zugleich die Standardansicht ist. Das führt dazu, dass der Export Standardmässig die falschen Daten liefert.

Ich wage darum noch einen weiteren Vorschlag:

Wenn die Option "Alle" ausgewählt ist und der NDS-Kurs-Export gestartet wird, so erscheint ein Alert:

`Möchtest du wirklich alle Personen inkl. dem Leitungsteam exportieren? Sonst wechsle oben auf Teilnehmer*innen und starte den Export erneut.`

Wie wäre es mit dieser Option?

**Comment by carlobeltrame** [comment]
Da kein Konsens erreicht werden konnte, wurde das in hitobito/hitobito_pbs#263 nur für die PBS umgesetzt:
![Screenshot from 2023-03-29 17-44-43](https://user-images.githubusercontent.com/7566995/228594126-bb4a2037-af57-415a-a6f6-54be47304d6c.png)

Falls der Cevi dies aktiv auch noch möchte, kann der Commit https://github.com/hitobito/hitobito_pbs/pull/263/commits/6ae6fae9ce6beca444d64154dc921390e73bafbd auch noch im Cevi-Wagon übernommen werden.

**Comment by tschuepbach** [comment]
@nchiapol 
Würde m. M. n. für uns auch Sinn machen. Der Export "NDS - Lager" müsste aber auch bei allen Kursen möglich sein, da Verbandskurse als Kurse erfasst sind, aber eigentlich J+S-Lager sind. Anlässe bräuchte generell nur den Export "NDS-Lager". Was meinst du?

**Comment by carlobeltrame** [comment]
Die Sichtbarkeit im Wagon anzupassen ist ebenfalls vorbereitet, dazu müsste die Unterscheidungslogik analog zu diesem PBS-Wagon-Commit im Cevi Wagon umgesetzt werden: https://github.com/hitobito/hitobito_pbs/commit/70d0cc67bc986eb1d5f1636bc12da5289b2c8ecf
