### ISSUE TITLE
EVENT: Hinzufügen von Teilnehmer auf einen ausgebuchten event

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1957]
### Aktuelles Verhalten

Auf einem Event welcher ausgebucht ist, können unabhängig davon weitere Teilnehmer hinzugefügt werden. Eine Anmelde ist korrekterweise nicht mehr möglich. Unter de/groups/1/events/3/participations können aber Teilnehmer nach wie vor hinzugefügt werden.

### Gewünschtes Verhalten

Teilnehmende sollen zu einem ausgebuchten Event nicht mehr hinzugefügt werden können. Andere Rollen (Referent, etc) sollen aber unabhängig vom Kontingent hinzugefügt werden.

### Schritte zu reproduzieren

1. Ausgebuchter Event aufrufen
2. Person via participations als Teilnehmer hinzufügen

### Screenshots, weiterer Kontext

Ist dies ein gewolltes Verhalten?

**Comment by nchiapol** [comment]
Aus meiner Sicht ist das kein Bug sondern ein gewünschtes Feature. Wie participations können nur die Verantwortlichen weitere Teilnehmer hinzufügen - sie werden wissen, ob/für wen Ausnahmen möglich sind.

**Comment by olibrian** [comment]
closed by https://github.com/hitobito/hitobito/issues/1957#issuecomment-1357850859
