### ISSUE TITLE
E-Mail Verification: Verlorene Mailadresse kann nicht ersetzt werden

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito#1994]
### Aktuelles Verhalten

Eine Mutter wollte über die GS die Hauptemailadresse ihrer Tochter ändern, weil die aktuelle Adresse vom Anbieter gelöscht wurde.

Die Weder die GS noch ich als Admin des Dachverbands kann die Adresse ändern. Da die Änderung  noch bestätigt werden müsste. Für mich ist unklar an welche Adresse das Mail ging. Da Änderungen auf der Integration nicht bestätigt werden müssen, kann ich das auch nicht testen.

Ich nehme an die alte Adresse muss das bestätigen, da das als Sicherheitsfeature für OAuth gedacht war. Die alte Adresse existiert aber nicht mehr.

Wir konnten die Mail Adresse löschen - aber wenn wir danach eine neue eintragen muss diese ebenfalls wieder bestätigt werden. (Falls diese Bestätigung nun an die neue Adresse geht, würde das den Sicherheitsaspekt aushebeln.)

### Gewünschtes Verhalten

Noch zu definierende Rollen (Admins, Mitarbeiter der Geschäftsstelle, ...) müssen die Haupt-Mail mit sofortiger Wirkung ändern können.

### Schritte zu reproduzieren

1. Mit Account mit Mitarbeiter oder Admin Rolle einloggen
2. Haupt-Mail-Adresse einer Person ändern
3. Mail-Adresse sollte sofort ohne Bestätigung geändert werden.

### hitobito version

1.28.0

### Organisation

Cevi

**Comment by carlobeltrame** [comment]
Aus meiner Sicht funktioniert die Email Verification korrekt, du verwechselst aber wovor diese schützt.

Die Email Verification schützt Accounts nicht (oder nicht vordergründig, nicht gründlich) vor unberechtigten Änderungen an den Daten, und sie ist auch nicht dafür gedacht.
Die Email Verification schützt vor dem unberechtigten Eintragen einer Mailadresse welche ich nicht kontrolliere. Es ist also in gewisser Hinsicht ein Datenqualitäts-Thema, und nicht ein Berechtigungs-Thema.

Die Verifikations-E-Mail geht darum an die neu eingetragene Mailadresse. Bis der Link in dieser Mail angeklickt wird zählt weiterhin die alte Adresse. Auf der Integration funktioniert das genau gleich, aber man muss bedenken dass die Email-Verifikation nur bei Personen mit Login aktiv ist. Bei Personen ohne Login kann man beliebige Mailadressen eintragen, weil diese Personen quasi noch keine Accounts sind, sondern nur Datensätze. Beim Login erstellen geht in jedem Fall eine E-Mail an die Mailadresse (das Passwort-setzen-Mail), und so wird die Mailadresse dann verifiziert.

Die Email Verification ist für hitobito als OAuth Provider sehr wichtig, damit sich die Drittapplikationen, welche einen "Login via hitobito" anbieten, darauf verlassen können dass die Mailadresse des sich einloggenden Users authentisch ist. Eigentlich könnten sich solche Drittapplikationen auf die hitobito-ID verlassen, aber bei anderen OAuth Providern (konkret Google und Facebook) ist es sehr üblich, die Mailadresse als Identifikationsmerkmal für eine Person zu verwenden, und diese Services garantieren auch dass die Mailadressen verifiziert sind. Darum haben wir bei hitobito mitgezogen und die Email Verification eingebaut.

Ein konkretes Angriffs-Szenario welches durch die Email Verification verhindert wird ist:
1. Eine Person A loggt sich via hitobito bei einem Drittservice ein
2. Der Drittservice merkt sich A anhand der Haupt-Mailadresse, wie das bei anderen OAuth Providern üblich ist und ermutigt wird, und weil der Drittservice so oder so Mails an ihre User senden muss
3. Eine Person X mit Schreibzugriff auf A bearbeitet A und löscht die Haupt-Mailadresse
4. Person X füllt bei sich selber (oder bei einem anderen Account dessen Passwort sie kennt) die ehemalige Haupt-Mailadresse von Person A ein. Dieser Schritt wird durch die aktuelle Email-Verifikation verhindert.
5. Person X verwendet beim Drittservice den "Login via hitobito" und kann nun den dortigen Account von Person A übernehmen.

Würden wir die jetztige Mail-Verifikation durch deinen Vorschlag ersetzen, wäre dieses Szenario eine neue (bzw. wieder eingeführte) Sicherheitslücke. Siehe auch #957 für weitere Details.

Hier gibt es also von mir aus gesehen nichts zu ändern, ausser ihr möchtet neu zusätzlich noch eine Verifikation-Mail auf die alte Mailadresse? Diese würde euch aber genau in dem Fall einer verlorenen Mailadresse ein Bein stellen, und dann würden solche Zusatzregeln àla "Admins oder andere hohe Rollen könnens aber trotzdem ändern" überhaupt erst nötig werden.

**Comment by nchiapol** [comment]
Vielen Dank für die ausführliche Antwort und die Erläuterungen. In diesem Fall ist das aktuelle Verhalten tatsächlich bereits ok und es handelt sich mehr um ein UI und Dokumentationsproblem.

Könnte die Meldung "Die geänderte E-Mail-Adresse muss noch bestätigt werden, bevor sie aktiv wird." um "Der Bestätigungslink wurden an %{email} gesendet." ergänzt werden? Das hätte unsere Verwirrung verhindert. (Da das Variablen enthält und ich aktuell kein Test-Setup habe, traue ich mir den entsprechenden Pull-Request nicht zu.)

Einen Vorschlag für die aktualisierte Dokumentation folgt im entsprechenden Repo.

**Comment by carlobeltrame** [comment]
Gute Idee, merci. Siehe #1995. Besser so?
![Screenshot 2023-01-24 at 21-22-07 cevi db - Tony Bozsik _ Necessitatibus](https://user-images.githubusercontent.com/7566995/214401415-837dcfd4-d685-4245-a064-41cb2093f40f.png)

**Comment by nchiapol** [comment]
Perfekt. Danke!
