### ISSUE TITLE
Mailtrap: Account ist deaktiviert

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito#2031]
### Aktuelles Verhalten

![screenshot_2023-03-08_235857](https://user-images.githubusercontent.com/1123483/223870593-80a21c56-51b8-410d-b021-e326e8885d64.png)

Damit können keine Mails der Integration mehr getestet werden.

### Gewünschtes Verhalten

Eine funktionierende Mailbox für die Integration ;-)

### Schritte zu reproduzieren

Login bei Mailtrap.

### Wann ist der Fehler aufgetreten?

2023-03-08

**Comment by olibrian** [comment]
Mailtrap läuft wieder. Kredikarteninformation aktualisiert.
