### ISSUE TITLE
CSV-Exporte: Änderung von  ISO-8859-1 auf UTF-8

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#2035]
Da für einzelne Drittapplikationen bereits heute UTF-8 als CSV-Format vorausgesetzt wird, wollen wir sämtliche CSV-Exporte aus Hitobito auf das neue Format UTF-8 ändern.
Mit den bestehenden Kunden wurde abgeklärt, dass das alte Format, ISO-8859-1 nirgends spezifisch verwendet wird. Dieses muss nach der Mutation also nicht mehr zur Verfügung stehen.

Diese Umstellung wurde im PBS- und im Cevi-Wagon bereits gemacht, diese Wagon spezifischen Änderungen werden nicht mehr benötigt, wenn dies allgemein geändert wurde.

PBS: https://github.com/hitobito/hitobito_pbs/pull/250 / https://github.com/hitobito/hitobito/pull/1993
Cevi: https://github.com/hitobito/hitobito_cevi/issues/108

# Tech-Spec

- sinngebende Zielrichtung
- besondere/bekannte Bedingungen und Grenzfälle
- technische Einschränkungen
- Ein- und Ausgabeformate beschreiben
- Umsetzungsplan ergänzen oder anpassen

# ToDo

- [x] Settings anpassen wie im PBS Wagon [bereits gemacht](https://github.com/hitobito/hitobito_pbs/pull/250/files)
- [x] Im Core und in allen Wagons, wo die Specs "csv" [erwähnen](https://github.com/search?q=org%3Ahitobito+csv+path%3A%2F%5Espec%5C%2F%2F+NOT+repo%3Ahitobito%2Fhitobito_pbs+NOT+repo%3Ahitobito%2Fhitobito_cevi+language%3ARuby&type=code&l=Ruby), die Specs laufen lassen und ggf. fixen, wie im Cevi Wagon [bereits gemacht](https://github.com/hitobito/hitobito_cevi/commit/88ca59cee6f9763ef26fa6af07fdc4e64990e7fb)

**Comment by richardjubla** [comment]
Diese Anpassung wird auch (und initial) für die Behebung von #1733 benötigt. (Ein Auftrag der @jubla-ch )

**Comment by carlobeltrame** [comment]
Wurde im Core umgesetzt.
