### ISSUE TITLE
SUCHE: Auto-Completion in Suchfeld mit "/" gibt <i> zurück

### ISSUE THREAD

**Issue by maede97** [hitobito/hitobito#2060]
### Aktuelles Verhalten

Wird im Suchfeld der Name der Person mit Cevi- (oder Pfadi-) Namen gesucht (d.h. inklusive "/"), dann werden die Suchvorschläge falsch angezeigt.

### Gewünschtes Verhalten

Das Dropdown mit den Auto-Completion-Entries wird korrekt angezeigt.

### Schritte zu reproduzieren

1. Nach dem Login seinen eigenen Namen kopieren (inklusive "/", im Bild also "TEST-Matthias TEST / Scirocco"
2. Diesen Text im Suchfeld eingeben.
3. Die Suche zeigt nun alle Items mit "</i>" als Prefix an.

Es kann auch ein beliebiger Suchbegriff mit "/" eingegeben werden (auch dann tritt der Fehler auf).

### Wann ist der Fehler aufgetreten?

29.03.2023, Chrome-Browser und Firefox-Browser

### hitobito version

1.28.63

### Organisation

Cevi

### Screenshots, weiterer Kontext

![hito_bug](https://user-images.githubusercontent.com/14098502/228624248-1b716bc2-7b95-47cb-8bde-3c4e453667fd.png)

Danke @wp99cp fürs finden & mir weitermelden. :-)

**Comment by betsim** [comment]
Passiert auch bei der Eingabe von z.B. "la":

<img width="1460" alt="Bildschirmfoto 2023-06-22 um 07 37 45" src="https://github.com/hitobito/hitobito/assets/1453303/6778a4bf-e44d-4def-b557-964c53fbdc1f">

**Comment by richardjubla** [comment]
Kann ich bestätigen, sowohl auf 1.28 wie auch 1.30
![image](https://github.com/hitobito/hitobito/assets/95908537/536494df-d01e-4343-a725-369c7bd09063)

**Comment by ThomasEllenberger** [comment]
Kann den Bug bestätigen, passiert auch wenn ein "&" im Namen vorkommt.

**Comment by betsim** [comment]
*nach-oben-schieb* 

Dieser Bug macht die Arbeit in Hitobito wirklich mühsam, wie in diesem Screenshot ersichtlich:
<img width="1466" alt="Bildschirmfoto 2023-10-12 um 15 55 31" src="https://github.com/hitobito/hitobito/assets/1453303/c689118c-1cdb-432d-b70b-0761ad038388">
