### ISSUE TITLE
AUTH: 2FA verhindert "Remember Me" funktion bei mehreren Geräten

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#2068]
### Aktuelles Verhalten

Wenn 2FA aktiviert ist, funktioniert die "Remember Me" Funktion von devise nicht mit mehreren Geräten. Nur dasjenige Gerät, auf dem als letztes das Login getätigt wurde, erinnert sich an die Session.

![grafik](https://user-images.githubusercontent.com/1799621/229741399-66891d2e-f2c2-494e-8e94-34bfa17e8831.png)
__

### Gewünschtes Verhalten

Wenn beim Login "Remember Me" ausgewählt wird, verhält sich die Session unabhängig vom Login auf anderen Geräten. So muss bei häufigem Gerätewechsel nicht jedes mal der TOPT-Code eingegeben werden.

### Schritte zu reproduzieren

- 2FA / TOPT aktivieren
- Gerät A: Einloggen mit "Remember Me"
- Gerät B: Einloggen mit "Remember Me"

→ Es sind beide Geräte eingeloggt und können gleichzeitig auf die MiData zugreifen.

- Gerät A: Browserfenster schliessen
- Gerät A: Neues Browserfenster öffnen

→ Gerät A muss sich neu einloggen, "Remember Me" hat nicht funktioniert

### Wann ist der Fehler aufgetreten?

04.04.2023

### hitobito version

1.28.64

### Organisation

PBS/MiData

### Screenshots, weiterer Kontext

Wenn 2FA deaktiviert ist, funktioniert "Remember Me" auch mit zwei Geräten. Es gibt also einen Zusammenhang mit 2FA.

Altes Issue zu "Remember me", wurde gefixt, hier sehe ich allerdings noch keinen Zusammenhang zu 2FA:
https://github.com/heartcombo/devise/issues/3950

Verwendetet Browser:
- Gerät A: Firefox, Windows
- Gerät B: Chrome, Android

### ToDos

- [ ] Bug gemäss Videos in [Kommentar](https://github.com/hitobito/hitobito/issues/2068#issuecomment-1609299783) nachstellen und Devise bzw. unsere 2FA-Implementation debuggen

**Comment by TheWalkingLeek** [comment]
Ich konnte das so nicht nachstellen.. Habs direkt auf der aktuellen Integrationsumgebung (https://github.com/hitobito/ose_composition_pbs/tree/582fed2ae507b754859295f3fd830f5f5e724cb6) getestet
Gerät A: Firefox  (113.0.1) & Google Chrome (114.0.5735.106), Linux
Gerät B: Google Chrome (114.0.5735.130), Android

Vielleicht willst du das noch testen? @ThomasEllenberger
Besteht das Problem bei dir noch? @Michael-Schaer

**Comment by Michael-Schaer** [comment]
Hallo Nils, ich schicke dir ein Video zur Erklärung.

**Comment by carlobeltrame** [comment]
Das Problem besteht weiterhin, habs gerade getestet auf PBS Integration und Produktion. Zur Präzisierung bei den Anweisungen zum Reproduzieren: Statt "Gerät A Browserfenster schliessen und neu öffnen" würde ich empfehlen in den Dev Tools nur das Session Cookie zu löschen. Damit kannst du das Ablaufen des 30minütigen Session Cookies zuverlässiger simulieren als mit einem Browserneustart.

Video für User mit 2FA:

https://github.com/hitobito/hitobito/assets/7566995/b8e4a73f-d564-4f81-b906-3a397ce1de2a

Links Firefox, rechts Chromium. Im letzten Fenster wo man sich mit Remember Me und 2FA eingeloggt hat funktioniert das Remember Me, in allen anderen Fenstern ist das Remember Me Token ungültig und man kommt nach Ablauf des Session Cookies auf die Login-Seite.

Video für User ohne 2FA:

https://github.com/hitobito/hitobito/assets/7566995/1b62bd94-d0e9-4edc-aa5a-1283877a6714

Alles genau gleich, ausser dass man sich mit einem User ohne 2FA einloggt. Remember Me funktioniert auch in mehreren Browsern / Geräten gleichzeitig.

**Comment by tschuepbach** [comment]
Ist hier eine Lösung in Sicht? Dies erschwert die Arbeit mit der DB enorm, echt mühsam.

**Comment by ThomasEllenberger** [comment]
> Ist hier eine Lösung in Sicht? Dies erschwert die Arbeit mit der DB enorm, echt mühsam.

Dieses Issue ist in unserem Backlog und die Behebung ist bis Ende Jahr geplant.
Der Fix sollte also mit dem nächsten Release im Januar verfügbar sein.
