### ISSUE TITLE
Die API verwendet einen veralteten json:api Standard.

### ISSUE THREAD

**Issue by georgschoelly** [hitobito/hitobito#207]
### Hintergrund

Die API wurde am 9. Juli 2014 auf die `Oat` Bibliothek umgestellt (eeb83f713c4f5a6ad00453246acb8b2e1e8ee33d). Damals war der Standard noch nicht stabil und hat sich seither verändert.

### Weshalb ist das ein Problem?

Für json:api gibt es [ganz viele Client Libraries](http://jsonapi.org/implementations/), die die Arbeit mit der API vereinfachen. Weil Hitobito diesen Standard aber nicht korrekt umsetzt, können diese Libraries nicht verwendet werden.

### Können wir Oat updaten?

Oat scheint sich leider nicht, oder nur ganz langsam, [in Richtung Standard zu bewegen.](https://github.com/ismasan/oat/issues/40)

### Alternativen

Liste hier: http://jsonapi.org/implementations/#server-libraries-ruby

Mit rails kompatibel scheinen zu sein:

 * https://github.com/tiagopog/jsonapi-utils
 * https://github.com/doga/jsonapi_for_rails
 * https://github.com/tiagopog/jsonapi-utils
 * http://jsonapi-rb.org/guides/serialization/defining.html

**Comment by RolandStuder** [comment]
Ok, danke für die Ausführungen. Schauen wir mal in Ruhe an. Müssen sicherstellen, dass möglichst alle informiert sind, welche die API benutzen.

**Comment by RolandStuder** [comment]
Ein update wäre einfach, aber wir müssten die Schnittstelle versionieren, damit die bisherigen Anbindungen nicht kaputt gehen. Keine Aktivität mehr auf diesem Issue, schliesse es deshalb.
