### ISSUE TITLE
Anlässe: Anmeldemails werden nicht korrekt versendet

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#2083]
### Aktuelles Verhalten

Aktuell werden Anlass-Anmeldemails nicht mehr korrekt versendet.
Getestet auf der Integrationsumgebung von Die Mitte.

Meldet sich eine Person an einen Anlass an (Oder wird durch jemand anderes einem Anlass hinzugefügt) wird kein Email mehr versendet. Dies konnte auf der integrationsumgebung von Die Mitte nachgestellt werden. 

Einige Mails welche ich getestet habe, die weiterhin versendet werden:
- Übernahme eines Accounts
- Kurseinladungen
- Rechnungen
- Abos

### Gewünschtes Verhalten

Meldet sich eine Person an einen Anlass an oder wird diesem hinzugefügt, wird korrekt ein Email an die Emailadresse dieser Person versendet.

### Schritte zu reproduzieren

1. Person an Anlass anmelden
2. Warten...

### Wann ist der Fehler aufgetreten?

19.04.2023

### hitobito version

1.28.54

### Organisation

Die Mitte

**Comment by nchiapol** [comment]
@ThomasEllenberger @olibrian 
Ich habe eben versucht das auch bei uns nachzustellen. 

Folgende Mails habe ich getestet:
  * Anlass: Person meldet sich selbst  an: Mail fehlt
  * Anlass: Person wird durch Admin angemelet: Kein Mail - so gewünscht vgl. unten
  * Kurs (manuelle zuteilung): TN meldet sich selbst an: Mail "Voranmeldung eingegangen" funktioniert  
  * Kurs (manuelle zuteilung): Anmeldung wird durch Admin von links nach rechts geschoben: Mail "Voranmeldung eingegangen" funktioniert  
  * Kurs (manuelle zuteilung): Anmeldung wird durch Admin von rechts nach links geschoben: Mail "Bestätigung der Anmeldung"  funktioniert
  * Person wird imitiert: Mail fehlt

Beim Korrigieren dieses Bugs muss unbedingt darauf geachtet werden, dass auch die Mails bei den Kursen weiterhin korrekt funktionieren und möglichst keine Unnötigen Mails versendet werden. 

Insbesondere ist bei uns aktuell gewünscht, dass beim Anmelden durch einen Admin mindestens bei Kursen kein Mail ausgelöst wird. (vgl.  https://github.com/cevi/hitobito_cevi/issues/172 und https://github.com/hitobito/hitobito_cevi/issues/104).

**Comment by ThomasEllenberger** [comment]
Person wird immitiert: 
Habe ich erneut getestet, bei Die Mitte, Jubla und PBS. Dies funktioniert bei all diesen Umgebungen noch korrekt.
Getestet bei Cevi: Kein Mail erhalten. Scheint ein Problem spezifisch bei der Cevi zu sein. Erstaunlicherweise hat es auch bei der Cevi am 18.04.2023 noch funktioniert...

**Comment by ThomasEllenberger** [comment]
>    Anlass: Person wird durch Admin angemeldet: Kein Mail - so gewünscht vgl. unten
> 
> Insbesondere ist bei uns aktuell gewünscht, dass beim Anmelden durch einen Admin mindestens bei Kursen kein Mail ausgelöst wird. (vgl. [cevi/hitobito_cevi#172](https://github.com/cevi/hitobito_cevi/issues/172) und [hitobito/hitobito_cevi#104](https://github.com/hitobito/hitobito_cevi/issues/104)).

@olibrian : Abklären ob dies bei Die Mitte und anderen Umgebungen auch so gewünscht ist? (Die Mitte hat keine Kurse, sondern nur Anlässe.) @nchiapol : Im Zweifelsfalle ok, wenn diese bei euch bei Anlässen versendet werden, oder ist es bei euch auch bei Anlässen nicht gewünscht?

**Comment by ThomasEllenberger** [comment]
Habe dies auf der Umgebung von der Mitte und Cevi getestet.
Die Mails für An- und Abmeldung an Anlässen funktionieren wieder.

@nchiapol: Willst du bei euch testen ob alles sonnst noch wie gewünscht funktioniert?
Damit dieser Bugfix bei euch live wird, müsste ein Release gemacht werden. Wenn das aktuell kein Problem ist, können wir bis zum ersten geplanten Release Anfang Juli warten, dann muss auch der Elternzugang fertig sein, sonnst müssten wir einen ausserordentlichen Release für euch planen.

**Comment by nchiapol** [comment]
@ThomasEllenberger 

* Mails scheinen noch korrekt zu funktionieren. 
* Betreffend Release: Das könnte in den nächsten Wochen schon noch einige Anlässe betreffen und mit dem Mailstack-fix und den ersten Hackaton-Verbesserungen wären das ja dann doch schon einige Gründe. Falls kein grosses Problem mit unfertigen Änderungen besteht, können wir also gerne bei der nächsten Gelegenheit releasen.
* Zudem noch ein Update zum Mail beim imitieren: Das hängt bei uns scheinbar vom User ab. (bzw. wahrscheinlich vom alter der Erfassten Mailadresse. Kann es sein, dass auf der Integration etwas mit der Mail-Kontrolle diese Nachricht verhindert?)

**Comment by nchiapol** [comment]
@ThomasEllenberger 

Auch wenn das nicht direkt mit diesem Issue zu tun hat, doch noch ein Nachtrag.
Ich glaube, ich habe das Problem mit den fehlenden Mails beim imitieren lokalisiert: Die Mails werden nur versendet, wenn der imitierte User bereits ein Passwort gesetzt hat:
``` 
# app/controllers/person/impersonation_controller.rb:21
if person.password? && person.email? && Settings.impersonate.notify
```
Das sollten wir für die Zukunft im Kopf behalten um uns nicht mehr selbst zu verwirren. ;-)
