### ISSUE TITLE
SEARCH: Performance optimieren

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito#2092]
Die Personensuche dauert je nachdem wieviele/welche Rollen ein user hat sehr lange. Bug wurde in 
https://github.com/hitobito/hitobito/issues/2056 reported.

Bei der Mitte führt das immer wieder zu timeouts. Als Sofortmassnahme wurde mit #2056 das timeout erhöht.
Für eine nachhaltige Lösung muss aber das permission handling, insbesondere das Eruieren der sichtbaren Personen bezogen auf einen user, optimiert werden.

Im request log sehe ich viele DB Abfragen mit welchen die für den user sichtbaren Personen evaluiert. Deren ids werden gebraucht, um die Sphinx Abfrage auf die Sichtbaren Personen einzuschränken. Die Mehrheit der Abfragen werden hier ausgelöst:
* Group::NestedSet#layer_hierarchy
* EventAbility#if_layer_and_below_full_on_root
* SearchStrategies::Base#load_deleted_people_ids

Weitere mögliche Thesen:
- Prüfen, ob auch Rollen ohne eine Berechtigung für die Abfrage beigezogen werden. Oft hat eine Person mehrere Rollen und dabei sind einige nur informativ oder für ein Abo relevant.
- Als Hypothese steht im Raum, dass bei Personen welche Rechnungszugriff haben auftaucht. Sphinx durchsucht auch sämtliche Rechnungen. Daher ist hier der Scope sehr gross.
- Werden auch gelöschte Rollen für die Berechnung beigezogen?
- Fehlende Indexes (https://github.com/hitobito/hitobito/issues/2092#issuecomment-1526109863)

Mögliche Schritte:
* DB Dump von der Kunde lokal einspielen und das Problem nachstellen
* Bei der Gelegenheit am besten auch noch https://github.com/MiniProfiler/rack-mini-profiler ins Projekt integrieren

# ToDo

- [ ] Issue für Umsetzung erstellen
- [ ] Workflow des Features beschreiben
- [ ] ggf. Mockup erstellen
- [ ] Tech-Spec ergänzen
- [ ] ToDo für Umsetzung definieren

**Comment by patrickuhlmann** [comment]
ev. dumme Frage aber hat schon mal jemand angeschaut ob ev. einfach ein Index auf der Datenbank fehlt damit die Abfragen schnell ausgeführt werden können. Habe das einfach schon zu oft erlebt (einmal Index erstellen, DB-Query 100x schneller). Einfach bevor man da einen grösseren Umbau macht.

**Comment by TheWalkingLeek** [comment]
Andreas und ich haben da jetzt mal reingeschaut:
## Erkentnisse/Ideen 
- Wie im Ticket beschrieben macht `SearchStrategies::Base#load_accessible_deleted_people_ids` einen beachtlichen Teil der Load aus. In unserem lokalen Testen waren es rund 10 Sekunden
  - Dabei iterieren wir erst über alle `accessible_layers` für einen Ability check und holen für jeden relevanten Layer die DeletedPeople
  - Die `DeletedPeople#deleted_for` selbst ist dabei schon sehr komplex und baut für jeden Layer selbst ein SQL wo man sich fragen kann ob man nicht alle gleichzeitig absetzen kann?

## Konkrete Ansätze
- Das Berechnen von gelöschten Personen ist sehr teuer und machen wir immer wieder obwohl es sich selten pro Person ändert. Ein `last_active_role_id` Attribut auf der Person welches via Callbacks abgefüllt oder geleert wird würde diese Berechnung praktisch ablösen. Dies bedingt aber https://github.com/hitobito/hitobito/issues/1748
- In erster Linie `SearchStrategies::Base#load_accessible_deleted_people_ids` mit den aktuell gegebenen Mitteln aufräumen

**Comment by TheWalkingLeek** [comment]
https://github.com/hitobito/hitobito/pull/2134
https://github.com/hitobito/hitobito/pull/2138
