### ISSUE TITLE
KURSE: Abmeldung für Kurs nicht möglich, obwohl Teilnehmende sich selbst abmelden können

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito#2099]
### Aktuelles Verhalten

Wird in einem Kurs die Option "Teilnehmende können sich selbst abmelden" aktiviert, können sich die Teilnehmenden trotzdem nicht vom Kurs abmelden.

### Gewünschtes Verhalten

Mit der Option "Teilnehmende können sich selbst abmelden", sollen sich Teilnehmende auch von einem Kurs wider abmelden können. 

### Schritte zu reproduzieren

- Kurs mit Option "Teilnehmende können sich selbst abmelden" erstellen
- Kursanmeldung mit Account durchführen
- Account imitieren und Kursabmeldung versuchen
- Fehler: Account kann sich vom Kurs nicht abmelden

Achtung: Es gibt Accounts, in denen die Abmeldung für den Kurs möglich ist. Leider konnten wir diese Bedingungen nicht herausfinden.  

### Wann ist der Fehler aufgetreten?

02.05.2023

### hitobito version

1.28.68

### Organisation

Jubla

### Screenshots, weiterer Kontext

Test Kurs Petra : Teilnehmende können sich selbst abmelden.

![image](https://user-images.githubusercontent.com/95908537/235693669-0a5144da-1852-42ea-8951-e2a0bbf5cd6b.png)

Markus Kuhn meldet sich für den Kurs an:
![image](https://user-images.githubusercontent.com/95908537/235694275-e160906d-a5b2-4714-805e-19315b71172e.png)

Markus Kuhn ist auf der Warteliste
![image](https://user-images.githubusercontent.com/95908537/235694560-46585cb0-40d3-455d-abe5-d694e937dd82.png)

Die Kursadministration teilt Markus Kuhn dem Kurs zu, die E-Mail "Bestätigung der Anmeldung" wird verschickt
![image](https://user-images.githubusercontent.com/95908537/235696022-af7ee556-1c55-4add-9ef3-6eca937304c0.png)

**Bug: Der User Markus Kuhn sieht seine Anmeldung, kann sich aber für den Kurs nicht abmelden**
![image](https://user-images.githubusercontent.com/95908537/235698088-999ae304-cb2e-4cd2-b80e-f4dd3a9f6ea6.png)

**Comment by richardjubla** [comment]
@nchiapol zur Info, evtl. betrifft euch das auch.

**Comment by nchiapol** [comment]
@richardjubla Danke für den Hinweis. Ich habe bei uns eben keinen betroffenen Account gefunden. 

Ein Gedanken: 
Betrifft das nur Kurse oder auch Anlässe? Falls letzteres: Wir hatte während der Entwicklung unseres Voranmeldungsprozesses vorübergehend ähnliche Symptome. Anlass- und Kurs-Anmeldungen scheinen zwei verschiedene Dinge und wenn eine Anlass-Anmeldung in einem Kurs landet, kann sie nicht mehr gelöscht werden
(vgl. https://github.com/hitobito/hitobito_cevi/issues/79#issuecomment-1310905286). Das sollte aber eigentlich zurück gebaut worden sein.

**Comment by richardjubla** [comment]
> @richardjubla Danke für den Hinweis. Ich habe bei uns eben keinen betroffenen Account gefunden.
> 
> Ein Gedanken: Betrifft das nur Kurse oder auch Anlässe? Falls letzteres: Wir hatte während der Entwicklung unseres Voranmeldungsprozesses vorübergehend ähnliche Symptome. Anlass- und Kurs-Anmeldungen scheinen zwei verschiedene Dinge und wenn eine Anlass-Anmeldung in einem Kurs landet, kann sie nicht mehr gelöscht werden (vgl. [hitobito/hitobito_cevi#79 (comment)](https://github.com/hitobito/hitobito_cevi/issues/79#issuecomment-1310905286)). Das sollte aber eigentlich zurück gebaut worden sein.

Aus meiner Sicht betrifft das nur Kurse. Bei Anlässen konnte ich auf unserer Testumgebung eine An- und Abmeldung durchführen.

**Comment by richardjubla** [comment]
Der Bug besteht in [Version 2.0.0](https://db.jubla.ch/changelog) nicht mehr:  Die Option "Teilnehmende können sich selbst abmelden" funktioniert korrekt: 


![image](https://github.com/hitobito/hitobito/assets/95908537/5d4eae04-9f32-4bf9-93f3-fabb1f64b48d)
![image](https://github.com/hitobito/hitobito/assets/95908537/47840e1c-d97b-43d2-bc7a-cc7e34788e8d)
