### ISSUE TITLE
PDF Anmeldung Kontaktdaten können weitere Angaben überlagern

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#21]
Beim Drucken einer Eventteilnhame können die Kontaktdaten die weiteren Informationen überlagern, z. B. http://dsj.puzzle.ch/de/groups/1/events/1/participations/6/print.pdf 

<img width="1077" alt="bildschirmfoto 2016-06-14 um 18 49 28" src="https://cloud.githubusercontent.com/assets/194364/16051618/c483a556-3260-11e6-94ab-99fbcec8db86.png">

Originalissue: https://redmine.puzzle.ch/issues/15446

**Comment by RolandStuder** [comment]
Wir hatten keine weiteren Meldungen von diesem Problem, scheint in der Realität nicht aufzutreten oder irrelevant.

**Comment by nchiapol** [comment]
Well, wir hatten genau das Problem vor ein paar Wochen auch. Ich konnte das damals dann aber nicht reproduzieren und habe erst jetzt gesehen, dass die Betroffene Person mehr Telefonnummern eingetragen hatte als ich.
Auf wunsch kann ich das Betroffene PDF gerne per Mail senden.

**Comment by RolandStuder** [comment]
@nchiapol Ok, danke für die Rückmeldung, ich habe jetzt einen einfach fix gemacht, dass nur die ersten drei Telefonnummern aufgedruckt werden. Die ganze Positionierung dynamisch zu machen wäre etwas aufwändiger. Bei den Veranstaltungsdaten werden auch nur eine begrenzte Anzahl gezeigt.
