### ISSUE TITLE
Export der Rechnungsliste (8h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#211]
Nur zusammengefasst ohne die einzelnen Positionen auf der Rechnung.

**Comment by RolandStuder** [comment]
Möglichkeit nach Datum einzuschränken.

**Comment by janissbinder** [comment]
@RolandStuder Könntest du dieses Ticket noch genauer spezifizieren? Ich weiss nicht genau welche Daten und in welchem Format ich es exportieren soll.

**Comment by RolandStuder** [comment]
Ist umgesetzt
