### ISSUE TITLE
EINSTELLUNGEN: Qualifikations-, Kursarten und -kategorien

### ISSUE THREAD

**Issue by tschuepbach** [hitobito/hitobito#2113]
### Aktuelles Verhalten

Aktuell sind bei den Einstellungen die Qualifikations-, Kursarten und -kategorien nicht mehr sichtbar. Screenshot Produktion:
<img width="199" alt="image" src="https://github.com/cevi/hitobito_cevi/assets/40494600/7c2e2561-4081-4876-a3b8-c39cd65242db">

### Gewünschtes Verhalten

Qualifikations-, Kursarten und -kategorien können wieder bearbeitet werden.

### Schritte zu reproduzieren

1. Login mit :admin ability, Ebene Dachverband
2. Einstellungen via Navigation links

### Wann ist der Fehler aufgetreten?

23.05.2023

### hitobito version

1.28.74

### Organisation

Cevi

**Comment by carlobeltrame** [comment]
Merci für die Meldung! Ich kann das Problem reproduzieren, aber nur auf der Testumgebung. Wenn ich einen Produktions-Daten-Dump lokal laufen lasse und dann dich oder Carbon imitiere, funktioniert es korrekt.

Im Code sehe ich auch auf die Schnelle nicht, warum das falsch laufen könnte. Bedingung dafür dass man diese Menüeinträge sehen kann ist, dass mindestens eine Gruppe Kurse anbietet, und dass man irgendwo mindestens eine Rolle mit `:admin` Permission hat. Aus meiner Sicht ist bei euch beides gegeben.

Wir haben für den Elternzugang an den Berechtigungen herumgeschraubt, aber nicht in der Ecke der Qualifikations-, Kursarten und -kategorien.

**Comment by tschuepbach** [comment]
Ich habe noch versucht die Einstellungen via Direktlinks von der browser-history aufzurufen. Dabei erscheint bei allen drei folgende Meldung:
<img width="877" alt="image" src="https://github.com/hitobito/hitobito/assets/40494600/c91d9f52-0ac4-4d9a-8c53-ee91f4bfe8f0">

**Comment by ThomasEllenberger** [comment]
Habe dies angeschaut auf den Integrationsumgebungen von Cevi, Jubla, PBS, Core.
Das Problem scheint nur bei Cevi und Jubla Integration zu bestehen. Im Core und bei der PBS kann ich die Einstellungen noch immer sehen.

**Comment by tschuepbach** [comment]
Ist hier eine Lösung in Sicht? Wir bräuchten die Einstellungen auf der Produktion aller aller spätestens Ende Juni.

**Comment by ThomasEllenberger** [comment]
Dieser Bug wird mit hoher Priorität behoben. 
Aktuell sind alle unsere Entwickler noch mit anderen Issues beschäftigt. 
Sobald wir Kapazität haben wird sich dem jemand annehmen.
Ich vermute jedoch dass dann auch ein Release der Produktivumgebungen notwendig ist, damit dies aktiv wird. Wann ein Release gemacht wird ist grossteilig abhängig von den einzelnen Kunden.

**Comment by richardjubla** [comment]
Merci, die Qualifikations-, Kursarten und -kategorien sind bei uns wieder sichtbar
