### ISSUE TITLE
EVENT: event_requires_approval - Sofortige Anmeldung ohne E-Mail Freigabe der Anmeldung

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito#2120]
### Aktuelles Verhalten

Die Anmeldung an einen Kurs kann mit der Option `Freigabe: Die Scharleitung wird informiert und muss die Anmeldung bestätigen` (event_requires_approval) eingeschränkt werden. 
Eine Anmeldung führt aber zu einer direkten Anmeldung und löst kein E-Mail für die Freigabe aus.

### Gewünschtes Verhalten

Bei einer Anmeldung an einen Kurs erfolgt folgendes:
- Die Person landet in den Anmeldungen (nicht als Zugeteilte Teilnehmende)
- Bei der Person erscheint die Warnung: `? Kursfreigabe ausstehend`
- Bei der Anmeldung erscheint die Orange Warnung, dass die Anmeldung noch freigegeben werden muss
- Eine E-Mail an die Scharleitenden wird ausgelöst «Anlass: E-Mail Freigabe der Anmeldung» https://jubla.puzzle.ch/custom_contents/3/edit
- Durch die Freigabe durch die Scharleitung erfolgt die Zuteilung zum Kurs, sofern dies dies nicht durch andere Optionen/Abhängigkeiten ausgeschlossen ist. (zB. Option event_supports_applications)
- Status ändert auf `Kursfreigabe bestätigt`

 

### Schritte zu reproduzieren

- Kurs mit aktiver Option `Freigabe: Die Scharleitung wird informiert und muss die Anmeldung bestätigen` erstellen (event_requires_approval = yes)
- Mit Profil ohne Rolle Scharleitung oder zugriffsberechtigung für Anfragen für den Kurs anmelden
- **Bug**: Eine direkte Anmeldung an den Kurs erfolgt
- Feature?: Zugriffsberechtigung für Event/Kurs erfolgt nicht (Eigentlich könnte eine Anfrage zur Zugriffsberechtigung ausgelöst werden. Ich verstehe aber das dies hier nicht passiert, da onehin eine Freigabe durch eine zugriffsberechtigte Rolle erfolgen muss)
- **Bug**: E-Mail an die Scharleitenden wird nicht ausgelöst 

Problem: Ohne die E-Mail ist für die zugriffsberechtigte Rolle (Scharleitung/Coach) nicht ersichtlich, ob und für welche Mitglieder der Ebene/Gruppe eine Kursanmeldung vorliegt. 

### Wann ist der Fehler aufgetreten?

01.06.2023

### hitobito version

1.28.74

### Organisation

Jubla

### Screenshots, weiterer Kontext

![image](https://github.com/hitobito/hitobito/assets/95908537/6aa19999-f212-4b7e-8c15-ba56bf490539)

![image](https://github.com/hitobito/hitobito/assets/95908537/fe1ba94c-66fa-47e5-b9f5-68afadf69ab9)
![image](https://github.com/hitobito/hitobito/assets/95908537/2c99d674-ec69-4aa0-9226-28ac0af9352a)

Bug: Karl-Wilhelm Jäger / Jägi mit der Rolle Leiter/in kann sich direkt an den Kurs anmelden. Seine ausstehende Kursfreigabe wird zwar angezeigt, wird aber durch die direkte Anmeldung übersteuert. 

![image](https://github.com/hitobito/hitobito/assets/95908537/7d8ca8e6-5c66-4f6e-bc11-07599744c4f7)

Erst eine manuelles verschieben von Jägi von Zugeteilt zu Anmeldung durch eine Kursadministration ermöglicht den angedachten Ablauf: Die Scharleitung kann die Anmeldung freigeben. (Ein E-Mail, wird dennoch nicht ausgelöst)

![image](https://github.com/hitobito/hitobito/assets/95908537/eb779940-c2b2-4a47-b10f-f9d41221d3d8)

**Comment by nchiapol** [comment]
Wir beobachten das gleiche Problem: Bei uns sollte der Coach informiert werden, aber auch diese Mails werden nicht ausgelöst.  

Von einer Geschäftsstelle wurde das für die Problem für die Produktiv-Instanz gemeldet und ich konnte das auf der Integration nachstellen. Das Mail an den Coach wird unabhängig der Checkbox "Freigabe" nicht verschickt.

Gemäss der meldenden Geschäftsstelle wurden sicher letzten Dezember noch Benachrichtigung verschickt. Ich vermute, danach wurden keine Kurse mehr durchgeführt, die diese Einstellung aktiviert hatten.


Die automatische Zuteilung funktioniert bei uns korrekt und ich vermute die Jubla sieht das gleiche Verhalten. Wie wir bei unseren Anpassungen gelernt haben hatte die Checkbox "Warteliste" schon lange eine automatische Zuteilung zur Folge - deshalb haben wir dort bei uns nun den Text auch auf "Wenn es noch freie Plätze hat, werden Teilnehmende automatisch zugeteilt." geändert.

**Comment by richardjubla** [comment]
> Wir beobachten das gleiche Problem: Bei uns sollte der Coach informiert werden, aber auch diese Mails werden nicht ausgelöst.
> 
> Von einer Geschäftsstelle wurde das für die Problem für die Produktiv-Instanz gemeldet und ich konnte das auf der Integration nachstellen. Das Mail an den Coach wird unabhängig der Checkbox "Freigabe" nicht verschickt.
> 
> Gemäss der meldenden Geschäftsstelle wurden sicher letzten Dezember noch Benachrichtigung verschickt. Ich vermute, danach wurden keine Kurse mehr durchgeführt, die diese Einstellung aktiviert hatten.
> 
> Die automatische Zuteilung funktioniert bei uns korrekt und ich vermute die Jubla sieht das gleiche Verhalten. Wie wir bei unseren Anpassungen gelernt haben hatte die Checkbox "Warteliste" schon lange eine automatische Zuteilung zur Folge - deshalb haben wir dort bei uns nun den Text auch auf "Wenn es noch freie Plätze hat, werden Teilnehmende automatisch zugeteilt." geändert.

Lieber @nchiapol 

Wir planen einen Release Mitte Oktober. Der Versand der E-Mal (E-Mail an Scharleiter) ist dabei aus unserer Sicht ein zwingendes Feature. 

Wenn eine Freigabe notwendig ist (event_requires_approval) erfolgt aktuell bei uns eine automatische Zuteilung und die Freigabe ist lediglich in der definitiven Anmeldung "nachvollziehbar". Die Scharleitung kann die Freigabe gar nicht machen weil die Person bereits zugeteilt ist (und bekommt vielleicht auch aus diesem Grund keine E-Mail). Eine Freigabe ist nur möglich, wenn die Person noch nicht zugeteilt ist. Wird die Person manuell verschoben (Voranmeldung), funktioniert die Freigabe durch die Schrleitung wieder.

Wir sehen folgendes Verhalten als korrekt an:

- Wenn die Freigabe aktiviert ist, darf **keine** automatische Zuteilung erfolgen **nur** wenn die Freigabe erteilt wurde.
- Wenn eine automatische Zuteilung aktiviert/oder deaktiviert ist (über andere Einstellungen/Bedingungen wie Vorbedingungen), darf nur eine automatische Zuteilung erfolgen **wenn** auch diese anderen Bedingungen erfüllt sind.

Kannst du dieses Verhalten nachvollziehen und bestätigen?

**Comment by richardjubla** [comment]
> Die automatische Zuteilung funktioniert bei uns korrekt und ich vermute die Jubla sieht das gleiche Verhalten. Wie wir bei unseren Anpassungen gelernt haben hatte die Checkbox "Warteliste" schon lange eine automatische Zuteilung zur Folge - deshalb haben wir dort bei uns nun den Text auch auf "Wenn es noch freie Plätze hat, werden Teilnehmende automatisch zugeteilt." geändert.

Ich gehe davon aus, dass die automatische Zuteilung in diesem Fall nicht korrekt funktioniert. Ist eine Freigabe notwendig, darf keine Zuteilung erfolgen. Erfolgt die Zuteilung, geht "hitobito" davon aus, dass eine definitive Anmeldung vorliegt, auch der angemeldeten Person wird dies so mitgeteilt. Eine Zuteilung sollte nur aufgrund aller gültiger Bedingungen (Freigabe/Bedingungen/Qualifikationen/Warteliste) erfolgen.

**Comment by nchiapol** [comment]
@richardjubla 
Ich habe deine Rückfragen nicht erneut bei uns durchgespielt, aber: Bei uns gilt, die Option "automatische Zuteilung" ist stärker als Freigabe/Bedingungen/Qualifikationen (nicht aber max. TN-Zahl). Das hat bei uns initial auch zu Diskussionen geführt  (https://github.com/cevi/hitobito_cevi/issues/174). Wir haben uns aber entscheiden an diesem Verhalten festzuhalten.

Natürlich wäre es elegant, wenn das System diese Situation erkennen und die Anmeldung nicht automatisch zuteilen würde. Wir sind aber der Meinung, dass damit viel Komplexität verbunden wäre. Da sich dieses Problem mit klarer Kommunikation des Verhaltens verhindern lässt, investieren wir unsere Ressourcen deshalb lieber in andere Anliegen. 
Soweit ich das beurteilen kann, war das nun auch kein Problem mehr.

Falls ihr das aber in einem gemeinsamen Code implementieren wollt, wären wir damit aber wohl einverstanden.

**Comment by nchiapol** [comment]
PS: Ob die Freigabe-Mails auch bei uns durch die automatische Zugeteilt unterdrückt werden, prüfe ich bei Gelegenheit noch.

**Comment by nchiapol** [comment]
Habe unterdessen versucht zu kontrollieren ob die Freigabe-Mails ohne automatische Zuteilung funktionieren. Auf unserer Integrationsumgebung habe ich aber auch dann keine Mails erhalten.

**Comment by nchiapol** [comment]
@carlobeltrame @ThomasEllenberger 
Und noch einmal ich: Ich habe mit meiner lokalen Version herumgespielt und auch dort werden keine Freigabe-Mails verschickt. Grund scheint, dass die `@send_approval ` in `app/jobs/event/participation_confirmation_job.rb` nur in `initialize` existiert.

Ich habe den Code wie folgt mit zwei print-Statements instrumentiert, 
```
class Event::ParticipationConfirmationJob < BaseJob

  self.parameters = [:participation_id, :locale]

  def initialize(participation, send_approval: true)
    super()
    @participation_id = participation.id
    @send_approval = send_approval
    print "INITCONFIRM #{@send_approval} -"
  end

[...]

  def send_approval
    print "approving #{@send_approval} -" 
    return unless @send_approval && participation.pending?

[...]
``

und der relevante Output ist danach
```
INITCONFIRM true
[...]
approving  - 
```

Ich habe dann diverse Dinge versucht (z.B. Variable umbenennen) leider ohne Erfolg. Wenn ich den `return unless`-Check zu `return unless true && participation.pending?` anpasse klappt alles. Ich bin mit meinem Ruby/Rails am Ende...

**Comment by tschuepbach** [comment]
Bei uns häufen sich die Anfragen und Unklarheiten der nicht versendeten Benachrichtigungen bezgl. der Coach-Freigaben. Wäre schön, wenn dieses Problem etwas priorisiert werden könnte..
