### ISSUE TITLE
KURSE: Option event_waiting_list / Warteliste

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito#2122]
### Aktuelles Verhalten

Jubla / event_waiting_list 
`Warteliste: Wenn keine Plätze mehr frei sind, landen neue Anmeldungen automatisch auf der Warteliste.`

Cevi / event_waiting_list
`Automatisch zugeteilt: Wenn es noch freie Plätze hat, werden Teilnehmende automatisch zugeteilt.`

Obwohl es sich um den gleichen Parameter (event_waiting_list) handelt, ist die Beschreibung des Parameters zwischen Jubla & Cevi unterschiedlich UND das verhalten ist **nicht** gleich. 
Ich habe gesehen:
- Ein Überbuchen eines Kurses ist unabhängig von dieser Option möglich. (Keine Ahnung ob das so beabsichtigt ist, es gibt keine Möglichkeit eine Überbuchung von einem Kurs zu verhindern)
- Wird eine Maximale Teilnehmerzahl gesetzt, werden bei der Cevi ab erreichen der Teilnehmerzahl eine Anmeldung in der Anmeldung/Warteliste aufgeführt

**Bug:** Die Option für die Warteliste funktioniert nicht. Auch eine Überbuchung führt zu einer direkten Zuteilung zu einem Kurs ohne in der Anmeldung/Warteliste zu landen. Auch wird keine Meldung angezeigt, dass die Anmeldung (wegen Überbuchung) nur provisorisch ist.
**Bug:** Ohne Optionen erfolgt immer eine direkte Anmeldung. (Bei der Cevi erfolgt ohne Optionen immer ein Voranmeldung auf die Warteliste)
**Bug:** Transaktionsmail `Bestätigung der Anmeldung` wird versendet. (Als folge von Bug, welcher direkt zu einer Zuteilung führt)
**Bug:** Die Warnung "Es sind derzeit alle Plätze belegt" wird nur bei einer Überbuchung UND der aktiven Option event_waiting_list=yes angezeigt. Aus meiner Sicht sollte eine Überbuchung nicht möglich sein oder die Warnung bei jeder Überbuchung angezeigt werden. 

### Gewünschtes Verhalten

- Gemäss Puzzle/Hitobito sollte das Verhalten von event_waiting_list als "Core-Option" in den Testumgebungen von Cevi/Jubla das gleiche Verhalten zeigen. Dies ist bei meinen Tests nicht der Fall. 
- Bei Kursen wird jeweils die Anmeldung von einer Kuradministration verwaltet, deshalb halte ich es für sinnvoll, dass grundsätzlich alle Anmeldungen nicht direkt zugeteilt werden und auf der Warteliste (Anmeldung) landen.
- Die Option event_waiting_list steuert, ob für einen Kurs dennoch eine direkte Anmeldung möglich ist. (Dies macht für mich nur sinn, wenn die direkte Anmeldung sonnst nicht möglich ist oder durch eine weitere Option (früher event_supports_applications?) eingeschränkt werden kann. 
- Ein Überbuchen von Kursen kann nicht eingeschränkt werden. Aus diesem Grund wäre es wichtig, dass alle Anmeldungen über der maximalen Teilnehmerzahl (mindestens) in der Warteliste (Anmeldung ohne Zuteilung) landen und dies bei der Anmeldung dem User als Warnung angezeigt wird.

### Schritte zu reproduzieren

- Kurs erstellen und Option event_waiting_list jeweils aktivieren oder deaktivieren
- Als Kursteilnehmer eine Anmeldung durchführen

### Wann ist der Fehler aufgetreten?

01.06.2023

### hitobito version

1.28.74

### Organisation

Jubla, Cevi

### Screenshots, weiterer Kontext

Cevi Test-db mit Anmeldung an Kurs mit allen Plätzen belegt:
Korrekt: Warnung zur Überbuchung wird angezeigt, Anmeldung landet auf Warteliste
![image](https://github.com/hitobito/hitobito/assets/95908537/a4b973d6-001e-420b-a49b-d46a667e41da)

Jubla Test-db mit Anmeldung an Kurs mit allen Plätzen belegt:
Bug: Person wird direkt angemeldet, keine Warnung zur Überbuchung wird angezeigt.
![image](https://github.com/hitobito/hitobito/assets/95908537/86a9152e-1849-4e91-a2d7-6afa03d7a96b)

Beim Testen auf der Cevi-DB habe ich gesehen, dass die Kurs-[Anmeldungen](https://cevi.puzzle.ch/groups/1/events/1195/application_market) zu einem Fehler E500 führen können:
@nchiapol 
![image](https://github.com/hitobito/hitobito/assets/95908537/ebba474b-f479-49c4-88e8-a2adbea395e8)

Trivia/Vermutung:
- Ich kann leider immer noch nicht genau auf die Optionen event_waiting_list und event_supports_applications eingehen. Mangels Verständnis und Dokumentation. Aktuell habe ich die Vermutung, dass die Warteliste (Anmeldung ohne direkte Zuteilung) eigentlich nur in Ausnahmefällen oder durch Optionen vorgesehen war. 
Eine Anmeldung sollte wenn möglich direkt erfolgen. Die Jubla (und evtl. andere Org.) haben aber mit der Kursverwaltung das Interesse, die Anmeldungen zu verwalten und sind deshalb daran interessiert, die Zuteilung zum Kurs manuell vorzunehmen. (Dabei wird jeweils zusätzlich oder manuell kontrolliert, ob alle Vorbedingungen stimmen, die Rechnung bezahlt wurde oder die Scharleitung das OK gegeben hat). Die Option event_supports_applications diente wohl dafür, alle Anmeldungen zuerst auf die Warteliste (Anmeldung ohne direkte Zuteilung) zuzuordnen. Mit dem wegfallen dieser Funktion und dem Bug der Option event_waiting_list werden grundsätzlich alle Kursanmeldungen gleich direkt zugeteilt. Eine Situation die der Kursverwaltung ein gehörige Prozessveränderung und "Probleme" verursachen würde.
- Ich konnte nicht herausfinden wie und ob die Option "Provisorische Anmeldungen" event_tentative_applications korrekt funktioniert.
- Der Elternzugang sollte keinen Einfluss/Veränderungen auf Kurs-Anmeldungen haben

**Comment by carlobeltrame** [comment]
Der Cevi hat bei dieser Option vor einigen Monaten Customizations machen lassen. Daher ist es zu erwarten dass das Verhalten unterschiedlich ist. Ich habe aber wegen den komplizierten Sachverhalten keinen Überblick mehr wie es sich auf welcher Umgebung verhalten müsste.

**Comment by tschuepbach** [comment]
Hoi Richard

hitobito_cevi/issues/168

Hier kannst du in etwas nachlesen, wie sich dies bei uns (im Optimalfall) verhalten sollte.. Ansonsten darfst du mich bei Fragen oder Unklarheiten gerne anrufen.

**Comment by richardjubla** [comment]
> Der Cevi hat bei dieser Option vor einigen Monaten Customizations machen lassen. Daher ist es zu erwarten dass das Verhalten unterschiedlich ist. Ich habe aber wegen den komplizierten Sachverhalten keinen Überblick mehr wie es sich auf welcher Umgebung verhalten müsste.

Gemäss meinen Informationen (oder deren Interpretation) ging ich davon aus, dass wir eben diese Anpassungen (inkl. Core/Youth) ebenfalls erhalten haben. Siehe auch: https://github.com/hitobito/hitobito/issues/1927#issue-1466163124 

Demzufolge müssen wir wohl davon ausgehen, dass auf unserer Testumgebung die Kursanmeldungen "teilweise" neu anders funktionieren wie sie im Core/Youth angepasst wurden. Diese unterscheiden sich auch noch zusätzlich zur aktuellen Produktivumgebung. **Zudem** funktionieren aber die Kursanmeldungen weiterhin "teilweise" so, wie sie nur in unserer Testumgebung funktioniert. Wir können für unsere Tests keine verlässlichen vergleiche mit der Cevi-Testumgebung machen und falls wir Anpassungen benötigen ist (für uns) unklar, ob sie unseren oder gemeinsamen Code betreffen.

Wir verfolgen weiterhin das Ziel, im Inkrement 2/23 die Anmeldeprozesse für Kurse nachzuvollziehen und soweit sicherzustellen damit wir mit einem Release weiterhin unsere Kurse anbieten und durchführen können. Dazu werden wir bei bedarf weitere/ähnliche Issues wie dieses eröffnen.

**Comment by richardjubla** [comment]
> Finde ich super wenn ihr euch einen Überblick verschafft wie die Prozesse aktuell funktionieren und dann Schritt für Schritt gezielte Anpassungen vornehmt.
> 
> Ich habe mich nur auf den Punkt "Gemäss Puzzle/Hitobito sollte das Verhalten [...] in den Testumgebungen von Cevi/Jubla das gleiche Verhalten zeigen" bezogen. Dieser Aussage stimme ich nicht zu. Folglich kannst du dich (hier und in den weiteren angekündigten Issues) für die Erhebung bei der Jubla nicht wirklich darauf abstützen, wie es beim Cevi funktioniert. Deine anderen Punkte und Findings sind valide und sehr wertvoll, merci dafür.

So super finden wir das nicht gerade, dass wir uns eher unverhofft einen Überblick verschaffen dürfen ;-). Für einen Release benötigen wir eine funktionale Kursverwaltung und können uns nicht Schritt für Schritt vornehmen. Weder Test- noch Produktivumgebung funktioniert richtig. bei aktuell 35 offenen Kursen mit über 300 Teilnehmenden, pro Jahr können es mehr als 3'000 werden.... Ich werde mich mit @ThomasEllenberger über das weitere Vorgehen austauschen.

**Comment by nchiapol** [comment]
@richardjubla Wie am Hackaton besprochen, denke ich, dass auch für euch unser Verhalten passen könnte. Ich fände es super, wenn wenigstens wir zwei hier Synergien nutzen könnten. Falls also aus eurer Sicht etwas an unserem Verhalten gar nicht passt, können wir das gerne besprechen.

Ausserdem:  Warteliste != Rechte Spalte im Tab-Anmeldungen. Im Screenshot unten ist nur Donar auf der Warteliste, Frost wurde einfach noch nicht zugeteilt (ist also gemäss unseren Begriffen erst Vorangemeldet).
![screenshot_2023-06-02_233538-1](https://github.com/hitobito/hitobito/assets/1123483/e57b9f15-dee8-49e9-9c00-e9882d900bad)

Betreffend dem 500er: Auf dem Anmeldungen-Tab hatte ich das Problem in der Produktion noch nie. Kann also gut auch ein Artefakt dieses Test-Kurses mit seinen speziellen TN sein.

**Comment by richardjubla** [comment]
> @richardjubla Wie am Hackaton besprochen, denke ich, dass auch für euch unser Verhalten passen könnte. Ich fände es super, wenn wenigstens wir zwei hier Synergien nutzen könnten. Falls also aus eurer Sicht etwas an unserem Verhalten gar nicht passt, können wir das gerne besprechen.
> 
> Ausserdem: Warteliste != Rechte Spalte im Tab-Anmeldungen. Im Screenshot unten ist nur Donar auf der Warteliste, Frost wurde einfach noch nicht zugeteilt (ist also gemäss unseren Begriffen erst Vorangemeldet). ![screenshot_2023-06-02_233538-1](https://user-images.githubusercontent.com/1123483/242995556-e57b9f15-dee8-49e9-9c00-e9882d900bad.png)

@nchiapol Bisher bin ich leider gescheitert die Synergien zu finden oder zu nutzen. Zudem sehen wir viele von euch gemeldeten oder bereits gelöste Fehler noch auf unserem Testsystem (https://github.com/cevi/hitobito_cevi/issues/168). Ich bin hier insbesondere nach dem Hackaton von einer anderen Situation ausgegangen.

Es wäre für mich essenziell von @thomasellenberger zu wissen, welche Funktionen der Kursverwaltung im Core, im Youth und welche ausschliesslich in unserem Wagon vorkommen. Für mich steht (leider) auch die Option im Raum, unseren Wagon (inkl. der Core-Anpassungen) wieder zurücksetzten zu lassen.

Zur "Warteliste": Ich werde versuchen jeweils ein genaueres Wording für die verschiedenen Stati der Anmeldung zu wählen:
- Voranmeldung
- Anmeldung auf Warteliste
- Anmeldung ohne Zuteilung
- Anmeldung mit direkter Zuteilung
- Anmeldung mit offener Freigabe durch Scharleitung/Coach 
- etc.

**Comment by ThomasEllenberger** [comment]
Danke @richardjubla fürs testen und zusammenfassen.

Ich habe versucht mir einen Überblick über die verschiedenen Features und Usecases zu machen, unabhängig der Bugs.
So wie ich dass sehe haben Cevi, Jubla und PBS alle etwas andere Features, wenn sich auch einige überlappen. Keine der Umgebungen funktioniert exakt wie im Core.

Wir haben mit den Änderungen für die Cevi in den Issues https://github.com/hitobito/hitobito_cevi/issues/79  und https://github.com/hitobito/hitobito_cevi/issues/80 Anpassungen vorgenommen und diese im Core umgesetzt.
Im Ticket #1927 wurde spezifiziert dass dies im Core gemacht wird, jedoch Pfadi und Jubla ihre Prozese beibehalten möchten.
Es scheint jedoch als hätte dies nicht geplante Auswirkungen zumindest bei der Jubla gehabt, wodurch Bugs bei der Kursanmeldung der Jubla entstanden.

Es ist uns bewusst, dass wir hier nun drei unterschiedliche Lösungen haben. Diese haben auch Features welche teilweise gleich heissen, aber nicht gleich funktionieren, oder den Default nicht gleich gesetzt haben. Das ganze wurde auch für uns sehr unübersichtlich.

Ich sehe hier desshalb ein zweiteiliges Vorgehen:
1. Beheben der Bugs, so dass wir zu einer funktionierenden Lösung auf allen drei Umgebungen kommen und diese möglichst bald releasen können (geplanter erster Allgemeiner Release ist Anfang July).
2. Diskussion ob und wie Dinge vereinheitlicht werden können. Ich denke hier wäre es zielführend wir könnten uns einmal alle gemeinsam Zeit nehmen zu diskutieren was und wie wir etwas haben möchten. Die Umsetzung dazu sehe ich eher langfristig und müsste gut durchdacht sein und schlussendlich auch eventuelle andere Kunden beinhalten welche Anlässe, Kurse und Lager verwenden.

So wie ich es aktuell verstehe, funktioniert bei der Cevi und der Pfadi alles zumindest soweit, dass einem Release nichts im Wege steht. Ich werde im Team abklären, inwieweit ein Zurücksetzen der Änderungen im Jubla Wagon möglich ist und Sinn ergibt. Ansonnsten würde ich zusammen mit @richardjubla eine Liste der notwendigen minimalen Bugfixes aufstellen die nötig sind um einen Release zu ermöglichen.

**Comment by nchiapol** [comment]
@ThomasEllenberger Das vorgeschlagene Vorgehen scheint mir sinnvoll. Ich nehme mir gerne Zeit für eine gemeinsame Diskussion.

Zudem eine Ergänzung: Mindestens ein Bug der Jubla betrifft auch uns, vgl. https://github.com/hitobito/hitobito/issues/2120#issuecomment-1574322915

Ich bin deshalb froh, wenn ich mitbekomme welche Bugs die Jubla findet und beheben möchte. Dann kann ich die auch gleich bei uns testen ;-)

**Comment by richardjubla** [comment]
Lieber @ThomasEllenberger 

Ich bitte um eine Struktur/Gefäss in der wir unsere Anpassungen/Bugs melden und sammeln können. Wir möchten im aktuellen Inkrement 3/23 mit einem Release eine funktionierende Kursverwaltung ausspielen können. Dazu benötigen wir Klarheit über Zeiträume, Budget/Finanzierung oder Fristen.

**Comment by ThomasEllenberger** [comment]
@richardjubla Da sich hier einiges getan hat, bin ich den obersten Post Stand 28.09.2023 noch einmal durchgegangen. Anbei meine Rückmeldungen/Erkenntnisse stand heute:

> Obwohl es sich um den gleichen Parameter (event_waiting_list) handelt, ist die Beschreibung des Parameters zwischen Jubla & Cevi unterschiedlich UND das verhalten ist **nicht** gleich. Ich habe gesehen:

Korrekt. Der Parameter (event_waiting_list)  stammt zwar aus dem Core, die Jubla und die Cevi haben hier aber beide Wagon spezifisch Weiterentwicklungen vorgenommen, welche das Verhalten verändern, weshalb dieses auf der Jubla_INT und der Cevi_INT nicht identisch funktioniert.

>  Ein Überbuchen eines Kurses ist unabhängig von dieser Option möglich. (Keine Ahnung ob das so beabsichtigt ist, es gibt keine Möglichkeit eine Überbuchung von einem Kurs zu verhindern)

Korrekt. Meines Erachtens gibt es keine Möglichkeit die maximale Anzahl Anmeldungen auf einem Kurs zu begrenzen.

>  Wird eine Maximale Teilnehmerzahl gesetzt, werden bei der Cevi ab erreichen der Teilnehmerzahl eine Anmeldung in der Anmeldung/Warteliste aufgeführt

Dieses Verhalten ist gemäss meinen Tests bei der Jubla identisch. Achtung: Warteliste /= Nationale Warteliste!

> **Bug:** Die Option für die Warteliste funktioniert nicht. Auch eine Überbuchung führt zu einer direkten Zuteilung zu einem Kurs ohne in der Anmeldung/Warteliste zu landen. Auch wird keine Meldung angezeigt, dass die Anmeldung (wegen Überbuchung) nur provisorisch ist. 

Dies kann ich so nicht bestätigen. Nach meinen Tests landet eine Anmeldung bei einem vollen Kurs auf der rechten Seite im Anmelden tab und der Anwender erhält eine Meldung dass es sich um eine Voranmeldung handelt. Achtung: Warteliste /= Nationale Warteliste!
Siehe Testcases https://github.com/hitobito/hitobito_jubla/issues/47

> **Bug:** Ohne Optionen erfolgt immer eine direkte Anmeldung. (Bei der Cevi erfolgt ohne Optionen immer ein Voranmeldung auf die Warteliste) 

Die Cevi hat dieses Verhalten bei sich spezifisch anpassen lassen, und hat standartmässig ein Häckchen gesetzt, welches Anmeldungen immer auf die Rechte Seite des Anmeldungen Tabs schiebt, auch wennes noch freie Plätze im Kurs hat. Dieses Verhalten weicht vom Jubla verhalten ab.

> **Bug:** Transaktionsmail `Bestätigung der Anmeldung` wird versendet. (Als folge von Bug, welcher direkt zu einer Zuteilung führt) 

Diese Bemerkung verstehe ich nicht.

> **Bug:** Die Warnung "Es sind derzeit alle Plätze belegt" wird nur bei einer Überbuchung UND der aktiven Option event_waiting_list=yes angezeigt. Aus meiner Sicht sollte eine Überbuchung nicht möglich sein oder die Warnung bei jeder Überbuchung angezeigt werden.

Dies kann ich durch meine Tests bestätigen. 
Dass eine Überbuchung nicht möglich ist, oder die Warnung bei jeder Überbuchung erscheint wären neue Anforderungen.

> ### Gewünschtes Verhalten
> 
>  Gemäss Puzzle/Hitobito sollte das Verhalten von event_waiting_list als "Core-Option" in den Testumgebungen von Cevi/Jubla das gleiche Verhalten zeigen. Dies ist bei meinen Tests nicht der Fall.

Diese Annahme ist leider nicht korrekt. Sowohl Cevi wie auch Jubla haben hier wagon spezifisches das Teile des Kurswesens vom Core überschreibt.

>    Bei Kursen wird jeweils die Anmeldung von einer Kursadministration verwaltet, deshalb halte ich es für sinnvoll, dass grundsätzlich alle Anmeldungen nicht direkt zugeteilt werden und auf der Warteliste (Anmeldung) landen.

Dies ist eine neue Anforderung der Jubla.
Bei der Cevi haben wir eine Auswahl hierfür eingefügt in form der Option "Automatisch zugeteilt"

>   Die Option event_waiting_list steuert, ob für einen Kurs dennoch eine direkte Anmeldung möglich ist. (Dies macht für mich nur sinn, wenn die direkte Anmeldung sonnst nicht möglich ist oder durch eine weitere Option (früher event_supports_applications?) eingeschränkt werden kann.

Die "event_waiting_list" steuert meines Erachtens nur die automatische Aufnahme zur nationalen Warteliste wenn ein Kurs voll ist und hat nichts mit der direkten Anmeldung an den Kurs selbst zu tun.

>   Ein Überbuchen von Kursen kann nicht eingeschränkt werden. Aus diesem Grund wäre es wichtig, dass alle Anmeldungen über der maximalen Teilnehmerzahl (mindestens) in der Warteliste (Anmeldung ohne Zuteilung) landen und dies bei der Anmeldung dem User als Warnung angezeigt wird.

Korrekt: Eine Überbuchung des Kurses kann meines Erachtens heute nicht eingeschränkt werden.
Anmeldungungen an einen vollen Kurs landen meines Erachtens heute bereits auf der rechten Seite des Anmelden Tabs.
Dies ist ungleich der nationalen Warteliste! Nur mit aktiviertem Checkmark "Warteliste" landen Anmeldungen zu einem vollen Kurs zusätzlich auch noch auf der nationalen Warteliste.

**Comment by richardjubla** [comment]
> Korrekt. Der Parameter (event_waiting_list) stammt zwar aus dem Core, die Jubla und die Cevi haben hier aber beide Wagon spezifisch Weiterentwicklungen vorgenommen, welche das Verhalten verändern, weshalb dieses auf der Jubla_INT und der Cevi_INT nicht identisch funktioniert.

Dann müsste es doch möglich sein. Den Parameter "event_supports_applications" wieder für uns zu aktivieren?
https://github.com/hitobito/hitobito/commit/d3eb5308e1fc33df2531b061b2d15dbe606a0b63

**Comment by richardjubla** [comment]
> Diese Bemerkung verstehe ich nicht.

Es gibt das Transaktionsmail "Bestätigung der Anmeldung" https://jubla.puzzle.ch/custom_contents/2/edit
Dieses wird versendet, sobald eine Anmeldung bestätigt wird. Sie sollte damit verbindlich sein.
Falls nun aber eine Anmeldung nicht direkt zu einer Anmeldung führen soll (Warteliste/Überbuchung/etc.) darf diese E-Mail die Anmeldung nicht bestätigen. 

Dafür gibt es das Transaktionsmail "Anlass: E-Mail Voranmeldung" https://jubla.puzzle.ch/custom_contents/36/edit
Es informiert darüber, dass eine Vornameldung für die Teilnahme am Anlass eingegangen ist. 

Ich kann nicht nachvollziehen was unser Parameter event_waiting_list genau macht. Wenn er aber Anmeldungen auf die  Warteliste setzten soll wenn keine Plätzte mehr frei sind (So steht es akutell in der jubla.db), dann darf in diesem Fall kein E-Mail mit einer Anmeldebestätigung versendet werden.

**Comment by richardjubla** [comment]
Diese Issue wird mit Version 2.0 obsolet und ohne Lösung geschlossen.
