### ISSUE TITLE
mysql2 0.3.15 und MySQL 5.7

### ISSUE THREAD

**Issue by stefanbrunner** [hitobito/hitobito#214]
Hallo Zusammen

Ich versuche seit einigen Tagen verzweifelt eine Instanz von Hitobito zu installieren. Leider scheitere ich jedesmal daran mit `rake db:create` eine DB zu erstellen.

Ich erhalte folgende Fehlermeldung:

`hitobito@srv-hitobito:~/hitobito$ sudo rake db:create
require rails:   0.720000   0.190000   0.910000 (  0.909139)
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'mysql2'.
/home/hitobito/hitobito/config/application.rb:24:in `block in <top (required)>'
/home/hitobito/hitobito/config/application.rb:15:in `with_benchmark'
/home/hitobito/hitobito/config/application.rb:22:in `<top (required)>'
/home/hitobito/hitobito/Rakefile:12:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
NameError: uninitialized constant Mysql2::Client::SECURE_CONNECTION
/var/lib/gems/2.3.0/gems/mysql2-0.3.15/lib/mysql2/client.rb:12:in `<class:Client>'
/var/lib/gems/2.3.0/gems/mysql2-0.3.15/lib/mysql2/client.rb:2:in `<module:Mysql2>'
/var/lib/gems/2.3.0/gems/mysql2-0.3.15/lib/mysql2/client.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/mysql2-0.3.15/lib/mysql2.rb:10:in `<top (required)>'
/home/hitobito/hitobito/config/application.rb:24:in `block in <top (required)>'
/home/hitobito/hitobito/config/application.rb:15:in `with_benchmark'
/home/hitobito/hitobito/config/application.rb:22:in `<top (required)>'
/home/hitobito/hitobito/Rakefile:12:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
hitobito@srv-hitobito:~/hitobito$`

Wie kann ich Hitobito installieren? Ich hoffe jemand von euch weiss rat.
So viel wie ich bereits weiss, liegt es daran das sql2 0.3.15 nicht mit MySQL 5.7 funktioniert. Die installation einer neueren Version von sql2 bringt aber nichts da rake immer noch die 0.3.15er Version verwendet.

**Comment by Chronyms** [comment]
Hallu
Ich hatte das Problem auch, habe aber einen Lösungsansatz gefunden. Ich kann nicht Garantieren, dass die Lösung für dich Funktioniert, da ich dein Setup nicht kenne, aber kannst ja mal Probieren.

Tatsächlich liegt es an der Version von mysql2 für Ruby, im zusammenspiel mit Ruby-on-Rails und MySql.

Ich konnte das Problem lösen, indem ich die Version von mysql2 auf 0.3.17 änderte. Die Version welche installiert wird, ist in der Datei "hitobito/Gemfile" hinterlegt. Dort also die Zeile "gem 'mysql2', '0.3.15'
" zu "gem 'mysql2', '0.3.17'" ändern.
Danach im Verzeichnis "hitobito" den Befehl "bundle" ausführen.

**Comment by RolandStuder** [comment]
Soweit ich weiss, ist dieses Issue behoben mit den Gem Upgrades von den letzten Releases, falls nicht biete kommentieren.
