### ISSUE TITLE
GRUPPEN: Archivieren gibt leere Seite aus

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito#2142]
### Aktuelles Verhalten

Archiviere ich eine Gruppe (z.B. https://db.windband.ch/de/groups/9979) wird anschliessend eine leere Seite angezeigt und die Gruppe scheint weiterhin aktiv zu sein (jedenfalls vermag ich keinen Hinweis auf der Gruppe für die Archivierung zu erkennen).

### Gewünschtes Verhalten

Beim Ausführen des Befehls "Archivieren" soll die Gruppe auch tatsächlich archiviert werden.

### Schritte zu reproduzieren

1. Gruppe https://db.windband.ch/de/groups/9979 öffnen
2. Tab Info > Bearbeiten > Archivieren

### Wann ist der Fehler aufgetreten?

20.06.2023 14.20

### hitobito version

1.28.41.1

### Organisation

SBV

**Comment by betsim** [comment]
Weil es die Live-Seite betraf, wurde die Gruppe 9979 inzwischen gelöscht, d.h. der Bug kann so nicht mehr nachvollzogen werden. Auf der Integrationsumgebung kann ich den Bug auch nicht reproduzieren und auf der Live-Umgebung nicht mehr testen.

**Comment by kronn** [comment]
Aufgrund der fehlenden Reproduzierbarkeit und auch der vergangenen Zeit würde ich das Issue hier schliessen. Nicht als Absage an das Problem, sondern schlicht, weil ich hier nicht sehe, wie wir es lösen oder auch nur nachstellen können. Wenn es wieder auftritt, helfe ich gerne bei der Behebung des Fehlers.
