### ISSUE TITLE
E-Mail validation: False positive needs server restart

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito#2154]
### Aktuelles Verhalten

Die Haupt E-Mail Adresse wird beim erstellen oder speichern validiert. Diese Validierung ist bei uns bereits mehrere Male (6.7.23/29.4.23/25.10.22) ausgefallen. Dies führt dazu, dass sich Menschen nicht für Gruppen/Events anmelden können oder auch keine Haupt-E-Mail-Adresse für ein Profile angelegt oder aktualisiert werden kann. 
Der Fehler ist schwer überprüfbar und benötigt jeweils einen neuen Start des Servers. 

### Gewünschtes Verhalten

Mögliche Varianten:
- Überprüfung stabiler machen
- Überprüfung um Domain White List mit gängigen Providern führen (würde wohl 90% der Fälle abdecken)
- False positive führt zu Warnung und nicht zu Abbruch (wohl nicht erwünscht / Security) 

### Schritte zu reproduzieren

Neues Profil mit Haupt-E-Mail anlegen oder Haupt-E-Mail ändern mit Domain ohne oder (bewusst) inkompatiblem MX Eintrag.  Neues Profil mit Haupt-E-Mail anlegen oder Haupt-E-Mail ändern wenn der Service "abgestürzt" ist. 

### Wann ist der Fehler aufgetreten?

06.07.2023

### hitobito version

1.28.30.2

### Organisation

Jubla

### Screenshots, weiterer Kontext

![image](https://github.com/hitobito/hitobito/assets/95908537/fdef3654-98ff-427c-961b-83cc8cc972b1)
![image](https://github.com/hitobito/hitobito/assets/95908537/5ec1eb6d-8d4b-4a50-a6c2-8041ee3bc60d)

Specs: https://github.com/hitobito/hitobito/issues/1851

**Comment by carlobeltrame** [comment]
Merci fürs Ticket. Wir haben das bereits seit Anfang Jahr gelöst, aber durften wenn ich mich recht erinnere seither nie regulär bei euch releasen.

**Comment by richardjubla** [comment]
Merci, schliesse das Ticket.
