### ISSUE TITLE
Kontakthistory (Notizen) nach Jahr anzeigen (analog Anlässe) (4h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#216]
Weitere Filter auf Notizen ermöglichen.

## Offene Fragen:

* Geht es um die Ansicht pro Person oder um den Reiter Notizen? Auf dem Reiter Notizen ist das schwierig zu machen, vielleicht sind das pro Jahr hunderte von Nachrichten und Pagination und Auswahl des Jahres anzubieten finde ich verwirrlich.
* Was ist das Ziel? In welchen Fällen ist das wichtig?

**Comment by codez** [comment]
Annahme: Auf Personenansicht Paginierung nach Jahr.

**Comment by codez** [comment]
Schätzung: 0.5PT
