### ISSUE TITLE
AHV-Nummer vom Profil in den Event verschieben

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#2162]
Aus der Diskussion zwischen der Ausbildung PBS, Jubla und Cevi ist ein Bedürfnis entstanden: Die AHV-Nummer soll nur noch temporär gespeichert und nach Abschluss des Events wieder gelöscht werden. Die Anpassung betrifft vermutlich vor allem den Youth-Wagon.

### Grund-Idee
- Das AHV-Feld im Profil wird entfernt und die Daten gelöscht
- Stattdessen kann die AHV-Nummer neu bei der Anmeldung zu einem Event eingetragen werden (jedoch nicht mehr mit dem Profil verknüpft)
- Pro Event kann gewählt werden, ob die AHV-Nummer erfasst wird und ob diese obligatorisch ist oder nicht
- Beim Abschluss des Events (z.B. X Tage nach Durchführung) werden alle AHV-Nummern des Events gelöscht.
- Bei Exports von Personenlisten wird die AHV-Nummer entfernt 
- Bei Exports von Teilnehmer*innen wird die AHV-Nummer vom neuen Feld übernommen

### Fragen
- Braucht es eine Zwischenphase?
- Was gibt es für Abhängigkeiten?

@richardjubla @nchiapol Wie ist der Stand bei euch? Was müssen wir beachten?

**Comment by carlobeltrame** [comment]
Führt das bei Abteilungen, deren TN sich nicht selber zu den Anlässen anmelden, nicht dazu dass die Leitenden sich ausserhalb von hitobito alle AHV-Nummern der Kinder aufschreiben werden?

**Comment by richardjubla** [comment]
Die Jubla kennt die Felder:
- person_ahv_number_old / AHV-Nummer alt
- person_ahv_number / AHV-Nummer

Die AHV-Nr. ist sicher speziell, da sie sich nie ändert und eine eindeutige Zuordnung zu einem Menschen ermöglicht. (Sie ist nicht ein besonders schützenswerter Datensatz, es müssen aber besondere rechtlichen Bestimmungen beachtet werden, wenn die AHV-Nr. systematisch erhoben wird.) https://www.zas.admin.ch/zas/de/home/partenaires-et-institutions-/utilisation-systematique-du-navs13.html

Ich könnte mir vorstellen, dass die AHV-Nr. zu einem temporären Feld wird. Wir müssten aber schauen ob und wo noch andere Stellen auf vorhandene/gespeicherte AHV-Nummern angewiesen sind. Es wäre blöd, wenn eine Schar einen "Event" durchführen müsste, nur um an eine Liste von AHV-Nr. zu kommen 😅

**Comment by nchiapol** [comment]
Kleines Update: Gemäss dem Mail "Informationen vom 18. Juli 2023 für J+S-Coaches" des BASPO gilt:

> Falls Sie die AHV-Nummer in Ihrer Vereinsdatenbank speichern wollen, brauchen Sie die ausdrückliche Erlaubnis der betroffenen Personen bzw. deren Erziehungsberechtigten.

**Comment by tschuepbach** [comment]
Der Cevi ist definitiv auch mit dabei.

Folgende Überlegungen habe ich mir noch gemacht:
- Auf der Personen-Übersicht (.../groups/.../events/.../participations/...) wird die AHV-Nummer auch angezeigt. Bei uns wird diese aktuell für die Kontrolle der Zulassungsbedingungen (J+S-Bio) verwendet. Das neue AHV-Feld sollte ja dann bei den Anmeldeangaben weiter unten auch erscheinen.
- Was passiert mit Kursen, welche schon (nach dann altem Mecano) eröffnet sind, schon Anmeldungen haben und die AHV-Nummer benötigt wird? z.B. sind alle MFEs für das Jahr 2024 schon auf allen JuVe-Datenbanken offen zur Anmeldung.

**Comment by Michael-Schaer** [comment]
Ich denke auch, dass eine Zwischenphase nützlich wäre, in der z.B. bereits erfasste AHV-Nummern noch sichtbar sind, jedoch keine Neuen erfasst werden können.

Dann müsste aber sowohl die Anmeldung, wie auch die Anzeige und der Export berücksichtigen, dass es zwei mögliche Felder gibt, die eine AHV enthalten können.

**Comment by ThomasEllenberger** [comment]
Bei einem Austausch mit Cevi, Jubla und Pfadi haben wir uns die Grundlagen für dieses Ticket angeschaut und konnten uns auf einen MVP einigen. @nchiapol @Michael-Schaer @richardjubla 

Die Erkenntnisse und das weitere Vorgehen will ich in diesem Kommentar festhalten.
Nach Aufwandschätzung werde ich ein neues Umsetzungsticket mit den genauen Anforderungen eröffnen und diese Diskussion hier schliessen. Bis dann darf hier gerne noch weiter diskutiert und Rückgemeldet werden.

#### Ausgangslage:
- Für die Anmeldung von Personen in der NDS wird weiterhin die AHV-Nummer benötigt.
- Zukünftig wird diese jedoch nur noch für die erste Meldung einer Person in einer Organisation benötigt. Bei weiteren Events in der gleichen Organisation braucht es die AHV-Nummer nicht mehr zwingend.
- Für das konstante speichern der AHV-Nummer in Hitobit fehlt die gesetzliche Grundlage. Auch eine Einwilligung der Eltern befähigt uns nicht, diese länger als zwingend notwendig zu speichern.


#### MVP-Hitobito:
- Auf Events wird eine neue Frage für die AHV Nummer bei den Anmeldeangaben hinzugefügt, Analog den "Bemerkungen".
  - Die Frage gibt es automatisch auf allen Events (Anlässe, Kurse, Lager).
  - Für die Frage hat es drei Bulletpoints zur Auswahl: "Obligatorisch", "Optional" und "Nicht angezeigt" analog den Kontaktangaben.
  - Per Default ist keine Option ausgewählt.
  - Damit der Event gespeichert werden kann muss zwingend eine Option ausgewählt werden.
  - Es gibt einen Hilfetext welcher pro Umgebung ausgefüllt werden kann.
- Sämtliche Anmeldeangaben werden nach einer gewissen Zeit automatisch gelöscht.
  - Zeitraum ist pro Wagon definierbar.
  - Betrifft alle Fragen welche unter "Anmeldeangaben" erfasst werden.
  - Analog #2129 
- Alle NDS-Exporte werden angepasst, damit sie neu das Kursfeld AHV-Nummer ausgeben und nicht mehr das Feld AHV-Nummer in den Personendaten.
- Das AHV-Nummer Feld auf den Personendaten und sämtliche Inhalte darin werden gelöscht.
  - Cevi und Jubla haben auch noch ein Feld "AHV-Alt" dieses wird ebenfalls gelöscht.
- Abklären: Einmalige Migration aller aktiver Events.
  - Bei allen zum Zeitpunkt der Migration aktiven Events sollen die AHV-Nummern aus den Personendaten ins neue AHV-Feld auf den Events migriert werden.

**Comment by nchiapol** [comment]
@ThomasEllenberger Vielen Dank für die Zusammenfassung des Meetings, das entspricht so auch meiner Erinnerung. 

Hinweis von @tschuepbach: Wir haben nicht definiert was mit den Fragen vom Tab "Administrationsangaben" passiert. Wir haben nicht explizit darüber gesprochen. Aus meiner Sicht können wir die gleich behandeln wie die "Anmeldeangaben", das wäre wohl die einfachste Lösung. Auf jeden Fall sollte das Verhalten aber klar ersichtlich sein.

**Comment by ThomasEllenberger** [comment]
Dies klingt für mich einleuchtend und ich werde dies so in die Anforderungen übernehmen, insofern nicht gegenteilige Voten von @richardjubla oder @Michael-Schaer kommen.

**Comment by ThomasEllenberger** [comment]
Die Diskusion hier wird geschlossen.
Das Feature wird durch zwei neuen Issues umgesetzt:
https://github.com/hitobito/hitobito_youth/issues/58
https://github.com/hitobito/hitobito_youth/issues/59
