### ISSUE TITLE
Personen weitere Berechtigungen auf Gruppen vergeben (40h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#217]
Das DSJ will auf einer Ebene die Zugriffe noch genauer steuern. Am günstigen liesse sich das natürlich über die Rollen lösen, indem wir den Geschäftsstellenarbeitenden, die weitgehenden Berechtigungen entfernen und dafür an den geeigneten Orten eine Adressverwalter Rolle vergeben.

Trotzdem sollen wir eine alternative Möglichkeit schätzen.

* Ein zusätzliches Tab für Zugriffsberechtigung
* Alle Gruppen werden in einem Baum dargestellt.
* Person erhält weiter Zugriffsrechte auf alle ausgewählten Gruppen
* Beim Auswahl einer Gruppe werden Untergruppen automatisch zusätzlich ausgewählt.

![image](https://cloud.githubusercontent.com/assets/194364/24888717/94512024-1e65-11e7-9c11-b1516b13547d.png)

Dürfte man natürlich z. B. mit unsichtbaren Rollen abdecken.

Ergänzung:

* Personen mit bestimmten Rollen müssten nach wie vor Notizen und Tags vergeben können.

**Comment by codez** [comment]
Schätzung:
* GUI, um Adressverwaltungsrollen in den jeweiligen Gruppen zu erteilen/löschen: 1PT
* Berechtigungen dynamisch anpassen für alle entsprechenden Actions: 5PT
