### ISSUE TITLE
Haushalte abbilden für bessere Versände (32h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#218]
Immer wieder kommt die Frage, wie man Haushalte besser abdecken könnte, damit nicht unnötige Versände gemacht werden. Diskutiert in #106 und #164 .

Ein Vorschlag ist direkt die Haushalte abzubilden. Eine mögliche Darstellung ist wie im Mockup.

* Ein Haushalt kann beliebig viele Personen enthalten.
* Ein Person kann nur zu einem Haushalte gehören.
* Der Haushalt übernimmt die Angaben von der ersten Person, diese können aber überschrieben werden.
* Die Person erbt ab dann die Adressangaben vom Haushalt (aber nicht Telefonnummern oder anderes)
* Wenn eine Adresse aktualisiert wird, wird man gefragt,ob man alle akutalisieren will oder die Person aus dem Haushalt entfernen will.
* Name und Anrede werden automatisch für die Personen kombiniert. (Anschrift/Anrede dynamisch, da nicht alle Personen eines Haushalts in einem Export sein müssen)
* Versand E-Mailadressen werden kommagetrennt ausgegeben
* Rollen/Tags usw. werden in Exporten nicht ausgegeben können wohl nicht ausgegeben werden
* Im Export gibt einen Boolean-Wert Haushalt.
* Im Export kann gewählt werden, ob man Haushalte zusammengefasst ausgeben will. (macht nur Sinn für Adressexport nicht für Full export)
* Bestehendes "Mehrfachsendungen vermeiden" bei Etiketten wird ausgebaut.

<img width="875" alt="bildschirmfoto 2017-11-17 um 09 28 54" src="https://user-images.githubusercontent.com/194364/32937690-cda4521c-cb79-11e7-9f58-abe3ff618c5b.png">

Im beigelegten PDF ist eine mögliche Implementation
[Haushaltsadressierung.pdf](https://github.com/hitobito/hitobito/files/1481545/Haushaltsadressierung.pdf)

## Bemerkungen

* Die zusätzlichen Use Cases der PBS können damit nicht ohne weiteres abgedeckt werden. Wir prüfen, aber eine allgemeinere Lösung Personen zu verlinken.

**Comment by codez** [comment]
* Neuer CSV Export (weniger Felder, einfacheres Export Dropdown)
* Adresse weiterhin auf Personen, allenfalls gleichzeitig aktualisieren.
* Anschrift/Anrede dynamisch, da nicht alle Personen eines Haushalts in einem Export sein müssen.

**Comment by codez** [comment]
Schätzung: 4PT

**Comment by RolandStuder** [comment]
Optigem löst das wie folgt:

![familienadressierung_image002](https://cloud.githubusercontent.com/assets/194364/26829364/9b215978-4ac5-11e7-9cfb-4eff453d9f57.png)
![familienadressierung_image001](https://cloud.githubusercontent.com/assets/194364/26829365/9b2418a2-4ac5-11e7-97e7-0c025dfbc360.png)

**Comment by RolandStuder** [comment]
* Zum verknüpfen brauche ich Schreibrechte auf beiden Seiten.
* Beim verknüpfen wird die Adresse vom aktuellen Eintrag in den anderen reingeschrieben
* Aktualisiere ich eine Adresse muss ich wählen, ob ich die Person aus dem Haushalt entfernen will oder ob für alle die Adresse angepasst werden soll.
* Möglichkeit bieten, dass ich mich selbst aus dem Haushalt entfernen kann (sonst muss ich zu einer anderen Person springen und mich dort aus dem Haushalt löschen, das ist unlogisch).

![image](https://user-images.githubusercontent.com/194364/29922322-6c33ce9c-8e55-11e7-8315-bfb81887b7bc.png)

**Comment by UeliKurmann** [comment]
Die PBS hat die Anforderung, dass für Kinder auch die Eltern erfasst werden können. Dies, damit die Namen hinterlegt werden können und Verbände an einen Haushalt zusammengefasst werden können. Aus unserer Sicht kann es sinnvoll sein, diesen Issue um die Attribute für die Eltern zu erweitern. 
Die folgenden zusätzlichen Felder wären nötig:
- Vorname, Name (Vater, Mutter)
- Anrede für die Eltern

Beim Export kann man Wählen, ob an die "Kinder" oder die "Eltern" geschrieben werden soll.

**Comment by RolandStuder** [comment]
Danke @UeliKurmann, gemäss Takin sei das aber vor allem für den Emailversand wichtig, und dafür müsste die Lösung noch etwas anders aussehen. Aber wir haben diese Anforderungen grundsätzlich im Hinterkopf.

**Comment by adriananderegg** [comment]
Wir sind da schon abgestimmt. Zum Ausholen, es gibt in diesem Kontext folgende UseCases:

0. Adressierung des Kindes (bisherige Funktionalität)
1. Adressierung Haushalt um Papier und Porto sparen
2. Adressierung der Eltern eines Kindes via Post (Rechnungen)
a. ohne Zusammenzug pro Haushalt
b. mit Zusammenzug pro Haushalt
3. Adressierung NUR der Eltern via E-Mail für Infoversand (da Kind nicht zuverlässig)
4. Kontaktdaten der Eltern für Notfälle (primär Telefon, sekundär E-Mail)

andere, als Kombination von obigen
- Adressierung Eltern UND Kind via Post
Kann durch Kombination von 0 + 2 abgedeckt werden
- Adressierung Eltern UND Kind via E-Mail
Kann durch Kombination von 0 + 3 abgedeckt werden

Issue bisher deckt 1 ab. Mittels Namen und Vornamen könnte allenfalls auch 2a abdeckt werden. 
Falls ihr das anders lösen könnt, sind wir natürlich offen.

**Comment by nchiapol** [comment]
Im folgenden die Rückmedeldungen aus dem Cevi zur Variante vom 2017-11-17.
Grundsätzlich entspricht diese Umsetzung unseren Erwartungen.

Wir haben aber folgende Wünsche/Anforderungen:
  - Der "Zu Haushalt hinzufügen"-Link soll nur in der Editier-Maske angezeigt werden (unterhalb des Adressfelds).
  - Ist ein Kontakt in einem Haushalt, sollen sowohl in der normalen Ansicht wie im Editmodus die ANDEREN Mitglieder des Haushalts verlinkt werden. (Titel der Liste: "Im Haushalt mit")
  - Die Liste "Im Haushalt mit" braucht keine Löschknöpfe (Eine Person wird aus einem Haushalt entfernt, indem ihre Adresse geändert wird.)
  - Bei der Suche nach einem neuen Haushalt sollen die gleichen Angaben angeziegt werden wie in der allgemeiner Suche.
  - Die Möglichkeit 1 Zeile pro Haushalt ausgeben zu lassen muss für alle exportierbaren Formate (Excel, CSV, Etiketten; nicht für Mail-Adressen) bestehen. Sowohl bei Normalen Listen wie auch bei Abos.  
  - "Mehrfachsendungen vermeiden" soll nicht erweiter sondern durch "Nur eine Etikette pro Haushalt drucken" ersetzt werden. ("Mehrfachsendungen vermeiden" scheint uns zu wenig zuverlässig.)
  - Der Zusammenzug für Adressen muss auch für selbst-definierten Etiketten funktionieren (Scheint da hat "Mehrfachsendungen vermeiden" einen Bug).
  - Beim Export dürfen nur Personen berücksichtigt werden, die auch tatsächlich in dem entsprechenden Filter/Abo/Liste enthalten sind. Sind also Alice, Bob und Charlie in einem Haushalt aber nur Alice und Bob in meiner Gruppe, so darf Charlie nicht im Export auftauchen. 
  - Beim Ändern der Adresse einer Person in einem Haushalt, darf im Prompt (Seite 7 im PDF) 
die Option "Alle Adressen ändern" nur angezeigt werden, wenn die ändernde Person
schreibrechten auf allen betroffenen Kontakten hat. Sonst sollte stattdessen einen Hinweis 
angezeigt werden, im Sinne von "Du hast keine Schreibrechte an folgenden Personen in diesem Haushalt: ..."
  - Aktuell hat der Cevi Felder "Name Eltern" und "Anrede Eltern" beide sollten mit "Empfehlung: Haushalte verwenden" markiert werden. (Text auf Editier-Mask analog zu "Wird als Login verwendet") Es macht unserer Meinung nach mehr Sinn, hier in Zukunft die Eltern nun als echten Kontakt zu erfassen.

Die Funktionalität der "Personenverknüpfung" ist für uns im Moment nicht prioritär. Das scheint ziemlich kompliziert und hat wohl viel mühsame Spezialfälle. Im 
Gespräch hatten wir folgende Gedanken:
  - Das sollte unabhängig von Haushalt sein, Bsp: Haushalt mit Vater+neuer Partnerin, separate 
Adresse Mutter
  - Beim Zusammenzug der Adressen für einen Haushalt möchten wir dann Entscheiden können, ob alle Namen oder nur die Eltern im Haushalt angeschrieben werden.
  - Sind Beziehungen abgebildet wäre es interessant, bei einer Liste mit Kindern Briefe/Mails an die verlinkten Eltern zu senden (evtl. mehrere Briefe falls mehrere Kontaktpersonen mit unterschiedlichen Adressen erfasst wurden).

Allgemein scheint die Verlinkungs-Variante aus #410 hier in die richtige Richtung zu gehen. Im Rahmen des bestehenden Vertrags mit der Region Bern, soll hier aber nur der Teil Haushalt implementiert werden.

**Comment by RolandStuder** [comment]
@nchiapol 

> Im folgenden die Rückmedeldungen aus dem Cevi zur Variante vom 2017-11-17.
> Grundsätzlich entspricht diese Umsetzung unseren Erwartungen.

Danke für die Rückmeldungen

> Wir haben aber folgende Wünsche/Anforderungen:
>   - Der "Zu Haushalt hinzufügen"-Link soll nur in der Editier-Maske angezeigt werden (unterhalb des Adressfelds).

Ok, können wir so machen, ist tatsächlich etwas konsistenter wenn wir es so gestalten. Insgesamt fände ich es eben aber begrüssenswert, wenn wir mehr und mehr direkt manipulieren könnten, wie bei den Tags, aber hier macht es wohl Sinn. Eine ähnliche Funktionalität bei der PBS ist auch so umgesetzt worden.

>   - Ist ein Kontakt in einem Haushalt, sollen sowohl in der normalen Ansicht wie im Editmodus die ANDEREN Mitglieder des Haushalts verlinkt werden. (Titel der Liste: "Im Haushalt mit")

Bin nicht sicher, ob ich das richtig verstanden habe. Wir zeigen sicher im Editmodus und im Showmodus die anderen Personen an. Ein Link ist da natürlich auch vorgesehen, wohl aber abhängig davon, ob man Leserechte auf die andere Person hat.

>   - Die Liste "Im Haushalt mit" braucht keine Löschknöpfe (Eine Person wird aus einem Haushalt entfernt, indem ihre Adresse geändert wird.)

Hier bin ich etwas unsicher, inhaltlich macht es zwar Sinn und ist mit dem Prompt nachvollziehbar. Aber es ist nicht einfach zu erlernen  / entdecken. Wie kann ich als Benutzer verstehen, dass ich die Adresse ändern muss und damit die Person aus dem Haushalt entfernen kann. Evtl. wäre die Checkbox wie [hier](https://user-images.githubusercontent.com/194364/29922322-6c33ce9c-8e55-11e7-8315-bfb81887b7bc.png) doch etwas einfacher zu verstehen.

>   - Bei der Suche nach einem neuen Haushalt sollen die gleichen Angaben angeziegt werden wie in der allgemeiner Suche.

OK.

>   - Die Möglichkeit 1 Zeile pro Haushalt ausgeben zu lassen muss für alle exportierbaren Formate (Excel, CSV, Etiketten; nicht für Mail-Adressen) bestehen. Sowohl bei Normalen Listen wie auch bei Abos.  

Wir haben vor allem an die Abos gedacht, aber macht natürlich eigentlich nur Sinn das überall zu machen. Ok.

>   - "Mehrfachsendungen vermeiden" soll nicht erweiter sondern durch "Nur eine Etikette pro Haushalt drucken" ersetzt werden. ("Mehrfachsendungen vermeiden" scheint uns zu wenig zuverlässig.)

Ja, das ist so vorgesehen, wir wollen nicht zwei Funktionen, die denselben Zweck erfüllen.

>   - Der Zusammenzug für Adressen muss auch für selbst-definierten Etiketten funktionieren (Scheint da hat "Mehrfachsendungen vermeiden" einen Bug).

Ok. Danke für den Hinweis.

>   - Beim Export dürfen nur Personen berücksichtigt werden, die auch tatsächlich in dem entsprechenden Filter/Abo/Liste enthalten sind. Sind also Alice, Bob und Charlie in einem Haushalt aber nur Alice und Bob in meiner Gruppe, so darf Charlie nicht im Export auftauchen. 

Das ist so vorgesehen, die Anschrift wird aus den Personen einer Liste zusammengeführt. Vornamen und gleichen Nachnamen sollen sinnvoll zusammengesetzt werden, Z. B. Urs, Ben und Nathalie Bregy. Evtl. müssen wir hier die Vornamen auf eine maximale Länge beschränken, weil bei zu langen Zeilen irgendwann keine sinnvolle Etikette mehr gedruckt werden kann.

>   - Beim Ändern der Adresse einer Person in einem Haushalt, darf im Prompt (Seite 7 im PDF) 
> die Option "Alle Adressen ändern" nur angezeigt werden, wenn die ändernde Person
> schreibrechten auf allen betroffenen Kontakten hat. Sonst sollte stattdessen einen Hinweis 
> angezeigt werden, im Sinne von "Du hast keine Schreibrechte an folgenden Personen in diesem Haushalt: ..."

Ja, das macht Sinn. Wir hatten überlegt, eigentlich nur eine Verknüpfung zuzulassen, wenn ich auch Schreibrechte auf die neu verknüpfte Person habe. Da müssen wir ein bisschen schauen, was sich einfach umsetzen lässt.

>   - Aktuell hat der Cevi Felder "Name Eltern" und "Anrede Eltern" beide sollten mit "Empfehlung: Haushalte verwenden" markiert werden. (Text auf Editier-Mask analog zu "Wird als Login verwendet") Es macht unserer Meinung nach mehr Sinn, hier in Zukunft die Eltern nun als echten Kontakt zu erfassen.

Ok, können wir gerne ergänzen.


> Die Funktionalität der "Personenverknüpfung" ist für uns im Moment nicht prioritär. Das scheint ziemlich kompliziert und hat wohl viel mühsame Spezialfälle. Im Gespräch hatten wir folgende Gedanken:

Genau, es wird da ein bisschen kompliziert, weil sehr viele Fälle entstehen können, wenn man denn soll damit inteligente Exporte machen können.

Eine Frage die noch etwas offen blieb war die vom Import. Der ist nicht in der Offerte enthalten, es wäre gut, wenn der Cevi Region Bern einen kleinen Beispieldatensatz aus der bestehenden Software bereitstellen könnte. Damit wir sehen können, wie sich das einfach machen liesse.

**Comment by nchiapol** [comment]
@RolandStuder 

> Insgesamt fände ich es eben aber begrüssenswert, wenn wir mehr und mehr direkt manipulieren könnten.

Tönt grundsätzlich sinnvoll. Aus meiner Sicht müsste das aber alles auf einmal angepasst werden, so dass das Interface trotzdem konsistent bleibt.

> Wir zeigen sicher im Editmodus und im Showmodus die anderen Personen an. Ein Link ist da natürlich auch vorgesehen, wohl aber abhängig davon, ob man Leserechte auf die andere Person hat.

Das Entspricht unseren Vorstellungen. Uns gings auch darum, dass nur die anderen Angezeigt werden (im PDF ist auch Sarah noch einmal aufgeführt) 

> Wie kann ich als Benutzer verstehen, dass ich die Adresse ändern muss und damit die Person aus dem Haushalt entfernen kann. Evtl. wäre die Checkbox wie hier doch etwas einfacher zu verstehen.

Zusätzlich zum Prompt eine Checkbox wäre sicher auch ok. Was wir nicht möchten, sind Löschknöpfe für die anderen Personen wie im PDF. Ich sollte eine Person nur aus dem Haushalt entfernen können, wenn ich diese Person am berabeiten bin. (entsprechend auch nur im Edit-Mode)

> Das ist so vorgesehen, die Anschrift wird aus den Personen einer Liste zusammengeführt. 

Perfekt

> Vornamen und gleichen Nachnamen sollen sinnvoll zusammengesetzt werden, Z. B. Urs, Ben und Nathalie Bregy. Evtl. müssen wir hier die Vornamen auf eine maximale Länge beschränken, weil bei zu langen Zeilen irgendwann keine sinnvolle Etikette mehr gedruckt werden kann.

Tönt sinnvoll.

> Wir hatten überlegt, eigentlich nur eine Verknüpfung zuzulassen, wenn ich auch Schreibrechte auf die neu verknüpfte Person habe.

Und was passiert, wenn ich die schreibrechte auf jemanden verliere? Kann ich "meinen" Kontakt dann nicht mehr aus dem Haushalt entfernen? Wir würden es vorziehen, wenn fürs Verknüpfen Schreibrechte an der Betroffenen Person genügen.

> Eine Frage die noch etwas offen blieb war die vom Import.
Ich weiss nicht, was ihr da besprochen hattet. Ich habe mich gestern ncoh einmal mit den Verantwortlichen aus Bern besprochen. Vorerst brauchen wir da nichts. (Wir werden das zuerst intern besprechen und melden uns wieder, sollten wir eure Unterstützung brauchen. Grundsätzlich glaube ich aber, dass wir das wieder selbst erledigen können.)

**Comment by RolandStuder** [comment]
@amaierhofer Hier eine Zusammenstellung, wie es jetzt für die Etablierung eines Haushalts oder der Entfernung einer Person funktionieren soll.

PDF Prototyp mit Verlinkung:
[Haushaltsadressierung v2.pdf](https://github.com/hitobito/hitobito/files/1698235/Haushaltsadressierung.v2.pdf)
