### ISSUE TITLE
Migration Pipelines

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito#2200]
Im Rahmen der Jenkins CentOS 7 VM, welche abgelöst wird, sollen die bestehenden Hitobito-Pipelines migriert werden.
Dieses Ticket soll sicherstellen, dass diese Pendenz nicht vergessen geht.
Zudem soll das weitere Vorgehen definiert werden.
Daraus resultierende Tasks können gleich in weiteren Issues festgehalten werden.

**Comment by carlobeltrame** [comment]
Duplikat von #1914, bzw. wird die Migration zu GitHub Actions dort bereits sehr aktiv bearbeitet.
