### ISSUE TITLE
INVOICES: Absendername E-Mail Rechnungen wird nicht korrekt dargestellt.

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#2203]
### Neue Spezifikation
Beim Issue #1839 ging es darum einen manuellen Absendernamen eintragen zu können, dieser wurde im 'Sender' Header der Email gesetzt. 

Der Bug war ein Problem das Der Sendername sanatized wurde. Während dem Umsetzen hat sich herausgestellt dass
der 'Sender' Header einfach der technische Absender der Email ist, angezeigt im Mail Client wird immer nur der 'From' Header.
Da gewünscht wird das der manuell eingetragene Absendername im Mail Programm der Nutzer als Absender angezeigt wird. Überschreiben wir neu den 'From' Header und nicht den 'Sender' 

### Aktuelles Verhalten

In Issue #1893 wurde das Feature umgesetzt, dass man manuell einen Email Absendernamen für Rechnungsemails vergeben kann.
Dies scheint aktuell nicht korrekt zu funktionieren.
Ein weiterführendes Problem scheint zu bestehen, wenn der absendername ein Sonderzeichen (in diesem fall ein "è" ) beinhaltet wird dieses nicht korrekt dargestellt.

### Gewünschtes Verhalten

Der unter "E-Mail Absendername" eingetragene Name sollte bei einer per Mail versendeten Rechnung dem Kunden als Absendername angezeigt werden.

### Schritte zu reproduzieren

1. Auf den Rechnungseinstellungen einen E-Mail Absendername
 eintragen.
2. Rechnung vom entsprechenden Layer aus stellen und per Email versenden.
3. Anzeigename ist nicht der eingetragene Name.

### Wann ist der Fehler aufgetreten?

25.09.2023

### hitobito version

1.30.0

### Organisation

SWW

### Screenshots, weiterer Kontext

![grafik](https://github.com/hitobito/hitobito/assets/100761305/bba0a4bc-14ba-4d6f-8d03-8f2383573e26)
![grafik](https://github.com/hitobito/hitobito/assets/100761305/f757cc22-fbd1-4d8b-a8b3-92d456d90859)
![grafik](https://github.com/hitobito/hitobito/assets/100761305/91153df8-52bd-4653-84bc-7c121d96e4be)

**Comment by daniel-illi** [comment]
Dieses Ticket ist noch nicht genau genug spezifiziert und entsprechend noch nicht korrekt implementiert: es wird ein laut RFC 5322/6854 ungültiger Header generiert was vermutlich je nach Mail Client zu einem unerwünschten Verhalten führt.

Siehe https://github.com/hitobito/hitobito/pull/2206#pullrequestreview-1651956269
