### ISSUE TITLE
Persistierte Filter bearbeitbar machen (6h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#223]
Ein Benutzer kann einen persistierten Filter auch bearbeiten. Neu kann ein Benutzer einen bestehenden Filter bearbeiten mit Klick auf den neuen Menüpunkt Bearbeiten (edit-icon).

* [x] Zwei Punkte in Untermenu
  * [x] Edit Icon und Text "Bearbeiten"
  * [x] Trash Icon und Text "Löschen"
* [x] Edit führt zu Bearbeitungsformular vom Filter
* [x] Name in Formular anpassbar.
* [x] Button "Suchen" im Bearbeitungsmodus nicht sichtbar.
  
Referenz:
![image](https://cloud.githubusercontent.com/assets/194364/25118806/12166a0c-2418-11e7-835f-e92d59fa935c.png)

**Comment by psunix** [comment]
fixed pre-selected roles, qualifications
review ok
