### ISSUE TITLE
Ausbildungs-Seite: HTML-Tags

### ISSUE THREAD

**Issue by maede97** [hitobito/hitobito#2234]
### Aktuelles Verhalten

Navigiere auf einer Abteilung auf den Tab "Ausbildung". Die Spalte "Qualifikation" zeigt nun HTML-Escaped Content. Die Links zu Anmeldungen sind nicht mehr brauchbar und können auch nicht mehr angeklickt werden.

### Gewünschtes Verhalten

Die Links funktionieren wieder.

### Schritte zu reproduzieren

1. Anmelden (bei Cevi PRODUKTIV, Integration, aber auch bei PBS Integration)
2. Auf eine Abteilung wechseln
3. Auf "Ausbildung" klicken

### Wann ist der Fehler aufgetreten?

24.10.2023

### hitobito version

1.31.1

### Organisation

Cevi, PBS

### Screenshots, weiterer Kontext

![Screenshot 2023-10-24 202115](https://github.com/hitobito/hitobito/assets/14098502/aa4102da-214d-45a7-879d-702f5cfdf635)

Danke @wp99cp fürs melden!

**Comment by richardjubla** [comment]
Kann ich auf [Version 1.31.0](https://jubla.puzzle.ch/changelog) bestätigen:
![image](https://github.com/hitobito/hitobito/assets/95908537/e1b392f7-f455-491d-94d3-8382bb3452a4)

Ist in [Version 1.28.30.2](https://db.jubla.ch/changelog) nicht vorgekommen:
![image](https://github.com/hitobito/hitobito/assets/95908537/7a1618db-0940-4bb4-9f82-5120519c002e)
