### ISSUE TITLE
EVENT: Temporäre Felder (Bemerkungen/AHV Nr.)

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito#2238]
### User Story

Als Event-Verantwortlicher (Lager, Anlass, Kurs, etc.) möchte ich die Bedingungen für das “Recht auf vergessen” automatisch einhalten können. Bestimmte Informationen wie zum Beispiel die Bemerkungen (event_participation_additional_information) oder die AHV-Nr. ((event_participation_contact_data[ahv_number]) sollen nicht mehr permanent gespeichert werden. Diese Informationen werden nach einer bestimmten Zeit (wenige Monate) nach dem Event (event_dates_attributes_0_finish_at) aus den Anmelde-Daten für einen Event gelöscht und stehen dann nicht mehr zur Verfügung. Allen Akteuren (Event-Verantwortlicher, Teilnehmer*in, Coach, etc.) ist dieser Umstand bewusst oder durch den Anmeldeprozess ersichtlich (UX). Damit kann ich die rechtliche Nachweispflicht (Wer hat an einem Kurs teilgenommen) und die zum Kurs verfügbaren Anmelde-Daten (Bemerkungen, Allergien, AHV-Nr.) mit meinen datenschutzrechtlichen Bestimmungen automatisch einhalten (Privacy by Design). Damit wäre man einen Schritt näher, dass bestimmte Event-Informationen eines User/Profil wie die AHV-Nr. nur noch temporär in einer Hitobito-Instanz vorhanden sind.

### Aspekte
-  Dieses Feature/Story nimmt die Bedürfnisse von #2162#issuecomment-1653873580 und #2129 auf
- Die Entfernung oder Löschung der AHV Felder (Jubla person_ahv_number_old / person_ahv_number) ist nicht Bestandteil dieser Story. Die AHV-Daten (aus dem Profil) solle nach Möglichkeit weiterhin in den Event übernommen werden. Jede Hitobito-Instanz soll  so selbständig für sich in einem Change anpassen, ob und wann die AHV-Daten (oder andere Felder) in Zukunft nicht mehr im Profil gespeichert werden können. 
~- In der Annahme, das dies den Umfang stark beeinflusst: Temporäre Felder sind fix (Change) definiert und können nicht individuell (User defined) bestimmt werden. Alternativ wäre interessant alle Felder mit der Option "temporär" auszustatten (Diese Option wäre dann Standard).~
- Alle die zusätzlichen Fragen des Events (Feld-Informationen im  Tabs "Anmeldeangaben" und "Administrationsangaben") werden automatisch nach Ablauf der Frist gelöscht. (Hitobito-Instanzen können eine eigene Frist setzten oder den Check deaktivieren oder überspringen lassen?)
- Die Profil-Felder und die Temporären Felder müssen entkoppelt sein. ~Bisher gehen die Informationen vom Profil in den  Event über (und auch zurück?)~. Im Event sind Profil-Informationen lediglich verknüpft. Obwohl ein Event (und deren berechtigte Rollen) nur auf bestimmte Daten zugriff erhalten und nicht das Profil selbst, kommen die Daten aus dem Profil selbst und sind nicht im Event gespeichert.  Zukünftig muss es zum Beispiel auch möglich sein, dass eine AHV-Nr. nur noch für eine Event-Anmeldung abgefragt und verfügbar wird, ohne dass dieses Feld noch irgendwo sonnst in der Datenbank vorkommt. 
- Alle Export-Funktionen prüfen
- Auch vergangene Events einbeziehen: Die Lösung soll und darf alle Events betreffen. Dies bedeutet, dass auch Event-Anmeldungen (inkl. PDF?) aus vergangenen Jahren mit einem Release bereinigt werden.

**Konfig-Daten**
- Umsetzung auf Ebene: Core  ~~/ Youth~~ (Begründung:  https://github.com/hitobito/hitobito/issues/2238#issuecomment-1814320018)
- Zukünftig temporäre Felder: event_participation_additional_information / event_participation_contact_data[ahv_number] /  (Individuelle Profil Daten wie Haupt-E-Mail, Vorname, Nachname, Übername, Firmenname, Adresse, PLZ, Ort, Land, Geschlecht, Geburtstag, Telefonnummern, Sprache, Nationalität gemäss J+S, AHV-Nummer, J+S-Nummer, Weitere E-Mails, Social Media) oder optional alle Event-Felder individuell (event_admin_questions_attributes_000000000_question)
- Zeit zwischen Event-Enddatum und Löschung: 4 Monate
- Hilfstext(e): Ja

### Definition of Done 

- [ ] durch Puzzle zu verifizieren und/oder zu ergänzen
- Event-Informationen für die Felder "Bemerkungen" und "AHV-Nr." sind nur noch wenige Monate nach dem Event verfügbar
- Es darf nur das letzte Datum für die Löschung berücksichtigt werden (Events können mehrere Daten haben)
- Allen Akteuren (Event-Verantwortlicher, Teilnehmer*in, Coach, etc.) kann durch geeignete Massnahmen (Hilfstext, Hinweis, UX/GUI) die temporäre Speicherung klargemacht werden.
- Die Lösung ist so beschreiben, umgesetzt und nachvollziehbar, dass sie von Menschen auf der Stage-/Produktivumgebung getestet und ohne Code-/Programmierkenntnisse nachvollzogen werden kann.
- Zeitplan (Change, Test, Relese) 
- Check: Dokumentation, Anleitungen, Tests, etc.

**Zusage von Seiten jubla**
Die Jubla/FG Datenbank hat sich dieses Thema vorgenommen und möchte es umsetzten. Wir sind gewillt, dieses Feature für uns und auf ebene youth/core umsetzten zu lassen. Voraussetzung ist eine Offerte im 2023.  
Plan/Erwartungshaltung:
- Eine konsolidierte Haltung (Story) als Grundlage für eine Offerte wird erstellt
- Jubla kann Offerte im 2023 in Auftrag geben (und/oder Finanzierung mit Youth-Community besprechen)
- Falls es das gibt, koordiniert Puzzle/Hitobito die Definition der Felder der einzelnen Youth-Mitglieder etc.
- Feature kann im Inkrement 1/24 oder 2/24 umgesetzt werden
- Hitobito-Instanzen können individuelle folge Aufträge/Changes anhängen

Bisher wurden die Bemerkungen zu einem Event für immer gespeichert. Ebenso die AHV-Nr. im Profil und in der Event-Anmeldung.
Neu sollen diese Informationen in einem Event nach einer gewissen Zeit nach dem Event automatisch gelöscht werden

# ToDo

- [ ] tbd

### Mockup/MVP

Dieses Mockup zeigt die Möglichkeit/Beispiel, Event-Felder zu temporären Feldern zu machen:
![image](https://github.com/hitobito/hitobito/assets/95908537/e98d95f3-c2b0-4938-a374-a16dbe7efb60)

Dieses Mockup zeigt die Möglichkeit/Beispiel, wie Event-Daten als temporär gekennzeichnet werden könnten:
![image](https://github.com/hitobito/hitobito/assets/95908537/4170b14a-ce25-4d75-80db-bff9d41cdf43)
Einfacher: Alle temporären Daten mit einem * kennzeichnen oder so.

Dieses Mockup zeigt die Möglichkeit/Beispiel von Hilfstext(en) beim Anmeldeprozess
![image](https://github.com/hitobito/hitobito/assets/95908537/5c611eaa-6e98-4fd0-b8e7-0992fb5a31c0)

Dieses Mockup zeigt die Optionen beim Erstellen/Bearbeiten eines Event
<img width="854" alt="image" src="https://github.com/hitobito/hitobito/assets/95908537/ef6d562d-e7f8-4c20-b9ca-2f0ecb74cf8d">
Ist nur ein sehr einfaches/schlechtes Beispiel: Dem Event-Verantwortlichen soll klar werden, dass er nur temporäre Daten bekommen wird.

**Comment by richardjubla** [comment]
Lieber @nchiapol und @Michael-Schaer 
Diese Story/Issue für euch zur Information und als Anfrage zum mitverfolgen. Ich bitte um eine Reaktion (gesehen?) und mittelfristig um eine Einschätzung auf youth-Ebene.

Lieber @thomasellenberger
Bitte um ein weiterverfolgen bzw. youth-Koordination der Story. Hilfreich erachte ich auch eine Rückmeldung oder Einschätzung aus technischer Sicht. Gibt es "Regeln" oder optimalere Ansätze welche zu beachten wären. Welche Aspekte machen die Story besonders anfällig für Komplexität oder Folgekosten?

Merci!

**Comment by nchiapol** [comment]
@richardjubla Vielen Dank fürs Aufbereiten. Ich habe das Issue gesehen und das sieht soweit gut aus. Ich unterstütze, dass das auf Ebene youth oder gar im Core umgesetzt wird. Finanziell beteiligen können wir uns allerdings dieses Jahr wohl nicht mehr.

Anregungen meinerseits:
  * Um die Komplexität klein zu halten, würde ich empfehlen, dass neben dem Bemerkungsfeld (https://user-images.githubusercontent.com/95908537/278357477-5c611eaa-6e98-4fd0-b8e7-0992fb5a31c0.png) einfach alle die zusätzlichen Fragen des Events (Tabs "Anmeldeangaben" und "Administrationsangaben") automatisch löschen. So können alle relevanten Felder einfach aus dem Profil gelöscht und dort ergänzt werden (z.B. mittels einem als "Kopiervorlage" verwendeten Event oder mit bei allen Events automatisch erstellten Fragen.)
  * Um temporäre Felder zu markieren würde ich ein Sand- oder Stoppuhr-Icon vorschlagen, ,it dem ausführlichen Text als Tooltip.

**Comment by richardjubla** [comment]
> @richardjubla Vielen Dank fürs Aufbereiten. Ich habe das Issue gesehen und das sieht soweit gut aus. Ich unterstütze, dass das auf Ebene youth oder gar im Core umgesetzt wird. Finanziell beteiligen können wir uns allerdings dieses Jahr wohl nicht mehr.
> 
> Anregungen meinerseits:
> 
> * Um die Komplexität klein zu halten, würde ich empfehlen, dass neben dem Bemerkungsfeld (https://user-images.githubusercontent.com/95908537/278357477-5c611eaa-6e98-4fd0-b8e7-0992fb5a31c0.png) einfach alle die zusätzlichen Fragen des Events (Tabs "Anmeldeangaben" und "Administrationsangaben") automatisch löschen. So können alle relevanten Felder einfach aus dem Profil gelöscht und dort ergänzt werden (z.B. mittels einem als "Kopiervorlage" verwendeten Event oder mit bei allen Events automatisch erstellten Fragen.)
> * Um temporäre Felder zu markieren würde ich ein Sand- oder Stoppuhr-Icon vorschlagen, ,it dem ausführlichen Text als Tooltip.

Danke @nchiapol 
Deine Hinweise (insb. zu den zusätzlichen Fragen) habe ich gerne aufgenommen. So wie es aussieht ist es OK, dass diese Infos "alle" temporär werden. Die Umsetzung scheint mir dann auch einfacher.

**Comment by ThomasEllenberger** [comment]
Vielen Dank für das sehr ausführliche und detaillierte Issue.

Für mich sieht dies nach einer Erweiterung des issues der PBS aus, welches wir aktuell im Core umsetzen: #2129 
Gerne würden wir desshalb auch dieses Issue im Core umsetzen.
Eine Frage wäre für mich dann ob wir dieses einfach ausweiten, und definieren welche Felder temporär sein sollen. Mann könnte dann pro Umgebung einstellen wie lange nach Anlässen dies gelöscht werden soll.
Oder müsste auch pro Umgebung definierbar sein, welche Felder als temporär gelten?

**Comment by richardjubla** [comment]
> Eine Frage wäre für mich dann ob wir dieses einfach ausweiten, und definieren welche Felder temporär sein sollen. Mann könnte dann pro Umgebung einstellen wie lange nach Anlässen dies gelöscht werden soll.


Lieber @ThomasEllenberger 

In meiner Story mache ich dazu folgenden Vorschlag:
Zukünftig temporäre Felder: event_participation_additional_information / event_participation_contact_data[ahv_number] / (Individuelle Profil Daten wie Haupt-E-Mail, Vorname, Nachname, Übername, Firmenname, Adresse, PLZ, Ort, Land, Geschlecht, Geburtstag, Telefonnummern, Sprache, Nationalität gemäss J+S, AHV-Nummer, J+S-Nummer, Weitere E-Mails, Social Media) oder optional alle Event-Felder individuell (event_admin_questions_attributes_000000000_question)

Werden zu viele Individuelle Profil Daten gelöscht, kann dann später keine Zuordnung gemacht werden. Niemand kann mehr herausfinden oder beweisen, dass diese Anmeldung (eigener Datensatz) zu einem Profil auf der Datenbank gehört. (Das wäre nicht unsere Absicht)
Das Interesse der Jubla ist, lediglich die "Unwichtigen" Daten (Bemerkungen) und solche mit potenziell heikleren Daten (AHV Nr. / J+S-Nummer) entfernen. Die Hoheit dieser Daten ist somit wieder im Profil und explizit nicht mehr in Event-Datensätzen.

Aktuell sehe ich folgenden Konsens für die Temporären Felder:
- Alle zusätzlichen Fragen des Events (Tabs "Anmeldeangaben" und "Administrationsangaben") werden temporär
-  event_participation_additional_information / event_participation_contact_data[ahv_number] 
 
> Oder müsste auch pro Umgebung definierbar sein, welche Felder als temporär gelten?
Hier ist unser Wunsch, die Komplexität (Kosten) zu berücksichtigen. Idee: Eine Config-Datei/Parameter welche festlegt, welche Profil-Daten Temporär sein sollen. 

Was nicht weiter verfolgt wird:
- Der User (Event-Ersteller) soll nicht mehr selber festlegen können, welche Daten temporär sein sollen.

**Comment by tschuepbach** [comment]
Wir AV's haben gestern noch folgendes dazu diskutiert:

- Wie bereits von Carbon vorgeschlagen, soll bei Kursen und Lagern die AHV-Nummer bei den Anmeldeangaben als automatisch erstellte Frage abgefragt werden. (Da kann man sich im Cevi-Wagon bedienen, wir haben bei den Kursen bereits eine solche vordefinierte Frage).
Der Text dieser Frage muss editierbar sein, Pflichtangabe = true/false auswählbar und lösch- bzw. ausblendbar sein (je nach Export-Funktionalität). Die dort eingegebene AHV-Nummer muss validiert werden, analog wie heute in den Personenstammdaten.

- Die Exporte sollen sich explizit auf das neu definierte AHV-Feld beziehen. Im besten Fall wird die AHV-Nummer nur bei den NDS-Exporten berücksichtigt, bei allen anderen Exporten (Spaltenauswahl, Alle Angaben, etc.) nicht.

Alles andere wurde bereits erwähnt.

**Comment by richardjubla** [comment]
> Wir AV's haben gestern noch folgendes dazu diskutiert:
> 
> * Wie bereits von Carbon vorgeschlagen, soll bei Kursen und Lagern die AHV-Nummer bei den Anmeldeangaben als automatisch erstellte Frage abgefragt werden. (Da kann man sich im Cevi-Wagon bedienen, wir haben bei den Kursen bereits eine solche vordefinierte Frage).
>   Der Text dieser Frage muss editierbar sein, Pflichtangabe = true/false auswählbar und lösch- bzw. ausblendbar sein (je nach Export-Funktionalität). Die dort eingegebene AHV-Nummer muss validiert werden, analog wie heute in den Personenstammdaten.
> * Die Exporte sollen sich explizit auf das neu definierte AHV-Feld beziehen. Im besten Fall wird die AHV-Nummer nur bei den NDS-Exporten berücksichtigt, bei allen anderen Exporten (Spaltenauswahl, Alle Angaben, etc.) nicht.
> 
> Alles andere wurde bereits erwähnt.

Lieber @tschuepbach 

Die automatischen erstellten Fragen sind mir nur bei Kursen bekannt. Für Lager wurde mir von Seiten Hitobito mitgeteilt, dass dies ein zusätzliches Feature wäre. Auch aus diesem Grund ist es nicht als Anforderung in der Story. Ich kann nicht abschätzen wie die Umsetzung erfolgen kann, der Vorschlag sieht aber in erster Linie eine Umsetzung im Core vor ohne dabei partikulare (bereits bestehende) Umsetzungen in einzelnen Wagons zu berücksichtigen. Ich hoffe die Story bildet das so ab.

Es soll aus meiner Sicht kein neu definierte AHV-Feld geben. Das bestehende wird weiter genutzt und eben nur temporär verwendet.

**Comment by richardjubla** [comment]
Als noch unbestätigte Information aus der Ecke NDS: Das Baspo soll/ist sich seiner Rolle als Speicher-Ort für die AHV Nr. bewusst. Die Verwaltung der Nummer (zu gemeldeten Profilen/Teilnehmer*innen) soll in der neuen NDS passieren. Damit sinkt der Druck oder das Problem, dass die AHV Nr. für diesen Fall in Hitobito verbleiben müsste. 
Nach einem Lager sollen die Daten umgehend bei der NDS importiert werden. Ein Import von unvollständigen Daten (nicht alle AHV Nr.) soll dennoch gemacht und nachträglich vervollständigt (oder abgeglichen) werden können. AHV-Daten sind zukünftig als statische Daten nur noch in der NDS vorgesehen. (und rechtlich auch an diesem Ort korrekt)

Die Jubla verfolgt weiterhin den gefassten Entscheid: 
1. AHV Nr. zu temporärem Feld machen (auch nachträglich alte Events bereinigen)
2. AHV Nr. als (statisches) Profil-Feld entfernen (nicht Teil dieses Ticket)

**Comment by richardjubla** [comment]
Ich schliesse dieses Ticket:


- **Bemerkungen** können automatisch gelöscht werden, siehe https://github.com/hitobito/hitobito/issues/2129 und auch die aktuelle Erweiterung hier https://github.com/hitobito/hitobito_sac_cas/issues/367
- Die **Verschiebung der AHV Nr.** in den Event erfolgt auf Ebene Youth mit folgenden zwei Stories: https://github.com/hitobito/hitobito_youth/issues/58 https://github.com/hitobito/hitobito_youth/issues/59

**Comment by ThomasEllenberger** [comment]
Werden Teile von diesem issue evtl. durch https://github.com/hitobito/hitobito_sac_cas/issues/367 bereits umgesetzt?

**Comment by richardjubla** [comment]
> Werden Teile von diesem issue evtl. durch [hitobito/hitobito_sac_cas#367](https://github.com/hitobito/hitobito_sac_cas/issues/367) bereits umgesetzt?

@ThomasEllenberger 
Ich gehe davon aus, dass es für die Bemerkungen (event_participation_additional_information) oder sogar generell für die Kursfragen Lösungen gibt. Wichtig wäre, dass EVENT (und nicht nur Kurse) gemeint sind.

Mit der Offerte/Umsetzung haben wir uns ja mit https://github.com/hitobito/hitobito_youth/issues/58 https://github.com/hitobito/hitobito_youth/issues/59 klar auf die AHV-Nr. fokussiert. Meine Aussage zum Schliessen von diesem Ticket müsste weiterhin korrekt sein: https://github.com/hitobito/hitobito/issues/2238#issuecomment-2074305936
