### ISSUE TITLE
PEOPLE: Notfallkontakte

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#2247]
DRAFT

Es soll möglich sein das eine Person einen oder mehrere Notfallkontakte hinterlegen kann.

- Dies kann ein externer Kontakt sein oder eine Person aus Hitobito
- Datenschutz:
  - Wer kann diese Kontaktdaten lesen?

- Notfallkontakte sollen bei Personen Listen mit exportiert werden können

![image](https://github.com/hitobito/hitobito/assets/655627/5d130adb-1dc2-41a3-a51b-50b3791752bc)

# Tech-Spec

- ...

![image](https://github.com/hitobito/hitobito/assets/655627/c85389a2-f49d-40b3-8dc8-ee528433c23b)

# ToDo

- [ ] Migration erstellen
- [ ] Domainklasse erstellen oder anpassen
- [ ] Model/View/Controller anpassen
- [ ] Neues Feature mit FeatureGate deaktivierbar machen
- [ ] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by carlobeltrame** [comment]
Gehört das wirklich in den Core? Wie sieht es mit Datenschutz aus? Ist das eine Information die Organisationen abgesehen vom SAC wirklich brauchen und daher im neuen Datenschutzgesetz auch speichern dürfen? Oder machen wir einen Feature Toggle, mit dem das deaktiviert werden kann (und standardmässig deaktiviert ist)?

**Comment by nchiapol** [comment]
Ein paar Gedanken:
  * Bei Notfallkontakten ist es entscheidend, dass sie aktuell sind. Ist die Person da der richtige Ort? (Es geht da nicht nur darum, dass jemand gerade nicht erreichbar sein könnte - ist wäre auch sehr schlecht, wenn nach der Trennung der/die Ex als erstes über den Notfall informiert würde.) Ich würde diese Info analog zu den Gesundheitsangaben jeweils beim Anlass abfragen. (Und dort mit den gleichen Datenschutz-Prozessen schützen)
  * Grundsätzlich ist die Info auch für uns (Cevi bzw. allg. Jugendverbände) relevant. Bis jetzt sammeln wir die Info einfach auf Notfallblättern in Papierform.

**Comment by patrickuhlmann** [comment]
Die Verknüpfung mit Anlässen scheint mir sinnvoll. Anstatt Feature Toggle könnte man dann auch auf den Anlässen konfigurieren ob bei einer Anmeldung ein Notfallkontakt erfasst werden kann/muss oder nicht. Bei einem Lager würde man das aktivieren, bei einer kurzen Sitzung nicht.

**Comment by carlobeltrame** [comment]
Merci für eure Inputs. Ich bespreche das mit dem SAC, welcher das Feature vermutlich umsetzen lassen wird. Wenn ich den SAC mit euren Argumenten überzeugen kann, können wir das im Core oder Youth Wagon machen.

**Comment by carlobeltrame** [comment]
Der SAC tendiert aktuell wegen der vielen Touren die eine Einzelperson übers Jahr hinweg macht dennoch zur Speicherung auf der Person statt auf der Anlassteilnahme. Falls der CEVI oder sonst jemand mitfinanzieren möchte, wäre es aber denkbar dass man hier von dieser Schiene abweicht. Das Thema wird im Frühling dann aktuell, wenn das Kurs- und Tourenwesen des SAC auf hitobito integriert werden.

**Comment by patrickuhlmann** [comment]
Wäre dann zumindest geplant das bei der Anmeldung zu einem Anlass der/die Notfallkontakte(e) angezeigt werden damit man sehen würde falls diese veraltet sind und diese direkt korrigieren kann?

**Comment by carlobeltrame** [comment]
Möglich. Bei der Anmeldung werden ja die Personalien inkl. Adresse, Telefonnummer der sich anmeldenden Person auch angezeigt. Dort könnte man auch den Notfallkontakt anzeigen. Allerdings wäre der vermutlich relativ weit unten im Formular.

**Comment by sykesonrocks** [comment]
@mtnstar paar Gedanken meinerseits:
- Wäre super, wenn der User in seinem Profil zwei Notfallkontakte erfassen könnte. Ich sähe hierfür ein separater/neuer Abschnitt ("Notfallkontakt"). Folgende Angaben soll der User pro Notfallkontakt erfassen können: Name, Telefon.
- Im KVS Projekt wurde besprochen, dass der Notfallkontakt im Zuge einer Kursanmeldung immer abgefragt wird. Hier ist die Idee, dass die zwei im User Profil erfassten Notfallkontakte dargestellt werden, mit der Möglichkeit die Daten/Felder zu überschreiben. Falls überschrieben wird, werden die Änderungen in das Profil übernommen. So kann sichergestellt werden, dass der Notfallkontakt pro Event aktuell ist.
- Betreffend Datenschutzrichtlinien: ich kann nachvollziehen, wenn man entscheidet, dass ein Notfallkontakt nicht im Userprofil, aber im Zuge einer Kursbuchung erfasst werden darf und nach Kursabschluss wieder gelöscht wird. So wird es z.B. bei der Swiss auch gehandhabt: 
![image](https://github.com/hitobito/hitobito/assets/132900428/2b452b40-eef5-429f-9bdb-419375385b20)

**Comment by mtnstar** [comment]
@sykesonrocks danke für die Inputs.
ich schaue das an sobald ich dieses Ticket weiter konzipiere

**Comment by mtnstar** [comment]
wird vorerst nur auf TVS umgesetzt, Notfallkontakt wird nicht gespeichert auf Personenprofil
