### ISSUE TITLE
EVENTS: Formatierung Event

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito#2252]
### Aktuelles Verhalten

Die Beschreibung bei Events wird nicht formatiert.
So funktionieren beispielsweise Zeilenumbrüche oder auch die Darstellung von Links nicht mehr.
Das Verhalten tritt seit den letzten Releases auf und nur solange sich die Person nicht eingeloggt hat.
Nach dem Login passt die Darstellung

### Gewünschtes Verhalten

Auch ohne Login erscheint die Beschreibung der Events wie nach dem Login.

### Schritte zu reproduzieren

Klicken auf externen Anmeldelink.

### Wann ist der Fehler aufgetreten?

10.2023

### Organisation

SVSE, JUBLA

### Screenshots, weiterer Kontext

Ohne Login:
![image](https://github.com/hitobito/hitobito/assets/69250571/ffb61d55-de91-41e3-a44d-1f74852de21e)
Mit Login:
![image](https://github.com/hitobito/hitobito/assets/69250571/6dd99613-e247-42da-a305-b4faf80cbc89)

**Comment by tschuepbach** [comment]
Kann ich so bestätigen.
In der Cevi-Umgebung sind zudem folgende, dazu passende, Issues offen:
- [ ] https://github.com/hitobito/hitobito/issues/1931
- [ ] https://github.com/hitobito/hitobito/issues/1763

**Comment by njaeggi** [comment]
This issue is getting fixed in #2360
