### ISSUE TITLE
Einstellungen

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito#2257]
### Aktuelles Verhalten

Wir haben das Problem, dass wir die Position der Rechnungs**anschrift** nicht mehr ändern können.

Früher war diese Option unter Weiteres oder Einstellungen auf der Obersten Ebene eines Layers
Nun findet sich dieser Abschnitt gar nicht mehr.

Vermutlich eine Folge von https://github.com/hitobito/hitobito/issues/2165
(bei uns ist kein Tab Messages verfügbar)

### Gewünschtes Verhalten

Wir können die Einstellung wieder bearbeiten.

### Schritte zu reproduzieren

Login und suchen

### hitobito version

1.31.0

### Organisation

Cevi

**Comment by maede97** [comment]
Gemäss Changelog aus dem verlinkten PR:
"Der Gruppen-Tab "Einstellungen" wurde entfernt und die Optionen sind neu in der Bearbeitungsansicht der Gruppe unter dem Tab "Nachrichten" (#2165)"

**Comment by nchiapol** [comment]
Danke @maede97 - aber eben wir haben kein Tab "Nachrichten"...

Mit dem Hinweis auf die Bearbeitungsansicht und neuem Suchen habe ich es nun aber gefunden:
![screenshot_2023-11-11_203629](https://github.com/hitobito/hitobito/assets/1123483/fa337a14-2859-4b61-8d17-445d1cb338c5)
