### ISSUE TITLE
PERSON: Testsystem - Serverfehler auf allen Profilen

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#2261]
### Aktuelles Verhalten

Auf dem Testsystem können keine Profile mehr geöffnet werden. Beispiel: Der folgende Link führt auf einen Serverfehler:
https://pbs.puzzle.ch/de/groups/1/people/2

### Gewünschtes Verhalten

Profil wird angezeigt

### Schritte zu reproduzieren

- Login als Hussein Kohlmann
- Aufruf eines Profils, z.B. das eigene: https://pbs.puzzle.ch/de/groups/1/people/2

### Wann ist der Fehler aufgetreten?

18.11.2023

### hitobito version

1.31.5

### Organisation

PBS Integration

**Comment by richardjubla** [comment]
Kann ich auf jubla Integration nicht reproduzieren (erfreulicherweise).

**Comment by Michael-Schaer** [comment]
Scheint wieder zu klappen, merci!
