### ISSUE TITLE
TECH: Aufsplitten CI test build github actions

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#2282]
Aktuell werden die test build tasks in einem grossen Job mit einzelnen Steps ausgeführt.

Um schneller zu sehen welche Test-Typen failen, soll dieser Job in drei einzelne Jobs aufgeteilt werden:

1. Rubocop
1. specs ohne feature specs
1. feature specs

# ToDo

- [ ] Issue für Umsetzung erstellen
- [ ] Workflow des Features beschreiben
- [ ] ggf. Mockup erstellen
- [ ] Tech-Spec ergänzen
- [ ] ToDo für Umsetzung definieren

**Comment by rnestler** [comment]
Ich glaube das ist umgesetzt oder?
