### ISSUE TITLE
Mail Mandantenfähigkeit (4h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#229]
- Bisher sind Mailsetting in Umgebungsvariablen, analog zu apartment
- Skript das Mailaccount einrichtet
- Skript das Mailaccount wieder abreisst

## ToDo

Sys hat Mailserver angepasst.

X-Envelope-To für foo+irgendwas@bla.hitobito.com wird auf folgenden Wert gesetzt: foo+irgendwas+bla. X-Envelope-Host wird nicht verwendet.

- [x] Code muss noch entsprechend angepasst werden.
- [x] Bei Mailinglisten Infos und Formular bearbeiten sollte die richtige Subdomain angezeigt werden:

![image](https://cloud.githubusercontent.com/assets/194364/26620532/821a2914-45e3-11e7-85d0-c5780660f826.png)

**Comment by codez** [comment]
Sys Ticket erstellt: https://redmine.puzzle.ch/issues/24288

**Comment by codez** [comment]
Sys hat Mailserver angepasst.

`X-Envelope-To` für `foo+irgendwas@bla.hitobito.com` wird auf folgenden Wert gesetzt: `foo+irgendwas+bla`. `X-Envelope-Host` wird nicht verwendet.

Code muss noch entsprechend angepasst werden.

**Comment by kronn** [comment]
bounces werden noch nicht richtig behandelt.

**Comment by codez** [comment]
@kronn Und warum kommt das dann doch durch das Review?

**Comment by RolandStuder** [comment]
Ist umgesetzt.
