### ISSUE TITLE
Bug: seit bootstrap upgrade fehlen required marks

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito#2296]
### Aktuelles Verhalten

Seit dem bootstrap upgrade werden die required marks bei form field labels nicht mehr angezeigt.

vor upgrade:

![Image](https://github.com/hitobito/hitobito/assets/636849/c0b0af62-faa9-4bd3-a4d5-4ba6a7f9bfd7)

nach upgrade:

![Image](https://github.com/hitobito/hitobito/assets/636849/f936d77d-383d-480c-a1db-2a2a578565b7)

betroffen ist zumindest der SAC wagon

### Gewünschtes Verhalten

required marks werden angezeigt

### Schritte zu reproduzieren

Selbstregistrierungsformular in SAC wagon öffnen

**Comment by njaeggi** [comment]
Problem came from new self registration form, not bootstrap. I fixed it and merged it into master, it should work again now
