### ISSUE TITLE
Performanceoptimierung von grossen Listen (24h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#23]
Die PBS hat festgestellt, das der Export ihres grössten Abos die Server Ressourcenmässig überlastet hat.

Auch die delayed_jobs mussten danach neu gestartet werden.

Anmerkung: Die Lücke im Graph hat mit dem Problem nichts zu tun. Sie entstand, weil /sys Zenoss zügelte.

Da die PBS den Export dringend brauchte, konnten wir das Problem entschärfen, indem wir hitobito 8 statt 4 CPUs zugewiesen haben. Der genannte Export funktioniert so wieder, dauert aber 30min. Ich erachte das jedoch als vorübergehende Lösung und möchte, dass wir den Export trotzdem überarbeiten sprich tunen. 
![whatsapp-image-20160609](https://cloud.githubusercontent.com/assets/194364/16051910/065a03a2-3262-11e6-9799-3babe74cf25f.jpeg)

Originalissue: https://redmine.puzzle.ch/issues/18205

* Es geht hier mal um CSV Export, PDF ignorieren wir noch.

**Comment by puzzleitc** [comment]
der CSV Export läuft nicht über delayed_job, von dem her ist es etwas seltsam das der Neustart der Workers das Problem behob.

**Comment by RolandStuder** [comment]
Es handelt sih um Aboexport für Sarasani bei PBS Schweiz

**Comment by RolandStuder** [comment]
Der Aboexport für das Sarasani hat funktioniert, aber ca. 1 Stunde gedauert. Konntet Ihr hier noch eine Verbesserung machen?

**Comment by RolandStuder** [comment]
Es brauch eine Analyse. Vermutlich hilft ein Streaming, statt alles im Memory zu halten.

**Comment by RolandStuder** [comment]
ca. 1/2 Tag Analyse
2.5 PT für Lösung, z. B. Streaming, ist aber natürlich abhängig von der Analyse.

**Comment by amaierhofer** [comment]
Mittlerweile als Background job gelöst

**Comment by RolandStuder** [comment]
Betrachte ich damit nicht als gelöst. Die Performance ist schwach. Ein Export auch mit 60'000 Einträge sollte nicht 1h in Anspruch nehmen.

**Comment by RolandStuder** [comment]
Grosse Listen werden inzwischen im Hintergrund exportiert. Die Peromance wurde nicht verbessert, aber wenn wir hier nicht jemanden haben, der sagt "hier machen wir was, hier investieren wir was" können wir hier nichts unternehmen.
