### ISSUE TITLE
SEARCH: Tabs in Suchresultaten funktionieren nicht mehr

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#2306]
### Aktuelles Verhalten

Seit dem Bootstrap Upgrade sehen die Tabs bei den Suchresultaten so aus:
![Screenshot 2023-12-14 at 13-01-37 MiData PBS_MSdS_MSS - Ergebnisse](https://github.com/hitobito/hitobito/assets/7566995/463d57d2-d269-4155-a61e-e9d3392a1eb6)

### Gewünschtes Verhalten

Die Suchresultate verschiedener Arten können auf Tabs angesehen werden:

![Screenshot 2023-12-14 at 13-01-11 MiData PBS_MSdS_MSS - Ergebnisse](https://github.com/hitobito/hitobito/assets/7566995/9a3a80ba-5b7b-4950-96bd-7cbceb81fa24)

### Schritte zu reproduzieren

1. Auf beliebiger Integrationsumgebung einloggen
2. In der grossen Suchbar etwas beliebiges eingeben
3. Auf den Lupen-Button klicken

### Wann ist der Fehler aufgetreten?

Seit dem Bootstrap Upgrade

### hitobito version

2

### Organisation

alle

**Comment by TheWalkingLeek** [comment]
Collapse im Footer funktioniert auch nicht mehr
