### ISSUE TITLE
PERSON: HTML code im Text

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#2307]
### Aktuelles Verhalten

Wenn eine neue Person erstellt wird

![grafik](https://github.com/hitobito/hitobito/assets/1799621/67fd89a8-aa6b-4790-9086-f9631a397bea)

### Gewünschtes Verhalten

Siehe Screenshot

### Schritte zu reproduzieren

Siehe Screnshot

### hitobito version

1.31.5

### Organisation

PBS Integration

**Comment by carlobeltrame** [comment]
Wird in #2310 mitgelöst.
