### ISSUE TITLE
ROLES: Inaktive Rollen werden als Fehlerhaft markiert in Person#Verlauf

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#2312]
### Aktuelles Verhalten

![image](https://github.com/hitobito/hitobito/assets/655627/8ff2f74e-9b21-465d-8149-d49f0ac3b0a6)

### Gewünschtes Verhalten

Bei inaktiven Rollen sollte keine Warnung angezeigt werden

### Schritte zu reproduzieren

1. Rolle auf Person mit bis Datum in der Vergangenheit erfassen
2. Auf history Tab der Person wechseln und Inaktive Rollen prüfen

### hitobito version

1.31.5

### Organisation

sac_cas

**Comment by mtnstar** [comment]
```
 #<Group::SektionsMitglieder::Ehrenmitglied:0x00005590ec37cd50
  id: 277,
  person_id: 600048,
  group_id: 18,
  type: "Group::SektionsMitglieder::Ehrenmitglied",
  label: "",
  created_at: Wed, 01 Nov 2023 00:00:00.000000000 CET +01:00,
  updated_at: Thu, 30 Nov 2023 14:11:48.000000000 CET +01:00,
  deleted_at: Thu, 30 Nov 2023 14:11:48.000000000 CET +01:00,
  archived_at: nil,
  delete_on: Mon, 27 Nov 2023,
  convert_on: nil,
  convert_to: nil,
  beitragskategorie: nil,
  terminated: false>,
```

bei mir lokal wie auch auf sac integration gibt es mind. 1 rolle bei der **delete_on** sowie **deleted_at** mit einem Wert abgefüllt ist.

@amaierhofer hast du eine Idee warum es das geben könnte? eigentlich sollte diese Konstellation gar nie auftauchen, oder?

**Comment by amaierhofer** [comment]
Meiner Meinung nach ist es okay, wenn sowohl `delete_on` und `deleted_at` ist gesetzt sind. Der Wert im `delete_on` bleibt erhalten, wenn die Role destroyed wird. 

Das Verhalten aus dem Screenshot kann ich nicht reproduzieren. Mit dem bei mir aktivem generic Wagon wird eine bestehende Rolle gelöscht, wenn  das Bis Datum in der Vergangeheit ist. Dabei wird allerdings  `deleted_at`  auf den aktuellen Zeitpunkt gesetzt *und der Bis Wert aus dem Formular nicht übernommen*.  Da würde ich erwarten, dass Bis übernommen wird.

Neu werden aber gelöschte Rollen nie als `outdated?` betrachtet.
