### ISSUE TITLE
Bootstrap: Gefundene "Bugs" auf der Cevi-Testumgebung

### ISSUE THREAD

**Issue by tschuepbach** [hitobito/hitobito#2317]
### Aktuelles Verhalten

Folgendes ist uns aufgefallen:

~**Person/Abos**~
~Testperson: https://cevi.puzzle.ch/groups/335/people/3086/subscriptions
Die An- resp. Abmelden Buttons werden nicht korrekt angezeigt, sondern nur als Art Hover:~
<img width="400" alt="image" src="https://github.com/hitobito/hitobito/assets/40494600/dd3c963c-f7e2-4f9e-a83d-d091b01e72d9">
<img width="417" alt="image" src="https://github.com/hitobito/hitobito/assets/40494600/805b4f0f-3924-40f4-b3a4-ef09caa7b638">

~**Person/Sicherheit**~
~Testperson: https://cevi.puzzle.ch/groups/335/people/3086/subscriptions
Bei "Rollen, die auf mich Zugriff haben" wird das Ladeicon immer angezeigt, obwohl der Button nicht aktiviert wurde:~
<img width="244" alt="image" src="https://github.com/hitobito/hitobito/assets/40494600/7bf0476f-93cd-4895-8d4e-5bb8b2dc7b30">

~**Ansicht Kursübersicht**~
~Link: https://cevi.puzzle.ch/list_courses~
~Sieht etwas unschön und verschachtelt aus, gerade bei mobilen Geräten oder kleinen Ansichten:~
<img width="724" alt="image" src="https://github.com/hitobito/hitobito/assets/40494600/83aca8dd-5711-4613-a44a-7385844865dc">
![image](https://github.com/hitobito/hitobito/assets/40494600/697ced8b-4b6e-41ac-b9f1-7efaa970fabf)
![image](https://github.com/hitobito/hitobito/assets/40494600/939aa5bc-71a6-4c89-9254-97af30e2fd69)

~**Kursarten/Vorbedigungen**~
~Test: https://cevi.puzzle.ch/event_kinds/14/edit~
~Checkboxes sind noch nicht korrekt ausgerichtet:~
<img width="346" alt="image" src="https://github.com/hitobito/hitobito/assets/40494600/d598f10d-6b24-49d5-96d0-404fb0f23f8c">

### Gewünschtes Verhalten

Alle Ansichten werden korrekt dargestellt

### Schritte zu reproduzieren

Siehe Links oben

### Wann ist der Fehler aufgetreten?

20.12.2023

### hitobito version

1.31.5

### Organisation

Cevi Testumgebung

**Comment by tschuepbach** [comment]
Nice to have:

Bei der Erfassung von "Anmeldeangaben" und "Administrationsangaben" ist `Eintrag hinzufügen` nicht mehr ausgerichtet:

Neu:
<img width="601" alt="image" src="https://github.com/hitobito/hitobito/assets/40494600/39cb7ab8-de7a-43f4-a13e-a55f7cd0855b">

Bisher:
<img width="635" alt="image" src="https://github.com/hitobito/hitobito/assets/40494600/d6582176-ea5b-430f-9933-e44278ddfe8e">


Bei einer Kursanmeldung wird eine grosse Lücke zwischen den Kontaktangaben und der DSE-Einwilligung dargestellt:
<img width="872" alt="image" src="https://github.com/hitobito/hitobito/assets/40494600/4cf882c1-f1c7-41a3-b7bf-2e279ec9b7b5">
Dies ist anhängig davon, wie viele Kontaktangaben angezeigt resp. abgefragt werden.
Test mit Person: https://cevi.puzzle.ch/groups/336/people/3105, Kurs: https://cevi.puzzle.ch/groups/6/events/1216

**Comment by nchiapol** [comment]
Weiterer Layout Bug: Bullet-Lists sind schlecht ausgerichtet (vgl. Screenshots unten), ein `pl-4` im `ul`-tag würde das imo lösen.

![screenshot_2023-12-28_140855](https://github.com/hitobito/hitobito/assets/1123483/bd6b4542-65c0-4184-b684-5e171e989af9)

![screenshot_2023-12-28_141341](https://github.com/hitobito/hitobito/assets/1123483/1cf6d762-fe1b-4a21-bf6a-47443e5a80c4)

**Comment by nchiapol** [comment]
Mindestens bei der Voranmeldung für einen Kurs ist die Bootstrap-Meldung nicht korrekt gestylet:
![screenshot_2023-12-28_143522](https://github.com/hitobito/hitobito/assets/1123483/1f026436-21b6-44e9-a38b-0e4e0714bbce)

Ursache: die `class` des `div` enthält `alert-warn` statt `alert-warning`

**Comment by patrickuhlmann** [comment]
Die Infoansicht von Personen hat sich gegenüber vorher verschlechtert. Alles klebt auf derselben Zeile aneinander ohne Abstand.

| Neu | Vorher |
|--------|--------|
| [Integration](https://cevi.puzzle.ch/groups/1/people/3336.html) | [Produktion](https://db.cevi.ch/groups/2748/people/21623.html) |
| ![image](https://github.com/hitobito/hitobito/assets/511373/34d659ac-4b5f-4c4c-a203-5b6891a316aa) | ![image](https://github.com/hitobito/hitobito/assets/511373/c4f4e75e-44ff-490c-ac43-2a23a5c6a409) |

**Comment by patrickuhlmann** [comment]
Die Infoansicht von Anlässen hat sich gegenüber vorher verschlechtert. Auch hier klebt alles zusammen.
| Neu | Vorher |
|--------|--------|
| [Integration](https://cevi.puzzle.ch/groups/488/events/1217) | [Produktion](https://db.cevi.ch/groups/1819/events/3821) |
| ![image](https://github.com/hitobito/hitobito/assets/511373/12622bdf-d0c8-401e-965b-d5b6ebbafb36) | ![image](https://github.com/hitobito/hitobito/assets/511373/7e9350d6-d3b8-4572-8ca6-b70be60f09eb) |

**Comment by patrickuhlmann** [comment]
Hier ein Vergleich vorher/nachher zur Kursübersicht. Die Filter waren vorher viel sbesser angeordnet.

| Nachher | Vorher |
|--------|--------|
| [Integration](https://cevi.puzzle.ch/list_courses) | [Produktion](https://db.cevi.ch/list_courses) |
| ![image](https://github.com/hitobito/hitobito/assets/511373/ab635f50-0db1-4caf-9436-72fe1e8c93c7) | ![image](https://github.com/hitobito/hitobito/assets/511373/4ea0c732-6390-4998-b6c6-3dcf39e88e7c) |

**Comment by njaeggi** [comment]
> Die Infoansicht von Anlässen hat sich gegenüber vorher verschlechtert. Auch hier klebt alles zusammen.

Wenn ich es auf der Integration prüfe sieht es bei mir nicht so aus:

![image](https://github.com/hitobito/hitobito/assets/68543592/ea6783ad-a107-4765-9309-7ef470133b6e)

Der gemeldete Anlass existiert nicht mehr, deshalb habe ich diesen verwendet: https://cevi.puzzle.ch/groups/488/events/1218

Auch die Personenansicht scheint bei mir zu funktionieren.

Auf welchem Browser wurde getestet? Firefox und Chrome stellen Anlässe und Personen bei mir schön dar.

**Comment by patrickuhlmann** [comment]
Ich hatte jeweils in Firefox getestet aber es gerade noch in Chrome angeschaut. Die Darstellung ist identisch. In Normalbreite sieht es bei mir auch gut aus. Allerdings habe ich vergessen zu erwähnen das ich die Responsive Ansicht geprüft habe indem ich das Browserfenster schmal gemacht habe analog zu einem Mobiltelefon. Die Verschlechterung tritt ein sobald er von der Anzeige des Menüs links auf das "Hamburger" Menü wechselt. Habe es auch noch auf einem Fairphone 5 getestet und dort dieselbe Verschlechterung wie im Browser.

**Comment by njaeggi** [comment]
Alle durchgestrichenen Fehler wurden behoben und werden morgen im Release dabei sein.
