### ISSUE TITLE
ROLES: FutureRole und primary group

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#2319]
### Aktuelles Verhalten

Aktuell kann man auch auf einer FutureRole die Primary Group :star: setzen. Da die Rolle noch nicht aktiv ist, bin ich mir nicht sicher ob dies irgendwie Sinn macht. Dies sollte man mit diesem Ticket prüfen.
Ausserdem gibt es folgendes seltsames Verhalten:

Clickt man auf :star: einer FutureRole, wird die komplette Ansicht/Auflistung der Rollen dupliziert:

![image](https://github.com/hitobito/hitobito/assets/655627/11bc59a5-9af3-431d-8ff5-da82c077025e)

### Gewünschtes Verhalten

Ein klick auf :star: einer FutureRole hat keine Auswirkung und ist höchstens read-only bzw. muss dies bei einer FutureRole ggf. gar nicht angezeigt werden.

### Schritte zu reproduzieren

1. Person#info einer Person öffnen
2. Falls nicht bereits vorhanden, eine FutureRole der Person assignen
3. Click auf set primary group :star: der FutureRole

### ToDos

Verhalten primary group für FutureRole fixen bzw. anpassen

**Comment by ThomasEllenberger** [comment]
Bei meinen Tests kann ich das gleiche Verhalten bestätigen.
Dies passiert jedoch nur auf der aktuellen Ansicht. Wird die Seite neu geladen sind die duplizierten Rollen wieder weg.
