### ISSUE TITLE
Skript das Subdomains auf Openshift erstellt (12h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#232]
Auch gleich Abklärungen zu #229 und #230 klären

**Comment by kronn** [comment]
Die subdomains werden als Routen in Openshift eingetragen.

```shell
oc login -u hitobito_saas_admin # das PW wird beim ersten Login abgefragt
oc project hitobito_saas
oc expose service rails -l type=customer --name=customer23 --hostname=subdomain23.hitobito.ch
```

Subdomains sollten sofort funktionieren, für abweichende Domains müssen gesonderte DNS-Einträge gemacht werden. Eine Route anzulegen dauert nur wenige Sekunden.

Das tatsächliche Script sollte dann Teil eines neuen Wagons werden.

**Comment by kronn** [comment]
Erledigt durch #259

**Comment by RolandStuder** [comment]
Ist umgesetzt in privatem Repo von mir.
