### ISSUE TITLE
ROLES: FutureRole beim Editieren bestehender Rolle nicht möglich

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito#2323]
### Aktuelles Verhalten

Wird eine bereits vergebene Rolle einer Person bearbeitet und dabei das (in der Vergangenheit liegende) Datum der Rolle neu in die Zukunft geändert, erscheint die Fehlermeldung "Eintritt kann nicht später als heute sein"

![Hitobito_Eintritt_kann_nicht_spaeter_als_heute_sein](https://github.com/hitobito/hitobito/assets/1453303/b2d9c0eb-9fcd-43cc-9f96-3f17783e5f0f)

### Gewünschtes Verhalten

Wird die bestehende Rolle gelöscht und neu mit einem Datum in der Zukunft erfasst, funktioniert es einwandfrei. Der Zwischenschritt (Löschen) sollte nicht nötig sein und die Rolle sollte direkt mit einem Datum in der Zukunft editiert werden können.

### Schritte zu reproduzieren

Beliebige Person mit aktiver Rolle öffnen und die aktive Rolle in eine zukünftige Rolle umwandeln versuchen

### Wann ist der Fehler aufgetreten?

21.12.2023, 14 Uhr

### hitobito version

1.31.5

### Organisation

SBV

**Comment by mtnstar** [comment]
@betsim das ist ein bewusstes Verhalten. 
Wenn wir Rollen erstellen/aktivieren, werden diverse Callbacks getriggert die z.B. die Primär-Gruppe der Person neu setzen usw. 
Aus diesem Grund kann aus einer aktiven Rolle keine künftige werden (FutureRole)
Man kann aber ohne Problem einfach die aktuelle Rolle auf ein Datum terminieren (kann auch in der Vergangenheit sein) und dazu parallel eine neue Rolle erfassen mit Von-Datum in der Zukunft.

**Comment by betsim** [comment]
Ok, verstehe ich. Dann wäre aber eine etwas sinnhaftere Fehlermeldung noch gut. Zum Beispiel: "Eine bestehende Rolle kann nicht in eine zukünftige Rolle geändert werden. Bitte Rolle beenden und neu erfassen" (oder ähnlich).
