### ISSUE TITLE
PEOPLE: Profil "ohne Rollen" kann nicht mehr gelöscht werden

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito#2326]
### Aktuelles Verhalten

In der Gruppe "ohne Rollen" können Profile direkt gelöscht werden, sofern die Berechtigungen vorhanden sind. (Darum wird auch das Löschen-Icon angezeigt). Dies ist in der [Version 1.28.30.2](https://db.jubla.ch/changelog) und auch [Version 1.31.5](https://jubla.puzzle.ch/changelog) nicht mehr möglich.

![hitobito-deleate](https://github.com/hitobito/hitobito/assets/95908537/56c4fb08-019b-4e01-a1be-41822516c4b0)

### Gewünschtes Verhalten

In der Gruppe "ohne Rollen" sollen Profile gelöscht werden können, sofern die Berechtigungen vorhanden sind.

### Schritte zu reproduzieren

In der Gruppe "ohne Rollen" eine Person löschen -> Error 404

### Wann ist der Fehler aufgetreten?

22.12.2023

### hitobito version

1.31.5

### Organisation

Jubla, Pfadi

### Screenshots, weiterer Kontext

@Michael-Schaer [Version 1.31.5](https://pbs.puzzle.ch/de/changelog) ist auch betroffen (ihr habt da zwei lösch-icons, das erste verhält sich gleich)

**Comment by richardjubla** [comment]
![hitobito-deleate-pbs](https://github.com/hitobito/hitobito/assets/95908537/53dadfee-0b30-4315-b2b3-d497d60cd53d)

**Comment by richardjubla** [comment]
Das fehlerhafte Verhalten ist leider auch in [Version 2.1.2](https://db.jubla.ch/changelog) immer noch reproduzierbar.

**Comment by richardjubla** [comment]
Das fehlerhafte Verhalten ist auch in [Version 2.1.5](https://jubla.puzzle.ch/changelog) immer noch reproduzierbar.

**Comment by richardjubla** [comment]
Dieses Ticket ist vermutlich ein Duplikat für https://github.com/hitobito/hitobito/issues/1780

**Comment by richardjubla** [comment]
Das fehlerhafte Verhalten ist auch in Version 2.2.0 immer noch reproduzierbar.

**Comment by ThomasEllenberger** [comment]
Duplikat von https://github.com/hitobito/hitobito/issues/1780 
Wird deshalb geschlossen, und dort weiterverfolgt.
