### ISSUE TITLE
EVENTS: Anmeldung an einen Event mit Anmeldeschluss in der Vergangenheit

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#2328]
### Aktuelles Verhalten

Ich möchte mich als Benutzer zu einem Event anmelden. Der Anmeldeschluss habe ich leider verpasst. Trotzdem erscheint auf dem Event noch der Button "Anmelden". Wenn ich den anklicke erscheint die Anmeldung zur Eingabe der Kontaktmöglichkeiten (/participations/contact_data?event_role[type]=Event%3A%3ARole%3A%3AParticipant) . Nach dem weiter erhalte ich die Meldung "Sie sind nicht berechtigt, diese Seite anzuzeigen" und kann mich nicht zum Event anmelden. Was wohl der Anmeldeschluss verursacht.

### Gewünschtes Verhalten

Als Benutzer möchte ich den "Anmelden" Button gar nicht sehen oder noch besser eine Meldung, wieso ich mich da nicht anmelden kann.

### Schritte zu reproduzieren

Kann sowohl in der Prod wie in der Integration der Pfadi nachgestellt werden.
In der Prod: https://db.scout.ch/de/groups/4/events/24922
in der Testumgebung: https://pbs.puzzle.ch/de/groups/1/events/2185/
Achtung: Als Admin kann ich natürlich auch nach dem Anmeldeschluss noch eine Person hinzufügen oder mich selber anmelden. Dies ist bewusst so gewählt.

### Wann ist der Fehler aufgetreten?

27.12.23

### hitobito version

1.31.6

### Organisation

PBS/Midata und wohl auch core

### Screenshots, weiterer Kontext

Anmelden trotz verstrichener Anmeldeschluss
![2023-12-27_13-52](https://github.com/hitobito/hitobito/assets/9592347/42628a00-2100-4aae-98d1-25df0e30c0f0)

**Comment by ThomasEllenberger** [comment]
## Zusatz Kurse:

### Aktuelles Verhalten: 
Bei Kursen mit einem Anmeldeschluss in der Vergangenheit kann man sich trotzdem anmelden.
Es erscheint keine Fehlermeldung. Die Anmeldung kann abgeschlossen werden und man ist anschliessend zum Kurs angemeldet.

### Gewünschtes Verhalten:
Analog erstem Beitrag: Der "Anmelden" Button soll nicht mehr ersichtlich sein, wenn der Anmeldeschluss in der Verganenheit liegt.

### Hitobito Version:
2.0.0

### Organisationen
Getestet auf Pro Natura Integration und PBS Integration

**Comment by nchiapol** [comment]
@ThomasEllenberger: Wir möchten das aktuelle verhalten explizit beibehalten 

(vgl auch https://github.com/cevi/hitobito_cevi/issues/157)

**Comment by ThomasEllenberger** [comment]
Wir haben hier noch weitere bugs in diesem Zusammenhang gefunden.

Getestet auf Pro-Natura Integration
Version 2.0.0

### Aktuelles Verhalten:

Aktuell kann man sich auf der Kursübersicht selbst Anmelden, unabhängig vom Anmeldedatum und vom Kursstatus.
![image](https://github.com/hitobito/hitobito/assets/100761305/d5ce312d-e5c8-40a2-9e43-9043168f08ce)

In der Kursliste werden die Stati und der Anmeldebeginn (Nicht aber Anmeldeschluss) und der Kursstatus  hingegen korrekt verwendet und man kann sich nur an einen Kurs anmelden wenn der Kurs den Status "offen zur Anmeldung" hat und der Anmeldebeginn in der Vergangenheit liegt.
![image](https://github.com/hitobito/hitobito/assets/100761305/87d35f3b-16a1-4366-8b9e-bf2717727386)




### Gewünschtes Verhalten:
Auch auf der Kursübersicht selbst soll der Button "Anmelden" nur ersichtlich sein, wenn der Kurs den Status "offen zur Anmeldung" hat, und das Datum "Anmeldebeginn" in der Vergangenheit liegt.


### Abgrenzung:
Oben genanntes Verhalten, dass man sich nach dem Datum "Anmeldeschluss"  noch immer anmelden kann ist aktuell kein Bug. Dies war in der Vergangenheit bereits so (ausser bei PBS die dies spezifisch überschriben hat). Wird dies geändert werden wir dies mit einem Feature machen, nicht mit einem Bugissue.

**Comment by codez** [comment]
Eine entsprechende Prüfung wurde in folgendem Commit entfernt: https://github.com/hitobito/hitobito_youth/commit/95ec59c433c4cc992f069ae80313c256f3f5040d#diff-b10b71d053ec9069d1a47b197c83caac26fca801f1934d3f0aceaeca24965aa3L1 (app/views/events/_actions_show.html.haml#1)

Das ganze Template wurde in diesem Commit überhaupt erst komplett überschrieben: https://github.com/hitobito/hitobito_youth/commit/7a4ff706d7735a9927b85aefb6015f8f93758e53#diff-b10b71d053ec9069d1a47b197c83caac26fca801f1934d3f0aceaeca24965aa3 Hätte es hier allenfalls gereicht, die anzupassende Funktionalität in eine Helper Methode zu extrahieren, ohne das ganze Template zu kopieren und damit die Wartbarkeit beträchtlich zu verschlechtern?

**Comment by carlobeltrame** [comment]
Ich sehe, da hätte ich in meiner Commit Message expliziter sein müssen. Wenn ich mich richtig erinnere habe ich diesen Commit gemacht, weil der Anmelden-Button in gewissen Szenarien für den Elternteil nicht sichtbar war, auch wenn der Elternteil die Erlaubnis hat eines seiner Kinder für den Anlass anzumelden. Möglicherweise war es in einem Edge Case beim Anlegen eines neuen Kindes direkt bei der Anlassanmeldung: Das neu erstellte Kind hat in diesem Moment noch keine Rollen, und hat daher nie die Berechtigung, den Anlass anzuschauen, ergo wurde die Option dann nicht geboten, das eben erstellte Kind für den Anlass anzumelden. Siehe auch https://github.com/hitobito/hitobito/issues/1969 im Abschnitt "Neuer Ablauf" die Schritte 3-6 für eine Übersicht, wie sich das für die User anfühlen sollte.

Kann gut sein dass ich da etwas zu grosszügig entfernt habe. Vermutlich müssten wir die Berechtigungsfragen von den Anmeldeschluss-, Status- und weiteren reinen Event-AttributEntscheidungen trennen. Den Workflow mit den Kindern anmelden und optional neuem Kind anlegen sollte man aber auf jeden Fall auch berücksichtigen, wenn man das wieder stärker einschränkt.

**Comment by Michael-Schaer** [comment]
Ich möchte bekräftigen, dass die Änderung für die PBS ungünstig ist: Es melden sich aktuell viele Personen, die den Anmeldebutton sehen und versuchen, sich anzumelden. Erst wenn sie alle Angaben zusammengesucht und eingetippt haben, kommt die Fehlermeldung und die Anmeldung ist weg. Das ist eine kleine UX-Katastrophe ;) 

Ich denke, dass hat auch nichts mit dem UseCase des Cevi zu tun: Eine Ausnahme für eine Anmeldung trotz verpasster Anmeldefrist sollte ja gut abbildbar sein. Irrtum vorbehalten, wird wohl auch das Cevi den Button nur dann sehen wollen, wenn eine Anmeldung möglich ist.

**Comment by nchiapol** [comment]
Ich bin mit @Michael-Schaer einverstanden. Unser UseCase ist nur, dass bei Kursen nicht der Anmeldeschluss sondern der Kursstatus darüber entscheiden soll ob Anmeldungen möglich sind.

Der Anmeldebutton sollte auch bei uns nur angezeigt werden, wenn Anmeldungen möglich sind.

**Comment by richardjubla** [comment]
Bisher war es (bei uns/unserer Sicht) eine Kombination aus Kursstatus und Anmeldeschlussdatum. Wenn beides zutrifft, ist eine Anmeldung durch TN möglich. Wir schliessen uns den Aussagen vom Cevi und der PBS an.


Siehe auch:
https://github.com/hitobito/hitobito/issues/2161 
https://github.com/hitobito/hitobito/issues/2233 - Sowohl Datum wie auch Kurs Status wird ignoriert. (Auch Kurse mit dem Status "Erstellt" oder "Bestätigt" sind offen zur Anmeldung, obwohl erst ab dem Status "offen zur Anmeldung" eine Anmeldung möglich sein sollte)
In der Version 1.28.30.2 ist/war dieses nicht der Fall.
