### ISSUE TITLE
PEOPLE: bis-Datum in der Vergangenheit terminiert die Rolle mit End-Datum heute

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito#2333]
### Aktuelles Verhalten

Durch #2245 wird die Rolle sofort terminiert und nicht mit Verzögerung. Das funktioniert korrekt - aber das Eingetragene End-Datum ist nicht der eingetragene Bis-Termin sondern das heutige Datum

### Gewünschtes Verhalten

Es wird der eingetragene Bis-Termin gespeichert.

### Schritte zu reproduzieren

1. Rolle mit Bis-Datum in der Vergangenheit beenden.
2. Verlauf der betroffenen Person öffnen.

### hitobito version

1.31.5

### Organisation

Cevi

### Screenshots, weiterer Kontext

Ich habe versucht den Wechsel vom TN zum Leiter per 2024-12-01 auszuführen. Das End-Datum der TN-Rolle ist aber falsch.
![screenshot_2023-12-28_142231](https://github.com/hitobito/hitobito/assets/1123483/6dd94188-ef5c-4925-b6d0-a721a5103cc9)

**Comment by mtnstar** [comment]
dies wurde in der Zwischenzeit gefixt und ist auf den Integrationen deployed.
bitte Ticket wieder öffnen falls das Problem trotzdem noch bestehen sollte.

**Comment by nchiapol** [comment]
hat in meinem Test eben korrekt funktioniert
