### ISSUE TITLE
ELTERNZUGANG: Verwalter können Kinder nicht entfernen

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito#2335]
### Aktuelles Verhalten

Verwalter haben bei ihren Kindern den link "Entfernen", das Kind wird auf der Bearbeiten-Seite auch nicht mehr angezeigt. Beim Speichern werden aber nur die anderen Änderungen gespeichert, das Kind ist nach dem Speichern wieder verknüpft.

Das Entfernen als Admin funktioniert korrekt.

### Gewünschtes Verhalten

Der Link funktioniert auch für Verwaltet korrekt. (Oder wird gar nicht angezeigt.)

### Schritte zu reproduzieren

1. Verwalter-Account (https://cevi.puzzle.ch/groups/87/people/905) öffnen und imitieren
2. Verwalter bearbeiten
3. Kind entfernen
4. Speichern
   * Meldung: "Person ... wurde erfolgreich aktualisiert." wird angezeeigt (ohne "Kind ... entfernt.")
5. Kinder kontrollieren

### hitobito version

1.31.5

### Organisation

Cevi

**Comment by ThomasEllenberger** [comment]
Problem wurde in https://github.com/hitobito/hitobito/issues/2125#issuecomment-1586786815 bereits festgehalten.
Da dort die Übersichtlichkeit meines Erachtens nicht mehr gegeben ist, welche Bugs durch die Nacharbeiten behoben wurden und welche weiterhin bestehen schlage ich vor dass ich ein neues Ticket eröffne für Bekannte issues beim Elternzugang eröffne und dieses hier schliesse.

**Comment by nchiapol** [comment]
@ThomasEllenberger Danke für den Hinweis. 

Persönlich würde ich für jedes Anliegen ein eigenes Ticket nutzen, so können die dann auch einfacher einzeln referenziert, kommentiert oder geschlossen werden. Die Tickets können immer noch via Milestone oder Project oder Label gruppiert werden.

Ich kann aber natürlich auch mit deinem Vorschlag leben.

**Comment by nchiapol** [comment]
Scheint mit neuen Layout (https://github.com/hitobito/hitobito_youth/pull/44) behoben.
