### ISSUE TITLE
static_name for groups

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito#2353]
Hallo zusammen

Gemäss #2219 sollen Gruppen neu übersetzt werden können. Dies funktioniert auf der SBV-Integrationsumgebung nicht. Muss dieses Feature zuerst aktiviert werden oder mache ich etwas falsch?

Ich wechsle die Sprache und ändere dann den Namen einer Gruppe --> diese Änderung wird in allen Sprachen vorgenommen.

**Comment by carlobeltrame** [comment]
Hallo Simon
In #2219 wurde nicht ermöglicht, die Gruppennamen zu übersetzen. Vielmehr wurde dort die Möglichkeit geschaffen, bei gewissen Gruppentypen (z.B. bei euch der Gruppentyp "Verein", oder ein Gruppentyp namens "Vorstand") das Namens-Feld zu entfernen und stattdessen einen fixen, nicht mehr konfigurierbaren Namen für alle Gruppen dieses Typs anzuzeigen.
Also wenn z.B. ihr in allen euren Vereinen den Vorstand gezwungenermassen genau gleich benennen wollt, dann würde dieses Feature helfen. Der Name aller Vorstands-Gruppen könnte z.B. auf "Vereinsvorstand" forciert und fixiert werden. Dies verlangt eine Code-Änderung, und mit dieser Code-Änderung könnten wir dann auch "Vereinsvorstand" in anderen Sprachen im Code einfügen.
In diesem Sinne erlaubt #2219 also nur, die Namen von Gruppen mit fixiertem Namen zu übersetzen, und die Übersetzung erfolgt im Code (bzw. Transifex), nicht durch die User.

**Comment by carlobeltrame** [comment]
Das wäre ein Feature das vom Umfang her sehr gut an einem Hackathon implementiert werden könnte. Falls am nächsten Hackathon vom 8.-10. März jemand von euch vorbeikommt kann ich gerne instruieren.
