### ISSUE TITLE
Bootstrap: Weitere, gefundene "Bugs"

### ISSUE THREAD

**Issue by tschuepbach** [hitobito/hitobito#2360]
### Aktuelles Verhalten

~**Zeilenumbrüche**~
~Das Problem mit den Zeilenumbrüchen besteht weiterhin. Bei der Kursbeschreibung funktionieren die Zeilenumbrüche nur, solange man eingeloggt ist. Beispiel externe Ansicht: https://db.cevi.ch/groups/1/public_events/3713~

~Bei Ort / Adresse funktionieren diese nie, egal ob eingeloggt oder nicht.~

~Gemäss https://github.com/hitobito/hitobito/issues/1763 wurde dies behoben, bei uns funktioniert dies aber nach wie vor nicht. Wurde auch schon hier erfasst: https://github.com/hitobito/hitobito/issues/2252~

~Bei den Aufnahmebedingungen haben wir nach wie vor folgendes Problem: https://github.com/hitobito/hitobito/issues/1931~
~Seit dem Bootstrap Update funktionieren zudem die Zeilenabstände bei den Aufnahmebedingungen nicht mehr:
<img width="340" alt="image" src="https://github.com/hitobito/hitobito/assets/40494600/f5709f5d-113f-4e57-ad92-b8834c196ed6">
Beispiel Kurs: https://cevi.puzzle.ch/groups/6/events/1161~

~**Kursübersicht/Kursliste**~
~Je nach Bildschirmgrösse kann es vorkommen, das die Kursarten in der Navigation links abgeschnitten werden:
<img width="249" alt="Screenshot 2024-01-10 075537" src="https://github.com/hitobito/hitobito/assets/40494600/ceddf13e-2391-453c-8bb3-0266d3d8aca0">~

~<img width="199" alt="Screenshot 2024-01-10 083044" src="https://github.com/hitobito/hitobito/assets/40494600/8d6602e5-2448-4621-ac78-e0d9464f7e7c">~

~[Link](https://db.cevi.ch/list_courses?filter%5Bsince%5D=15.01.2024&filter%5Buntil%5D=15.01.2025&filter%5Bstates%5D%5B%5D=&filter%5Bstates%5D%5B%5D=created&filter%5Bstates%5D%5B%5D=confirmed&filter%5Bstates%5D%5B%5D=application_open&filter%5Bstates%5D%5B%5D=application_closed&filter%5Bstates%5D%5B%5D=assignment_closed&filter%5Bstates%5D%5B%5D=completed&filter%5Bstates%5D%5B%5D=closed&filter%5Bplaces_available%5D=0&filter%5Bgroup_ids%5D%5B%5D=) zur Übersicht.~

~**Anfragen**~
~Bei Personenanfragen / -freigaben fehlt wohl dass Icon "✓":~
<img width="729" alt="Screenshot 2024-01-12 144344" src="https://github.com/hitobito/hitobito/assets/40494600/b455dab4-54c3-43d7-ad74-a8759e55b804">

~**Kurs/Tab Teilnehmende**~
~Im Tab "Teilnehmende" in einem Kurs, sind die Buttons, sowie das Export-Menü abgeschnitten. Hängt auch wieder mit der Bildschirmgrösse zusammen.~
![Unbenannt](https://github.com/hitobito/hitobito/assets/40494600/8957445d-e25f-49c7-b1e5-a17e317fd267)

![asdfasf](https://github.com/hitobito/hitobito/assets/40494600/09ba19c7-067a-40d3-800e-93f85d000674)

**Anmeldeangaben**
~Beim Beantworten der Anmeldeangaben entstehen kleine Spaltenbreiten resp. grosse Lücken. Hängt wieder mit der Bildschrimgrösse zusammen:~
![Screenshot 2024-01-09 180822](https://github.com/hitobito/hitobito/assets/40494600/25e8db74-ca8c-4f91-837f-90d626d760db)

<img width="455" alt="image" src="https://github.com/hitobito/hitobito/assets/40494600/8409cfd9-4b34-41b3-a9fe-20844326bc97">

### Gewünschtes Verhalten

Alle Ansichten werden korrekt dargestellt.

### Schritte zu reproduzieren

Siehe Links oben. Falls weitere, konkrete Beispiel in der Testumgebung benötigt werden, bitte melden.

### Wann ist der Fehler aufgetreten?

15.01.2024

### hitobito version

2.0.0

### Organisation

Cevi

**Comment by tschuepbach** [comment]
**Tab Personen**
Wenn nur noch eine Person in einer Gruppe vorhanden ist und man ein Änderung bei der Rolle vornehmen möchte, wird das Menü resp. der letzte Punkt ("Rollen entfernen") abgeschnitten:
<img width="474" alt="image" src="https://github.com/hitobito/hitobito/assets/40494600/52576baf-c6a2-4590-b4f1-5d906b0dab78">

Korrekt wäre:
<img width="228" alt="image" src="https://github.com/hitobito/hitobito/assets/40494600/1c91bd8f-7e82-4997-a22a-98a8885bf270">

Beispiel: https://cevi.puzzle.ch/groups/415/people

**Comment by mtnstar** [comment]
![image](https://github.com/hitobito/hitobito/assets/655627/4f1bc6d9-0c6b-4d6d-adbc-4a454ed2eed9)

links im login form schiessen über die box hinaus

**Comment by ThomasEllenberger** [comment]
Kidnappe das Ticket gleich noch für ein weiteres Issue:

In den Personendaten sind die "Titel" und Einträge nicht mehr aligned:
![Image](https://github.com/hitobito/hitobito/assets/100761305/2aade3ed-4e10-4125-8e4c-17c3104d772f)

Durch das Deaktivieren von `padding-top` behebt sich das problem, evtl ist das der fix, evtl nicht...  


![Image](https://github.com/hitobito/hitobito/assets/100761305/7fe54b89-0322-46ba-99bf-a2231d09974d)

**Comment by codez** [comment]
Bei der Root Gruppe ist oberhalb des Titels eine Leerzeile drin, welche sonst bei keiner anderen Gruppe vorhanden ist. Kann diese entfernt werden?

![hit_title](https://github.com/hitobito/hitobito/assets/271590/2926b098-6dc0-42fc-b6e9-22d17be6bbe2)

**Comment by codez** [comment]
Bei der Liste der Event Participations brechen die Buttons auf kleinen Bildschirmen nicht auf eine neue Zeile um:

![hit_event_participants](https://github.com/hitobito/hitobito/assets/271590/58ec52d4-772c-4642-97ed-546a2f07ffc2)

Bei der regulären Personenliste funktioniert das gut:

![hit_people](https://github.com/hitobito/hitobito/assets/271590/50a301a8-5f5f-4f2c-afd5-d15ce03a9f2b)

**Comment by tschuepbach** [comment]
Feldbeschriftung beim OAuth-Login:
![image](https://github.com/hitobito/hitobito/assets/40494600/a2b86b9f-ea0a-40de-aea0-ea60e64e1377)

**Comment by carlobeltrame** [comment]
> Bei der Root Gruppe ist oberhalb des Titels eine Leerzeile drin, welche sonst bei keiner anderen Gruppe vorhanden ist. Kann diese entfernt werden?
> 
> ![hit_title](https://github.com/hitobito/hitobito/assets/271590/2926b098-6dc0-42fc-b6e9-22d17be6bbe2)

Das ist nur der Fall wenn du mit dem Root-User eingeloggt bist, hat nichts mit Bootstrap zu tun. Wir hatten vormals mal entschieden, diesen und weitere kleine Bugs die nur den Root User betreffen nicht zufixen, wegen dem begrenzten Nutzen. Ich hatte es mir mal angeschaut und nicht herausgefunden warum genau das so ist

**Comment by carlobeltrame** [comment]
Zumindest bei der PBS, vielleicht noch bei anderen Wagons: Wenn die Schriftarten [überschrieben](https://github.com/hitobito/hitobito_pbs/blob/master/app/assets/stylesheets/hitobito/customizable/_variables.scss#L66..L68) werden, greift das nicht mehr.

**Comment by njaeggi** [comment]
> Zumindest bei der PBS, vielleicht noch bei anderen Wagons: Wenn die Schriftarten [überschrieben](https://github.com/hitobito/hitobito_pbs/blob/master/app/assets/stylesheets/hitobito/customizable/_variables.scss#L66..L68) werden, greift das nicht mehr.

Ist bei allen Wagons, ist bei Jemk bereits gefixt, morgen werde ich noch die anderen machen, damit nächste Woche die Schtiftart auf allen Integrationen wieder übernommen wird.

Das gleiche gilt für Font-Awesome Icons und Hover Effekten für Links

**Comment by tschuepbach** [comment]
Darstellung Bullet-Points im Changelog:
<img width="117" alt="image" src="https://github.com/hitobito/hitobito/assets/40494600/c85bbdb3-fc25-43dc-89c6-22f67ee7ac6a">

![image](https://github.com/hitobito/hitobito/assets/40494600/871aade4-c5b6-4f89-8440-6adfd5f99d4c)

**Comment by njaeggi** [comment]
> Feldbeschriftung beim OAuth-Login: ![image](https://private-user-images.githubusercontent.com/40494600/297481236-a2b86b9f-ea0a-40de-aea0-ea60e64e1377.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTI5MDQsIm5iZiI6MTcwNTk5MjYwNCwicGF0aCI6Ii80MDQ5NDYwMC8yOTc0ODEyMzYtYTJiODZiOWYtZWEwYS00MGRlLWFlYTAtZWE2MGU2NGUxMzc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA2NTAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhYWFmMmY5ODlkZmJlNjI0MTBmOTZlMzljYzUyMDIwN2M5NjQ5ZjY1ZDM3MmE3ODdjNjU3YmI5NTVlZmIzY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SwXhJ3UYarh6Nf2T3eoUgzzD8PROxhxP07BOEaYDCfE)

Dieses Verhalten kann ich nicht nachstellen und wurde eventuell bereits gefixt, kann dies kurz nochmals überprüft werden?

**Comment by carlobeltrame** [comment]
> > Feldbeschriftung beim OAuth-Login: ![image](https://private-user-images.githubusercontent.com/40494600/297481236-a2b86b9f-ea0a-40de-aea0-ea60e64e1377.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTI5MDQsIm5iZiI6MTcwNTk5MjYwNCwicGF0aCI6Ii80MDQ5NDYwMC8yOTc0ODEyMzYtYTJiODZiOWYtZWEwYS00MGRlLWFlYTAtZWE2MGU2NGUxMzc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA2NTAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhYWFmMmY5ODlkZmJlNjI0MTBmOTZlMzljYzUyMDIwN2M5NjQ5ZjY1ZDM3MmE3ODdjNjU3YmI5NTVlZmIzY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SwXhJ3UYarh6Nf2T3eoUgzzD8PROxhxP07BOEaYDCfE)
> 
> Dieses Verhalten kann ich nicht nachstellen und wurde eventuell bereits gefixt, kann dies kurz nochmals überprüft werden?

Scheint behoben zu sein. Vergleiche die [Integration](https://cevi.puzzle.ch/users/sign_in?oauth=true) mit der [Produktion](https://db.cevi.ch/users/sign_in?oauth=true)

**Comment by njaeggi** [comment]
> Scheint behoben zu sein. Vergleiche die [Integration](https://cevi.puzzle.ch/users/sign_in?oauth=true) mit der [Produktion](https://db.cevi.ch/users/sign_in?oauth=true). Auch auf Mobile siehts gut aus.

Integration und Produktion haben beide bereits Bootstrap 5, bedeutet wenn etwas kaputt gegangen wäre, kann so nicht mehr überprüft werden wie es davor aussah.

Aber auch auf älteren Versionen vom master war es nicht reproduzierbar.
