### ISSUE TITLE
PEOPLE: Hauptgruppe setzten für Aktive Rolle

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito#2365]
### Aktuelles Verhalten

Die Hauptgruppe für Aktive Rollen im Profil kann nicht gesetz werden und wird auch nicht mehr mit dem Stern-Symbol im Profil angezeigt. 

![image](https://github.com/hitobito/hitobito/assets/95908537/14de36cc-be1a-41c1-94ec-6e08d65aae22)

### Gewünschtes Verhalten

Im Profil kann eine Aktive Rolle als  Hauptgruppe gesetzt werden. Die ist dann als Stern-Symbol sichtbar.

### Schritte zu reproduzieren

Profil bearbeiten, Hauptgruppe setzten für Aktive Rolle

### Wann ist der Fehler aufgetreten?

09.01.2024

### hitobito version

Version 2.0.0

### Organisation

Jubla

**Comment by richardjubla** [comment]
Das "bearbeiten" der Hauptgruppe führt zu komischer/falscher Darstellung:
![hitobito-edit-ehemalige-rolle](https://github.com/hitobito/hitobito/assets/95908537/084e8981-5719-4cd9-9357-bcfcc3d1cf89)

**Comment by ThomasEllenberger** [comment]
Konnte den Bug nachstellen.

Wir haben hier für den SAC Anpassungen im Core gemacht.
Problem ist dass bei der Jubla der `roles_aside` bei aktiven Rollen nicht mehr angezeigt wird.
Im Jubla Wagon ist der Rollen partial überschrieben, und offenbar gibt es dafür keine Testabdeckung.

Bitte schauen dass dieser wieder korrekt angezeigt wird, und wenn möglich gleich Tests dazu schreiben.

**Comment by ThomasEllenberger** [comment]
@richardjubla: Bitte testen
