### ISSUE TITLE
Selbstregistrierung: Neuer Bug

### ISSUE THREAD

**Issue by patriziajubla** [hitobito/hitobito#2373]
### Aktuelles Verhalten

Bei einer externen Registrierung wird ein externes Profil erstellt sowie auch bei Personen, die sich noch einloggen müssen (Anmelden und einschreiben). Danach entstehen Duplikate. Wenn sich die Person vorher einloggt funktioniert es korrekt.

### Gewünschtes Verhalten

Person die sich einloggt wird mit dem bereits bestehenden Profil in der Gruppe eingeschrieben.

### Schritte zu reproduzieren

1. Link für externe Registrierung anwählen
2. Vorname und Nachname eingeben da Pflichtfeld
3. Button Anmelden und Einschreiben klicken
4. Anmelden
5. Bei Gruppe unter Externe Personen erscheint ein Duplikat

### Wann ist der Fehler aufgetreten?

Version 1.30

### hitobito version

2.0.0

### Organisation

Jubla

### Screenshots, weiterer Kontext

![image](https://github.com/hitobito/hitobito/assets/141237247/1e6ae8d3-e695-49f4-8be4-1579b7e8b6ad)

**Comment by patriziajubla** [comment]
Siehe: SELF-REGISTRATION: Doppelte Mailadresse validieren #1707

**Comment by ThomasEllenberger** [comment]
Ich kann dies so auf eurer Integrationsumgebung unter Hitobito Version 2.0.3 nicht nachstellen:
Bitte auf Integration erneut testen. Könnt ihr dies da auch nachstelen, müssen wir zusammen reden, da wir offenbar unterschiedliche Dinge testen. Andernfalls gehe ich davon aus, dass sich dies mit eurem nächsten Release von Alleine löst.

**Comment by richardjubla** [comment]
**Sieht gut aus!** In der Integrationsumgebung kann ich den Fehler nicht mehr nachstellen: Über "Anmelden und Einschreiben" gelangt ein (noch) nicht angemeldetes Profil über den Login zur definierten Rolle in der Gruppe (Auch das E-Mail an die Gruppen-Leitung wird ausgelöst). Das Ticket kann aus meiner Sicht geschlossen werden.  


![image](https://github.com/hitobito/hitobito/assets/95908537/40abe514-a936-41f1-9afb-a29508ac108e)

![image](https://github.com/hitobito/hitobito/assets/95908537/f985d687-fa73-4b1f-8ac8-74cb03a3186f)
