### ISSUE TITLE
GROUPS: Einstellungen externe Registrierung

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#2374]
Aktuell wenn keine Rollen mit Schreibrechten auswählbar:

![image](https://github.com/hitobito/hitobito/assets/655627/64aba778-e74e-46f6-9e19-55bf66162342)

Neu: Die externe Registrierung kann auf dieser Gruppe nicht aktiviert werden da auf dieser keine oder nur Rollen mit Schreibrechten vorhanden sind. Tab ausblenden oder einfach alle Input Felder read-only

JSON:API - Attribute ausblenden falls nicht konfigurierbar

**Comment by sykesonrocks** [comment]
@mtnstar ich kann bestätigen, dass das Register "Externe Registrierung" nicht mehr eingeblendet wird - somit OK

![image](https://github.com/hitobito/hitobito/assets/132900428/7cf5497d-cf0b-41ba-a0dd-bcda926e3f44)
