### ISSUE TITLE
MESSAGES: Links auf mailing_lists#index werden nicht gerendert

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#2376]
Siehe auch Ticket #2370 

### Aktuelles Verhalten

Wenn ich als nicht root mich einlogge und auf die Liste der Abos gehe (Gruppen Tab Abos), dann sehe ich nur Text anstatt links um die Abos anzusehen bzw. zu bearbeiten obwohl ich Schreibrechte darauf habe.
Zugriff via Link: my-hitobito.example.com/groups/42/mailing_lists/42 funktioniert jedoch.

![image](https://github.com/hitobito/hitobito/assets/655627/d19c4bb7-7440-46a5-8c08-e6839ada8f79)

### Gewünschtes Verhalten

Es sollten klickbare Links gerendert werden falls ich Schreibrechte auf die Abos habe.

### Schritte zu reproduzieren

1. Login als non-root User mit Schreibrechten auf einer Gruppe/Abos
2. Erstellen eines neuen Abos mit 'Abo erstellen'
3. Zurück auf der Liste wird das Abo nur als Text und nicht als Link aufgelistet

Beim root-User tritt das Problem nicht auf.

### ToDos

- [ ] Berechtigungscheck fixen inkl. Spec !

**Comment by richardjubla** [comment]
@mtnstar 
Ist das ein Duplikat von https://github.com/hitobito/hitobito/issues/2370

**Comment by mtnstar** [comment]
> @mtnstar Ist das ein Duplikat von #2370

merci Richi für die Info. Ich schliesse dein Ticket #2370 mal und wir werden das mit diesem Ticket hier beheben.
