### ISSUE TITLE
Bug Import Person erscheint mehrere Male

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#238]
Infos/Beispiel CSV (echte Daten) bei @rolandstuder

**Comment by hupf** [comment]
Mail an @RolandStuder geschrieben.

Tritt auf, weil im Importierten CSV drei Einträge ohne Vor-/Nachname die gleiche Company haben. Der Doublette Finder findet dann dreimal den gleichen Eintrag.

Anpassung des Doublette Finder Mechanismus notwendig, falls dieser Fall abgedeckt werden soll. Wie weiter?

**Comment by RolandStuder** [comment]
## Folgende Situation ist problematisch

Ich mache einen CSV Import, welcher gleichlautenden Firmenbezeichnung hat z. B. "20min" aber ohne Vorname / Nachname und mit gleichem ZIP Code. Damit meint hitobito es handle sich um die gleichen Einträge wie eine Person von der Firma 20min mit dem Namen Hans Muster

Wenn wir sagen auch leere Felder sollen verglichen werden (für Nachnamen / Vorname), so dass `20min / ohne Name` und `20min / Hans Muster` **nicht matched**  wäre für das DSJ die Situation nicht wirklich gelöst. Weil dann immer noch mehrere Einträge mit `20min / ohne Name` als Duplikate gelten.

## Empfehlung Umgang mit Firmen ohne Namen

Grundsätzlich sind solche Einträge aber auch in einem Autocomplete z. B. beim Hinzufügen zu einem Abo voneinander nicht zu unterscheiden und auch in der Übersichtsliste sieht man die Unterschiede erst in der Emailadresse. Daher macht es sowieso Sinn die Firmennamen anzupassen, z. B. nach "20min Inland Redaktion"

## Lösungsideen

* Matching über E-Mail-Adresse geht nicht, da wir sonst bestehende E-Mailadressen nicht überschreiben könnten.
* Robuster: primary_key mitexportieren und bei matching verwenden:
  * Wenn primary_key in import-entry nicht vorhanden -> bisheriges matching
  * Wenn primary_key in import_entry unterschiedlich -> zwingend neuen Eintrag / kein Dupletten-Hit
  * Wenn primary_key in import_entry gleich einem bestehenden Eintrag -> bestehenden Eintrag matchen.

## Was ist Bug, was nicht?

Dass ein Eintrag `Firmenname / Ohne Name` mit `Firmenname / Hans Muster` matched entspricht kaum dem zu erwartenden verhalten. Damit könnte man diesen Teil als Bug anschauen, wobei wir eigentlich nicht ausschliessen können, dass manche Personen einen provisorischen Eintrag `20min / Ohne Name` machen, den sie später ergänzen wollen mit `20min / Hans Muster` oder sogar dass man den entfernen will.

Dass aber Einträge `Firmenname / Ohne Name`mit `Firmenname / Ohne Name` als Duplette angeschaut ist, macht inhaltlich Sinn. 

Die Erweiterung um das matching mit primary_key wäre damit sicher eine robuste Lösung, die Weiterverarbeitung und Wiederimport beliebig zulässt. Bei einem Initialimport müsste man aber immer noch aufpassen oder eben selbst ids vergeben, was aber wieder zu zufälligen matches führen könnte, weil man ja nicht weiss, welche ids frei sind.

**Comment by RolandStuder** [comment]
Relevanter Code: https://github.com/hitobito/hitobito/blob/master/app/domain/import/person_doublette_finder.rb

Ergänzung: Initialimport ist kein Problem, weil die Einträge innerhalb des Importfiles nicht miteinander gematched sind

**Comment by RolandStuder** [comment]
[Dokumentation dazu wie Duplicates gematched werden](https://github.com/hitobito/hitobito/wiki/Duplicate-Matching)

**Comment by RolandStuder** [comment]
Keine weitere Aktivität auf diesem Issues, ist zwar nicht resolved, tritt aber wohl nur speziellen Fällen auf. Wir haben selten reine Firmeneinträge ohne Namen.
