### ISSUE TITLE
ELTERNZUGANG: Mail für Anlassanmeldebestätigung wird nicht an Verwalter versendet

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#2392]
### Aktuelles Verhalten

Hat ein Kind keine Emailadresse hinterlegt, soll alle Korrespondenz stattdessen an den Verwalteraccount gehen: #1968 
Melde ich als Verwalter mein Kind welches keine Emailadresse hinterlegt hat dieses an einen Anlass an, erhalte ich keine Bestätigungsemail für die Anmeldung:
Hat mein Kind eine Email-Adresse eingetragen, wird die Bestätigungsmail korrekt an mein Kind und an mich versendet.

### Gewünschtes Verhalten

Hat ein Kind keine Emailadresse hinterlegt, und ist mit einem Verwalteraccount verknüpft so soll die Bestätigungsmail bei Anlässen korrekt an die Emailadresse des Verwalteraccounts versendet werden.
Bitte sämtliche Youth Umgebungen testen und überall beheben.

### Schritte zu reproduzieren

Als Verwalter ein Kind ohne Emailadresse an einen Anlass anmelden.

### Wann ist der Fehler aufgetreten?

31.01.2024

### hitobito version

2.0.2

### Organisation

SJAS

**Comment by richardjubla** [comment]
@patriziajubla nach Möglichkeit bitte versuchen nachzustellen.

**Comment by patriziajubla** [comment]
> @patriziajubla nach Möglichkeit bitte versuchen nachzustellen.

Getestet und funktioniert

**Comment by richardjubla** [comment]
@ThomasEllenberger 

Kann dieses Ticket wieder geöffnet werden? Siehe: https://github.com/hitobito/hitobito/issues/2816

**Comment by ThomasEllenberger** [comment]
@richardjubla Danke fürs erwähnen. 
Denke wir fixen das gleich mit dem neuen Issue und lassen dieses hier geschlossen.

**Comment by richardjubla** [comment]
@ThomasEllenberger 
Wir haben den HotFix getestet: Wenn das Kind eine Hauptemail hinterlegt hat, wird das Mail nur an das Kind versendet. Das entspricht nicht deiner Aussage wonach: _Hat mein Kind eine Email-Adresse eingetragen, wird die Bestätigungsmail korrekt an mein Kind und an mich versendet._
