### ISSUE TITLE
PBS Kürzel fehlt bei einer Person beim Export

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#24]
Schritte zum Reproduzieren:

Export von dieser Liste
https://db.scout.ch/de/groups/2/people?kind=deep&name=&role_type_ids=125

Führt bei allen Präsidenten zu einem korrekten PBS-Kürzel (Kantonalverband).
- Einzig bei https://db.scout.ch/de/groups/993/people/67559 fehlt diese Angabe
- bei allen anderen mit der Rolle Präsident bei Kantonen wird das Kürzel korrekt gezeigt
- bei allen anderen in der Ebene Thurgau wird das Kürzel korrekt gezeigt.
- Der Betroffene hat keine Gruppenzugehörigkeiten ausserhalt der Ebene/Untergruppen von Thurgau.
- Eine Anpassung des Kürzels behebt den Fehler nicht.

Original Issue: https://redmine.puzzle.ch/issues/18080 reported by Rene Brugger

**Comment by RolandStuder** [comment]
Der Fehler ist nicht abhängig vom Kantonalverband. Wir haben ein weiteres Beispiel
siehe: https://db.scout.ch/de/groups/1145/people/9429

**Comment by psunix** [comment]
fixed
