### ISSUE TITLE
Teilnehmer Liste (TN) von Anlässen als JSON API (8h) 

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#243]
siehe https://github.com/hitobito/hitobito_cevi/issues/17

**Comment by RolandStuder** [comment]
@KunoKunz Evtl. ist dies noch aktuell, auch für PBS mit dem Jahr der Digitalisierung :-)

**Comment by Michael-Schaer** [comment]
Kann m.E. geschlossen werden.
