### ISSUE TITLE
Anlässe als JSON API (14h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#244]
## Akzeptanzkriterien

* [ ] Anlässe können für authentifizierte Nutzer über ein JSON API Endpoint gefunden werden ( /groups/:id/courses /groups/:id/camps) (8h)
   * `/groups/:id/events/`
    * `/groups/:id/courses/`
   * `/groups/:id/camps/`
  _=> Welche kommen da? Pagination!_

* [ ] Pagination (inkl. Pagination Link in API Response)
* [ ] Optionaler Parameter für Gruppe und alle Untergruppen (filter=layer / filter=all) (1h)
* [ ] Optionaler Parameter schränkt Zeitraum ein (from / to, Anlässe werden eingeschlossen, wenn sich der from / to - Zeitraum mit dem Event überschneidet (2h)
* [ ] Pagination
* [ ] Response ist JSON mit allen öffentlichen Attributen
* [ ] Doku für Endpoint (grob)
* [ ] ~~Link auf TN Liste falls ich Berechtigung auf die TN Liste habe~~

## Zu besprechen:

* [ ]   _=> Wäre einfacher und konsistenter, diese Einschränkung fix einzubauen und gar keine anlassartübergreifenden Listen bereitzustellen (andere Attribute & ist jetzt bereits so)_ ? Längerfristig sollte das flexibel sein, denke ich, daher dieser Vorschlag (rs), aber ja es ist wahr, dass es nicht konsistent ist, und wir haben in der Frage "Zusammen oder Getrennt" schon Schritte in beiden Richtungen gemacht.
* [ ]  _=> Fixe Einschränkung nach Jahr wie bisher wäre ohne Zusatzaufwand möglich_ Müssen wir schauen, ich denke, es ist ein Funktion die eigentlich im UI auch fehlt.
* [x] Zu Link auf Teilnehmerliste:   _=> Link auf die Webseite oder Link auf einen noch zu bauenden JSON Endpoint?_ Macht eigentlich wenig Sinn, weglassen

**Comment by RolandStuder** [comment]
Vergleiche https://hitobito.discoursehosting.net/t/json-schnittstelle-oder-kalender-feed-fuer-anlaesse/37/5

**Comment by RolandStuder** [comment]
@codez  Bitte schätzung kurz überprüfen

**Comment by kronn** [comment]
@smathys An sich sollte es hiermit beschrieben worden sein: https://github.com/hitobito/hitobito/pull/685/commits/f8af4211022ba9977d99c18329191c31475cc83c, was jetzt ein Teil von 05_rest_api,md ist. Soweit ich weiss, ist das aber die einzige Doku.

**Comment by smathys** [comment]
@kronn Danke für den Hinweis, ich hab irgendwie nicht genau hingesehen, habe nur auf das root geschaut und gedacht, die events kommen bei /events, deshalb hab ich es nicht gesehen. sorry für die verwirrung
