### ISSUE TITLE
OPS: WAF soll status code 422 durchreichen

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito#2447]
### Aktuelles Verhalten

Seit dem Update vom Turbolinks auf Turbo (#2396) werden Forms via ajax submitted. Das führt dazu, dass der Server StatusCode 422  bei Validierungsfehler liefert und nicht wie bisher 200.

Bei Instanzen wo die WAF aktiv ist (zb. PBS) werden responses mit status code 422 rewritte und liefen dann einen unschönen HTML seite ohne dem ursprünglichen Formular

### Gewünschtes Verhalten

Status code 422 soll durchgereicht werden

### Schritte zu reproduzieren

1. Neue Gruppe ohne Namen erstellen

### Wann ist der Fehler aufgetreten?

Seit Turbo integriert ist

### hitobito version

2.0.4

### Organisation

PBS

**Comment by kronn** [comment]
Es ist mit der aktuellen WAF nicht einfach möglich, diese Responses durchzulassen. Da die WAF vorerst nur im Testbetrieb war, wurde sie vorerst deaktiviert.
