### ISSUE TITLE
COURSE: Tooltip-Text zeigt HTML-Tags an

### ISSUE THREAD

**Issue by simfeld** [hitobito/hitobito#2452]
### Aktuelles Verhalten

Die `<br>` und `<b>` tags sind Teil des Texts

![grafik](https://github.com/hitobito/hitobito/assets/9254954/26399ddd-459e-44a9-b63a-47a74ad407b6)

Das Problem liegt hier:
`<span class="badge bg-warning" rel="tooltip" title="<b>Vorbedingungen für Anmeldung sind nicht erfüllt.</b><br>Altersgrenze von 18 Jahren ist unterschritten.<br>Folgende Qualifikationen fehlen oder sind abgelaufen: J+S Leiter LS/T Jugendsport">!</span>`

### Gewünschtes Verhalten

Tooltip content sollte als HTML gerendert werden anstatt nur Text.

### Schritte zu reproduzieren

https://pbs.puzzle.ch/de/groups/1/events/1168/application_market => hover auf warning-icon

### Wann ist der Fehler aufgetreten?

wurde in PBS-internem Supportsystem am 30.12.2023 gemeldet

### Organisation

PBS

**Comment by simfeld** [comment]
Evtl. fehlt in https://github.com/hitobito/hitobito/blob/f927f7c05f3928305d7dc108da6aa0025aadcab9/app/javascript/javascripts/modules/tooltips.js.coffee#L9 die Option `html: true` (https://getbootstrap.com/docs/5.0/components/tooltips/#options) ?

**Comment by richardjubla** [comment]
@simfeld 
Ist dieser Bug ein Duplikat von https://github.com/hitobito/hitobito/issues/2416 ?

**Comment by richardjubla** [comment]
und evtl. hier: https://github.com/hitobito/hitobito/issues/2305

**Comment by ThomasEllenberger** [comment]
Closed, da Duplikat
