### ISSUE TITLE
EVENT: Anmeldeformular Pflichtfelder

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito#2466]
In unserer hitobito-Instanz und täglichen Arbeit ist uns aufgefallen, dass ein Profil für Event-Anmeldungen neu zwingend eine Haupt-E-Mail-Adresse angeben muss (Ausnahme: Profil wird von Verwalter*in angemeldet). Zudem fehlen "Fehlermeldungen" die darauf hinweisen, das Felder zwingend auszufüllen sind oder weshalb der eingegebene Wert nicht validiert werden kann. Das Formular gibt auch keine Rückmeldung, dass der Vorgang nicht gespeichert/fortgeführt werden kann.

Daher haben wir überlegt, ...

- Ist es korrekt, dass alle Profile zwingend eine Haupt-E-Mail-Adresse für eine Event-Anmeldung benötigen? (wenn nicht Verwaltet oder durch Event-Verwalter "übersteuert" angemeldet)
- Ist es ein Bug, dass Pflichtfelder für den User nicht sichtbar validiert werden?

Was meint die Community dazu?

Aus unserer Sicht ist es vertretbar, dass ein Profil für einen Event zwingend eine Haupt-E-Mail-Adresse benötigt. Es ist eine Ausnahme und nicht "normal", dass ein Profil überhaupt zu einem Event kommt, wenn es keine eigene Haupt-E-Mail-Adresse hat.
Die Haupt-E-Mail-Adresse muss aber zwingend fehlen können, wenn das Profil durch einen Event-Verwalter oder einen Verwalter*in für den Event angemeldet oder hinzugefügt wird. 

Die Pflichtfelder müssen aus unserer Sicht zwingend eine Fehlermeldung produzieren, falls sie nicht oder nicht korrekt ausgefüllt sind. Zudem müsste auch die korrekte form/Validierung des Feldes angezeigt werden. Die Tel. Nr. oder AHV-Nr. ist hier ein gutes Beispiel: Es werden nur validierte und explizit "korrekte" Werte akzeptiert. Der User sieht aber nicht, wie und wo der Fehler liegt.

# ToDo, um die Diskussion zu starten

- [ ] andere Organisationen hier erwähnen (@ und github-usernamen)

# ToDo, nachdem die Diskussion ein Ergebnis hat

- [ ] Diskussionsergebnisse zusammenfassen
- [ ] Issue für Umsetzung erstellen
- [ ] ggf. Mockup erstellen
- [ ] Tech-Spec ergänzen
- [ ] ToDo für Umsetzung definieren

Bilder/Gif

Fehler: Button für Weiter funktioniert nicht, keine Fehlermeldung oder Rückmeldung
![hitobito-event-anmeldung](https://github.com/hitobito/hitobito/assets/95908537/3dc3b46f-a1c5-4697-99a2-10544cc31894)

**Comment by amaierhofer** [comment]
Die fehlden Fehlermeldungen sind leider mit dem Turbo upgrade reingekommen und wurde mit f9ef60e96cf2d5803e3e96019ecc9e9a080a2c39 auf master bereits behoben. Mit #2575 wird dieses Problem noch an anderen stellen behoben.

**Comment by richardjubla** [comment]
> Die fehlenden Fehlermeldungen sind leider mit dem Turbo upgrade reingekommen und wurde mit [f9ef60e](https://github.com/hitobito/hitobito/commit/f9ef60e96cf2d5803e3e96019ecc9e9a080a2c39) auf master bereits behoben. Mit #2575 wird dieses Problem noch an anderen stellen behoben.

Danke! Das höre ich gerne. Nehme das gerne auf als Überlegung für einen eigenen Release (wegen Lageranmeldungen vor dem Sommer und so...).
