### ISSUE TITLE
oAuth von hitobito bereitstellen (16h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#247]
## Akzeptanzkriterien

* [ ] hitobito bietet sich als oAuth Instanz an.
* [ ] Eine externe Applikation kann einen Benutzer via oAuth authentifizieren, der Benutzer erhält einen Dialog, wo der Benutzer das Login bestätigen kann (falls er schon in hitobito eingeloggt ist) oder sich noch in hitobito einloggen kann und dann den Login bestätigen kann, vgl. Twitter / Gmail oAuth
* [ ] Die aufrufende Applikation erhält die Personendaten dieser Person und das Authentication Token fürs APIs)

**Comment by codez** [comment]
Siehe https://github.com/doorkeeper-gem/doorkeeper

**Comment by RolandStuder** [comment]
Aus Sicherheitsgründen, muss man Whitelisten welche Applikationen APIs Tokens erhalten dürfen, weil die ja via API Token sehr viel Zugriff haben, je nach dem wer sich damit einloggt.

**Comment by bergerar** [comment]
Bis wann ist eine Umsetzung geplant? 
Zurzeit kreiere ich eine neue Webseite, welche ein Login Möglichkeit über die Datenbank anbieten soll. Dazu möchte ich ungern die alte API einsetzten....

**Comment by RolandStuder** [comment]
Wir wissen es nicht, wahrscheinlich wird es von einer Person der Pfadi Schweiz gemacht und wir werden es reviewen @diegosteiner hast du schon einen Plan?

**Comment by diegosteiner** [comment]
Ich werde einen ersten Entwurf bis Ende Jahr zusammenstellen, auf dessen Basis die weitere Umsetzung diskutiert werden kann. Es wird noch einige Fragen zu klären geben. Danach werden weitere Arbeiten und das Codereview auch noch mal einige Zeit in Anspruch nehmen. 

@bergerar: Bis man damit rechnen kann, dass OAuth auf einem Produktivsystem ausgerollt ist wird also sicherlich Mitte des kommenden Jahres.

**Comment by hannessolo** [comment]
Ich hätte auch Interesse an diesem Feature.

@diegosteiner Gibt es schon einen aktiven Branch, wo man beitragen könnte? Oder ist das Feature noch hauptsächlich in Planung?

**Comment by diegosteiner** [comment]
Es hat inzwischen hitobito-interne Bewegung zu diesem Thema gegeben. @RolandStuder : Könntest du hier ein Statement dazu abgeben? Danke!

**Comment by KunoKunz** [comment]
Bei Puzzle steht momentan auch Keycloak im Gespräch. @diegosteiner konntest du deinen Entwurf zusammenstellen?

**Comment by diegosteiner** [comment]
Ich habe mal einen Branch mit [Doorkeeper](https://github.com/doorkeeper-gem/doorkeeper) angefangen:

https://github.com/diegosteiner/hitobito/compare/e31c35e7406c1c375f9d28ec9bbdb64f776ff2ae...feature/oauth-provider

Das gem eignet sich meiner Meinung nach gut. Für mich liegen die Herausforderungen an den folgenden Orten:

- Da es doch ein ziemlicher Eingriff ist fände ich es sinnvoll, wenn jemand aus dem Coreteam die Implementation übernehmen würde, insbesondere auch die automatisierten Tests.
- Damit die Konfiguration des Providers möglich wird müssen noch einige Views umgesetzt werden.

**Comment by diegosteiner** [comment]
Was ich hierzu von Seite PBS noch wichtig finde:

- hitobito bietet sich als OAuth Instanz an, speichert also die Email-Adresse und das Passwort selbst bei sich, während andere Applikationen die Authentifizierung an hitobito abgeben könnten.
- Es gibt für den Anfang nur einen oder zwei Scopes; Der "Default" Scope erlaubt es angemeldeten Usern lediglich die eigene Email auszulesen. Ein zweiter Scope "Person" würde es erlauben, alle Infos zum eigenen Personendaten und die Rollen in Gruppen auszulesen. Weitere Scopes könnten dann folgen. Mehr zu Scopes: https://github.com/doorkeeper-gem/doorkeeper/wiki/Using-Scopes
- Jeder Kunde (z.B. die PBS) kann definieren, welche Applikationen (bzw. welche Domains) sich per OAuth anbinden können. Doorkeeper bringt hierzu eigentlich schon alles mit, es muss einfach noch gestylt werden. Es soll auch möglich sein, alle Domains zu erlauben, zumindest mit dem Default Scope
- Später soll auch pro whitegelistete Applikation definiert werden können, welche Scopes erlaubt sind.

Desweiteren (betrifft aber alle APIs):
- Ich fände es noch wichtig, dass wir eine Beschränkung der req/min vorsehen. Es wäre schade, wenn diese Schnittstellen missbraucht oder überbelastet würden. Rack::Attack wäre hier eine Option: https://github.com/kickstarter/rack-attack

@carlobeltrame : Hast du noch Ideen/Ergänzungen?

**Comment by carlobeltrame** [comment]
Klingt schon mal sehr sinnvoll. Optimal für eCamp und wohl auch andere Drittapplikationen in unserer Organisation wäre ein Scope der nur E-Mail, Vorname, Nachname und wenn möglich Pfadiname (nickname) enthält. So könnte man den User nicht nur identifizieren, sondern auch im UI korrekt ansprechen, ohne Zugriff auf sensible Personendaten wie z.B. das Geburtsdatum oder den Wohnort. Aber ich sehe die Motivation, ähnliche Scopes wie die Google OAuth Scopes userinfo.email und userinfo.profile einzuführen, und mit einer solchen Lösung können wir definitiv arbeiten.

**Comment by Michael-Schaer** [comment]
Merci für euere Rückmeldungen! Ich fasse die Akzeptanzkriterien zusammen:

- [ ] hitobito bietet sich als OAuth Instanz an, speichert also die Email-Adresse und das Passwort selbst bei sich, während andere Applikationen die Authentifizierung an hitobito abgeben könnten.

- [ ] Es gibt für den Anfang drei Scopes zur Steuerung der Angaben, die zur angemeldeten Person übermittelt werden:
 1. "Default": E-Mail
 2. "Name": E-Mail, Vorname, Nachname, Pfadiname
 3. "Person": Alle eigenen Personendaten und Rollen in Gruppen

- [ ] Jeder Kunde (z.B. die PBS) kann definieren, welche Applikationen (bzw. welche Domains) sich per OAuth anbinden können. Es soll auch möglich sein, alle Domains zu erlauben, zumindest mit dem Default Scope

- [ ] Um Missbrauch und Überlastungen zu verhindern, soll eine Beschränkung der Requests/min eingebaut werden.

#### Gem-Vorschläge und Übergabe von Filou:
- Doorkeeper bringt für die Scopes/Whitelist eigentlich schon alles mit, es muss einfach noch gestylt werden. 
- Später sollen weitere Scopes dazukommen und pro whitegelistete Applikation definiert werden können, welche Scopes erlaubt sind. Mehr zu Scopes: https://github.com/doorkeeper-gem/doorkeeper/wiki/Using-Scopes
- Rack::Attack wäre eine Option, um die Anzahl Requests zu steuern: https://github.com/kickstarter/rack-attack

**Comment by amaierhofer** [comment]
Ein erster Wurf ist jetzt auf PBS integration deployed. Ich hoffe das UI ist einigermassen selbsterklärend. Folgendes ist bereits umgesetzt

- Verwalten von OAuth Application für Admins (unter Einstellungen)
- Auth Workflow (AccessGrants / AccessTokens)
- Profile Endpoint um scope spezifische Attribute der Person zu lesen

Offen
- Branding vom Autorisierungs Screen
- Request Throttling?

**Comment by Michael-Schaer** [comment]
Für mich sieht es so aus, als würde der Auth Workflow zwar funktionieren, der Zugriff über die Tokens jedoch nicht.

Wenn ich mit Curl das Profil abgreifen will, erhalte ich einen 401er mit Doorkeeper error="invalid_token":
https://pastebin.com/QeLVEicN

Verwendete Test-Applikation:
https://pbs.puzzle.ch/de/oauth/applications/5

**Comment by amaierhofer** [comment]
@Michael-Schaer  Danke fürs testen. Du musst mit dem Autoriserungs token erst einen [`Authoriziation Code Request`](https://www.oauth.com/oauth2-servers/access-tokens/authorization-code-request/) durchführen. Erst dieser liefert das eigentliche Access Token, welches dann auf dem profiles endpoint verwendet werden kann. Für das von mir generierte Autorisierungs token sieht das wie folgt aus. 

`
curl  -H 'Accept: application/json' -X POST -d 'grant_type=authorization_code' -d 'client_id=fec5519765de7f30c9017b46697bcb4071846e84374254287087f59869b97eca' -d 'client_secret=2e1a8ef6676e3b9a13a75a7e6ae55879a02b8a5194af010dd8af0eb1a2ca0957' -d 'redirect_uri=urn:ietf:wg:oauth:2.0:oob' -d 'code=bdfdbcd1d398b26cbcb82e3f3b7ae7e811829f1873de99b2017f72cfdba469ac' https://pbs.puzzle.ch/oauth/token
`

`client_id`, `client_secret`, `redirect_uri` sind auf der applikation definiert, der `code` parameter entspricht deinem individuellen Autorisierungs Token.

**Comment by Michael-Schaer** [comment]
Merci für die Rückmeldung. Mit Curl und Python konnte ich den Prozess jetzt schon mal durchspielen, das hat soweit geklappt. Mit dem Scope "email" kommt dann auch ein JSON-Array zurück, das ich auslesen kann. 

Hier noch mein Python Example mit requests_oauthlib, falls das jemand zum Testen gebrauchen kann:
https://pastebin.com/LU1zbN4Z

**Comment by carlobeltrame** [comment]
Ich konnte OAuth nun auch grundsätzlich erfolgreich einmal durchtesten, mit einer Drittapplikation unter Entwicklung (ecamp3-oauth.gloggi.ch). Einige Dinge die mir noch aufgefallen sind:
* Dass nur HTTPS redirect URIs erlaubt sind ist sicher sinnvoll, aber das Testen und Entwickeln könnte um einiges einfacher sein, wenn beim Hostnamen `localhost` (mit beliebigem Port) ausnahmsweise auch HTTP erlaubt wäre
* Die verfügbaren Scopes sollten irgendwo aufgelistet sein: `email`, `name`, `with_roles`, `api_access`
* Momentan scheint nur der `email` Scope zu funktionieren, ich bekomme nie mehr als die Mailadresse
* Im Admin-Interface im Feld Redirect URI kann eine Whitelist von URIs eingetragen werden. Dies sollte entsprechend gelabelt werden, zumindest URIs überall in Mehrzahl, vielleicht noch ein Hinweis dass ein URI pro Zeile eingegeben werden kann.
* Die Liste mit OAuth Zugangstokens kann schnell mal sehr lang werden. Vielleicht sollte diese paginated oder asynchron geladen werden.
* Die Liste mit aktiven OAuth Autorisierungen scheint momentan noch nicht zu funktionieren, diese war bei mir jedenfalls immer leer, egal in welchem Zustand ich gerade Autorisierungen offen hatte

**Comment by amaierhofer** [comment]
Danke @carlobeltrame  für dein Feeback. 
> Ich konnte OAuth nun auch grundsätzlich erfolgreich einmal durchtesten, mit einer Drittapplikation unter Entwicklung (ecamp3-oauth.gloggi.ch). Einige Dinge die mir noch aufgefallen sind:
> 
> * Dass nur HTTPS redirect URIs erlaubt sind ist sicher sinnvoll, aber das Testen und Entwickeln könnte um einiges einfacher sein, wenn beim Hostnamen `localhost` (mit beliebigem Port) ausnahmsweise auch HTTP erlaubt wäre

Für das lokale testen wäre es einfacher, wenn du Anpassung direkt vornimmst, siehe https://github.com/hitobito/hitobito/blob/f4e6fd7f0cb3a50fb1a2b81f3dd27efa41515f81/config/initializers/doorkeeper.rb#L137
> * Die verfügbaren Scopes sollten irgendwo aufgelistet sein: `email`, `name`, `with_roles`, `api_access`

Habe ich entsprechend ergänzt

> * Momentan scheint nur der `email` Scope zu funktionieren, ich bekomme nie mehr als die Mailadresse

Konnte ich nicht nachvollziehen, bei mir wurde der im  `X-Scope` Header definiert scope berücksichtigt. Hast du hier ein konkretes Beispiel auf der Integrationsumgebung? 
> * Im Admin-Interface im Feld Redirect URI kann eine Whitelist von URIs eingetragen werden. Dies sollte entsprechend gelabelt werden, zumindest URIs überall in Mehrzahl, vielleicht noch ein Hinweis dass ein URI pro Zeile eingegeben werden kann.

Habe ich entsprechend ergänzt
> * Die Liste mit OAuth Zugangstokens kann schnell mal sehr lang werden. Vielleicht sollte diese paginated oder asynchron geladen werden.

Ja, kann ich bei nächster Gelegenheit machen.

> * Die Liste mit aktiven OAuth Autorisierungen scheint momentan noch nicht zu funktionieren, diese war bei mir jedenfalls immer leer, egal in welchem Zustand ich gerade Autorisierungen offen hatte

Diese Liste Zeigt die momenten offenen Autorisierungstoken. Das token verschwindet wieder aus der liste, sobald damit ein Zugangstoken erstellt wurde oder die hinterlegte Gültigkeitsdauer von 10 Minuten abgelaufen ist.

Ich denke es wäre sinnvoll, wenn wir hier noch *die noch umzusetzten Punkte* festhalten

*  [ ] Bessere beschriebung der Autorisierungs Tokens (Offene Autorisierungs Tokens?)
*  [ ] Page von Zugsangstoken (diese Liste kann sehr lang werden)

**Comment by carlobeltrame** [comment]
> > * Dass nur HTTPS redirect URIs erlaubt sind ist sicher sinnvoll, aber das Testen und Entwickeln könnte um einiges einfacher sein, wenn beim Hostnamen `localhost` (mit beliebigem Port) ausnahmsweise auch HTTP erlaubt wäre
> 
> Für das lokale testen wäre es einfacher, wenn du Anpassung direkt vornimmst, siehe
> 
> https://github.com/hitobito/hitobito/blob/f4e6fd7f0cb3a50fb1a2b81f3dd27efa41515f81/config/initializers/doorkeeper.rb#L137

Da hatte ich mich wohl nicht genügend genau ausgedrückt. Ich meinte nicht hitobito lokal, sondern Drittapplikationen die die hitobito-OAuth-Schnittstelle nutzen sollen. Mein Anliegen ist es, dass eine lokale Drittapplikation unter Entwicklung die hitobito-Integrationsumgebung ansprechen kann, und somit die callback-URI auch http://localhost:xxxx sein kann. Nun ist aber SSL enforced für alle callback URIs, und das bedeutet dass ich entweder lokal einen reverse SSL proxy mit self-signed certificate laufen lassen muss (mühsamer Setup), oder die Drittapplikation irgendwo hosten muss und etwa mit Let's encrypt SSL dafür einrichten muss (mühsam für Entwicklung und Debugging).
Ich weiss aber nicht, ob es dafür einen einfachen Fix gibt, ist wohl auch kein Showstopper (ich habe inzwischen beide Optionen genutzt). Deine Lösung, selber eine hitobito-Instanz aufzusetzen, sehe ich aber als noch mehr Aufwand als den reverse Proxy (ich würde ja auch nicht ein lokales Google OAuth System aufsetzen nur um meine Drittapplikation an Google OAuth anzubinden).

> > * Momentan scheint nur der `email` Scope zu funktionieren, ich bekomme nie mehr als die Mailadresse
> 
> Konnte ich nicht nachvollziehen, bei mir wurde der im `X-Scope` Header definiert scope berücksichtigt. Hast du hier ein konkretes Beispiel auf der Integrationsumgebung?

Tatsächlich, wenn ich im X-Scope-Header auf dem profile request einen Scope mitschicke klappts. Nur den api_access Scope konnte nicht zum Laufen bringen, ich habe dort nie mehr gesehen als mit with_roles, auch wenn ich API-Tokens besitze (selber erstellt, also sicher zum richtigen User gehörend). Habe getestet mit https://pbs.puzzle.ch/de/oauth/applications/7 und den Accounts hussein_kohlmann@hitobito.example.com (hat ein Token auf dem Dachverband) sowie letizia_wilhelm@hitobito.example.com (hat ein Token auf https://pbs.puzzle.ch/de/groups/511)

**Comment by kronn** [comment]
> > > * Dass nur HTTPS redirect URIs erlaubt sind ist sicher sinnvoll, aber das Testen und Entwickeln könnte um einiges einfacher sein, wenn beim Hostnamen `localhost` (mit beliebigem Port) ausnahmsweise auch HTTP erlaubt wäre

Es sollte jetzt möglich sein, gegen die Integrationsumgebung der PBS (pbs.puzzle.ch) oAuth-Tests aus von localhost via HTTP zu machen.

**Comment by carlobeltrame** [comment]
Super, funktioniert gemäss meinen Tests so, danke! (im RedirectURIs Feld muss man http://localhost... inklusive http:// eintragen)

**Comment by carlobeltrame** [comment]
Bleibt somit nur noch der api_access Scope, habe ich da etwas falsch verstanden?

**Comment by Michael-Schaer** [comment]
Super, merci! Ich sehe noch zwei offene Punkte:

- [ ] Scope "api_access" 
- [ ] Pagen von Zugsangstoken (diese Liste kann sehr lang werden)

Weiter sollten wir die beiden Neulinge "Service API" und "OAuth" noch ausführlich und wenn möglich in Englisch beschreiben. Dem würde ich mich sonst nächste Woche mal annehmen, da das nicht in den Abnahmekriterien drin ist.

**Comment by kronn** [comment]
Der Scope `api_access` sagt mir hier leider nichts und ich finde auch nicht genug, um das umzusetzen. Welche Attribute sollen da zurückkommen?

**Comment by Michael-Schaer** [comment]
Merci fürs Nachfragen Matthias! Der Scope api_access macht eigentlich keinen Sinn. Das OAuth-API soll unabhängig vom "alten" JSON-API bleiben, damit wir den Zugriff auch sauber steuern können. 
-> Diesen Scope bitte entfernen.

Dann sind mir noch zwei Sachen aufgefallen, die M.E. noch nicht ganz stimmen. Da wäre ich auch um Feedback von euch froh.

#### Authorization Code Grant
Der "email" Scope muss beim initialen Authorization Code Request immer angegeben werden. Die beiden Scopes "with_roles" und "name" können also nicht für sich stehen. 

Das finde ich an sich kein Problem, allerdings müsste dann die Authorisierung verhindert werden, wenn ein Scope ohne "email" angefordert wird. [Dieser Request macht zum Beispiel keinen Sinn.](https://user-images.githubusercontent.com/1799621/59423020-9ccef180-8dd1-11e9-902c-996177b0e72f.png)

Ausserdem müsste die Beschreibungen ([Applikation](https://pbs.puzzle.ch/de/oauth/applications/5) und [Authorisierung](https://user-images.githubusercontent.com/1799621/59421801-7f008d00-8dcf-11e9-8a78-683b71e7d6e6.png)) noch angepasst werden:

> (email) Lesen deiner E-Mail Adresse
> **(name) Lesen deines Vor- und Nachnamens** 
> (with_roles) Lesen deiner Stammdaten und Rollen

Hier noch ein Code-Beispiel für den beschriebenen Fall:
https://pastebin.com/tvNJrtjr (Scopes in Zeile 2)

#### Encodings
Wenn ich "with_roles" bei hussein_kohlmann@hitobito.example.com ausgebe, stimmen die Encodings nicht (PowerShell mit utf-8, Curl for windows)
~~~~
 {"role_name": "Pr├ñsident", "group_name": "Pfadibewegung Schweiz"},
~~~~

**Comment by kronn** [comment]
Den scope api_access werde ich dann entfernen, merci für die Klarstellung. (Es tut gut, sowas aufzuräumen :smile: )

Bezüglich des Authorization Grant bist du auf einen anderen Fehler gestossen. Es soll schon so sein, dass man sich nur für `name` oder `with_roles` einen grant holen kann. Die Prüfung ging aber immer NUR gegen den email-scope. Dies passe ich noch an.

**Comment by Michael-Schaer** [comment]
Ok, merci! Ich glaube jetzt verhalten sich die drei Scopes so, wie wir sie spezifiziert haben.

Noch zwei Dinge:
1. Im GUI müsste man dann noch die Beschreibung vom 4ten Scope entfernen:
"Lesen deiner Stammdaten, Rollen und Api Tokens (api_access)"
z.B. hier: https://pbs.puzzle.ch/de/oauth/applications/5

2. Die Encodings stimmen bei mir noch nicht

**Comment by amaierhofer** [comment]
Die übrig gebliebenen Scopes habe ich auf Integration entfernt. Das Problem mit den Encodes habe mit curl nicht. Eventuell erwartet dein Client ein anderes Encoding als UTF-8. 
[encoding_example.txt](https://github.com/hitobito/hitobito/files/3354523/encoding_example.txt)

**Comment by Michael-Schaer** [comment]
Merci für die Korrektur! Abnahme PBS ist erfolgt.
