### ISSUE TITLE
UI: UI Fehler

### ISSUE THREAD

**Issue by philobr** [hitobito/hitobito#2477]
### Aktuelles Verhalten

_in der mobilen Ansicht:_
- [x] **Mobile_Bestand:** In der Anzeige "Bestand" einer Ebene geht diese über die Breite des Bildschirmes hinaus und man kann nicht horizontal scrollen
- [x] **Mobile_Statistik:** ähnliches Problem
- [x] **Mobile_Kurs-Anwesenheit:** ähnliches Problem
- [x] **Mobile_Übersicht-Kurse:** ähnliches Problem
- [x] **Mobile_Kurs-Anmeldung und Mobile_Kurs-Anmeldung-2:** In der Ansicht einer Kursanmeldung werden einige Dinge gemäss Bilder nicht korrekt dargestellt (Name und Standortnadel, Qualifikationen, Anmeldeprioritäten, Empfehlungen)
- [x] **Mobile_Rollen-Verlauf:** visuelle Überlagerung der Rolle und des Startdatums
- [x] **Mobile_Geschwister-Indent:** In der Personenansicht ist der Punkt "Geschwister in ..." nicht ausgerichtet auf die anderen Punkte

_in der Laptop Ansicht_
- [x] **Laptop_Kursdaten:** Bei einem Kurs werden beim Bearbeiten die Felder für das Start- und Enddatum nicht richtig angezeigt (nur in der Testumgebung, nicht in der Produktion!)
- [x] **Laptop_Aboadresse:** Ebenfalls nur in der Testumgebung ist das Feld der Mailadresse eines Abos zu klein, wenn ich dieses bearbeiten möchte.

### Gewünschtes Verhalten

gem oben.

### Schritte zu reproduzieren

Alles in der Integration, keine speziellen Anpassungen

### hitobito version

2.0.4

### Organisation

PBS

### Screenshots, weiterer Kontext

[Mobile_Bestand](https://github.com/hitobito/hitobito/assets/122129110/84979c10-2de3-4db4-b526-85daa2fc59b4)

[Mobile_Statistik](https://github.com/hitobito/hitobito/assets/122129110/1d0addb8-b4dd-4854-877c-c5663a4d04ed)

[Mobile_Kurs-Anwesenheit](https://github.com/hitobito/hitobito/assets/122129110/d4bd7618-60e9-466b-b650-fe6f8c8a7ddf)

[Mobile_Übersicht-Kurse](https://github.com/hitobito/hitobito/assets/122129110/2cc0366f-6cfa-4db0-be74-667eae4062e0)

[Mobile_Kurs-Anmeldung](https://github.com/hitobito/hitobito/assets/122129110/b43b4337-9bca-4bb0-986d-888779d93570)
[Mobile_Kurs-Anmeldung-2](https://github.com/hitobito/hitobito/assets/122129110/aa4e5eca-ca88-4378-85d6-9c47aa8f55c9)

[Mobile_Rollen-Verlauf](https://github.com/hitobito/hitobito/assets/122129110/6a0fd8c2-076d-455b-b4a9-7482d2d9f13e)

[Mobile_Geschwister-Indent](https://github.com/hitobito/hitobito/assets/122129110/101e21cf-9d86-46b2-839a-05d5bf365832)

[Laptop_Kursdaten](https://github.com/hitobito/hitobito/assets/122129110/28501bba-d6f4-4d3e-a5ca-e5329a46add8)

[Laptop_Aboadresse](https://github.com/hitobito/hitobito/assets/122129110/ff618595-8f9a-4103-a5df-cbecd3b9ccab)

@ThomasEllenberger gem. Absprache im Hackathon

**Comment by njaeggi** [comment]
- Laptop_Kursdaten: Bei einem Kurs werden beim Bearbeiten die Felder für das Start- und Enddatum nicht richtig angezeigt (nur in der Testumgebung, nicht in der Produktion!)

Sollte bereits gefixt worden sein, ich kann es nicht so reproduzieren, kann das nochmals überprüft werden?

**Comment by philobr** [comment]
> * Laptop_Kursdaten: Bei einem Kurs werden beim Bearbeiten die Felder für das Start- und Enddatum nicht richtig angezeigt (nur in der Testumgebung, nicht in der Produktion!)
> 
> Sollte bereits gefixt worden sein, ich kann es nicht so reproduzieren, kann das nochmals überprüft werden?

Ah ja, scheinbar geht das wieder, bei mir tritt der Fehler auch nicht mehr auf...
