### ISSUE TITLE
Verschiedene Freitextattribute werden falsch exportiert.

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#25]
Bei Export von Kontakten (mit allen Angaben) werden auf der Version vom Cevi verschieden Attribute fehlerhaft exportiert.

z. B. Korrespondenzsprache: 

translation missing: de.activerecord.attributes.person.correspondence_languages.Deutsch

und Anrede

translation missing: de.activerecord.attributes.person.salutations.Herr
- Die Fehler treten nur auf, wenn man einen Eintrag macht auf den eine Übersetzung zu erwarten wäre (also z. B: Deutsch, respektive Herr). Bei anderen Strings z. B. DE oder Du kommt kein solcher Fehler.

original issue: https://redmine.puzzle.ch/issues/11002 von Carbon

z. B. bei http://cevi.puzzle.ch/groups/1/people?returning=true siehe Korrespondenzsprache im Full Export

**Comment by kronn** [comment]
ist bereits im master behoben, siehe https://github.com/hitobito/hitobito_cevi/commit/0adecf2da92cc99313c9e6c9aa3245a5e40af775
