### ISSUE TITLE
ELTERNZUGANG: Elternzugang und Datenschutzerklärung funktionieren nicht gemeinsam

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito#2502]
### Aktuelles Verhalten

Wenn ein Verwalter versucht ein Kind zu einem Anlass anzumelden, das die Datenschutzerklärung noch nicht akzeptiert hat, wird beim weiterklicken nach dem erfassen der Kontakt-Daten (und der Zustimmung zur Erklärung) ein 500er ausgelöst.

### Gewünschtes Verhalten

Die Anmeldung funktioniert ohne Fehler.

### Schritte zu reproduzieren

1. Manager und Kind vorbereiten (sicherstellen, dass `kind.privacy_policy_accepted? == false`)
2. Falls nötig Anlass vorbereiten
3. Manager imitieren
4. Kind anzumelden versuchen

### Wann ist der Fehler aufgetreten?

in der Produktion bei ersten Anmeldungen zu Auffahrtslagern

### hitobito version

2.0.0 / commit cfff477a622847 (Master von Anfang Woche)

### Organisation

Cevi

### Screenshots, weiterer Kontext

Das Problem ist

``` 
def privacy_policy_param
    params[:event_participation_contact_data][:privacy_policy_accepted]
end
```

(in `app/controllers/event/participation_contact_datas_controller.rb`)
Denn bei einer Managed-Anmeldung sind die Daten in `event_participation_contact_datas_managed` (btw. `datas` hat ein unnötiges/inkonsistentes `s`)

Korrekt wäre deshalb wohl z.B.

```
def privacy_policy_param
  if params.key?("event_participation_contact_data")
    params[:event_participation_contact_data][:privacy_policy_accepted]
  else 
    params[:event_participation_contact_datas_managed][:privacy_policy_accepted] 
  end
end
```

Die Änderung im Core löst das Problem. Da der Elternzugang aber im Youth  wagon ist, und das relevante File dort noch nicht existiert (und ich noch nie neue Files überschrieben habe), ist ein Pull-Request zu aufwändig. Deshalb nur hier als Report.

@ThomasEllenberger: Der fix muss unbedingt in das nächste Release, der Bug macht den Elternzugang unbrauchbar und betrifft wahrscheinlich alle Verbände.

**Comment by ThomasEllenberger** [comment]
@nchiapol Der Bug sollte behoben und der Fix ab heute auf eurer Integration sein.
Kannst du dies testen, ob das bei euch wieder funktioniert?

**Comment by nchiapol** [comment]
Hab das eben auf unserer Integration getestet, funktioniert in meinem Test.
