### ISSUE TITLE
Events: Fehlende Antwort bei Anmeldeangaben wird nicht hervorgehoben.

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito#2524]
### Aktuelles Verhalten

Wir beim Anmelden auf dem zweiten Tab mit den Anmeldeangaben eine Pflicht-Frage nicht beantwortet, erscheint zwar eine Meldung. Die relevante(n) Frage(n) werden aber nicht mehr hervorgehoben.
![screenshot_2024-03-24_233423](https://github.com/hitobito/hitobito/assets/1123483/6585132e-647b-4437-bfa5-1d90709e1014)

Früher wurden die fehlenden Fragen eingefärbt. (vgl. Screenshot in https://github.com/hitobito/hitobito/issues/2161)

### Gewünschtes Verhalten

fehlende Fragen werden hervorgehoben.

### Schritte zu reproduzieren

1.   Für Kurs Anmelden
2.  Bewusst ein zwingendes Feld (Pflichtfeld) nicht ausfüllen

### hitobito version

2.0.4

### Organisation

Cevi

**Comment by nchiapol** [comment]
@thomasellenberger evtl. passt das noch in die Fixes für den Release. Ist möglicherweise auch ein Bootstrap-Problem.

**Comment by richardjubla** [comment]
Verbindung mit https://github.com/hitobito/hitobito/issues/2466 
Die Pflichtfelder werden auch auf der ersten Seite (Kontaktangaben) nicht korrekt validiert.
