### ISSUE TITLE
PEOPLE: Personenimport - Vorschau nicht mehr möglich

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#2557]
### Aktuelles Verhalten

Will man einen Personenimport machen, so ist dies nicht mehr möglich.
Man kann zwar noch eine CSV-Datei hochladen, sobald man jedoch auf "Vorschau" klickt, erscheint diese nicht mehr.
Getestet in Saas/ PBS/ SAC/Digisus-Lab

### Gewünschtes Verhalten

Personenimporte via CSV-Files können wieder korrekt gemacht werden.

### Schritte zu reproduzieren

1. in beliebiger Gruppe "Liste importieren"
2. CSV Auswählen & Hochladen
3. Alles einstellen und auf "Vorschau" klicken.
4. ... nichts passiert

### Wann ist der Fehler aufgetreten?

05.04.2024

### hitobito version

2.1.3

### Organisation

Core

### Screenshots, weiterer Kontext

![grafik](https://github.com/hitobito/hitobito/assets/100761305/8b737510-f4d1-4979-b406-23c5d0423d82)

**Comment by tschuepbach** [comment]
Kann ich in der Cevi-Umgebung auch bestätigen.
