### ISSUE TITLE
EVENT: Kontaktperson Suche ist Flake

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito#2565]
### Aktuelles Verhalten

Teilweise funktioniert die Suche im Feld "Kontaktperson" beim Bearbeiten eines Kurses nicht, d.h. es erscheint kein Dropdown mit Vorschlägen:

![321971412-f46fb9d4-9c68-48c2-981f-6c6385704b27](https://github.com/hitobito/hitobito/assets/271590/e7c3e631-fbe9-4c1c-99fb-d238590da67c)

Das Verhalten ist leider nicht konstant reproduzierbar, normalerweise erscheinen die Vorschläge. Es gilt herauszufinden, wie das zustande kommt (oder ob das allenfalls kürzlich gefixt wurde):

### Gewünschtes Verhalten

Vorschläge erscheinen immer

### Schritte zu reproduzieren

* Kurs bearbeiten
* Im Feld "Kontaktperson" Name einer existierenden Person eingeben
* Es erscheinen keine Vorschläge

### Wann ist der Fehler aufgetreten?

10.4.24

### Organisation

SAC

**Comment by tobiasstern** [comment]
Um den Fehler zu reproduzieren, muss man das Formular in einen ungültigen Zustand bringen i.e. dass oben ein Fehler angezeigt wird.

**Comment by amaierhofer** [comment]
Ist ebenfalls ein Turbo Upgrade Problem, siehe https://github.com/hotwired/turbo/issues/85#issuecomment-756191950

**Comment by richardjubla** [comment]
Die Suche (turbo-progress-bar) ist aus meiner Sicht ebenfalls betroffen. Braucht es dazu ein eigenes Ticket?

**Comment by amaierhofer** [comment]
@richardjubla Danke für den Hinweis. Ich habe dafür https://github.com/hitobito/hitobito_jubla/issues/94 bei euch im Projekt erstellt. Die Umsetzung am Besten mit den PLs koordinieren.

**Comment by codez** [comment]
> eventuell umstellen auf https://www.npmjs.com/package/stimulus-autocomplete

Das wäre sicher ein eigenes Ticket. Scheint das der vielversprechendste Ansatz ein entsprechender Stimulus Controller zu sein scheint: https://github.com/hotwired/turbo/issues/520#issuecomment-1020209174
