### ISSUE TITLE
Bestandsmeldung mit 0 Personen kann nicht bestätigt werden.

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#26]
Wenn eine Meldung 0 ergibt (zb diese Gruppe: https://db.cevi.ch/groups/721/people?returning=true) dann kann man die Statistik bestätigen, das rote Ausrufezeichen bleibt aber.
Lösen kann man das nur, wenn man manuell ein Jahrgang erfasst und 0 Personen einträgt.

Konnte ich reproduzieren auf http://cevi.puzzle.ch/groups/295/population

Es allerdings ein minimales Issue, weil das höchst selten der Fall sein sollte. Eine Gruppe ohne Bestand macht wenig Sinn.

Macht ein Fix überhaupt Sinn?

Original Issue: https://redmine.puzzle.ch/issues/17322 von Carbon

**Comment by RolandStuder** [comment]
I contacted Carbon to ask whether it0s ok to close this as a issue not worthy to fix.

**Comment by RolandStuder** [comment]
Feedback von Carbon:
- Zu diesen Gruppen: Die haben Mitglieder, aber die haben aber alle Rollen, welche 
bei der Statistik nicht berücksichtigt werden. Ohne Listen-Feature ist das 
eine der guten Möglichkeit um Listen mit ehemaligen/halb-aktiven Personen zu 
führen.

Also tiefe Priorität, aber bei einem Bugfixing Sprint zu fixen.

**Comment by diegosteiner** [comment]
Ist dieses Problem nach wie vor offen? Ich konnte es lokal nicht reproduzieren:

![image](https://cloud.githubusercontent.com/assets/939106/18869720/de06fb0a-84ad-11e6-8be5-33d9ae294f6c.png)

**Comment by RolandStuder** [comment]
Konnte ich auch beim Cevi auf Integraton reproduzieren. Daher schliesse ich das Isseue.
