### ISSUE TITLE
PEOPLE: Household aside auf Person view

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito#2622]
blocks #2616 

Der Household einer Person soll im Aside auf der Person show view angezeigt werden mit action buttons zum Editieren und Auflösen des Household.

# Mockup

![Screenshot from 2024-05-21 13-18-23](https://github.com/hitobito/hitobito/assets/636849/11364629-3667-4a1f-a8b0-d545d9c30c24)

# Tech-Spec

* Im aside eine Household section anzeigen
* in turbo frame tag wrappen   
  ```ruby
  turbo_frame_tag("household_aside") do
  ```
* Platzhalter Buttons
  * nur anzeigen, wenn `can?(:create_households, Person)`
  * Falls Household leer ist, Button "Erstellen" anzeigen, sonst Buttons "Verwalten" und "Auflösen".
* Household Personen auflisten, in separatem `_household_member` partial um das customizen im wagon zu ermöglichen
  * ```ruby
    person.household.household_members.map(&:person)
    ```
  * Person verlinken sofern user Leserechte auf Person hat
  * Alter hinter dem Namen in Klammern

- https://github.com/hitobito/hitobito/blob/master/app/models/household.rb

# ToDo

- [x] View anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by Largo** [comment]
@amaierhofer
Soeben fertig implementiert. Hitobito core könnte gemergt werden. Man koennte noch mehr regression tests hinzufuegen...
Das Alter habe ich auf verlangen wieder entfernt.  Soll ich das in einem SAC branch wieder hinzufuegen?

**Comment by richardjubla** [comment]
Ich kann mir gut vorstellen, dass insbesondere Verwalter*innen und Kind(er) in einem Haushalt verwaltet werden möchten. Hier sind mir folgende Fehlermeldungen aufgefallen: 

![image](https://github.com/hitobito/hitobito/assets/95908537/820b1670-efd0-46a8-b5cd-ebe38d572cba)
Fehler: 
Kind konnte nicht hinzugefügt werden, da es bereits Verwalter*in ist.
Kann nicht sowohl Verwalter*innen als auch Kinder haben.


Leider kann ich nicht mehr dazu sagen oder mir erklären wie oder was dazu führt.
