### ISSUE TITLE
Berechtigungsänderungen (13h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#267]
## Akzeptanzkriterien

* [ ] Kontakte mit Rolle "Vorstandsmitglied" haben die gleiche Bereichtigung wie Rolle "Administrator". Diese sollten die gleichen Berechtigungen haben wie die Rolle "Mitarbeiter"

### Admin Rolle Geschäftsstelle

* [x] Neue Rolle vorhanden auf `Dachverband::Geschäftsstelle` mit Name `Admin` `:layer_and_below_full, :admin, :contact_data`

### Geschäftsstellenmitarbeiter

* [x] Berechtigungsänderung der Rolle `Dachverband::Geschäftsstelle::Mitarbeiter` auf `:group_read, :contact_data`
* [x] Rolle `Dachverband::Geschäftsstelle::Mitarbeiter` soll bezüglich allen Kontakten in layer_and_below die Ability erhalten deren Kontaktdaten zu sehen, also das was ein Benutzer sonst bei `:contact_data` sieht) Schätzung: 6-12h
   * Schwierigkeit: Accessibles muss angepasst werden 

### Adressverwalter für externe Kontakte

* [x] Neue Rolle für `Dachverband::Externe Kontakte` mit Name `Adressverwaltung` Berechtigungen `:group_and_below_full`

### Adressverwalter Rolle auf Jupa Stati

* [x] Neue Rolle `Adressverwalter` auf Gruppe `Jupa Status` 
* [x] Berechtigung :layer_and_below_full, :contact_data

### Ability Anpassen für Notes und Tags

* [x] Ability für Notes und Tags schon bei :group_full / :group_and_below_full vergeben.

### Weiteres

* [x] Readme ist Up to date

**Comment by RolandStuder** [comment]
Überlegen, ob man das für Tags nicht grad auch so machen soll.

**Comment by RolandStuder** [comment]
Schätzung machen, mit allen notwendigen Änderungen

* Neue Rolle in Dachverband::Geschäftsstelle mit Name Admin :layer_full_and_below, :admin, :contact_data
* Berechtigungsänderung von Dachverband::Geschäftsstelle::Mitarbeiter auf :group_read, :contact_data, :layer_and_below_contact_data
* Neue Rolle Dachverband::Externe Kontakte -> Adressverwaltung mit :group_read_and_below_full
* Diese Rolle soll auch Ability haben Tags und Notizen zu erstellen und zu löschen.

**Comment by RolandStuder** [comment]
DSJ hätte gerne drei Stufen Berechtigung abgedeckt:

* Admin die eben überall Rollen auf layer_and_below abdecken können
* Dann Personen, die bezüglich anderen Gruppen nur contact_data sehen können
* Zusätzlich Adressverantwortliche, die dann auch :tags und :people_notes machen können.

:layer_contact_data
:layer_and_below_contact_data
:group_contact_data
:group_and_below_contact_data

**Comment by RolandStuder** [comment]
@jochanan: Ich habe beim nochmaligen Anschauen, gemerkt dass der Aspekt Schreibzugriffe auf Jupa gar nicht abgedeckt ist. Wie müssten da auch noch eine Spezialregel einführen, oder auch "Adressverantwortlich auf den JUPA Stati oder den JUPAs zulassen.".

Ich rufe dich an um das mit dir noch zu klären.

**Comment by psunix** [comment]
person ability fixed
review ok

**Comment by RolandStuder** [comment]
@jharari bitte Abnehmen, du kannst es ausprobieren auf: http://dsj.puzzle.ch 

- Wenn alles OK ist: Bemerkung "OK, abgenommen" hinterlegen.
- Wenn nicht OK, Bemerkung "Nicht OK: " und was inkorrekt ist.

Als Erinnerung den Integrationsumgebungen werden keine echten Mails verschickt, diese werden an https://mailtrap.io verschickt und können dort überprüft werden.

**Comment by jharari** [comment]
Nicht Ok:
-Kontakte mit Rolle "Vorstandsmitglied" haben die gleiche Bereichtigung wie Rolle "Administrator". Diese sollten die gleichen Berechtigungen haben wie die Rolle "Mitarbeiter"

Frage für Erweiterung:
-Ist es möglich, dass man bei weiteren Angaben die Option hat, um zwischen "privat" bzw. "öffentlich" auszuwählen? Oder ist dies mit einem grossen Mehraufwand verbunden? Insbesondere wäre das für die Felder "Adresse", "PLZ", "Ort", "Geburtsdatum" massgebend.
-Ist es möglich, sämtliche Angaben, welche zur Zeit "öffentlich" sind auf "privat" zu wechseln? Wenn wir dieses alle manuell ändern müssen, wäre das mit einem erheblichen Aufwand verbunden.

**Comment by RolandStuder** [comment]
@jharari Ok, zu Vorstandsmitglied.  Diese Rolle ging in den Diskussion wohl unter.

**Comment by RolandStuder** [comment]
@jharari Zu den anderen Issues müssen wir das neu öffnen. Geburtsdatum kriegst du sowieso erst bei vollem Lese-Zugriff.

**Comment by jharari** [comment]
Das Geburtsdatum ist eben eim Excel-Export trotzdem sichtbar, auch wenn ich nicht vollen Lese-Zugriff habe. Ist wohl ein Bug?

**Comment by RolandStuder** [comment]
bitte für 1.15 machen

**Comment by RolandStuder** [comment]
* [ ] Kontakte mit Rolle "Vorstandsmitglied" haben die gleiche Berechtigung wie Rolle "Administrator". Diese sollten die gleichen Berechtigungen haben wie die Rolle "Mitarbeiter"
