### ISSUE TITLE
Gruppe wird nicht angezeigt bei Rollen verschieben

### ISSUE THREAD

**Issue by patrickuhlmann** [hitobito/hitobito#2687]
### Aktuelles Verhalten

Beim Versuch Rollen zu verschieben wird kein Auswahlfeld Gruppe angezeigt:
![image](https://github.com/hitobito/hitobito/assets/511373/d15bd20f-36fd-49c2-b5d5-0c32a2e3679a)

### Gewünschtes Verhalten

Es gibt ein Feld "Gruppe", wo alle Gruppen aufgeführt werden auf die ich Schreibzugriff habe und wodurch ich auswählen kann wohin die Rollen verschoben werden sollen.

### Schritte zu reproduzieren

Beispielsweise mit dem Benutzer luchs@cevimail.ch auf der Testumgebung mit der Gruppe https://cevi.puzzle.ch/groups/452/people

1. Die Person "Hauptleiter" auswählen
2. Rollen/Rollen verschieben auswählen
3. Im angezeigten Fenster kann keine Grupe ausgewählt werden da das Feld gar nicht angezeigt wird.

### Wann ist der Fehler aufgetreten?

Ist immer reproduzierbar

### hitobito version

2.1.5

### Organisation

Cevi

**Comment by nchiapol** [comment]
Hat etwas gedauert, bis ich herausgefunden habe, wo das Problem entsteht. Deshalb hier der entsprechende Screenshot:
![screenshot_2024-06-17_083432](https://github.com/hitobito/hitobito/assets/1123483/19e9c439-e4d6-48b8-be39-dea215ede730)

Ich vermute, das verschieben von Rollen funktioniert nur innerhalb einer Ebene. "Buchs-Rohr Aarau" ist eine Ortsgruppe. Die Ebene Ortsgruppe kann keine weiteren Gruppen enthalten (Jungschar, Verein und Co sind darunterliegende Ebenen. 

Wenn du das gleiche in der "Jungschar Buchs-Rohr Aarau" versuchst, scheint alles zu funktionieren.
![screenshot_2024-06-17_083907](https://github.com/hitobito/hitobito/assets/1123483/eb404d65-90da-4636-b186-8d6a29a95488)

**Comment by patrickuhlmann** [comment]
Aha ok. Ja das ist nicht sehr intiutiv. Könnte man anstatt kein Feld Gruppe anzuzeigen nicht einen Text wie beispielsweise "Es gibt keine weiteren Gruppen auf dieser Ebene" anzeigen. Das wäre deutlich benutzerfreundlicher.

**Comment by ThomasEllenberger** [comment]
So wie ich das verstehe ist dies entsprechend kein Bug, sondern wäre ein featurerequest, möchte man hier was ändern.
Werde das Ticket desshalb schliessen.
