### ISSUE TITLE
PEOPLE: Bug in Household view person links

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito#2689]
In der Household edit view sind die Personen verlinkt.
Beim klick auf eine Person erscheint die Meldung "Content missing" statt das Personenprofil.
In der dev console wird ein turbo error angezeigt.

![Screenshot from 2024-06-17 10-52-03](https://github.com/hitobito/hitobito/assets/636849/e426e2ed-ff96-4003-b14b-bb6de2a1eb4d)

![Screenshot from 2024-06-17 10-52-08](https://github.com/hitobito/hitobito/assets/636849/52183b20-8bf9-4bde-9675-f624cf61db1e)

![Screenshot from 2024-06-17 10-52-28](https://github.com/hitobito/hitobito/assets/636849/92e12166-3d90-4345-9292-ba4ea5bc6cb6)

**Comment by rnestler** [comment]
Wie soll es sich denn verhalten? Nur den Frame mit der Person ersetzen oder komplett auf die Person linken?
