### ISSUE TITLE
TN Liste sortierbar nach Ortsgruppe 4h

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#269]
* Auf TN-Listen von Kursen wird bereits die Ortsgruppe angezeigt (Wagon, ist ein Attribut) .
* Die TN-Liste von Kursen/Anlässen sollte nach Ortsgruppe sortiert werden können
* Ortsgruppe ist ein Personenattribut und nicht zwingen identisch mit der Hauptebene (siehe https://github.com/hitobito/hitobito_cevi/blob/master/app/models/cevi/person.rb#L70)
* Im Export bereits vorhanden
* Im Cevi Wagon umsetzen

## Acceptance Criteria

* [x] Bei allen TN Listen welche Ortsgruppen anzeigen, erscheint "Ortsgruppe" im Tabellenheader als Link
* [x] Beim klicken dieses Links werden die Teilnehmer nach Ortsgruppe sortiert.
* [x] Ist nur im Cevi Wagon umgesetzt

Deckt https://github.com/hitobito/hitobito_cevi/issues/3 ab.

**Comment by RolandStuder** [comment]
@nchiapol Bitte abenehmen.

**Comment by nchiapol** [comment]
OK, abgenommen
