### ISSUE TITLE
FORMS: Events-Anmeldung und Profil-Edit nicht mehr benutzbar

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito#2698]
### Aktuelles Verhalten

Als Datenbank-Benutzer*in möchte ich mich (oder meine Kinder) für einen Event Anmelden können oder mein Profil bearbeiten können. Die Formulare dazu sollen funktionieren und es mir ermöglichen mein Ziel zu erreichen oder mir sinnvolle Hinweise geben, weshalb meine Formular-Daten nicht verarbeitet werden können.

Bitte beachten: Im nächsten Release (2.7.24) sind die Youth-Verbände voll in den Lageranmeldungen drin. Es wäre sehr ungünstig, wenn die Events-Anmeldungen dann nicht korrekt funktionieren sollten.

### Gewünschtes Verhalten

- Verwalter-Profil kann bearbeitet und gespeichert werden
- Event-Anmeldung für Kind (Verwalter*innen) durchführen

**Fehler: "Kind konnte nicht hinzugefügt werden, da es bereits Verwalter*in ist."**
Erscheint im Formular zum Speichern der eigenen Profil-Daten. An einem Ort, an dem diese Informationen gar nicht bearbeitet oder gespeichert werden. https://jubla.puzzle.ch/groups/343/people/1385/edit 

**Fehler: "Adresse muss ausgefüllt werden" / "Kann nicht sowohl Verwalter*innen als auch Kinder haben."**
Erscheint im Formular zur Anmeldung an ein Event (Lager, Anlass, Kurs). Die Adresse kann gar nicht korrekt ausgefüllt werden und scheitert immer. Warum oder weshalb eine Anmeldung nicht nicht sowohl Verwalter*innen als auch Kinder haben kann ist mir nicht klar, oder die Fehlermeldung ist nicht präzise. Die Anmeldung betrifft immer nur ein Profil und sollte unabhängig davon funktionieren, ob sich ein Verwalter*in oder ein Kind (durch den Verwalter*in) für den Event anmeldet.

### Schritte zu reproduzieren

1. Profil mit Verwalter*in-Funktion erstellen oder https://jubla.puzzle.ch/groups/343/people/1385 imitieren
2. Profil-Daten bearbeiten /edit und Speichern (es müssen keine Daten verändert werden)

1. Profil mit Verwalter*in-Funktion nutzen um sich selbst oder verwaltetes Profil für Event anzumelden

### Wann ist der Fehler aufgetreten?

07.06.2024

### hitobito version

2.1.5

### Organisation

Jubla

### Screenshots, weiterer Kontext

![image](https://github.com/hitobito/hitobito/assets/95908537/c3b383ad-e45b-4301-94e0-63f54d5ee3e3)

![image](https://github.com/hitobito/hitobito/assets/95908537/ba6dcf1c-ad41-4244-bc0b-ed25fb4e2f7e)

**Comment by nchiapol** [comment]
Ich habe eben versucht, das beim Cevi zu Reproduzieren:
  - Das Anmelden eines Kindes war kein Problem - aber: bei uns war die Adresse bei meinem Test-Kurs vorher optional. Wenn ich dort nun Strasse und Hausnummer zu Pfilchtfeldern mache, werden diese geprüft (Der Stern fehlt allerdings in der Darstellung) und wenn sie leer sind wird auf Strasse und Hausnummer verwiesen, nicht auf Adressse:
![screenshot_2024-06-23_235318](https://github.com/hitobito/hitobito/assets/1123483/3c43db90-55d0-4c75-889f-2d17deabc93e)
Meine Vermutung deshalb: Ihr hattet die alte unstrukturierte Adresse als Pflichtfeld. Die wird jetzt nicht mehr angezeigt aber immer noch geprüft. @thomasellenberger: Wie von Richi erwähnt, muss das beim Release funktionieren, bitte unbedingt noch einmal testen.
  - Das Problem beim Bearbeiten der Profil-Daten kann ich nicht reproduzieren.

**Comment by ThomasEllenberger** [comment]
- Der Bug, dass die Fehlermeldung erscheint dass die Adresse ausgefüllt sein muss wenn diese ausgefüllt ist, kann ich stand heute nicht mehr nachvollziehen. Ich gehe davon aus, dass dies bereits gefixt wurde.

- Das Problem mit "Kann nicht Verwalter und Kind sein" konnte ich bei dieser Speziellen Person nachvollziehen. Jedoch bei keinem anderen Profil,welches ich bereits in früheren Tests genutzt habe, oder dass ich neu angelegt hätte.
- Die Meldung von Carbon kann ich nachvollziehen (Kein * wenn obligatorisch unnd Fehlermeldung mit Strasse) Ist ein rein kosmetisches Problem, deshalb niedrigere Prio.

**Comment by nchiapol** [comment]
@ThomasEllenberger 
> Der Bug, dass die Fehlermeldung erscheint dass die Adresse ausgefüllt sein muss wenn diese ausgefüllt ist, kann ich stand heute nicht mehr nachvollziehen. Ich gehe davon aus, dass dies bereits gefixt wurde.

Hast du das bei Jubla mit dem Kurs und den Personen aus Richis Test versucht?

Bitte unbedingt meine Vermutung wie folgt testen:
1. Ein "altes" Test-System einrichten (gemäss aktueller Produktion von Jubla/Cevi)
2. Dort einen Kurs anlegen bei dem die Adresse ein Pflichtfeld ist
3. (optional) Anmeldung testen
4. das Test-System auf das neue Release Upgraden
5. Kontrolle ob nun in den Kurseinstellungen Adresse nicht mehr erscheint und dafür Strasse und Hausnummer Pflichtfelder sind.
6. Anmeldung testen

Das Problem darf nur als gefixt betrachtet werden, wenn dieser Test funktioniert. Wenn meine Vermutung stimmt, lässt sich das möglicherweise auf der Integration nicht zuverlässig testen.

**Comment by richardjubla** [comment]
> * Der Bug, dass die Fehlermeldung erscheint dass die Adresse ausgefüllt sein muss wenn diese ausgefüllt ist, kann ich stand heute nicht mehr nachvollziehen. Ich gehe davon aus, dass dies bereits gefixt wurde.

![image](https://github.com/hitobito/hitobito/assets/95908537/67b57f3b-9f93-4005-8db0-1cba68fe1470)
Erfreulicherweise kann ich das auch nicht mehr reproduzieren. Ich gehe aktuell davon aus, dass "normalerweise" die Adresse zwingend und die Nummer optional abgefragt werden soll. 


> * Das Problem mit "Kann nicht Verwalter und Kind sein" konnte ich bei dieser Speziellen Person nachvollziehen. Jedoch bei keinem anderen Profil, welches ich bereits in früheren Tests genutzt habe, oder dass ich neu angelegt hätte.

Nicht zum ersten Mal und ein gefährlicher Zustand: Ich vermute dass wir inkonsistente (defekte) Profile haben welche nicht mehr den "Regeln" entsprechen. Es müsste ausgeschlossen werden, dass dies Auswirkungen auf die produktiven Daten hat.

**Comment by TheWalkingLeek** [comment]
https://github.com/hitobito/hitobito_youth/commit/b7a483ef6f8ab6ce253fb6d160dc89257748fef5

**Comment by richardjubla** [comment]
Nach dem Update sind uns in der produktiven Datenbank [Version 2.1.4](https://db.jubla.ch/changelog) die Felder zusätzliche Adresszeile, Strasse und Hausnummer verschwunden.... 
![image](https://github.com/hitobito/hitobito/assets/95908537/5c199f3f-c6d8-48cc-999c-6ebf15590433)

**Comment by kronn** [comment]
Das ist so korrekt. Während der Konvertierung der Adressen waren die Eingabefelder für den alten und neuen Stil deaktiviert und versteckt. Damit war sichergestellt, dass die Adressen nicht während der Umwandlung verändert werden und so vielleicht Änderungen verloren gegangen wären. Die vorhandenen Daten waren weiterhin lesbar.

**Comment by richardjubla** [comment]
In der produktiven Datenbank (Version 2.2.0) wie auch in der Stage-Umgebung sind die Fehler nicht mehr vorhanden oder nicht reproduzierbar. Es gibt noch Folgefragen wie die Pflichtfelder oder die optionale Hausnummer welche separat verfolgt werden.
