### ISSUE TITLE
Berechtigungs und Rollenanpassungen im Cevi Wagon (6h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#270]
Cevi Wagon

## Akzeptanzkriterien:

* [x] Sektion, neue Rolle mit Name Administrator/-in (:layer_full_and_below, :contact_data)
* [x] Group::Jungschar Rolle Coach neu :layer_and_below_full statt :layer_and_below_read
* [x] Entfernen von :admin Berechtigung bei Geschäftsstellen:
    * Dachverband Geschäftsstellen :admin Berechtigungen entfernen
    * Mitgliederoganisationen Geschäftsstellen :Admin Berechtigungen entfernen
* [x] Anpassung von mehreren Rollen auf Dachverband

**Auf Layer Dachverband** (nicht auf Mitgliederorganisationen)
  * Vorstand [layer_and_below_read -> layer_read]
    * Präsidium
    * Finanzverantwortliche/-r
    * Mitglied
  * Geschäftsstelle [layer_and_below_full -> layer_full]
    * Geschäftsleiter/-in
    * Angestellte/-r
    * Finanzverantwortliche/-r
  * Gremium [layer_and_below_read -> layer_read]
    * Leitung 
    * Mitglied
    * Aktive/-r Kursleiter/-in

Deckt folgende Cevi- Issues ab:

* https://github.com/hitobito/hitobito_cevi/issues/13
* https://github.com/hitobito/hitobito_cevi/issues/6
* https://github.com/hitobito/hitobito_cevi/issues/2
* https://github.com/hitobito/hitobito_cevi/issues/19

**Comment by RolandStuder** [comment]
@nchiapol Kannst du auf http://cevi.puzzle.ch abnehmen gemäss, bitte OK oder NICHT OK angeben (siehe https://github.com/hitobito/hitobito/wiki/Abnahme)

**Comment by nchiapol** [comment]
OK, abgenommen
