### ISSUE TITLE
Export/Strukutrierte Adressen: keine Adressen im Export Spaltenauswahl 

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito#2704]
### Aktuelles Verhalten

Der Export "Spaltenauswahl" auf einer Gruppe enthält eine leere Spalte "Adresse".

### Gewünschtes Verhalten

Auch im Export "Spaltenauswahl" enthält die Spalte "Adresse" die korrekten Daten

### Schritte zu reproduzieren

1. Testgruppe öffnen (z.B. https://cevi.puzzle.ch/groups/85/)
2. Export/Excel/Spaltenauswahl herunterladen

### Wann ist der Fehler aufgetreten?

Tests für Release 2024-07

### hitobito version

2.1.5

### Organisation

Cevi

### Screenshots, weiterer Kontext

Getestet:
  - Gruppe/XLS/Spaltenauswahl: leer
  - Gruppe/CSV/Spaltenauswahl: leer
  - Gruppe/XLS/Addressliste: ok
  - Person/XLS/Spaltenauswahl: ok

Wohl eine Folge von https://github.com/hitobito/hitobito/issues/2226

**Comment by ThomasEllenberger** [comment]
Bug wurde behoben.
Müsste nun in allen Exporten korrekt funktionieren.

**Comment by nchiapol** [comment]
@ThomasEllenberger Habe das eben getestet, funktioniert aber noch immer nicht. 

Exporte der Gruppe https://cevi.puzzle.ch/groups/5/people
  * CSV-Export "Spaltenauswahl"  enthält eine leere Address-Spalte.
  * XLSX-Export "Spaltenauswahl"  enthält eine leere Address-Spalte.
  * CSV-Export "Haushalte" enthält eine Spalte Address mit Strasse + Nummer in einem Feld
  * CSV-Export "Adressliste" enthält eine Spalte Address mit Strasse + Nummer in einem Feld

**Comment by nchiapol** [comment]
Bugs sind nicht behoben, aber die Unterscheidung zwischen diesem Issue und https://github.com/hitobito/hitobito/issues/2705 ging unterdessen verloren. Habe deshalb dort kommentiert.
