### ISSUE TITLE
Bei Anlässen optional eine Unterschrift verlangen können (2h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#271]
## Zu korrigieren

* [ ] Anmerkung gemäss Kommentar korrigieren: https://github.com/hitobito/hitobito/issues/271#issuecomment-306312725

Die Funktionalität aus den Kursen von 
  * Unterschrift erforderlich
  * Zweitunterschrift erforderlich
  * Zweitunterschrift von

Sollte auch für Anlässe verfügbar sein.

Ist aktuell nur auf Kursen verfügbar: https://github.com/hitobito/hitobito/blob/92db15a8e375d93f9634c3138335169e8dd6b76a/app/models/event/course.rb

deckt ab https://github.com/hitobito/hitobito_cevi/issues/12

**Comment by codez** [comment]
Bei den Lagern von PBS und Jubla werden diese Felder nun ebenfalls verfügbar sein.

**Comment by RolandStuder** [comment]
@nchiapol Bitte abnehmen.

**Comment by nchiapol** [comment]
Nicht OK, die TN werden nicht auf die benötigte Unterschrift hingewiesen. (Bei den Kursen erscheint nach der Anmeldung ein zusätzlicher Text im grünen Balken, der sollte auch bei Anlässen angezeigt werden.)

**Comment by RolandStuder** [comment]
@nchiapol Bitte Korrektur abnehmen.

Wenn alles OK ist: Bemerkung "OK, abgenommen" hinterlegen.
Wenn nicht OK, Bemerkung "Nicht OK: " und was inkorrekt ist.

**Comment by RolandStuder** [comment]
Text habe ich angepasst
