### ISSUE TITLE
Neue Rolle "Helfer" bei Anlässen/Kursen (2h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#273]
Wir möchten bei allen Eventtypen eine neue Rolle "Helfer" mit den gleichen Rechten wie die Küche.

Deck folgendes ab https://github.com/hitobito/hitobito_cevi/issues/11

Resolved in https://github.com/hitobito/hitobito/pull/274 bitte reviewen

**Comment by RolandStuder** [comment]
@nchiapol Kannst du auf http://cevi.puzzle.ch abnehmen gemäss, bitte OK oder NICHT OK angeben (siehe https://github.com/hitobito/hitobito/wiki/Abnahme)

**Comment by nchiapol** [comment]
OK, abgenommen
