### ISSUE TITLE
Neue Rolle in MIO Gremium mit Lesezugriff auf TN Liste aller Kurse (4h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#275]
## Zu korrigieren 

* [ ] Ability auf Application Market für Mitgliederorganisation::Gremium::Ausbildungsmitglied entfernen, siehe https://github.com/hitobito/hitobito/issues/275#issuecomment-306304732

Wir brauchen in den MIO Gremien eine neue Rolle, die Lese-Zugang auf die TN-Liste alle Kurse hat.

Neue Rolle: 

* Mitgliederorganisation::Gremium::Ausbildungsmitglied

Berechtigung
- layer__and_below_read

Zusätzliche Abilities

- ability participations_show auf layer_and_below
- ability application_market auf layer_and_below, beinhaltet Schreibrechte

deckt ab: https://github.com/hitobito/hitobito_cevi/issues/1

**Comment by RolandStuder** [comment]
@nchiapol Bitte abnehmen, habe eine Person bereitgestellt mit der richtigen Rolle:
http://cevi.puzzle.ch/groups/166/people/2174.html (standardpasswort)

**Comment by nchiapol** [comment]
Nicht OK: Die neue Rolle sollte in den Kursen nichts verändern können. Im Tab Anmeldungen kann sie aber Anmeldungen manipulieren. (Das ist oben auch entsprechend notiert, im ursprünglichen Issue aber explizit nicht erwünscht.)
Wäre schön, wenn das noch korrigiert werden kann. Wie aber im ursprünglichen Issue erwähnt, ist der Anmeldungstab nicht so zentral und kann entsprechend auch wieder deaktiviert werden, sollte der Mehrauwand zu gross sein.

**Comment by RolandStuder** [comment]
Berechtigung beim Anmeldungsmarkt ist aktuell alles oder nichts. Wäre etwas aufwändiger das anzupassen, also entfernen wir die Berechtigung auf die Anmeldungen.

**Comment by nchiapol** [comment]
Damit können wir leben. Danke für die Info.

**Comment by RolandStuder** [comment]
Bitte für 1.15 noch korrigieren

**Comment by RolandStuder** [comment]
[ ] Ability auf Application Market für Mitgliederorganisation::Gremium::Ausbildungsmitglied entfernen, siehe https://github.com/hitobito/hitobito/issues/275#issuecomment-306304732

**Comment by psunix** [comment]
ability wurde bereits durch @codez angepasst.
