### ISSUE TITLE
Weniger Rechte für AssistantLeader (2h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#276]
Rolle `AssistantLeader` (Kurs-Leiter) sollten die gleichen Rechte an der TN-Liste haben wie die Küche, nicht wie der Hauptleiter. (Wir sehen das als Bug)

Konkret geht es um die Rolle AssistantLeader (https://github.com/hitobito/hitobito/blob/92db15a8e375d93f9634c3138335169e8dd6b76a/app/models/event/role/assistant_leader.rb) und nicht um die Hauptleitung. Im Core hat diese volle Berechtigung. Müsste im Wagon überschrieben werden.

* Neu nur Leseberechtigung auf TN-Liste
* Kann Kurs nicht bearbeiten.

Gilt für alle Eventtypen

Machen wir im Wagon.

**Comment by codez** [comment]
Bezieht sich das nur auf die TN-Liste (:participations_full) oder auch auf die Verwaltung des Anlasses/Kurses (:event_full, momentan für Hilfsleiter möglich)?

**Comment by RolandStuder** [comment]
@nchiapol Bitte abnehmen

**Comment by nchiapol** [comment]
Ok, abgenommen
