### ISSUE TITLE
Configuration von Int / Prod vervollständigen und Smoke Tests machen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#279]
* [x] Gemäss Konvetionen anpassen: Test -> Int
* [x] Jenkins Job für Int Umgebung -> Continous
* [x] mailtrap.io konto erstellen und mailconfig testen
* [x] catch-all konto erstellen und konfigurieren
* [x] test tenant einrichten
* [x] admin passwort setzen und in cryptopus ablegen

**Comment by psunix** [comment]
warte noch bis /sys das catch-all konto eingerichtet hat

**Comment by psunix** [comment]
/sys hat catch-all eingerichtet. @kronn hat ose config gemacht
