### ISSUE TITLE
Fix Sphinx deprecation warning

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#28]
Du noch kurz eine Frage, sphinx/searchd meldet noch folgendes:

using config file '/var/www/vhosts/cevi/www/config/production.sphinx.conf'...
WARNING: compat_sphinxql_magics=1 is deprecated; please update your application and config
für cevi/jubla/pbs könnt ihr dies anpassen?

original issue gemeldet von Lukas Grimm https://redmine.puzzle.ch/issues/6897

**Comment by ombre8** [comment]
but why :(

**Comment by RolandStuder** [comment]
Weil das mit Migration auf Appuio eh entfallen sollte.
