### ISSUE TITLE
Backup von DBs einzeln sicherstellen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#281]
## IST 

Backup sichert alle Datenbanken zusammen, was einen Restore einer einzelnen DB sehr aufwändig machen würde.

## Soll

DB einzeln backupen.

**Comment by psunix** [comment]
https://github.com/appuio/mysql-multidb-backup-container

image erstellt und int/prod multitenancy damit ausgerüstet.

ausserdem ose project template angepasst.

**Comment by kronn** [comment]
das Restore haben wir jetzt nicht so ganz freiwillig getestet. Es funktioniert.
