### ISSUE TITLE
ELTERNZUGANG: Anmeldebestätigung Lager wird nicht an Verwalter*in versendet

### ISSUE THREAD

**Issue by patriziajubla** [hitobito/hitobito#2816]
### Aktuelles Verhalten

Es werden keine Anmeldebestätigungen per Mail an Elternzugang versendet

### Gewünschtes Verhalten

Anmeldebestätigung der Lageranmeldung wird versendet

### Schritte zu reproduzieren

1. Verwalter*in Logt sich ein
2. Verwalter*in meldet Kind an
3. Verwalter*in erhält Bestätigungsmail

### hitobito version

2.2.3

**Comment by richardjubla** [comment]
@patriziajubla vielleicht ist das eine Ergänzung, Erweiterung oder ein Duplikat von https://github.com/hitobito/hitobito/issues/2574

**Comment by patriziajubla** [comment]
Das sind zwei verschiedene Bugs, bei 2574 wird die Kontaktperson nicht benachrichtigt, was bei uns auch passiert. Bei diesem Bug 2816 erhält der*die Verwalter*in keine Anmeldebestätigung

**Comment by richardjubla** [comment]
> @richardjubla Das sind zwei verschiedene Bugs, bei #2574 wird die Kontaktperson nicht benachrichtigt, was bei uns auch passiert. Bei diesem Bug #2816 erhält der_die Verwalter_in keine Anmeldebestätigung

Korrekt, habe falsch nachgeschaut: Eine Anmeldebestätigung an den Verwalter*in sollte aber versendet werden: https://github.com/hitobito/hitobito/issues/2392 und https://github.com/hitobito/hitobito_youth/pull/47

**Comment by patriziajubla** [comment]
@richardjubla habe getestet funktioniert nicht (mehr) und haben dies auch als Rückmeldungen erhalten. Ich erachte dies als sehr dringend zu beheben.

**Comment by patriziajubla** [comment]
@richardjubla habe getestet. Funktioniert, wenn Kind kein Hauptemail hinterlegt hat, erhält Verwalter*in das Mail. Wenn das Kind eine Hauptemail hinterlegt hat, wird das Mail nur an das Kind versendet.

**Comment by richardjubla** [comment]
@ThomasEllenberger 

Gemäss unseren Test funktioniert der Hotfix nur teilweise und nicht gemäss deiner [Definition](https://github.com/hitobito/hitobito/issues/2392#issue-2109986729). Kannst du dieses Ticket wieder öffnen, #2392 oder machen wir ein komplett neues Ticket?

**Comment by ThomasEllenberger** [comment]
@richardjubla @patriziajubla 
Ich habe dies soeben auch auf eurer Integration getestet, und bei mir hat es das Mail jeweils an beide versendet (Kind und Verwalterin)
Wie war euer Testsettup? Wo und mit wem habt ihr dies getestet?

@njaeggi Dies hat bei mir funktioniert unabhängig davon ob ich die Verwalterin oder das Kind imitiert habe.

**Comment by patriziajubla** [comment]
@ThomasEllenberger Hallo Thomas

Vielen Dank fürs testen und wiedereröffnen

Habe nochmals kontrolliert, hat bei uns auch funktioniert:

![image](https://github.com/user-attachments/assets/7aa37142-795d-430f-be8c-583df85609ec)

Ticket kann wieder geschlossen werden.

**Comment by nchiapol** [comment]
Ich habe eben auch in der Cevi-Umgebung getestet: 

**TLDR: funktioniert alles korrekt**

Getestete Konfigurationen:
  * TN hat Haupt-Email und Verwalter meldet TN an: Mail an TN + beide Verwalter (+beide Coaches für Freigabe)
  * TN hat Haupt-Email und meldet sich selbst an: Mail an TN + beide Verwalter (+beide Coaches für Freigabe)
  * TN hat kiene Haupt-E-Mail und Verwalter meldet TN an: Mail an beide Verwalter (+beide Coaches für Freigabe)
  * [nur möglich via Imitieren] TN hat keine Haupt-E-Mail und meldet sich selbst an: Fehlermeldung dass Haupt-E-Mail zwingend erfasst sein muss

**Comment by njaeggi** [comment]
Könntet ihr ab morgen bitte nochmals gründlich die Integration testen? Aus unserer Sicht sollte nun alles so funktionieren wie gewünscht 🚀

**Comment by nchiapol** [comment]
Habe eben, die drei realistischen Szenarien getestet und keine Probleme festgestellt:
  * TN hat Haupt-Email und Verwalter meldet TN an: Mail an TN + beide Verwalter (+beide Coaches für Freigabe)
  * TN hat Haupt-Email und meldet sich selbst an: Mail an TN + beide Verwalter (+beide Coaches für Freigabe)
  * TN hat keine Haupt-E-Mail und Verwalter meldet TN an: Mail an beide Verwalter (+beide Coaches für Freigabe)
