### ISSUE TITLE
PEOPLE: Duplicate Finder Memory Usage

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito#2824]
### Aktuelles Verhalten

Der People::DuplicateLocatorJob braucht momentan übermässig viel Memory, was zu Restarts der Delayed Job Container führt.

### Gewünschtes Verhalten

Der Job soll einen konstanten Memoryverbrauch haben.

### Schritte zu reproduzieren

People::DuplicateLocatorJob auf SAC Integration starten

### Wann ist der Fehler aufgetreten?

6.9.2024

### Organisation

SAC

### ToDos

Das Problem liegt wohl im Import::PersonDuplicateFinder, welcher alle Personen in @duplicate_entries behält. Je mehr Personen verarbeitet wurde, desto grösser wird diese Liste. Die Liste selbst wird allerdings nur für wegen ihrer Size gebraucht (zumindest im Core) und ist zudem semantisch falsch benannt, da sind nicht duplizierte Personen enthält, sondern nur die einmalig vorkommenden Personen.

**Comment by Largo** [comment]
Insieme will need to be changed as well.
