### ISSUE TITLE
Anmeldetermin in Kursen anzeigen. (2h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#285]
Für View list_courses Anmeldedatum in der Tabelle anzeigen.

## Akzeptanzkriterien

- [x] Wenn Anmeldebutton vorhanden, darunter Anmeldedatum anzeigen (bis XX.XX.XXXX).

## Offene Fragen

- [x] Können wir das einfach auch bei list_events auch ergänzen?
- [x] Wäre es sinnvoll allgemein das zu konsolidieren, auch bei Anzeige unter den Gruppen `/groups/325/events`?

**Comment by psunix** [comment]
bis wurde auch angezeigt wenn kein Anmeldeschluss gesetzt: fixed.
review ok
