### ISSUE TITLE
Qualifikationen vergeben mit Submit (8h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#286]
## IST

Qualifikationen bei einem Kurs werden direkt vergeben, sobald man Checkmark oder X klickt. Manchmal vergeben so Kursleiter zu früh die Qualifikationen

## Soll

Qualifikationen werden nur nach einem explizitem Submit aktualisiert.

![image](https://cloud.githubusercontent.com/assets/194364/26588867/ccc82034-4556-11e7-8aa5-80b3f5529b4e.png)

**Comment by RolandStuder** [comment]
@philippekeller Passt das so?

**Comment by psunix** [comment]
review ok
getestet mit pbs wagon
