### ISSUE TITLE
multitenant prod stable

### ISSUE THREAD

**Issue by psunix** [hitobito/hitobito#287]
team hitobito ist nun die erste instanz die produktiv auf ose3 läuft. diese Umgebung wird bisher aber vom master branch deployed. 
um zu verhindern das unstable/unfertige features auf dieser umgebung deployed werden ist es wichtig das wir dort auf stable wechseln. 
momentan ist die Version 1.15 deployed, welche zurzeit in Entwicklung ist. 

Vorschlag: neuen release erstellen (1.15, 1.14.1) und dann dann deployment umstellen auf stable branch.

release 1.14 ist nicht kompatibel mit multitenant

**Comment by psunix** [comment]
@RolandStuder bitte prüfen und ggf. in planung

**Comment by RolandStuder** [comment]
Bleibt bis auf weiteres auf Master. So lange wir das nicht nach aussen bieten. Wir machen den Stable dann mit 1.15
