### ISSUE TITLE
Anlass erstellen: Komisches Verhalten mit Pflichtfeld AHV-Nummer

### ISSUE THREAD

**Issue by patrickuhlmann** [hitobito/hitobito#2876]
### Aktuelles Verhalten

Beim Erfassen eines neuen Anlasses gibt es im Tab "Anmeldeangaben" das Feld "AHV-Nummer" mit Checkboxen "Angabe". Es ist markiert als wenn es ein Pflichtfeld wäre aber man kann den Anlass speichern ohne etwas auszufüllen, der Wert ist unklar.

### Gewünschtes Verhalten

Wenn es als Pflichtfeld markiert ist sollte es auch so durchgesetzt werden respektive müsste eine Option wie z. B. "Optional" standardmässig ausgewählt sein.

### Schritte zu reproduzieren

1. Neuen Anlass erstellen
2. Pflichtfeld Name und Von ausfüllen. Speichern

### Wann ist der Fehler aufgetreten?

23.09.2024

### hitobito version

2.2.3

### Organisation

Cevi

### Screenshots, weiterer Kontext

![image](https://github.com/user-attachments/assets/ca58ce35-540c-4482-b351-138ab6b2f7e1)

**Comment by nchiapol** [comment]
@patrickuhlmann Well spotted

Dass keine Vorauswahl getroffen wurde ist korrekt (vgl MVP in https://github.com/hitobito/hitobito_youth/issues/58). 

Der Bug ist, dass entgegen dem MVP keine Auswahl erwungen wird

@diegosteiner nehme an, das ist ebenfalls bei dir.
