### ISSUE TITLE
API: Gruppen-Mitglieder abrufen

### ISSUE THREAD

**Issue by Tschet1** [hitobito/hitobito#2900]
Als Entwickler einer Application basierend auf der JSON API
möchte ich die Möglichkeit haben, Personen die einer Gruppe angehören abzurufen.
um in der Anwendung Personen mit der Gruppen-Zugehörigkeit zu filtern.

Ich sehe zwei Möglichkeiten, dies umzusetzen:
Entweder könnten die Mitglieder einer Gruppe verlinkt werden oder Personen können via Gruppen-Zugehörigkeit gefiltert werden.
Soweit ich das sehe, gibt es momentan nur einen Filter basiert auf der primary_group_id.

**Comment by carlobeltrame** [comment]
Auf der Integrationsumgebung ist genau dafür der Endpoint `GET /roles` mit dem Filter `&filter[group_id][eq]=9999` verfügbar. Reicht dies nicht aus?

**Comment by Tschet1** [comment]
ah sorry, habe nicht gesehen dass das im core bereits vorhanden ist.
