### ISSUE TITLE
API: filter Gruppen basierend auf layer_group

### ISSUE THREAD

**Issue by Tschet1** [hitobito/hitobito#2901]
Als Entwickler einer Application basierend auf der JSON API
möchte ich die Möglichkeit haben alle Gruppen einer Ebene abzurufen, 
ohne alle Gruppen in der Datenbank abfragen zu müssen.

Momentan gibt es keine Möglichkeit, Gruppen mit der layer_group zu filtern. Wenn ich alle Gruppen einer Ebene abfragen möchte, muss ich momentan alle Gruppen in der Datenbank abfragen und in einem zweiten Schritt die layer_group zu checken.
Ein zusätzlicher Filter basierend auf der layer_group wäre aus meiner Sicht sinnvoll.

**Comment by carlobeltrame** [comment]
Auf der Integrationsumgebung ist genau dafür der Filter `&filter[layer_group_id][eq]=1234` verfügbar. Reicht dieser nicht aus?

**Comment by Tschet1** [comment]
ah sorry, habe nicht gesehen dass das im core bereits vorhanden ist.
