### ISSUE TITLE
Filter: Personenfilter mit Tags um UND Verknüpfung erweitern (16h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#291]
## Grosses Risiko

Ist relativ komplex zu implementieren stellt eines hohes Risiko dar. Deswegen ist die Schätzung so hoch. Bei den Abos haben wir das im ersten Schritt nicht hingekriegt.

Erweiterung von #283 

* [ ] Zusätzliche Option Filter bereitstellen
* [ ] Wenn Option gewählt Suche gibt nur Personen zurück, welche Alle der aufgelisteten Tags enthalten.
* [ ] Default-Wahl: Oder Verknüpfung (hat eines der folgenden Tags)
 
![image](https://cloud.githubusercontent.com/assets/194364/26725099/1ebe3d68-479d-11e7-8ddf-c9736a260e1e.png)

**Comment by olibrian** [comment]
Wurde umgesetzt.
