### ISSUE TITLE
Filter: Personenliste Enums Filter (6h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#293]
## Akzeptanzkriterien

* [ ] Auf Personenliste kann nach nach Filter nach Attributen, welche eine einfach Auswahl zulassen, z. B. Kanton oder Geschlecht
* [ ] Matchingstrategie ist: Wenn Person Wert X hat
* [ ] Berechtigung wie bei #292 

---

![image](https://cloud.githubusercontent.com/assets/194364/26762126/b8923d86-493c-11e7-934e-c8dd43933a4a.png)

**Comment by olibrian** [comment]
Wurde umgesetzt
