### ISSUE TITLE
Filter: Enums mit Mehrfachauswahl (3h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#294]
## Akzeptanzkriterien

* [ ] Vorraussetzung #293 erledigt
* [ ] Mehrfachauswahl ermöglichen, mit Chosen.js

## ToDo

* [ ] Mockup anpassen

---
![image](https://cloud.githubusercontent.com/assets/194364/26762096/3d300de4-493c-11e7-8eaf-34e7432264af.png)

**Comment by ThomasEllenberger** [comment]
Umsetzung im Moment nicht geplant.
Issue closed, da bereits 6 jährig.
