### ISSUE TITLE
Filter: Filter für Boolean (2h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#296]
* [ ] Personenliste können nach Booleans gefiltert werden, z. B. Checkbox Firma oder "hat Geschwister in Ortsgruppe"
* [ ] Matchingstrategien
  * [ ] set to false
  * [ ] set to true
* [ ] gleich Berechtigungen wie bei anderen

---

![image](https://cloud.githubusercontent.com/assets/194364/26762292/f6f3dad2-493f-11e7-9666-486e8eb6f48c.png)

**Comment by ThomasEllenberger** [comment]
Umsetzung im Moment nicht geplant.
Issue closed, da bereits 6 jährig.
