### ISSUE TITLE
Filter: Filterblocks einzeln hinzufügen (8h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#297]
## Akzeptanzkriterien

* [ ] Filter-Kriterien erscheinen erst, wenn man sie aus einem Dropdown auswählt.
* [ ] Filter-Kriterien können wieder entfernt werden 
* [ ] Grosse Filter Kriterien können immer noch expanded/collapsed werden
* [ ] Attributfilter erscheinen als separate Blöcke, nicht ein Block mit allen Attributen
* [ ] Reihenfolge der Filter persistieren

![image](https://cloud.githubusercontent.com/assets/194364/26762874/d07c925e-4949-11e7-9102-779a755812aa.png)

**Comment by ThomasEllenberger** [comment]
Umsetzung im Moment nicht geplant.
Issue closed, da bereits 6 jährig.
