### ISSUE TITLE
Filter: Gruppen aus Tree auswählen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#298]
## Ist

Heute können auf der Personenliste nur Rollen ausgewählt werden.

## Soll

Auf der Personenliste sollen Suchen auch nach Gruppen eingeschränkt werden können.

## Akzeptanzkriterien

* [ ] Treenansicht lässt sich beliebig ausklappen
* [ ] Gruppen kann man einzeln auswählen.
* [ ] Wähle ich eine Gruppe aus, so sind alle Untergruppen ausgewählt.
* [ ] Sublayer werden nicht automatisch ausgewählt.
* [ ] Bei Sublayer hat man die Möglichkeit alle auszuwählen mit einer künstlichen Node
* [ ] Der Tree soll von Anfang an so offen sein, dass man die erste Ebene inklusive Layer sieht.
* [ ] Der Tree ist durchsuchbar (Beispiel: siehe JSTree Demo https://www.jstree.com/demo/)

## Bemerkungen

* Die Lösung erlaubt nicht eine Gruppe OHNE Subgruppen auszuwählen, ich kann z. B. nicht Personen direkt auf dem Dachverband finden, ohne dessen Subgruppen auch auszuwählen (die Lösungen das abzudecken sind für den Benutzer recht komplex, siehe https://ux.stackexchange.com/questions/9598/hierarchical-multi-state-tree-check-box-selection Workaround für dies wird die Rollenauswahl sein.

![image](https://cloud.githubusercontent.com/assets/194364/26762903/67d23b90-494a-11e7-9320-f4b6faa3dd7a.png)

**Comment by ThomasEllenberger** [comment]
Umsetzung im Moment nicht geplant.
Issue closed, da bereits 6 jährig.
