### ISSUE TITLE
Filter: Rollen in Baumansicht auswählen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#299]
## Ist

Bisher werden die Rollen in einer relativ grossen Ansicht dargestellt, die sehr viel Platz einnimmt und die Struktur nur bedingt gut zeigt.

## Soll

Neu soll man die Rollen in einer Baumansicht auswählen können.

## Akzeptanzkriterien

* [ ] Auswahl der Rollen in einer Baumansicht in Personenfilter
* [ ] Auch in Abo Rollenfilter
* Abhängigkeit zur Gruppenauswahl wird in seperatem Issue betrachtet.

## Bemerkungen

* Es besteht ein gewisses Risiko, das für die Filtermöglichkeiten Rollen / Gruppen zu ähnlich wirken. Im Abo ist das ja auch anders abgebildet, allerdings ist auch diese Möglichkeit nicht so super zugänglich.

![image](https://cloud.githubusercontent.com/assets/194364/26763239/b4d063e0-494f-11e7-8581-74145132ba45.png)

**Comment by ThomasEllenberger** [comment]
Umsetzung im Moment nicht geplant.
Issue closed, da bereits 6 jährig.
