### ISSUE TITLE
Core: Anfragen-Tab gibt bei aktivierten Anfragen einen 500er

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito#2993]
### Aktuelles Verhalten

Sind Anfragen auf einem Layer aktiviert und klicke ich auf das Anfragen-Tab
![screenshot_2024-11-09_222701](https://github.com/user-attachments/assets/e723a4c5-32d5-4210-8ad6-3e8103dc596e)
bekommt ich einen 500er

Entsprechend kann ich bestehende Anfragen nicht beantworten. 
(Der Fehler tritt sofort auf, wenn ich Anfragen aktiviere, es ist keine offene Anfrage nötig. Ich bin überrascht, dass das bei der PBS nicht schon aufgefallen ist.)

Auch kann ich Anfragen natürlich nicht wieder deaktivieren, da der Knopf dafür auf der Seite mit dem Fehler wäre...

### Gewünschtes Verhalten

Das Anfragen Tab funktoniert ohne Fehler

### Schritte zu reproduzieren

1. Rolle mit hinreichenden Rechten in einer Gruppe wählen
2. Versuchen das Anfragen Tab zu öffnen

### hitobito version

2.3.5

### Organisation

Cevi

### Screenshots, weiterer Kontext

Das Problem tritt auf dem Produktivsystem, der Integration und der lokalen Entwicklungsumgebung auf.

lokale Fehlermeldung ist
```
ActiveModel::MissingAttributeError at /groups/1/person_add_requests
missing attribute: company
```
![screenshot_2024-11-09_223648](https://github.com/user-attachments/assets/40a0e554-ed4a-4bbd-b8ec-785e752da3ba)

Der gleiche Code wird z.B. auch verwenden, wenn die Kontaktperson für eine Gruppe ausgewählt wird. Dort funktioniert alles. In `person_add_requests` scheint aber kein echtes Person-Objekt übergeben zu werden. Es hat keines der typischen Personen-Attribute. (vgl. Debugger im Screenshot)

**Comment by nchiapol** [comment]
@ThomasEllenberger: Ich bin Zufällig über dieses Problem gestolpert - das kann aber rasch wirklich problematisch werden. Es scheint mir deshalb wichtig, dass hier bald ein Bugfix verfügbar ist.

**Comment by richardjubla** [comment]
Ich kann das Verhalten in [Version 2.3.6](https://jubla.puzzle.ch/changelog) reproduzieren und halte das ebenfalls für problematisch, da dieses Feature bei uns für alle Gruppen/Ebenen aktiviert werden soll:  https://github.com/hitobito/hitobito_jubla/issues/106

**Comment by ThomasEllenberger** [comment]
Das Problem ist uns bekannt und wird in https://github.com/hitobito/hitobito_pbs/issues/354 auch bereits behandelt. 
Wir priorisieren dieses Issue entsprechend und werden einen Hotfix dafür bereitstellen sobald dies behoben ist.

**Comment by nchiapol** [comment]
@ThomasEllenberger: Danke für den Hinweis auf das PBS issue. Könnt ihr in Zukunft versuchen Core-Probleme auch (evtl. zusätzlich) im Core-Repo zu erfassen? Dann sehen wir das gleich alle und können Doppelspurigkeiten vermeiden.

**Comment by ThomasEllenberger** [comment]
> [@ThomasEllenberger](https://github.com/ThomasEllenberger): Danke für den Hinweis auf das PBS issue. Könnt ihr in Zukunft versuchen Core-Probleme auch (evtl. zusätzlich) im Core-Repo zu erfassen? Dann sehen wir das gleich alle und können Doppelspurigkeiten vermeiden.

Klar, wenn uns in dem Moment klar ist, dass es sich um ein Core Issue handelt, machen wir dass.

**Comment by ThomasEllenberger** [comment]
@nchiapol @richardjubla der Fix wurde soeben auf euerer Integration deployed.
Wäre super wenn ihr heute noch etwas zum testen kommt.
Wir werden dies morgen auf den Produktionsumgebungen releasen.

**Comment by nchiapol** [comment]
@ThomasEllenberger: Habe das auf unserer Integration getestet. Der Anfrage Tab lässt sich öffnen sowohl wenn eine Anfrage offen ist, wie auch wenn keine wartet. Ausserdem konnte ich die offene Anfrage erfolgreich annehmen und ablehnen. Aus meiner Sicht also gerne Morgen auf die Produktionsumgebung einspielen.

**Comment by richardjubla** [comment]
> @ThomasEllenberger: Habe das auf unserer Integration getestet. Der Anfrage Tab lässt sich öffnen sowohl wenn eine Anfrage offen ist, wie auch wenn keine wartet. Ausserdem konnte ich die offene Anfrage erfolgreich annehmen und ablehnen. Aus meiner Sicht also gerne Morgen auf die Produktionsumgebung einspielen.


Kann das auf unserer Integration ebenfalls **korrekt** testen.
