### ISSUE TITLE
ENV Variablen in config/settings.yml werden nicht escaped

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#30]
Im config/settings.yml werden Werte von ENV Variablen verwendet, z.B.:

```
config:
```

> ```
>   <% if ENV['RAILS_MAIL_RETRIEVER_CONFIG'].present? %>
>     <%= "{ #{ENV['RAILS_MAIL_RETRIEVER_CONFIG']} }" %>
>   <% end %>
> ```

Diese werden jedoch nicht escaped. Es gibt also Zeichen die zu einem Syntax Error führen sobald im wagon.rb ein Settings.rebuild! gemacht wird. In der Variable RAILS_MAIL_RETRIEVER_CONFIG ist unter anderem das Mailserver Passwort enthalten, welches solche Zeichen beinhalten kann.

Das Problem kann wie folgt reproduziert werden:

> $ RAILS_MAIL_RETRIEVER_CONFIG="{" rails c
> require rails:   0.370000   0.110000   0.480000 (  0.481885)
> require gems:   1.040000   0.190000   1.230000 (  1.246623)
> /home/mhofer/.rvm/gems/ruby-2.1.7/gems/config-1.0.0/lib/config/sources/yaml_source.rb:20:in `rescue in load': YAML syntax error occurred while parsing /home/mhofer/projects/hitobito/hitobito/config/settings.yml. Please note that YAML must be consistently indented using spaces. Tabs are not allowed. Error: (<unknown>): did not find expected ',' or '}' while parsing a flow mapping at line 39 column 9 (RuntimeError)
>         from /home/mhofer/.rvm/gems/ruby-2.1.7/gems/config-1.0.0/lib/config/sources/yaml_source.rb:15:in`load'
>         from /home/mhofer/.rvm/gems/ruby-2.1.7/gems/config-1.0.0/lib/config/options.rb:50:in `block in reload!'
>         from /home/mhofer/.rvm/gems/ruby-2.1.7/gems/config-1.0.0/lib/config/options.rb:49:in`each'
>         from /home/mhofer/.rvm/gems/ruby-2.1.7/gems/config-1.0.0/lib/config/options.rb:49:in `reload!'
>         from /home/mhofer/.rvm/gems/ruby-2.1.7/gems/config-1.0.0/lib/config.rb:33:in`load_files'
>         from /home/mhofer/.rvm/gems/ruby-2.1.7/gems/config-1.0.0/lib/config.rb:41:in `load_and_set_settings'
>         from /home/mhofer/.rvm/gems/ruby-2.1.7/gems/config-1.0.0/lib/config/integration/rails.rb:19:in`preload'
>         from /home/mhofer/.rvm/gems/ruby-2.1.7/gems/railties-4.2.5.1/lib/rails/railtie.rb:194:in `public_send'
>         from /home/mhofer/.rvm/gems/ruby-2.1.7/gems/railties-4.2.5.1/lib/rails/railtie.rb:194:in`method_missing'
>         from /home/mhofer/.rvm/gems/ruby-2.1.7/gems/config-1.0.0/lib/config/integration/rails.rb:11:in `block in <class:Railtie>'
>         from /home/mhofer/.rvm/gems/ruby-2.1.7/gems/activesupport-4.2.5.1/lib/active_support/lazy_load_hooks.rb:36:in`call'
>         from /home/mhofer/.rvm/gems/ruby-2.1.7/gems/activesupport-4.2.5.1/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
>         from /home/mhofer/.rvm/gems/ruby-2.1.7/gems/activesupport-4.2.5.1/lib/active_support/lazy_load_hooks.rb:45:in`block in run_load_hooks'
>         from /home/mhofer/.rvm/gems/ruby-2.1.7/gems/activesupport-4.2.5.1/lib/active_support/lazy_load_hooks.rb:44:in `each'
>         from /home/mhofer/.rvm/gems/ruby-2.1.7/gems/activesupport-4.2.5.1/lib/active_support/lazy_load_hooks.rb:44:in`run_load_hooks'
>         from /home/mhofer/.rvm/gems/ruby-2.1.7/gems/railties-4.2.5.1/lib/rails/application.rb:148:in `run_load_hooks!'
>         from /home/mhofer/.rvm/gems/ruby-2.1.7/gems/railties-4.2.5.1/lib/rails/application.rb:96:in`instance'
>         from /home/mhofer/.rvm/gems/ruby-2.1.7/gems/railties-4.2.5.1/lib/rails/railtie.rb:123:in `config'
>         from /home/mhofer/projects/hitobito/hitobito/config/application.rb:34:in`class:Application'
>         from /home/mhofer/projects/hitobito/hitobito/config/application.rb:28:in `<module:Hitobito>'
>         from /home/mhofer/projects/hitobito/hitobito/config/application.rb:27:in`<top (required)>'
>         from /home/mhofer/projects/hitobito/hitobito/bin/commands.rb:25:in `require'
>         from /home/mhofer/projects/hitobito/hitobito/bin/commands.rb:25:in`<top (required)>'
>         from /home/mhofer/projects/hitobito/hitobito/bin/rails:6:in `require_relative'
>         from /home/mhofer/projects/hitobito/hitobito/bin/rails:6:in`<main>'

Das Problem ist im Twiki dokumentiert und wurde von Sophia entdeckt, als sie für die DSJ Instanz ein Passwort mit einem "{" generierte:

https://twiki.puzzle.ch/bin/view/Hitobito/ProjektSetup

**Comment by codez** [comment]
RAILS_MAIL_RETRIEVER_CONFIG muss gültiges YAML enthalten. Sonderzeichen müssen beim Setzen dieser Variable escaped werden. Dies kann die Applikation nicht tun.
