### ISSUE TITLE
Filter: Rollenauswahl auf verfügbare Rollen beschränken

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#300]
## Akzeptanzkriterien

* [ ] Nur jene Rollen zur Auwahl anbieten, welche überhaupt in den gewählten Gruppen vorkommen können.
* [ ] Wähle ich eine Gruppe so wird die mögliche Rollenauswahl sofort erweitert
* [ ] Wähle ich ein Gruppentyp ab, so werden nicht mehr passende Rollen ausgeblendet.

![image](https://cloud.githubusercontent.com/assets/194364/26763279/963555ac-4950-11e7-8e33-1d54095ad33f.png)

**Comment by RolandStuder** [comment]
Mach nur in Zusammenhang mit #298 Sinn

**Comment by RolandStuder** [comment]
@KunoKunz  Es hat hier noch verschiedene Issues zum Personenfilter, ich finde es macht Sinn diese offen zu halten.

**Comment by ThomasEllenberger** [comment]
Umsetzung im Moment nicht geplant.
Issue closed, da bereits 6 jährig.
