### ISSUE TITLE
Filter: Filter für Datumsfelder (4h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#301]
## Akzeptanzkriterien

* [ ] Personenlisten können auch nach Datumsfelder eingeschränkt werden, z. B. Geburtstag oder Eintrittsdatum
* [ ] Matchingstrategien
  * [ ] von / bis 
  * [ ] von oder bis darf leer sein, so dass ich z. B. alle Daten ab einem bestimmten Datum wählen kann.

![image](https://cloud.githubusercontent.com/assets/194364/26763311/2bdaafd0-4951-11e7-83aa-23c34b529c17.png)

**Comment by mlue00** [comment]
Merged https://github.com/hitobito/hitobito/issues/295
