### ISSUE TITLE
Tags sollen von allen Personen mit Schreibberechtigung auf Person bearbeitet werden können. (4h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#302]
* Alle mit :full gibt ability to manage tags
* Alle mit :show_full gibt ability to read tags

**Comment by RolandStuder** [comment]
Schliesse aufgrund von Inaktivität

**Comment by carlobeltrame** [comment]
Wenn ich richtig sehe ist dieses Issue Vorbedingung vom noch offenen Issue #283, korrekt? Dann sollte es vielleicht nicht aufgrund von Inaktivität geschlossen werden.

**Comment by RolandStuder** [comment]
Nicht zwingend, aber ich denke du hast recht, dass es etwas voreilig war dieses Issue zu schliessen.

**Comment by amaierhofer** [comment]
Personen mit `:group_full` und `:group_and_below_full` dürfen nun auch tags lesen und schreiben
