### ISSUE TITLE
Zugriffsrechte auf Personen, welche abgelaufene Rollen in meinen Gruppen haben (12h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#303]
Damit ich eine sinnvolle Suche nach Personen mit abgelaufene Rollen  (#159) in meinen Gruppen kann, brauche ich zumindest minimale Leserechte auf diese Personen. Idealerweise auch Leserechte auf die vergangenen Rollen (Verlauf)

## Akezptanzkriterien

* [ ] Nur im SBV Wagon machen
* [ ] Ich erhalte den gleichen Zugriff auf Personen mit abgelaufene (gelöschten) Rollen in meinen Gruppen, sowohl Lese- wie auch Schreibrechte
* [ ] Spezialimplementation entfernen von #64 (ausblenden im Wagon reicht)
* [ ] Zusatzschätzung machen: Wie gross ist der Aufwand, diese neuen Rechte auf Personen einzuschränken, deren Rolle maximal X Jahre abgelaufen ist?

**Comment by amaierhofer** [comment]
Im Zuge von #159 haben wir damit schon herum experimentiert, ggf könnten die PersonReadables angepasst werden allerdings müssten wir dann auch noch an diversen anderen Stellen die Rollen von Hand joinen.

**Comment by RolandStuder** [comment]
Das würde es erlauben Ehemalige Mitglieder zusehen, ohne denen extra eine Rolle zuordnen zu müssen.
