### ISSUE TITLE
Filter: Rollenfilter auf Bereich einschränken (4h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#304]
Hier nur Frontendanpasssungen, Persistenz in #278 anpassen

## Akzeptanzkriterien

* [ ] Suchbereich kann ausgewählt werden :deep, :layer, :group (ist implementiert im Qualifikationsfilter
* [ ] Default_Suchbereich -> :deep

### Rollenfilter

* [ ] Es stehen nur Rollen zur Auswahl, welche im Suchbereich möglich sind.
* [ ] Default ist: Keine Rollen angewählt
* [ ] Ist keine einzige Rolle gewählt, wird der Rollenfilter ignoriert.

**Comment by codez** [comment]
Auf Branch people_filter
