### ISSUE TITLE
PERSON: Adress Validator tag_invalid failt 

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito#3044]
### Aktuelles Verhalten

Im Address::CheckValidityJob tritt bei `Contactable::AddressValidator#tag_invalid!` der Fehler "Gültigkeitsprüfung ist fehlgeschlagen: Tag ist bereits vergeben" auf. 

Siehe https://sentry.puzzle.ch/pitc/hitobito-backend/issues/52175

### Gewünschtes Verhalten

Der Tag wird nicht erstellt, wenn er bereits existiert.

### Schritte zu reproduzieren

TBD

**Comment by carlobeltrame** [comment]
Duplikatvon #1431
