### ISSUE TITLE
ABOS: Mailchimp Sync Job failed

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito#3045]
### Aktuelles Verhalten

Der ReoccurringMailchimpSynchronizationJob failt mit der Meldung "Gültigkeitsprüfung ist fehlgeschlagen: Group muss ausgefüllt werden". Siehe https://sentry.puzzle.ch/pitc/hitobito-backend/issues/71039

### Gewünschtes Verhalten

Job läuft fehlerfrei durch

### Schritte zu reproduzieren

-

### Wann ist der Fehler aufgetreten?

Seit mehreren Monaten

### Organisation

SAC

**Comment by amaierhofer** [comment]
MailingListe hatte noch eine referenz auf einen nicht mehr existierende Gruppe. Problem trat nur auf SAC INT auf. Die gruppe hat ein `dependent: :destroy` auf die mailing listen, dass beim löschen auch greift. Ich habe die orphaned mailing liste auf INT mal von hand gelöscht.
