### ISSUE TITLE
Fehler beim Nicht-Hinzufügen einer zweiten Datei zu einem Kurs

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#305]
ActionController::ParameterMissing
App: hitobito-tenants Where: event/attachments#create

https://team.hitobito.com/de/groups/1/events/4/attachments

Reproduzierbar mit: 
* \+ hinzufügen 
* Datei auswählen 
* OK (Im OS-Dateidialog)
* \+ hinzufügen 
* Cancel (Im OS-Dateidialog)
→  :boom:

Errbit:

* https://errbit.puzzle.ch/apps/592e69e8473b0b009ced0e9f/problems/59390a7ea48daf009ec39b80
* https://errbit.puzzle.ch/apps/529c60a2de77482d71027b0a/problems/590df0f4de77485ab4000306

**Comment by RolandStuder** [comment]
Bitte PR anschauen. Aber nicht zu lange forschen!

**Comment by psunix** [comment]
tritt nur bei chrome/chromium auf, firefox ist ok
