### ISSUE TITLE
Manchmal gehen Einladungsmails nicht raus

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#308]
IST: 

Es gibt Hinweise, dass die Einladungsmails für hitobito Login nicht immer verschickt werden (https://team.hitobito.com/de/groups/XXX/people/XXX/send_password_instructions)

Siehe auch https://github.com/MartinGantenbein/hitobito_aolv#bekannte-probleme (scheint also nicht an unserer Infrastruktur zu liegen)

Und bei Pro Natura hatten wir das auch schon so: Dort kann ich die konkreten Fälle angeben:
https://hitobito.pronatura.ch/de/groups/38/people/470.html
https://hitobito.pronatura.ch/de/groups/48/people/481.html

SOLL:

Die Mails sollten immer funktionieren.

**Comment by RolandStuder** [comment]
@MartinGantenbein Hast du irgendein Muster gesehen, wann Einladungsmail in hitobito funktionieren und wann nicht? Ihr seid offenbar nicht die einzigen die dieses Problem haben.

**Comment by KunoKunz** [comment]
Habe einen Testuser erfasst, bei dem es nicht geklappt hat: kuno proton. Markus Wernig hat auch erwähnt, dass er nichts erhalten hat.

**Comment by RolandStuder** [comment]
@KunoKunz Bitte hier keine Personendaten festhalten.

**Comment by psunix** [comment]
für das Debuggen wäre es sinnvoll wenn wir eine Art Log für Mails schreiben würden. Ob dies auf der DB oder in einem Logfile passieren soll ist noch offen. Einfach so als erste Idee in Richtung Problembehebung.

**Comment by MartinGantenbein** [comment]
Das Problem bei uns ist nicht, dass die Mails nicht rausgehen, sondern dass der darin angegebene Link nicht funktioniert. Habe da aber bisher nie genauer reingeschaut, weil der Workaround via "Passwort vergessen" zuverlässig funktioniert.

**Comment by RolandStuder** [comment]
Schliesse dies aufgrund von Inaktivität.

Möglicherweise sind die Links jeweils einfach expired.
