### ISSUE TITLE
Gewisse Mails auf dem Catch-All Konto halten die gesamte Queue für Mailinglisten auf

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#309]
## IST:

Wenn ein Mail im Catch-All Konto nicht weiter verarbeitet werden kann, so hängt die gesamte Queue fest und keine weiteren Mails werden verarbeitet.

Somit kann ein einzelne fehlerhaftes Mail alle weiteren Mails blockieren. 

Aktuelle Lösung ist das Mail zu löschen, damit dann alles weiterläuft. Das erfordert aber manuelles eingreifen und kann zu massiven Verzögerungen führen, insbesondere am Wochenende.

## SOLL

Bitte separat diese beiden Schätzen.

* [x] Ein ungültiges Email darf nicht die Queue blockieren.
* [x] Unprocessable Email: raise error and move it to Trash folder

**Comment by RolandStuder** [comment]
Kommentar Hupf: sollte man noch diskuttieren, was wirklich sinn macht. ich denke eine antwort an den absender ist nicht unbedingt angebracht (oftmals sind es auch spam mails oder hacking versuche). wichtig ist, dass es einen errbit fehler gibt.

**Comment by hupf** [comment]
Variante 1 müssen wir genauer definieren:
* In welchem Fall (bei welcher Response/Exception) wird das Mail gelöscht, wann gibt es ein Retry?
* Gibt es eine bestimmte Anzahl Retries bis das Mail gelöscht wird?
* Wie kommen wir zum Mail Content fürs Debuggen (z.B. Errbit, Log)?

**Comment by psunix** [comment]
Case: leerer X-Envelope-To header

wird ein Mail an eine ungültige Domain gesendet, so wird von Puzzle Mailserver beim zurück senden der Errormeldung der Header X-Envelope-To nicht gesetzt. Ein E-Mail ohne X-Envelope-To header wird dann einfach vom MailRelayJob ignoriert und bleibt in der Inbox. 
Diesen fall sollte man sicher auch handeln.

**Comment by RolandStuder** [comment]
Ist anders gelöst, aber gelöst. mit #384
