### ISSUE TITLE
Events: Liste der Einladungen zeigt nur Zeit statt Datum

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito#3104]
### Aktuelles Verhalten

https://cevi.puzzle.ch/groups/85/events/1247/invitations
![screenshot_2024-12-21_233933](https://github.com/user-attachments/assets/5071979b-d1e5-408c-b1d5-47cf355ca2a9)

### Gewünschtes Verhalten

ganzes Datum wird angezeigt

### Schritte zu reproduzieren

Link oben öffnen

### Wann ist der Fehler aufgetreten?

Release test für 1/25

### Organisation

Cevi

### Screenshots, weiterer Kontext

* Der CSV export enthält das korrekte Datum,
* Wie die Dokumentation zeigt, hat das früher korrekt funktioniert: https://github.com/hitobito/user_documentation/blob/master/events.rst

**Comment by kronn** [comment]
Dies tritt aktuell nur auf der Integrationsumgebung auf. Der Bug dahinter ist bekannt und wird als #3069 geführt. Ich schliesse dieses Issue daher als Duplikat.
