### ISSUE TITLE
Protokoll/Notizen zu Events erfassen.

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#311]
Für die Events zum Tribe/Meetup wäre es hilfreich, wenn dazu ein Protokoll erfasst werden könnte. Zum Beispiel analog den Notizen bei den Personen? 

Besteht dazu ein allgemeines Bedürfnis? Gibt es Einwände?

**Comment by RolandStuder** [comment]
Hier einfach einmal mehr die Frage, wer soll das sehen können? Teilnehmer? Dann wäre es grundsätzlich verschieden von den bestehenden Personennotizen.

**Comment by KunoKunz** [comment]
Ja, die Teilnehmer respektive Mitglieder der entsprechenden Gruppe. Ziel wäre u.A., dass auch die informiert sind, welche am Anlass nicht teilnehmen konnten.

**Comment by ThomasEllenberger** [comment]
Umsetzung im Moment nicht geplant.
Issue closed.
