### ISSUE TITLE
Neuer Gruppentyp Ehemalige (8h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#312]
# Neu ist:

* Leitung Ehemalige hat auch darunterliegenden Ebenen Zugriff auf Ehemalige.

## Rollen

* **Leitung**
   * Lesen und Schreiben auf dieser Gruppe. :group_and_below_full
   * Lesen und Schreiben von Personen und Gruppen auf allen Gruppen Ehemalige der darunterliegenden Ebenen => Abilities spezifisch für diese Rolle erweitern
    * Lesen der Kontaktdaten aller anderen Personen mit Kontaktdatenberechtigung., :contact_data

* **Adressverwaltung**
  * Lesen und Schreiben auf der Gruppe. :group_and_below_full
  * Erstellen von Anlässen und Abos auf der Gruppe.

* **Kassier**
  * Lesen auf der Gruppe. :group_and_below_read
  * Lesen der Kontaktdaten aller anderen Personen mit Kontaktdatenberechtigung. :contact_data

* **Mitglied**
  * Lesen auf der Gruppe. :group_read

* **Extern**
   * Die Rolle Extern kann nur öffentliche Daten (Gruppen, Anlässe und Abos; keine anderen Personen) sehen.
  * Diese Rolle ist nur von Personen in dieser Ebene sichtbar, nicht von Personen aus darüber liegenden Ebenen.

* **Versandadresse Ehemalige**
  * Die Rolle Versandadresse kann nur öffentliche Daten (Gruppen, Anlässe und Abos; keine anderen Personen) sehen.

## Akzeptanzkriterien:

* [ ] Wer, wie bisher, :layer_full  hat, soll auch die Ehemaligen sehen. z. B. ein BuLei, oder Leiter Arbeitsstelle.
* [ ] Zu jeder Ebene wird eine Ehamligengruppe erstellt siehe #313 
* [ ] Auch Rolle Extern existiert hier, zum Beibehalten der Konsistenz
* [ ] Es können Untergruppen "Ehemalige" angelegt werden

# Offene Fragen

* [ ] Sollen Mitglieder wirklich Leserechte haben, da da alle Ehemaligen aufgeführt werden? 
* [ ] Braucht **Leitung** auch Möglichkeit Abos / Events auf Unterebenen zu Verwalten? (wäre einfacher, wenn nicht.)

Kommentar hierzu. Es schein, dass man das also über eine ganze reguläre Gruppenstruktur lösen könnte (was das ganze natürlich weniger komplex und günstiger macht). Einzig das Lesen von Ehemaligen darunter liegenden Kantonen oder Scharen wäre dann speziell zu lösen.

**Comment by RolandStuder** [comment]
* Wer, wie bisher, :layer_full hat, soll auch die Ehemaligen sehen können oder nicht? z. B. ein BuLei, oder Leiter Arbeitsstelle? Ja, nein? Es wäre hilfreich, wenn das zugelassen wäre, das würde die Lösung einiges einfacher machen, sonst wird es sehr kompliziert.

* Verstehe ich das richtig Leitung in der Gruppe Ehemalige, soll NUR auf ehemalige aus Unterebenen zugreifen können, aber nicht auf andere Personen, wie z. B. Leiter? Beispiel Verwalter der Ehemaligen auf Bundesebene, soll Ehemalige auf Kantons oder Scharebene sehen können. Er soll aber nicht die aktiven Mitglieder sehen können, korrekt?

* Mitglied: Lesen auf der Gruppe. Sei ihr da sicher? Sollen dort alle einander sehen? Passt das zum Beispiel auf Bundesebene, dort hat man vielleicht dann Zugriff auf Daten, auf die man vorher nicht Zugriff hatte, nur weil man mal 1 Monat in einer Projektgruppe drin war, plötzlich sehe ich alle ehemaligen BuLeis usw…

* Braucht ihr wirklicht die Rolle Extern hier?

Kommentar hierzu. Es schein, dass man das also über eine ganze reguläre Gruppenstruktur lösen könnte (was das ganze natürlich weniger komplex und günstiger macht). Einzig das Lesen von Ehemaligen darunter liegenden Kantonen oder Scharen wäre dann speziell zu lösen.

**Comment by RomanOester** [comment]
> Wer, wie bisher, :layer_full hat, soll auch die Ehemaligen sehen können oder nicht? z. B. ein BuLei, oder Leiter Arbeitsstelle? Ja, nein? Es wäre hilfreich, wenn das zugelassen wäre, das würde die Lösung einiges einfacher machen, sonst wird es sehr kompliziert.
Ja, dies soll auch der Fall sein.

**Comment by RomanOester** [comment]
> Wer, wie bisher, :layer_full hat, soll auch die Ehemaligen sehen können oder nicht? z. B. ein BuLei, oder Leiter Arbeitsstelle? Ja, nein? Es wäre hilfreich, wenn das zugelassen wäre, das würde die Lösung einiges einfacher machen, sonst wird es sehr kompliziert.

Ja, dies soll auch der Fall sein.

**Comment by RomanOester** [comment]
> Verstehe ich das richtig Leitung in der Gruppe Ehemalige, soll NUR auf ehemalige aus Unterebenen zugreifen können, aber nicht auf andere Personen, wie z. B. Leiter? Beispiel Verwalter der Ehemaligen auf Bundesebene, soll Ehemalige auf Kantons oder Scharebene sehen können. Er soll aber nicht die aktiven Mitglieder sehen können, korrekt?

Genau, nur Zugriff auf Ehemalige, jedoch auch auf die eigene Ebene (sowie darunterliegende). Die aktiven Mitglieder soll man nicht sehen können.

**Comment by RomanOester** [comment]
> Mitglied: Lesen auf der Gruppe. Sei ihr da sicher? Sollen dort alle einander sehen? Passt das zum Beispiel auf Bundesebene, dort hat man vielleicht dann Zugriff auf Daten, auf die man vorher nicht Zugriff hatte, nur weil man mal 1 Monat in einer Projektgruppe drin war, plötzlich sehe ich alle ehemaligen BuLeis usw…

Ist denn dies nicht auch jetzt schon so bei einer Gruppe? Aktuell hat man ja auch als Ehemaliger einer Gruppe Zugriff auf die aktuellen Mitglieder der Gruppe. Man hat ja dann nur Leserechte auf der entsprechenden Gruppe. Als ehemaliges Fachgruppenmitglied auf Bundesebene sehe ich dann nicht gleich die ehemaligen Buleis, da ja das Ganze in sich noch eine Struktur hat.

**Comment by RomanOester** [comment]
> Braucht ihr wirklicht die Rolle Extern hier?

Es geht hier wohl eher um die Vollständigkeit bzw. dass auch die "normale" Struktur und die "normalen" Rollen verfügbar sind. Z.B. kann die Rolle "Extern" benötigt werden, wenn man ein Ehemaligenfest organisiert und dort z.B. auch den Grillmeister in der DB einträgt oder die Sponsoren oder so.

**Comment by RomanOester** [comment]
> Kommentar hierzu. Es schein, dass man das also über eine ganze reguläre Gruppenstruktur lösen könnte (was das ganze natürlich weniger komplex und günstiger macht). Einzig das Lesen von Ehemaligen darunter liegenden Kantonen oder Scharen wäre dann speziell zu lösen.

Genau, im Grunde ist es eine zusätzliche, aber an sich reguläre Gruppenstruktur: Ein neuer Gruppentyp, der sich über alle Ebenen hinzieht > bei jeder "aktiven" Gruppe gibt es eine "ehemalige" Gruppe.

**Comment by RomanOester** [comment]
Die Frage ist noch, ob Mitglieder der Gruppe "Ehemalige" wirklich Leserechte haben sollen. Wird geklärt.

**Comment by RolandStuder** [comment]
Ok, wir konnten das grundsätzlich jetzt im Gespräch nachvollziehen. Wir würden das in eine Gruppe abbilden, ohne die bisherigen Ehemaligenrollen anzufassen.

Wir denken es ist ein grosses Risiko, dass das verwirrlich wird, wenn wir gleichzeitig, die alten Ehemaligenrollen behalten und das neue System einführen. Aber das ist am Ende eure Entscheidung. Die alten Ehemaligenrolle zu entfernen sollte auch nicht so aufwändig sein. Am besten klären wir dass dann in Konzeptionsmeetings. Aber wir schätzen das jetzt mal so.

Idee, wir könnten Zugriff auf Ehemalige von anderen Gruppen über materialisierte Listen lösen (erkläre ich gerne mal am Telefon, was das ist). Dann hätten wir eine allgemeine Lösung dafür, die wir auch für andere Zugriffserweiterungen verwenden können (siehe #331 und #335).

**Comment by RolandStuder** [comment]
Leseberechtigung tatsächlich so, ausser wenn, wir Kinder auch dort aufnehmen.

**Comment by RolandStuder** [comment]
Wird abgedeckt durch #366 und #367
