### ISSUE TITLE
Gruppentyp Ehemalige existiert automatisch (4h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#313]
In jeder Gruppe mit Typ Bund, Kanton, Region oder Schar soll eine neue Gruppe mit Typ Ehemalige mit dem Namen „Ehemalige“ erstellt werden.

# Akzeptanzkriterien

* [ ] Migrationen erstellen
* [ ] Löschen verhindern
* [ ] automatisches Anlegen 
* [ ] Gruppe heisst "Ehemalige"

**Comment by RolandStuder** [comment]
* Die Gruppe sollte also wohl nicht löschbar sein, oder doch?
* Ich nehme an, auch bei den Ehemaligen sollte man Untergruppen anlegen können, um innerhalb dieser Liste noch etwas organisieren zu können?Oder ist dies einfach eine Personenliste und fertig?

**Comment by RomanOester** [comment]
> Die Gruppe sollte also wohl nicht löschbar sein, oder doch?

Nein, die Gruppe darf nicht gelöscht werden können, sie besteht, ob man will oder nicht.

> Ich nehme an, auch bei den Ehemaligen sollte man Untergruppen anlegen können, um innerhalb dieser Liste noch etwas organisieren zu können?Oder ist dies einfach eine Personenliste und fertig?

Ja, es sollen auch innerhalb der Ehemaligen Untergruppen hinzugefügt werden können.

**Comment by RolandStuder** [comment]
Im Falle von materialisierten Liste, könnten man die schon auch automatisch anlegen lassen. Ehemaligen Untergruppen, wären nicht so einfach zu machen, weil die Rolle dann ja bei materialisierung neu erstellt werden müsste, aber man könnte nebendran Listen anlegen, wo man die Leute dann eintragen könnte.

**Comment by RolandStuder** [comment]
Wird abgelöst von Issues #368 und #369
