### ISSUE TITLE
Migration Ehemalige (8h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#314]
Wenn eine Person auf einer Ebene in mindestens einer Untergruppe mit der Rolle Ehemalig erfasst ist und in keiner anderen Gruppe der selben Ebene eine aktive Rolle hat, soll diese Person in die Gruppe mit dem Typ Ehemalige in dieser Ebene mit der Rolle Mitglied hinzugefügt werden.
 
- aktive Rolle -> nicht hinzufügen
- aktive Rolle, Ehemalig -> nicht hinzufügen
- aktive Rolle, Versandadresse -> nicht hinzufügen
- aktive Rolle, Ehemalig, Versandadresse -> nicht hinzufügen
- Ehemalig -> hinzufügen
- Ehemalig, Versandadresse -> hinzufügen
- Versandadresse -> nicht hinzufügen
- Ausnahme: Wenn Kind Rolle "Ehemalig von Kindergruppe" hat -> nicht hinzufügen.

Eine Ausnahme ist, wenn die Person nur als Kind in einer Kindergruppe vorhanden ist. In
 diesem Fall soll das Kind nicht in die Gruppe der Ehemaligen hinzugefügt werden.

Zu machen

* Die alten Ehemaligenrollen, die bei allen Gruppen vorkommen z. B.  sollen umbenannt werden, z. B. in `Archivierte Rolle` (nur Übersetzung, am Modell nicht ändern)
* Migrationen gemäss obenstehendem

**Comment by RolandStuder** [comment]
Scheint mir recht klar zu sein.

Wieso die Spezialbehandlung der Versandadresse? Was ist die Idee dahinter? Wäre froh das zu wissen, nicht dass wir hier etwas unnötig komplexes machen.

* Ich nehme an, wir löschen dann die anderen „Ehemaligenrollen“ und behalten nur die neue Rolle Mitglied bei Ehemaligen. Stimmt das?

**Comment by RomanOester** [comment]
> Wieso die Spezialbehandlung der Versandadresse? Was ist die Idee dahinter? Wäre froh das zu wissen, nicht dass wir hier etwas unnötig komplexes machen.

Die Versandadresse wird nicht speziell behandelt: Wenn jemand nur diese Rolle hat, wird man nicht zu einer Ehemaligengruppe hinzugefügt. Ist man aber Ehemalig und hat die Rolle Versandadresse, dann schon. Denn "Versandadresse" heisst ja nur, dass man in einer Versandliste drin ist, man kann aber trotzdem Ehemalig sein.

> Ich nehme an, wir löschen dann die anderen „Ehemaligenrollen“ und behalten nur die neue Rolle Mitglied bei Ehemaligen. Stimmt das?

Im Moment würde ich sagen ja – vielleicht muss hier noch die FG Datenbank genau klären, welche Auswirkungen dies hätte. Dies bedingt auch eine Kommunikation unsererseits an die Scharen, weil ja z.T. mit diesen Rollen gearbeitet wird.

Folgende Frage haben wir uns aber glaub ich bisher nie gestellt: Was passiert mit der Anzeige "Ehemalige Rollen"? Oder meintest du das damit?
Könnten diese Rollen einfach so und vollständig ersetzt werden?

**Comment by RolandStuder** [comment]
Cool wäre natürlich, wenn wir es hier hinkriegen die Liste so konfigurierbar zu machen, dass man sie einfach über den normalen Filter materialisieren könnte, dafür wäre notwendig:

* Ich kann sagen, hatte Rolle XYZ abgeschlossen vor heute
* Person nur einschliessen, wenn keine der folgenden Rollen ABC

Andererseits können wir es über ein Custom Flag machen, das wäre wohl einfacher zu bewerkstelligen.

**Comment by RomanOester** [comment]
Das mit den materialisierten Listen und Custom Flag und so müssen wir noch kurz besprechen ;-)

**Comment by RolandStuder** [comment]
Issues ist veraltet und abgelöst.
