### ISSUE TITLE
Automatisches Hinzufügen zur Gruppe Ehemalige (12h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#315]
Falls eine aktive Rolle einer Person zu Ehemalig geändert wird, soll geprüft werden ob die Person noch eine aktive Rolle in dieser Ebene und deren Untergruppen hat. 

Ist dies nicht der Fall, soll die Person der Gruppe mit dem Typ Ehemalige in dieser Ebene mit der Rolle Mitglied hinzugefügt werden. 

Zudem soll ein personalisiertes Mail mit nachfolgendem Inhalt an die Person versandt werden. 
Der Mail Inhalt soll auf jeder Ebene über den Admin Bereich angepasst werden können:

> Liebe X / Lieber Y
Herzlichen Dank für dein wichtiges Engagement für Jungwacht Blauring. Bestimmt hast du viele tolle Erlebnisse gehabt und gute Freundschaften aufgebaut – eben Lebensfreu(n)de.
"Freude und Freunde – und das fürs Leben" soll auch heissen, dass deine Jubla-Zeit jetzt nicht
vorbei sein muss. Als frischgebackene Ehemalige / frischgebackener Ehemaliger bist du nämlich ein wichtiger Teil für Jungwacht Blauring. Vielleicht braucht deine ehemalige Schar jedes Jahr tatkräftige Unterstützung beim Sommerlager-Aufbau? Oder der entsprechende Kantonalverband ist auf der Suche nach Leuten, die beim kantonalen Geländespiel die Verpflegung organisieren? Es wäre doch toll, wenn du auf diese oder andere Arten noch mit Jungwacht Blauring in Verbindung bleiben könntest.
Darum kannst du in deinem Profil auf der jubla.db (Link auf das Personenprofil) bestimmen, welche Ebene dich in Zukunft kontaktieren und dir Informationen senden darf. Vielen Dank nochmals für dein Engagement – auch über deine aktive Zeit hinaus.
Liebe Grüsse
Jungwacht Blauring Schweiz

# Akzeptanzkriterien

## Hinzufügen

* [ ] Beim Löschen der letzten aktiven Rolle in einer Ebene, erstellen wir eine Rolle Ehemalige::Mitglied
* [ ] Die Rolle Ehemalig wird in einer zufälligen Ehemaligengruppe direkt unter der Ebene angelegt. (Zufällig weil, wir bei mehreren Ehemaligengruppen nicht wissen, welche primär ist).
* [ ] Hat eine Person schon eine Rolle Ehemalige::Mitglied , auch in einer Untergruppe in derselben Ebene, dann wird die Rollen nicht erstellt.

## Ehemaligenmail verschicken

* [ ]  Wir verschicken diese Mails am darauf folgenden Nacht, damit Löschen und neue Rolle erstellen nicht zum Versand eines Mails führt. Job wird beim erstellen der Ehemaligen Rolle für die darauf folgende Nacht gescheduled, falls bis dann die Ehemaligenrolle wieder entfernt wurde, wird das Mail nicht geschickt.
* [ ] Wenn Ehemalige Rollen aus anderen Ebenen bereits vorher existiert haben, wird trotzdem ein Mail verschickt.

Definition Aktive Rolle: Alle ausser Versandadresse, Ehemalig und Extern

* [ ] 2 Mails im Admin Bereich definierbar (ein fürs Scharen und eins für andere Ebenen)
* [ ] Diese Email werden auch für Personen verschickt, welche kein Login haben.
* [ ] Hat eine Person schon eine Ehemalige Rolle (manuell hinzugefügt). Erhält er kein Email.

**Comment by RolandStuder** [comment]
Ich würde vorschlagen hier etwas vorsichtiger zu sein. Einfach ein Mail rauszuschicken, wenn ich die letzte aktive Rolle lösche, könnte dazu führen, dass ich z. B. Personen die ich eigentlich nur verschieben will, kurz als Ehemalige deklariere und so aus versehen anschreibe.

Daher wäre es wohl besser, beim Löschen der Rolle nachzufragen, ob die Person zu den Ehemaligen hinzugefügt und darüber informiert werden soll.

Oder zumindest fragen, ob ein solches Mail verschickt werden soll.

* Soll für Ehemalige welche gar kein Login haben, überhaupt ein Mail verschickt werden? Das wäre nämlich dann ihr erster Kontakt mit der DB.

Sollte eine Person dann nicht auch die Rolle Ehemalige verlieren, wenn sie wieder aktiv ist, oder wollt ihr das manuell behandeln?

Ich denke hier auch wieder an den Fall, dass ich jemanden aus einer Gruppe austrage, und dann in einer anderen wieder eintrage. Diese Person wird dann „Ehemalig“, obwohl ich sie nur „verschoben“ habe (weil ich nicht immer daran denke, dass ich die Person auch verschieben könnte)

**Comment by RomanOester** [comment]
> Ich würde vorschlagen hier etwas vorsichtiger zu sein. Einfach ein Mail rauszuschicken, wenn ich die letzte aktive Rolle lösche, könnte dazu führen, dass ich z. B. Personen die ich eigentlich nur verschieben will, kurz als Ehemalige deklariere und so aus versehen anschreibe.
Daher wäre es wohl besser, beim Löschen der Rolle nachzufragen, ob die Person zu den Ehemaligen hinzugefügt und darüber informiert werden soll.
Oder zumindest fragen, ob ein solches Mail verschickt werden soll.

Wenn ich mich richtig erinnere haben wir diskutiert, ob gefragt werden soll, ob ein Mail verschickt werden soll oder nicht. Wir haben dies mit Ja beantwortet, da es ein übergeordnetes Interesse ist, den frischen Ehemaligen zu danken und bestenfalls noch ein wenig zu "behalten", eben z.B. indem sie das Einverständnis geben, kontaktiert zu werden. Dem "aus Versehen verschieben" liegt ja eine Fehlnutzung der Datenbank zugrunde, warum wir einen solchen konkreten Fall in Kauf nehmen.

> Soll für Ehemalige welche gar kein Login haben, überhaupt ein Mail verschickt werden? Das wäre nämlich dann ihr erster Kontakt mit der DB.
Sollte eine Person dann nicht auch die Rolle Ehemalige verlieren, wenn sie wieder aktiv ist, oder wollt ihr das manuell behandeln?
Ich denke hier auch wieder an den Fall, dass ich jemanden aus einer Gruppe austrage, und dann in einer anderen wieder eintrage. Diese Person wird dann „Ehemalig“, obwohl ich sie nur „verschoben“ habe (weil ich nicht immer daran denke, dass ich die Person auch verschieben könnte)

Ja, auch Ehemalige ohne Login sollen das Mail erhalten. Über die Jahre wird es immer mehr Leute geben, die so oder so ein Login haben bzw. gehabt haben und schon mal von der Datenbank gehört haben. Die Person soll den Status Ehemalig nur dort verlieren, wo sie wieder aktiv wird. Wenn sie aber aus der Schar austritt und nach ein paar Jahren z.B. in die Kantonsleitung geht, bleibt sie Ehemalig auf Stufe Schar (und hat schon mal das Infomail erhalten) und wird aktiv auf Kantonsebene. Tritt sie dort aus, erhält sie ein neues Mail mit einem anderen Inhalt. Bisher war nur von einem einzelnen Mail die Rede, wir möchten aber zwei verschiedene Mails: eines bei Austritt aus Stufe Schar, eines bei Austritt auf Stufen Kanton und Bund.

**Comment by RolandStuder** [comment]
Das müsste auch mit materialisierten Listen nach wie vor Custom gelöst werden.

**Comment by RolandStuder** [comment]
Wird abgelöst von #371 und #372
