### ISSUE TITLE
Import ehemalige Personen (8h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#316]
Die Importfunktion soll so angepasst werden, dass auch Listen mit Ehemaligen Personen der Datenbank hinzugefügt werden können. Also wenn **beim Import die Rolle als Ehemalig::Mitglied eingestellt** wird, soll geprüft werden ob die Person in anderen Gruppen derselben Ebene noch aktive Rollen hat. Ist dies nicht der Fall, soll die Person der Gruppe mit dem Typ Ehemalige in dieser Ebene mit der Rolle Mitglied hinzugefügt werden.

# Entscheidungen

* Sollen hier auch Mails ausgelöst werden, wie bei #315? -> NEIN, keine Mails
* Auch beim manuellen hinzufügen der Rolle Ehemalig -> KEIN Mail verschicken
* Fehlermeldung für Personen, welche noch eine aktiv Rolle in der Ebene haben.

**Comment by RolandStuder** [comment]
Ok, sollten wir über einen Duplettencheck lösen können, wird aber sicher nicht ganz trivial. Der Import ist schon relativ komplex, insbesondere müssen wir dabei schauen, dass nachvollziehbar bleibt, wer jetzt importiert wird und wer nicht.

**Comment by RomanOester** [comment]
Hier soll kein Mail ausgelöst werden, weil es ja ein manueller Import ist, der auch x Jahre nach dem Ausstieg passieren kann.
