### ISSUE TITLE
Einstellung der Kontaktdaten durch die Person (4h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#317]
Bei allen ehemaligen Personen erscheint nach "Nationalität gemäss J+S" ein neuer Abschnitt mit dem Titel "Kontaktfreigaben". Dort gibt es drei Zeilen, wo die Person im Bearbeitungsmodus Häkchen setzen bzw. entfernen kann. Folgender Text soll im Bearbeitungsmodus sichtbar sein:

Mit dem Setzen eines Häkchens erlaubst du folgenden Ebenen, dich zu kontaktieren und dir Informationen zu senden:

- lokale Ebene (Schar)
- regionale Ebene (Regionalleitung, Fach- und Arbeitsgruppen)
- kantonale Ebene (Kantonsleitung, Fach- und Arbeitsgruppen)
- nationale Ebene (Verbandsleitung, Bundesleitung, Fach- und Arbeitsgruppen)

Ansichtmodus: Angezeigt werden jeweils zu  alle Ebenen ein Label Ja / Nein
 
Wichtig: Personen, die bei einer jeweiligen Ebene das Häkchen nicht gesetzt haben, dürfen bei gefilterten Abfragen nicht erscheinen.

Das Filtern wird unter #347 abgehandelt.

# Akzeptanzkriterien

* [ ] Der Einstellungsbereich Ehemaligenversände erscheint nur, wenn ich nur Rollen vom Typ Ehemalig::Mitglied inne habe.

Diese Personen bei gefilterten Abfragen zu ignorieren, wird sicher eine Herausforderung. Das betrifft nämlich Abo, so wie Personenliste:

**Comment by RolandStuder** [comment]
* Dürfen die Häckchen schon erscheinen, wenn er die Ehemaligenrolle nicht hat?

Diese Personen bei gefilterten Abfragen zu ignorieren, wird sicher eine Herausforderung. Das betrifft nämlich Abo, so wie Personenliste:

* Dann ist die Frage, führt jede Filterung automatisch zum Ausschluss?

* Ein Ehemaliger erscheint also auf keiner Mailingliste / keinem Abo von der Region, wenn er das entsprechende Häckchen nicht gesetzt hat?

* Es wäre sicher einfacher und klarer, wenn dies über eine allgemeine Filterfunktion abgedeckt wird, wo ihr bei der Generierung der Liste explizit sagt, dass ihr nur Leute haben wollte, welche ein Häckchen gesetzt haben. Siehe https://github.com/hitobito/hitobito/issues/296

* Ich nehme an, ihr benötigt diese Funktion definitiv auch für Abos, oder? Dann würde nämlich obenstehendes Issue nicht ausreichen.

* Wäre das Szenario denkbar, die Personen nur von Abos auszuschliessen, aber nicht von Personenlisten? (die ihr in mittlerer Zukunft nach diesen Häckchen solltet filtern können).

**Comment by RomanOester** [comment]
Ich finde die Fragen zu komplex, um sie einfach so schriftlich beantworten zu können.
Die Idee dahinter ist, dass Ehemalige selbst definieren können, von welcher Ebene und ob überhaupt sie kontaktiert werden wollen. Gedacht wäre, dass die aktiven Personen dies nicht können, denn z.T. bedingt ihre Rolle (z.B. Scharleitung), dass sie gewisse Infos erhalten – ob sie wollen oder nicht. Aber die Ehemaligen möchten wir möglichst bedarfsgerecht behandeln und informieren. Im Grunde dachten wir, dass diese Häkchen bei der Filterfunktion berücksichtigt werden, für Ad-hoc-Versände. Sonst – z.B. bei Zugehörigkeit bei einem Abo – sollen die Häkchen ignoriert werden. Weil zu einem Abo hat man sich unter Umständen mal angemeldet und es ist eher etwas regelmässiges.

Ein Anwendungsfall ist z.B., wenn die Bundesleitung für die Einladung zu einem nationalen Anlass die Ehemaligen anschreiben will. Dann passiert das über die Filterfunktion auf der obersten Stufe. Dasselbe ist aber auch beim Kanton denkbar oder bei der Schar.

**Comment by RolandStuder** [comment]
Diskussion am Telefon hat gezeigt, dass man wohl vor allem genau beim Abo eben dies muss berücksichtigen können.
