### ISSUE TITLE
Filter und Suchen mit Datumsstempel (12h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#318]
Es soll möglich sein, Personen nach Rollen und dessen Von- und Bis-Daten zu filtern. z.B.:

- finde alle Personen, welche die Rolle Scharleitung zwischen 1980 und 1990 innehatten.
- finde alle Personen, welche im Jahr 2010 in der Schar xy Ehemalig wurden.

siehe auch https://github.com/hitobito/hitobito/issues/159

**Comment by RolandStuder** [comment]
War bereits Thema und haben wir geschätzt, siehe https://github.com/hitobito/hitobito/issues/159

Es wäre gut dies allgemein zu lösen über alle Verbände hinweg, bedingt aber grosszügigere Leseberechtigungen bei anderen Organisation, das wollen wir in den nächsten Wochen mit diesen anderen Gruppen klären. Gewisse Vorarbeiten haben wir dafür schon gestartet.

**Comment by RomanOester** [comment]
Gut, wenn dies schon angedacht ist. Gerade für die Bundesebene ist dies ein wichtiges Feature.

**Comment by RolandStuder** [comment]
Über materialisierte Listen könnte man individuell steuern, wer sinnvollerweise Zugriff haben sollte, bei anderen Verbänden. Damit könnte man evtl. https://github.com/hitobito/hitobito/issues/303 umschiffen.
