### ISSUE TITLE
Report toter Adressen (10h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#319]
Es soll möglich sein, Angaben von Personen als inkorrekt zu melden (nicht mehr aktuelle Adressen, Telefonnummer, E-Mail-Adresse). Die Angaben sollen markiert werden, so dass entweder die Person selbst, oder eine befugte Person die Angaben korrigieren kann.

* Schätzung beinhaltet Email-Benachrichtigung mit einem kurzen Text des Reporters.
* Anzeige auf der Person, dass eine Meldung vorliegt und sie wird angezeigt
* Meldung kann dismissed werden.
* Benötigt Custom Content im Admin Bereich

# Idee

* [ ] Wir senden Nachricht an "näheste" Person mit Schreibberechtigung": Ausgehend von der Primär-Gruppe, dann suchen bis wir eine besetze Rolle finden, die auf die Person Schreibberechtigung hat, Priorität nach Rollenreihenfolge.
* [ ] Jeder mit Leseberechtigung kann Meldung machen.

## Offene Fragen

* [ ] Bezieht sich diese Meldung auf einzelne Angaben? also markiert man eine einzelne Telefonnummer als „tot“ oder auf die ganze Person?
* [ ] Wer soll dann wie informiert werden? Wie soll ich entdecken, welche Angaben ich anpassen soll?
* [ ] Welche Berechtigung erlaubt eine solche Meldung zu machen?
* [ ] Wird beim markieren ein Vorschlag gegeben, welches die korrekte Angabe ist, oder sonst ein Texthinweis?
* [ ]  Habt ihr eine Vorstellung, wie das aussehen könnte, oder Beispiele, wo eine solche Funktionalität bereits umgesetzt wurde.
* [ ]  Ist mir insgesamt noch ein bisschen unklar, wie das insgesamt aussehen soll beim Report von toten Adressen.
* [ ] Vielleicht könnt ihr hier auch noch etwas Auskunft geben, wann ihr auf Probleme stösst und wie das bisher gehandhabt wird.

**Comment by fossil12** [comment]
Finde ich eine sehr gute Idee.

**Comment by RolandStuder** [comment]
* Bezieht sich diese Meldung auf einzelne Angaben? also markiert man eine einzelne Telefonnummer als „tot“ oder auf die ganze Person?
* Wer soll dann wie informiert werden? Wie soll ich entdecken, welche Angaben ich anpassen soll?
* Welche Berechtigung erlaubt eine solche Meldung zu machen?
* Wird beim markieren ein Vorschlag gegeben, welches die korrekte Angabe ist, oder sonst ein Texthinweis?
* Habt ihr eine Vorstellung, wie das aussehen könnte, oder Beispiele,  wo eine solche Funktionalität bereits umgesetzt wurde.

Ist mir insgesamt noch ein bisschen unklar, wie das insgesamt aussehen soll beim Report von toten Adressen.

Vielleicht könnt ihr hier auch noch etwas Auskunft geben, wann ihr auf Probleme stösst und wie das bisher gehandhabt wird.

**Comment by RomanOester** [comment]
Vielleicht reicht hier ein einfacher "Fehler bei Kontaktdaten melden"-Button (ähnlich wie das Melden von Spam-Profilen auf sozialen Plattformen), bei dessen Klick ein Fenster aufgeht mit der Aufforderung, genau zu beschreiben, was falsch ist. Dann geht eine Meldung zur Person und z.B. bei keiner Aktion innerhalb einer Woche zur Rolle "Leitung" der entsprechenden Gruppe mit der Aufforderung/Bitte, Abklärungen zu treffen bzgl. den gemeldeten falschen Kontaktdaten.
Mir stellt sich spontan die Frage nach dem Missbrauch dieser Funktion.
Mit dieser Funktion soll die Qualität der Adressen gesteigert werden bzw. eben alte und nicht mehr aktualisierbare Adressen nicht mehr berücksichtigt werden.

**Comment by RolandStuder** [comment]
Es bleibt etwas schwierig, zu wissen, wer genau informiert werden soll. Es gäbe dort durchaus Algorithmen, aber es ist etwas kompliziert. Vorschläge wäre naheste Rollen mit Schreibberechtigung zu finden: Ich nehme die Primärgruppe, und suche, ob es eine besetzte Rolle mit Schreibberechtigung gibt, wenn nicht, such ich ein Gruppenstufe höher, ob es dort jemanden hat, bis zur Ebene, dann wird es tricky, weil schreibberechtigte Personen auch auf Untergruppen sein können. Dann suchen wir vielleicht weiter nach Personen mit :layer_full Berechtigung. Und nehmen die erste erwähnte Rolle gemäss Priorisierung in der Klasse.

Oder einfache Custom Lösung, einfach an nähesten "Adressverantwortlichen" schicken.

**Comment by RomanOester** [comment]
Aufgrund der Kosten dieses Features stellt sich mir die Frage nach dem tatsächlichen Nutzen. Meiner Meinung nach ist dieses Feature nice-to-have, aber nicht unbedingt notwendig. Vor allem auch deshalb, weil die technische Umsetzung komplex zu sein scheint.
Am besten besprechen wir dies noch kurz telefonisch.

**Comment by KunoKunz** [comment]
Die Jubla möchte dies momentan noch nicht realisieren. Ist vom Aufwand her ziemlich hoch und bringt wohl nicht den entsprechenden Nutzen.

**Comment by RolandStuder** [comment]
Kosten / Nutzen stimmt nicht, schliesse diese Issue aufgrund mangelndem Interesse
