### ISSUE TITLE
Anpassen der Standardfragen bei Jubla Kursen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#320]
Diese Seeds müssen angepasst werden
https://github.com/hitobito/hitobito_jubla/blob/6c9ce439e2144ed5c9aa24a0c681b4ecb5135ceb/db/seeds/event_questions.rb

- Ich habe während dem Kurs folgendes ÖV Abo
GA, Halbtax / unter 16 Jahre, keine Vergünstigung

- Ich bin Vegetarier/in
ja, nein

- Ich habe bereits das neue Kurshilfsmittel «schub» (Auflage 2016)
ja, nein

- Ich habe bereits ein Meisterwerk (das Handbuch der Mindestkenntnisse)
ja, nein

**Comment by psunix** [comment]
in den seeds entsprechend angepasst.
auf jubla production manuell angepasst.

**Comment by RolandStuder** [comment]
Webliche Form fehlt gemäss Bernhard Schüssler: Vegetarier/in

**Comment by psunix** [comment]
in prod und in den Seeds Vegetarier/-in angepasst
