### ISSUE TITLE
Weitere Adress-Angaben als Privat markieren

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#321]
Frage @jharari

> Ist es möglich, dass man bei weiteren Angaben die Option hat, um zwischen "privat" bzw. "öffentlich" auszuwählen? Oder ist dies mit einem grossen Mehraufwand verbunden? Insbesondere wäre das für die Felder "Adresse", "PLZ", "Ort", "Geburtsdatum" massgebend.

@jharari Wie sehr macht das Sinn? Dann sehe ich bei Personen, plötzlich nur noch den Namen. Und es erhöht wieder die Komplexität. Machbar wäre es schon, dass man die gesamte Adresse als Privat markiert. Aber ich erachte es nicht unbedingt als sinnvoll.

**Comment by jharari** [comment]
Habe das intern abgeklärt. Vorläufig ist es in Ordnung so wie es ist.
