### ISSUE TITLE
Migration alle Telefonnummer und Emailadressen von öffentlich nach privat (3h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#322]
## Akezptanzkriterien

* [x] Migration von allen Flags "öffentlich" von Telnummern und zusätzlichen Emailadressen auf False
* [x] Neuer Default im Wagon Flag "öffentlich" auf false, NUR im DSJ Wagon!

> Ist es möglich, sämtliche Angaben, welche zur Zeit "öffentlich" sind auf "privat" zu wechseln? Wenn wir dieses alle manuell ändern müssen, wäre das mit einem erheblichen Aufwand verbunden.

@jharari Ist machbar. Wollt ihr das wirklich? Die Idee ist dass man speziell sensitive Daten wie Natelnummer auch mal ausblenden kann.

@jharari Dann wollt ihr das neu als Defaulteinstellung auch haben? Das müsste zusätzlich angepasst werden.

@jharari Mir scheint, wenn ihr das anpassen wollt, dann stimmt es auf einer anderen Ebene nicht. Wenn sie von den Personen Kontaktdaten sehen sollen, aber dann die Adresse nicht sehen sollen, was ist denn inhaltlich die Idee davon, dass sie überhaupt diese Personen sehen können?

**Comment by jharari** [comment]
Gerne würden wir sämtliche Angaben auf privat wechseln und dies dann auch als Defaulteinstellung so haben.

**Comment by psunix** [comment]
done

**Comment by psunix** [comment]
auch bei den social accounts standard auf privat sowie die bestehenden Einträge auf privat gesetzt.
