### ISSUE TITLE
Custom Attribute (selbstdefinierte Attribute) (48h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#338]
Ein Admin sollte für die ganze Organisation zusätzliche Attribute für Personen festlegen können.

Typen

* String
* Aufzählung
* Datum 
* Text
* Checkbox
* evtl. Zahl

Schätzung:

* Grundlagen 16h für Bearbeiten usw
* CSV Export (6h)
* JSON (6h)
* Import (12h)
* Log (8h)

**Comment by RolandStuder** [comment]
Hier ist zu beachten, dass mit den konfigurierbaren Spalten auf der Ansicht und dem Export wohl weitere Aufwand dazukommt.

**Comment by RolandStuder** [comment]
Auch fehlen die Aufwände für den Personenfilter und allenfalls Abofilter

**Comment by ThomasEllenberger** [comment]
Umsetzung im Moment nicht geplant.
Ein möglicher Workaround sind die frei definierbaren Tags.
Issue closed.
