### ISSUE TITLE
Rollen und Gruppentypen direkt im Admininterface erstellen anpassen. (80h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#339]
Für die multitenant Version wäre es toll, wenn man selbst Gruppen und Rollentypen erstellen könnte.

Zu beachten
* Es braucht einen Mechanismus um mit Rollen / Gruppen, die nach der Umkonfiguration ungültig werden umzugehen. Entweder muss man beim umstellen sagen können, wie diese transformiert werden, oder man lässt sie oder löscht sie und macht sie irgendwo auffindbar.

**Comment by RolandStuder** [comment]
@kunokunz das wäre die Powerlösung für den Multitenant. Aber ziemlich risikobehaftet.

**Comment by ThomasEllenberger** [comment]
Umsetzung im Moment nicht geplant.
Issue closed.
