### ISSUE TITLE
Filtern von Abos gemäss Kontaktwünschen auf Person (8h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#347]
Voraussetzung #376 

* [ ] Abos auf einem Layer beinhalten Personen mit Ehemalige::Mitglied nur, wenn bei Kontaktdaten #376  die Checkbox angewählt ist.
* [ ] Massgebend ist, wo das Abo angesiedelt ist, wenn Bund mich bezüglich Ehemaligen Rolle auf Schar anschreiben will, erscheine ich nicht, wenn ich die Checkbox abgewählt habe für den Bund.

**Comment by RomanOester** [comment]
> Person ist Ehemalig auf Schar, aber aktiv in einer Arbeitsgruppe auf dem Kanton. Und hat markiert, dass sie keine Kantonalen Versände erhalten will. Was soll dann passieren?

In diesem Fall soll die Person keine Versände erhalten. Die Einstellung der Checkbox hat absolute Priorität.

**Comment by RolandStuder** [comment]
Ja. Wobei es ja zu diesem Fall gar nicht kommen sollte, weil wir ja gesagt haben, man kann sich nur auschliessen kann, wen man nur noch ::Ehemalige:::Mitglied Rollen hat.

**Comment by RomanOester** [comment]
Nicht OK. Ich habe einen Test gemacht, und da konnte ich als "Leitung Kantonsleitung" einen Filter erstellen, wo eine ehemalige Person drin erschien, der KEIN Häkchen bei der kantonalen Ebene hatte.

**Comment by RolandStuder** [comment]
@RomanOester Wir hatten ja besprochen, dass hier dieses Verhalten verwirrlich sein könnte, wann jetzt eine Person erscheint und wann nicht. Deshalb wurde das vorläufig nur bei den Abos umgesetzt, das hatten wir nicht wirklich zu Ende besprochen, sorry.

Variante 1: Aber wir können das noch tun. Die Frage ist wie genau wollen wir das umsetzen. Am einfachsten ist es wenn wir es analog zu den Abos gestalten kann, abhängig davon wo ich den Filter anlege, erhalte ich das entsprechende Resultat. Wenn ich auf dem Kanton dies mache, erscheint die Person ohne Häckchen nicht. Wenn ich aber einen Filter direkt bei der Schar mache, dann erscheint er. Unabhängig von der Rolle, die ich selbst habe.

Variante 2: Die andere Variante wäre, abhängig von der Rolle des Suchenden dies zu tun. Ich finde also die Person nicht, wenn ich eine Rolle auf dem Kanton habe. Was soll aber passieren, wenn ich sowohl im Kanton, wie in der Schar aktiv bin. Dann würde die Person, dieser Schar, wo ich auch dazugehöre, wohl trotzdem auf einer Kantonsliste erscheinen. Ich bin nicht sicher, ob diese zweite Variante wirklich vernünftig umzusetzen ist.

Ist es ok, wenn wir Variante 1 machen? Ein Kalei könnte zwar einen Filter direkt bei der Schar anlegen, und dort die Person finden. Aber ich sehe nicht, wann er das machen sollte, ich fände es unlogisch, wenn wir das verunmöglichen.

**Comment by RomanOester** [comment]
Wie soeben besprochen sollen auch beim Filtern jene Personen nicht berücksichtigt werden, die keine Infos von der entsprechenden Ebene wollen. Dabei muss beachtet werden, auf welcher Ebene die suchende Person ist.
Beispiel: Ein Bulei-Mitglied hat nur Zugriff auf die Ebene "Bund" und darf keine Personen herausfiltern können, die keine Infos der Ebene "Bund" möchten. Ein Kalei-Mitglied hat nur Zugriff auf die Ebene "Kanton" und darf keine Personen herausfiltern können, die keine Infos der Ebene "Kanton" möchten usw. Wenn eine suchende Person auf zwei Ebenen dabei ist, hat sie auch Zugriff auf beide Ebenen.
Sehe ich das richtg so? Das wäre dann meines Erachtens Variante 2, oder?

Das Häkchen muss standardmässig gesetzt sein, heisst also: standardmässig erhalten die Leute Infos bzw. können herausgefiltert werden.

**Comment by RomanOester** [comment]
Bei der Filterfunktion gibt es unterhalb der Datumsauswahl Fehler: Dort ist jeweils "Rolle" falsch geschrieben ("Role" anstatt "Rolle" mit Doppel-L).

**Comment by RolandStuder** [comment]
siehe letzter Kommentar

**Comment by RolandStuder** [comment]
Typo habe ich korrigiert https://github.com/hitobito/hitobito/commit/4b1702591c7340dbf0b4b2565cd847a175fb6a28
