### ISSUE TITLE
View auf Subscriptions von einer Person aus (8h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#348]
Konzept:
* neues Tab auf Person
* Alle Abos aufführen, zu der die Person gehört, die Selbstanmeldung / Abmeldung zulassen.
* Erlaubt Abmeldung
* Subscription auf der ich explizit ausgeschlossen bin, wird ebenfalls angezeigt.

**Comment by MartinGantenbein** [comment]
Erweiterungswunsch zum Konzept:
- Erlaubt Auswahl der E-Mail-Adresse(n) pro Subscription

### Hintergrund
Personen die Mitglied von mehreren Gruppen sind bzw. verschiedene Rollen besetzen verwenden z.T. unterschiedliche E-Mail-Adressen für verschiedene Absender. Versände von Gruppe A sollen an die Adresse X gehen, Versände von Gruppe B aber an Adresse Y. Es ist für diese Personen nicht erwünscht, dass alle Versände in beiden Mailboxen landen.

### Hinweis
Eventuell macht es mehr Sinn, diesen Wunsch als separates Issue zu erfassen und das Requirement isoliert zu analysieren. Die Anforderung muss nicht zwingend auf "Person" gelöst werden, denkbar wäre auch eine Lösung auf Ebene "Abo" (z.B. "ausgeschlossene E-Mail-Adressen" analog "ausgeschlossene Personen").

**Comment by RolandStuder** [comment]
Schliesse dies aufgrund von Inaktivität.
