### ISSUE TITLE
Mehrfachaktionen auf Personenliste ermöglichen (16h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#349]
* Aufwände liegen in der Berechtigung, ich kann auf einer Personenliste gleichzeitig Personen haben, auf welche unterschiedliche Berechtigungen haben
* Pagination, Mehrfachaktion sind nur für Personen auf einer Seite möglich.

Ziel pragmatische Lösung, die das Arbeiten mit mehreren Personen vereinfacht, wir können  es in Kauf nehmen, dass gewisse Aktionen erst beim Ausführen scheitern (und der User darüber informiert wird).

[Prototyp für Mehrfachmutationen.pdf](https://github.com/hitobito/hitobito/files/2099055/Mehrfachmutationen.pdf)

**Comment by RolandStuder** [comment]
Zu beachten:

* Im UI muss konsistent gelöst sein, für welche Aktionen die Auswahl gilt. Wir haben aktuell solche Aktionsarten
  * Person hinzufügen / Importieren -> Unabhängig von der Auswahl
  * Exportieren / Rechnungen erstellen -> Aktionen, die auch bereitstehen, wenn ich niemanden ausgewählt habe, aber die bei einer Auswahl auf die Auswahl beschränkt sein sollte. Z. B. sollte ich immer exportieren können, aber wenn ich fünf Personen ausgewählt habe, will ich nur diese fünf exportieren.
  * Neu: Rollen löschen / Personen verschieben / Neue Rollen zuweisen -> Aktionen, die nur zur Verfügung stehen, wenn ich eine Auswahl getroffen habe.

![image](https://user-images.githubusercontent.com/194364/41361005-4b73d08e-6f2e-11e8-82f2-d75c6c734a11.png)

Frage mich, ob in der Schätzung der Aspekt vom Export das berücksichtig ist?

**Comment by janissbinder** [comment]
#654

**Comment by RolandStuder** [comment]
Implementiert in  1.19
