### ISSUE TITLE
Event-Anmeldung nur für Gruppenmitglieder

### ISSUE THREAD

**Issue by MartinGantenbein** [hitobito/hitobito#353]
Wir wünschen uns die Möglichkeit von Events, zu denen sich nur Gruppenmitglieder (inklusive Mitglieder von Untergruppen) anmelden dürfen. Auf den ersten Blick glaubten wir, dies sei standardmässig so, und man könne via Checkbox "Externe Anmeldungen" auch Mitgliedern von anderen Gruppen (sowie externen Mitgliedern aus weiter unten liegenden Layers) die Anmeldung ermöglichen. Das scheint aber nicht so zu sein, "extern" wird in diesem Kontext offensichtlich anders verstanden als in "externes Mitglied".

Logisch wäre für mich, wenn die Sichtbarkeitsregel `layer_and_below` angewendet würde: Alle Personen, die von der Gruppe des Events her mit Berechtigung `layer_and_below` sichtbar sind, dürfen sich zum Event anmelden, alle anderen nicht. Das heisst, alle mit einer Rolle im gleichen Layer dürfen sich anmelden, alle ausser "externe Mitglieder" mit einer Rolle in darunter liegenden Layers dürfen sich anmelden.

**Comment by RolandStuder** [comment]
@MartinGantenbein Ich verstehe das Anliegen und ich denke für andere Communities könnte das auch interessant sein.

Externe Anmeldungen ist übrigens so zu verstehen, dass sich Personen die in hitobito nicht erfasst sind trotzdem registrieren können. Du erhältst. eine eine URL, die du verschicken kannst, bei der sich eine beliebige Person anmelden kann. Es ist aktuell noch nicht sehr elegant, aber ein Release mit Verbesserungen diesbezüglich ist auf Herbst geplant.

**Comment by RolandStuder** [comment]
Nach wie vor ein valides Anliegen, aber ich schliesse das Issue bis das Thema wieder aufkommt.
