### ISSUE TITLE
Failure Resistant DB Connection Pool

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito#355]
Durch Wartungsarbeiten im OpenShift werden (Mysql) Container von einem Cluster in einen anderen verschoben. Dabei produzieren die Connections auf den alten Container folgende Fehler: "Mysql2::Error: Can't connect to MySQL server on 'mysql' (113)" / "Mysql2::Error: closed MySQL connection"

In der Regel wird dafür der Connection Pool so konfiguriert, dass er "tote" Datenbankverbindungen
erkennt und erneuert. Bevor also ein Fehler weitergereicht wird, sollte z.B. der gleiche DB Query mit einer neuen Verbindung ausgeführt werden.

**Comment by RolandStuder** [comment]
@psunix Ist dieses Issue mit den Helath Checks abgedeckt, oder ist das noch etwas anderes?

**Comment by RolandStuder** [comment]
Schliesse dies aufgrund von Inaktivität.
