### ISSUE TITLE
Impersonierung eines Benutzers für Support (12h) (Core)

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito#356]
Die Supporteinheiten in den Kantonen und auf Bundesebene stehen oftmals vor dem Problem, dass sie Supportanfragen nicht zufriedenstellend bearbeiten können, weil sie ganz andere Berechtigungen haben als ihre Benutzer. So sehen sie die Benutzer / Lager o.ä. gar nicht. 

Eine Lösung über Co-Browsing ist schwierig umzusetzen, da die Supportanfragen häufig asynchron bearbeitet werden (Benutzer arbeitet abends mit Hitobito, Support tagsüber)

Wünschenswert ist, dass Adressverwalter temporär die Sicht von Personen innerhalb ihrer Organisation einnehmen können und dann mit den genau gleichen Rechten/Ansichten arbeiten, wie der impersonierte Benutzer. 

Zur Absicherung sind verschiedene Massnahmen zu prüfen (ggf. weitere Ideen)
- Änderungen etc. weiterhin mit dem ursprünglichen Benutzer kennzeichnen
- verstärktes, transparentes Logging bei impersonierten Zugriffen
- Information an den impersonierten Benutzer (explizite Freigabe halten wir für übertrieben)

# Akzeptanzkriterien

* [x] Neue Berechtigungsart/Permission :account_takeover oder :take_over_account
* [x] Impersonierung. Ich kann auf der Person einen Button klicken "Account übernehmen", ab dann bin ich als diese Person eingeloggt.
* [x] Zum Zeitpunkt der Accountübernahme wird eine Email-Notification ausgelöst, dass Person XXX den Account übernommen hat.
* [x] Ein Logeintrag wird angelegt, dass die Person XXX den Account übernommen hat.

Wenn Zeit bleibt:

* [x] Wenn ich einen Account übernommen habe, wird mir oben am Bildschirmrand angezeigt, dass ich aktuell einen Account übernommen habe
* [x] Ich kann mit einem Klick wieder auf meinen eigenen Account wechseln.
* [ ] Logeinträge von geloggt, als hätte der urpsprüngliche Account die Änderung gemacht habe (Roland übernimmt Thomas, Logeintrag zeigt allfällige Änderungen mit "geändert von Roland an".

![image](https://user-images.githubusercontent.com/194364/33853890-e39d6aaa-debf-11e7-983e-797aaaf8d2ad.png)

**Comment by RolandStuder** [comment]
* Impersonierung
* Information an Account Inhaber
* Eine bestimmte Liste von Rollen (hardcoded) die Berechtigung geben
* Ein Logeintrag, dass Account von XXX übernommen wurde.

Grobidee `current_user` umbiegen auf neuen, noch unklar, ob man einfach wieder zurück kommt.

Impersonierung: 4h
Zusätzliches Logging: 2-4h

**Comment by janissbinder** [comment]
Die Permissions müssen noch in den Wagons ergänzt werden. Im Generic wurden sie bereits vergeben, da klar war wer diese Berechtigung erhält.

**Comment by RolandStuder** [comment]
Bitte letzten Punkt mit dem Logging auch noch machen @amaierhofer

**Comment by amaierhofer** [comment]
Prüfen ob der current_user den papertrail verwendet angepasst werden kann. Idealfall (a hat b gemacht als "c"), sonst "a hat b gemacht als support"

**Comment by RolandStuder** [comment]
@amaierhofer Failed auf Integration mit 

> 504 Gateway Time-out The server didn't respond in time.

Lokal funktioniert es wunderbar.

**Comment by RolandStuder** [comment]
Das Übernehmen eines Accounts failed, wenn bei der Person, welche übernommen wird, keine E-Mailadresse hinterlegt ist. Am besten wäre es sowieso, man würde dieses Mail nur verschicken, wenn e-Mail vorhanden ist und sich die Person bereits einmal eingeloggt hat (wie bei allfäligem add_request).

**Comment by Michael-Schaer** [comment]
Die Übernahme funktioniert gut. Das Feature ist echt ein Meilenstein für den Support!

Abgenommen, vorausgesetzt das Feature kann auf Produktion per Rolle vergeben werden.
