### ISSUE TITLE
Zwei Faktor Authentifizierung 2FA (1d)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#361]
hitobito erlaubt gewissen Personen umfassenden Zugriff. Eine Zweifaktor-Authentifizierung würde gerade für solche Personen Sinn machen.

Am einfachsten wäre wohl eine Lösung mit Code auf Mobile schicken.

Die Anfrage kommt aus der SaaS Community: https://hitobito.discoursehosting.net/t/two-factor-authentication/21

**Comment by olibrian** [comment]
Aus dem Ticket #859 von der PBS gemeldet
Zwei Ideen zu 2FA:

    Gibt es die Möglichkeit, 2FA für Rollen mit vielen Rechten zu erzwingen?
    Ist auch eine Anbindung an Authenticator-Apps geplant (Microsoft, Google, FreeOTP)?

**Comment by mtnstar** [comment]
2FA wurde mit TOTP umgesetzt und ist jetzt im core intergiert.
