### ISSUE TITLE
Aboexport Performance optimieren oder als Backgroundjob lösen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#362]
Aboexporte sind aktuell sehr langsam, z. B. Sarasani Export dauert bis zu einer Stunde. Auf Openshift haben wir nun nicht mehr die Möglichkeit das Time Out Limit so hoch zu halten.

Wir brauchen damit eine neue Lösung für die Aboexporte. 

## Vorgehen / Lösungsmöglichkeiten:

* Analyse der Performance (Was macht den Aboexport so langsam? Ist es das fehlende Memory? Der SQL Query? usw....)

Nach sorgfältiger Analyse gibt es potentiell zwei Wege, wobei sich diese nicht ausschliessen. 

* Ausreichende Performanceoptimierung, so dass wir auch bei grossen Abos unter der Time Out Limite bleiben.
* Verschieben von grösseren Aboexporten in einen Backgroundprozess, so dass der Benutzer ein Email erhält,mit attachtem Export oder Link auf Exportfile.

Weitere Details im Issue #23

**Comment by RolandStuder** [comment]
Gut zu wissen ist vielleicht auch noch, dass wir gewisse Exports eben erst hingekriegt hatte, nachdem damals auf dem hoodie mehr RAM bereit gestellt hat.

**Comment by kronn** [comment]
Ich habe leider die Commits nicht richtig verlinkt. Daher hier der Compare-View: https://github.com/hitobito/hitobito/compare/d2237ec...89a285e

**Comment by kronn** [comment]
encore une fois… komplette Commit-Range mit Kompression größerer Dateien: https://github.com/hitobito/hitobito/compare/d2237ec...6924204

**Comment by kronn** [comment]
Für Integrationstests ist der Code auf https://pbs.puzzle.ch deployed

**Comment by RolandStuder** [comment]
Danke, wird der Export nun in jedem Fall im Hintergrund ausgeführt? Oder versucht der Export abzuschätzen, ob er aufwändig ist oder nicht?

**Comment by kronn** [comment]
Der Export wird erstmal in jedem Fall im Hintergrund ausgeführt. Die Kompression in ein ZIP-File wird erst ab 512kb Exportgrösse vorgenommen. Meiner Ansicht nach ist das bereits eine Schwelle, aber der es für die Übertragung sinnvoll ist, aber das kann man gerne noch anpassen.

Ich kann schauen, ob eine Grössenschätzung im Vorfeld möglich ist, erstmal war es so schneller umgesetzt.

**Comment by amaierhofer** [comment]
Exports werden mittlerweile als im Hintergrund gemacht und per Email verschickt
