### ISSUE TITLE
Konsolidierte Kostenrechnung stimmt nicht

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#364]
Bei Insieme Reporting/Controlling

* Einzelne Kostenrechnungen Regionalverbände sind korrekt
* In der konsolidierten Kostenrechnung über alle Verbände hinweg sind die Zahlen aber höher, als die Summe der einzelnen bei Block und Jahreskursen.
* Die Kontrollspalte zeigt nicht Nullwerte an

Siehe Daten für das Jahr Reporting für 2016.

Export konsolidierte Kostenrechnung zeigt Abweichungen. Bitte analysieiren. 

Details mit Beispielfile findet ihr hier: https://ticket.puzzle.ch/projects/insi-ins-akr/work_packages/25777/activity

**Comment by psunix** [comment]
fix implementiert. kunde muss nun testen und bestätigen ob ok
