### ISSUE TITLE
Reporting: Klientenstatistik / Kursstatstik sind inkosistent

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#365]
Die Statistiken stimmen nicht überein, irgendetwas wird da unterschiedlich gerechnet. Siehe z. B.

https://desk.insieme.ch/de/groups/1/controlling?year=2016

* KlientInnen Statistik Blockkurse zeigt 5974  (dies sind nur Behinderte)
* Kursstatistik zeigt Zahl für Blockkurse 5929 + 9 ergibt 5938

Diese Zahlen sollten übereinstimmen.

**Comment by psunix** [comment]
implemented und auf int deployed.

warte auf feedback kunde
