### ISSUE TITLE
Neuer Gruppentyp Ehemalige

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#366]
Neuer Gruppentyp: 

* Name: Ehemalige
* Zugelassen unter jedem Layer, der bei der Jubla existiert
* Gruppentyp Ehemalige ist auch unter Gruppentyp Ehemalige erlaubt

## Rollen

* **Leitung**
   * Lesen und Schreiben auf dieser Gruppe. :group_and_below_full
    * Lesen der Kontaktdaten aller anderen Personen mit Kontaktdatenberechtigung., :contact_data

* **Adressverwaltung**
  * Lesen und Schreiben auf der Gruppe. :group_and_below_full
  * Erstellen von Anlässen und Abos auf der Gruppe.

* **Kassier**
  * Lesen auf der Gruppe. :group_and_below_read
  * Lesen der Kontaktdaten aller anderen Personen mit Kontaktdatenberechtigung. :contact_data

* **Mitglied**
  * Lesen auf der Gruppe. :group_read

* **Extern** (entspricht der bestehenden Externen Rolle)
  * Die Rolle Extern kann nur öffentliche Daten (Gruppen, Anlässe und Abos; keine anderen Personen) sehen.
  * Diese Rolle ist nur von Personen in dieser Ebene sichtbar, nicht von Personen aus darüber liegenden Ebenen.

* **Versandadresse Ehemalige**

  * Die Rolle Versandadresse kann nur öffentliche Daten (Gruppen, Anlässe und Abos; keine anderen Personen) sehen.

## Akzeptanzkriterien:

* [x] Gruppentyp Ehemalige existiert, mit den obenstehenden Rollentypen
* [x] Unter einer Gruppe "Ehemalige" ist Gruppentyp "Ehemalige" möglich
* [x] Es können Untergruppen "Ehemalige" angelegt werden

## Bemerkungen

* löst Issue #312 ab

**Comment by janissbinder** [comment]
https://github.com/hitobito/hitobito_jubla/commit/4b5566b1fc77bebf7ce8f1e27f7b84fcb8df0204
