### ISSUE TITLE
Gruppentyp Ehemalige wird für alle Ebenen automatisch erstellt.

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#368]
In jeder Ebene mit Typ Bund, Kanton, Region oder Schar soll eine neue Gruppe mit Typ Ehemalige mit dem Namen „Ehemalige“ erstellt werden.

# Akzeptanzkriterien

* [x] Zu jeder Ebene existiert eine Gruppe vom Typ `Ehemalige` mit dem Namen `Ehemalige`
* [x] Beim Erstellen eine neuen Ebene wird die Gruppe `Ehemalige` automatisch erstellt.

# Bemerkungen

Es gibt bereits einen Mechanismus dafür self.default_children auf der ::Gruppe

**Comment by janissbinder** [comment]
https://github.com/hitobito/hitobito_jubla/commit/d4a0114893e2fe6b60ef71db003f0bf9113dc8d8
