### ISSUE TITLE
Die letzte Gruppe Ehemalige kann nicht gelöscht werden

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#369]
# Akzeptanzkriterien

* [ ] Ist eine Gruppe auf einem Layer die letzte Gruppe vom Typ `Ehemalige`, so kann sie nicht gelöscht werden.
* [x] Layer müssen trotzdem gelöscht werden können, wenn unter dem Layer nur noch Ehemaligengruppen bestehen.
* [ ] Die Fehlermeldung sagt: "Gruppe `Gruppenname` konnte nicht gelöscht werden. Es braucht mindestens eine Ehemaligengruppe.

**Comment by janissbinder** [comment]
Da dieses Feature so umgesetzt wurde, dass die Benutzer gar nicht in der Lage sind die Letzte Ehemalige Gruppe zu löschen, habe ich die Fehlermeldung nicht eingebaut.
