### ISSUE TITLE
Verschieben von Gruppen Rollen (16h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#37]
Vorraussetzung #349 , #570, #344 

Verschieben von mehreren Mitgliedern ermöglichen, dies ist nicht weitere als eine Kombination aus neue Rolle zuweisen #570 und bestehende Rollen löschen #344

- Mehrfachauswahl
- Bei unterschiedlichem Zielgruppentyp -> Matching machen Rollen auf die neue Rollen (manuelle Zuweisung)

siehe auch im Prototyp https://balsamiq.cloud/shpminv/p3amzl0

## 1
![image](https://user-images.githubusercontent.com/194364/41364924-4bec748a-6f38-11e8-915f-d22d42745218.png)
## 2
![image](https://user-images.githubusercontent.com/194364/41364936-5587ce68-6f38-11e8-989f-4686b55bbdc9.png)
## 3
![image](https://user-images.githubusercontent.com/194364/41364944-5e13ec6a-6f38-11e8-84a8-4fb59aae81a2.png)

**Comment by RolandStuder** [comment]
Idee: Man kann beliebig viele auswählen, wenn nicht eindeutig ist, welche Rolle entfernt werden muss, so wird die Person am anderen Ort hinzugefügt, aber die Rolle/Rollen werden nicht entfernt.

Eleganter wäre ein zusätzlicher Dialog, wo ich auswählen kann, welche Rolle entfernt werden soll.

**Comment by RolandStuder** [comment]
Es kann auch sein, dass man auf gewisse Rollen berechtigt ist auf andere nicht. (wenn gefilterte Liste)

**Comment by RolandStuder** [comment]
siehe https://hitobito.discoursehosting.net/t/massenmanipulationen-auf-personenlisten/33/2

**Comment by Michael-Schaer** [comment]
Im Testsystem kann ich die Funktion "Rolle verschieben" nicht testen. Beim klick auf den Button geschieht nichts. Die anderen beiden Funktionen "Hinzufügen" und "Löschen" gehen beide ohne Probleme.

**Comment by RolandStuder** [comment]
Danke für die Rückmeldung, das Problem liegt bei der Erweiterung um die Datumsfelder. Ich habe einen Fix, aber vielleicht braucht es noch Tests oder eine elegantere Lösung dazu. Siehe https://github.com/hitobito/hitobito_pbs/pull/86

**Comment by Michael-Schaer** [comment]
Wir haben auf dem Testsystem ein Problem mit der zusätzlichen Bezeichnung dr Rolle:

- Person auswählen
- Rollen verschieben
- Beliebige Rolle auswählen
- Bezeichnung «XY» eingeben
- Abschliessen
-> Die neue Rolle hat keine Bezeichnung «XY» 

Getestet auf Ebene Abteilung:
https://pbs.puzzle.ch/de/groups/530/people

**Comment by RolandStuder** [comment]
Ist umgesetzt 😄
