### ISSUE TITLE
Exportformat vCard

### ISSUE THREAD

**Issue by MartinGantenbein** [hitobito/hitobito#374]
Als zusätzliches Exportformat vCard (*.vcf) anbieten, damit die Mitglieder einer Gruppe / eines Abos einfach in verschiedene Kontakt-Applikationen importiert werden können.

**Comment by RolandStuder** [comment]
Die wäre sicher eine willkommene Ergänzung

**Comment by RolandStuder** [comment]
Toll, vielen Dank für deine tollen Contributions!
