### ISSUE TITLE
Auswahl welche Ebenen mich kontaktieren dürfen (4h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#376]
Bei allen ehemaligen Personen erscheint nach "Nationalität gemäss J+S" ein neuer Abschnitt mit dem Titel "Kontaktfreigaben". Dort gibt es vier Zeilen, wo die Person im Bearbeitungsmodus Häkchen setzen bzw. entfernen kann. Folgender Text soll im Bearbeitungsmodus sichtbar sein:

# Kontaktfreigaben für Ehemaligenversände

Mit dem Setzen eines Häkchens erlaubst du folgenden Ebenen, dich zu kontaktieren und dir Informationen zu senden:

- nationale Ebene (Verbandsleitung, Bundesleitung, Fach- und Arbeitsgruppen)
- kantonale Ebene (Kantonsleitung, Fach- und Arbeitsgruppen)
- regionale Ebene (Regionalleitung, Fach- und Arbeitsgruppen)
- lokale Ebene (Schar)

---

# Akzeptanzkriterien

* [x] Der Einstellungsbereich Ehemaligenversände erscheint nur, wenn ich **nur** Rollen vom Typ Ehemalig::Mitglied inne habe.

* [x] Habe ich auf anderen Ebenen noch anderer Rollen so, wird der Bereich  nicht angezeigt.
* [x] Das Filtern aufgrund dieser Angaben wird in einem anderen Issues abgehandelt.

Zu korrigieren:

* [x] Um lokale Ebene Schar ergänzen

**Comment by RomanOester** [comment]
Nicht OK: Bei der Auswahl fehlt die Zeile "lokale Ebene (Schar)".

**Comment by RolandStuder** [comment]
Zu korrigieren:

* [ ] Um lokale Ebene Schar ergänzen

**Comment by RomanOester** [comment]
Hier ist mir noch aufgefallen, dass dies nur im Bearbeitungsmodus angezeigt wird und nicht, wenn man auf dem Profil ist. Titel wäre "Kontaktfreigabe".

**Comment by RolandStuder** [comment]
@RomanOester Haben wir korrigiert. Bitte anschauen und freigeben.

**Comment by RomanOester** [comment]
Ist jetzt OK.
