### ISSUE TITLE
Automatisieren von Int Deployment

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#378]
Aktuell muss deployment auf Integration manuell angestossen werden, wäre super, wenn man das automatisiert hätte, wie früher.

**Comment by kronn** [comment]
@psunix  auch bei einem frischen checkout mit `git clone git@github.com:hitobito/ose_composition_jubla.git --recursive --branch devel` wird nicht der branch mit aktuellen Commits geholt, sondern so, wie es eingecheckt ist. Dies ist schon beim init-commit der Fall.

Man kann die Submodules entsprechend der Konfiguration aktualisieren, indem man `git submodule update --remote` ausführt. Dann wird im `devel`-Branch auch korrekt der `master`-branch der jeweiligen Submodule geholt. Die Working-Copy hat dann changes, die man als den zu deployenden Stand committen kann. 

Ich würde dies im Int-Deployment build machen, bevor der generische OpenShift-Job gestartet wird. Ich hätte hierzu gerne deinen Input.

**Comment by kronn** [comment]
Das Deployment-Skript wurde in https://github.com/hitobito/hitobito/commit/3d6268cb7326e47aaadd53fb3748c208e6a6e2c3 angepasst. Damit sollte es möglich sein, ohne manuelle updates am compositioning-Repo eine aktuelle Version in die Integration zu deployen.
