### ISSUE TITLE
Rechnungen Konfiguration bei Gruppenfusion behandeln

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito#381]
Kann nicht automatisch übernommen werden, wir müssen festlegen wie wir damit umgehen wollen.

- Was passiert mit der Rechnungsnummer? 
- Welche Kontaktdaten sollen übernommen werden?

**Comment by RolandStuder** [comment]
Ich frage mich, ob wir nicht sowieso die Rechnungsnummern unique über die DB halten sollten.

Sonst würde ich sagen, dass Rechnungen und Artikel alle in der neuen Gruppe verfügbar sind.

**Comment by amaierhofer** [comment]
@RolandStuder Wie genau wollen wir hier vorgehen? Aktuell gehen die bei der Gruppe hinterlegten informationen beim Fusionieren verloren.

**Comment by RolandStuder** [comment]
Hm. Gibt es einen Check, ob überhaupt etwas angegeben ist als Absender? Wenn ja, wäre es am einfachsten, einfach die Daten rauszulöschen und leer zu lassen, so dass der Benutzer gezwungen wird neu das anzugeben. Eine Flash Message auf der Liste mit Hinweis, dass Einstellungen vorgenommen werden müssten wäre gut.

**Comment by RolandStuder** [comment]
Ich werde dies nochmals testen. Ist aber abgeschlossen.
