### ISSUE TITLE
Produktionsdeploy Stable (4h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#383]
Issue #362 und #323 fixes sollen auf stable komme und deployed werden

* neue Version erstellen
* dann 6x mal deployen

**Comment by RolandStuder** [comment]
Neue Übersetzungen sind hinterlegt.

**Comment by kronn** [comment]
Deployment von DSJ, Cevi, Insieme, Jubla und ProNatura lief gestern abend. PBS scheint in der falschen Version deployed zu sein. Ich schaue mir das an.

**Comment by kronn** [comment]
PBS ist jetzt auch deployed
