### ISSUE TITLE
Mailgun Mail-Versand (12h)

### ISSUE THREAD

**Issue by psunix** [hitobito/hitobito#386]
Der Mailversand wird heute über SMTP gemacht.
Neu soll das Senden von Mails über das API von Mailgun möglich sein.

http://mailgun.com

- [ ] Einbau von: https://rubygems.org/gems/mailgun_rails
- [ ] Konfiguration von entweder SMTP oder Mailgun für den Mailversand (ActionMailer)
- [ ] Konfiguration der Mailgun Credentials wie API Key, API URL (über ENV vars)
- [ ] Prüfen ob so auch Attachments versendet werden können oder ob es dort ggf. noch Anpassungen braucht. (Attachments werden z.B. bei der Event-Anmeldung mit versendet)
- [ ] Openshift Template mit den neuen ENV Vars ergänzen
- [ ] Für eine Umgebung neuen Account bei Mailgun einrichten, Kreditkarte muss hinterlegt werden um an beliebige Empfänger senden zu können
- [ ] Mailversand Testen auf einem auf Openshift deployten System, evtl. auch nur lokal

**Comment by MartinGantenbein** [comment]
Wir (https://github.com/MartinGantenbein/hitobito) haben in unserer Hitobito-Instanz bereits Mailgun in Gebrauch (nur für ausgehende Mails). Wir verwenden die SMTP-Schnittstelle von Mailgun, dafür ist kein Gem (mailgun_rails) notwendig und keine Codeanpassung. Es muss nur die Konfiguration angepasst werden:
`RAILS_MAIL_DELIVERY_CONFIG=address: smtp.mailgun.org, port: 587, user_name: $MAILGUN_USER_NAME, password: $MAILGUN_PASSWORD, domain: $MAILGUN_DOMAIN, authentication: plain, enable_starttls_auto => true`

Nach einigen Problemen sind wir inzwischen ganz zufrieden damit, leider kann sich das aber rasch wieder ändern (unabhängig davon, ob man Mailgun via SMTP oder via REST verwendet):
Bei der Standard-Variante wird man irgend einer Mailgun-IP zugewiesen, wenn man Pech hat wird diese IP auch von einem Spam-Versand verwendet und die IP landet auf den einschlägigen Blacklists. In der Folge werden unsere E-Mails dann durch gewisse Provider nicht mehr akzeptiert und zurückgewiesen. Dies erfährt der Absender (im Fall von Abos) aber nicht (der Empfänger sowieso nicht), ich als Hitobito-Betreiber muss regelmässig auf meinem Mailgun-Account prüfen, ob Versände fehlgeschlagen sind und entsprechend reagieren (Meldung an Mailgun und Request für neue IP --> Support funktioniert einwandfrei und rasch). Das Problem ist, dass auch eine saubere IP plötzlich auf einer Blacklist landen kann, wenn man das Pech hat, dass Mailgun einem unseriösen Kunden die gleiche IP zuweist...

**Comment by psunix** [comment]
@MartinGantenbein vielen Dank für dein Feedback mit First-Hand-Experience, das ist natürlich sehr wertvoll. 
Ein weiterer Nachteil von Sendgrid und Mailgun ist das die Anzahl der Versendeten Mails entscheidet wieviel das schlussendlich verrechnet wird. Bei Mailgun sind zwar 10k gratis pro Monat, aber wieviele Mails werden effektiv versendet? Da wir heute den Mailversand nicht wirklich loggen ist es schwierig ab zu schätzen wieviele das wirklich sind.

**Comment by RolandStuder** [comment]
@psunix Der Preis ist egal, wenn wir dafür eine stabile Lösung mit gutem Logging haben. Ich denke, am besten machen wir mal zuerst ausgehende Mails testweise mit einem unserer Kunden, aber ohne auf die API umzustellen.

**Comment by RolandStuder** [comment]
@KunoKunz Vielleicht sollte man eben Mails doch von externem Server versenden lassen, dort hätte man wohl besserer Reporting und vielleicht auch weniger Spamanfälligkeit. Man müsste nur Mailkonfiguration anpassen und schauen was der Service an Monitoring / Logging bietet

**Comment by psunix** [comment]
zurzeit fahren wir nicht schlecht mit dem SMTP server von appuio. Schliesse dieses Issue darum mal.
