### ISSUE TITLE
Mailgun Empfang Mails Mailinglisten ()

### ISSUE THREAD

**Issue by psunix** [hitobito/hitobito#387]
Für eingehende Mails welche auf Mailinglisten gesendet werden soll neu ein API-Endpoint welcher vom Mailgun Service getriggert wird zur Verfügung gestellt werden.

http://mg-documentation.readthedocs.io/en/latest/user_manual.html#routes

- [ ] POST API Endpoint /mail_retreiver + controller erstellen
- [ ] Auth Token für Authentifizierung als ENV Variable
- [ ] Über Konfig soll es möglich sein entweder den Legacy POP3 Job oder per Mailgun mails zu empfangen
- [ ]

**Comment by psunix** [comment]
etwas unschön an Mailgun ist halt einfach die Tatsache das es properitär ist.
https://github.com/atech/postal macht auf den ersten Blick einen sehr guten Eindruck und ist auch Opensource. Müsste man halt einfach selber hosten.
Dies einfach als weiteren Input bevor man diese Story hier umsetzen würde.

**Comment by RolandStuder** [comment]
Mails abholen ist nicht mehr so ein Thema, darum schliesse ich das.
