### ISSUE TITLE
BSV Export alle Kurse statt nur abgeschlossene

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#389]
![bildschirmfoto 2017-08-30 um 15 49 17](https://user-images.githubusercontent.com/194364/30748791-9f6378f4-9fb1-11e7-90c5-00786d02a198.png)

Beim Export der BSV Export Liste, sollten nur Kurse mit dem Status "Abgeschlossen" `:closed` exportiert werden. Aktuell werden aber auf Produktion und Integration alle Kurse exportiert.

Die entsprechende Funktion ist hier:

https://github.com/hitobito/hitobito_youth/blob/01b3fa0bde5452f3b6f6f0c0243c04bc3c5fedbd/app/controllers/youth/event/lists_controller.rb#L49

Lokal auf dem Master-Branch hat es für mich korrekt funktioniert. Ich vermute fast, da ist beim Kurswesen Zeugs irgendwie untergegeangen. Meine Vermutung ist, dass wenn wir die neue Version deployen, dass alles wieder in Ordnung ist.

Also am besten die neuste Version deployen und dies überprüfen.

**Comment by RolandStuder** [comment]
Info an Benni Schüssler und Lucia, wenn abgeschlossen

**Comment by RolandStuder** [comment]
Ist übrigens auf dem Youth-Wagon

**Comment by psunix** [comment]
zuerst auf prod kurz testen ob issue noch aktuell. evtl. werden seit dem neuen release schon nur die abgeschlossenen kurse exportiert.

**Comment by RolandStuder** [comment]
Ist deployed. Thx
