### ISSUE TITLE
Berechtigung für Rechnungsstellung 2h

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#39]
SOLL:
- Berechtigung :finance kann neu Rollen zugeteilt werden.
- Die Berechtigung erlaubt alle Aktionen bezüglich Rechnungsstellungen, es gibt keine Unterscheidung zwischen Lese- und Schreibrechten.
- Die Berechtigung bezieht sich nur auf den aktuellen Layer.

**Comment by amaierhofer** [comment]
@RolandStuder  Kannst du bitte eine Liste von Rollen zusammenstellen, die die `finance` Permission bekommen sollen? Werden diese Rollen alle direkt am Layer hängen oder an Untergruppen? Wie soll die Permission `admin` behandelt werden, wenn dies nicht am Layer sondern in einer Untergruppe z.b. für die Gruppe `Bundesleitung` vergeben ist?

**Comment by RolandStuder** [comment]
- Liste kommt nocht
- Rollen können auch Untergruppen
- Persmission :admin ist irrelevant
