### ISSUE TITLE
Bestand und Statistik in der Region anzeigen (10h) (PBS Wagon)

### ISSUE THREAD

**Issue by js4gh** [hitobito/hitobito#392]
- Gleich wie in der Abteilung sollen in der Region die Tabs Bestand die Statistik angezeigt werden. 
- Bestand, es werden nur "Aktueller Bestand" und "Jahrgangsübersicht" aller Personen in der Region und der darunterliegenden Regionen/Abteilungen angezeigt, auf die Anzeige aller Gruppen (inkl. Personen) wird verzichtet.
- Statistik, Ansicht analog der beim Kanton (Liste aller Abteilungen in der Region + Total)

**Comment by fossil12** [comment]
Die Jubla hat den selben Wunsch. Unser Ticket dazu: http://feedback.jubla.ch/issues/101

**Comment by RolandStuder** [comment]
Bitte zwei Schätzungen machen. Wie gross ist der Aufwand dies für eine Organisation zu machen. Wieviel ist der Aufwand, dies auch für eine zweite Organisation zu machen. (Die Bestandesmeldung, wenn auch ähnlich ist im Wagon drin, weil das viel mit den verschiedenen Rollen zu tun hat).

**Comment by RolandStuder** [comment]
* Tab Statistik beim Region anzeigen (4h)
* Tab Bestand auf Region, Kanton, Dachverband (6h)

Für 2. Wagon ca. 50% des Aufwandes

**Comment by RolandStuder** [comment]
@adriananderegg Bitte abnehmen.

**Comment by js4gh** [comment]
Von meiner Seite sage ich abgenommen.

Es stellt sich mir einzig noch die Frage was nun bei einer Bestandsmeldung passiert, ob diese wie bisher nur bei den Abteilungen gefordert ist, was aus meiner Sicht so sein sollte?

**Comment by RolandStuder** [comment]
@js4gh Das hat keinen Zusammenhang, es ist nur eine zusätzliche Ansicht auf Region. Auf der Testdb ist eine Bestandesmeldung ausstehend, also kannst du sehen, dass alles in Ordnung ist.

**Comment by adriananderegg** [comment]
@RolandStuder abgenommen
