### ISSUE TITLE
Lageransicht verbessern (8h)

### ISSUE THREAD

**Issue by js4gh** [hitobito/hitobito#393]
Diese Issues verfolgt zwei Ziele
•	In der Abteilung werden immer alle Lager der Abteilung (Ebene) Angezeigt 
•	Region, Kantonalverband und Bundesebene haben eine bessere Übersicht über die stattfinden Lager.

Bestehende Lageransicht auf allen Stufen (PBS, KV, Region usw.) wie folgt ergänzen:
•	Zusätzliche Anzeige der folgenden Felder (inkl. Sortiermöglichkeit)
o	«Lagerstatus» (Auswahlfeld aus Lager erstellen, Allgemein)
o	«Hauptebene/Gruppe» (Haupterben und Gruppe in welcher das Lager erstellt wurde) 
o	«Kanton / Land» (Auswahlfeld aus Lager erstellen, Allgemein)

Berechtigung, Anzeige und Export anpassen:
•	Es werden immer alle Lager der Gruppe/Ebene und der Gruppen/Ebenen darunter angezeigt.
•	Beim Kantonalverband werden zusätzlich alle Lager angezeigt die im Entsprechenden Kanton stattfinden. («Kanton / Land» (Auswahlfeld aus Lager erstellen, Allgemein))

# Akzeptanzkriterien

Auch wenn sich das Issue eigentlich auf Lager bezieht, so soll dies für jeden Typ von Anlassliste gelten, sofern dies nicht speziellen Aufwand bedeutet.

## Listenansicht erweitern

* [x] Listenansicht zeigt `Lagerstatus`
* [x] Listenansicht zeigt `Hauptebene/Gruppe`
* [x] Listenansicht zeigt `Kanton/Land`

## Scope der Anzeige []

* [x] Auf einem Layer gibt es neu eine Auswahl für den Scope der Eventliste / Lagerliste / Kurslite
* [x] Ich habe die Wahl zwischen: `Alle` und `Nur [layername]` z. B. ("Nur Kanton").
* [x] Ist Scope `Alle` gewählt, so erscheinen alle Events von Untergruppen und von Unterlayern
* [x] Ist Scope `Nur [layername]`gewählt so erscheinen alle Events von Untergruppen (aber nicht Unterlayern
* [x] Auf Untergruppen eines Layer erscheint die Scope-Auswahl nicht, aber es werden auch Events von Untergruppen angezeigt

## Spezialscope durchgeführt in Kanton XX

* [x] Auf Gruppen vom type `Kanton`erscheint auf der Lagerliste ein zusätzlicher Scope "Durgeführt in [Kantonkürzel]"
* [x] Wähle ich diesen Scope so erscheinen alle Events, welche als Durchführungskanton eben [Kantonskürzel haben] (eine ähnliche View gibt es bereits für Kantonsverantwortliche: https://pbs.puzzle.ch/de/list_camps_in_canton?canton=be (allerdings machen wir sie hier ohne Einschränkung nach Durchführungsdatum oder Status oder Einreichung)

## Export:

* [x] Export exportiert immer die Liste des gewählten Scopes

## Sortierfuntion

* [x] Liste kann nach folgenden Spalten sortiert werden: Name, Datum, Status, Gruppen, Kanton/Land
  
## Bugs:

* [x] Wähle ich Option von Scope `Nur [layername]` so erscheinen nur Events von direkten Kinder des Layers nicht aber von Kindeskindern, siehe: https://pbs.puzzle.ch/de/groups/506/events/camp?returning=true

**Comment by RolandStuder** [comment]
An diesen Ansichten basteln wir immer wieder herum. Und jeder braucht ein bisschen etwas anderes. Wir fänden es insgesamt sinnvoller, wenn man allgemein Anlässe / Lager / Kurse selbst filtern könnte und sich so die geeignete Ansicht zusammenstellen könnte.

**Comment by RolandStuder** [comment]
Wie seht ihr das? Gerade bezüglich Kurse sehen das aber einige z. B. Jubla als eher problematisch an, weil sie nicht wollen, dass sich Personen einfach so bei fremden Kantonen anmelden.

**Comment by adriananderegg** [comment]
Eine dynamische Ansicht wäre natürlich auch sehr schön. 

Es sollen keine zusätzlichen Kurse sichtbar sein. Es sollen diejenigen Lager aggregiert auf Kantonsebene angezeigt werden, welche bei einer Navigation auf untere Ebenen auch schon sichtbar sein.

**Comment by RolandStuder** [comment]
# Schätzung

Bestehende Lageransicht auf allen Stufen (PBS, KV, Region usw.) wie folgt ergänzen: (2h)
•	Zusätzliche Anzeige der folgenden Felder (inkl. Sortiermöglichkeit)
o	«Lagerstatus» (Auswahlfeld aus Lager erstellen, Allgemein)
o	«Hauptebene/Gruppe» (Haupterben und Gruppe in welcher das Lager erstellt wurde)
o	«Kanton / Land» (Auswahlfeld aus Lager erstellen, Allgemein)

Berechtigung, Anzeige und Export anpassen: 
•	Es werden immer alle Lager der Gruppe/Ebene und der Gruppen/Ebenen darunter angezeigt. (2h)
•	Beim Kantonalverband werden zusätzlich alle Lager angezeigt die im Entsprechenden Kanton stattfinden. («Kanton / Land» (Auswahlfeld aus Lager erstellen, Allgemein)) (2h)
* Pagination (2h)

**Comment by RolandStuder** [comment]
Es gilt einfach zu unterscheiden, was man sich anssieht:
* Lager: Aktuelle Ebene (z. B. Lager auf Kanton direkt oder Untergruppen vom Kanton)
* Lager durchgeführt von Regionen und Abteilungen (Unterebenen vom Kanton)
* Lager durchgeführt in diesem Kanton.

Das machen wir über eine Tabnavigation wie bei der Personenliste, Bezeichnungen sind aber schwierig zu finden. Hier sind wir dankbar für Vorschläge.

![image](https://user-images.githubusercontent.com/194364/33276760-b70eec2c-d396-11e7-9b14-4f809a246cdd.png)

Hier ein Vorschlag, der implizeirt allerdings, dass man unter Alles auch die Lager sieht, die im Kanton BE durchgeführt werden (es wäre aber einfacher diese separat zu behandeln und nur aufzuführen, wenn man den entsprechenden Tab ausgewählt hat).

**Comment by js4gh** [comment]
in der PBS Testumgebung wird zur Zeit "durchgeführt im Kanton" immer angezeigt, gedacht ist aber das die Funktion nur auf Gruppen vom Typ Kanton erscheint.

**Comment by RolandStuder** [comment]
Zu korrigieren:
- [ ] "Durchgeführt in [Kantonsname]" soll nur bei Lager erscheinen, erscheint zurzeit auch bei Kursen und Anlässen.

**Comment by RolandStuder** [comment]
@adriananderegg Bitte abnehmen. (Hier der Vorbehalt, dass fälschlicherweise “durchgeführt im Kanton” auch bei Anlässen und Kursen angezeigt wird. Dies wird noch korrigiert.)

**Comment by js4gh** [comment]
@RolandStuder 

Wie sieht es mit der ursprünglich gewünschten Sortierfunktion aus? Es wäre wünschenswert das man die Angezeigten Lager manuell sortieren kann. (so wie das bei der Personen Ansicht auch möglich ist)

Ein Problem mit der Anzeige muss noch korrigiert werden:
"Ist Scope Nur [layername]gewählt so erscheinen alle Events von Untergruppen (aber nicht Unterlayern)"

https://pbs.puzzle.ch/de/groups/506/events/camp?filter=layer&returning=true   

Das Lager "test_on_utteloo" wird nicht angezeigt obwohl es sich in der selben Abteilung (gleicher Layer) befindet. Bei der "Alle" Ansicht klapp es dann wunderbar, was den ursprünglichen Wunsch nach einer besseren Übersicht in der Abteilung, Region usw. abdeckt. Mein Vorschlag die Ansicht "Nur [layername]" so anpassen das wie heute nur die Lager der aktuellen "Gruppe" angezeigt werden.
was meinst du?

Wenn das noch angepasst ist kann die Erweiterung dann von mir aus als abgenommen betrachtet werden.

**Comment by RolandStuder** [comment]
@js4gh 

* Ah, ja es zeigt fälschlicherweise nur die Untergruppen. Das fixen wir.
* Und ja Sortierfunktion ging unter, wir ergänzen noch, dass nach Name, Datum, Status, Gruppen, Kanton/Land sortiert werden kann, nicht aber nach Beschreibung oder Anmeldung

**Comment by amaierhofer** [comment]
Bei "Nur [layername]" sollen rekursiv all Kindergruppen berücksichtig werden, die keine layer sind.

**Comment by RolandStuder** [comment]
@js4gh Wir haben es in die andere Richtung gefixed. Es werden auch  bei der Wahl "Nur [Ebenenename]" Kindeskinder usw angezeigt.

Es ist besser, wenn wir auch jeweils die Anlässe von Untergruppen anzeigen, weil es schwierig zu verstehen ist, dass sich auf Untergruppen auch noch Events verstecken können. Dieses Verhalten werden wir mittelfristig auch bei anderen Orten einfügen, z. B. bei Abos, dies man sonst gar nicht auffindet, ausser man weiss, dass man dort noch nachschauen kann.

Ein Lösung mit drei Scopes hatten wir auch überlegt, aber bringt eigentlich nicht so viel, und es ist sprachlich extrem umständlich drei Filter zu haben, Alle, Nur [Ebenenname], [Ebenenname] unter Untergruppen (nimmt dann auch sehr viel Platz ein).

Das einzige was ich sehe ist, dass der Filter nicht Sinn macht, wenn es gar keine Unterebenen gibt, dort wird wohl eben eher das von euch formulierte Verhalten erwartet.

**Comment by RolandStuder** [comment]
Filter wird jetzt nur noch angezeigt, wenn es überhaupt noch Unterebenen hat. https://github.com/hitobito/hitobito/commit/60d4ec1b5cb52fc71a96c5ebe76d3e7452caf25b

**Comment by js4gh** [comment]
@RolandStuder finde ich gut so... das mit dem Filter ist aber noch nicht im PBS TEST-System oder?
Mir ist aufgefallen das die Sortierfunktion auf dem Kantonalverband, bei der Ansicht "im Kanton durchgeführt" nicht funktioniert ich nehme an das korrigiert ihr noch?

**Comment by Michael-Schaer** [comment]
Die Sortierung muss noch gefixt werden. Ansonsten abgenommen.
