### ISSUE TITLE
Performance Analyse Liste_courses

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#394]
bei db.scout.ch führt die Ansicht https://db.scout.ch/de/list_courses oft zu einem TimeOut

**Comment by RolandStuder** [comment]
Diese Ansicht darf nicht ein Time Out geben. Bitte anschauen, woran das liegt. Meine Vermutung ist, dass die Anzeige der Anzahl Teilnahmen, das ganze langsam macht.

Bitte 1-2h investieren um das query zu analyisieren und Lösungsvorschläge zu machen. Ich vermute zwei Möglichkeiten wären:

- Zwischenspeichern der Teilneherzahlen im Model
- Pagination der Ansicht mit geeigneten Filter, dazu mache ich noch ein Mockup.

**Comment by RolandStuder** [comment]
Hier eine Visualisierung, wie man das mit Pagination und Filtern machen könnte. @janissbinder bitte eine Grobschätzung machen:

![image](https://user-images.githubusercontent.com/194364/31078287-c8183e88-a781-11e7-86da-e5aed2645287.png)

**Comment by janissbinder** [comment]
Ich habe mir das ganze einmal angesehen. Wir haben momentan ein generelles Performance Problem beim laden der Kurse. Momentan fällt dies leider erst beim Anzeigen der Kursliste auf, sollte jedoch trotzdem frühzeitig behoben werden.

**Comment by RolandStuder** [comment]
@janissbinder Ich habe mir das mal angeschaut. Ein grosses Problem ist dass, das campy Modul einen N + 1 Query erzeugt, da bei after_initalize jedesmal der Kind geladen wird, und das passiert, vor irgendwelchen includes. Die Implementation von `campy` ist damit ziemlich performance behindert. Wenn ich dies entferne, ist die Ansicht mindestens doppelt so schnell. Das Problem ist natürlich, dass `campy?`an anderen Orten gebraucht wird.

Siehe das :after_initialize 

https://github.com/hitobito/hitobito_pbs/blob/e69a4340b26a0e736e60612d77de2d22fde60825/app/models/pbs/event/course.rb#L42

**Comment by RolandStuder** [comment]
Ich schliesse dieses Issue @KunoKunz aber hier ist die Performance eine Katastrophe, really hurts PBS Leute, die alle Kurse sehen können.
