### ISSUE TITLE
Tentativ Roles verhindern Anzeige von tatsächlicher Zuweisung bei Kursen(6h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#395]
Person werden im Kurs bei zugeteilter Rolle manchmal nicht angezeigt, wenn sie für die Person eine provisorische Anmeldung vorliegt.

# Schritte zum Reproduzieren

* Installation mit youth_wagon nehmen
* Kurs eröffnen
* Kurs Bearbeiten / auf Tab Anmeldung Möglichkeit "provisorische Anmeldungen aktivieren"
* Auf dem Tab `Info` eine Person provisorisch anmelden
* Die Person auf dem Tab Teilnehmer in einer Rolle z. B. "Küche" hinzufügen (nicht Hauptleitung wählen, da es mit dieser Rolle funktioniert)

**Expected**: Hinzugefügte Person erscheint auf der Personenliste

**Actual**: Person erscheint nicht auf der Personenliste

# Korrigieren:

* Neu soll ein Hinzufügen mit einer Rolle, die provisorische Anmeldung löschen.

**Comment by janissbinder** [comment]
https://github.com/hitobito/hitobito_youth/commit/18366b4f96a4442e787356cf7712ba0e7c1cbab2
