### ISSUE TITLE
SphinxIndexJob wirft Exception

### ISSUE THREAD

**Issue by hupf** [hitobito/hitobito#397]
Betrifft folgenden Errbit Fehler:
https://errbit.puzzle.ch/apps/597041bcbd44b8009c944c65/problems/59cb644e0c4ec2009c4b7ead

```
NoMethodError: undefined method `index' for #<ThinkingSphinx::RakeInterface:0x00000002029c00>
```

### Problem 1

Im folgenden Commit wurde Sphinx aktualisiert:
ce145b0795c471496a00c2b740cf4a6ad6441074#diff-8b7db4d5cc4b8f6dc8feb7030baa2478

Im `SphinxIndexJob` rufen wir `#index` auf:
ThinkingSphinx::RakeInterface.new.index

Diese Methode gibt es nicht mehr, unser Job muss angepasst werden:
https://github.com/pat/thinking-sphinx/commit/b809f81c17bc9879e4620c5e2530900a23c3c05d#diff-ec2634b6fd4c4a7faecb98d523a7026eL40

### Problem 2

In der OpenShift Umgebung sollte nicht mehr mit dem DelayedJob indexiert werden, dies passiert im Sphinx Container selber.

**Comment by psunix** [comment]
fixed
