### ISSUE TITLE
Rechnungsentwurf erstellen 24h

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#40]
Alles bezieht sich

- Auf der Rechnungsübersicht kann mit einer Action "Neue Rechnung" eine neu Rechnung erstellt werden.
- Ein neues Sheet erscheint (https://projects.invisionapp.com/share/S47MIDEDH#/screens/165849459) 
- Ich kann über die Suche eine Person hinzufügen (gleiche Zugriffsart wie bei der globalen Suche)
- Sobald ich eine Person ausgesucht habe, werden die Kontaktdaten von dieser Person angezeigt. (https://projects.invisionapp.com/share/S47MIDEDH#/screens/165849482)
- Ein Klick auf Empfänger ändern, führt zum vorherigen Zustand zurück.
- Die Rechnung enthält Rechnungstitel, Rechnungstext, Rechnungsdatum, Rechnungsnummer
- Rechnungsnummer sollte fortlaufen sein und stellt sich aus ID der Ebene und einer Laufnummer zusammen z. B. #674-1
- Eine Rechnung enthält 1-N Positionen.
- Postionen können hinzugefügt, verändert und gelöscht werden.
- Eine Position enthält einen Namen, eine Beschreibung einen Betrag, Anzahl (default 1), MWSt. (defaultwert 8%)
- Betrag wird automatisch errechnet inkl. MWSt.
- Zustäzlich wird TOTAL, MWST TOTAL und TOTAL INKL MWST. angezeigt.
- Eine Rechnung kann folgende Stati haben: Entwurf | Gestellt | Überfällig | Bezahlt | Storniert (evlt. teilweise bezahlt) 
- Beim Erstellen werden Personendaten kopiert, so dass immer die Adresse gespeichert wird, welche zum Zeitpunkt der Rechnung hinterlegt ist, und damit keine Zugriffsproblem entstehen, sollte die Person die Rolle nicht inne haben, aufgrund der ich diese Person sehe.
- Action Entwurf Speichern erstellt eine Rechnung im Status Entwurf.

**Comment by RolandStuder** [comment]
FRAGE: 
Macht das Behandeln der MWSt. für diese Personen überhaupt Sinn für lokale Gruppenleiter.

**Comment by adriananderegg** [comment]
MwSt. macht aus meiner Sicht (Sicht Jugendverbände) keinen Sinn, da ein Verein mehr als 150'000 CHF aus kommerzieller Tätigkeit machen müsste. Für die üblichen Gruppen sicherlich kein Thema. 

*******************
entnommen von http://www.vitaminb.ch/static/files/bdur/b_durS_16.pdf

Mehrwertsteuerpflichtig sind alle Umsätze aus einer kommerziellen Tätigkeit. Darunter fallen beispielsweise Festwirtschaftsbetriebe, Verkauf von Basarartikeln, Sponsoring oder andere Werbeleistungen. 
Ausgenommen sind Leistungen, die nicht gewinnorientierte Einrichtungen (also etwa Vereine) ihren Mitgliedern gegen einen statuarischen Beitrag erbringen. Für Sportvereine, die nicht gewinnorientiert sind und ehrenamtlich geführt werden, besteht bis zu einem Jahresumsatz von höchstens 150'000 Franken keine Mehrwertsteuerpflicht.
