### ISSUE TITLE
Defaultrollen in Gruppen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#401]
In vielen Föllen wenn ich z. B: Kontakte hinzufüge zu einer Gruppe ist in 99% der Fälle die Rolle schon klar. Es wäre praktisch, wenn pro Gruppentyp eine Defaultrolle festgelegt werden könnte, welche automatisch beim hinzufügen und Import vorausgewählt ist.

**Comment by Tschet1** [comment]
duplicate of 548?
