### ISSUE TITLE
Exception beim Aufruf Personen Log Seite PBS prod

### ISSUE THREAD

**Issue by psunix** [hitobito/hitobito#404]
https://errbit.puzzle.ch/apps/529c60a2de77482d71027b0a/problems/59ef73d75d429f7dd86afef6

https://github.com/hitobito/hitobito/blob/stable/app/models/person/add_request/mailing_list.rb#L26

Der AddRequest scheint keiner Gruppe assigned zu sein

**Comment by amaierhofer** [comment]
AddRequests für nicht existierende MailingList, sollten über dependent_destroy gelöscht werden. Habe die zwei pending add_requests von hand gelöscht
