### ISSUE TITLE
pbs wagon: label "Button"

### ISSUE THREAD

**Issue by psunix** [hitobito/hitobito#405]
![latest-screenshot](https://user-images.githubusercontent.com/655627/31992814-99d235ea-b97b-11e7-8ca5-45c7253c2d4c.png)

bei event approval form hat der Submit-Button das Label: "Button". 
Titel ist 'title?

groups/:group_id/events/:event_id/participations/:participation_id/approvals

soll hier grundsätzlich wirklich ein formular angezeigt werden ?
sollte ja die approvals auflisten, nicht?

**Comment by RolandStuder** [comment]
Schliesse das Issue wegen Inaktivität.
