### ISSUE TITLE
pbs wagon: event approval exception wenn keine decision gesetzt

### ISSUE THREAD

**Issue by psunix** [hitobito/hitobito#406]
event/approvals#create 
https://errbit.puzzle.ch/apps/529c60a2de77482d71027b0a/problems/59c16a610c4ec2009c4af0c7

param decision ist hier nil.
hidden field decision wird über get param befüllt. (via click auf button auf der participation#show)
wurde der link direkt ohne diesen param aufgerufen ?
redirect zu participatio#show wenn param nicht gesetzt ?

**Comment by RolandStuder** [comment]
Schliesse das Issue wegen Inaktivität.
