### ISSUE TITLE
Kinder als Ehemalige hinzufügen wenn ein bestimmtes Alter erreicht ist (4h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#409]
- Kinder welche >= 15 sind sollen angeschrieben werden und zu den Ehemaligen hinzugefügt werden.
- Das Alter, ab welchem die Kinder angeschrieben werden, soll anpassbar sein

## Akzeptanzkriterien

- Personen mit Adminberechtigung haben unter Einstellungen einen neuen Menüpunkt "Ehemaligenverwaltung"
- Unter Adminpunkt Ehemliagenverwaltung kann ein Alter festgelegt werden (Integer)
- Bei entfernen der Rolle Kindergruppee::Kind wird (falls keine andere Rolle besteht), eine Kind als Ehemalige::Mitglied hinzugefügt, wenn sein Alter >= als das festgelegte Alter ist.

**Comment by MartinGantenbein** [comment]
Diese Anforderung macht nur für Jugendorganisationen Sinn und sollte daher nur für diese umgesetzt werden.

**Comment by RolandStuder** [comment]
@MartinGantenbein Ja, das wird nur für die Jubla so umgesetzt. Danke fürs Feedback

**Comment by janissbinder** [comment]
https://github.com/hitobito/hitobito_jubla/commit/02b3a8767848911d0a0277e2dd0483520a04dd2f

**Comment by RolandStuder** [comment]
Wir die Altergrenze konfigurierbar gemacht, aber das passiert in einem Konfigurationsfile. Es gab keinen sinnvollen Ort um die Einstellung abzulegen, extra eine Seite dafür anzulegen schien uns auch nicht wirklich adäquat. Wir gehen ja auch davon aus. Dass sich das nur sehr selten ändern wird, daher denken wir dass es sinnvoller ist, das im Konfigurationsfile festzuhalten.
