### ISSUE TITLE
event participation: duplicate index entry (mysql error)

### ISSUE THREAD

**Issue by psunix** [hitobito/hitobito#414]
https://errbit.puzzle.ch/apps/529c60a2de77482d71027b0a/problems/59bec8e90c4ec2009c4a9d6b

exception ist schon mehrmals aufgetaucht. konnte das innerhalb kurzer Zeit aber nicht rekonstruieren. Schickt man das selbe Formular für die Participation zweimal ab, scheint dieser Fall gehandelt zu sein. 

Exception:
Mysql2::Error: Duplicate entry '4939-24044' for key 'index_event_participations_on_event_id_and_person_id'

**Comment by RolandStuder** [comment]
@psunix Ist das mit dem PR von kronn gelöst? Können wir dieses Issue schliessen?

**Comment by kronn** [comment]
Ich hätte gerne ein Review für den PR, vielleicht ist der darin enthaltene Ansatz nicht der beste.
