### ISSUE TITLE
person send add request job: add request cannot be found

### ISSUE THREAD

**Issue by psunix** [hitobito/hitobito#415]
https://errbit.puzzle.ch/apps/529c60a2de77482d71027b0a/problems/5a0b43d253b77b2445d0a6cc

der erwähnte job findet teilweise den add request nicht. add request existieren nur solange diese noch nicht bestätigt/abgelehnt wurden. wurde in diesen Fällen evtl. der Add Request bereits vor dem Mail verarbeitet? Den Job so bauen das er die Meldung nur rauslässt wenn der AddRequest nocht existiert.

**Comment by hupf** [comment]
Duplicate of #440
