### ISSUE TITLE
Auf Suchresultate-Ergebnis-Seite (global Search) auch Events und Gruppen darstellen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#419]
IST:

Mache ich eine Suche in der globalen Suche oben rechts und klicke auf die Lupe, dann komme ich auf eine Suchresultateseite. Auf dieser finde ich aber nur Personen.

SOLL:

Diese Suchresultateseite so erweitern, dass auch Events und Gruppen als Resultate erscheinen.

### Spalten für Gruppen:
- Gruppenname
- Layername

### Spalten für Events:
- Eventname
- Daten
- Beschreibung
- Durchführende Gruppe / Ebene

![image](https://user-images.githubusercontent.com/194364/33257215-ac5b4956-d355-11e7-988f-e109e1616b01.png)

**Comment by Michael-Schaer** [comment]
Ein erstes Benutzer-Feedback zu der neuen Darstellung der Such-Resultate:

> Sinnvoll wäre es hier, von Beginn weg den Tab anzuzeigen, der auch Ergebnisse ausspuckt.
> Bsp: ich suche nach „PBS CH 563-18“ und klicke auf die Lupe um zu suchen. Dann sehe ich auf den ersten Blick den leeren Personen-Tab, anstelle der „Anlässe“.

**Comment by RolandStuder** [comment]
@Michael-Schaer Danke für das Feedback. Habe ein Issue dazu aufgestellt, wäre sicher kein schlechtes Issues für jemand der mal was Programmieren will oder für den Hackathon. https://github.com/hitobito/hitobito/issues/512
