### ISSUE TITLE
Bei Abos definieren, welche Email-Adressen bevorzugt werden sollen (12h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#421]
## Hintergrund:

Bei Organisation wie der Pfadi werden oft Kinder als Personen erfasst, allerdings sollen Versandinformationen an die Eltern gehen. Siehe Issue #412 und https://github.com/hitobito/hitobito/issues/410. 

## Umsetzung

* Bei Abos kann man neu hinterlegen, welche Labels von Email, bevorzugt für den Versand verwendet werden soll.
* Ein Versand an eine E-Mail List geht nach folgenden Regeln:
  * Sind keine präferierten Versand-Email-Labels definiert so funktioniert es wie bisher.
  * Sind präferierte Labels vergeben, erfolgt der E-Mailversand bei den einzelnen Personen an die Emails mit dem entsprechenden Label.
  * Ist für eine Person keine E-Mail mit dem entsprechenden Label vorhanden, so wird das E-Mail an die Versandadressen geschickt. 
  * Wenn mehrere Labels zutreffen, an alle Labels schicken

## Zu fixen:

* [ ] Darstellungsbug korrigieren siehe: https://github.com/hitobito/hitobito/issues/421#issuecomment-365064403
* [ ] Ermöglichen auch Haupt-Email-Adresse einzuschliessen. Zwei Varianten, siehe Mockups:
   * Mit Checkbox: "Versand auch an Haupt-E-Mail-Adresse"
   * Mit Label "Haupt-E-Mail"

### Variante Checkbox

![image](https://user-images.githubusercontent.com/194364/36421378-78dee896-1638-11e8-95dd-6cd71306c4c1.png)

### Variante: label für Haupt-e-Mail

* Label "Haupt-e-Mail" erlauben.
* Problem: Wie machen mit Übersetzungen? Alle Übersetzungen als Varianten von diesem behandeln?
* Hilftetext gemäss Screenshot unten ergänzen.

![image](https://user-images.githubusercontent.com/194364/36422222-751438a8-163b-11e8-8173-e9e524b2af1a.png)

**Comment by amaierhofer** [comment]
Aufwand in etwa 12h

* Neues Attribute prefered_labels auf MailingList (serializiertes Array)
* UI Anpassungen, Labels vergeben mit typeahead
* Anpassungen bei `MailRelay::List#receivers` (Gesetzte Labels berücksichtigen)
* Integration tests

**Comment by amaierhofer** [comment]
@RolandStuder Hast du einen Vorstellung davon mit welcher UI Komponente wir die Label Auswahl bei der Mailing Liste am machen wollen?

**Comment by RolandStuder** [comment]
Konnte ich nicht korrekt testen, da Mailtrap die BCC Empfänger nicht auflistet.

Aber der Export der E-Mailadressen respektiert die bevorzugten Labels nicht, siehe https://pbs.puzzle.ch/de/groups/392/mailing_lists/88/subscriptions.email?returning=true

korrigieren:

- [ ] Auch e-Mailexport sollte dieselben Empfänger enthalten wie die Mailingliste.

**Comment by RolandStuder** [comment]
@adriananderegg Bitte abnehmen

**Comment by js4gh** [comment]
@RolandStuder 
mit welche Label kann die, nur die "Haupt-E-Mailadresse" angesprochen werden? Ich denke so zur Vollständigkeit braucht es die Möglichkeit oder?

**Comment by RolandStuder** [comment]
@adriananderegg Wie seht ihr das, braucht es eine Ansprechmöglichkeit der Haupt-E-Mailadresse? Die Ergänzung würde ermöglichen, dass man z. B. Vater, Mutter, Erziehungsberechtigte und Haupt-E-Mail Adresse ansprechen könnte.

Ich bin mir nicht sicher, ob es nötig ist, sehe aber dass die Möglichkeit aktuell fehlt.

**Comment by adriananderegg** [comment]
In der Anzeige hat es einen Fehler, wenn mehrere Labels ausgewählt werden, der Info-Text wird wiederholt. 
Ich würde zudem im Info-Text erwähnen, dass (Vorschlag) "Dabei werden auch E-Mail Adressen verwendet, die nicht als Versand-Adresse markiert sind". 
Ebenfalls den Tool-Top bei "Versand" auf der Person ergänzen. Vorschlag:
"Kann durch die Angabe eines Labels im Abo übersteuert werden."

![grafik](https://user-images.githubusercontent.com/9968417/36119949-df8619cc-1041-11e8-8e8e-5458dbdf33b0.png)

**Comment by RolandStuder** [comment]
@amaierhofer  Bitte fixen gemäss den Punkten im Ticket: Darstellungsfehler, Textergänzungen und Möglichkeit Haupt-E-Mail Adresse auch einzuschliessen.

**Comment by RolandStuder** [comment]
@amaierhofer Habe es mit Mockups ergänzt, es gibt zwei Variante, wähle die einfachere zum implementeiren. Es ist wohl schwierig dies über eine Label zu lösen, weil ich in alle Sprachen abdecken können muss, somit müssten mehrere Labels als "Haupt-E-Mail"-label gelten, z.B.  "e-mail principale", "main adress", der Hilfetext müsste auch jeweils dieses Beispiel enthalten.
