### ISSUE TITLE
Neuer Gruppentyp Kommission (3h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#422]
Neuer Gruppentyp: `Kommission`
Auf Kanton / Region / Dachverband

Rollen:
* Leitung :layer_and_below_read, :group_and_below_full
* Mitglied :layer_and_below_read, :group_and_below_read

**Comment by adriananderegg** [comment]
gemäss Frage im alten Issue [hier](https://github.com/hitobito/hitobito_pbs/issues/71#issuecomment-347229197)
Bitte auf Region, Kanton und Bundesebene ermöglichen.

**Comment by RolandStuder** [comment]
@adriananderegg Bitte abnehmen

**Comment by adriananderegg** [comment]
@RolandStuder abgenommen
