### ISSUE TITLE
Varianten Einzahlungsschein wählen und drucken

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#425]
Es gibt vier Typen von Einzahlungsscheinen, die wir unterstützen müssen:

Notwendige Angaben in der Konfiguration

## Roter Einzahlungsschein (Einzahlungsschein Post)

* Einzahlung für (Textarea)
* Postkonto-Nummer (String)

Ergibt roten Einzahlungschein mit Feld Zahlungszweck,  Beispiel:
![image](https://user-images.githubusercontent.com/194364/33667639-b2763720-da9d-11e7-905e-40b9f3596592.png)

## Roter Einzahlungschein Bank (Einzahlungsschein Bank)

siehe auch: https://www.appkb.ch/download/online/roter_ES.pdf

* Einzahlung für
* IBAN
* Zugunsten von
* Postkonto Nummer der Bank

Ergibt roten Einzahlungschein mit Feld Zahlungszweck, Beispiel:
![image](https://user-images.githubusercontent.com/194364/33667485-44be97e0-da9d-11e7-92a7-df8eb3c9c380.png)

## ESR (oranger Einzahlungsschein Post)

* Einzahlung für
* Teilnehmer-Nummer

Volle Info https://www.postfinance.ch/content/dam/pfch/doc/cust/download/inpayslip_isr_man_de.pdf

Beispiel:

## BESR (oranger Einzahlungsschein Bank)

* Einzahlung für
* Zugunsten von
* Teilnehmer-Nummer

Volle Info:
https://www.zkb.ch/media/dok/efinance/vesr-handbuch-fk.pdf

Beispiel:
![image](https://user-images.githubusercontent.com/194364/33668841-21577f98-daa1-11e7-926f-1a35f681035e.png)

### Einstellungen

* [x] Einzahlungsschein-Art wählbar in den Einstellungen
* [x] Attribute für roten Einzahlungschein Post hinterlegbar
* [x] Attribute für roten Einzahlungsschein Bank hinterlegbar
* [x] Attribute für orangen Einzahlungschein Post hinterlegbar (ESR)
* [x] Attribute für orangen Einzahlungsschein Bank hinterlegbar (BESR)

### ESR Nummer generieren

* [x] ESR Nummer generieren 27-stellig

### Druck

* [x] Druck von roten Einzahlungschein Post funktioniert
* [ ] Druck von roten Einzahlungschein Bank funktioniert
* [x] Druck von orangem Einzahlungschein Post funktioniert ESR
* [ ] Druck von orangem Einzahlungschein Bank funktioniert BESR
* [ ] Druck von orangem Einzahlungsschein Post ohne Betrag funktioniert ESR+
* [ ] Druck von orangem Einzahlungscchein Bank ohne Betrage funktioniert BESR+

### Codierzeile

* [ ] Codierzeile von roten Einzahlungschein Post funktioniert
* [ ] Codierzeile von roten Einzahlungschein Bank funktioniert
* [x] Codierzeile von orangem Einzahlungschein Post funktioniert ESR
* [ ] Codierzeile von orangem Einzahlungschein Bank funktioniert BESR
* [ ] Codierzeile von orangem Einzahlungsschein Post ohne Betrag funktioniert ESR+
* [ ] Codierzeile von orangem Einzahlungscchein Bank ohne Betrage funktioniert BESR+

### Tests

* [ ] Test von roten Einzahlungschein Post erfolgreich durchgeführt
* [ ] Test von roten Einzahlungschein Bank erfolgreich durchgeführt
* [ ] Test von orangem Einzahlungschein Post erfolgreich durchgeführt ESR
* [ ] Test von orangem Einzahlungschein Bank erfolgreich durchgeführt BESR
* [ ] Test von orangem Einzahlungsschein Post ohne Betrag erfolgreich durchgeführt ESR+
* [ ] Test von orangem Einzahlungscchein Bank ohne Betrage erfolgreich durchgeführt BESR+

**Comment by janissbinder** [comment]
* Druck von orangem Einzahlungsschein Post ohne Betrag funktioniert ESR+
* Druck von orangem Einzahlungscchein Bank ohne Betrage funktioniert BESR+

@RolandStuder Verstehe ich das richtig, es sollte die Möglichkeit geben einen orangen Einzahlungsschein ohne den Betrag auszudrucken?

**Comment by janissbinder** [comment]
Ich habe das mit den Beträgen nun umgesetzt. Leider hat diese Erneuerung das Dropdown ein wenig überfüllt: 
![image](https://user-images.githubusercontent.com/5112014/33884910-d97618e2-df41-11e7-9514-a118eb62b83b.png)

@RolandStuder Ich wäre dir dankbar wenn du ein Input geben könntest wie man den Workflow hier verbessern könnten oder ob wir es vorerst einmal so stehen lassen sollen.

**Comment by janissbinder** [comment]
@RolandStuder ist jetzt eigentlich bekannt, wie die ersten Ziffern der Referenznummer gebildet werden? Und weshalb gibt es eigentlich eine 16 wie auch 27 stellige Referenznummer?

**Comment by RolandStuder** [comment]
@janissbinder Die Idee ist eher, dass wenn ich keinen Posten erstelle, dass ich dann eine Rechnung ohne Rechnungsbetrag erhalte. Oder ist das vom Flow her ein Problem?

**Comment by janissbinder** [comment]
@RolandStuder nein das ist vom Flow her kein Problem. Die minus Beträge sollen in dem Fall auch angezeigt werden?

**Comment by janissbinder** [comment]
Die Kodierzeile für den Roten Einzahlungsschein muss noch erstellt werden.
