### ISSUE TITLE
Export Fehler bezügliche Qualifikationsdaten

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#428]
Bug gemeldet von Rene Brügger

Siehe Person: https://db.scout.ch/de/groups/3158/people/23562
Qualifikationen laufen bis Ende 2019 gemäss Übersicht:

![image](https://user-images.githubusercontent.com/194364/33854377-cef4a580-dec1-11e7-9a81-f4bd8b5fcebd.png)

Mache ich einen Export so zeigen dieser als Ablaufdaten der Qualifikation die falschen Daten an:

![image](https://user-images.githubusercontent.com/194364/33854407-f0eb44aa-dec1-11e7-98c0-fd6adb5759a8.png)

Meine Vermutung ist, dass nicht die neuste Qualifikation genommen wird beim Export, sondern eine veraltete oder ist es dasselbe Problem, wie bei #423

**Comment by kronn** [comment]
Es ist leider nicht das selbe Problem wie im anderen Issue gewesen. Die Vermutung war aber trotzdem richtig. Es wurde die erste gültige Qualifikation gewählt. In der Anzeige wird die genommen, die zuletzt erworben wurde und damit am längsten gilt. Der Export macht das jetzt genauso wie die Anzeige. Somit bestätigen beide Quellen nun gleichermassen:
![you-have-koalafications](https://user-images.githubusercontent.com/72198/34119428-625a1e76-e422-11e7-808c-deb79d14ca05.jpeg)
