### ISSUE TITLE
Alle Exports die aktuell per E-Mail zugestellt werden auf einen async Prozess umstellen. (8h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#429]
Aktuell werden einige Exports per Email zugestellt. Bitte Aufwandschätzung für eine Lösung, wo sie wieder direkt im Browser heruntergeladen werden können, allerdings mit async Javascript, so dass der Benutzer nicht in eine Timeout läuft.

**Comment by amaierhofer** [comment]
- Job anpassen, file nach tmp//#{filename} schreiben
-  Timestamp in filename mitaufnehmen
- Auf neue seite redirecten, wo via js so lange gepullt wird bis das file da ist
- Files die älter als 1 Tag sind löschen

**Comment by RolandStuder** [comment]
![image](https://user-images.githubusercontent.com/194364/40615792-8f98b494-6288-11e8-9516-d9280a491a76.png)

**Comment by janissbinder** [comment]
@amaierhofer kannst du dir den momentanen stand einmal auf https://github.com/hitobito/hitobito/tree/async_export anschauen?
