### ISSUE TITLE
Rechnung per E-Mail erstellen (6h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#43]
- Email wird nur an Primäradressene verschickt (weitere Versandadressen könnten dazu führen, dass zum Beispiel Rechnung an zwei getrennte Elternteile geht).
- Absender-Email ist primäre Email-Adresse der eingeloggten Person
- Zahlungsbedingungen gemässe Einstellungen auf dem Rechnungsmodul
- PDF Rechnung ohne Einzahlungsschein anhängen
- Warnung nach der Aktion, wenn kein Emailverschickt werden konnte, weil keine primäre Emailadresse hinterlegt ist.
- Rechnungsstatus ändert auf "Gestellt"

https://projects.invisionapp.com/share/S47MIDEDH#/screens/166316058

**Comment by RolandStuder** [comment]
Hat jemand eine bessere Idee wie wir das lösen, wohin diese Rechnungen geschickt werden sollen wenn wir mehrere E-Mailadressen als Versand markiert haben?

**Comment by adriananderegg** [comment]
Eine ähnliche Story mit dem Empfänger gibt es auch bei den Abos (E-Mail oder Etiketten), wo teilweise gewünscht wird, die Kommunikation an die Eltern zu richten. 
Diese Story wird etwas weniger relevant, wenn Rechnungen nicht mehr via Abos ausgelöst werden. Trotzdem wird es weiterhin auch andere Kommunikation geben, welche an die Erziehungsberechtigten gerichtet werden möchten, z.B. Einladung an die Mitgliederversammlung (welche auch an die gesetzlichen Vertreter gesendet werden sollte). 

Daher generelle Lösung EINES (verknüpften, ähnlich wie bei Geschwistern?) Adresstyps "Erziehungsberechtigte/r bei Minderjährigen", der bei Rechnungen und Abos zum Einsatz kommen könnte.
[neues Enhancement?]

Andere Möglichkeiten wären:
- die Definition EINER "Rechnungsadresse" direkt auf dem Kontakt mit einer (default) Option "wie Primäradresse". So könnte die Primäradresse bei Bedarf übersteuert werden. 
- Warnhinweis in Rechnungsemail, dass diese Rechnung an mehrere Empfänger gesendet wurde, jedoch nur 1x zu bezahlen ist.

**Comment by amaierhofer** [comment]
* Aktuell gibt es Fehler wenn keine Email vergeben ist (siehe #61)
* UI ist verwirrend, da Rechunug Zustandsänderung im Background passiert. 
* Falls Rechnung ohne E-Mail möglich sein soll, dann müssen wir auch die Rechnung im Controller updaten
