### ISSUE TITLE
Ehemaligen Kontaktflag falscher Default

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#434]
IST: Die Flags sind per Default NICHT ausgewählt.

SOLL:

* Flags sollen auf True gesetzt sein als Default, wenn eine Person neu Ehemaligenstatus erhält.
* Auch bei migrierten Ehemaligen sollen alle Flags auf True gesetzt sein.

**Comment by RomanOester** [comment]
Ist OK.
