### ISSUE TITLE
Rolle Ehemalige:Adressverwaltung existiert nicht oder hat falschen Namen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#437]
Gruppe: Ehemalige Rolle Addressverwaltung existiert nicht, oder hat falschen Namen (zwei Rollen mit Versandsaddresse)

![image](https://user-images.githubusercontent.com/194364/34199943-9d9e86e0-e56f-11e7-8354-d9ae5c84b38c.png)

**Comment by amaierhofer** [comment]
https://github.com/hitobito/hitobito_jubla/blob/4ca0ceeef465b8e9dcbb2774e3b2e56688310eb9/app/models/group/alumnus_group.rb#L57
