### ISSUE TITLE
Absendereinstellungen festlegen (4h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#44]
https://invis.io/S47MIDEDH#/168708071_Rechnungsstellung-Einstellungen_Formular

Unter Einstellungen auf dem Rechnungsmodul können folgende Einstellungen vorgenommen werden:
- Absender (Textarea)
- Absender-Email (Dropdown mit primären Emails aller Personen mit der Berechtigung für Finanzen
- Zahlungsinformationen (Textarea).
- Standardzahlungsfrist (Integer, Anzahl Tage)

**Comment by amaierhofer** [comment]
Ich hab auf den Invision sketch keinen Zugriff, kannst du mich bitte noch berechtigen, bin dort mit der puzzle email registriert.

**Comment by RolandStuder** [comment]
Habe den Link angepasst.
