### ISSUE TITLE
Person::AddRequest kann im Job nicht geladen werden

### ISSUE THREAD

**Issue by hupf** [hitobito/hitobito#440]
Errbit Issue: https://errbit.puzzle.ch/apps/529c60a2de77482d71027b0a/problems/5a54d9df8030ff5a9fc14328

Passiert bei PBS Prod. Der `Person::SendAddRequestJob`, wollte einen `Person::AddRequest` laden, welcher zum Zeitpunkt als der Job ausgeführt wurde nicht mehr existert hat. Ich konnte noch nicht herausfinden wie es zu dieser Konstellation kam. Wird ev. die Person wieder entfernt während der Job gescheduled, aber noch nicht gelaufen ist?

**Comment by RolandStuder** [comment]
Schliesse das Issue wegen Inaktivität.
