### ISSUE TITLE
Mahnungen erstellen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#442]
IST: Bisher wurde nur ein UI erstellt, für das Mahnwesen, ohne die Prozesse darum herum zu implementieren.

SOLL: Auch Prozees im plementerein und UI dafür anpassen.

## Grobidee:

3 Mahnstufen mit Standardtexten. Mahnung und Rechnungsstellung soll gleich abgehandelt werden ohne zusätzliche Buttons

## Akzeptanzkriterien

* [ ] Unter Einstellungen kann für jeden Layer für jede Mahnstufe ein Titel vergeben werden (z. B. Zahlungserinnerung)
* [ ] Unter Einstellungen kann für jeden Layer für jede Mahnstufe eine Text vergeben werden (z. B. "Ihnen ist vielleicht entgangen, dass Sie eine unserer Rechnungen noch nicht bezahlt haben).
* [ ] Unter Einstellungen kann für jeden Layer für jede Mahnstufe eine Zahlungsfirst angeben werden (z. B. 30 Tage)

## Button "Rechnung stellen" / Mahnungen drucken

* [ ] Der Button `Rechnung stellen` heisst neu `Rechnung stellen/mahnen`
* [ ]  Mahnungen werden gleich gedruckt wie Rechnungen, das System stellt selbst fest was gemahnt wurde.
* [ ] Neu heissen die Actions `Status setzen` -> `Status setzen (Gestellt/Gemahnt)` und `Status setzen (Gestellt/Gemahnt) und E-Mail verschicken`

## Einzelmahnung auslösen

* [ ] Bei der Invoice-Show-Action kann ich mit dem Button "Rechnung stellen/mahnen" eine Mahnung erstellen, falls die Rechnung den Status "Überfällig" hat.

## Mehrere Mahnungen auslösen

* [ ] Auf der Invoice-Index-Action kann ich mehrere Rechnungen auswählen und mit Button "Rechnung stellen/mahnen" diese Mahnen.

## Logging

*  [ ] Im Statusbereich  der Rechnung erscheinen immer die Daten der letzten Mahnung: `Fällig am` zeigt das Fälligkeitsdatum der Mahnung
* [ ] Eintrag im Log "Rechnung gestellt" wird um Fälligkeitsdatum ergänzt (`Gestellt, fällig 7. Januar 2018`)
* [ ] Bei Mahnung wird ein neuer Logeintrag erstellt: `Gemahnt, fällig 7. März 2018`).

## Statusänderung

* [ ] Wird eine Überfällige Rechnung gemahnt erhält sie neu den Status `Gemahnt ([Titel des Mahnstatus])`
* [ ] Bei der 2. / 3. Mahnung wird automatisch die Mahnstufe erhöht
* [ ] Ist die 3. Mahnstufe erreicht zählen weitere Mahnungen als 3. Mahnstufe

## Anpassungen im PDF / Mail

* [ ] Direkt unter dem Rechnungstitel wird jeweils der Mahntext, wie bei den Einstellungen definiert hinterlegt. 
* [ ] Der Rechnungstitel wird prepended, mit dem Mahntitel und `-` (z. B. "Erinnerung - Rechnung Lager")

## Daten

* [ ] Rechnungsdatum wird wieder auf den heutigen Tag gesetzt
* [ ] Fälligkeitsdatum wird auf heutigen Tag + Zahlungsfrist gesetzt

**Comment by amaierhofer** [comment]
@RolandStuder Sollen die 3 Mahnungstexte als custom_content hinterlegt werden oder machen wir das über locales?

**Comment by RolandStuder** [comment]
Nein 3 Mahnungstexte sind pro Ebene definierbar:

![image](https://user-images.githubusercontent.com/194364/36732872-3c6c33a4-1bcf-11e8-8de2-5e94f12f1501.png)

**Comment by amaierhofer** [comment]
Das originale Fälligkeitsdatum geht leider verloren wenn wir Mahnungen erstellen, entsprechend kann ich das bei der show seite nicht anzeigen.

**Comment by RolandStuder** [comment]
Ja, das ist ok, aber es soll im Log erscheinen:

>  Eintrag im Log "Rechnung gestellt" wird um Fälligkeitsdatum ergänzt (Gestellt, fällig 7. Januar 2018)
