### ISSUE TITLE
Zusätzliche Möglichkeiten im Qualifikationsfilter der PBS fehlen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#443]
Die PBS hat zusätzliche Filter im Wagon, um die Qualifikation genauer einschränken zu können. In der aktuellen Version erscheinen diese nicht mehr. (Auf Produktion sind sie noch vorhanden).

## SOLL:
![image](https://user-images.githubusercontent.com/194364/34999744-d4a04448-fae2-11e7-92f8-1e53f5b46a52.png)

## IST:

- Bereich Qualifikationsjahr fehlt
- Auswahl UND / ODER Filter fehlt

**Comment by RolandStuder** [comment]
Wenn man das korrigiert, darf man das gerne, direkt in den Core bewegen, es gibt keinen guten Grund, das im Wagon zu halten.

**Comment by amaierhofer** [comment]
[Qualifikationsfilter Korrektur.pdf](https://github.com/hitobito/hitobito/files/1758538/Qualifikationsfilter.Korrektur.pdf)

**Comment by amaierhofer** [comment]
Danke fürs PDF. Ich denke die letzte Option ist unnötig (es wird nach allen gesucht). Ich habe mir erlaubt diese wegzulassen. Zeitraum wird nur sichtbar, wenn "alle" ausgewählt wurde.
