### ISSUE TITLE
Rechnungswesen Korrekturen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#444]
## ToFix

* [x] Ich kann Personen nur Rechnung stellen, wenn sie im richtigen Layer erscheinen. Das ist für Kantonalverbände und ähnliche sehr unpraktisch.
* [x] `Rechnungen` sollten in der Topnavigation vor `Einstellungen`erscheinen.
* [x] Kontaktperson unter Einstellungen entfernen. Auf der Rechnung im PDF und Email und Show View aber festhalten, wer die Rechnung erstellt hat.
* [x] Es werden keine e-Mails verschickt für Rechnungen
* [x] Payment Information fehlt auf PDF Rechnung
* [x] Zahlungszweck sollte nur für Orange Einzahlungsscheine erscheinen auf dem Create Invoice Form.
* [x] Auf Liste werden die Rechnung nicht korrekt nach Nummern sortiert. Es wird alphabetisch und nicht numerisch sortiert.
* [x] Die Textareas auf dem Edit Form sind sehr gross 3 Zeilen reichen. (evtl. schon gemacht)

**Comment by KunoKunz** [comment]
[ ] Beim Versand via E-Mail sollte die Absender-Adresse konfiguriert werden können
[ ] Im Text des Rechnungs-E-Mails sollten keine Platzhalter mandatory sein

**Comment by janissbinder** [comment]
Die Absender E-Mail Adresse kann im settings.yml angepasst werden.

**Comment by RolandStuder** [comment]
Der allgemeine e-Mail Absender kann zwar im Settings.yml angepasst werden. Aber Rechnungssettings sind pro Layer. Also sollte das dort konfiguriert werden können. @KunoKunz Ist das noch aktuell?

**Comment by KunoKunz** [comment]
Ja. Sonst macht es m.E. keinen Sinn, dass weitere Rechnungssettings auf den Layers sind.

**Comment by RolandStuder** [comment]
Sollte die Absenderadresse nicht eher die Primäradresse der Person sein, die die Rechnung verschickt?
