### ISSUE TITLE
Contributing.md anlegen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#446]
Sollte enthalten:

* [ ] Vorgaben bezüglich Tests
* [ ] Common Mistakes (die wir schon gesehen haben)
* [ ] Vermerk der Änderung im Changelog

bitte weitere Dinge als Kommentar festhalten.

**Comment by RolandStuder** [comment]
@KunoKunz Dies wäre schon noch sinnvoll, damit wir potentielle Contributors besser abholen. Es ist üblich im Contributing.MD file festzuhalten, was so für Regeln gelten, was zu beachten ist für Pull Requests.

**Comment by olibrian** [comment]
Als Input:
Template: https://gist.github.com/PurpleBooth/b24679402957c63ec426
How to Contribut: https://opensource.guide/how-to-contribute/

**Comment by kronn** [comment]
Ich habe noch das hier gefunden: https://github.com/nayafia/contributing-template

**Comment by olibrian** [comment]
Erster Draft wurde erstellt. Siehe PR #1171
