### ISSUE TITLE
Qualifikationsfilter PBS gibt unerwartete Resultate zurück

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#447]
Wir sind auf einen kleinen Fehler beim Qualifikationenfilter gestossen. Dieser erfüllt seinen Zweck nicht ganz so wie er angedacht wurde.

Problem nachstellen:
 
-  Navigieren zu Gruppe -> Ausbildung -> Weitere Ansichten -> Qualifikationenfilter
-  Eine Qualifikation auswählen und „Abgelaufen zwischen“ auf 2017 bis 2017 setzen (siehe Screenshot „Suchmaske“).
-  Suchen
-  Das Suchresultat enthält auch die Personen mit noch aktiven Qualifikationen (siehe Screenshot „Resultate“). Beispiel: Das zweite Suchresultat im Screenshot ist eine Person mit „J+S Coach bis 31.12.2019“.

Die Idee hinter diesem Suchfeld ist eigentlich, alle Personen zu finden, die beispielsweise seit 2017 keine Qualifikation mehr haben. Diese können dann benachrichtigt werden bezüglich Folgekursen. Diejenigen, die bereits einen Folgekurs besucht haben (und eine aktuelle Qualifikation haben) sind dabei nicht interessant.

Vermutlich wird nur angeschaut, ob eine erteilte Qualifikation abläuft, ohne dass Verlängerungen durch Kurse usw. berücksichtigt werden.

**Comment by amaierhofer** [comment]
Ich warte hier noch auf #443

**Comment by amaierhofer** [comment]
Ich hab den Filter so angepasst, sodass wenn ein Zeitraum gesetzt wird, nur die aktuelle / letzte Qualifikation berücksichtig wird. Ich habe den Eindruck das macht am meisten Sinn.
