### ISSUE TITLE
Korrektur ESR gemäss Testresultat

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#448]
* [x] OCR-B Schrift einbauen
* [ ] Kodierzeile genau positionieren, (ist zu weit links)
* [x] Kodierzeile (10 Zeichen pro Zoll), Abstand zwischen Ziffern einhalten
* [x] Empfangsschein/Verarbeitungsteil/Kodierzeile, richtige ESR Nr. drucken nicht Kontonummer. (Man muss unter Einstellungen neben der Kontonnummer NUR BEI orangen Einzahlungsschein eine Teilnnehmernummer eintragen können, diese wird dann verwendet für die Einzahlungsschiene und nicht die Kontonummer, siehe ESR Doku Seite 40). 
* [x] Referenznummer fehlt auf Empfangsschein und Verarbeitungsteil.

 
- ESR Dokumentation: https://www.postfinance.ch/content/dam/pfch/doc/cust/download/inpayslip_isr_man_de.pdf
- OCR-B Schrift: http://ansuz.sooke.bc.ca/page/fonts#ocrb

**Comment by RolandStuder** [comment]
@amaierhofer 
- OCR-B Schrift brauchst du für die Kodierzeile findest du hier http://ansuz.sooke.bc.ca/page/fonts#ocrb

**Comment by amaierhofer** [comment]
[Testergebnisse](https://github.com/hitobito/hitobito/files/1736719/Dokumentscan.Xerox.pdf)

**Comment by amaierhofer** [comment]
Wir müssen das zusammen anschauen bzw definieren wie ich prüfen kann, dass das jetzt in Ordnung ist. Aktuell lege ich Rechnungen aus dem PDF drüber und prüfe mit Augenmass ob es in etwa passt.

- OCRB Schrift habe ich eingebaut
- Kodierzeile neu positioniert, meiner Meinung nach war die aber zuweit rechts nicht links
- Kodierzeile wurde auf ocrb, font size 10 gestellt, weis nicht wie ich 10 Zeichen pro Zoll setzte ..
- Referenznummer kommt bei mir, eventuell war hier etwas an den Einsstellungen falsch gesetzt?

Den Punkt richtige ESR Nr und nicht Kontonummer drucken muss ich mir noch anschauen.

**Comment by amaierhofer** [comment]
@RolandStuder  Bezüglich richtige ESR Nr, wenn ich das richtig verstehe, dann fehlt hier auch noch ein Feld auf der InvoiceConfig (TeilnehmerNr.) die dann beim roten Einzahlungsschein verwendet werden soll (statt der KontoNr).

**Comment by amaierhofer** [comment]
Bei folgender Rechnung fehlt die Referenznummer https://pbs.puzzle.ch/de/groups/1/invoices/13

**Comment by amaierhofer** [comment]
Referenznummer fehlt noch unter Einbezahlt von auf der linken seite, vergleichen mit Dokumentatiokn Punkt 5.5.1.5

**Comment by KunoKunz** [comment]
Schriftart wird OCR-B1 verlangt.
Kodierzeile ist nun zuweit rechts.

[ESR-Testbericht2.pdf](https://github.com/hitobito/hitobito/files/1761564/ESR-Testbericht2.pdf)

**Comment by amaierhofer** [comment]
Wir haben Inkonsistenzen bezüglich PDF (skalierung) zwischen verschiedene Computern festgestellt. Wir sollten versuchen das PDF auf windows zu drucken und uns daran orientieren um die Kodierzeile zu positionieren. Ich hoffe sys ist am Donnerstag soweit, dass wir die letzten Anpassungen an der Positionierung vornehmen können.
