### ISSUE TITLE
(B)ESR(+) Rechnung per PDF (20h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#45]
https://projects.invisionapp.com/share/S47MIDEDH#/screens/166299090

Rechnungsstellung per PDF mit Bereich für Einzahlungsscheindruck
- Zahlungszweck nimmt den Rechnungstitel
- PDF Darstellung sollte möglichst kompakt sein, damit möglichst die Situation von mehreren Seiten vermieden werden kann.
- PDF Druck ohne B(ESR)+

Referenz:
ESR Punkt 4.8.6: https://github.com/hitobito/hitobito/files/311813/Hitobito_Erweiterung_Rechnung_v0.1.pdf

Wie stellt sich die ESR Nummer zusammen:
https://www.raiffeisen.ch/rch/de/firmenkunden/liquiditaet-und-zahlungsverkehr/zahlungsverkehr/esr-zahlungsbeleg.html

FRAGE:
- Machen das Gruppen tatsächlich mit Druck auf Einzahlungsscheinspapier scheinen, oder legen diese diese einfach vorgedruckte Einzahlungsscheine bei?

**Comment by adriananderegg** [comment]
(B)ESR(+) ((**B**ank) **E**inzahlungs**S**chein mit **R**eferenznummer, orange Einzahlungsscheine) mit dynamischer Generierung der Nummer und Druck auf ESR-Papier bei Rechnungserstellung ist bei grösseren Gruppen im Einsatz, sicherlich aber nicht flächendeckend. (v.a. da ein verbreitet eingesetztes Produkt dies heute kann) 
ESR wird aber ab 2018 durch QR-Codes ersetzt. Dadurch stellt sich bei diesem Enhancement sicher die Kosten/Nutzen-Frage, ob das noch für max. 1-2 Jahre ab Go-Live sinnvoll ist. 

Rote Einzahlungsscheine werden beigelegt. 

Eine Variante ohne Einzahlungsschein (reine Rechnung mit Kontoangaben) müsste sicherlich möglich sein.

**Comment by RolandStuder** [comment]
Potentiell könnte diese Gem eingesetzt werden: https://rubygems.org/gems/vesr

**Comment by KunoKunz** [comment]
* [ ] Bei den Rechnungseinstellungen für  "Oranger Einzahlungsschein Bank" braucht es noch ein Feld für die Identifikationsnummer
* [ ] Die Referenzzeile soll danach gemäss Beschreibung der Raiffeisen aufbereitet werden. 
[Raiffeisen - BESR.pdf](https://github.com/hitobito/hitobito/files/2463833/Raiffeisen.-.BESR.pdf)
