### ISSUE TITLE
Qualifikationen mit 0 Jahren Laufzeit können nicht reaktivierbar definiert werden

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito#458]
Qualifikationen die nur im akutellen Jahr gültig sind (Gültgikeit 0 Jahre) kann nicht als reaktivierbar definiert werden.
Im Kanton Zürich betrifft dies die Suchtpräventionsanerkennung SPOiZ. Dort wird im ersten Jahr ein Grundkurs, in allen weiteren Jahren ein Aufbaukurs besucht. (Das Suchtpräventionsprogramm hat TN aus allen Jugendverbänden, deshalb ist das wohl nicht nur für den Cevi relevant.)

**Comment by RolandStuder** [comment]
@nchiapol  Ist es tatsächlich, so dass wenn ich im Dezember 2017 den Kurs besuche, ich im Januar 2018 keine Anerkennung habe?

Und die andere Frage: Ist die Reaktivierbarkeit überhaupt relevant, da man die Qualifikation quasi jedes Jahr neu erteilt? Also kann man nicht einfach auch bei den Aufbaukurse die Qualifikation erneut erteilen?

**Comment by nchiapol** [comment]
Die SPOiZ Kurse finden alle Anfangs Jahr statt und gelten nur für die aktuelle Kurssaison. 

Natürlich kann ich im Aufbaukurs die Qualifikation neu erteilen, bloss kann ich dann die Anerkennung nicht als Vorbedingung eintragen.

Ich weiss, das ist ein ziemlicher Edge-Case und kein riesiges Problem für uns. Aber ich verstehe nicht, weshalb hier die Funktionalität scheinbar unnötig eingeschränkt ist.

**Comment by RolandStuder** [comment]
@nchiapol OK, danke für die Ausführungen. Es hat jeweils validiert, ob die Gültigkeit der Qualifikation begrenzt wurde. 0 Jahre Gültigkeit machen intuitiv nicht so viel Sinn.

Ich habe die Validierung angepasst und lasse einen Entwickler noch drüber schauen.

**Comment by RolandStuder** [comment]
@nchiapol Ist gefixed und wird mit dem nächsten Release ausgeliefert.
