### ISSUE TITLE
Export von Adresslisten mit einer Adresse pro Haushalt ermöglichen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#461]
![image](https://user-images.githubusercontent.com/194364/36315022-e52092ca-1336-11e8-890a-2a4d0c02b738.png)

* [x] Name -> zusammengefügter Name
* [x] Adresse
* [x] PLZ
* [x] Ort
* [x] Land
* [x] Hauptebene -> einfach die erste Ebene nehmen, die man erwischt, es gibt keine gute Strategie

Beispiele Namen:

Immer nur die die auch im Versand drin sind.
* Ein Export geht on einer Personenliste aus.
* Sind mehrere Personen aus einem Haushalt so werden diese zusammengeführt.
* Sind noch weitere Personen in einem Haushalt, aber nicht auf der Personenliste, werden diese NICHT hinzugefügt.

* Andreas Mäder, Mara Mäder, Ruedi Mäder -> Andreas, Mara und Ruedi Mäder
* Andreas Mäder, Rahel Steiner ->  Andreas Mäder, Rahel Steiner
* Andreas Mäder, Rahel Steiner, Rahel Emmenegger, Blunsch Wyss -> Andreas Mäder, Rahel Steiner … (Limit noch zu definieren)

**Comment by amaierhofer** [comment]
Das Label habe ich jetzt gesehen stimm noch nicht mit dem screenshot überein. Auch habe ich mal bei 40 Zeichen Länge ein Limit definiert, wo für Vornamen nur noch der Anfangsbuchstabe verwendet wird. Das kürzen der kompletten Zeile mit ... ist noch implementiert, da müssten wir noch wissen ab welcher Zeichenlänge.

**Comment by amaierhofer** [comment]
- Undefined Method beim export einer einzelnen Person beheben
- Haushalt export soll nich nur auf der Personen Liste sondern auch bei Abos verfügbar sein

**Comment by Michael-Schaer** [comment]
Beim Export der Personenansicht werden die Haushalte nicht zusammengefasst:

Problem Nachstellen:
-	Folgende Gruppe auswählen: https://pbs.puzzle.ch/de/groups/169/people 
-	Person „Roland Privat“ bei „Roland Studer“ im Haushalt eintragen.
-	Personenansicht 
-	Export -> Excel -> Adressliste
-	Export -> Excel -> Haushaltsliste
-	Die beiden Listen im Mailtrap vergleichen -> Sie sind identisch
