### ISSUE TITLE
Unzustellbare Emails blockieren Mail Versand auf Tenants

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito#466]
Bounces von unzustellbaren Emails führen auf dazu, dass die die Queue verarbeitung blockiert wird. 
Eventuell ist das Problem in neueren Version schon behoben. Bis dahin muss das Email manuell aus der Inbox entfernt werden.

https://errbit.puzzle.ch/apps/592e69e8473b0b009ced0e9f/problems/5a946a1fe80cb100ac4b6f70?notice=20569

**Comment by RolandStuder** [comment]
Wirklich? Das hatten wir doch länger gelöst, oder @psunix? Oder ist das anders, weil es multitenant betrifft?

**Comment by RolandStuder** [comment]
@amaierhofer Ist das jetzt behoben oder nicht?

**Comment by RolandStuder** [comment]
@amaierhofer Ist das jetzt behoben oder nicht? Kann mir nicht vorstellen, dass dies wirklich der Fall ist, sonst wäre der Multitenant wohl dauerblockert, oder? Ich schliesse das Issue, please reopen, falls es doch ein Problem wäre.
