### ISSUE TITLE
Fehlerhaftes Email bei User mit ungültiger Email (3h)

### ISSUE THREAD

**Issue by psunix** [hitobito/hitobito#468]
Wenn ein email an einen ungültige Adresse verschickt wird gibt er SMTP server folgenden Fehler zurück.

 `Net::SMTPSyntaxError: 504 5.5.2 <bla.bli@bluewin>: Recipient address rejected: need fully-qualified address`

- https://errbit.puzzle.ch/apps/529c60a2de77482d71027b0a/problems/5aa014ed6167b9009fa36d46
- https://errbit.puzzle.ch/apps/529c60a2de77482d71027b0a/problems/5aa020916167b9009fa36dc8

Dieser Fehler sollte beim Einzel sowie beim Bulk Mailversand behandelt werden.

**Comment by psunix** [comment]
Net::SMTPServerBusy: 450 4.1.2 <dude@ungueltig-domain.com>: Recipient address rejected: Domain not found 

Es landen immer wieder Exceptions vom Rails Mailer in Errbit wenn die Domain ungültigt ist. Im Bulk Mail berücksichtigen wir diesen Fall. Jedoch bei allen anderen Mailern nicht. z.B. wenn ich jemand neu registrieren will und eine ungültige Mailadresse (Domain) angibt.

Definieren was man im Fall einer ungültigen Maildomain/Adresse macht.

**Comment by RolandStuder** [comment]
Dieser Fehler tritt also jedesmal auf, wenn wir eine ungültige Domain haben. Bei Mailinglisten werden nach wie vor die anderen Adressen korrekt bedient. Allerdings sollten wir in solchen Fällen den Absender informieren und nicht einfach einen einen Fehler erzeugen. oder?

**Comment by kronn** [comment]
Sofern der Absender eine gültige E-Mail hat, könnte man diesen informieren. Bei vom hitobito erzeugten Mails muss man glaube ich mail für mail sehen, wer ein sinnvoller "Absender" im Fehlerfall ist. Wie ist dies beispielsweise bei Anmeldebestätigungen für Anlässe und so?

**Comment by kronn** [comment]
Nach Rücksprache mit @psunix scheint die beste Lösung zu sein, dass wir eine Validierung auf die Person (und alle models, die E-Mails speichern können) setzen. Diese prüft, ob die Mailadresse gültig formatiert ist (also, das hinter dem @ ein FQDN ist) und ob die Domain per DNS erreichbar ist. Andere Fehler bei der Mailadresse werden dann vom Server auf dern anderen Seite beantwortet.

In einem weiteren Schritt könnte ein Rake-Task oder ähnlich erstellt werden, der alle Personen prüft, ob sie auch valide sind und eine Liste der nicht validen Personen liefert. Diese können dann von den Verantwortlichen bei den jeweiligen Vereinen bearbeitet werden. Dieser Rake-Task kann dann natürlich auch für künftige Änderungen/Anpassungen verwendet werden.

Der Absender wird insofern dann immer informiert, wenn eine E-Mail-Adresse ein Problem hat: entweder von hitobito beim Speichern oder vom Mail-Server, wenn das Postfach des Empfängers nicht exisiert oder voll ist.

**Comment by RolandStuder** [comment]
Muss man hier jetzt was machen? Führt dies zu Aufwand bei uns? Für ene Behebung bräuchte es ja offenbar schon ein paar Schritte.
