### ISSUE TITLE
Rechnung Detailansicht (6h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#47]
https://invis.io/S47MIDEDH#/166326248_Rechnung_Detail

Detailansicht:
- Enhält Adresse zum Zeitpunkt der Rechnungsstellung.
- History auf der Rechnung erfasst alle Events:
  - Entwurft erstellt
  - Rechnung gestellt (Email/PDF)
  - Zahlung
  - Teilzahlung
  - Mahnung erstellt
  - Rechnung geändert (ohne Details, was die Änderungen waren)
  - Status geändert

**Comment by amaierhofer** [comment]
- Total (neben Status) soll Total inkl. MWSt. sein
- Erfasste Zahlung soll in übersicht aufscheinen (z.b Zahlung über 10 CHF erfasst)
- Rechnung geändert und status geändert scheinen nicht auf (bedingen model anpassungen)

**Comment by janissbinder** [comment]
In der History müssen nur folgende Punkte aufgeführt werden

- Rechnung gestellt
- Mahnung versendet
- Rechnungsbetrag CHF 1000.- bezahlt
