### ISSUE TITLE
People#log rendert nicht für Einträge mit nicht existierend Klassen

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito#470]
Bei Jubla wurden bestimmten Gruppen Typen z.b `Group::Flock::Alumnus`, `Group::SimpleGroup::Alumnus` entfernt. Papertrail Versions Einträge die solche Gruppen referenzieren können nicht gerendert werden und haben zum Ergebnis, dass die Log Seite bei gewissen Personen einen Fehler hat. Siehe https://errbit.puzzle.ch/apps/51e3cc00de7748233f0007c3/problems/5aa962ed6167b95ef44a3c6f

**Comment by RolandStuder** [comment]
Ist auch bei Abos ein Problem #473

**Comment by amaierhofer** [comment]
Abos gefixed via #480
