### ISSUE TITLE
Berechtigungen für Rolle Coach und Scharbegleitung in der Jubla

### ISSUE THREAD

**Issue by fossil12** [hitobito/hitobito#471]
### Ist

- Kann nicht "Ausbildung" auf Schar sehen
- Kann alle Kinder der Schar sehen
- Export CSV/Excel > SPORTdb nicht möglich, nur allgemeiner Export möglich

### Soll

- Lager bei denen er/sie Coach ist: Teilnehmerliste für SPORTdb exportieren können
- "Ausbildung" auf Schar sehen (wichtig damit der Coach Aus/Weiterbildungen empfehlen kann)
- Nur Kinder in Lagern anzeigen (nicht in der Schar von der er/sie Coach ist)

### Ist

- Kann nicht "Ausbildung" auf Schar sehen
- Kann alle Kinder der Schar sehen
- Kann TN eines Lagers nicht sehen
- Kann Anlässe & Lager sehen, aber nicht Teilnehmerliste (solange nicht angemeldet)

### Soll

- "Ausbildung" auf Schar sehen (wichtig damit die Scharbegleitung Aus/Weiterbildungen empfehlen kann)
- Kann Kinder der Schar nicht sehen
- Kann TN eines Lagers nicht sehen
- Kann Anlässe & Lager sehen, aber nicht Teilnehmerliste (solange nicht angemeldet)

(Die letzen 2 Punkte von Ist und Soll sind schon korrekt.)

**Comment by olibrian** [comment]
Aufgrund des Alters dieses Issue erlaube ich mir dies zu schliessen. Falls es hier noch Anpassungswünsche gibt, einfach melden.
