### ISSUE TITLE
Sortierung auf Anlässen verbessern

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#472]
## IST:

In einer Liste werden die Anlässe, wenn man sie nach Gruppen sortiert, nur nach dem Namen der Gruppe sortiert, ohne den Layer in Betracht zu ziehen.

![image](https://user-images.githubusercontent.com/194364/37516226-ba26e6fe-290d-11e8-9a81-54a82c84a8e2.png)

Siehe Beispiel. Die Reihenfolge ist nicht intuitiv, da z. B. eine Biber Gruppe der Abteilung Schekka zwischen Ebenen oder anderen Gruppen erscheint.

# SOLL:

Sortierung nach `name_with_layer`

**Comment by olibrian** [comment]
Wurde in der Zwischenzeit behoben.
