### ISSUE TITLE
 Entfernen von Gruppen / Rollentypen aus dem Code führt zu Problemen bei Log / Abos / evtl. Filtern

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#473]
Mit der Erweiterung der Ehemaligenverwaltung der Jubla haben wir gewisse Rollen und Gruppentypen aus den Klassendefinitionen entfernt. Solche Änderungen führen zu Problemen, wenn wir dazu keine expliziten Migrationen schreiben, was aber auch inhaltlich nicht unbedingt Sinn macht (ein Log Eintrag zu einem früher existierenden Gruppentyp kann ja nicht wirklich sinnvoll migriert werden.

Wo führt das zu Problemen:
- Abos, da frühere Ehemaligenrollen nicht mehr existieren, siehe z. B. https://errbit.puzzle.ch/apps/51e3cc00de7748233f0007c3/problems/5aab83d96167b9275e19e228
- Logeinträge zu nicht existierenden Rollentypen

Wie kann mit dem umgegangen werden? Diese Herausforderungen werden wir immer wieder haben, eine Lösung nur auf Ebene Migrationen scheint mir kurzsichtig, wir müssen mit verschwindenden Rollen und Gruppentypen generell umgehen können, die Applikation braucht diese Robustheit.

**Comment by RolandStuder** [comment]
Wir haben eine Migration geschrieben, welche entsprechende Abonnenten entfernt. Log ist mit Issue #470 auch gelöst. Aber wir müssen längerfristig schauen, wie wir allgemein damit umgehen, dass Rollen gelöscht werden können und uns dann die entsprechenden Klassen fehlen.

**Comment by RolandStuder** [comment]
@amaierhofer Sehe ich das richtig, das bei Abos dieses Problem weiterhin bestehen wird, dass wenn wir die ein Rollentyp löschen, dass dann Abos welches diese Rolle enthalten fehlschlagen, ausser man hat extra eine Migration dafür.

**Comment by RolandStuder** [comment]
Ein Hinweis in den Guidelines ist hier: https://github.com/hitobito/hitobito/blob/master/doc/development/03_guidelines.md#rollen-umbennen--entfernen

Aber Rollen löschen ist ein Codeeingriff, den jemand halt bis auf weiteres mit der nötigen Vorsicht machen muss.

**Comment by olibrian** [comment]
Dokumentation vorhanden. Aktuell keine weiteren Schritte, Case kommt selten vor.
