### ISSUE TITLE
Kalender Export führt zu 500 Fehler

### ISSUE THREAD

**Issue by fossil12** [hitobito/hitobito#475]
Wenn ich [hier](https://db.jubla.ch/groups/146/events/simple) den Kalender Export auf der Anlassliste oder einem einzelnen Anlass machen will bekomme ich folgenden einen 500 Fehler:

```
500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.
```

**Comment by RolandStuder** [comment]
Siehe entsprechenden errbit Fehler: https://errbit.puzzle.ch/apps/51e3cc00de7748233f0007c3/problems/5aaa2cc26167b95ef44a4469

**Comment by RolandStuder** [comment]
Gemäss @amaierhofer bereits gefixt.
