### ISSUE TITLE
[Jubla-wagon] Hinzufügen einer aktiven Rollen zu einer Ehemaligen Person kann zu eine Fehler führen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#477]
Füge ich auf der Show Action der Person **von einer Group::Alumnus** https://jubla.puzzle.ch/groups/123/people/15 , einer Person eine neue aktive Rolle hinzu, z. B. für Verbandsleitung - Präses...

Dann wird automatisch korrekterweise die bestehende Ehemaligenrolle entfernt. Nach dem hinzufügen der Rolle, will die Applikation zurück auf die Show Action im Kontext der Ehemaligengruppe, wo die Person jetzt keine Rolle mehr besitzt, dies führt zu einem Fehler.

Allgemein sollen solche Fälle besser gerettet werden. Wenn eine Person existiert, einfach keine Rolle mehr im entsprechenden Kontext hat, so sollte ein alternativer Gruppen-kontext gefunden werden. Solche Fehler hatten wir  nämlich schon einige Male.

**Comment by olibrian** [comment]
So nicht mehr nachvollziehbar. Ich schliesse mal dieses Ticket.
