### ISSUE TITLE
[jubla-wagon] Falsche Ehemaligenlisten

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#479]
> Ich wurde gerade darauf aufmerksam gemacht, dass hier jemand auf mehr
> als 1900 Personen Zugriff hat. Bei mir sind es sogar über 2200. Die
> Details der Personen kann ich aber nicht einsehen. Da bekomme ich einen
> 500er error.
> Hier die Gruppe: https://db.jubla.ch/groups/425/people?filter_id=416

![image](https://user-images.githubusercontent.com/194364/37599321-be5f75be-2b84-11e8-8e2d-49e147d826d3.png)

- [ ] Diesen Fehler bitte korrigieren
Das ist inhaltlich nicht plausibel, da dies ja bei einer Schar ist.

Es kommen weitere Fehler hinzu, siehe unten

**Comment by RolandStuder** [comment]
Filter funktioniert in verschiedenen Situationen nicht korrekt.

Z. B. Filter Ehemalige gibt für eine Untergruppe 17 Personen zurück: https://jubla.puzzle.ch/groups/3/people?filter_id=8

Mache ich in der übergeordneten Ebene einen Filter der die Untergruppe einschliesst findet, der nur 6 Personen. siehe https://jubla.puzzle.ch/groups/1/people?filter_id=166

**Comment by RolandStuder** [comment]
Komisch ist, dass auf pbs.puzzle.ch das Verhalten anders ist, aber auch nicht korrekt.

2 gelöschte Rollen, werden nicht gefunden:
https://pbs.puzzle.ch/de/groups/579/people?filters%5Brole%5D%5Bfinish_at%5D=&filters%5Brole%5D%5Bkind%5D=deleted&filters%5Brole%5D%5Brole_type_ids%5D=116-117&filters%5Brole%5D%5Bstart_at%5D=&name=Ehemalige&range=group

Darüberliegend ein Filter findet sie dann korrekt:

https://pbs.puzzle.ch/de/groups/578/people?filter_id=37

**Comment by RolandStuder** [comment]
Siehe auch hier: Roland Studer wird gefunden, obwohl Rolle nicht gelöscht ist und keine Rolle hatte, die gelöscht wurde https://jubla.puzzle.ch/groups/39/people?filter_id=44

Hier erscheinen die gelöschten Personen nicht: https://jubla.puzzle.ch/groups/115/people?filter_id=120 z. B. https://jubla.puzzle.ch/groups/127/people/955 war in der Gruppe

Bei Filter in übergeordneter Rolle werden die gelöschten drei Rollen aber dann gefunden: https://jubla.puzzle.ch/groups/39/people?filter_id=167

Wenn ich darüber nachdenke, ist evtl. das Problem, dass der Zugriff im falschen Moment überprüft wird? Im Sinne von, der Query schaut nach der Grundmenge der Accessibles in dieser Gruppe (die null ist, weil dort keine aktive Rollen ist, und dass er erst dann schaut, welche davon gelöschte Rollen haben bezüglich dieser Gruppe). Dann würde das auf dem Layer funktionieren, weil dort gehören die Personen zu den Accessibles, weil sie eine Rolle Ehemalige::Mitglied haben.

**Comment by amaierhofer** [comment]
Eventuell kommen hier mehrere Dinge zusammen. Das im ersten Eintrag beschriebene Problem entsteht aufgrund konnte ich wie folgt im lokal mit dem generic Wagon reproduzieren.

- Neuen Filter in der Region Bern / Geschäftsstelle anlegen
- In der aktuellen Gruppe und allen darunter liegenden Gruppen auswählen
- Keine weitere Auswahl (Rollen, Zeitraum) treffen

![2018-03-30-135309_1920x1186_scrot](https://user-images.githubusercontent.com/180780/38136891-beaccfbc-3421-11e8-9699-caa3ed339902.png)

**Comment by RolandStuder** [comment]
@amaierhofer konnte den Fehler lokal nicht herstellen. Ist schwierig zu beurteilen, aber du konntest ja den Fehler reproduzieren und fixen. Müssen wir halt ausprobieren.

Was etwas unschön ist, ich kann ein Datum festlegen ohne Rollen zu wählen, gefiltert wird ohne Berücksichtigung des Datums. Könnte man da noch eine Warnung einbauen?

**Comment by RolandStuder** [comment]
@amaierhofer Besser als eine Warnung wäre die Berücksichtigung der Option, siehe #510
