### ISSUE TITLE
Zahlung erfassen (8h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#48]
https://invis.io/S47MIDEDH#/166326248_Rechnung_Detail
- Zahlung erfasst führt zu Dialog, Default Wert ist voller Betrag
- Wird das bestätigt so wechselt der Status bei voller Bezahlung automatisch auf Bezahlt, sonst bleibt der Status

**Comment by amaierhofer** [comment]
@RolandStuder  aktuell sieht das model vor, dass das Eingangsdatum einer Zahlung null sein kann. Macht das aus deiner Sicht sinn? Wir fänden besser, wenn das ein Pflichtfeld werden würde.

**Comment by amaierhofer** [comment]
Eingangsdatum ist jetzt ein Pflichtfeld
