### ISSUE TITLE
openshift: delayed job auf STDOUT loggen

### ISSUE THREAD

**Issue by psunix** [hitobito/hitobito#484]
momentan wird der log-output in das File logs/delayed_job.log geschrieben.

damit auf Openshift die Logs ersichtlich sind müssen diese auf STDOUT geschrieben werden.

RAILS_LOG_TO_STDOUT=1

https://github.com/hitobito/hitobito/blob/master/config/environments/production.rb#L52

Logger für production entsprechend konfigurieren. Wenn RAILS_LOG_TO_STDOUT gesetzt, auf STDOUT loggen.

Bei Rails 5 haben wir das so gemacht:

config/environments/production.og

`  if ENV["RAILS_LOG_TO_STDOUT"].present?
    config.logger = ActiveSupport::TaggedLogging.new(Logger.new(STDOUT))
  end
`

prüfen ob das so auch mit Rails 4 klappt.

dann bei allen Openshift Projekten bei den DJ-DeploymentConfigs die Umgebungsvariable RAILS_LOG_TO_STDOUT=1 setzen

**Comment by RolandStuder** [comment]
Ok, dann nach Update auf Rails5 machen. nach #546
