### ISSUE TITLE
Überschreiben von Adressen in gewissen Fällen mit Haushaltsadressierung möglich

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#488]
## Zum Reproduzieren

* Bearbeite Person A
* Person ist bereits in Haushalt 1
* Füge bei Person A Haushalt 2 hinzu (auf Haushalt 2 habe ich nur Leseberechtigung auf eine der Personen.
* Wichtig: Füge nun noch eine Person B hinzu, auf die ich Schreibberechtigung habe.
* Ändere die Adresse
* Speichere

IST: Die Adresse von allen Personen wird aktualisiert.

SOLL: Die Aktion sollte einen Fehler erzeugen, weil ich auf eine Person keine Schreibberechtigung habe.

**Comment by amaierhofer** [comment]
@RolandStuder  Ich konnte das Problem leider nicht nachstellen. Kannst du es bitte anhand konkreter Personen in der Demo Umgebung beschreiben?

**Comment by smathys** [comment]
Hallo @RolandStuder 
Carbon (@nchiapol) hat gestern noch getestet, und das reproduzieren des Bugs folgendermassen beschrieben:

-------------------------------------------------------------------------------------------
    • Ich kann Person zu einem Haushalt hinzufüge, auch wenn ich keine Schreibrechte habe. Dafür öffne ich eine Person im Haushalt auf der ich Rechte habe und füge dann neue Personen hinzu.
Bei der Person ersten die ich so hinzufüge, wird die Adresse des Haushalts der neuen Person angepasst. (ohne Warnung, mit «abbrechen» kann ich die Änderung aber verwerfen).
Bei der zweiten Person wird die Adresse der neuen Person geändert obwohl ich dort keine Schreibrechte habe.
--------------------------------------------------------------------------------------------

**Comment by smathys** [comment]
wir haben es nochmals getestet und können den Fehler nicht mehr reproduzieren, scheint also gelöst und kann geclosed bleiben
