### ISSUE TITLE
Mailmonitoring (6h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#491]
Die Catch All Adressen müssen monitored werden, damit Probleme frühzeitig bemerkt werden, wenn die Mailzustellung nicht mehr funktioniert.

- Einerseits sollte gewarnt werden, wenn das älteste Mail älter als 30min oder 1h ist.
- Andererseits sollte geschaut werden, wie viele Mails nicht weiterverarbeitet werden.

Lieber jetzt etwas strenge Regeln setzen, mit false positives und später die Toleranz erhöhen.

**Comment by RolandStuder** [comment]
@psunix Ist die Ruby Lösung nicht auch problematisch, weil sie sich ja nicht selbst überwachen kann. Es braucht ja quasi einen Job um aktuell zu überprüfen, ob jetzt Mails in der Inbox rumliegen, die nicht verarbeitet werden. Was wenn das aber ist, weil ein anderer Job das ganze System auslastet? Wie kann dann gewährleistet werden, dass der Monitoring Job sauber läuft?

**Comment by psunix** [comment]
@RolandStuder dieses Monitoring würde über einen HTTP-Endpoint getriggert werden und würde im Rails Container laufen. Einen Delayed Job würde ich dafür nicht vorsehen. 
Falls /sys die Möglichkeit hat das Postfach direkt aus Icinga aus zu monitoren, wäre das natürlich auch eine Option.

**Comment by RolandStuder** [comment]
@: Ah logisch, mit http-Endpoint ist das dann ja kein Problem.

**Comment by RolandStuder** [comment]
Ist gemacht, es muss aber überall wo deployed wird, noch im ICINGA überwacht werden, dokumentation https://github.com/hitobito/hitobito/blob/master/doc/betrieb/02_health_checks.md
