### ISSUE TITLE
Bulkmailsversand für grosse Versände unzuverlässig

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#492]
Erneut schlug  ein Bulk-Emailversand fehl, betroffenes Abo:

https://db.scout.ch/de/groups/179/mailing_lists/2391

Wegen der neuen Zustellungsart hat sich der Verhalten verändert, aber nicht verbessert. Offenbar hat der Job immer wieder versucht durchzulaufen und so gewissen Personen, das Mail bis zu 50 Mal verschickt.

Die muss prioritär gelöst werden.

**Comment by amaierhofer** [comment]
Möglicherweise der zugrunde liegende Fehler im Errbit, https://errbit.puzzle.ch/apps/529c60a2de77482d71027b0a/problems/5ab3bf2a6167b9357ca10030

**Comment by psunix** [comment]
laut der exception die wir im Errbit erhalten haben ist nicht das Senden selber fehlgeschlagen sondern das anschliessende Löschen der Nachricht vom POP3 Postfach. 
Dieses Problem wäre vermutlich auch aufgetaucht ohne das neue Bulk Mail.
Versuche nun rauszufinden was genau zu dem EOF Error beim Löschen der Nachricht geführt haben könnte.

**Comment by RolandStuder** [comment]
Problem wird adressiert durch #498
