### ISSUE TITLE
Export Anlässe xls/csv Haushalte werden nicht zusammen gefasst

### ISSUE THREAD

**Issue by smathys** [hitobito/hitobito#494]
Bei einem Anlass wenn man die Teilnehmer exportiert, werden die Haushalte nicht zusammen gefasst

siehe Testfall : 
https://cevi.puzzle.ch/groups/329/events/1072/participations

[event_participations_export.zip](https://github.com/hitobito/hitobito/files/1842651/event_participations_export.zip)

betrifft: https://github.com/hitobito/hitobito/issues/218

**Comment by RolandStuder** [comment]
@smathys Wenn wir das machen, dann können wir nur eine reine Adressliste herauslassen, dass sich ja Daten aus dem Anmeldeformular nicht so einfach zusammenfügen lassen.

Wäre das so ok?

**Comment by smathys** [comment]
@RolandStuder ja das ist so okay.
