### ISSUE TITLE
Mail Abo Catch All Model mit Log

### ISSUE THREAD

**Issue by psunix** [hitobito/hitobito#498]
der Versand der Abolisten-Mails wird heute nur über die Logfiles und nicht im Detail protokolliert.
Ausserdem merkt sich das System auch nicht welche Mail an welche Adresse bereits gesendet wurde. So kam es vor ein paar Tagen dazu das eine Mail 65x an die gleichen 2600 Empfänger gesendet wurden da der Job nie komplett durchlief weil es zu einer Exception beim Löschen der Nachricht im Catch-All-Konto kam. 

# 1. MailLog

Neues Model: MailLog
id, mailinglist_id, mail_hash, (succeeded_recipients), (failed_recipients), mail_subject, mail_sender,
status, created_at, updated_at (DateTime)

Verhindern das das gleich Mail an einen Empfänger mehrmals gesendet wird:

Ausbaustufe 1 (8+)

- Wir halten fest ob ein Mail verarbeitet worden ist.
- Der Job für Mailinglists überprüft, ob das Mail schon man verarbeitet wurde, wenn ja, wird kein neuer Job dazu mehr angelegt
- Skip Mails, so dass weitere Mails verarbeitet werden können, und ein altes nicht die Job Queue blockiert.

Ausbausstufe 2 (+6h)

- Wir halten während dem Bulkmailing fest, an wen schon das Mail verteilt worden ist.
- Bulkmail prüft dann beim Versenden, ob dem Empfänger das Mail schon zugestellt worden ist oder nicht.
- Beim Senden prüfen ob die Adresse nicht bereits im MailLog unter succeeded oder failed recipients eingetragen

**Comment by RolandStuder** [comment]
Sendeprotokoll wäre natürlich schön, müsste aber sicher anonymisiert sein, weil das zum Teil ja für interne Kommunikation benutzt wird. Das schränkt dann auch die Nachvollziehbarkeit ein. Oder man müsste das per Option aktivieren lassen.

Sendeprotokoll hat sicher erst zwei Priorität.

**Comment by RolandStuder** [comment]
Ausbaustufe 1 ist gemacht und bei PBS deployed. Ausbausstufe 2 ist im Moment nicht vorgesehen, wir fokusieren jetzt auf die Mailchimp Integration
