### ISSUE TITLE
Auf Personenansicht auch abgelaufene Rollen unter Ehemalige Rollen abbilden (1h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#499]
- Nur für Rollentypen, die wir als aktiv betrachen, die also auch eine Ehemaligenrolle generieren bei Löschung.

**Comment by amaierhofer** [comment]
Ich verstehe nicht genau was hier gemeint ist. Die Jubla Rollen haben meines Wissens kein Ablaufdatum (das gibt es nur bei PBS). Was genau meinst du mit abgelaufenen Rollen?

**Comment by RolandStuder** [comment]
Doch die Rolle wird ja nicht gelöscht, sonst gäbe es keinen Verlauf. Es sollten einfach alle aktiven Rollen aufgelistet werden, die "gelöscht" wurden.

**Comment by amaierhofer** [comment]
Willst du diese gelöschten Rollen mit den Ehemaligen in der gleichen Liste darstellen oder sollen wir diese separat ausweisen?
