### ISSUE TITLE
Einfügen einer neuen Gruppe setzt ebenfalls das Änderungsdatum anderer Gruppen

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito#5]
Fügt man eine neue Gruppe irgendwo in der Hierarchie ein, so wird bei allen Regionen und Abteilungen und dem Kanton innerhalb des Kantons, wo die neue Gruppe eingefügt wurde, das Änderungsdatum angepasst.

Reproduziert auf dem PBS Testsystem:
Erstellt Gruppe id = 360 im Kanton Bern 26.11.2014 22:34
Sämtliche Gruppen im Kanton kriegen ein neues Änderungsdatum, z.B. id = 24
Einige Kantone (z.B. id = 332) sind nicht betroffen, andere aber schon (z.B. id = 156)

**Comment by codez** [comment]
Fixed
