### ISSUE TITLE
Bei Release temporäre Tabellen löschen (gemäss Viehweger)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#502]
> grosse Exporte benötigen in MySQL (aber auch anderen DBs) temporäre Tabellen. Diese werden im Dateisystem abgelegt und je nach DB unterschiedlich behandelt. MySQL 5.7 nutzt hierfür eine ibtmp-Datei, die in der default-Einstellung bei 12MB anfängt und bei Bedarf wächst, leider unbeschränkt. Die Datei wird dabei nur grösser, aber nicht wieder kleiner. 
> 
> Die kurzfristige Lösung ist, die Datei zu löschen und den DB-Server neuzustarten.

PV war voll und musste vergrössert werden.

**Comment by kronn** [comment]
Ist erledigt
