### ISSUE TITLE
SendAddRequestJob: Check if Person has email address

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito#504]
Error in Mailer if Person (in #ask_person) does not have an email address:

ArgumentError: An SMTP To address is required to send a message. Set the message smtp_envelope_to, to, cc, or bcc address.

https://errbit.puzzle.ch/apps/529c60a2de77482d71027b0a/problems/5aba578c6167b91702343834

**Comment by RolandStuder** [comment]
Sollte man den Fall von fehlender E-Mail Adresse nicht allgemein abhandeln können, dies hatte z. B. beim Impersonation Feature #356 auch dazu geführt, dass bei fehlender E-Mail Adresse die Impersonierung fehlschlägt.

**Comment by codez** [comment]
The same happens for the SendLoginJob: https://errbit.puzzle.ch/apps/5970547ebd44b8009c944c8f/problems/5aba10c26167b917023436e0
