### ISSUE TITLE
Fehler beim Drucken einer Rechnung mit Einzahlungschein

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito#507]
siehe https://errbit.puzzle.ch/apps/5970547ebd44b8009c944c8f/problems/5ab15f746167b9357ca0f2ca

NoMethodError: undefined method `split' for nil:NilClass
app/domain/invoice/payment_slip.rb:53→ last_code_line_block
app/domain/invoice/payment_slip.rb:30→ code_line

PaymentSlip rechnet mit einer participant_number die für nicht ESR (ch_es, ch_bes) Rechnunge nicht nicht gesetzt wird.

**Comment by RolandStuder** [comment]
Betrachte das als abgenommen, weiss nicht wie ich es reproduzieren könnte.
