### ISSUE TITLE
Travis Build failen mit mysql2 Gem Issue

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito#508]
Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile.

**Comment by kronn** [comment]
Ich habe die Travis-config angepasst. Da wir in allen Umgebungen neuere Ruby-Versionen haben und das gleiche mysql2-gem verwenden können, konnte mit https://github.com/hitobito/hitobito/commit/4b8f07e4dac25f3d059943a353655308cd8d2d82 der entsprechende Workaround für Travis entfernt werden.
