### ISSUE TITLE
Status anpassen (2h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#51]
- Bei Fehlmanipulationen sollte der Status manuell angepasst werden können.

**Comment by janissbinder** [comment]
@RolandStuder Sollte es wirklich möglich sein jeden Status anzupassen? Es ist nicht wirklich sinnvoll, dass eine bereits versendete Rechnung wieder Editierbar wird.

**Comment by RolandStuder** [comment]
@janissbinder  Ich würde aktuell sagen, ja. Versendete Rechnung können z. B. Fehler haben. Das kann auch noch im Status Bezahlt noch Probleme geben, wo man nachträglich Sachen ändern muss.
