### ISSUE TITLE
Export von Adresslisten via Mail - Auswahl der Mail-Adresse

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#513]
Rückmeldung eines Benutzers:
> Ich habe jetzt gerade gemerkt, dass das Mail an alle drei meiner Mail-Adressen gesendet wurde, auch wenn mir die MiData meldet:
> „Export wird im Hintergrund gestartet und nach Fertigstellung an tobiasjuon@gmail.com versendet.“

**Comment by RolandStuder** [comment]
Braucht es eine Auswahl, oder wäre es einfacher einfach das ganze an die Hauptemailadresse zu verschicken?

Plus es wäre sowieso sinnvoll den Default für E-Mailadressen so zu setzen, dass Versand NICHT ausgewählt ist, oder?

**Comment by RolandStuder** [comment]
Ist nicht länger aktuell, da jetzt Export im Hintergrund erfolgen und nicht mehr per Mail zugestellt werden.
