### ISSUE TITLE
Hilfe zum ersten User zu gelangen bei einer neuen Installation

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#515]
Wenn ich hitobito lokal aufsetze, ist nicht klar, wie ich zum ersten User komme, was da geseeded wird und wie ich mich einloggen kann.

Besser wäre

1. Immer einen root-benutzer automatisch zu erstellen.
2. Benutzerlogin und Passwort anzeigen als Willkommensnachricht

Oder vielleicht eleganter eine extra "Setup" Action, wo ich den ersten Benutzer festlegen kann, wenn es noch keinen gibt und dort gleich ein Passwort wählen kann.

**Comment by olibrian** [comment]
Wurde im Development Repo beantwortet: https://github.com/hitobito/development/issues/3
