### ISSUE TITLE
Lager im Kanton XX entspricht nicht erwarteter Liste

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#517]
Der Filter auf Kantonen im PBS Wagon gibt nicht die erwarteten Resultate zurück.

z. B.  gibt Durchgeführt im Kanton BE keine Lager zurück, siehe: https://db.scout.ch/de/groups/4/events/camp?filter=canton&returning=true

Obwohl es klar solche Lager gibt, z. B. 
https://db.scout.ch/de/groups/1358/events/2438

Beim Kanton Jura kommen aber dann sehr viel Lager.

https://db.scout.ch/de/groups/911/events/camp?filter=canton&returning=true&year=2017

Vielleicht filtern wir diese nicht korrekt. Es gab einen Filer für gewisse Rollen auf dem Kanton, welche denen bald und aktuell stattfinden Lager im eigenen Kanton anzeigt. Und wir haben fälschlicherweise alte Einschränkungen übernommen, aus

>  Wähle ich diesen Scope so erscheinen alle Events, welche als Durchführungskanton eben [Kantonskürzel haben] (eine ähnliche View gibt es bereits für Kantonsverantwortliche: https://pbs.puzzle.ch/de/list_camps_in_canton?canton=be (allerdings machen wir sie hier ohne Einschränkung nach Durchführungsdatum oder Status oder Einreichung)

aus #393 

## Noch offen

* [ ] Sollen nur Lager von auserkantonalen Abteilungen angezeigt werden oder alle (durchgeführt in Bern: Soll dies auch Lager von Berner Abteilungen im Kanton Bern anzeigen?)

**Comment by RolandStuder** [comment]
@Michael-Schaer Sollen nur Lager von auserkantonalen Abteilungen angezeigt werden oder alle (durchgeführt in Bern: Soll dies auch Lager von Berner Abteilungen im Kanton Bern anzeigen?)

**Comment by RolandStuder** [comment]
Ok, Problem gefunden:

Bei den Kantonen, wo es nicht funktioniert sind die Kantone nicht richtig konfiguriert. Z. B. ist bei Kanton Solothurn keine relevanter Kanton hinterlegt:
![image](https://user-images.githubusercontent.com/194364/38419865-41c1ad5c-39a2-11e8-8a50-13e4544a4e69.png)

Bei jedem Kantonalverband muss festgelegt werden, welche Kantone zu ihm gehören. Das wurde so gemacht, da gewisse Kantone keinen eingen Kantonalverband haben (oder hatten), also kann man z. B. für den Kantonalverband Appenzell sowohl Innterrhoden sowieo Ausserrhoden auswählen. Deshalb erscheinen beim Kanton Jura auch die Lager vom Kanton Bern und vom Kanton Jura.

Jetzt bräuchten wir Feedback von euch, ob das schon immer so konfiguriert war, oder ob ihr den Eindruck habt, dass das fälschlicherweise von uns irgendwie angepasst wurde. Meine Vermutung ist, dass das nie konfiguriert wurde, weil es glaube ich bisher nur Einfluss hatte auf die eine bestimme Liste unter Lager:

![image](https://user-images.githubusercontent.com/194364/38420081-f073a134-39a2-11e8-9949-43569482dbee.png)

Kann hier den Link nicht gut teilen, weil die Liste nur für bestimmte Rollen für jeweils ihren Kanton freigeschaltet ist: z. B. https://pbs.puzzle.ch/de/list_camps_in_canton?canton=be Meine Vermutung ist meine, dass diese Liste einfach kaum genutzt wurde oder vielleicht gar nicht bekannt war bei den entsprechenden Personen.

Die guten News sind daher, dass ihr einzig bei den Kantonalverbänden auf Bearbeiten gehen müsst, und dort die Kantone eintragen müsst und dann funktioniert das ohne Anpassung vom Code.

Ich schliesse damit dieses Issue.

@michael-schaer

**Comment by Michael-Schaer** [comment]
Danke für das Update. Bitte noch überprüfen, wie die Logik genau umgesetzt ist. Also ob es ausser des Kantons noch andere Filter gibt.

Anzeige aller Lager im Kanton (auch von Abteilungen in Bern) ist meiner Meinung nach korrekt.

**Comment by RolandStuder** [comment]
@Michael-Schaer Nein, es gibt keine weiteren Filter. Verhält sich genau gleich wie sonst der Rest der Anlasslisten auch.
