### ISSUE TITLE
Emails von Testinstallation können nicht mehr abgerufen werden

### ISSUE THREAD

**Issue by fossil12** [hitobito/hitobito#522]
Emails welche von der [Testinstallation](http://jubla.puzzle.ch/) versendet werden kommen nicht mehr bei mailtrap an. Somit können z.B. keine neuen Testaccounts mit Login versehen werden.

**Comment by kronn** [comment]
Der Mail-Server von mailtrap hat sich geändert. Die Konfiguration ist angepasst, es sollte nun wieder funktionieren.

**Comment by fossil12** [comment]
@kronn Danke. Gerade getestet. Es funktioniert wieder.
