### ISSUE TITLE
Anführungszeichen im Anlasstitel kann zu fehlerhaftem E-Mailversand führen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#523]
Zum Reproduzieren:

* Neuen Anlasse erstellen
* Titel mit Anführungszeichen verwenden `Hier "ist" was kapuut`
* Sich beim Anlass anmelden
* Anmeldebestätigung ansehen

Die Anmeldebestätigung sieht dann wie folgt aus:

![image](https://user-images.githubusercontent.com/194364/38689192-3cc72a92-3e7b-11e8-8757-810c13e94d77.png)

RAW Email:

````
Date: Thu, 12 Apr 2018 17:46:36 +0200
From: noreply@cevi.puzzle.ch
To: studer@puzzle.ch
Message-ID: <5acf7f5c30191_1051f98c3937@delayed-job-41-z0jf4.mail>
Subject: =?UTF-8?Q?Best=C3=A4tigung_der_Anmeldung?=
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit


--
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<div>Hallo Roland<br></div><div><br>Du hast dich f=C3=BCr ein Angebot ang=
emeldet. Die Details dazu findest du unten sowie im PDF im Anhang.</div><=
div><br></div><div>Falls f=C3=BCr die Anmeldung zu diesem Angebot zus=C3=A4=
tzliche Unterschriften n=C3=B6tig sind, enth=C3=A4lt das PDF entsprechend=
e Unterschriftszeilen. Druck in dem Fall das PDF aus, und schicke es unte=
rschrieben per Post oder E-Mail zur=C3=BCck.</div><div><br>"Was ist gut?<=
br/><br/>Daten:<br/>01.12.2018<br/><br/>Teilnehmer/-in:<br/><strong>Rolan=
d Studer / hito-bito</strong><p>49075 Jaylan Fall<br />5106 Dockhaven</p>=
<p><a href=3D"mailto:studer@puzzle.ch">studer@puzzle.ch</a></p></div><div=
><br></div><div>Falls du ein Login hast, kannst du deine Anmeldung unter =
folgender Adresse einsehen:&nbsp;</div><div><a href=3D"http://cevi.puzzle=
.ch/groups/1/events/1077/participations/127538">http://cevi.puzzle.ch/gro=
ups/1/events/1077/participations/127538</a></div><div><br></div><div>Mit =
lieben Gr=C3=BCssen</div><div>Deine Cevi.DB</div>=

--
Content-Type: application/pdf
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=""Was ist gut?_Roland Studer.pdf"
Content-ID: <5acf7f5c306b7_1051f98c39452@delayed-job-41-z0jf4.mail>

JVBERi0xLjMKJf////8KMSAwIG9iago8PCAvQ3JlYXRvciA8ZmVmZjAwNTAw
MDcyMDA2MTAwNzcwMDZlPgovUHJvZHVjZXIgPGZlZmYwMDUwMDA3MjAwNjEw
...
dCAyIDAgUgovSW5mbyAxIDAgUgo+PgpzdGFydHhyZWYKMjQxOAolJUVPRgo=

----
````

Interessanterweise wird hier das e-Mail als `content-type: text/html`deklariert, bei korrekt versendeten Anmeldebestätigungen ist diese `multipart/mixed`

* [ ] Frage: Wieso taucht dies erst jetzt auf? Auch konnte in den Fehler nicht immer reproduzieren, vor drei Tagen habe ich auf Cevi Integration den Fehler nicht provozieren können:

````
Date: Mon, 09 Apr 2018 16:06:43 +0200
From: noreply@cevi.puzzle.ch
To: studer@puzzle.ch
Message-ID: <5acb7373364ed_1051f98c37395@delayed-job-41-z0jf4.mail>
Subject: =?UTF-8?Q?Best=C3=A4tigung_der_Anmeldung?=
Mime-Version: 1.0
Content-Type: multipart/mixed;
 boundary="--==_mimepart_5acb737335d23_1051f98c37272";
 charset=UTF-8
Content-Transfer-Encoding: 7bit


----==_mimepart_5acb737335d23_1051f98c37272
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable
...
````

**Comment by RolandStuder** [comment]
Das Issues kommt daher, dass das Attachment im Filename ein Anführungszeichen enthält.

Der Filename wird unter anderem aus dem Eventnamen erstellt und nicht vom ActionMailer korrekt abgehandelt:

Erstellung des Namens:

https://github.com/hitobito/hitobito/blob/fbe41b5a2ff6c8e21ed893f2b3c82c000af784f9/app/domain/export/pdf/participation.rb#L45

Zuweisung als Attachment:

https://github.com/hitobito/hitobito/blob/fbe41b5a2ff6c8e21ed893f2b3c82c000af784f9/app/mailers/event/participation_mailer.rb#L22

**Comment by RolandStuder** [comment]
So das kann also bei irgendeinem Mail mit Attachement zu diesem Problem führen. Aktuell haben wir dies aber wohl nur bei den Participations. 

@kronn Wie flickt man das korrekt, dass das auch in Zukunft überall korrekt klappt, z. B. mit Listenexporten oder Rechnungen. Allgemein sollten bei der Zuweisung eines Attachments die Dateinamen so bereinigt werden, dass sie auch korrekt verarbeitet werden.

Ich habe noch etwas gegraben:

Meine Vermutung ist, dass der Check für `has_attachments?`vom ActionMailer failed, deshalb auch der falsche Content-Type.

https://github.com/rails/rails/blob/6003dafc1f844275d6a7fe9e626eaeb1176c8e8a/actionmailer/lib/action_mailer/base.rb#L861

Check, ob das Mail ein Attachment hat:

https://github.com/rails/rails/blob/4bd80f110d41a02ddc76212a92b5367541e6bce7/actionmailer/lib/action_mailer/vendor/tmail/attachments.rb#L9

Ich hätte es gerne selbst geflickt. Ich vermute mal, dass wir die Methode `attachments` im ApplicationMailer anpassen sollten. Weiss aber nicht genau wie man das mit Argumenten handhabt.

**Comment by kronn** [comment]
Aktuell ist es so, dass wir den Filename nicht speziell behandeln. 

Rails selbst bietet nur ein einfach zu verwendendes, aber nicht übermässig magisches Interface an, um die Attachments hinzuzufügen. Es ist hier der Anwendung überlassen, das nicht falsch zu verwenden.

Das zukunftssicherste ist vermutlich eine helper-method dem hitobito-`ApplicationMailer` hinzuzufügen, die den Namen des Attachments von Zeichen bereinigt, die in Dateinamen nicht gut unterstützt werden. Wenn wir das Interface von Rails beibehalten wollen, müssten wir einen Attachment-proxy erstellen, der `[]=` implementiert und dann den bereinigten Namen an Rails' `attachment` weiterreicht.

**Comment by amaierhofer** [comment]
Ich bezweifle, dass der Benefit den Aufwand rechtfertigt und auch dass die Helper Methode konsequent verwendet werden würde. Anstelle würde ich sicherstellen, dass Dateinamen die wir generieren auch "mail tauglich" sind.
