### ISSUE TITLE
Performance von Anzeige & Export von Teilnehmerlisten Analyse

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#525]
Beim Jamboree Lager der PBS haben sich Performance Probleme merklich gemacht. Trotz Pagination geht der Aufruf der Seite ca. 5-7 Sekunden.

Der Export von 1000+ Teilnehmern geht ca. 10 Minuten.

Wir wollen eine Analyse machen.

Gerne würde die PBS das Bundeslager im 2021 mit bis zu 30'000 Mitgliedern die Anmeldung über die MiData machen lassen. Deshalb müssen wir das anschauen, wo die Engpässe liegen.

**Comment by janissbinder** [comment]
Ich habe mir das ganze einmal angesehen. Meiner Ansicht nach müssten die SQL Queries überarbeitet werden. Bei mir lokal wird für die Jamboree Teilnehmer Abfrage über 3. Sekunden benötigt um die SQL Queries abzusetzen. Diese sind auch noch die Standard Queries welche vom controller/lists_controller generiert werden, deshalb glaube ich, dass wir da noch viel Potential haben.

Das rendern der View sollte jedoch auch nicht vernachlässigt werden. Diese benötigt nämlich, trotz Pagination, stolze 1.3 Sekunden um zu laden. Da könnten also auch noch einzelne Dinge optimiert werden.

Und mit dem Export haben wir ja schon seit längerem zu kämpfen: https://github.com/hitobito/hitobito/issues/23. Da sollten wir meiner Meinung nach schon einmal ein wenig Zeit investieren um die Performance hierbei zu verbessern. Bei einem Export von 30'000 Mitgliedern wird sich dieser ansonsten sicher im Stundenbereich bewegen.
