### ISSUE TITLE
«Add Role» Button

### ISSUE THREAD

**Issue by jesuistouriste** [hitobito/hitobito#529]
Should exist only once in the context of Role, not with every role associated to that person
<img width="621" alt="screenshot 2018-04-16 15 55 56" src="https://user-images.githubusercontent.com/3735878/38813214-ab10841a-418e-11e8-8caf-2d38549c731d.png">

**Comment by RolandStuder** [comment]
Beachten bei https://github.com/hitobito/hitobito/commits/feature/better-roles-aside

**Comment by ThomasEllenberger** [comment]
Also discussed here: https://github.com/hitobito/hitobito/issues/511
Issue is currently not planed -> closed.
