### ISSUE TITLE
English Translation of documentation

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#530]
Most of the [existing documentation](https://github.com/hitobito/hitobito/tree/master/doc) is provided only in German. And you really need documentation to understand and use and set up hitobito, which locks out foreign interest as well as our friends from the romandie and the ticino. So we started to translate the documentation as needed. Currently on a separate branch.

So if you want to help out, we welcome any contributions here, also you are welcome to improve / extend whatever you stumble upon.

Documentation: https://github.com/hitobito/hitobito/tree/master/doc

We will overwrite the current German documentation, we don't think the community is currently big enough to support English and German.

We welcome Pull Requests for this!

## State of Translations:
		
* architecture
   * [ ] diagrams
   * [ ] 01_einfuehrung.md
   * [ ] 03_kontextabgrenzung.md
   * [ ] 04_loesungsstrategie.md
   * [ ] 05_bausteinsicht.md
   * [ ] 07_verteilungssicht.md
   * [ ] 08_konzepte.md
   * [ ] 09_entwurfsentscheidungen.md
   * [ ] 12_glossar.md
   * [ ] README.md
* betrieb
   * [ ] diagrams
   * [ ] openshift
   * [ ] 01_openshift.md
   * [ ] 02_health_checks.md
* development
   * [ ] 01_setup.md
   * [ ] 02_deployment.md
   * [ ] 03_guidelines.md
   * [ ] 04_wagons.md
   * [x] 05_rest_api.md
   * [ ] 06_jenkins_setup.md
   * [ ] README.md
* e-mail
   * [ ] README.md

**Comment by ThomasEllenberger** [comment]
Readthedocs have been translated into French and Italian: https://github.com/hitobito/hitobito/issues/1894
Further translations are currently not planned.
