### ISSUE TITLE
Make participation list searchable by name

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#531]
Bei grösseren Anlässen ist es schwierig einzelne Teilnehmer zu finden, ein Suchen auf der Seite hilft nicht, wenn man mehrere Seite hat.

Eine Suchmöglichkeit gleich wie beim Filter für Rechnungen wäre hier sehr hilfreich.

**Comment by Michael-Schaer** [comment]
Wichtig ist erst mal, dass wir wieder nach Teilnehmer-Namen suchen können.

Grundsätzlich wäre eine Suche nach allen Attributen schon auch interessant. Vielleicht macht das aber mehr Sinn, wenn wir das zusammen mit dem Thema Filter/Export/Suche fürs Release 2018 diskutierien?

**Comment by RolandStuder** [comment]
@Michael-Schaer Guter Punkt. Die Filter funktionieren grundsätzlich etwas anders, aber beim Export müsste man sicher beachten, dass das dann auch dort funktionieren sollte.

**Comment by RolandStuder** [comment]
Eine teilwise Implementation existiert auf diesem Branch:

https://github.com/hitobito/hitobito/tree/feature/531-search-participations

**Comment by kronn** [comment]
PR #659 sollte dies lösen.
