### ISSUE TITLE
EOFError beim lesen vom POP3 Server

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito#534]
eim lesen vom pop3 kam es zu einem Fehler
https://errbit.puzzle.ch/apps/529c60a2de77482d71027b0a/problems/5acfbe756167b944ffe4f5f4

Das Email wurde als folge nicht korrekt verarbeitet.
https://errbit.puzzle.ch/apps/529c60a2de77482d71027b0a/problems/5ae1b17a6167b96b721ab5d9

Ich habe das entsprechende email in den failed Ordner verschoben
https://mail.puzzle.ch/webmail/726af9358ed8f791/?_task=mail&_caps=pdf%3D1%2Cflash%3D0%2Ctif%3D0&_uid=19&_mbox=failing&_action=show

**Comment by amaierhofer** [comment]
Weiteres Beispiel: 

Email
https://mail.puzzle.ch/webmail/7d5f23930198406d/?_task=mail&_caps=pdf%3D1%2Cflash%3D0%2Ctif%3D0&_uid=25&_mbox=failing&_action=show

Errbit Meldung, dass email bereits verarbeitet wurde
https://errbit.puzzle.ch/apps/529c60a2de77482d71027b0a/problems/5aed882f6167b967ca656498?notice=2677

Ursächlicher(?) EOFError
https://errbit.puzzle.ch/apps/529c60a2de77482d71027b0a/problems/5aed882d6167b967ca656495

**Comment by janissbinder** [comment]
In `app/domain/mail_relay/base.rb` gibt es in der methode relay_batch*1 einen Aufruf von `Mail.find_and_delete(count: retrieve_count)`. Das finden und löschen der Mail sollte dabei in zwei Schritte aufgeteilt werden:

## ***1:**
```
      def relay_batch
        last_exception = nil

        mails = Mail.find_and_delete(count: retrieve_count) do |message|
          begin
            new(message).relay
          rescue MailProcessedBeforeError => e
            message.mark_for_delete = false
            Airbrake.notify(e)
          rescue Exception => e # rubocop:disable Lint/RescueException
            message.mark_for_delete = false
            last_exception = MailRelay::Error.new(message, e)
          end
        end

        [mails, last_exception]
      end
```

**Comment by RolandStuder** [comment]
@amaierhofer Taucht das noch auf, muss man das fixen?

**Comment by amaierhofer** [comment]
Exception wird jetzt rescued, siehe 55a5df1f.
