### ISSUE TITLE
Duplikate finden global für Admin

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#54]
:Admin können global Duplikate finden
https://invis.io/3Z7RTPKSW#/169360065_Admin_Start
Also duplikat wird dasselbe Prinzip verwendet wie beim CSV Import

Erweiterungen möglich, z. B. für Fuzzier search (leichte Abweichungen, Tippfehler, phonetische Vertauschungen..

Mit Matches hat man folgende Möglichkeiten
- beide behalten (diese Paarung erscheint in Zukunft nicht mehr als potentielle Duplikat)
- zusammenführen (alle Gruppenzugehörigkeiten / Eventsteilnahme usw. alles was am Model hängt.)
- Details einblenden

**Comment by codez** [comment]
Die Möglichkeiten für Fuzzy Search müssten erst noch abgeklärt werden, MySql bietet da nur beschränkt Unterstützung. Allenfalls würde eine weiteres Tool/Service dafür benötigt.
