### ISSUE TITLE
Frontend Technology Decisions / API Decisions (Angular / React / Vue / GraphQL)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#543]
We are currently on Rails 4, using Bootstrap 2.3 and jQuery. This stack is somewhat dated. Expectations for a very responsive frontend are real, and I ithink we should discuss the possibilities.

For example we will implment something like this soon: http://suisa-prototyp.bitballoon.com/repertoire which will probably a pain to do with jQuery and it is not very elegant.

Also our current UI is highly abstracted. It's hard for new people to find their way.

So I would like to discuss which way we go forward here. I am thinking about two parts: API and frontend library / framework.

Because also on the side of APIs there is more demand, and our current APIs are very limited.

So there are the obvious candiates for the frontend as far as I know:
* Angular.js
* React.js
* Vue.js

As far as I know in at Puzzle we have mainly Angular knowledge, as it is strategic, but we should consider other options.

On the other hand, I was thinking about the API we provide. If we actually invest there, why not go a real step forward and to for GraphQL. 

So I think this is something we should talk about in the coming weeks. Any feedback from contributors, the community, interested people is welcome.

So what are your thought's what would be the right tools?

Something we have to consider is of course, that we need to make sure, we don't run into problems when we need wagons to overwrite components or behaviors.

**Comment by matejLukasik** [comment]
At Zeilenwerk, I led the switch from the classic Rails 4/5 + jQuery stack to a new one React + GraphQL + Rails 5 API. The feedback I have gotten from our developers is very positive. I believe GraphQL is really a much better abstraction than REST. It removes a load of REST based problems, enables smooth cooperation between FE and BE engineers and makes your applications more stable by definition (strongly typed).

Overall, we are definitely not experts in either React nor GraphQL, but we are very happy about what we are getting by scratching the surface. I believe they are going to be somewhat of a standard few years from now.

Happy to discuss more details if you would be interested in our experiences.

**Comment by RolandStuder** [comment]
I had a talk with out architect. And he pointed out many things that I did not think about:

* A new API will not magically give it more attention. The current REST API did not get a lot of attention so far.
* Our clients generally don't have big budgets, so we need to be very careful about bigger changes with a lot of risk
* Generally there is probably not enough development happening, so where will the resources come from.
* Leads to a more complex buildprocess
* How we override things is currently well established with the wagon functionality. Hard to say, how we would do this when we move all the UI components to another library.
* addtional Risk with version - updates. Do we have enough speed (will there be enough work on hitobito) to keep up?
* We have a maintanable version. Adding these layers would add complexity. 
* We should have link what is possible with turbolinks if we do a comparison.

**Comment by RolandStuder** [comment]
Under current circumstances this is not a feasible project, though it might be viable to do some components with other solutions that jquery. I close this due to inactivity.
