### ISSUE TITLE
Duplikatserstellung bei Person erstellen verhindern

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#55]
Das System soll eine Dubletten Kontrolle aufweisen. Schon beim Erfassen eines Mitglieds soll auf mögliche Dubletten aufmerksam gemacht werden.

Statt den Benutzer wählen zu lassen, lassen wir den Benutzer immer erst die Person suchen und bieten dann erst an, dass er eine neue Person erfassen kann.

![bei erstellung](https://cloud.githubusercontent.com/assets/194364/16375544/3179f0de-3c5c-11e6-9fef-971efb1d84b8.png)

**Comment by codez** [comment]
Das aktuelle Widget basiert auf Bootstrap 2 (http://getbootstrap.com/2.3.2/javascript.html#typeahead) und müsste wohl ersetzt werden, um einen Link in die Liste zu rendern.
