### ISSUE TITLE
Fehler beim hinzufügen von weiteren E-Mail-Adressen?

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#550]
https://errbit.puzzle.ch/apps/529c60a2de77482d71027b0a/problems/5afe710b6167b94c6349853e#

Kann jemand feststellen, was da los ist? Beim Hinzufügen von zusätzlichen e-Mail-Adressen trete ab und ein Fehler auf, könnte wohl dieser hier sein.

**Comment by janissbinder** [comment]
Der Fehler ist entstanden indem ein Benutzer bei den erweiterten Emails ein Punkt(.) beim Label eingetragen hat. Während dem Überprüfen ob das Label bereits vorhanden ist, wurde dadurch ein hash zurückgegeben, da alle labels immer gleich übersetzt angezeigt werden und ein Punkt für i18n die ganze Untergruppe bedeutet.

**Comment by simfeld** [comment]
Hallo zusammen

Der ursprüngliche Bug Report zu diesem Fehler stammt von mir, ich habe ihn an midata@pbs.ch geschickt. Wann denkt ihr, dass der Fix auf der produktiven Version ist? Ich wäre froh, wieder Mailadressen eintragen zu können.

Liebe Grüsse, Samuel/Olipo

**Comment by janissbinder** [comment]
Hallo Samuel,

Ich habe die korrupten Daten auf der Produktion korrigiert und du solltest nun wieder Mailadressen eintragen können. Leider ist der Fix noch nicht deployt, was bedeutet, dass die Daten vorübergehend wieder korrupt werden können (Sollten aber eigentlich nicht). Wann dass die neue Version releast wird, kann ich dir voraussichtlich nächste Woche mitteilen.

Gruess Janiss

**Comment by simfeld** [comment]
@janissbinder habe es getestet, funktioniert. Danke.
