### ISSUE TITLE
Beschreibung der Berechtigungen auf den aktuellen Kontext beziehen.

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#554]
![image](https://user-images.githubusercontent.com/194364/40482045-a9f326fe-5f53-11e8-9675-aa3cdfc96c8f.png)

Aktuell sind die Beschreibung der Berechtigungen allgemein formuliert (Ebenen / Gruppen / Untergruppen) Das ist nicht immer einfach nachzuvollziehen, einfacher wäre eine Beschreibung, die vom Kontext abhängig ist, und die Gruppentypen aufzählt und nicht nur.

Z. B. 

- Schreiben und Lesen auf _Dachverband_  und Untergruppen.
- Schreiben und Lesen auf _Dachverband_ und darunter liegenden _Regionen_, _Abteilungen_

**Comment by RolandStuder** [comment]
Ist in PR, ein Beispiel wie es aussieht.

![image](https://user-images.githubusercontent.com/194364/40576730-7cb6d5e2-60fb-11e8-9ed4-95695d2158dc.png)

Wird auch genutzt für die Darstellung der Rollenberechtigungen:

![image](https://user-images.githubusercontent.com/194364/40576743-b78b5c2e-60fb-11e8-9325-54ad078a91e1.png)

**Comment by RolandStuder** [comment]
We can now also show the available roles with permissions when creating a group: 
![image](https://user-images.githubusercontent.com/194364/40578453-9419891e-6114-11e8-879a-f7308d8eb652.png)

**Comment by olibrian** [comment]
Aus dem PR: Der Mehrwert des PR wurde etwas von der Realität überholt, daher schliesse ich diesen PR und das zugehörige Ticket.
