### ISSUE TITLE
Gruppennamen mehrsprachig

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#556]
Viele unserer Organisationen sind mehrsprachig, deshalb wäre es praktisch für gewisse Gruppen auch verschiedene Namen für die verschiedenen Sprachen vergeben zu können.

Diese Namen sollten dann bei Exporten und im User Interface so angezeigt werden.

## Mögliche Umsetzung im UI

![image](https://user-images.githubusercontent.com/194364/40711308-22ccc1f6-63fb-11e8-9d7f-444c60e78149.png)

* Sortierung der Navigation müsste natürlich nach dem Namen in der jeweilig gewählten Sprache sein. Damit könnten wir nicht mehr die Nested-Set Sortierung benützen (die sowieso fehlerhaft ist, das Kurznamen nicht berücksichtigt werden #542)
* Das Bedienungsmodell das wir im Adminbereich verwenden funktioniert hier schlecht, weil übersetzte und unübersetzte Inhalte dabei sind.

Wo muss dies angezeigt werden

* Überall wo der "Name" oder "Kurzname" benutzt wird, also global sollte das Attribut name immer mit dem Locale abgerufen werden.
* Personenlisten
* Teilnehmerliste
* Linksnavigation
* Gruppenname bei Rollen auf Personenanaischt
* Auf Sheet Gruppe.

**Comment by kronn** [comment]
Wenn es so gelöst werden kann, wie bei den CustomContents kann es recht schnell (~2h) gelöst werden. Dies wäre jedoch eine Lösung ohne die Sortierung. Wäre das erstmal ausreichend?

**Comment by KunoKunz** [comment]
Entscheid am Meeting vom 3.10. : Die Verbände, Unterverbände und Vereine mit mehrsprachigen Namen werden wie folgt in **einem** Feld erfasst: Deutsche Bezeichnung/Französische Bezeichnungen oder ähnlich.
