### ISSUE TITLE
Link auf Forum bei der generic-Instanz einbauen

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#557]
Die Generic-Instanz kommt aktuell bei den Multitennants und der Demoversion zum Einsatz. Da macht es m.E. Sinn, wenn wir oben in der Navigation einen Link auf das Forum [https://hitobito.discoursehosting.net/] einbauen.

**Comment by RolandStuder** [comment]
Habe den Footer ergänzt gleich mit Links auf Forum, Dokumentation und Support e-Mail Adresse

![image](https://user-images.githubusercontent.com/194364/41099853-0d03f626-6a60-11e8-87fc-265a38612c19.png)
