### ISSUE TITLE
Alumnusrollen für Jubla zurückbringen (16h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#558]
## IST: 

Bei der Jubla Ehemaligenverwaltung fehlt die Möglichkeiten zu sehen, wer bezüglich einer bestimmten Gruppe Ehemalig ist. Es geht hier darum, ob jemand bezügliche einer bestimmten GRUPPE Ehemalig ist, nicht bezüglich eines bestimmten LAYERS!

## SOLL

Zurückbringen der früheren Funktionalität, wo es eine Alumnusrolle pro Gruppentyp gab. 
Dafür kann der "alte" Code zurückgebracht werden. Ich konnte die entsprechenden Commits nicht unbedingt identifizieren. Aber praktisch alle Funktionalität sollte for den Änderungen im Herbst 2017 noch vorhanden sein.

## Akzeptanzkriterien

* [ ] Pro Gruppentyp gibt es eine Alumnusrolle z. B.  `ChildGroup::Alumnus` (siehe https://github.com/hitobito/hitobito_jubla/commit/a3ff9ecb6f5048e043f6b11f3d79a96c406abcd8)
* [ ] Diese Alumnusrolle wird automatisch zugeteilt, wenn ich meine letzte aktive Rolle in dieser Gruppe beende.
* [ ] Die Alumnusrolle wird automatisch entfernt, wenn ich wieder eine aktive Rolle erhalte.
* [ ] **Weder**  Alumnusrollen `GroupType::Alumnus`  **noch** die Rolle `Ehemalige::Mitglied` werden auf der Person angezeigt (sie können also nur von der Listenansicht aus bearbeitet werden).
* [ ] Alumnusrollen sollten `:kind` `:ehemalige` haben und in einem separaten Tab auf der Personenliste erscheinen.

**Comment by RolandStuder** [comment]
View Rechts auf Person show:
- Bereich abgelaufene Rollen soll heissen "Ehemalige Rollen"
- Es werden KEINE Alummusrollen rechts dargestellt, weder `Ehemalige::Mitglied` noch `GroupType::Alumnus`

**Comment by janissbinder** [comment]
Das mit den besprochenen conatactable_flags muss noch angepasst werden
