### ISSUE TITLE
Krisenverantwortliche Kanton - Zugriff auf Lagerinformationen (PBS)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#564]
## Problem

Die Benutzer mit Rolle «Verantwortlicher Krisenteam» und «Mitglied Krisenteam» auf Kantonsebene können zwar die Liste der Lager «durchgeführt im Kanton» anschauen. Sie sehen aber die folgenden für ihre Arbeit zentralen Daten nicht:

* Ort / Adresse
* Koordinaten
* Höhe über Meer
* Notfallnummer
* Besitzer/-in / Vermieter
* Lagerleiter: Mobile-Nummer, E-Mail
* Coach: Mobile-Nummer, E-Mail
*  Tabelle Erwartete Anzahl Teilnehmer

Für alle Lager, die im Kanton eines Krisenverantwortlichen durchgeführt werden, müssen diese Informationen vorhanden sein.

Auch bei den Lagern aus dem eigenen Kanton, bzw. von Abteilungen des eigenen Kantons müssen diese Informationen ersichtlich sein.

 
### Erweiterung der Berechtigungen (dieses Issue)

* Erweiterung der Rollen «Verantwortlicher Krisenteam», «Mitglied Krisenteam», «Sekretariat» und «Kantonsleiter» um die nötigen Berechtigungen. Sichtbar sind die oben genannten Daten für folgende Lager:
  * Alle Lager «durchgeführt im Kanton»
  * Alle Lager der eigenen Abteilungen und des eigenen Kantons
  * Zugriff auf die Kontaktdaten des Lagerleiters und Coaches über zusätzliche Felder

## Geklärte Fragen:

* Ja, es bezieht sich nur auf Lager, nicht auf andere Events
* Die Alternative, dass wir diesen Rollen die zusätzlichen Leseberechtigungen auf der ganzen Schweiz erteilen ist nur eine Notlösung. Falls der Aufwand die geschätzten 4h übersteigt, Rücksprache mit Roland Studer nehmen.

## Akzeptanzkriterien

* [ ] Die Rollen «Kanton :: Verantwortlicher Krisenteam», «Kanton :: Mitglied Krisenteam», «Kanton :: Sekretariat» und «Kanton :: Kantonsleiter» sind die Rollen die erweiterte Berechtigungen erhalten.
* [ ] Diese Rollen sehen auf dem eigenen Kanton das Tab "durchgeführt im Kanton"
* [ ] Diese Rollen sehen die folgenden Attribute…
  * Ort / Adresse
  * Koordinaten
  * Höhe über Meer
  * Notfallnummer
  * Besitzer/-in / Vermieter
  * Lagerleiter: Mobile-Nummer, E-Mail
  * Coach: Mobile-Nummer, E-Mail
  * Tabelle Erwartete Anzahl Teilnehmer (dieser Punkt nur, wenn er zu kaum zusätzlichen Aufwand führt.)
* [ ] … auf Lagern im eigenen Kanton von allen Untergruppen / Unterebenen
* [ ] … und auf allen Lagern, die in diesem Kanton durchgeführt werden. (kommt es hier zu Mehraufwänden als die gesamt geschätzten 4h, dann Rücksprache mit Roland Studer nehmen).
* [ ] Die Rollen erhalten aber NICHT die Berechtigung auf die Anmeldungen / Teilnehmerliste zuzugreifen.

**Comment by RolandStuder** [comment]
Als Alternative: 
- Was wenn wir es Berechtigungsmässig einfach halten und einfach Krisenverantwortlichen für alle Lager in der ganzen Schweiz diese Berechtigung erteilen. Was wären die Ersparnisse im Aufwand hierfür.

**Comment by RolandStuder** [comment]
Schätzung: 4h

* Wirklich nur auf Lager? Einfacher wenn wir das auf alle Events
* Alternative ok, dass wir das auf allen Events der gesamten Schweiz erlauben.

**Comment by Michael-Schaer** [comment]
Folgende Punkte haben wir beim Testing noch gefunden, ansonsten stimmt die Umsetzung für uns:

- Fehlermeldung 500: Viele Lager werden nicht angezeigt. Zusammenhang mit Berechtigungen oder Datenmigration?
Beispiele:
    https://pbs.puzzle.ch/de/groups/17/events/921
    https://pbs.puzzle.ch/de/groups/69/events/1009
    https://pbs.puzzle.ch/de/groups/497/events/753

- Der Coach hat die Kontaktdaten vom Lagerleiter eingetragen (falsche Variable)

- Wenn keine E-Mail oder Tel-Nummer erfasst ist, wird ein leeres Feld angezeigt, was etwas unschön ist, aber nicht häufig vorkommt.

**Comment by RolandStuder** [comment]
Die Fehler sind korrigiert, ich habe auch Tests ergänzt.

**Comment by RolandStuder** [comment]
@Michael-Schaer Ist bereit auf Integration zum Testen
