### ISSUE TITLE
Blasmusikverband: Ein Verein mehreren Mitgliederverbänden anhängen können

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#565]
## Variante Vollprogramm: Eine Gruppe darf mehrere Parents haben

* Eine Gruppe darf mehrere Parents haben, erscheint in der Gruppenstruktur und in der Navigation mehrmals.
* evtl. kann auf Gruppen mit meheren Parents ausgewählt werden, welcher Pfad normalerweise angezeigt werden soll (Breadcrumb / im Kontext welcher Parentgroup die Gruppe angezeigt werden soll.
* UI dazu noch unklar

## Variante Minimal

* Ich kann auf einem bestimmten Gruppentyp Verein mehrere sekundäre Zugehörigkeiten zu einem Mitgliederverband oder Regionalverband auswählen.
* Der Verein wird auch in der Linksnavigation im Baum für diesen Mitgliederverband / Regionalverband angezeigt
* Bei Aboversänden wird dieser Verein gleich eingeschlossen, wie Vereine, welche tatsächlich zu diesem Regionalverband / Mitgliederversand gehören.

**Comment by RolandStuder** [comment]
Fundamental anders aber sehr spannend und komplex wäre ein System, wo ich Daten subscriben kann. Ein Verein hat gar keine fixe Zuordnung mehr, aber kann mit anderen Organisationseinheiten Daten austauschen. Eigentlich ein federated system. natürlich ist dies ein vielfaches kompexer, aner interessant zum daran herumdenken in Hinblick auf die Zukunft von hitobito und responsive Organisationen allgemein.

**Comment by KunoKunz** [comment]
Vorschlag aus dem Workshop mit dem SBV: Jugendmusik erhält Flag „Mitglied Jugendmusik-Verband“. Brassband und Blaskapelle können dann ähnlich gelöst werden.

**Comment by KunoKunz** [comment]
Welche resp. wieviele Vereine, Verbände sind betroffen?
- 20-25 Stück bei den Jugendmusiken
- Brassbands: rund 40

Wie sind die Zuständigkeiten geregelt (bspw.Festlegen neuer Gremien, Kontrollen/Mutationen der Mitglieder)?
- Bei den Brassbands immer der SBV
- Bei den Jugendmusiken immer der Jugendmusik-Verband

Der Grund für die mehrfache Zugehörigkeit: Wenn ein Verein/Verband nicht Mitglied beim SBV ist, kann er nicht am eidg. Musikfest teilnehmen.

Ist der Verein/Verband (Jugendmusik, Brassband) Mitglied beim SBV oder deren Mitglieder?
-> Immer der Verein

Wenn Blaskapellen dazukommen, werden sie wie ein Kanton behandelt.

**Comment by RolandStuder** [comment]
@codez Die Notizen von der Besprechung

Sekundäre Struktur

-  DV
   - MV
       - Verein (Zugehörigkeit zu MV2...)
   - MV2

- Group::Verein -> Group::Mitgliederverband

## Spezielle Gruppen / Rollen

* Entsprechend bei Ehemaligen Jubla

- Group::Verein / Group::Jugendverein / Group::Brassverein 
- DV::Spezielle Rolle Nur Jugendverein
- DV::JugendGS

## Kategorienzuordnung

:jugend / :brassband

- entsp. Rollen entsprechend
- Filter anpassen
- Abos anpassen
- Auf der Rolle selbst, definieren, welche Kategorien Zugriff haben.

- Fall: 
    * DV
        * MV Jugendmusik
            - Rolle GS:Speziell (Jugendmusik)
            * MV Jugendmusik Wallis
        * MV Kanton Wallis
            * Verein
- hierarchische Kategorie

MV Jugendmusik -> Verein -> 500 Jugendmusiken
Abos: Rootmöglichkeiten müssen anders sein.

Punktuell wäre:
  - Zugriff erteilen
  - Gruppenliste exportieren (CSV auf Info)

Heikel:
  - Abos
  - (Navigation anpassen)

## Mehrfachzuordnung als Vollprogramm

- Müsste man evtl. einschränken, dass das nur bei gewissen Gruppentypen, geht, wie ist das bei bisherigen.
- Berechtigungen, wie wäre das.

**Comment by codez** [comment]
### Grobschätzung Variante "Mehrfachzuordnung als Vollprogramm" (DAG): 20 PT

Nötige Anpassungen (aufgrund Vorkommnisse von `hierarchy` und `layer_group`, weiteres möglich; exkl Reserve):

*Core*
* Datenmodell Gruppe (2)
* Datenmigration (1)
* Weitere Parents hinzufügen (Controllers, Views) (2)
* Berechtigungen (3)
* Gruppennavigation, Breadcrumb (aktueller Pfad in Session speichern?) (2)
* Anzeige der Ebene einer Person (Detailansichten, Listen, Export, ...) (1)
* Gruppen verschieben (0.25)
* Anlassliste Benutzer*in (0.25)
* Anlass Filter (0.25)
* Teilnahmebestätigung (0.25)

*PBS*
* Berechtigungen (0.5)
* Kursfreigaben (0.25)
* Lageranmeldungen (0.25)
* Kursteilnahmebenachrichtigungen (0.25)

*Jugendverbände*
* Provisorische Anmeldungen (0.25)

*Jubla*
* Berechtigungen (0.5)
* Alumni (1)
* Coaches (0.25)

*Insieme*
* Berechtigungen (0.5)
* Registrierung bei Anlässen (0.25)
* Aboadressen (0.25)
* Statistik (0.25)

**Comment by codez** [comment]
### Grobschätzung Variante Minimal: 6 PT

Nötige Anpassungen (ausschliessich im Wagon, exkl. Reserve):

* Datenmodell & weitere Parents hinzufügen (Controllers, Views) (2)
* Gruppennavigation (1.5)
* Abos (1.5)

Option Alle Berechtigungen: +4PT

**Comment by KunoKunz** [comment]
Noch eine Rückmeldung vom SBV: Ein Verein muss max. drei (3) Verbänden angehängt werden können.

**Comment by RolandStuder** [comment]
@KunoKunz Hier weisst du besser wo der Stand ist, ich weise es dir zu.
