### ISSUE TITLE
Stable branches entfernen (3h)

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito#568]
Mit Einführung der Composition repos ist es nicht mehr notwendig stable branches zu pflegen.

- stable Branches entfernen
- Jobs anpassen, ggf. jobs nach DSL auslagern
- Eventuell VERSION File beim build schreiben (was schreiben wir für master?)

**Comment by RolandStuder** [comment]
@amaierhofer  Wieviel Aufwand sparen wir damit? Ich frage, weil wir dieses und letztes Jahr viele Kosten für die Umstellung auf OpenShift hatten, ist das nice to have?, macht das die neuen Deploys schneller, weniger Fehler wegen Merging? Und wie gross ist der Umstellungsaufwand?

**Comment by kronn** [comment]
Ich sehe es nicht als "nice to have", sondern als Vereinfachung des Workflow an. 

Da das Merging effektiv wegfällt, passiert es nicht mehr, dass stable und master verschiedene Commits haben. Dies hat in der Vergangheit manchmal zu Inkonsistenzen zwischen prod und int geführt. Die Version wird komplett durch das Composition-Repo gesteuert und ist damit weiterhin gut kontrollierbar. Ich schätze den Umstellungsaufwand eher in Stunden (weil ja mehrere Repos betroffen sind) als in Tagen. Es ist eher eine Umstellung des Verhaltens und der Dokumentation und vielleicht des Toolings. Gerade die Jenkins- und Travis-Konfigurationen sollte man sich aber ansehen.

Das VERSION-File beim Build zu schreiben, sollte eine Kleinigkeit sein, nach meinem Verständnis müsste es in https://github.com/hitobito/hitobito/blob/master/.s2i/pre_assemble#L18 passieren (vor allem, bevor das .git-Verzeichnis entfernt wird).
