### ISSUE TITLE
Veteranenwesen Blasmusikverband

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#569]
# Hintergrund

Der Blasmusikverband hat ein stark entwickeltes Veteranenwesen. Wenn eine Person X Jahre aktiv war, erhält die Person den Veteranenstatus.  Veteranen gibt es auf Kantonaler und auf eidgenössischer Stufe

Das entsprechende Reglement: http://www.windband.ch/media/1066/veteranenreglement_sbv_2013_maerz_d.pdf

# Lösungsmodell

Wir bilden das Veteranenwesen mit dem Rollenmodell ab. Wir erstellen entsprechende Rollen auf den verschiedenen Ebenen. Die Rollen werden manuell vergeben. 

Die Veteranen können aber über einen intelligenten Filter identifiziert werden. Wir setzen zusätzliche folgende Funktionen um:
* Mehrfachauswahl auf Personenlisten
* Rolle zuweisen aus Merhfachauswahl
* Fehlende Mitgliedschaften ergänzen

# Anforderungen

## Aktivjahre auf Person

* [x] Eine Person hat ein berechnetes Feld Aktivjahre
* [x] Aktivjahre Berechnung wie dokumentiert: http://www.windband.ch/media/1067/regelung_der_berechnung_der_veteranenjahre_sbv_2013_juni_d.pdf (Monate und Tage sind irrelevant für die Berechnung, es geht nur um die Kalenderjahre)
* [x] Aktivjahre wird im Export "Alle Angaben" auch exportiert.

## Nach Aktivjahren Filtern

<img width="583" alt="mockup" src="https://user-images.githubusercontent.com/194364/41349103-146535fc-6f0f-11e8-98a9-cc7756fcfea7.png">

Bitte hier überlegen, ob wir den Filter allgemein halten können, damit ihn auch auf andere Personenattribute beziehen könnte siehe #292, wobei es hier ja aber um ein berechnetes Feld geht.

* [x] Zusätzliche Filterbereich: `Aktivjahre` auf Personenlisten
* [x] Filter für Aktivjahre, suche nach Personen mit X Aktivjahren
* [ ] Filter kann auf ein bestimmtes Jahr in der Vergangenheit bezogen werden.

## Erweiterung Aktivjahr auf anders Jahr bezogen berechnen

<img width="567" alt="bildschirmfoto 2018-06-13 um 13 40 16" src="https://user-images.githubusercontent.com/194364/41349178-571ddc00-6f0f-11e8-9bf7-6c2555e5ed63.png">

## Weitere Aktivjahre im Verlauf hinzufügen

![image](https://user-images.githubusercontent.com/194364/41453608-b4afb2ae-7076-11e8-9245-9db5d9b35667.png)

* [ ] … hier ergänzen

## Neue Gruppen und Rollen

* [x] Auf Layer Dachverband neuer Gruppentyp Group::Veterans
  * [x] Neuer Gruppentyp gehört zu default_children
  * [x] Neuer Rollentyp auf dieser Gruppe `Eidgenössischer VeteranIn` (keine Berechtigungen)
  * [x] Neuer Rollentyp auf dieser Gruppe `Eidgenössischer EhrenveteranIn` (keine Berechtigungen)
  * [x] Neuer Rollentyp auf dieser Gruppe `CISM Veteran` (keine Berechtigungen)
* [x] Auf Layer Mitgliederverband neuer Gruppentyp Group::Veterans
  * [x] Neuer Gruppentyp gehört zu default_children
  * [x] Neuer Rollentyp auf dieser Gruppe `Kantonaler VeteranIn` (keine Berechtigungen)
  * [x] Neuer Rollentyp auf dieser Gruppe `Kantonaler EhrenveteranIn` (keine Berechtigungen)

## Offene Fragen

* [x] Wo bilden wir CISM Veteranen ab, wer verwaltet diese? -> Rolle auf Dachverband::Veteranen
* [x] Welche Rollen sollen als Aktivejahre zählen, Alle Aktivmitglieder, Alle aus Vorstand und Dirigent, oder? -> Nur Rolle Mitglieder::Mitglied
* [x] Gab es da einen Unterschied bei den Jugenmusiken? -> Nein
* [x] Wer sind Funktionäre / Fähnrich, als welche Rollen werden die erfasst? (wegen Veteranenreglement… -> Egal, es werden nur Jahre von Mitglieder::Mitglied gezählt.
* [x] In der Ausschreibung wird noch "Medaillen verwalten" erwähnt. Braucht es das noch? Oder ist dies gleichbedeutend wie die Rolle "Veteran" zu vergeben? -> Ist mit Rollenvergabe abgedeckt.

**Comment by KunoKunz** [comment]
Falls wir mit dem Projekt gut vorwärts kommen: Wäre es ein "Zückerchen", wenn wir die Veteranenmeldung als Export anbieten könnten? Falls ja: Ablauf heute? Was bedeuten die einzelnen Tabellen im Formular?

**Comment by RolandStuder** [comment]
@KunoKunz Da wir das als Filter umsetzen und mit Rollen ist das per Default schon drin, wenn du die Liste gefiltert hast, kannst du die auch exportieren. Wir müssen einfach schauen, dass das Attribut Aktivjahre auch exportiert wird.

**Comment by KunoKunz** [comment]
@RolandStuder die Inhalte schon - ich habe eher an eine Excel-Vorlage gedacht, die sich nach dem heutigen Formular richtet und mit den entsprechenden Angaben (für den Verein) abgefüllt wird.
[formulare_veteranenmeldungen_sbv_2013_april_d.xlsx](https://github.com/hitobito/hitobito/files/2102813/formulare_veteranenmeldungen_sbv_2013_april_d.xlsx)

**Comment by KunoKunz** [comment]
Eigentlich könnten die Listen auch weggelassen werden. Neu könnten die Verantwortlichen der Vereine ihre Anwärter auch irgendwie taggen oder mit einem "Anwärter"-Status versehen. Dafür müssten wir allerdings die Filtermöglichkeiten ausbauen.

**Comment by RolandStuder** [comment]
@KunoKunz Ja guter Punkt, ich denke Tags auch zuweisen zu können und den Filter #283 / #291  noch zu erweitern sind wohl grad ein bisschen viel Sachen zum reinpacken. Wobei vielleicht der DSJ dort mithelfen würde.

**Comment by KunoKunz** [comment]
* [ ] @KunoKunz Wichtig: auf Stufe Kantonalverbände müssen alle Mitglieder der Unterverbände angezeigt werden.

**Comment by RolandStuder** [comment]
Implemented
