### ISSUE TITLE
Upload von ESR-Zahlungen Batch (16h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#57]
siehe Punkt 4.5 in https://github.com/hitobito/hitobito/files/311813/Hitobito_Erweiterung_Rechnung_v0.1.pdf

Spezifikation enthalten zu Zahlungsbatchfiles camt 053 054 in https://www.postfinance.ch/content/dam/pfch/doc/cust/download/inpayslip_isr_man_de.pdf

**Comment by RolandStuder** [comment]
Link

**Comment by RolandStuder** [comment]
Beispielfiles:

https://wiki.xmldation.com/@api/deki/files/209/=FI_camt_054_sample.xml.xml
https://wiki.xmldation.com/@api/deki/files/208/=FI_camt_053_sample.xml.xml

Ich habe noch nicht ganz verstanden, wann man welches File benötigt.

**Comment by KunoKunz** [comment]
Wir haben die Testdatei erhalten. Geht per Mail an ama.

**Comment by KunoKunz** [comment]
Die Testdatei enthält gemäss telefonischer Auskunft der Postfinance verschiedene UseCases und Beispiele, die für uns nicht relevant sind. Es geht hier lediglich um die Verarbeitung der ESR-Gutschriften.

Ich werde in der Community noch nachfragen, ob sie ihre Kontoauszüge täglich oder monatlich erhalten. Je nach Anforderung brauchen wir nur den camt.054 umsetzen. Ich würde auf jeden Fall mal mit diesem beginnen. Je nach Aufwand kann danach noch camt.053 mit diesem Release umgesetzt werden oder würde danach für einen neuen Kunden umgesetzt.

- camt.053 ist der "Kontoauszug End of Day" (siehe Dok. "Implementation Guidelines Seite 21 ff.)
- camt.054 ist die Sammelbuchungs-auflösung und Belastungs- und Gutschriftsanzeige (Seite 69 und im Anhang A ab Seite 96).

Da 053 die in der CH am häufigsten verwendete Form ist, wird im Dokument primär dieses Format beschrieben. Ausnahmen für 054 finden sich auf Seite 27.

Geschäftsvorfall-Codes sind im besagten Dokument ab Seite 100 aufgeführt.

**Comment by RolandStuder** [comment]
Dieser Code wird sowieso nochmals angeschaut, weil es nicht für alle files geht, deshalb schliesse ich dieses Issue.
