### ISSUE TITLE
Werkliste Crud Controller erstellen (2h)

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito#577]
* Neuen `SongsController` erstellen, mit einfachen crud views und toplevel routes
* Nur Rollen mit Permissions `songs_census` sollen darauf zugriff haben
* Alle Spalten als `search_columns` registrieren

**Comment by RolandStuder** [comment]
Auf der Werkliste sollten nur Personen auf der obersten Ebene Edit / Destroy machen dürfen. Verein::SuisaAdmin darf nur neue Werke ergänzen, aber nicht bestehende Löschen.
