### ISSUE TITLE
Zahlung per Kreditkarte / Postkarte ermöglichen (24h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#58]
Einbindung eines externen Services als Payment Provider?

Online Zahlung ermöglichen. Kassier muss sich selbst beim entsprechenden Service registrieren.
- Kassier muss sich dort selbst registrieren und 

Vorschläge für einen solchen Service? wie z. B. https://stripe.com/? Gibt Twint nun Möglichkeiten?

**Comment by richardjubla** [comment]
Auch wenn der "Hype" evtl. etwas nachgelassen hat. Twint ist gekommen um zu bleiben. 
Das Angebot und die Nutzung scheint ein mächtiges Feature zu sein. (und von den Vereinen geschätzt?)
https://www.twint.ch/geschaeftskunden/unsere-loesungen/vereine/

Die TWINT und RaiseNow QR-Code und PayLink Lösungen sind technisch an diverse Vereinssoftware angebunden. 
![image](https://user-images.githubusercontent.com/95908537/219721558-6e7228e8-f0d1-432a-81f2-c2180c39b9b4.png)
