### ISSUE TITLE
Werkliste via CSV Import erfassen (8h)

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito#582]
* eigener `SongsImportsController`  als singelton resource
* Berechtigungen berücksichtigen

**Comment by RolandStuder** [comment]
[werkliste.csv.zip](https://github.com/hitobito/hitobito/files/2126897/werkliste.csv.zip)

Beispieldaten mit denen man Testen kann. Entspricht nicht dem Datenformat, welches wir von der SUISA erhalten werden. Aber damit man nicht alles selbst erfinden muss (es hat viele "Duplikate", wegen Schreibfehlern)
