### ISSUE TITLE
API requests for groups (20h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#585]
To make local groups discoverable PBS wants an improvement to the API, so they can feed their group finder from the current data in hitobito (see http://www.pfadi.swiss/de/pfadi-map?field_geofield_distance%5Borigin%5D=)

## Needed adjustments

* Additional fields on the groups 4h
* Save Multiple Geolocations savable per group 8h
* API Endpoints to get multiple groups with their public data, including a filter for group_type 8h

**Comment by Michael-Schaer** [comment]
### Erweiterung der Abteilungen für Pfadi-Finder
Anders als vorgesehen, soll sich die Entwicklung nur auf die neuen Abteilungs-Felder und den API-Zugriff beschränken. Es werden keine Suchfunktion oder Gruppenfilter in der MiData benötigt.

Neue Felder auf der Abteilung:

-	Geschlecht: Gemischt, Männer, Frauen (Select-Box)
-	Datum Schnuppertag (dd.mm.yyyy)

-	Treffpunkte:
o	Erfassen von Koordinaten (bis zu 4 Treffpunkte sind möglich)
o	Eine Koordinate besteht aus zwei Feldern (Lat / Long)
o	Überprüfung aufs Format [Decimal degrees](http://wiki.gis.com/wiki/index.php/Decimal_degrees)
o	Maximalanzahl Treffpunkte können angepasst werden. Konfigurierbar oder einfach im Code anpassbar machen. Initialwert: 4

-	Info-Text oberhalb der neuen Felder, am besten als konfigurierbarer Text (Einstellungen -> Texte)
DE: «In den folgenden Felder könnt ihr die öffentlichen Angaben eurer Abteilung eintragen. Diese Angaben werden jeweils nächtlich in den Pfadi-Finder unter https://pfadi.swiss übernommen. Es können bis zu vier Treffpunkte pro Abteilung definiert werden.»

**Comment by carlobeltrame** [comment]
Brauchen die Treffpunkte keinen Namen oder Bezeichnung? Z.B. "Schulhausplatz" etc.? Oder sind sie eher als "Zentren" des Einzugsgebiets gedacht?

**Comment by Michael-Schaer** [comment]
Ja genau, wir wollen beim Pfadifinder von einer Ortsangabe/PLZ auf die umliegenden Treffpunkte kommen. Für den Moment sind also keine ausformulierten Bezeichnungen nötig.
