### ISSUE TITLE
Neue ESR-Standards 2019 (24h)

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#589]
Die heute unterschiedlichen Standards für Zahlungen werden standardisiert. Die Unterscheidung nach rotem und orangem ES ist nicht mehr nötig. Die Art des Verfahrens ergibt sich aus der Rechnungskonfiguration und den Rechnungsdaten.

Bei der Aufbereitung des QR-Codes gibt es unterschiedliche Verfahren:
- Verfahren mit strukturierter Referenz ohne zusätzliche Informationen
- Verfahren mit strukturierter Referenz mit zusätzlichen Informationen
- Verfahren mit Mitteilung
- "Alternative Verfahren" können für den ersten Schritt ausgelassen werden

Eine kurze und verständliche Übersicht der PF: https://www.postfinance.ch/de/unternehmen/produkte/debitorenloesungen/qr-rechnung.html

Weitere Info siehe Implementation Guidelines von SIX: https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-de.pdf

Sowie weitere Unterlagen für Software-Partner: https://www.paymentstandards.ch/de/home/software-partner.html

**Comment by RolandStuder** [comment]
Ich schliesse #72 als Duplikat

> Der in die Jahre gekommene DTA-Standard für elektronische Zahlungsaufträge wird ersetzt. Ab Mitte 2018 wird der DTA-Standard nicht mehr unterstützt.
> 
> http://www.akb.ch/firmenkunden/konten-zahlen/zahlungsverkehr/neuer%20zahlungsverkehr/harmonisierung%20im%20schweizer%20zahlungsverkehr.aspx#tab-1
> 
> Evtl. bietet dies die Gelegenheit, den beteiligten Organisationen hitobito für die Rechnungsstellung schmackhaft zu machen.
>

**Comment by KunoKunz** [comment]
Neuer Zeitplan und Infos zur QR-Rechnung:
https://www.raiffeisen.ch/rch/de/firmenkunden/liquiditaet-und-zahlungsverkehr/harmonisierung-zahlungsverkehr/qr-rechnung/was-ist-qr-rechnung.html#was-ist-eine-qr-rechnung?1

**Comment by amaierhofer** [comment]
Aufwände in etwa
- Einlesen / Verstehen der Materie (8h)
- Layouting für QR Rechnungen (12h)
- Bereinigen obsoleter Einstellungen (4h)

**Comment by KunoKunz** [comment]
Der QR-Code kann ausgelesen werden. Für die Verarbeitung der Rechnung fehlen allerdings folgende (abhängige) Pflichtfelder: 
- Zahlungsempfänger Nummer oder Adresszeile 2
- Zahlungsempfänger Land
- Endgültiger Zahlungspflichtiger Nummer oder Adresszeile 2
- Endgültiger Zahlungspflichtiger Land

**Comment by KunoKunz** [comment]
Ich erhalte immer noch die gleichen Fehler (Test auf MT-Int). Sowohl bei einer Rechnung, welche auf einer Person ausgelöst wurde und auch bei externen Rechnungen.

**Comment by amaierhofer** [comment]
Ich kann das nicht reproduzieren, bei mir klappt das [Drucken aller Rechnungen auf dem Dachverband](https://admin.hit-multitenancy-int.ocp.puzzle.ch/de/groups/1/invoices.pdf?ids=1,2,3,4) auf der Admin Instanz auf Integration. 

Es gab noch einen Fehler beim Darstellen der Rechnungsartikel , den habe ich mit 172bcbb3c behoben und das Deployment auf Integration angestossen.

**Comment by KunoKunz** [comment]
Das Drucken selber hat auch geklappt. Aber beim Einlesen der QR-Rechnung fehlen immer noch die oben aufgeführten Pflichtfelder.

**Comment by KunoKunz** [comment]
**Zahlungsempfänger Nummer oder Adresszeile 2:**
- Strukturierte Adresse: Hausnummer der Zahlungsempfängeradresse
- Kombinierte Adressfelder: Adresszeile2 mit Postleitzahl und Ort der Zahlungsempfängeradresse
- Strukturierte Adresse: maximal 16 Zeichen zulässig
- Kombinierte Adressfelder: maximal 70 Zeichen zulässig
- Muss geliefert werden bei Adress-Typ «K»


**Zahlungsempfänger Land:**
- 2-stelliger Landescode gemäss ISO 3166-1

Analog dazu bei der zahlungspflichtigen Person:
- Endgültiger Zahlungspflichtiger Nummer oder Adresszeile 2:
- Endgültiger Zahlungspflichtiger Land


Vermutlich müssten in den Rechnungseinstellungen das Feld "Einzahlung für" aufgeteilt werden. M.E. gleich, wie auf einer Person: - Adresse
- PLZ/Ort
- Land
Das Gleiche danach beim Erstellen einer externen Rechnung beim Feld "Empfänger Adresse"

Beim Erstellen einer Rechnung auf einer Person erhalte ich noch einen Fehler: "Empfänger Addresse oder E-Mail muss ausgefüllt werden". Die entsprechenden Felder werden im Form aber nicht angezeigt. Dies könnte wohl im gleichen Zug gefixt werden.

**Comment by KunoKunz** [comment]
Ich habe die verschiedenen Arten, um eine Rechnung zu erstellen, noch einmal getestet. Es gibt immer noch Punkte, die nicht funktionieren:

Externe Rechnung erstellen:
Die QR-Rechnung ist ungültig. Folgende (abhängige) Pflichtfelder wurden nicht geliefert.: Zahlungsempfänger Land, Endgültiger Zahlungspflichtiger Land

[Rechnung-1-17(1).pdf](https://github.com/hitobito/hitobito/files/5183698/Rechnung-1-17.1.pdf)

Rechnungen auf/für eine Gruppe erstellen:
Die QR-Rechnung ist ungültig. Folgende (abhängige) Pflichtfelder wurden nicht geliefert.: Zahlungsempfänger Land, Endgültiger Zahlungspflichtiger Nummer oder Adresszeile 2, Endgültiger Zahlungspflichtiger Land

[Rechnung-1-14.pdf](https://github.com/hitobito/hitobito/files/5183699/Rechnung-1-14.pdf)

Rechnung auf einer Person erstellen:
Die QR-Rechnung scheint hier formell in Ordnung zu sein. Allerdings kann die Rechnung auf der Testplattform danach nicht angezeigt werden, das Programm loopt ohne Ende. Der Einzahlungsschein wird auf einer separaten Seite gedruckt, was etwas unschön ist.

[Rechnung-1-12.pdf](https://github.com/hitobito/hitobito/files/5183700/Rechnung-1-12.pdf)

**Comment by KunoKunz** [comment]
* [ ] Der QR Validator meldet noch einen Fehler zurück: Zeile 32, Feld RmtInf.AddInf.StrdBkgInf Zahlungsinfo das Feld muss mit folgender Zeichenkette beginnen: //S1 
* [ ] Beim Erfassen der Zahlungen werden keine Buchungen erkannt. Wurde dort die Verarbeitung bereits auf den neuen Standard angepasst, @amaierhofer ?

**Comment by amaierhofer** [comment]
@KunoKunz kannst du bitte zu den zwei Punkten  Beispiele angeben?

**Comment by olibrian** [comment]
QR Rechnungen umgesetzt im Zuge erwähnten Tickets
