### ISSUE TITLE
Feature specs auf chrome-webdriver umstellen (8h)

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito#591]
- [x] webdriver ins projekt aufnehmen
- [ ] alle features specs zum laufen bringen
- [x] auf travis integrieren

**Comment by kronn** [comment]
In unserem Build-Setup ist Firefox aktualisiert worden, was zu #619 geführt hat. Die neue Selenium-Version erforder einen webdriver (chromedriver oder geckodriver). Auf travis ist dieser vorhanden, intern schauen wir gerade, was der gewünschte Weg ist.

**Comment by olibrian** [comment]
Specs laufen in der Zwischenzeit mit Github Actions
