### ISSUE TITLE
Nach Aktivjahren Filtern

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#600]
<img width="583" alt="mockup" src="https://user-images.githubusercontent.com/194364/41349103-146535fc-6f0f-11e8-98a9-cc7756fcfea7.png">

Bitte hier überlegen, ob wir den Filter allgemein halten können, damit ihn auch auf andere Personenattribute beziehen könnte siehe #292, wobei es hier ja aber um ein berechnetes Feld geht.

* [ ] Zusätzliche Filterbereich: `Aktivjahre` auf Personenlisten
* [ ] Filter für Aktivjahre, suche nach Personen mit X Aktivjahren
* [ ] Filter kann auf ein bestimmtes Jahr in der Vergangenheit bezogen werden.

**Comment by janissbinder** [comment]
On Hold, ich warte noch bis ein Reveiw für das Ticket hitobito/hitobito#292 da ist.

**Comment by kronn** [comment]
Ich habe den zugehörigen PR mal gemerged, damit das hier nicht weiter blockiert ist.

**Comment by RolandStuder** [comment]
Implemented
