### ISSUE TITLE
Weitere Aktivjahre im Verlauf hinzufügen

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#602]
![image](https://user-images.githubusercontent.com/194364/41453608-b4afb2ae-7076-11e8-9245-9db5d9b35667.png)

**Comment by janissbinder** [comment]
https://github.com/hitobito/hitobito_sbv/pull/3

**Comment by janissbinder** [comment]
Offene Punkte von PR: hitobito/hitobito_sbv#3

`app/models/sbv/role.rb`
```
  included do
    validates :created_at, presence: true, if: :deleted_at
    validate :created_at_has_to_be_earlier_or_equal_than_today
    validate :created_at_has_to_be_earlier_or_equal_than_deleted_at
  end
```

Bitte mit https://github.com/adzap/validates_timeliness lösen. Da es schon im Projekt vorhanden ist, sollten wir es auch nutzen :-)

**Comment by RolandStuder** [comment]
Thema Migration und Erfassen von Zusatzjahren für eine Person: Aus Musicgest werden wir bereits alte (=inaktive/als gelöscht markierte) Vereine importieren. D.h., dass wir für das Erfassen der Zusatzjahre den gleichen Meccano anwenden und der Admin auf Kantonalstufe halt einen alten/inaktiven Verein erfassen muss. (ak)

**Comment by KunoKunz** [comment]
Gemäss Beschluss vom 3.10. werden wir die reine Texteingabe nicht realisieren. Es muss für den Ausnahmefall ein gelöschter/inaktiver Verein hinzugefügt werden können.

**Comment by kronn** [comment]
Ich habe die validation noch angepasst, damit wir weniger custom validations haben.

**Comment by RolandStuder** [comment]
Ist Implementiert.
