### ISSUE TITLE
Zugang für Eltern

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#603]
# Ziel:

Oft haben die Eltern mehrere Kinder welche als Kinder z. B. bei der Pfadi Mitglieder sind. Heute gibt es für die Eltern keine gute Möglichkeit die Daten für ihre Kinder anzupassen oder diese für Anlässe anzumelden, da die Hauptemailadresse nur von einer Person verwendet weden kann, und also entweder pro Kind einen Account braucht (was sowieso unpraktisch ist, weil ich mich mehrmals in hitobito ab- und anmelden muss).

# Lösung

Kinder und Eltern können zu Familien zusammengefügt werden. Eltern erhalten dabei Schreibrechte auf die Kinder und erhalten die Möglichkeit die Kinder anzumelden.

![image](https://user-images.githubusercontent.com/194364/43453719-15310b42-94bb-11e8-94ca-2f67969257e3.png)

![image](https://user-images.githubusercontent.com/17568539/110790088-e7182780-8270-11eb-9b6e-c2c516866eef.png)

# Akzeptanzkriterien

## Familie verwalten.

* Auf einer Person sehe ich ein Tab Familie. (4h)
* Ich kann auf dem Tab Familie Personen hinzufügen, falls ich auf der Person Schreibberechtigung habe. (4h) 
  _=> Jede Person hat auf sich selbst Schreibberechtigungen. Das müsste wohl noch anders eingeschränkt werden, sonst kommt man zum Formular, kann dort aber keine Person hinzufügen._
* Bei der Suche nach Familienmitgliedern erscheinen alle auf die ich Schreibrechte habe. (2h)
* Ich kann wählen ob die die Person als Kind oder als Erziehungsberechtigte Person hinzugefügt werden soll.
* Eine Person kann wieder aus der Familie entfernt werden. (2h)
* Eine Person kann nur in einer Familie sein.
* Wenn ich mich als Erziehungsberechtigte Person anmelde, so komme ich nach der Anmeldung in hitobito direkt auf die Famlienübersicht (Navigationspunkt Familie in Hauptnav, die Familienübersicht wird auf einem Sheet auf oberster Ebene gezeigt und nicht im Kontext einer Gruppe / Person, siehe Mockup). (4h)

## Berechtigungen

* Erziehungsberechtigte Personen erhalten Schreibrechte auf die Kinder und auf die anderen Erziehungsberechtigten Personen der Familie. (8h)

## Anmeldungen

* Wenn ich bei einem Event auf den Anmeldeknopf drücke, erhalte ich eine Auswahl, welche Person ich anmelden möchte (mich selbst, andere Erziehungsberechtigte Person, Kinder). Ich führe dann die Anmeldung so durch als wäre ich diese Person. (8h)
* Beim Screen Kontaktangaben erscheinen die Angaben der anzumeldenden Person.

![image](https://user-images.githubusercontent.com/194364/43453660-e8f8e680-94ba-11e8-86e5-ddc7b64502eb.png)

## Haushalt

* Per Default ist eine Familie gleichzeitig auch ein Haushalt. (8h)
  _=> Was geschieht, wenn ein Familienmitglied einem anderen Haushalt hinzugefügt wird? Wird es dann auch aus der Familien entfernt? Wird das unterbunden?_
* Ich kann aber den Default entfernen, damit ich die Haushlatszugehörigkeit von jeder Person individuell festlegen kann.

## Übersicht über Anmeldungen

* Auf der Familienübersicht sehe ich alle Anmeldungen für Anlässe. (4h)

## Konfigurierbar über ein Konfigurationsflag

* Global für ganze Instanz (settings.yml) (2h)

# Datenschutz

* Ich kann nur Personen auf die ich Schreibrechte habe zu Familien hinzufügen, damit ich mir nicht zusätzliche Schreibrechte aneignen kann.

## ~~Übersicht über Ansprechpersonen (optional)~~

* Auf der Familienübersicht sehe ich eine im Wagon definierte Auswahl an Ansprechsperson von den Gruppen / Layern von den Kindern. (4h)

**Comment by RolandStuder** [comment]
@codez Optionales auch schätzen wenn es durchgestrichen ist, es geht aber drum, dass wir klar zeigen, dass das nicht einfach dabei ist.

**Comment by RolandStuder** [comment]
Dies ist ein Thema, das von Zeit zu Zeit wieder aufpoppt, aber doch ein rechter Brocken ist zum Implementieren.

**Comment by JugendProNatura** [comment]
Ist für Pro Natura ein wichtiges Feature, da unsere Lageranmeldungen über hitobito laufen und es momentan keine zufriedenstellende Lösung gibt.
Ist es möglich, eine Schätzung für Kosten und Aufwand zu machen und dann zu schauen, welche Organisation wie viel davon übernimmt? Wir gehen davon aus, dass dies für sehr viele Orgas eine wichtige Funktion ist!

**Comment by Vento-Nuenenen** [comment]
Im grunde ist diese Funktion auch für die Pfadi wichtig und Wünschenswert.
Da der Aufwand aber recht gross ist, haben wir uns als alleinstehende Organisation nicht da ran Getraut.

Möglicherweise könnten wir da zusammenspannen, falls wir in der Funktionsweise des Features übereinkommen...

**Comment by KunoKunz** [comment]
Wir haben am letzten Communitymeeting besprochen, dass @olibrian im Februar ein Meeting organisieren wird, um die möglichen gemeinsamen Vorhaben für 2020 zu besprechen. Neben diesem Feature geht es vor allem auch um die Themen Ehemalige/Archivierung sowie Datenschutz. Passt dies für euch?

**Comment by JugendProNatura** [comment]
Passt für uns, wir versuchen in dem Fall am Meeting anwesend zu sein. Ich denke es ist absolut sinnvoll und von unserer Seite her denkbar, sich bei diesem Feature zusammen zu tun.

**Comment by chrusu** [comment]
![image](https://user-images.githubusercontent.com/17568539/110214363-87063780-7ea4-11eb-8140-a94930a2a082.png)

**Comment by richardjubla** [comment]
Ich habe mir zum Thema "Elternzugang" ein paar (unqualifizierte) Gedanken gemacht. Falls sie Hilfreich sein sollten (und das Security-Konzept) nicht stören, möchte ich sie als Alternative/Ergänzung einbringen:

- Hitobito kennt die Funktion/Rolle "Imitieren" https://*.puzzle.ch/groups/*/people/*/impersonate 
- Hitobito (jubla) kennt die Personen Info "Familienmitglieder" (Geschwister) oder ähnliche Personen-Verbindungen

_Wäre es möglich und sinvoll, die Imitieren-Funktion für den Verwaltenden zu verwenden? Verwalter können so ihre Kinder (zugeteilte, verwertbare Accounts) imitieren und so alle gewünschten Funktionen durchführen._

Neu gibt es die Rolle "Verwalter*in". Diese Rolle kann "Familienmitglieder" oder Personen welche sich explizit selbst zur Verwaltung entscheiden auch imitieren.  

Abhängigkeiten:
- Die Option "Familienmitglieder" und "Imitieren" muss so eingeschränkt werden, dass Rechte-Ausweitung oder eine Übernahme eines "fremden" Accounts niemals möglich wird. Eltern/Verwalter können keine Kinder festlegen/übernehmen, Verwalter können nicht verwaltet werden. 
- Kinder müssen ihren Eltern/Verwalter auswählen oder durch Bearbeitung zugeteilt werden. Eine weite Möglichkeit wäre auch, lediglich "Versandadresse" oder "Kinder" auf der gleichen/tieferen Ebene als Auswahl zuzulassen. 
- Die Verbindung auf bestimmte Ebenen (Unterste Ebene -> Schar-Ebene/Kinder-Gruppe) beschränken
- Die Verbindung zwischen Verwalter und Kind muss wohl auch entfernt oder vorhandene Rollen explizit ignoriert werden. Der Verwalter darf nicht mehr Rechte/Ebenen erhalten mit der Imitierung des verwalteten Accounts. 
(Beispiel: Eintragen einer Haupt-E-Mail-Adresse / Veränderungen an Rollen / Ebenen / entfernen der Rolle Kind / etc.)


Alternativ könnte ein Personen-Feld "Verwalter*in" (ähnlich wie Familienmitglieder) eingeführt werden welches nur einseitig oder zwingend von einer übergeordneten Rolle gesetzt werden muss. 

Use Case:
Adressverwalter können Verwalter und Kinder miteinander verbinden. Kinder können auch selber ihren Verwalter bestimmen oder entfernen.
Der Verwalter kann dann die Kinder imitieren und für sie alle gewünschten Funktionen wie Eventanmeldung, Mutationen etc. übernehmen. (Selbst wie Weitergabe an einen anderen Verwalter wäre so möglich).

**Comment by carlobeltrame** [comment]
Die Imitieren-Funktion hatten wir bei einem früheren Workshop schon diskutiert und als Lösungsmöglichkeit ausgeschlossen. Ich weiss die Gründe nicht mehr abschliessend auswendig, aber ich glaube es hatte mit schlechter Usability (insbesondere bei SJAS und pro natura bei der externen Anlassanmeldung, aber auch generell) zu tun, und mit der Anforderung dass die Eltern alle Mails empfangen sollen die an die Kinder gehen.

**Comment by richardjubla** [comment]
> Die Imitieren-Funktion hatten wir bei einem früheren Workshop schon diskutiert und als Lösungsmöglichkeit ausgeschlossen. Ich weiss die Gründe nicht mehr abschliessend auswendig, aber ich glaube es hatte mit schlechter Usability (insbesondere bei SJAS und pro natura bei der externen Anlassanmeldung, aber auch generell) zu tun, und mit der Anforderung dass die Eltern alle Mails empfangen sollen die an die Kinder gehen.

**Merci! Ein Versuch wars wert ;-)**
(Eltern könnten ihre eigene E-Mail als "Weitere E-Mails" im verwalteten Account hinterlegen. Die externe Anmeldung wird aus meiner Sicht schwierig bleiben, da die Verwalter-Funktion schwierig "angeboten" werden kann. Bei einer externen Anlass-Anmeldung müsste die Anmelde-Option "Eltern und Kind(er)" gleich die entsprechenden Accounts und Verbindungen anlegen (und sinvoll erklären!) können.)

**Comment by ThomasEllenberger** [comment]
Sämtliche aus diesem Issue entstandenen Issues wurden erledigt:

#1965 - Elternzugang 1-1: Verwalter\*innen - Kind Beziehungen herstellen & Übersicht Familienbeziehung
#1966 - Elternzugang 1-2: Ändern der Basisdaten des Kindes
#1967 - Elternzugang 1-3: Anmelden an einem Anlass
#1968 - Elternzugang 1-4: Digitale Korrespondenz
#1969 - Elternzugang 2-1: Zusätzliche Kinder erfassen zu bestehendem Verwalter\*innen Account
#1970 - Elternzugang 2-2: Neuer Verwalter\*innen Account erstellen und Kinder zu diesem hinzufügen

Nacharbeiten & Bugs werden via Issue #2125 abgehandelt.
