### ISSUE TITLE
Mehrere Personen einem Anlass zuordnen (12h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#605]
* Nach der Auswahl mehrerer Personen #349
* Kann ich diese einem Event zuweisen.
* Der Event kann aus einer Liste ausgewählt werden, es erscheinen nur Events bei welchen ich die Berechtigung habe direkt selbt Mitglieder hinzuzufügen. 
  _=> Das können nach ein paar Jahren hunderte sein. Da braucht es wohl eine Suche._
* Ja nach Eventart muss eine Rolle ausgewählt werden.

**Comment by janissbinder** [comment]
#664

**Comment by RolandStuder** [comment]
Ist implementiert in 1.19
