### ISSUE TITLE
Persönlicher iCal Feed mit meinen Anmeldungen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#606]
* Jede Person kann eine persönliche iCal-Feedadresse abrufen. (4h)
* Der iCal Feed enthält alle Anlässe für die ich eine Rolle habe
* Die iCal Feedadresse kann unter Einstellungen oder auf der eigenen Seite abgerufen werden (To Be Defined) (2h)
* Der iCal Feed ist durch ein Token als Get Parameter geschützt (4h)
* Ich kann das Token / die URL erneuern.  (2h)

Die Tokenvergabe sollte im Hintergrund erfolgen, Personen sollen ohne Hintergrundwissen einen Feed bei sich abonnieren können.

Feed analog bestehendem Event iCal Export.

**Comment by RolandStuder** [comment]
wäre ein guter Kandidat für einen Hackday.

**Comment by adriananderegg** [comment]
Daten somit identisch mit "Meine nächsten Anlässe" auf der persönlichen Seite?

Ich hätte die URL (via Icon?) gleich neben der Liste auf der User-Startseite platziert: 
![image](https://user-images.githubusercontent.com/9968417/43851950-57f1d1d2-9b3c-11e8-9647-10cf4970c462.png)

Reset (allenfalls nochmals inkl. URL) dann unter Einstellungen
![image](https://user-images.githubusercontent.com/9968417/43851778-ed776178-9b3b-11e8-907b-1df664ab474a.png)

Meinungen?

**Comment by RolandStuder** [comment]
@adriananderegg Die Idee mit dem Icon gefällt mir! 

Ob man nur die "Meine nächsten Anlässe" drin hat, oder auch solche die man betreut ist für mich noch offen.

**Comment by fossil12** [comment]
Ich würde noch überlegen ob es aus Sicherheitsgründen besser ist wenn der Link erst generiert wird wenn der Nutzer das Icon anklickt oder auf die Einstellung geht.

**Comment by carlobeltrame** [comment]
Zum Kalenderfeed habe ich noch folgende Rückmeldungen:
* [ ] Der Endtermin stimmt nicht wenn Zeitpunkt 00:00 ist. Es wird jeweils der Vortag angegeben.
* ~~Wenn ich mich neu zu einem Event anmelde, erscheint der Event nicht im Kalender. Zwar ist er im ICS ersichtlich, wenn ich es direkt öffne, aber im Google Kalender kommt der Termin nicht. Auch wenn ich das Kalenderabo lösche und neu hinzufüge kommt der Termin nicht. Wie wird der Termin aktualisiert? Ist dies ein Google Problem?~~ -> es kann bis 12h dauern https://support.google.com/calendar/answer/37100?co=GENIE.Platform=Desktop&hl=de
* [ ] Nach dem Event kommt im Text immer ein Doppelpunkt
