### ISSUE TITLE
Export BSV Kurse für Kantone (PBS)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#607]
[Export BSV-Kurse Kantone.pdf](https://github.com/hitobito/hitobito/files/2269809/Export.BSV-Kurse.Kantone.pdf)

Anforderungen im PDF. Am besten ein globaler ZIP Export, so dass für jeden Kanton und jeder Region ein File generiert wird, das in einem ZIP zusammengefasst ist.

Neu Schätzen:

- Aufbereitung der Daten
- Bereitstellen als CSV-Download (1 Zeile pro Kurs)
- Bereitstellen als JSON
- Zugriff mit API Token erlauben.

**Comment by codez** [comment]
Schätzung:
* User Interface (4h)
* Aufbereitung der Daten (8h)
* PDF generieren (8h)
* Texte PDF (ohne Unterschrift) + Email (1h)
* Tagessatz global konfigurierbar (optional) (4h)
* Zip mit PDFs pro Kanton / Region (abhängig von ausgewählter Ebene) (4h)
* Hintergrundverarbeitung mit Email + Attachment (2h)

**Comment by Michael-Schaer** [comment]
Merci für die Schätzung! Wir haben festgestellt, dass die Lösung recht aufwändig ist, für eine vergleichsweise kleine Funktionalität. Wir wären froh, wenn wir für das Problem eine etwas leichtere Lösung finden könnten (auch mit dem Hintergedanken, dass wir beide Features #607 und #608 umsetzen wollen)

Gibt es eine Möglichkeit, das Feature mit weniger Aufwand umzusetzen?

### Vorschläge / Kommentare

> - Tagessatz global konfigurierbar (optional) (4h)

Ein Input-Feld für den Tagessatz auf dem GUI würde reichen

> - Aufbereitung der Daten (8h)

Die Logik dahinter ist sehr ähnlich wie beim bestehenden BSV-Export. Beispielsweise wird dort bereits auf die ausgewählten Kursarten, sowie auf die 17-30 jährigen TNs gefiltert.

> - PDF generieren (8h)

Die Tabelle im PDF darf so einfach wie möglich gestaltet werden, solange alle wichtigen Daten vorhanden sind.

> - User Interface + Berechtigung (4h)

Das GUI kann analog dem BSV-Export eingebaut werden

**Comment by janissbinder** [comment]
* User Interface + Berechtigung (4h)
* Aufbereitung der Daten (8h)
* Tagessatz global konfigurierbar (optional) (4h)
* Hintergrundverarbeitung + Async Download (3h)

**Comment by RolandStuder** [comment]
Wenn wir das über API Abfrage machen, macht es keinen Sinn mehr den Tagesansatz zu übergeben, dann macht es vielmehr Sinn dass dieser Teil er Logik in der Applikation liegt, welche die API abruft.

**Comment by RolandStuder** [comment]
closing in Favor of #670
