### ISSUE TITLE
LKB Export für PBS

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#608]
Neu Schätzen mit:

- Aufbereitung der Daten
- Bereitstellen als downloadbares CSV
- Bereitstellen als JSON
- Zugriff erlauben mit API Token

[LKB-Export.pdf](https://github.com/hitobito/hitobito/files/2269818/LKB-Export.pdf)

Anforderungen im PDF

**Comment by codez** [comment]
Schätzung:
* User Interface + Berechtigung (4h)
* Aufbereitung der Daten (4h)
* PDF generieren (6h)
* Texte PDF + Email (1h)
* Entschädigung global konfigurierbar (optional) (1h falls bei Export BSV Kurse auch umgesetzt)
* Zip mit PDFs pro Person (2h)
* Hintergrundverarbeitung mit Email + Attachment (2h)

**Comment by Michael-Schaer** [comment]
Bitte noch einmal eine Schätzung machen mit folgenden Anpassungen:

- Die Punkte 3-6 fallen weg	
- Der Excel-Export der Leiterkursbetreuer enthält folgende Spalten, die Daten sind auch übers JSON-API verfügbar:

> Daten des Leiterkursbetreuers [Vorname / Nachname / E-Mail], Kursnummer, Kursbezeichnung, Erster Kurstag, Letzter Kurstag, PBS-Kursart 

- Eine Auswahl der Kursarten und des Datums (Start und Ende) analog BSV-Export ist vorhanden (Nicht alle Kurse sind BSV-Berechtigt)

**Comment by janissbinder** [comment]
* User Interface (4h)
* Aufbereitung der Daten (5h)
* Hintergrundverarbeitung + Async Download (3h)

**Comment by RolandStuder** [comment]
closing in Favor of #670
