### ISSUE TITLE
Flexible Kontexthilfe

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#609]
## Variante A: Statische Hilfe automatisch sinnvoll verlinkt (12h)

![image](https://user-images.githubusercontent.com/194364/43848669-bb1ea400-9b33-11e8-830c-9607fdfdb4cf.png)

---

![image](https://user-images.githubusercontent.com/194364/43848702-d2781ffa-9b33-11e8-92d6-87cbd84faed3.png)

* Statische Hilfeseiten auf der hitobito Webseite
* Generiert aus einem separaten Repository, organisationsspezifische Aspekte können auf separaten Branches geführt werden.
* Hilfebutton auf der hitobito Website führt Benutzer auf die entsprechende eine passende Hilfeseite abhängig von der aktuellen Seite die gerade aufgerufen wir.
* Check ob eine solche Seite existiert

_=> Da braucht es wohl irgendeine Art von Caching oder Hintergrundjob, insbesondere falls organisationsspezifische Seiten und Fallbacks existieren_ 

Schätzung:
* System dass hitobito auf die richtige Hilfeseite verweist
* Keine Schätzung für das System statischer Hilfesseiten. 

## Variante B: (4h)

![image](https://user-images.githubusercontent.com/194364/43851006-d05f0b9c-9b39-11e8-8055-596c5ecdb766.png)

* Auf einer Seite kann der Hilfemodus aktiviert werden. Dann wird zu bestimmten Elementen ein Hilfetext angezeigt.
* Ein allgemeiner Seitentext wird auch eingeblendet
* Hilfetext kann einen externen Link enthalten.
* Mögliche Implementierung: Hilfetexte werden über data-attributes bereitgestellt

Schätzung ohne konkrete Hilfetexte, diese müssen zusätzlich hinzugefügt werden.

## Variante C: (8+4h)

Touren für eine Seite

* Eine geführte Tour, welche die wichtigsten Funktionalitäten einer Seite erklärt.
* Mehre Touren werden definiert für verschiedene Funktionen
* Eine Tour kann über mehrere Seiten führen (+4h)

Schätzung ohne konkrete Touren und Inhalte, diese müssen zusätzlich hinzugefügt werden.

**Comment by carlobeltrame** [comment]
Variante B wurde in in #811 umgesetzt
