### ISSUE TITLE
Rechnung mit externer Adresse stellen (2h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#61]
- Es müssen auch Rechnungen mit einer externen Adresse (nicht auf der jubla.db) erstellt
  werden können.

**Comment by janissbinder** [comment]
@RolandStuder Wie stellst du dir das vor? Sollte es nun wieder die Option geben in der Rechnungsübersicht eine Rechnung zu erstellen welche auf keine in der DB persistierten Personen verweist? Sprich dass man die Adresse einfach von Hand eintragen muss.

**Comment by RolandStuder** [comment]
Genau. Die Verlinkung zur Person sollte optional sein. Also ein neue Rechnung zu erstellen von der Rechnungsliste aus. Button "Neue Rechnung". Dann habe ich ein freies Adressfeld, das ich abfüllen kann.

**Comment by amaierhofer** [comment]
@RolandStuder bei einer normalen Rechnung wird die Empfänger Email automatisch gesetzt (Login email immer vorhanden). Bei einer Rechnung an externen kann dieses Feld leer sein. Macht das Sinn?

**Comment by amaierhofer** [comment]
PDF Export muss noch für fehlenden Rechnungsempfänger angepasst werden.

**Comment by janissbinder** [comment]
https://github.com/hitobito/hitobito/commit/59ebc17decb48453ff86bfc6db09af15497fe624
