### ISSUE TITLE
Rechnung zu mehreren Personen erstellen (1h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#610]

**Comment by codez** [comment]
Wenn ich das richtig verstanden habe, braucht es dafür nur einen Redirect auf das Rechnungserstellungsformular mit den entsprechenden recipient_ids.

**Comment by RolandStuder** [comment]
Ich glaube das ist gemacht in https://github.com/hitobito/hitobito/pull/654/commits/cd7ba3fa282324b474e2cb84f947e7b28d64a0fa
