### ISSUE TITLE
Rechnungsfunktion für andere Länder (16h)

### ISSUE THREAD

**Issue by Janfred** [hitobito/hitobito#611]
Aktuell kann die Rechnungs-Funktion nicht ohne Anpassungen im Core z.B. in Deutschland genutzt werden.
Es beginnt damit, dass die Kontonummer angegeben werden muss, aber hier eine Validation für Kontonummern aus der Schweiz angewendet wird.
Hier würde ich vorschlagen, dass die Kontonummer oder die IBAN angegeben werden muss.
Außerdem muss ein Einzahlungsschein ausgewählt werden, was in Deutschland nicht funktioniert.

* [ ] Kontonummervalidierung für andere Länder
* [x] alternativ: Kontonummer ignorieren, wenn IBAN angegeben ist
* [x] Währung konfigurierbar
* [x] Einzahlungsschein optional

**Comment by RolandStuder** [comment]
@Janfred Danke für die Hinweise. Wir hatten für die Umsetzung der Rechnungsfunktionalität nur ein beschränktes Budget, deshalb konnten wir vorerst diese nur für die Schweiz umsetzen, wo die meisten unser Kunden sind.

Insbesondere war eben wichtig, dass man nicht einfach nur Rechnungen stellen kann, sondern auch eine automatische Verarbeitung der Bankfiles ermöglicht. Wir hatten noch nicht die Zeit zu schauen, wie das in Deutschland möglich ist. Aber wir behalten das sicher im Auge.

Aber es ist wahr, dass wir ja bereits ermöglichen könnten, dass man zumindest Rechnungen verschicken und manuell nachführen kann.

**Comment by Janfred** [comment]
Bezüglich des Verarbeitens von Bankdaten im SEPA-Raum kann ich [pretix](https://github.com/pretix/pretix) sehr empfehlen, um sich Anregungen zu holen.
Die haben einen Import für SEPA-Dateien und matchen mit dem Verwendungszweck.
Da das python ist, wird vermutlich wenig in der Codebase kopierbar sein, aber zumindest die UI ist schonmal spannend

**Comment by RolandStuder** [comment]
Danke für den Tipp! Ich glaube, dass die Zahlungsfiles die man von der Bank erhält (camt.053 / camt.054	inzwischen ziemlich standardisiert sind, daher müsste man vor allem schauen, dass die Bankinformationen und allfällige Einzahlungsscheine korrekt aufbereitet würden.

**Comment by amaierhofer** [comment]
@Janfred Kontonummer ist jetzt nicht mehr notwendig, und beim Einzahlungsschein kann `Keiner` ausgewählt werden, und die Währung lässt sich nun über die Settings konfigurieren. 

Ich hoffe damit sind die grössten Hindernisse aus dem Weg geräumt und Rechnungsstellung wird nun auch für dich möglich.

**Comment by KunoKunz** [comment]
Die grundlegenden Anforderungen sind m.E. erfüllt. Merci allen Beteiligten!
