### ISSUE TITLE
Variable Rechnungsnummern

### ISSUE THREAD

**Issue by Janfred** [hitobito/hitobito#612]
Für einen Verein, in dem ich aktiv bin vergeben wir Rechnungsnummern nach einem bestimmten Schema:
`<Jahreszahl>-<Monat>-<Laufende Nummer>`
für die dritte Rechnung im August 2018 also `2018-08-03`

Diese Rechnungsnummer wird dann auch als Identifikation für den Zahlungseingang auf dem Konto genutzt.

Es wäre schön, wenn man entweder komplett manuell die Rechnungsnummer setzen könnte oder ein Schema für Rechnungsnummern angeben könnte.

**Comment by ThomasEllenberger** [comment]
Feature ist aktuell nicht geplant.
Da dieses Issue bereits 5 jährig ist, schliessen wir dieses.
