### ISSUE TITLE
Sessions Tabelle automatisch aufräumen (3h)

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito#613]
Einen nächtlich laufenden Job erstellen, welcher Sessions mit einem `updated_at` älter als z.B. einem Monat löscht.

**Comment by codez** [comment]
Der Aufwand, das in einem Job zu implementieren, ist etwa gleich gross, wie es einmal von Hand auszuführen. Ausserdem geht es dann nicht mehr vergessen und ist klarer dokumentiert.

**Comment by RolandStuder** [comment]
Liegt schon lange rum, ich nehme das mal ins Impediment Backlog rein.
