### ISSUE TITLE
Fehler beim Upload von Rechnungs-XML

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#614]
Es sind in payment_processes#create folgende Fehler aufgetreten:

KeyError: key not found: "CdtDbtInd"
KeyError: key not found: "NtryDtls"

**Comment by KunoKunz** [comment]
Der Upload scheint nun zu funktionieren, aber Zahlungen werden nicht erkannt. Wichtig ist, dass 

<CdtDbtInd>CRDT</CdtDbtInd> 

erkannt und verarbeitet werden.

**Comment by RolandStuder** [comment]
Implemented in 1.19.3
