### ISSUE TITLE
Trennzeichen bei E-Mail-Adressen Export

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#615]
Der Client bei insieme kann mit Komma nicht umgehen. Können als Separator auch Semikola verwendet werden?

**Comment by fossil12** [comment]
Bei der Jubla gab es dieses Problem auch schon. Anscheinend kann Outlook nur mit Semikolons umgehen. Bei anderen Mail-Clients geht manchmal beides. Teilweise aber auch nur Komma.

**Comment by RolandStuder** [comment]
Outlook kann so konfiguriert werden, dass es auch Kommas akzeptiert: siehe https://www.lifewire.com/commas-to-separate-email-recipients-1173680

**Comment by KunoKunz** [comment]
Danke für den Hinweis. Habe dies insieme so weitergemeldet und schliesse dieses Issue.
