### ISSUE TITLE
Anlass: Abmelden/entschuldigen

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#616]
Für einzelne Anlässe wäre es wünschenswert, wenn ich mich dafür abmelden/entschuldigen könnte und dies so auch festgehalten wird.

**Comment by RolandStuder** [comment]
Meines Wissens ist das bereits möglich, muss aber bei jedem Anlass individuell unter Anmeldung konfiguriert werden. 

Zudem gibt es in gewissen Wagons spezielle Anmeldestati

**Comment by Michael-Schaer** [comment]
Der Wunsch ist bei uns auch schon eingegangen, bei Anmeldungen und Abmeldungen benachrichtigt zu werden. Besonders in den folgenden beiden Fällen wäre es toll, wenn es diese Möglichkeit gäbe:

- Jemand meldet sich selber ab
- Jemand hinterlässt einen wichtigen Kommentar bei der Anmeldung (z.B. Allergie)

**Comment by RolandStuder** [comment]
@KunoKunz Ist dies für dich noch aktuell, es gibt eben eine Abmeldemöglichkeit, allerdings ohne Kommentar oder Notification.

**Comment by olibrian** [comment]
Wurde in https://github.com/hitobito/hitobito/issues/1276 umgesetzt.
