### ISSUE TITLE
Urheber einer Änderung wird beim Log nicht mehr aufgeführt

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#617]
### Beschreibung
Bei einer Änderung an einer Person wird der Urheber nicht mehr im Log notiert. Dies ist Datenschutz technisch sehr problematisch. Ev. besteht ein Zusammenhang mit der Haushaltfunktion.

![address_change_log](https://user-images.githubusercontent.com/1799621/44523457-38c02d00-a6da-11e8-9158-4bc20b516de1.png)

### Problem nachstellen

- Einloggen auf https://pbs.puzzle.ch mit Admin-Account
- Eine Person bearbeiten (z.B. https://pbs.puzzle.ch/de/groups/1/people/1917)
- Log der Person überprüfen

#### Zusatz
Dazu kommt eine kleine Unschönheit im Log (ohne Priorität): Bei jeder Änderung der Person wird unnötigerweise ein Text zum Haushalt ins Log geschrieben:
> Hans Müller / Vulgo wurde vom Haushalt () entfernt.

> Haushalt (Jano Baarck, Tillmann Förster, Julian Förster) wurde aktualisiert.

**Comment by RolandStuder** [comment]
Danke für die Meldung, schaue ich mir an, inklusive https://github.com/hitobito/hitobito_cevi/issues/36

**Comment by RolandStuder** [comment]
Wie hatten dieses Problem bereits einmal: https://github.com/hitobito/hitobito_cevi/issues/21 Wieso ist das zurück?

**Comment by RolandStuder** [comment]
Problemanalyse:

Das hat alles mit den Haushalten zu tun:

Siehe: https://github.com/hitobito/hitobito/blob/master/app/domain/person/household.rb#L43

    def persist!
      Person.transaction do
        empty? ? remove : save
      end
    end

Es wird nie geprüft, ob sich die Person bereits zu einem Haushalt gehört hat. Bei leerer `household_people_ids` wird `remove` ausgeführt, was immer einen Logeintrag macht, auch wenn die Person bereits vorher schon in gar keinem Haushalt drin war.

Ist die Person in einem Haushalt, dann wird ebenfalls immer ein Eintrag gemacht, unabhängig davon ob bei der Adresse etwas geändert hat oder nicht. 

Dies führt zu all diesen unschönen Einträgen.

Und für Papertrail wird aus unerfindlichen Gründen der `housemate` übergeben statt des aktuellen Benutzers https://github.com/hitobito/hitobito/blob/master/app/domain/person/household.rb#L148
