### ISSUE TITLE
Ein bestimmter Kurs erscheint nicht, der angezeigt werden sollte

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#618]
Wir haben einen Fehler bei der Anzeige der Kurse gefunden.
 
Problem (auf Produktion) nachstellen:
 
Folgende Ansicht öffnen («nur Region Basel»):
https://db.scout.ch/de/groups/299/events/course?filter=layer&returning=true&sort=dates_full&sort_dir=asc&year=2018
Der Kurs mit dem Namen «Einführungskurs und Weiterbildung Biberstufe 2018 (PBS CH BS 801-18)» erscheint
 
Folgende Ansicht öffnen («Alle»):
https://db.scout.ch/de/groups/299/events/course?filter=all&returning=true&sort=dates_full&sort_dir=asc&year=2018
Der selbe Kurs erscheint nicht
Wenn die Sortierung auf Datum (absteigend) gesetzt wird, so erscheint der Kurs an erster Stelle
 
Dabei handelt es sich um folgenden Kurs:
https://db.scout.ch/de/groups/299/events/6979

**Comment by codez** [comment]
Scheint ein [Rails Issue](https://github.com/rails/rails/issues/30531) zu sein.

Es erfolgt tatsächlich ein erstes Query mit `SELECT DISTINCT `events`.`id`, event_dates.start_at AS alias_0`, welches zwar 50 ids, aber nur 33 verschiedene zurück liefert. Zwei ids und damit Events fehlen. Wenn die Sortierung umgekehrt wird sind in den 50 ids offenbar alle 35 verschiedenen enthalten.

Der im Issue beschriebene Workaround könnte bei uns wohl auch angewandt werden.

**Comment by RolandStuder** [comment]
Tritt auch bei Insieme auf, Besipiele:

- Kursübersicht insieme Region Bern 2018: https://desk.insieme.ch/de/groups/4/events/course?returning=true
- Da sollte die "Kinderwoche Sommer 2018" auftauchen: https://desk.insieme.ch/de/groups/4/events/1856.html

- Kursübersicht insieme Kanton Bern 2019: https://desk.insieme.ch/de/groups/3/events/course?year=2019
- Da sollte die "Sommerwoche Kinder 2019" auftauchen: https://desk.insieme.ch/de/groups/4/events/1996.html

**Comment by RolandStuder** [comment]
@janissbinder Wie gross ist der Aufwand, dies zu lösen, mit dem Workaround, der hier beschreiben ist? https://github.com/rails/rails/issues/30531
