### ISSUE TITLE
Aktivjahre persistieren (4h)

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#622]
Um die Performance der Filter zu verbessern, ist es sinnvoll, die Aktivjahre (siehe #599) zu persistieren. Wenn sie in der DB gespeichert werden, müssen sie manuell aktualisiert/neu berechnet werden. Da die Aktivjahre nur kalenderjahrgenau sind, müsste es neu berechnet werden, wenn

- [ ] sich das Kalenderjahr ändert
- [ ] neue Rollen hinzukommen
- [ ] Rollen entfernt werden

Bei der Änderung des Kalenderjahres wäre ein Delayed Job Anfang des Jahres notwendig, der alle Aktivjahre neu berechnet. Die sollte aber auch via rake-Task möglich sein, um eventuelle Fehler beheben zu können. 

Es ist fraglich, ab wievielen Mitgliedern pro Verein, die live-Berechnung ein Problem wird. Bei 100 Mitgliedern mit wenigen Rollen war es bereits ein Problem. Bei einem anderen Zieljahr (#601) muss immer die live-Berechnung gemacht werden.

**Comment by KunoKunz** [comment]
Der Ablauf beim SBV ist m.W. wie folgt: 
Der  kantonale Verband erstellt eine Liste im September (für das Folgejahr), danach erfolgt die
Administration im Verband. An der Delegiertenversammlung (oder an einem ähnlichen Anlass) finden die Ehrungen danach statt. Es gibt bis zu 1000 neue Veteranen pro Jahr: Die heutige Anzeige (50 Personen pro Seite kann so belassen werden
