### ISSUE TITLE
Migration SBV (16h)

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#624]
Migration der heutigen Datenbanken Swoffice & Musicgest sowie Import der Suisa-Werkliste.

- Personen- und Vereinsdaten aus den "Musicgest"-Kantonen sollen nur von dort übernommen werden.
- Die fehlenden Angaben sollen von den Org. selber erfasst werden. Ausnahme Korrespondenzsprache (F) und Land (CH) können fix vorgegeben werden
- Suisa-Werkliste: wie bereits besprochen importieren wir nur die Angaben (Titel, Komponist, Arrangeur), die eindeutig zuordbar sind (Die CSV-Werkdatei ist nicht normalisiert und zur gleichen SUISA-ID gibt es teilweise mehrere mögliche Kombinationen).

**Comment by KunoKunz** [comment]
Ergänzungen und Änderungen für die Migration
* [ ] Besetzung wird nicht richtig angezeigt (translation missing: de.activerecord.attributes.group.besetzungen.h)
* [ ] Neuer zusätzlicher Wert für Besetzung: "Tambouren und Perkussion"
* [ ] Vereins-ID aus Swoffice ebenfalls übernehmen

* [ ] SUISA-Meldungen von 2018 und früherer Jahre werden nicht importiert. Gestartet wird mit der Werkliste, welche wir von der SUISA erhalten haben

**Comment by KunoKunz** [comment]
Zum Zeitplan: 
- 2018-11-01 Testsystem bereit für Datenbereinigung (Die Bereinigung der migrierten Daten soll bereits im Testsystem erfolgen und danach in die produktive Version übernommen)
- 2019-01-20 Swoffice wird stillgelegt
- 2019-02-01 Produktiver Start hitobito SBV

**Comment by kronn** [comment]
Zu den Musicgest-Wünschen:

Ja, die Kreise können übernommen werden. Es scheint - mit dem jetztigen Erfahrungsstand - relativ leicht machbar. 
Aktiv/Passivmitglieder: Soweit ich sehe, gibt es "Mitglieder und Nicht-Mitglieder". Diese Information ist pro Musiker-Verein-Zuordnung vorhanden. Bisher behandeln wir dieses Feld nicht speziell.
Ehemalige Rollen werden ausgelesen und migriert. Wenn eine Person gar keine aktive Mitgliedschaft mehr hat, wird sie jedoch noch nicht angelegt. Wie weit diese Historie geht, kann ich nicht eindeutig sagen.

- [ ] Kreise aus Musicgest migrieren
- [ ] Nichtmitgliedern die Passivmitglieder-Rolle geben
- [ ] auch Personen anlegen, die keine aktive Rolle mehr haben
