### ISSUE TITLE
Filter für Ehemalige

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#625]
Wenn Rolle „Aktivmitglied“ (nur diese, Passivmitglieder nicht) gelöscht wird, soll
die Person automatisch unter den Ehemaligen aufgeführt werden. Auch, wenn diese Person bspw. noch
Ehrenmitglied ist.

Ehemalige Mitglieder sollten als solche ebenfalls ersichtlich sein (mit Anzeige der Rolle von –
bis). 

## Entscheid:

- Wir setzen #303 um, damit man Personen mit abgelaufene Rollen Zugriff hat.
- Die ehemaligen Mitgliedschaften sind bereits heute im Verlauf ersichtlich.
- Erklärung, wie man die Filtern benutzen kann

**Comment by KunoKunz** [comment]
Problemstellungen sind die Zugriffsrechte (wenn sie keine Rolle haben) und - wenn es über eine Rolle gelöst wird - diese danach eigene Regeln hat (ich bin "Mitglied" bei den ehemaligen Mitgliedern....).

**Comment by KunoKunz** [comment]
@RolandStuder gibt es aus deiner Sicht und den Erfahrungen mit der Jubla noch etwas zu ergänzen? Issue bitte danach nach "ready" schieben

**Comment by RolandStuder** [comment]
Die Erfahrungen mit der Jubla haben gezeigt, dass die Lösung über automatische Rollenzuweisungen nicht so einfach nachzuvollziehen ist. Wir hatten dies gemacht, da damit die korrekten Zugriffsrechte erteilt werden und man den Ehemaligen Status auch konsistent wieder entfernen werden kann. Nach diesen Erfahrungen glauben wir es ist besser, das nicht automatisch zu machen. Wir wollen einen Filter bieten, um die entsprechenden Personen zu finden. Will man mit diesen Personen weiterarbeiten, so kann man diese einer Gruppe hinzufügen.

Ich passe das Feature in der Beschreibung entsprechend an.

**Comment by RolandStuder** [comment]
@KunoKunz Habe mir beim Aufschreiben noch die Gedanken gemacht, das wir wohl besser die bestehenden Filter einfach ersetzen, weil es inhaltlich wohl mehr Sinn macht, die Filter auf die Personen zu beziehen und nicht auf die Rollen, also folgendes:

![filter ehemalige 3](https://user-images.githubusercontent.com/194364/47424960-3a18df00-d789-11e8-9c13-81d12be6b33a.png)

Der heutige Filter, der nach Zeitraum einschränkt, macht folgendes:

- Findet Personen, bei welchen eine Rolle hinzugefügt wurde, auch wenn die Person schon eine der ausgewählten Rollen hatte.
- Findet Personen, bei welcher eine Rolle gelöscht wurde, auch wenn die Person immer noch eine andere der ausgewählten Rollen hat.

Ich glaube, das nun beschriebene Verhalten entspricht eher den Erwartungen: Ich finde Leute die aus einem Pool rausgefallen sind, oder in einem Pool von Personen neu erscheinen. Das ist was doch was ich brauche...
