### ISSUE TITLE
SUISA Modul Verbesserungen / Korrekturen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#635]
* [x] Suisa Tab erscheint nicht auf Verein, auch wenn ich übergeordnet berechtigt bin.
* [x] Löschen eines Werks aus der Liste funktioniert nicht.
* [x] Typeahead enhält nur Titel, sollte auch die Komponist, Arrangeur und Verlag enthalten.
* [x] Beim Bearbeiten einer Aufführung sehe ich nur Titel, sollte auch die Komponist, Arrangeur und Verlag enthalten.
* [x] Werke sollten nur von oberster Ebene gelöscht oder bearbeitet werden können.
* [x] SUISA nicht auf eigenem Sheet, ist ja nicht untergeordnet (war falsch im Mockup)

**Comment by KunoKunz** [comment]
* [ ] Datum der letzten Änderung auf Aufführung anzeigen
