### ISSUE TITLE
Auffinden von "gelöschten" Personen

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito#64]
## Story:

Als Adressverwalter will ich Personen, deren Rollen ich kürzlich gelöscht habe leicht auffinden können, um ihnen wieder eine angemessene Rolle zuteilen zu können.
## Ist:

Lösche ich von einer Person die Rolle verschwindet sie aus meiner Sicht und kann sie nur auffinden, indem ich sie erneut über die Suche hinzufüge.

## Lösung

Einfache Lösung:

- Neuer Navpunkt wie eine Gruppe auf der Ebene mit dem Namen "Gelöscht"
- nur sichtbar für Personen :layer_full oder :layer_and_below_full
- Wenn Person 0 Rollen hat, wird sie hier aufgeführt, sofern, die LETZTE Rolle zu dieser Ebene gehört hat.
- Zeilenwerk  klärt mit pzumkehr ab, ob das als Attribut auf Person geführt werden sollte.
- Hinzufügen von neuen Rollen dort direkt ermöglichen. Gleicher Dialog wie beim Rollen mutieren
- Kein Ablaufdatum, Personen bleiben dort immer drin.
- Will jemand Zugriff auf eine "gelöschte Person" bekommen (hinzufügen in Gruppe, Abo, ...), so gelten die gleichen Freigabe-Prinzipien wie immer. (hier muss also nichts unternommen werden).

![](https://wearecube.mybalsamiq.com/mockups/4968255.png)
edit: https://wearecube.mybalsamiq.com/projects/hitobito/Auffinden%20von%20gel%C3%B6schten%20Personen%20issue%2064

**Comment by RolandStuder** [comment]
Danke für das Issue. Sicher ein Verbesserungspunkt für hitobito.

Endgültiges Löschen müssen wir ermöglichen, aktuell können Dubletten nicht einmal manuell beseitigt werden.

Macht es Sinn, dass die letzte Gruppe mit Zugriff die Person löschen kann. Ist es nicht ein Risiko, dass eine Person auf übergeordneten Ebenen vielleicht die Person wieder aktivieren kann. Ein Löschen aus der Datenbank sollte evtl. nur vom Dachverband aus gemacht werden können. 

Was finden andere dazu?

Bemerkungen:
* Beim CEVI gibt es versteckte Rollen für Spender, diese müsste man berücksichtigen.
* Statistische Daten der Bestandesmeldung sind schon heute so abgelegt, dass nachträglich Rollenänderungen keinen Einfluss haben.
* Ich würde Personen nur bezüglich der Ebene, z. B. Pfadiabteilung als gelöscht darstellen, nicht auch auf Untergruppen, sonst wird es sehr schwierig die Personen zu finden.

**Comment by RolandStuder** [comment]
Ich kopiere hier den originalen Issue Text hin als Referenz, damit ich im oben, die Beschreibung anpassen kann.

Aktuell besteht ein Problem mit dem Löschen von Personen:
- Es kommt vor, dass bei einer Person aus Versehen die Rollen gelöscht werden. Dannach sind sie nicht mehr (ohne Weiteres) auffindbar.
- Jede Person hat aus Datenschutzgründen das Recht, dass ihre Daten vollständig gelöscht werden. 

Lösungsvorschlag:
- Personen ohne aktive Rolle sind bei der Gruppe, wo Sie zuletzt aktiv waren, im Menüpunkt "Gelöscht" sichtbar. Rechte für die Sichtbarkeit gemäss der letzten aktiven Rolle. 
- Will jemand Zugriff auf eine "gelöschte Person" bekommen (hinzufügen in Gruppe, Abo, ...), so gelten die gleichen Freigabe-Prinzipien wie bei Personen mit aktiven Rollen. Die zuletzt gelöschte Rolle ist für die (allfällige) Freigabe relevant. 
- Im Menüpunkt "Gelöscht" existiert die Möglichkeit, die Daten "endgültig" zu löschen. Dies geht nur sofort, falls die Person über keine "speziellen" Rechte besass und dadurch Daten modifizieren konnte . Andernfalls besteht eine Sperrfrist von 12 (?) Monaten (Sicherstellung der  #Nachvollziehbarkeit).
- Nach dem Löschen müssen allfällige Statistiken (Anzahl Kursteilnehmer, Bestandesmeldung, ...) trotzdem erhalten bleiben. Ggf. Person anonymisiert weiter bestehen lassen. 

Adrian Anderegg wrote:

Nice-to-have:
- Es besteht analog der Ansicht bei Personen in der Ansicht "Gelöscht" die Möglichkeit, gelöschte Objekte (Gruppen, Personen, ...) aus Untergruppen anzuzeigen. #

**Comment by RolandStuder** [comment]
Da dies eigentlich zwei separate Issues sind, habe ich für das endgültige Löschen einn neues issue angelegt #84

**Comment by nchiapol** [comment]
Beim Cevi habe ich noch nie gehört, dass das versehentliche Löschen einer Rolle zu Problemen geführt hätte. Die normale Suche scheint hier ausreichend zu funktionieren. Wir verwenden bis jetzt aber auch den Freigabe-Mechanismus noch nicht. In dem Zusammenhang könnte die vorgeschlagene Lösung tatsächlich nützlich sein.
Der Vorschlag mit einer separaten Gruppe auf Stufe Abteilung finde ich in diesem Zusammenhang sinnvoll.

Eine Alternative, die wohl auch sonst grossen Mehrwert schafft, wäre der Ausbau der Filter/Suche. Ergänzt werden müsste, dass nach Rollen in einem Zeitfenster gesucht werden kann. (Also auch Rollen die jetzt nicht mehr bestehen.)
Ich glaube damit liessen sich die meisten Use-Cases abdecken. Eine Suche auf der Abteilung nach allen Personen die eine Rolle mit Enddatum in den letzten 30 Tagen haben, wäre nahe an der "gelöscht" Gruppe aus dem Vorschlag.
Zusätzlich liessen sich mit einer solchen Suchfunktion aber auch viele weitere Fragen abdecken:

  * Wer war in den letzten 10 Jahren AL?
  * Wer hat im letzten halben Jahr sein Engagement in der Region beendet?
  * Wer waren die Mitglieder der Gruppe XY?

idealerweise aber auch bei Kursen:

  * Wer hat letztes Jahr in einem Kurs mitgeleitet?

**Comment by RolandStuder** [comment]
@nchiapol: Sehr einverstanden! Solche Intelligente Listen würden viel zulassen

Wir haben das schon einige Male in verschiedenen Zusammenängen diskutiert. Es hat eine gewisse Komplexität, so dass der Aufwand relativ gross wird, aber er lohnt sich sicher. Da müssen wir aber sicher zusammenspannen.

Ich habe ein neues Issues erstellt, wo wir das im grösseren Kontext diskutieren können, siehe #122 Dort wären wir sehr froh um Inputs. Daraus müssen wir wohl auch ein Paket schnüren.

**Comment by RolandStuder** [comment]
Ideal wäre natürlich, man könnte dort auch z. B. Gruppenleiter die eigenen Personen sehen könnte, daher wäre von der Idee/Logik her die Lösung mit einem Tab vielleicht sinnvoller. Dann funktioniert es für alle. Allerdings muss ich mir dann die Personen zusammensuchen. Oder wir lösen die Sichtbarkeit eleganter, so dass jeder auf die Gruppe gehen kann, aber man sieht nur die Personen, die bezüglich der letzten Rolle Sichtbarkeit hatten. Das macht es dann aber wohl etwas komplex.

Wahrscheinlich lohnt sich der zusätzliche Aufwand dafür nicht. Also entweder Tablösung mit Gelöscht... oder die Gruppe links. So wie ich die Nutzung bisher beobachte empfehle ich letzter Variante, da meistens das für Leute mit Layer_full Berechtigung relevant ist und ich bei ersterer Variante selbst die Dinge zusammensuchen muss.

**Comment by RolandStuder** [comment]
Einfache Lösung:

- Neuer Navpunkt wie eine Gruppe auf der Ebene
- nur sichtbar für Personen :layer_full oder :layer_and_below_full
- Wenn Person 0 Rollen hat, wird sie hier aufgeführt, sofern, die LETZTE Rolle zu dieser Ebene gehört hat.
- mit pzumkehr abklären, ob das als Attribut auf Person geführt werden sollte.

**Comment by RolandStuder** [comment]
Issue ist gemäss Besprechung aktualisiert.

**Comment by RolandStuder** [comment]
@adriananderegg Ready for testing auf 

Ich weiss nicht, wann genau das Auftritt, aber manchmal kann ich bei gelöschten Personen (Personen ohne Rollen) nicht direkt eine Rolle wieder zuordnen (siehe fehlendes Icon bei Personen im untenstehenden Screenshot.

![image](https://cloud.githubusercontent.com/assets/194364/23748062/5260b402-04c2-11e7-939f-3471a8ac61b5.png)

**Comment by codez** [comment]
Das Icon erschien nicht, wenn gleich eine gesamte Gruppe mit diesen Personen gelöscht wurde. Ist korrigiert.

**Comment by PBS-MichaelBurkhardtKauri** [comment]
Der Navpunkt wurde "Gelöschte Personen" benannt, ich finde die Bezeichnung sehr unglücklich, da es sich gar nicht um solche handelt. Es könnte auch zu Verwirrungen kommen wenn die User meinen, sie können hier effektiv gelöschte Personen wieder aktivieren. Für den Navpunkt finden wir sicher eine bessere Bezeichnung…

**Comment by RolandStuder** [comment]
@PBS-MichaelBurkhardtKauri Nun, selbst können ja Personen nur Rollen löschen, ausser sie haben Admin Berechtigung. Sie können ja hier in einem gewissen Sinnne gelöschte Personen reaktiviere. Vorschläge?

Man könnte auch sagen:
- Ohne Zuordnung
- Nicht zugeordnet
- Ohne Rollen

Hat sonst noch jemand gute Ideen?
