### ISSUE TITLE
Rückmeldungen SBV

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#647]
* [x] Sortierung der migrierten Gruppen stimmt nicht (sollte alphabetisch sein fürs nested set), fixed gemäss @kronn, aber b
* [x] z-index Problem auf Safari (current überdeckt sheet)
* [ ] Abstand zwischen nav und sheets @RolandStuder macht Abklärungen)
* [x] Darstellung Buttons auf Mobile – Buttons nicht sauber aufgereiht und „kleben“ aneinander
* [x] Beim pdf-Export soll die Schrift kleiner und dafür einheitlich sein. Die gepunktete Linie soll weggelassen werden
* [x] Gateway Timeout beim CSV Untergruppenexport auf https://sbv.puzzle.ch/de/groups/1/export_subgroups.csv 

## SUISA
* [x] Suche nur nach Titel (ohne Komponist und Arrangeur). Diese beiden Werte dafür im Suchresultat anzeigen
* [x] Der gleiche Titel kann mehrfach vorkommen. Die Prüfung, ob ein Werk bereits vorhanden ist, bezieht sich auf die Kombination der beiden Felder Titel und Komponist
* [x] Für oben stehenden Punkt sinnvolle Validation Message
* [x] Die Maske für das Erfassen eines neuen Stücks sollte nach dem Erfassen eines Stücks neu initialisiert/zurückgesetzt werden
* [x] Umlaute bei Exporten (Encoding ist wohl nicht korrekt)
* [x] Anzeige so aufbereiten, dass die Felder immer schön untereinander sind oder aber sämtliche Angaben in einen String zusammenfassen
* [x] Anstatt Aufführung #X allgemeiner Begriff „Aufführungen ohne Datum“ einsetzen
* [x] Anzeige der Anzahl bei gespielten Titel als Link auf Bearbeitung
* [x] Wesentlich sind die einzelnen Titel, die Überschriften können in gleicher Grösse wie die Titel in
einer schwächeren Farbe dargestellt werden
* [x] Datum der Änderung auch noch auf der Übersicht anzeigen (zuletzt geändert: XX.XX.XXXX)
* [x] Datumsformat ändern TT.MM.JJJJ
* [x] Titel löschen entweder nicht möglich oder nur durch Super-Suisa-Admin mit Hinweis, dass
dieser aus allen Listen gelöscht würde.

**Comment by RolandStuder** [comment]
Ich mache einen ersten Run über die Suisa Themen und beschreibe, was ich nicht tun konnte.

**Comment by RolandStuder** [comment]
Das meiste ist gemacht, siehe offener Pull Request https://github.com/hitobito/hitobito_sbv/pull/7

**Comment by janissbinder** [comment]
> Umlaute bei Exporten (Encoding ist wohl nicht korrekt)

Das encoding ist per default auf ISO-8859-1 gestellt worden damit excel die Files besser lesen kann. Soll ich das trotzdem umstellen?
