### ISSUE TITLE
Konzept: Handling beim Löschen von Gruppen / Personen

### ISSUE THREAD

**Issue by janissbinder** [hitobito/hitobito#649]
Welche Daten sollten persistiert bleiben und welche können verschwinden, wenn Gruppen oder Personen gelöscht werden?

Beispiel Invoice: Momentan gibt es kein dependent_destroy auf der Gruppe für die Rechnungen. Hierbei könnte man im Falle, dass eine Gruppe gelöscht wird, alle Rechnungen einfach dem Parent zuweisen. So wie es momentan implementiert ist, gibt es nämlich plötzlich Rechnungen ohne Zugehörigkeiten.

Es sind noch andere Beziehungen zu Gruppen und Personen betroffen, welche hinterfragt werden sollten, wie das löschen gehandelt wird.

**Comment by RolandStuder** [comment]
Ich glaube bei Rechnungen würde das eher zu Verwirrung führen.

**Comment by RolandStuder** [comment]
Ich schliesse diese Issue, es braucht kein Konzept. Es muss von Fall zu Fall entschieden und gelöst werden. Wenn das an einem Ort nicht korrekt, dann bitte ein separates Issue anlegen.
