### ISSUE TITLE
Mehrere Verbände mit Superstruktur abbilden

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#651]
Der SBV hat gewisse angefreundete Verbände, welche zum Teil vielleicht auch ihre Suisa Verwaltung wie beim SBV machen werden. Nun stellt sich die Frage, wie wir das bewerkstelligen wollen, es gibt zwei Möglichkeiten:

## Superstruktur

Wir können über den Gesamtverband eine Superstruktur legen, also einen weiteren Layer über der Dachverbandsebene. Das ist Technisch relativ einfach machbar:

### Was bedeutet dies für Aufwand?

- Models erstellen (an den Subgruppen wird nichts geändert)
- Anpassungen der Migrationen
- Anpassungen an Seed Files
- weiteres?
- Logo Upload für jede Ebene
- Mailinglisten von mehreren Domains abholen und korrekt verteilen (dachverband@db.windband.ch ist eine andere Mailingliste als dachverband@db.jodler.ch)

Und:

- Was wäre der vermutete Aufwand einer Migration eines Trees heraus aus einer bestehenden DB?
- Wenn wir dies tun, ist es besser `Root` auf `Dachverband` umzubennen in den Models oder gibt das überall Probleme und deutliche Mehraufwände für die Migration? (Wir können ja die neuen Models `Super` nennen, sollte keine Verwirrung bringen, denke ich.)

### Vor- / Nachteile

- Personendaten sind nicht abgetrennt
- Gruppen und Anlässe können voneinander eingesehen werden.
- Personen können gegenseitig hinzugefügt werden (Vor- / Nachteil)
- Eine nachträgliche Migration in einen eigenen Tenant wäre aufwändig.

## Multitenants

Wir könnten dies natürlich über einen Multitenant ermöglichen. Damit hätte jeder seine eigenen Daten, das wäre Datenschutztechnisch eine saubere Trennung, somit wäre eine spätere breitere Abtrennung einer verwandten Organisation einfacher.

### Was bedeutet dies für Aufwand?

- Mutlitenant Gem in Setup aufnehmen
- Umgebung entsprechend konfigurieren
- Anpassungen am Tenant / damit custom domains gehandhabt werden können (wir würden erwarten, dass dann gewisse Dinge über db.windband.ch oder über jodler.windband.ch oder eben vielleicht über db.jodler.ch oder jodler.db.windband.ch oder so abgehandelt werden würden) was sind da die Möglichkeiten / Probleme / Aufwände um dies zu ermöglichen?
- Zertifikatsmanagement, braucht es dort Anpassungen?
- Backups?

Frage:

Stimmt diese These überhaupt, wird es einfacher sein, einen MT Kunden in eine eigene Instanz zu überführen als einen Tree aus einer Superstruktur herauszulösen?

**Comment by KunoKunz** [comment]
Aus Sicht des Projektteams soll die Variante mit der Superstruktur weiterverfolgt werden. Ist es auch so möglich, pro Verband ein eigenes Logo anzuzeigen und custom Domains (wie oben unter MT beschrieben) zu verwenden? Mit welchen Kosten ist dies verbunden?

**Comment by olibrian** [comment]
Wurde für den SBV entsprechend umgesetzt.
