### ISSUE TITLE
Feld für Datenverwendung auf Person einfügen

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#666]
Auf der Person soll noch eine Checkbox eingefügt werden. Text im Sinne von "ich bin damit einverstanden, Werbung von meinem Verein,Verband etc. zu erhalten".

Kommt das mit dem neuen DSG für die Schweiz wohl für alle Vereine? Interesse zumindest beim SBV und m.W. auch ProNatura.

**Comment by KunoKunz** [comment]
Der Text soll wie folgt lauten: Ich akzeptiere eine Verwendung meiner Adressdaten

**Comment by RolandStuder** [comment]
Ist implementiert, kommt mit dem nächsten Verion
