### ISSUE TITLE
Default-Ansicht auf Personenliste

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#669]
Die Personenansicht auf einer Ebene oder Gruppe selber soll per Default alle Personen der gesamten Ebene oder gesamten Gruppe  inkl. Untergruppen zeigen.

**Comment by RolandStuder** [comment]
Es geht darum, dass es für viele Benutzer eher verwirrend ist, dass sie Personen aus Untergruppen nicht sehen kann. Z. B. bei den Anlässen haben wir das schon geändert. Ich denke es wäre überall sinnvoll dies so zu machen und entsprechende Filter bereitzustellen. Siehe #393

**Comment by nchiapol** [comment]
Falls das im Core angepasst werden soll, müssten wir uns einige Gedanken zu den Auswirkungen auf unsere Konfiguration machen. Entsprechend wäre es wohl gut, dass mit der ganzen Community zu besprechen.

**Comment by RolandStuder** [comment]
@nchiapol Besprecht es doch mal intern. Wir denken, es ist eigentlich das logischere Verhalten. Wir fragen, sicher die anderen Community Members auch um ihre Meinung, bevor wir hier weitergehen.
