### ISSUE TITLE
Erweiterterter BSV / LKB Export für PBS

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#670]
Ersetzt #607 #608,

Nur im PBS Wagon umsetzen.

* [ ] Neuer Button: "Erweiterter BSV/LKB Export", gleich Permissions wie für BSV Export Button 
* [x] Auf /list_courses einen erweiterten BSV Export anbieten, mit folgenden zusätzlichen Spalten:

* Kursart
* Datum (von - bis, Achtung es gibt im Export bereits ein Datum, das ist aber nicht vollständig)
* Kantonalverband
* Regionalverband (falls vorhanden)
* Weitere Spalten für den zugewiesenen LKB (Leiterkursbetreuer)
  * Personen-ID
  * Vorname
  * Nachname
  * Pfadiname
  * Adresse
  * PLZ
  * ORT
  * Land
  * Primäre E-Mailadresse
  * Anrede

* [x] Auf diesen Export soll auch mit API Token zugegriffen werden können.

**Comment by Michael-Schaer** [comment]
Uns fehlen noch zwei Sachen beim Export:

Wenn einzelne TN nur einen Teil des Kurses besucht haben, ist das BSV-relevant. Darum müssten die Anwesenheiten der TN im Export ersichtlich sein. Dies kann auch ganz einfach über einen String ausgegeben werden, z.B. "3x10,4x12,5x1" (TN x Tage).

Im Moment ist es so, dass wir für den BSV-Export für die Kantone die Infos aus beiden Exporten brauchen. Besser wäre, wenn der der Erweiterte Export auch die Felder vom "ursprünglichen" BSV-Export enthält, damit wir nur eine Datei einlesen müssen.

**Comment by RolandStuder** [comment]
@janissbinder Wo ist der Export jetzt hin, ich sehe ihn auf Int nicht? Und baut er nicht bereits auf dem bestehenden SBV Export auf?

**Comment by RolandStuder** [comment]
Ah, ich sehe, das wurde noch gar nicht neu deployed seit dem Merge. Der Kommentar von @Michael-Schaer ist daher etwas verwirrlich. 

@Michael-Schaer Braucht ihr wirklich eine Aufstellung 1x5Tage ... oder reicht die Summe? Werden die Teilnehmertage bisher noch gar nirgends exportiert?

**Comment by RolandStuder** [comment]
@diegosteiner Braucht ihr wirklich eine Aufstellung 1x5Tage, 3x 4 Tage ... oder reicht die Summe? Mir scheint die Teilnehmertage werden noch gar nirgendwo exportiert, obwohl sie erfasst werden, es gibt nur die Anzahl BSV Tage / Anzahl Teilnehmer.

**Comment by RolandStuder** [comment]
@Michael-Schaer Wenn bei einem Kurs keine Anwesenheiten eingetragen sind, was soll dann passieren, soll dann angenommen werden, niemand sei im Kurs gewesen, oder alle?

**Comment by RolandStuder** [comment]
@Michael-Schaer Es ist mir noch nicht klar, was du meinst mit `Infos aus beiden Exporten`, der erweiterte Export enthält alle Spalten aus dem bestehenden BSV Export.

Meinst du vielleicht Angaben, aus dem ganz normalen Export von der Anlassliste aus? also von https://pbs.puzzle.ch/de/groups/1/events/course?filter=layer&returning=true aus?

Weil wir haben als Grundlage den BSV Export verwendet, aber vielleicht wolltet ihr als Grundlage den normalen Anlassexport (der wie ich eben gesehen hatte, die LKB angaben eh schon drin hatte.

@diegosteiner Sinnvollerweise fügen wir beim Export für die Adressangaben zum LKB noch ein Prefix `LKB` ein, ok?

**Comment by diegosteiner** [comment]
@RolandStuder Prefix für Adressangaben finde ich gut. Die fehlenden Informationen sind auch von mir;  Konkret meinte ich, dass **Anzahl Kurstage** und **Anzahl TN** nicht im Erweiterten Export enthalten sind. Aktuell gibt es diese Felder im erweiterten Export:

```
Vereinbarung-ID-FiVer;Kurs-ID-FiVer;Kursart;Kantonalverband;Regionalverband;Kursnummer;Start Datum;End Datum;Kursort;Personen-ID;Vorname;Nachname;Pfadiname;Adresse;PLZ;Ort;Land;Email;Anrede
```

Im normalen BSV Export sind folgende Felder zusätzlich vorhanden:

```
...;Ausbildungstage;Teilnehmende (17-30);Kursleitende;Wohnkantone der TN;Sprachen
```

Mit der oben diskutierten Aufstellung sind diese Angaben allerdings wohl nicht mehr nötig und das Thema hätte sich meiner Meinung nach erledigt (wurde mir soeben klar).

**Comment by Michael-Schaer** [comment]
#### TN und Tage
Ja, wir brauchen die Unterteilung TN und Tage, so wird das PDF etwas transparenter.

#### Exporte:
Sehe ich wie Diego. Was aber noch fehlt, ist die Sprache des LKB. Bitte diese auch noch aufnehmen! Die LKB-Felder mit Präfix wären super! 

#### Was, wenn keine Anwesenheiten eingetragen
Ich melde mich noch dazu (Tendenz nicht aufführen)

**Comment by RolandStuder** [comment]
@janissbinder Hier fehlen noch gewisse Spalten, und dann diese Zusammenstellung von Teilnehmertagen, "3x10,4x12,5x1" (TN x Tage, aber nur für BSV relevante Teilnahmen 17-30 jährige)  (das ist eine neue Anforderungen).

Die Spalten die Fehlen sind in der add_counts Methode, welche nicht verwendet wird (https://github.com/hitobito/hitobito_pbs/blob/e00e7053c9ceda95f1bb1f630604255ff6a8eefc/app/domain/export/tabular/events/advanced_bsv_list.rb#L30)

**Comment by janissbinder** [comment]
Schätzung: 
* Fehlende Spalten hinzufügen: 1h
* Zusammenstellung Teilnehmertage: 10h

**Comment by RolandStuder** [comment]
Weitere Dinge nach Besprechung mit Michael Schär:

- Für die BSV sind andere Zahlen relevant als für die Auszahlung durch PBS. Wir machen deshalb weiter Spalten:
  - Zählung aller Teilnehmer, inkl. Referenten und Küche
  - Tagesaufstellung aller Teilnehmer, inkl. Referenten und Küche
  - Spalte bsv_days nicht exportieren (dient nur als default für bsv_days unter attendences

**Comment by RolandStuder** [comment]
The Pull Request contains all requirements, but probably needs some refactoring. There is some code duplication because we need private methods from the bsv info module from the youth wagon.

As mentioned above:

> Two things should be done better:

> * [ ]  Training_days / bsv_days should be formatted something like sprintf('%g',count) to show 3 instead of 3.0 in export
> * [ ]   Test should make sure, that it actually counts the member, it currently doesn't because the fabricated person returns false for `ch_resident?`

**Comment by RolandStuder** [comment]
@KunoKunz der Pull Request ist bereit: https://github.com/hitobito/hitobito_pbs/pull/90 es muss wirklich nur noch gemacht werden, was im obigen Kommentar steht steht: https://github.com/hitobito/hitobito/issues/670#issuecomment-457176763

**Comment by Michael-Schaer** [comment]
Wir haben festgestellt, dass zwei Sachen noch nicht stimmen:

## Anwesenheiten stimmen nicht im Export
Der Erweiterte BSV-Export liefert teilweise falsche Zahlen. Wir können nicht genau sagen, in welchen Fällen es passiert, aber haben ein Beispiel. Problem Nachstellen:
#### Teilnehmer-Export machen
- Login auf Produktion PBS
- Kurs "PBS CH BS 512-19" finden: https://db.scout.ch/de/groups/299/events/7401.html
- Kurs Exportieren (Alle Angaben)
-> Die Anwesenheiten wurden ausgefüllt (BSV-Tage: 1)

#### Vergleichen mit dem neuen BSV-Export
- https://db.scout.ch/de/list_courses
- Ebene wechseln: Pfadi Region Basel
- Erweiterter BSV-Export:
  - Modul Fortbildung Kindersport
  - 01.01.2019 - 31.12.2019
-> Die Anwesenheiten werden für den Kurs falsch exportiert: 14x0;19x0;
-> Erwartet: 14x1;19x1;

## Fehlende Spalte

#### Aktuell vorhandene Spalten:
- Teilnehmende (17-30) x Tage
- Teilnehmende Total x Tage

#### Benötigte Spalte:
- Teilnehmende Total x Tage, nur 17-30 jährige

Im Prinzip sollen die TN inkl. Kursleitende inbegriffen sein, jedoch nur die 17-30 jährigen (gleiches Format mit Personen x Tage). Bitte die neue Spalte zusätzlich einbauen, es sind beide benötigt.

**Comment by Michael-Schaer** [comment]
Diego Steiner hat hier schon ehrenamtlich etwas gemacht. Bitte die anderen Features bevorzugen und hier noch abwarten, was von Diego kommt.

**Comment by amaierhofer** [comment]
Bitte melden, falls wir hier etwas in Angriff nehmen sollen, sonst warten hier auf weiteren Input bzw den Pull Request von @diegosteiner

**Comment by diegosteiner** [comment]
PR ist jetzt fertig: https://github.com/hitobito/hitobito_pbs/pull/93
