### ISSUE TITLE
Rechnungsmodul - Wünsche Jubla (2w)

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#676]
* [ ] Logo / Briefpapier für E-Mail-Versand der Rechnungen
* [ ] Schriftart auf Century Gothic ändern (CI/CD Jubla)
* [ ] Adresse Empfänger & Block Rechnungsnummer etc. rechts und links anwählbar (je nach
Couvert, Fenster rechts oder links)
* [ ] Mahnung 4. Feld voransetzen für Zahlungserinnerung mit einem „netteren“ Text vor der 1.
Mahnung
* [ ] Rechnungsliste „Fällig seit“ Datum wählbar statt 1 Woche, ...?
* [ ] Rechnungen an alle Scharen senden mit verschiedenen Beträgen möglich? zB. Mitglieder-
Rechnungen?
* [ ] Bei Rechnung – „Drucken“ Auswahl ergänzen mit Rechnung plus Einzahlungsschein auf
Folgeseite. Wenn die Rechnungen nämlich per Mail verschickt werden, ist es mühsam, wenn
der ESR nicht schon in der Datei enthalten ist.

**Comment by RolandStuder** [comment]
Das ist noch so einiges an customization, sind einige Sachen die ich klar ausserhalb des Scope vom grundsätzlichen Rechnungssystem sehe.

- Custom Briefbpapier
- Mehr Konfiguration für Aussehen der Rechnung
- Rechnungen an Gruppen

**Comment by janissbinder** [comment]
## Schätzung
* Logo / Briefpapier für E-Mail-Versand der Rechnungen
```
Kommt Stark auf die Implementierung drauf an:
  * Mit Konfigurierbarem Logo (3PT)
  * Mit Standard Logo (1PT)
```
* Schriftart auf Century Gothic ändern (CI/CD Jubla) **(2h)**
* Adresse Empfänger & Block Rechnungsnummer etc. rechts und links anwählbar (je nach Couvert, Fenster rechts oder links) **(1PT)**
* Mahnung 4. Feld voransetzen für Zahlungserinnerung mit einem „netteren“ Text vor der 1. Mahnung **(2PT)**
* Rechnungsliste „Fällig seit“ Datum wählbar statt 1 Woche, ...? **(1PT)**
*  Rechnungen an alle Scharen senden mit verschiedenen Beträgen möglich? zB. Mitglieder-Rechnungen? **(5PT)**
* Bei Rechnung – „Drucken“ Auswahl ergänzen mit Rechnung plus Einzahlungsschein auf
Folgeseite. Wenn die Rechnungen nämlich per Mail verschickt werden, ist es mühsam, wenn
der ESR nicht schon in der Datei enthalten ist.**(1PT)**

**Comment by KunoKunz** [comment]
* [ ] Doku zu Schnittstelle und Kontakt bei @RolandStuder

**Comment by RolandStuder** [comment]
Kontakt bei Jubla ist Ulli Topf. Doku ist online verfügbar, aber ich bin nicht mehr sicher, welche Sage Version sie verwenden, defintiv nicht die Cloud Version.

**Comment by ThomasEllenberger** [comment]
>     * [ ]  Rechnungen an alle Scharen senden mit verschiedenen Beträgen möglich? zB. Mitglieder-
>       Rechnungen?

Wird aktuell in https://github.com/hitobito/hitobito/issues/1617 umgesetzt.

@richardjubla ist dieses Issue für euch noch aktuell?
Wir würden dieses sonnst schliessen um das Backlog aufgeräumt zu halten.

**Comment by richardjubla** [comment]
**Kurze Antwort: Nicht mehr aktuell: schliessen.**

Keine lange Antwort da weitgehend unbekannt und nicht konstruktiv/zielführend.
