### ISSUE TITLE
Rechnungsmodul - MwSt. konfigurierbar machen

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#677]
* [ ] Zwischentotal und MwSt. wegnehmen und nur Totalbetrag inkl. MwSt. ausweisen 
* [ ] Beträge inkl. MwSt. ausweisen und Steuersatz auf Rechnung rechts anzeigen

**Comment by ThomasEllenberger** [comment]
Issue wird zur Zeit nicht umgesetzt.
Closed.
