### ISSUE TITLE
Abacus Schnittstelle Variante mit Fakturierung in hitobito

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#683]
## Hintergrund

In Issues #598 ist vorgesehen, die Abacus Anbindung mit so zu lösen, dass die Fakturierung in Abacus erfolgt, nur die Auswahl der Personen erfolgt in hitobito, alles weitere passiert in Abacus. Dies stellt eine kostengünstige Variante dar, da nur in eine Richtung Daten gespiessen werden müssen, und hitobito keine Kenntnisse über Dinge wie Kostenstellen / Produktgruppen / Artikel haben muss.

Nachteil dieser Variante ist, dass man auf Seite Abacus das Fakturierungsmodul benötigt, welches teuer ist und auch monatliche Lizenzgebühren mit sich bring.

In diesem Issue soll deshalb eine Variante beschrieben werden, wie man das anders lösen könnte, indem die Rechnungen in hitobito verarbeitet werden, mehr Schritte sollen in hitobito erfolgen. 

### Variante #598 :
    hitobito
      Personenauswahl
    Abacus
      Rechnung erstellen (Positionen bestimmten / Rechnungstext usw....)
      Mahnungen erstellen
      Rechnungen bearbeiten
      Manuell Zahlungen erfassen
      Zahlungsfiles einlesen
      Artikel verwalten
      ...

### Neue Variante?

Wo abgrenzen?

* Erstellt man überhaupt so etwas wie Rechnungen in Abacus? Oder werden nur Bewegungen vom Bankkonto verbucht?
* Was muss man dementsprechend abgleichen von den Buchungen? Einfach ein Link machen, was muss da noch verbucht werden.

## Fragen:

* Wie Verbuchung auf das richtige Konto gemäss Kontenplan? 
  * Manuelle Eintragung auf Artikel?
  * Was bei mehreren Konten auf verschiedenen Positionen einer Rechnung
* Rechnungsstati
   * Gibt es überhaupt die Rechnungen in Abacus? Oder werden dort nur Buchungen hinexportiert
* Was muss alles verbucht werden?
  * Offene Rechnung
  * Teilbezahlte Rechnung
  * Bezahlte Rechnung
  * Offene Rechnung bei Jahreswechsel, anders?

**Comment by KunoKunz** [comment]
Aus der Besprechung mit Cevi und PBS:

Zweite Variante in Ergänzung zu #598:

Es werden zusätzliche Daten übermittelt:
- Betrag
- Kostenstelle (Info von Rechnungsartikel)

PBS braucht nur die Variante 1 #598. Cevi nur die Variante mit der zusätzlichen Info.

* [ ] wie sieht die Schnittstelle auf Seite Abacus aus? Braucht es dort auch beide Varianten oder ist der Record und weitere Verarbeitung einheitlich? Womöglich können auch mit der ersten Variante sämtliche Daten übermittelt werden und die empfangende Seite "weiss selber", was damit zu tun ist?

**Comment by KunoKunz** [comment]
> ## Abgrenzung:
> ### Variante #598 :
> 
> ```
> hitobito
>   Personenauswahl
> Abacus
>   Rechnung erstellen (Positionen bestimmten / Rechnungstext usw....)
>   Mahnungen erstellen
>   Rechnungen bearbeiten
>   Manuell Zahlungen erfassen
>   Zahlungsfiles einlesen
>   Artikel verwalten
>   ...
> ```
> 
> ### Neue Variante?
> Wo abgrenzen?
> 
>     * Erstellt man überhaupt so etwas wie Rechnungen in Abacus? Oder werden nur Bewegungen vom Bankkonto verbucht?
Bei der neuen Variante werden keine Rechnungen in Abacus erstellt. Es wird eher ein neuer Debitor erstellt mit den Informationen zur Person, allenfalls der Kostenstelle und des Betrages.
> 
>     * Was muss man dementsprechend abgleichen von den Buchungen? Einfach ein Link machen, was muss da noch verbucht werden.
Es sind so gesehen eben keine Buchungen sondern Abacus erhält die Information, dass die Person X der Organisation etwas schuldet. Es sollte jedoch sichergestellt werden, dass die gleiche Information nicht mehrmals aufgenommen wird.
> 
> 
> ## Fragen:
> 
>     * Wie Verbuchung auf das richtige Konto gemäss Kontenplan?
>       
>       * Manuelle Eintragung auf Artikel?
Wir haben ja auf den Rechnungsartikeln die Möglichkeit, eine Kostenstelle anzugeben.

>       * Was bei mehreren Konten auf verschiedenen Positionen einer Rechnung 
Hierzu muss noch geklärt werden, ob der Gesamtbetrag der Rechnung oder die einzelnen Positionen übermittelt werden sollen. Ist m.E. auch abhängig vom Aufbau der Schnittstelle auf Seite Abacus.
> 
>     * Rechnungsstati
>       
>       * Gibt es überhaupt die Rechnungen in Abacus? Oder werden dort nur Buchungen hinexportiert
Die Rechnung wurde bei dieser Variante ja in hitobito erstellt. Mahnwesen und das Verbuchen der Zahlung etc. erfolgt danach in Abacus.

> 
>     * Was muss alles verbucht werden?
>       
>       * Offene Rechnung
>       * Teilbezahlte Rechnung
>       * Bezahlte Rechnung
>       * Offene Rechnung bei Jahreswechsel, anders?
Die offene Rechnung respektive die einzelnen Posten davon.

**Comment by KunoKunz** [comment]
Was sind die zusätzlichen Kosten für diese beiden Varianten? Meines Erachtens unterscheiden sich die Varianten nur darin, dass bei der zweiten noch Detailinformationen mitgeliefert werden. Beim sendenden System scheint mir daher der zusätzliche Aufwand nicht so gross. Aber das hängt bestimmt auch mit Abacus zusammen, in welcher Form die Daten dort erwartet und verarbeitet werden können.

**Comment by tschuepbach** [comment]
Hierzu noch die Links der Abacus-Schnittstellen:

Debitoren Stammdaten: https://classic.abacus.ch/fileadmin/htmlfiles/abaconnect/debi/DEBI__Kunden_2017.00_AbaDefault_DE.html

Debitoren Bewegungsdaten: https://classic.abacus.ch/fileadmin/htmlfiles/abaconnect/debi/DEBI__Belege_2018.00_AbaDefault_DE.html#1000003_Number

Ansprechsperson OBT: Herr Dieter Holenstein, dieter.holenstein@obt.ch, 071 243 34 62, 079 635 56 20

**Comment by RolandStuder** [comment]
Wird bis auf weiteres nicht umgesetzt, siehe auch #598

**Comment by RolandStuder** [comment]
Schalte dies auf Inatkiv, wird bis auf weiteres nicht umgesetzt.
