### ISSUE TITLE
Startdatum für eine Rolle editieren

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#688]
Bei der Migration der Mitgliederdaten ist teilweise nicht ersichtlich/bekannt, seit wann eine Person Mitglied beim entsprechenden Verein ist. Als Default wird für diesen Fall das Datum der Migration übernommen, was in den meisten Fällen kaum der Realität entsprechen wird. Daher soll es neu möglich sein, das Startdatum im Verlauf editieren zu können.  

* [x] eine offene Frage in diesem Zusammenhang: wann werden die Mitgliedsjahre einer Person (neu) berechnet?

**Comment by kronn** [comment]
Die Aktivjahre werden einer Person neu berechnet, wenn ein Rolle von Typ "MitgliederMitglied" gespeichert wird. Ausserdem werden die Jahre für alle neu berechnet, wenn ein neues Jahr angefangen hat.
