### ISSUE TITLE
Mail-Versand umstellen

### ISSUE THREAD

**Issue by janissbinder** [hitobito/hitobito#690]
Prüfen ob bereits MailGun verwendet wird oder noch der alte Mailserver im *puzzle.ch Namespace

# Produktion
- [ ] Demo
- [ ] Multitenancy
- [ ] PBS
- [ ] ProNatura
- [ ] Jubla
- [ ] Insieme
- [ ] DSJ
- [ ] Cevi

# Integration
- [ ] Multitenancy
- [ ] SBV	
- [ ] PBS
- [ ] ProNatura
- [ ] Jubla
- [ ] Insieme
- [ ] DSJ
- [ ] Cevi

**Comment by RolandStuder** [comment]
Wir haben am Ende auf den appuio Mailserver umsgestellt und nicht auf Mailgun.  Ich schliesse diese Issues
