### ISSUE TITLE
Multitenancy deployment downtime

### ISSUE THREAD

**Issue by janissbinder** [hitobito/hitobito#692]
Auf Produktion gibt es eine sehr lange Downtime, da alle Tenants während dem deployment migriert werden müssen. Das kann teilweise gut eine Stunde dauern bis das durch ist...

Evtl: https://github.com/influitive/apartment#parallel-migrations

**Comment by RolandStuder** [comment]
Hat keine Priorität, wurde uns noch nie als Problem gemeldet, was heisst aber sehr lange?

**Comment by kronn** [comment]
Die Deploymentzeit (genauer, die Migrationszeit) ist direkt abhängig von der Anzahl der Tenants. Zuletzt hatte ein Deployment ohne neue Migrations circa 45 Minuten gedauert. Wenn Migrations dazu kommen, dauert es locker über eine Stunde.

Mit mehr aktiven Tenants steigt diese Zeit. Mit parallelen Migrations könnte dies beschleunigt werden.
