### ISSUE TITLE
Feature S-Liste PBS 

### ISSUE THREAD

**Issue by janissbinder** [hitobito/hitobito#695]
https://ticket.puzzle.ch/projects/pbsc-vbl/work_packages/44713

**Comment by RolandStuder** [comment]
Weiss nicht, ob das abgenommen wurde. Ich schliesse es aber mal, da es auf Implemented ist.

**Comment by KunoKunz** [comment]
Im Ticket sind noch Rückmeldungen (M. Schär, 24.6.2019) der PBS drin.
