### ISSUE TITLE
Testing Rechnungen (12h)

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#697]
Hier noch die Rückmeldungen vom Testing des Rechnungsmoduls:

[edit ak: Matching beim Import der Campt054-Datei wurde bereits überarbeitet]

### Rechnungsartikel / Selectbox
* [ ] Bei der Auswahl der Rechnungsartikel werden zuviele Einträge angezeigt.

Beispiel:
- Impersonieren Abteilungsleiter https://pbs.puzzle.ch/de/groups/17/people/1382
- Rechnungen -> Externe Rechnung erstellen

Die Selectbox der Rechnungsartikel enthält auch Einträge aus anderen Gruppen/Abteilungen.

### Zahlungen
Versehentlich erfasste Zahlung können nicht gelöscht werden. Die Rechnung zu löschen und neu zu erfassen, ist keine gute Lösung, da dann die ESR für die bereits gestellte Rechnung ändert.

Wenn eine «Teilzahlung» erfasst wurde wird trotzdem der ganze Betrag gemahnt / in Rechnung gestellt.

ak: Im Lösungsumfang ist nicht vorgesehen, diese Use Cases auch noch umzusetzen

### Kleinigkeiten
* [ ] Auch noch aufgefallen ist mir das es nach dem Rechnungartikel erstellen besser nicht auf den Artikel sondern auf die Artikel Übersicht zurück springen sollte.

**Comment by tschuepbach** [comment]
### Ergänzung Rechnungsartikel

- Bei Erstellung über 'Rechnungen -> Externe Rechnung erstellen' erscheinen die Rechnungsartikel mit Artikelnummer **und** Bezeichnung (Name) - vgl. #535 und #675 

- Bei Erstellung einer Rechnung über eine Person -> '+Rechnung erstellen' erscheinen die Rechnungsartikel **nur** mit Artikelnummer -> Bezeichnung (Name) fehlt

### Zahlungszweck

Weiter wird das Feld 'Zahlungszweck' bei Erstellung über 'Rechnungen -> Externe Rechnung erstellen' nicht angezeigt. (Bei Rechnung-Einstellungen mit 'Roter Einzahlungsschein Bank (CH)')

**Comment by KunoKunz** [comment]
Die realisierbaren Punkte wurden in neue Issues übernommen und mit #911 abgearbeitet.
