### ISSUE TITLE
Möglichkeit für Adressen der Mailingliste Hauptdomain zu verwenden.

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#70]
Die PBS hat nachgefragt, wie es möglich wäre nicht nur Mails auf eine Subdomain sondern auf die Hauptdomain anzunehmen, also statt @db.pbs.ch @pbs.ch.

Gibt es Lösungen dafür, welche sicherstellen, dass keine Konflikte entstehen? Ideen?

**Comment by lukasblunschi** [comment]
Ähhh, wer von der PBS hat das denn angefragt? :-)
hitobito hat ja keinen Einfluss darüber, was in den MX-Einträgen von pbs.ch steht. Und, bei den MX-Einträgen wird ja nur ein Mailserver eingetragen, d.h. dieser eine Mailserver müsste dann anhand des Emails entscheiden können, ob das Email an den hitobito Server weitergeleitet werden soll oder nicht - nicht gerade eine einfache Aufgabe...
Auf Seite hitobito könnte der Mailserver wahrscheinlich schon so konfiguriert werden, dass auch eingehende Emails für @pbs.ch angenommen werden, ich denke aber nicht, das damit das Problem gelöst wäre.

**Comment by RolandStuder** [comment]
War in einem Austausch zwischen Adrian, René und Michael gefallen. Hat sicher keine Priorität und der Gewinn wäre angesichts des Aufwandes eher gering.
