### ISSUE TITLE
Bestandesmeldung PBS falsche Aufstellung von Untergruppen

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#700]
Bei der PBS Bestandesmeldung  `group/[id]/census` verhält sich wie folgt:
- auf Bund, werden Kantone aufgelistet
- auf Kanton werden alle Regionen aufgelistet (inkl. auch Kindeskinder des Kantons), aber keine Abteilungen
- auf Region werden alle Abteilungen aufgelistet

Mit anderen Worten auf der Übersicht werden nur ein bestimmter Gruppentyp angezeigt, statt die direkten Kinder mit der korrekten Zusammenfassung. Das führt zu einer unsinnigen Ansicht.

**SOLL**:

Auf Bund / Kanton / Region sollen alle direkten `child layer` angezeigt werden.

Es soll nicht via subgroup_type gehen: https://github.com/hitobito/hitobito_pbs/blob/master/app/domain/census_evaluation.rb#L16

**Comment by kronn** [comment]
Abweichend vom obigen Soll ist vorerst implementiert, dass auf der kantonalen Sicht alle Abteilungen des Kantonalverbands angezeigt werden. Für den Bund und die Regionen ist die Ansicht unverändert.
