### ISSUE TITLE
Einsicht Rechnungen

### ISSUE THREAD

**Issue by smathys** [hitobito/hitobito#701]
Sobald ich die Berechtigung habe, für eine bestimmte Person Rechnungen zu erstellen, sehe ich alle seine ausstehenden und bezahlten Rechnungen, auch wenn diese von einer anderen Organisation gestellt worden sind.

Beispiel aus der Testumgebung:
Meine Rolle:
![image](https://user-images.githubusercontent.com/631965/50958037-10d23a00-14c0-11e9-9fa8-ed2d981938bf.png)

Somit habe ich die Berechtigung für Louis Siegrist Rechnungen zu erstellen. Wenn ich sein Profil aufrufe --> auf 'Rechnungen' klicke, erscheint folgendes:
image
![image](https://user-images.githubusercontent.com/631965/50958052-1760b180-14c0-11e9-8075-5b3e4b4a5c78.png)

Die untersten drei Rechnungen sind von einem anderen Verein, einer anderen Organisation gestellt.

Wenn ich diese anklicke, erscheint folgende Fehlermeldung:
image
![image](https://user-images.githubusercontent.com/631965/50958068-1def2900-14c0-11e9-99f6-8181351d49db.png)

Schön und gut, ich sehe trotzdem alle seine Rechnungen und ob diese bezahlt sind oder nicht.

Dasselbe gilt für alle andere Rollen auf der Ebene 'Region Bern', hängt nicht mit der Rolle 'Administrator/-in Ortsgruppen' zusammen.

see https://github.com/smathys/hitobito_cevi/issues/65

**Comment by MrTinnysis** [comment]
Das Rechnungstab ist bei anderen Personen nicht mehr sichtbar - bug hat sich erledigt und kann geschlossen werden.
