### ISSUE TITLE
PBS Einmaliger Datenexport für Mitgliederdatencheck

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#705]
Die PBS will ihren Abteilungen ein Poster zu ihren Mitgliederdaten bereitstellen, dafür brauchen sie gewisse Exporte.

- Personen mit Qualifikationen
- Gruppen mit IDs und Parents
- Daten aus der Bestandesmeldung.

**Comment by RolandStuder** [comment]
Wir klären, ab, was es ganz konkret braucht, weil viele Daten in einem exportierbaren Format zur Verfügung stehen:

- Personenexport existiert, allerdings fehlen die Qualifikationsspalten, aber vielleicht würde man die dann eh am besten zum Export (Alle Angaben) hinzufügen.
- Gruppenexport existiert, aber ohne Name / Type der übergeordneten Gruppe (enthält aber die ID)
- Bestandesmeldung Daten, könnte man direkt die Tabelle aus der DB member_counts exportieren, diese hat aber eine andere als die geforderte Struktur.

Weitere Frage: Kommt das in Zukunft jährlich?

Wir besprechen dies mit Martin Spielmann und machen dann die Schätzung.

**Comment by RolandStuder** [comment]
[Spezifikation Datenexport MiData für Mitgliederdatencheck_v0.1.xlsx](https://github.com/hitobito/hitobito/files/2802306/Spezifikation.Datenexport.MiData.fur.Mitgliederdatencheck_v0.1.xlsx)

Es braucht nur einen Extraexport der Personentabelle, wie im dokument beschrieben, plus einen "raw" export der Bestandesmeldugnstabelle, wie es sie aktuelle gibt `member_counts`

**Comment by amaierhofer** [comment]
Geschätzer Aufwand ca

- Neuer Personen Export mit allen Qualifikationen  3h
- MemberCounts export 1h
- Rake task und db pull 1h

**Comment by RolandStuder** [comment]
@amaierhofer Export soll an Michael Schär zugestellt werden, NICHT an Martin Spielmann aus Datenschutzgründen.

**Comment by RolandStuder** [comment]
Done
