### ISSUE TITLE
Pdf für Pro Natura anpassen

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#709]
Betroffen ist das pdf für die franz. Kursbestätigung Es soll "Description du cours" statt "Coursdescription" heissen.
[Pro Natura J+S Lagerleiter_in-Kurs _Michèle Ecuyer.pdf](https://github.com/hitobito/hitobito/files/2792294/Pro.Natura.J%2BS.Lagerleiter_in-Kurs._Michele.Ecuyer.pdf)

**Comment by RolandStuder** [comment]
Seit https://github.com/hitobito/hitobito/commit/8e51623859cb0eb926684537218ce98f9629ff3c gefixt, pro natura ist noch auf Version 1.17, ist set 1.18.7 gefixed. Es kommt nur Description, statt "Kursbeschreibung" / "Coursdescription", weil die Zusammensetzung dynamisch war, hatte das nicht mit verschiedenen Sprachen funktioniert.
