### ISSUE TITLE
Authentifizierung via hitobito

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#71]
Für eine einfache Anmeldung an externen Applikationen könnte hitobito eine Schnittstelle zur Anmeldung bereitstellen, z. B. oAuth. Damit könnten Systeme wie eCampus und Phundus angeschlossen werden (oder beliebige andere).

Aus der Diskussion aus dem 4. Community-Meeting:
- Soll es pro Instanz eine Schnittstelle geben, oder gibt es ein Zwischensystem, so dass man nur eine Schnittstelle einbinden muss?

**Comment by lukasmuellerme** [comment]
Ein Zwischensystem welches eine Schnittstelle ermöglich wäre idealer. Wächst hitobito muss so bei den Drittanwendung nicht für jede neue Organisation (welche auf hitobito eine neue Instanz darstellt) manuell eine eigene Schnittstelle eingerichtet werden. Die Frage ist ob die User bei der Anmeldung durch die Kennung der richtigen hitobito-Instanz zugeordnet werden können?

**Comment by KunoKunz** [comment]
Wenn wir die Community-Mitglieder in einer eigenen hitobito Instanz führen wollen, wäre es gut, wenn sie sich mit ihrem angestammten Login anmelden könnten.

**Comment by RolandStuder** [comment]
@KunoKunz Interessanter Gedanke: Es ginge nicht nur um die Anmeldung an einem externen System, sondern um eine Anmeldung an einer anderen hitobito Instanz.

**Comment by indr** [comment]
Aus Sicht des phundus füge ich gerne hinzu: Den Aufwand für die Einrichtung der Schnittstelle zu neuen hitobito-Instanzen stelle ich mir sehr gering vor und kann daher vernachlässigt werden. Evtl. wirds nur eine Frage der Konfiguration.

Mir ist die Handhabung des Falls unklar, wenn ein Benutzer bereits bei verschiedenen hitobito-Instanzen registriert ist. Muss er beim Login am externen System die Instanz (oder Provider) auswählen, dann ist für den Benutzer auch ersichtlich, für welche "Rolle" er sich anmeldet (wobei das beim phundus keinen Unterschied macht) und welches Passwort er einzugeben hat. Kann er als Provider lediglich "hitobito" auswählen, muss er sein Passwort erraten? Ist es das was KunoKunz erwähnte? Vielleicht ist meine Vorstellung von hitobito auch einfach etwas falsch (z.B. Instanz != Tenant/Mandant?).

Wenn man aber abwägt zwischen einer Lösung mit Zwischensystem oder der Auswahl des Providers, sollte man vielleicht auch den Aufwand für Wartung und Betrieb des Zwischensystems miteinbeziehen?

**Comment by diegosteiner** [comment]
Ich möchte mich auch für die Umsetzung einer oAuth-Schnittstelle einsetzen. Hitobito hat schon heute einen riesigen Funktionsumfang und die Anfragen für weitere Features sind zahlreich. Um zu verhindern, dass Hitobito zu einem unwartbaren Monolith wird, sollten wir neue Funktionalität in unabhängiere (Dritt-) Applikationen verlagern, die einzeln wartbar und austauschbar sind. Es werden bereits Efforts und Kommentare in diese Richtung gemacht, aber dafür ist diese Authentifizierungsschnittstelle meines Erachtens notwendig.

Meiner Einschätzung nach ist es kein grosser Aufwand, dies für jede Hitobito-Instanz einzeln aufzusetzen. Schlussendlich vertrauen die externen Applikationen einer Instanz und nicht allen gemeinsam (zumindest in meinen Augen, auch der Komplexität wegen) und sollten auch auf jeweils eine Instanz ausgerichtet sein.

Den Fall sich unter den Instanzen gegenseitig einloggen zu können sehe ich (noch) nicht.

**Comment by fossil12** [comment]
Die Jubla ist an dieser Idee interessiert.

Ich finde auch es sollte keine zentrale Instanz geben, welche die Authentifizierung durchführt. Dies führ zu mehr Aufwand und einer komplizierten Wartung.

Auch für den Nutzer ist dann direkt klar mit welchem Login er sich anmeldet und er erkennt seine Datenbank wieder.

**Comment by RolandStuder** [comment]
Jubla hat dazu auch ein Issue angelegt: http://feedback.jubla.ch/issues/29

**Comment by fossil12** [comment]
Das besser passende Issue von uns wäre: http://feedback.jubla.ch/issues/13

**Comment by MartinGantenbein** [comment]
Anderer Ansatz: Hitobito könnte OAuth-Login anbieten und müsste dann nicht selbst als OAuth-Provider auftreten. Auf der Login-Seite könnte man statt via E-Mail/PW auch via Google, Facebook, Twitter, Github, ... einloggen.

**Comment by KunoKunz** [comment]
In eine Anmeldung via Google, FB und Twitter würde ich aus ideologischen Gründen nichts investieren.

**Comment by adriananderegg** [comment]
#247

**Comment by RolandStuder** [comment]
Ich schliesse dieses Issue zugunsten von #247, damit nicht parallele Diskussionen laufen.
