### ISSUE TITLE
Bug: Mysql2::Error: Illegal mix of collations

### ISSUE THREAD

**Issue by janissbinder** [hitobito/hitobito#711]
## Errbit Error
Tritt seit einer weile fast halbstündlich auf.

`Mysql2::Error: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='`
https://errbit.puzzle.ch/apps/529c60a2de77482d71027b0a/problems/5c27b1d7da45d4bbec064646

**Comment by amaierhofer** [comment]
Wurde bei pbs blacklists beobachtet. Dort habe ich manuell auf Produktion die Collation der black_lists tabelle auf utf8_generic_ci gesetzt setzt `ALTER TABLE black_lists CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;`. Damit sollte auf dieser Tabelle das Problem nicht mehr auftreten.
