### ISSUE TITLE
Exporte auf MT-Instanzen funktionieren nicht

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#712]
Es gibt Probleme mit den Exporten in den MT-Umgebungen.

Bsp:
https://team.hitobito.com/de/groups/18/people#
- CSV- und Excel-Exporte laufen ins Leere

Die Kadetten und weitere Nutzer haben das Problem auch. Allerdings scheint es nicht genereller Natur zu sein. Hier gehen die Exports nämlich: https://team.hitobito.com/de/groups/1/people

**Comment by amaierhofer** [comment]
Lang an dem MailRelay job, der eine Email nicht verarbeiten konnte. Das hat die anderen jobs blockiert.

**Comment by RolandStuder** [comment]
Ist das also nun resolved?

**Comment by RolandStuder** [comment]
Habe es kurz getestet, geht nach wie vor nicht, das Problem ist nicht gelöst. Genau gleiche Situation wie vorher. Und sollten nicht E-Mails die nicht verarbeitet werden können, nicht länger blockierend sein?

**Comment by KunoKunz** [comment]
Beim bdef läuft der CSV-Export für Untergruppen endlos. Da scheint schon noch nicht alles gefixt zu sein.

**Comment by kronn** [comment]
Ich habe gestern den Untergruppen-Export von BDEF angesehen. Es gab keine blockierenden Jobs und  der konkrete Export-Job wurde anscheinend bearbeitet. Es wurde jedoch keine Datei geschrieben. Ich konnte die Daten jedoch manuell auf der Railsconsole exportieren und in eine Datei schreiben. Nach meiner Beobachtung ist der Fehler damit auf die Klasse `AsyncDownloadFile` einzugrenzen, ich habe jedoch noch keinen offensichtlichen Fehler gefunden.

**Comment by RolandStuder** [comment]
Hast du überprüft ob die Filenamen vom AsyncCookie perfekt mit dem vom File übereinstimmt? Das war bei Insieme mal das Problem, vielleicht wird die Timestamp zwei mal vergeben oder so.

**Comment by kronn** [comment]
Es wurde gar keine Datei erzeugt. Ich hatte eine Datei manuell erzeugt und so benannt, wie es erwartet wurde. Daraufhin startete der Download. Lediglich das Erzeugen der Datei fehlt also.

**Comment by KunoKunz** [comment]
> Es wurde gar keine Datei erzeugt. Ich hatte eine Datei manuell erzeugt und so benannt, wie es erwartet wurde. Daraufhin startete der Download. Lediglich das Erzeugen der Datei fehlt also.

also zurück zum Start oder hast du dies gleich behoben?

**Comment by kronn** [comment]
zurück zum Start, ich habe den Fehler noch nicht gefunden.
