### ISSUE TITLE
Rechnungen erstellen - Kodierzeile ESR+

### ISSUE THREAD

**Issue by tschuepbach** [hitobito/hitobito#717]
Die Platzierung der Kodierzeile bei Rechnungen ohne Betrag (ESR+) ist fehlerhaft.

Die Koderzeile müsste **rechts** und nicht links **ausgerichtet** sein.

![image](https://user-images.githubusercontent.com/40494600/51662333-c8cd1000-1fb3-11e9-880f-8090e5e486a3.png)

Verglichen Kodierzeile ESR:

![image](https://user-images.githubusercontent.com/40494600/51662365-e26e5780-1fb3-11e9-9e27-714f7532c7da.png)

Verglichen Anforderungen an die Kodierzeile der Post:

![image](https://user-images.githubusercontent.com/40494600/51662656-d6cf6080-1fb4-11e9-8939-069ef9ede664.png)

see smathys/hitobito_cevi#70

**Comment by smathys** [comment]
Wir habe zu diesem Issue seit 2 Monaten kein Feedback bekommen
