### ISSUE TITLE
Issues Migration SBV

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#719]
Der Verein https://db.windband.ch/de/groups/12299 und seine Mitglieder-Gruppe wurden nach dem  Import reaktiviert.
* [ ] können die Mitgliedschaften der Personen auch wieder aktiviert werden (= Enddatum der Mitgliedschaft 30.1.2019 löschen?)?
* [x] weshalb wird hier die Rolle Präsident noch als aktive Rolle aufgeführt? https://db.windband.ch/de/groups/12060/people/62441

**Comment by didierber** [comment]
Andere Verein zu reaktiviern:
https://db.windband.ch/fr/groups/16344
und das Enddatum der Mitgliedschaft von 30.1.2019 löschen

**Comment by KunoKunz** [comment]
> Andere Verein zu reaktiviern:
> https://db.windband.ch/fr/groups/16344
> und das Enddatum der Mitgliedschaft von 30.1.2019 löschen

@didierber sind die Mitglieder dieses Vereins in der Datenbank drin? Könntest du ein paar Personen-IDs hier verlinken? evtl. war der Verein auch doppelt vorhanden bei der Migration und so können wir die korrekte Zuordnung wiederherstellen. Danke!

**Comment by didierber** [comment]
Einigen Mitglieder von Versoix sehe ich in der 
https://db.windband.ch/fr/groups/16344/deleted_people
BALMER Catherine, Decre Lucien, Comminot Pascal, ...

Personnen in der gelöschte Liste haben keinen Link, so kann ich das Person-ID nicht sehen. Gelöschte Personnen kann ich nicht in der Suche finden.

**Comment by didierber** [comment]
In Ordnung. Issue kann geschlossen werden.
Anderen Vereine für FJM müssen reaktiviert werden: Isse #723

**Comment by KunoKunz** [comment]
wird gemäss D.Bérard geschlossen
