### ISSUE TITLE
ESR-Ablösung per 2018

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#72]
Der in die Jahre gekommene DTA-Standard für elektronische Zahlungsaufträge wird ersetzt. Ab Mitte 2018 wird der DTA-Standard nicht mehr unterstützt.

http://www.akb.ch/firmenkunden/konten-zahlen/zahlungsverkehr/neuer%20zahlungsverkehr/harmonisierung%20im%20schweizer%20zahlungsverkehr.aspx#tab-1

Evtl. bietet dies die Gelegenheit, den beteiligten Organisationen hitobito für die Rechnungsstellung schmackhaft zu machen.

**Comment by RolandStuder** [comment]
Wurde hierzu etwas im Community Meeting besprochen?

**Comment by RolandStuder** [comment]
Duplikat von #589
