### ISSUE TITLE
Migration SBV für FJM (Fédération Jurassienne de Musique)

### ISSUE THREAD

**Issue by didierber** [hitobito/hitobito#723]
Für den Verein "Union Démocratique Boncourt" sehen wir keine Mitglieder. Die Personnen sind jedoch vorhanden (falls man sie in "Person hinzufügen" sucht).
Scheint ein Berechtigungsproblem zu sein...
https://htbt-sbv-prod.appuioapp.ch/fr/groups/11682/people
25 Mitglieder, wie Caritey Alain, Claude Morane, Crelier Serge, Crétin Olivier, ....

Der Präsident (Vorstand) habe ich selbst hinzugefüt, aber man sieht dass er jetzt 2x die Rolle 'Vorstand Präsident" beistzt.

Sicher haben noch anderen Vereine das gleiche Problem.

**Comment by didierber** [comment]
Beim Verein "Batterie-Fanfare L'Audacieuse Bienne" sehen wir nur 6 Mitglieder (1 doppelt). Aber sie sind 17.
https://htbt-sbv-prod.appuioapp.ch/de/groups/11147/people?returning=true
Fehlt z.B: Grand Charles, Meier Ernst, Ory Roland, ...

Vorsicht: dieser Verein ist auch mit dem "Bernischer Kantonal-Musikverband" verbunden.

**Comment by KunoKunz** [comment]
> Für den Verein "Union Démocratique Boncourt" sehen wir keine Mitglieder. Die Personnen sind jedoch vorhanden (falls man sie in "Person hinzufügen" sucht).
> Scheint ein Berechtigungsproblem zu sein...
> https://htbt-sbv-prod.appuioapp.ch/fr/groups/11682/people
> 25 Mitglieder, wie 
Caritey Alain (https://db.windband.ch/de/groups/1/people/55469)
Claude Morane (https://db.windband.ch/de/groups/1/people/55365.html)
Crelier Serge (https://db.windband.ch/de/groups/1/people/53039)
Crétin Olivier (https://db.windband.ch/de/groups/1/people/55350.html)

Ein Berechtigungsproblem schliesse ich aus. Den Personen wurden keine Rollen vergeben. Weshalb, können wir abklären.
> 
> Der Präsident (Vorstand) habe ich selbst hinzugefüt, aber man sieht dass er jetzt 2x die Rolle 'Vorstand Präsident" beistzt.
> 
> Sicher haben noch anderen Vereine das gleiche Problem.

Die eine Präsidentenrolle bezieht sich noch auf den gelöschten Verein https://db.windband.ch/de/groups/11684.
* [ ] diese Rolle noch löschen und abklären, weshalb dies nicht automatisch geschehen ist

**Comment by KunoKunz** [comment]
> Beim Verein "Batterie-Fanfare L'Audacieuse Bienne" sehen wir nur 6 Mitglieder (1 doppelt). Aber sie sind 17.
> https://htbt-sbv-prod.appuioapp.ch/de/groups/11147/people?returning=true
> Fehlt z.B: 
Grand Charles (https://db.windband.ch/de/groups/1/people/10964),
Meier Ernst,
Ory Roland (https://db.windband.ch/de/groups/1/people/10969), ...
> 
> Vorsicht: dieser Verein ist auch mit dem "Bernischer Kantonal-Musikverband" verbunden.

Der Verein wurde doppelt importiert:
BE: https://db.windband.ch/de/groups/3224
JU: https://db.windband.ch/de/groups/11144

Der einfachste Weg wäre wohl, den einen Verein zu löschen und danach korrekt beiden Verbänden anzuhängen. Die fehlenden Mitglieder können danach als CSV importiert werden. Würde dies passen, @didierber?

**Comment by didierber** [comment]
Ok für das Löschen von  "Batterie-Fanfare L'Audacieuse Bienne". Der Vereine 3224 (Bern) löschen am Liebsten. So werde ich nur 11 Peronnen importieren, und das Eintritt-Datum ändern.
Aber zuerst prüfen ob jemand schon etwas auf die Vereine gemacht hat.

**Comment by KunoKunz** [comment]
Rückmeldung von J.P. Bendit vom 11.2.2019, welche wohl ähnlich gelagert sind wie die oben aufgeführten Probleme:

* [ ] Vereine ohne Mitglieder
> Union Démocratique Boncourt
> Les Echos du Val-Terbi Corban
> Brass-Band Corgémont
> Fanfare Concordia-Liberté Glovelier
> Fanfare L'Amitié Saulcy
> Musique-Fanfare Les Bois
> Point Jazz Band Courgenay

**Comment by didierber** [comment]
Diese Vereine sind als gelöscht definiert. bitte reaktivieren:
boncourt    https://db.windband.ch/de/groups/11684
Corban       https://db.windband.ch/de/groups/11169   
Corgémont https://db.windband.ch/de/groups/11539
Glovelier     https://db.windband.ch/de/groups/11119
Saulcy         https://db.windband.ch/de/groups/11639
Courgenay  https://db.windband.ch/de/groups/11429

**Comment by KunoKunz** [comment]
* [ ] Die Telefonnummern wurden nicht importiert. Können diese z.b. pro Kantonalverband noch für alle Mitglieder nachgetragen werden?

**Comment by didierber** [comment]
Sorry, noch die letzte zu reaktivieren (Musique Fanfare Les Bois )
https://db.windband.ch/de/groups/11704

**Comment by kronn** [comment]
Die genannten Vereine sind alle wieder reaktiviert, inklusive der Untergruppen (Vorstand, Mitglieder, ...) und den dort zugeordneten Personen.

**Comment by kronn** [comment]
@KunoKunz ich habe die Zuordnung der "Union Démocratique Boncourt" (Gruppen 11679 und 11684) genau andersherum als besprochen angepasst, da die geplante aktive Gruppe 11684 durch Umbenennen als Doublette gekennzeichnet wurde.

**Comment by didierber** [comment]
Ich habe ein Mittel gefunden, um die Telephonnummer zu importiren (via ein Import in einer temporäre Gruppe). und die Sprache werde auch korrekt setzen.

So keine Skript bilden und diese Issue schliessen. Danke & Gruss. 
Bitte keine Daten-Änderung für WestSchweiz Verbände machen, ohne mich zu melden.
