### ISSUE TITLE
SBV: Verlauf bearbeiten 

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#729]
* [ ] Die Einträge im Verlauf sollen (hart) gelöscht werden können
Edit: Das Ändern von Start- und Enddatum wird nicht mehr gefordert

**Comment by RolandStuder** [comment]
Ich nehme an, Verlaufseinträge sollten nur durch Admins gelöscht werden können. Wenn das jede Person mit Schreibberechtigung könnte, kann man Spuren von Manipulationen verwischen.

Start Enddatum kann im PBS Wagon geändert werden, die Frage ist, ob man das grad in den Core nimmt. Ich glaube es hat dort die Restriktion, dass man nicht Rollen mit Startdatum in der Zukunft haben kann, damit man sich nicht versteckt Berechtigungen in der Zukunft erteilen kann, bevor man seine Rolle abgibt.

**Comment by KunoKunz** [comment]
Ja, genau. M.W. können auch nur Admins heute neue Rollen hinzufügen im Verlauf.

M.E. könnte gut die Lösung der PBS in den Core genommen werden. Hängt auch von den jeweiligen Aufwänden ab.

**Comment by KunoKunz** [comment]
Einzelne Einträge können nicht gelöscht werden. Z.B. die Mitgliedschaft von 
https://sbv.puzzle.ch/de/groups/3522/people/9261/history im Verein https://sbv.puzzle.ch/de/groups/232.

Weshalb ist das so?

**Comment by amaierhofer** [comment]
Die gelöschten Rollen (rollen mit Bis Datum) sind jetzt auch löschbar, das hat noch gefehlt. 

Weiters gibt  Rollen die von der Person selbst nicht gelöscht werden können, da sie dadurch nicht mehr in der Lage wäre diese Alktion rückgängig zu machen (kann aufgrund der fehlenden Berechtigung sich die Rolle selber nicht mehr zuteilen). Diese Rolle kann aber immer von einer anderen berechtigten Person gelöscht werden

**Comment by KunoKunz** [comment]
Wenn ich als B. Lippuner (https://sbv.puzzle.ch/de/groups/3522/people/9261) versuche, die Mitgliedschaft in Eggersried (https://sbv.puzzle.ch/de/groups/3522/history_roles/63376) zu löschen, kommt ein weisser Bildschirm ohne weitere Angaben; die Rolle wird nicht gelöscht.

**Comment by amaierhofer** [comment]
Hab ich korrigiert und neu deployed.
