### ISSUE TITLE
Radiobuttons in Filter deaktivieren

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#731]
Wenn bei der optionalen Einschränkung auf einen Zeitraum ein Radiobutton einmal ausgewählt wurde, kann die Option nicht mehr abgewählt werden. Dies sollte irgendwie möglich sein.

Aktuell ist es möglich, dass ein Datum eingegeben werden kann, ohne dass ein RB selektiert werden muss. Hat das Datum so eine Auswirkung auf das Suchresultat?

**Comment by amaierhofer** [comment]
Das Verhalten von RadioButtons(RB) ist Standard Browser Verhalten und in der gesamten Applikation identisch. Es ist nicht vorgesehen, dass ein RB deaktivierbar ist (siehe https://ux.stackexchange.com/questions/13511/why-is-it-impossible-to-deselect-html-radio-inputs).

Die Auswahl eines RB hat keine Relevanz, solange kein entsprechendes Datum eingegeben wurde. Man könnte argumentieren, dass in diesem Fall ein Dropdown die besser geeignete Form Komponente ist. Wir können aber auch den RB deaktiverbar machen, was meinst du @KunoKunz

**Comment by KunoKunz** [comment]
Ich möchte das Standardverhalten nicht ändern. Evtl. reicht es bereits, wenn wir noch transparent machen (oder wenigstens den Kunden informieren), welche Daten bei einem leeren Datumseingabefeld von/bis vom System übernommen werden. Ich kläre dies mal noch mit dem Kunden.

**Comment by olibrian** [comment]
Keine Rückmeldung. Schliesse dieses Ticket.
