### ISSUE TITLE
Dokumentenbereich

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#732]
Ein potenzieller SaaS-Kunde möchte einen Dokumentenbereich, auf den Benutzer entsprechend ihren Berechtigungen Zugriff haben. 

* [ ] lässt sich dies über eine API zu einer Nextcloud-Instanz lösen? 
* [ ] oder auf Stufe Organisation/Verein (wie zu Anlässen) Dokumente hinzufügen?

**Comment by RolandStuder** [comment]
Was ist das Ziel des Dokumentenbereichs? Wäre gut hier ein paar Beispiele zu haben, wie sie es nutzen möchten. Eine Anbindung an Nextcloud wäre natürlich super!

**Comment by ThomasEllenberger** [comment]
Die Nextcloud Anbindung wurde in Issue https://github.com/hitobito/hitobito/pull/1989 umgesetzt.
-> Issue closed
