### ISSUE TITLE
"Alle auswählen" funktioniert im Internet Explorer nicht richtig 

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#734]
In der Rechnungsübersicht werden bei einem Benutzer von insieme (mit Internet Explorer V. 11.523.17134.0) nicht alle Rechnungen angewählt, wenn das "alle auswählen" Kästchen selektiert wird

**Comment by olibrian** [comment]
Internet Explorer wird nicht mehr unterstützt. Schliesse dieses Ticket.
