### ISSUE TITLE
Anmeldeangaben für Events 

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#735]
Obschon ich auf dem Tab Kontaktangaben bei einem Event "Nicht anzeigen" ausgewählt habe, werden die Felder danach angezeigt. Betrifft externe Anmeldungen

**Comment by KunoKunz** [comment]
Felder, die für die Anmeldung obligatorisch angeben werden sollen, können auch leer abgeschickt werden. Es scheint, als ob die Radiobutton-Auswahl gar nicht berücksichtigt wird.

**Comment by RolandStuder** [comment]
In welcher Rolle hast du das gemacht? Ich glaube, als Kursleiter hast du die Möglichkeit Anemldung zu erfassen, die unvollständig sind, als Teilnehmer aber nicht.

**Comment by KunoKunz** [comment]
Habe mich als Externer mit einer separaten E-Mail-Adresse versucht.

**Comment by amaierhofer** [comment]
Es fehlen noch Anpassungen im Insieme Wagon
