### ISSUE TITLE
Verein verschieben funktioniert nicht

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#736]
Der Verein 12299 kann nicht in die Gruppe 11794 verschoben werden (es passiert gar nichts).

https://db.windband.ch/de/groups/12299
https://db.windband.ch/de/groups/11794

**Comment by didierber** [comment]
Der Verein 12299 kann nicht in die Gruppe 11794 verschoben werden.  Der Verein ist nach der Verschiebung in der Gruppe 12079 angehängt.
https://db.windband.ch/de/groups/12299  (Ensemble de cuivres "The Friend's Band")
https://db.windband.ch/de/groups/11794  (SCMV - Ziel Regionalverband)
https://db.windband.ch/de/groups/12079  (Giron des Musiques de la Côte Ouest)

**Comment by KunoKunz** [comment]
Ein weiterer Verein: https://db.windband.ch/de/groups/2759 soll in https://db.windband.ch/de/groups/2639 verschoben werden

**Comment by didierber** [comment]
https://db.windband.ch/de/groups/12299 wurde am 06.05.2019 von Puzzle gelöscht.
Bitte der Verein und die entsprechenden Mitglieder reaktivieren, 
und dann in der Gruppe 11794 verschieben.

**Comment by didierber** [comment]
ich habe alles reaktiviert und der Verein befindet sich jetzt in der richtigen Gruppe.

Issue kann geschlossen werden.
