### ISSUE TITLE
Kursbestätigungen

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#741]
Beim erfolgreichen Abschluss eines kantonalen- oder nationalen Kurses sollen die Teilnehmenden einen schriftlichen Leistungsnachweis als Bestätigung erhalten. Dieses Dokument dient den Teilnehmenden als Befähigung, wenn sie einen J+S-Anlass mitleiten wollen, oder auch als Anhang einer Bewerbung. 

Der PDF-Export dafür wird als externes Tool von Ueli Kurmann / Calmo programmiert und bietet eine einfache REST-Schnittstelle. In der MiData braucht es dazu einen Absprung, sowie einige Anpassungen, um den Prozess abzubilden.

## Prozess Kursbestätigung
Beim Abschluss eines Kurses werden jetzt bereits die Qualifikationen an die Personen vergeben, die den Kurs erfolgreich abgeschlossen haben. Genau diese Personen sollen dann per E-Mail benachrichtigt werden, dass ihre Kursbestätigung freigegeben wurde. Sobald dies geschehen ist, finden die Teilnehmenden ihren persönlichen Absprungslink zum Export, direkt auf der Kursübersicht.

## Absprung
Der Absprung basiert auf den folgenden Daten aus der MiData:
- TN-Daten: Anrede, Name, Vorname, Wohnort, Geburtstag
- Kurstyp: Auswahl aus 9 fixen Typen
- Kursdaten: Datum, Ort, "Durchgeführt von"

Technisch ist dies bereits wie folgt umgesetzt:
```
POST URL: exampleurl.com/kurs/render/pdf/{kurs}/de

{kurs}: 
al-kurs
aufbaukurs
basiskurs
coachkurs
futurakurs
leitpfadikurs
panoramakurs
spektrumkurs
topkurs

Die Parameter werden mit folgender JSON Struktur übergeben:
{"name":"Rengel","vorname":"Heinrich","wohnort":"Oberdorf","dauer":"28.09.2017 - 29.09.2017","kursOrt":"Solothurn","organisator":"Pfadibewegung Schweiz (PBS)","geburtstag":"09.08.1977","anrede":"Herr“}
```

## Ergänzungen
- Die Funktion soll nur für ausgewählte Kurstypen verfügbar sein. -> Konfigurierbar pro Typ
- Einige KVs wünschen, die Bestätigungen nicht zu verwenden. Deshalb soll die Funktion pro Kurs deaktiviert werden können
- Die E-Mail-Benachrichtigung soll nur den Hinweis enthalten, dass ein Dokument zur Abholung bereitsteht mit Link zum Kurs
- Die E-Mail-Benachrichtigung soll manuell ausgelöst werden, bzw. für den Kursleiter freiweilig sein

**Comment by carlobeltrame** [comment]
@Michael-Schaer
1. Gilt dies tatsächlich nur für kantonale und nationale Kurse? Ist es also ausgeschlossen für regionale J+S-Kurse?
1. Schliesst "Genau diese Personen" auch die Kursleitenden ein? Danach ist nur noch von den "Teilnehmenden" die Rede.

**Comment by Michael-Schaer** [comment]
1. Ich würde die Regionen nicht systematisch ausschliessen. Es sollte reichen, wenn man pro Kursart definieren kann, ob die Funktion verwendet wird (z.B. hier https://pbs.puzzle.ch/de/event_kinds/30/edit).
Ich habe da an eine checkbox "Export Kursbestätigung aktivieren" auf dieser Ansicht gedacht. Vielleicht braucht es auch noch ein Textfeld "Name der Kursart im Export-Tool", wenn dies nicht direkt abgeleitet werden kann.

2. Nur Teilnehmende. Kursleitende lassen wir vorerst weg.

**Comment by Michael-Schaer** [comment]
Das sieht schon mal ganz gut aus! Das einzige, was uns beim Testing auffällt, ist das die Mails nicht rausgehen. Im Mailtrap finde ich jedenfalls keine Elemente zu den verschickten Bestätigungen. Kannst du das noch mal überprüfen?
 
Dann hier noch ein Wunsch, den wir bisher nicht geäussert hatten:
### Bestätigungen im Profil
Die Bestätigungen sollen im Profil der Person sichtbar sein. Dabei sehen wir zwei Möglichkeiten: 
1. Bei den Qualifikationen ein zusätzliches Icon einfügen, wenn eine Bestätigung dazu vorhanden ist. Logik: Wenn zwei Bestätigungen für eine Qualifikation vorhanden ist, soll die aktuellere angezeigt werden.
2. Eine zusätzliche Liste "Meine Bestätigungen" unterhalb der Qualifikationen

**Comment by carlobeltrame** [comment]
Ich verstehe nicht ganz, wie es mehrere Bestätigungen für eine Qualifikation geben soll..? Die Bestätigungen werden nicht in hitobito gespeichert, es werden nur on-the-fly die richtigen Parameter für das externe PDF-Tool generiert wenn man auf den Button klickt. Es behält also momentan niemand (ausser vielleicht der Benutzer) alte Versionen von Bestätigungs-PDFs.

Die Mails in Mailcatcher haben bei mir zwischenzeitlich auch nicht funktioniert, und dann später doch. Aber ich schau mir das nochmals an.

**Comment by carlobeltrame** [comment]
Nevermind, die Qualifikationen auf der Personenansicht können ja durch neuere Kurse aufgefrischt werden, ich nehme an das ist gemeint.

**Comment by carlobeltrame** [comment]
Das neu gewünschte Feature "Bestätigungen im Profil" ist nun auf PBS Integration deployed. Um eine Sicherheitswarnung in einigen Browsern zu vermeiden, müsste man das PDF-Export-Tool mit https anbieten und in der hitobito-config die externe URL auf https ändern:
![grafik](https://user-images.githubusercontent.com/7566995/70232676-424d9700-175d-11ea-9d66-0c97f100e6c9.png)


Die Mails konnten wir auch schon im Mailtrap auffinden. Diese werden aber mit `deliver_later` versendet. Das bedeutet ein Hintergrundprozess verschickt die Mails, darum kann es sein dass sie noch nicht direkt beim Drücken des Buttons im Mailtrap sind.

@Michael-Schaer bitte erneut testen.

**Comment by Michael-Schaer** [comment]
Ich bin leider erst jetzt zum erneuten Testen gekommen. Das sieht gut aus, genau so haben wir uns das vorgestellt!

Was mir jetzt allerdings noch aufgefallen ist: Der Absprung zeigt im Moment immer auf die deutsche Seite. Da bräuchten wir eigentlich auch den "fr" und "it" Link, je nach ausgewählter Sprache in der MiData.

**Comment by Vento-Nuenenen** [comment]
@Michael-Schaer 
Das Problem ist wohl, dass im PDF-Generator noch die Übersetzungen fehlen...

**Comment by Michael-Schaer** [comment]
@Vento-Nuenenen Merci für den Link!

Das Tool braucht auf jeden Fall noch einen Feinschliff und die Übersetzungen, dazu habe ich bei Ueli auch noch mal nachgefragt, wie wir da weitermachen.

Das tolle an der Funktion ist ja aber, dass wir sie nach dem Release jederzeit pro Kursart in der MiData aktivieren können. Von der Planung her muss also die Mehrsprachigkeit ins nächste Release, dann können wir das aufschalten, sobald das Export-Tool ready ist.

**Comment by Vento-Nuenenen** [comment]
@Michael-Schaer 
Der Carlo hat das eigentlich auch schon implementiert in der Zeile https://github.com/hitobito/hitobito_pbs/blob/e29cfb02e06ad69bb61095a28dfabdcec27acf64/config/settings.yml#L31
Das muss nur geändert werden. Er hat das wohl nich von Anfang an aktiviert, damit man im Testsystem nicht in einen Feheler läuft, wenn man die Sprache umstellt...

**Comment by carlobeltrame** [comment]
Stimmt genau, danke @Vento-Nuenenen. @Michael-Schaer, teile mir einfach mit wenn die Übersetzungen der Kursbestätigungen live sind, dann ist es eine Sache von 3 Minuten (plus Deployment) bis die übersetzten Versionen in der MiData funktionieren.

**Comment by Michael-Schaer** [comment]
Tiptop, merci. Ich denke wir können das auch jetzt gleich einbauen und ein weiteres (kleines) Release auf Produktion vermeiden. Da das Testing dieser Funktion jetzt abgeschlossen ist, macht es auch nichts, wenn auf dem Testsystem eine Fehlermeldung kommt.

Ueli wird das Export-Tool bald nachrüsten.

**Comment by carlobeltrame** [comment]
Ist erledigt. Wird beim master deployen mitgeliefert.

**Comment by kronn** [comment]
Das Feature wurde mit Version 1.20 released.
