### ISSUE TITLE
Anmeldedaten beim Lager - Defaultwerte

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#742]
Beim Import von Lager-TN in die SPORTdb ist die Nationalität eine Pflicht-Angabe. Deshalb wäre es nützlich, wenn die Standardwerte bei allen Lagern so gesetzt werden, dass die Nationalität ein Pflichtfeld ist.

@KunoKunz Ich melde mich bei Gelegenheit noch dazu bei dir

**Comment by carlobeltrame** [comment]
Fixed in https://github.com/hitobito/hitobito_pbs/pull/94
