### ISSUE TITLE
Rechnungsfeature auf PBS-Integration getestet (16h)

### ISSUE THREAD

**Issue by Vento-Nuenenen** [hitobito/hitobito#744]
Ich habe das neue Feature der Rechnungsstellung, für die PBS, auf der entsprechenden Integration getestet und dabei folgende Fehler / Probleme festgestellt:

### 1. Menü
![Arschiges Menü](https://user-images.githubusercontent.com/35610192/54884081-1ad3ca00-4e6d-11e9-985c-a537f87c9982.PNG)
Rechnungsebenen und die jeweiligen Optionen dazu sind gleich formatiert. Dies wird zu Verwirrung der Nutzer führen. Wird aber voraussichtlich nur wenige Nutzer betreffen.

### 2. Fehlermeldung mit Stacktrace
![Error](https://user-images.githubusercontent.com/35610192/54884088-2626f580-4e6d-11e9-951a-053477d3d27a.PNG)
Wenn eine Zahlung erfasst werden soll und keine oder eine falsche Datei hochgeladen wird, wird die Fehlermeldung mit einem Stacktrace versehen. Kann möglicherweise zu Verwirrung führen.

### 3. MWST. falsch beschriftet
![MWST](https://user-images.githubusercontent.com/35610192/54884095-2de69a00-4e6d-11e9-99cf-2d301453bbb1.png)
![mwst2](https://user-images.githubusercontent.com/35610192/54884096-32ab4e00-4e6d-11e9-8dae-f1e05ad3d692.PNG)
Wenn eine Rechnung gestellt wird, wird die Rechnungssumme inkl. MWST unterschiedliche angezeigt.
1.	Total inkl. MwST. = 80.00 CHF  Sollte 86.40 sein
2.	 Logisch, da hier nur Quantitäten gerechnet werden.  Ev ergänzen exkl. MwSt.
3.	OK
4.	OK
 
### 4. Fehlendes Pflicht-Sternchen bei IBAN
![Stern](https://user-images.githubusercontent.com/35610192/54884098-39d25c00-4e6d-11e9-9f57-9c9f719af72b.PNG)
 
### 5. Interne Rechnungartikel
![NR](https://user-images.githubusercontent.com/35610192/54884107-435bc400-4e6d-11e9-8769-f9f5c899ed60.png)
Bei internen Rechnungen werden keine Rechnungsartikel geladen. Nur die jeweiligen Artikelnummern.
Zudem werden die Daten der Artikel nicht sauber geladen.
Bei externen Rechnungen funktioniert das.

**Comment by js4gh** [comment]
Ohne gross zu suchen Sind mir die folgenden weiteren "Probleme" begegnet:

Getestet auf der folgenden Gruppe:
 https://pbs.puzzle.ch/de/groups/506/invoices

Absender stimmt im E-Mail nicht;
![image](https://user-images.githubusercontent.com/26506206/55036735-ca4e9f00-501b-11e9-8ed9-32915c3813e2.png)

Weder auf der Rechnung noch auf dem Einzahlungsschein wird der Absender(Rechnungstellung) angezeit:

https://pbs.puzzle.ch/de/groups/506/invoices.pdf?ids=686 
![image](https://user-images.githubusercontent.com/26506206/55037411-fd922d80-501d-11e9-9f4c-25e07bf06641.png)



Aus meiner Sicht sollten nur Reinigungsartikel angezeigt werden die mann selber erstellt hat:

![image](https://user-images.githubusercontent.com/26506206/55036988-8ad48280-501c-11e9-8a0d-5f2065007b4d.png)

Auch wenn bereits Zahlungen eingegangen sind wird der ursprüngliche Betrag gemahnt:
![image](https://user-images.githubusercontent.com/26506206/55037079-dbe47680-501c-11e9-81f2-f069fbe51da9.png)



Weiter zu bedenken, lange nicht alle (isch schätze bei weitem nicht die Hälfte) der Benutzer werden die Rechnungen nicht mit einer camt.054 XML Datei abgleichen.

Wünschenswert währe eine Möglichkeit mehrere Rechnungen auszuwählen und gleichzeitig auf Bezahlt zu setzen. (aus meiner Sicht klar ein Grundfunktion)

**Comment by js4gh** [comment]
@KunoKunz kannst du unsere Rückmeldungen so verarbeiten oder sollen wir die noch sonst wo, allenfalls einzeln erfassen?

**Comment by KunoKunz** [comment]
@js4gh Danke, damit können wir etwas anfangen.

**Comment by Vento-Nuenenen** [comment]
@KunoKunz @js4gh 
Nachtrag dazu:

> Aus meiner Sicht sollten nur Reinigungsartikel angezeigt werden die mann selber erstellt hat:
> 
> ![image](https://user-images.githubusercontent.com/35610192/55070844-6792ed00-5087-11e9-91c3-8b98e5cf0424.png)

Es geht meiner Ansicht nach, nicht um das selber erstellt, sondern darum, dass die Organisationen hier getrennt werden.
Momentan werden die Rechnungsartikel von allen Organisationen in dieses Dropdown geladen. Es sollten aber nur die Artiken von Organisation A angezeigt werden, wenn eine Rechnung für Org. A erstellt wird...

**Comment by js4gh** [comment]
weiterer Nachtrag:

Ich schlage vor bei den Mahnungen folgende Standard Texte zu hinterlegen:

**1. Mahnung**
Titel: Zahlungserinnerung
Text: Im hektischen Alltag kann es schnell mal vorkommen, eine fällige Zahlung zu übersehen. Vielleicht ist es Ihnen schon aufgefallen, dass Sie unsere letzte Rechnung noch nicht beglichen haben.
Danke, dass Sie die Überweisung in den nächsten Tagen vornehmen. Sollten Sie die Zahlung bereits veranlasst haben, betrachten Sie bitte dieses Schreiben als gegenstandslos.
Tage bis Fällig: 30


**2. Mahnung**
Titel: Zweite Mahnung
Text: Trotz unserer Zahlungserinnerung haben Sie unsere Rechnung noch nicht beglichen. 
Wir bitten Sie den fehlbaren Betrag zu begleichen.
Tage bis Fällig: 14

**3. Mahnung**
Titel: Dritte Mahnung
Text: Wir fordern Sie nun ein letztes Mal auf, den offenen Betrag innert Wochenfrist, zu begleichen.
Tage bis Fällig: 5

![image](https://user-images.githubusercontent.com/26506206/55975187-b3e64b80-5c89-11e9-9112-63f4eb1b3a50.png)

**Comment by js4gh** [comment]
Wie gross währe der Aufwand Rechnungen auch auf ein Abo auszustellen?

![image](https://user-images.githubusercontent.com/26506206/55977277-b7300600-5c8e-11e9-824a-1526038e26e9.png)

**Comment by RolandStuder** [comment]
Ist nicht ganz trivial. Bei Personenlisten nimmt es nur die aktuellen Ansicht, also wenn es mehrere Seite hat, muss man pro Seite einmal Rechnung erstellen drücken. Bei Abos haben wir noch keine Paginated Ansicht oder einen Controller, der das aufteilt. Also müsste man das entweder machen, und dass ist beim Zusammenzug vom Abo evtl. auch wieder nicht trivial. Oder dann müsste man es in einen Hintergrundjob verschieben und ein sinnvolles UI dazu gestalten. Hat also noch so seine Tücken.

**Comment by KunoKunz** [comment]
Falls mehr als fünfzig Personen zu einer Gruppe gehören, sollen für sämtliche Personen dieser Gruppe eine Rechnung erstellt werden (und nicht bloss für die ersten 50, welche angezeigt werden).

**Comment by tschuepbach** [comment]
> Falls mehr als fünfzig Personen zu einer Gruppe gehören, sollen für sämtliche Personen dieser Gruppe eine Rechnung erstellt werden (und nicht bloss für die ersten 50, welche angezeigt werden).

see  cevi/hitobito_cevi#68

**Comment by KunoKunz** [comment]
Zusammenfassung für #911 erstellt. Wird dort weitergeführt.
