### ISSUE TITLE
Aboversand Problem bei Jubla

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#745]
Bei der Jubla gibt es aktuell ein Problem mit dem Versand des folgendes Abos (andere scheinen zu funktionieren..)

Trotz Versandbestätigung melden die Personen, dass die Mails nicht angekommen sind. Bitte melden, was das Log dazu sagt:

https://db.jubla.ch/groups/1/mailing_lists/66/subscriptions?returning=true

Letztes Testmail versandt mit folgender Bestätigung:

```
Deine Mail an kalei.kontakt@db.jubla.ch wurde verschickt:

Betreff: Test e-Mail mit unberechtigter Adresse
Zeit: Donnerstag, 28. März 2019, 11:28 Uhr
Empfänger: 21
```

(Adresse war aber zu diesem Zeitpunkt berechtigt, also Betreff ignorieren)

**Comment by RolandStuder** [comment]
Ich habe einen weiteren Testversand gemacht, bisher haben 3 von 21 Personen zurückgemeldet, dass sie das Mail erhalten haben. Das Problem liegt wohl also wohl auf der Ebene Spamfilter und Greylisting.

**Comment by olibrian** [comment]
Spam Problematik wurde via help.puzzle.ch abgehandelt. Daher schliesse ich dieses Issue.
