### ISSUE TITLE
Sichtbarkeit OGL auf Übersicht

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#746]
Rückmeldung der Cevi:
> 
> Wir haben bei uns eine Meldung bekommen, dass für die
> Kursadministratoren in der Übersicht die Spalte nicht mehr angezeigt wird.
> 
> "Neu sehen wir die OGL nicht mehr, sondern nun noch die Hauptebene, was
> uns gar nicht’s bringt."
> 
> Dies hat vor dem Release im Dezember noch funktioniert. Es fällt erst
> jetzt auf, da die Kursadministration mit den Frühlingskursen wieder
> häufig genutzt wird.
> Das Sekretariat sieht die info noch, also wurde nur etwas ander
> Kursadministratoren Rolle verändert. Für die Kurs Admins ist es wichtig,
> diese Spalte auch korrekt zu sehen.
> 

Ich konnte allerdings das Problem nicht reproduzieren, ausser ich verstehe es falsch. Auf der Teilnehmerübersicht von Kursen habe ich folgende Spalten, auch als Kurshauptleiter / Kursleiter. Oder geht es um eine andere Rolle? 

![image](https://user-images.githubusercontent.com/194364/55153689-5a433480-5153-11e9-9666-68b89eceb8c6.png)

Bitte schickt mir doch den Link einer Person, bei der das nicht klappt, wie gewünscht, inkl ein Link auf die Seite wo ihnen die Spalte fehlt.

**Comment by nchiapol** [comment]
Ja, das betrifft primär die Rolle "Mitgliederorganisation / Gremium / Ausbildungsmitglied". Grundsätzlich sollte die Spalte Ortsgruppe aber bei allen Rollen angezeigt werden, die auf Kursteilnehmer zugreifen können. 

Person die das sehen sollte: https://db.cevi.ch/groups/101/people/161
Seite die nicht funktioniert: https://db.cevi.ch/groups/2/events/1095/participations

Screenshot beim Imitieren:
![image](https://user-images.githubusercontent.com/1123483/55188694-407a0f80-519c-11e9-812a-0cb6a81e223a.png)

**Comment by RolandStuder** [comment]
Danke für die Präzisierungen, die Rechte auf diese Spalte war abhängig von der Schreibberechtigung. Ich weiss nicht was sich verändert hat, dass diese Personen nicht länger Zugriff haben, aber ein fix war einfach, ich mache den Pull Request dazu.

**Comment by smathys** [comment]
können wir diesen fix in einem separiertem Release haben?
