### ISSUE TITLE
Weniger Rechte für welsche Vereinspräsidenten

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#747]
Vereinspräsidenten in den französischsprachigen Verbänden sollen selber keine zusätzlichen Mitgliedschaften (im Verlauf einer Person) hinzufügen können.

Können wir dies überhaupt auf einzelne Funktionen anwenden? Neue Mitglieder hinzufügen sollte ja nach wie vor möglich sein.

-> saubere Lösung mit neuen Organisationstypen und damit verbundene Rollen (Anzeigeproblematik, Listen, Abos
-> Quick & dirty: zusätzliches Attribut auf den Vereinen, welches die Anzeige "übersteuert". Nebenwirkungen nicht ausgeschlossen!
-> bisherige Vereine müssen geändert werden - auch da sind Nebenwirkungen nicht ausgeschlossen!

**Comment by RolandStuder** [comment]
Das soll also nur für die französischsprachigen Verbände gelten und für andere aber nicht?
