### ISSUE TITLE
Startdatum auf Rollenübersicht anzeigen

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#749]
Bei der Rollenübersicht soll das Startdatum einer Rolle noch angezeigt werden

**Comment by RolandStuder** [comment]
Dafür steht der Verlauf zur Verfügung, die Rollenübersicht ist aktuell schon visuell überladen. Ich würde das nicht tun.

Ich habe da noch einen Branch mit einer Überarbeitung offen: https://github.com/hitobito/hitobito/issues/511, siehe Branch https://github.com/hitobito/hitobito/tree/feature/better-roles-aside

Von wem kam der Wunsch?

**Comment by olibrian** [comment]
Keine weiteren Infos. Ich schliesse den Issue
