### ISSUE TITLE
Abo Mailingliste Historie

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito#75]
Enhancement:

Mailinglisten von Abos entwickeln sich zu einem sehr wertvollen und auch intensiv genutztem Werkzeug.  Daher ist es wünschenswert, dort mehr Transparenz zu bekommen. 

Loging der Nachrichten, welche durch Hitobito an die Maillingliste weiterverteilt wurden. Anzeige in Liste und mit Details. 

Minimal: analog den gelogten Informationen in deliver hitobito/app/domain/mail_relay/lists.rb

```
logger.info("#{Time.zone.now.strftime('%FT%T%z')}: " \
                  "Relaying email from #{sender_email} " \
                  "for list #{envelope_receiver_name} " \
                  "to #{message.smtp_envelope_to.size} people")
```

Variante: 
Zusätzlich mit dem Inhalt  (Text ohne Attachements aus Speicherüberlegungen)
Ggf. Limitierung der maximal angezeigten/gespeicherten Nachrichten auf 20 Nachrichten pro Abo. 

So hätte der Benutzer mehr Transparenz, ob seine Nachricht auch von Hitobito weitergeleitet wurde.

**Comment by RolandStuder** [comment]
Ich bin nicht sicher ob ich richtig verstehe. Die Versandten Mail sollen bei jeder Person auf dem Log erscheinen? Oder soll dies beim Abo sichtbar sein?

Hier würde ich gerne über den genauen Zweck sprechen, damit wir das richtige bauen. Feedback über erfolgreichen Versand wäre auch per Mails möglich, das hätte den Vorteil, das wir das bestehende UI nicht mit weitere Inhalten beschweren.

z. B.

---
Folgendes Mail wurde an 50 Personen versandt

HIER DER INHALT:
Mailtext ...
---

**Comment by RolandStuder** [comment]
Heikel ist hier, dass wir wieder einschränken müssen, wer diese Logs sieht. Der Query für Abos ist recht langsam. Daher ist ein individuelles prüfen, ob eine Person auf dem Abo ist nicht sehr performant. Und die Person muss zuerst das Abo aufzusuchen um die Bestätigung zu erhalten.

Ich denke daher ist die Lösung über ein Bestätigungsemail einfacher.
- Simple Lösung: Sender empfängt das Mail genau wie alle anderen.
- Elegantere Lösung: Sender empfängt am Ende das Email, mit der Zusatzinformation: Folgendes Mail wurde an 50 Personen versandt

Ich bin mir nicht mehr sicher, was in den folgenden Fällen passiert, aber ich glaube:

* Wenn ich auf ein Abo schreibe auf das ich nicht berechtigt bin, erhalte ich eine Rückmeldung, dass ich das nicht darf.
* Bei einem nicht existierende Abo erhalte ich glaube ich kein Feedback.

**Comment by RolandStuder** [comment]
Elegante Lösung ohne weitere Ergänzungen

**Comment by RolandStuder** [comment]
@adriananderegg Wie siehst du das diesbezüglich:

* Personen welche selbst auf der Mailingliste sind und unterschiedliche Absender und Empfängeradresse haben, werden halt so zwei Mails erhalten.

Sollten wir noch folgendes tun?

Es ist möglich, dass die Absenderadresse hinterlegt ist aber nicht auf der Empfängerliste auftaucht, nämlich wenn das Versandflag auf dieser zusätzlichen E-Mailadresse nicht gesetzt ist.

Evlt. sollte man vor dem Versand prüfen ob die Absenderadresse bei einem der Empfänger als zusätzliche Adresse ohne Versandflag hinterlegt ist. Damit könnte man noch einige unnötige Doppelmails verhindert

**Comment by adriananderegg** [comment]
Dies allein wäre kein Problem. Die zweite E-Mail enthält ja andere Informationen, nämlich ob die E-Mail erfolgreich versandt wurde. 

Die Bestätigung sollte nur an "Moderatoren" gesandt werden 
-->Ist mailing_list[anyone_may_post] gesetzt => keine Benachrichtigung

nice to have: 
Bestätigung sollte auf dem Abo an-/abschaltbar sein

Falls zu komplex müssen wir evtl. die tabellarische Darstellung wieder ins Auge fassen.

**Comment by RolandStuder** [comment]
@adriananderegg Bist du sicher, dass wir das nur beim Newletter Fall tun sollten? Dann ist das Feedback sehr inkonsistent, mal erhältst du eine Bestätigung mal nicht. Das würde doch dem angestrebten Effekt zuwiederlaufen. Dann eher über die Checkbox, dann kontrolliert zumindest jemand explizit.

**Comment by adriananderegg** [comment]
@RolandStuder vielfach werden Abos als rollenspezifische E-Mailadressen genutzt. 
Die Adresse abteilungsleitung@pfadiexample.ch wird auf ein Abo weitergeleitet, welches alle Abteilungsleiter dieser Pfadi beinhaltet. So müssen bei einem Wechsel auf einer Rolle keine E-Mailadressen umgestellt werden. Die Adresse abteilungsleitung@pfadiexample.ch ist immer korrekt. 

Daher haben wir sehr viele Abo E-Mails, welche keinen Newsletter-Charakter haben. 

Checkbox ist ok, Default aber "aus", unbedingt auch bei bereits bestehenden Abos.

**Comment by RolandStuder** [comment]
@adriananderegg Ok. Ich verstehe. Dann würde ich es unbedingt konfigurierbar machen.

Wir sind jetzt relativ weit weg vom ursprünglichen Issue. Denkst du dass wir mit dieser Lösung dem Bedürfnis nach mehr Transparenz, was mit den Mails passiert gerecht werden. Sieht jemand noch andere Möglichkeiten?

**Comment by RolandStuder** [comment]
Durch Issues hitobito/hitobito#138 abgelöst "Mailbestätigung an Absender (konfigurierbar)"
