### ISSUE TITLE
E-Mail-Benachrichtigung bei Kursfreigaben 

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#751]
Beim Kantonalverband Zürich werden die Mails bei Kursfreigaben nicht an die richtien Personen verschickt.

Hier ein Screenshot mit den Einstellungen zu den Kursfreigaben (Rolle:Kantonsleiter -> Tab:Kursfreigaben):
<img width="296" alt="screenshot" src="https://user-images.githubusercontent.com/1799621/55623523-8853f480-57a3-11e9-9a91-56439ac39ee1.png">

Erwartetes Verhalten:
Bei Kursfreigaben werden die Ausbildungsverantwortlichen (Rolle) benachrichtigt. 

Situation auf Produktion:
Die Kursfreigaben werden die Kantonsleiter (Rolle) benachrichtigt.

**Comment by RolandStuder** [comment]
Das tritt aber nur beim Kanton Zürich auf, bei den anderen erhalten die richtigen Rollen die Benachrichtigung? @Michael-Schaer Kannst du uns ein Beispiel zuschicken?

**Comment by Michael-Schaer** [comment]
Das Problem ist anscheind doch nur Zeitweise aufgetreten. Mittlerweile kommen die E-Mails auch bei den Ausbildungsverantwortlichen wieder an.

Vermutlich ist das Problem also auf E-Mail-Ausfälle zurückzuführen.

**Comment by kronn** [comment]
Da die entsprechenden Mails wieder ankommen, schließe ich das Issue hier erstmal.
