### ISSUE TITLE
insieme: Excel-Import funktioniert nicht mehr

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#752]
Ist der Excel-Import nur bei insieme implementiert? Dieser funktioniert nicht mehr. CSV sei noch in Ordnung.

**Comment by RolandStuder** [comment]
Import? Meines Wissens gab es nirgendwo je einen Excel Import.

**Comment by kronn** [comment]
Ich habe bei einer kurzen Suche keinen Excel-Import gefunden. Gibt es hier noch weitere Infos?

**Comment by olibrian** [comment]
Keine weiteren Infos/Probleme bekannt. Ich schliesse mal das Ticket.
