### ISSUE TITLE
Mailversand berücksichtigt nur eine der adressierten Listen (8h)

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito#754]
Problem ensteht, wenn ein Email an mehrere Abos geschickt wird. In diesem Fall wird immer nur eine der adressierten Listen berücksichtigt. Welche das ist, ist jedoch nicht deterministisch. Wahrscheinlich erklärt damit auch das Verhalten aus #745 

https://github.com/hitobito/hitobito/blob/6e5820174c25cef28c4a10af779705232d59a9b2/app/domain/mail_relay/base.rb#L146 liefert nur einen Emfpänger, es müsste aber für jeden der Empfänger ein eigener  BulkVersand durchgeführt werden.

**Comment by js4gh** [comment]
Genau diese Problem tritt bei der Pfadi Chutze in letzter Zeit auch immer mal wider auf und bringt die Verantwortlichen zur Verzweiflung. Währe super wenn das Zeitnahe behoben wird! :-)

**Comment by smathys** [comment]
Wie ist hier der Stand dieses Issues? wir haben so ein Problem per Email am 3. April gemeldet. Hier auf dem Issue ist seit 20 Tagen nichts gelaufen, obwohl es scheinbar alle Jugendverbände auf dem Produktiven System betrifft?

**Comment by KunoKunz** [comment]
@smathys Damit alle auf dem gleichen Stand sind: Aus Applikationssicht sieht soweit alles in Ordnung aus. Es gibt den Umstand (seit jeher), dass bei Mailversänden nur eine adressierte Mailingliste berücksichtigt wird. Dies werden wir vermutlich Anfang Juni beheben können. Darüber hinaus sind wir auf konkrete Beispiele angewiesen, damit wir mit unseren Partnern den Problemen nachgehen können.

**Comment by kronn** [comment]
Ich wäre hier dankbar für konkrete Beispiele oder eine Anleitung zum Nachmachen.

Wir lesen den `X-Envelope-To`-Header aus, welcher vom Mailserver gesetzt wird. Ich finde leider keine offizielle Doku, wie dieser gebildet wird. Daher ist mir unklar, was genau angepasst werden muss.

**Comment by KunoKunz** [comment]
Gemäss Aussage der Jubla hat dies bis März noch funktioniert. Auf Stufe Bund wurden wöchentlich Mails an mehrere Abos versendet.

**Comment by maede97** [comment]
Habe das gerade nochmals getestet mit 2 Mailinglisten https://cevi.puzzle.ch/groups/306/mailing_lists?returning=true
Selbst der Bounce (keine Berechtigung auf diese Liste zu schreiben) kommt nur für die erste Liste.
```
Date: Sun, 16 Jun 2019 16:16:39 +0200
From: mail1-bounces@cevi.puzzle.ch
To: Matthias <XXXX.XXXX@XXXX.ch>
Message-ID: <5d064f4746203_f123197c6135b@delayed-job-77-9gl24.mail>
In-Reply-To: <6754cd32-e0d9-7b04-7478-fef9c99b1c88@XXXX.ch>
References: <6754cd32-e0d9-7b04-7478-fef9c99b1c88@XXXX.ch>
Subject: RE: Test Multiple Mailinglisten
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Precedence: list
List-Id: mail1.cevi.puzzle.ch

Du bist nicht berechtigt, auf diese Liste zu schreiben.
```
Komischerweise, beim zweiten Versuch (mit richtigem Absender) wird, so viel ich gemerkt habe, die Liste 2 verwendet (oben: `List-Id: mail1.cevi.puzzle.ch`)

Output 2:
```
Return-Path: <scirocco@cevi.ch>
Received: from agamemnon.rz.puzzle.ch ([unix socket])	 by agamemnon.rz.puzzle.ch (Cyrus unknown-Kolab-2.5.12.25-1.1.el7.kolab_16) with LMTPA; Sun, 16 Jun 2019 16:18:28 +0200
Received: from servmail.kirchenweb.ch (servmail.kirchenweb.ch [XXXX]) by agamemnon.rz.puzzle.ch (Postfix) with ESMTPS id 3E4BFA000FA; Sun, 16 Jun 2019 16:18:26 +0200
Received: from [192.168.1.133] (XXXX.dynamic.wline.res.cust.swisscom.ch [XXX]) (using TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)) (No client certificate requested) by servmail.kirchenweb.ch (Postfix) with ESMTPSA id 94B47A2F94; Sun, 16 Jun 2019 16:17:52 +0200
Date: Sun, 16 Jun 2019 16:17:52 +0200
From: Matthias v/o Scirocco <scirocco@cevi.ch>
Sender: mail2-bounces+scirocco=cevi.ch@cevi.puzzle.ch
To: mail1@cevi.puzzle.ch, 
 mail2@cevi.puzzle.ch
Message-ID: <5f494027-b891-bb60-fdcb-eeda2b17c3fc@cevi.ch>
Subject: Test 2
Mime-Version: 1.0
Content-Type: text/plain;
 charset=utf-8;
 format=flowed
Content-Transfer-Encoding: quoted-printable
X-Sieve: CMU Sieve 2.4
X-Envelope-To: mail2
X-Original-To: cevi.integration+mail2@puzzle.ch
X-Virus-Scanned: amavisd-new at puzzle.ch
X-Spam-Flag: NO
X-Spam-Score: -4.2
X-Spam-Level: 
X-Spam-Status: No, score=-4.2 tagged_above=-10 required=5
 tests=[BAYES_00=-1.9, RCVD_IN_DNSWL_MED=-2.3, SPF_HELO_NONE=0.001,
 SPF_PASS=-0.001] autolearn=ham autolearn_force=no
Organization: =?UTF-8?Q?Cevi_B=C3=A4retswil?=
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101
 Thunderbird/60.7.1
X-kirchenweb-MailScanner-Information: Please contact the ISP for more
 information
X-kirchenweb-MailScanner-ID: 94B47A2F94.A3071
X-kirchenweb-MailScanner: Found to be clean
X-kirchenweb-MailScanner-SpamCheck: not spam, SpamAssassin (nicht zwischen
 gespeichert, Wertung=-2.899, benoetigt 3, autolearn=not spam, ALL_TRUSTED
 -1.00, BAYES_00 -1.90, URIBL_BLOCKED 0.00)
X-kirchenweb-MailScanner-From: scirocco@cevi.ch
Precedence: list
List-Id: mail2.cevi.puzzle.ch

Und noch ein Test
```

Reihenfolge der Mail-Listen in Thunderbird: `mail1@cevi.puzzle.ch` zuerst, dann `mail2@cevi.puzzle.ch` als zweites.


Beide Mails sollten noch auf Mailtrap in der Cevi-Inbox sein.

**Comment by kronn** [comment]
Danke für die detaillierte Antwort, @maede97. Ich habe die mails mit unseren Admins mal durch die Server verfolgt. Es werden anfänglich tatsächlich zwei Mails verarbeitet, die an die jeweils richtige Liste gehen sollen. Es scheint jedoch einen weiteren Mailfilter zu geben, der die inhaltlich gleichen Nachrichten im zentralen Postfach der hitobito-Instanzen dedupliziert. Wir suchen gerade nach einer möglichst nachhaltigen Lösung.

**Comment by kronn** [comment]
Die Postfächer sind wieder so konfiguriert, dass Duplikate erlaubt sind. Damit ist es wieder auf dem Stand der vor dem Update des Mailservers bestand. Wenn der Fehler nochmal auftritt, bitte dieses Issue wieder öffnen oder ein neues Issue erstellen.
