### ISSUE TITLE
Run Wagon Builds on Core Changes  (4h)

### ISSUE THREAD

**Issue by bihorco36** [hitobito/hitobito#758]
Es gibt folgende Ansätze für GH Actions:
- https://github.com/peter-evans/repository-dispatch
- https://utensils.io/articles/trigger-github-actions-from-another-repo
- https://blog.marcnuri.com/triggering-github-actions-across-different-repositories

**Comment by severinraez** [comment]
Testweise Nightly-Action auf dem Generic-Wagon aktiviert: https://github.com/hitobito/hitobito_generic/commit/d691cbc6bcbf04daafa2bc147cf07354bde79d91

TODO:

- [ ] Prüfen, ob Action über nacht getriggert wird
- [ ] Auf restlichen Wagons aktivieren
- [ ] Entscheid dokumentieren (insb: Direktes Triggern der Pipelines hat Security-Implikationen, da ein Service-User mit Write-Access auf alle Wagon-Repos berechtigt werden muss. Dessen Personal Access Token kann durch externe Contributer im Hitobito-GitHub-Team ausgelesen werden).

**Comment by severinraez** [comment]
Erledigt, Details unter https://github.com/hitobito/hitobito/blob/master/doc/development/06_ci_cd.md
