### ISSUE TITLE
Eigene Etikettenformat pro User

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito#76]
- Der Benutzer kann eigene Etikettenformate definieren.
- Das Menu Admin - Etikettenformate wird dazu allen Benutzern freigeschaltet.
- Das Menu Admin wird in "Einstellungen" umbenannt.
- Der Punkt Etikettenformate wird allen zur Verfügung gestellt.
- Die Seite enthält zwei Bereiche: Persönliche Etikettenformate und Etikettenfomate für den gesamten Verband (letzerer ist wie bisher nur für :admin zugänglich).
- Selbst-definierte Etiketten sind nur sichtbar nur für den jeweiligen Benutzer.
- Der Benutzer kann aktivieren, dass er nur noch seine eigenen Etikettenformate sieht.
- Bezeichnung in der Liste auch mit edit-form verlinken.
- Die Etikettenformate stehen dann bei jedem Export zur Verfügung.

siehe: 
![](https://wearecube.mybalsamiq.com/mockups/5219421.png)
edit https://wearecube.mybalsamiq.com/projects/hitobito/76%2077%20Etikettenformat

**Comment by RolandStuder** [comment]
Gruppenspezifische Etikettenformate wären näher am aktuellen Modell und wahrscheinlich ein wenig einfacher machbar.

**Comment by RolandStuder** [comment]
Zu entscheiden:

- **Format auf Ebene festhalten oder pro Benutzer**? Pro Benutzer wäre vom Konzept her einfacher, pro Ebene / Gruppe wohl praktischer, wobei die allgemein verwendeten Formate ja schon vom Dachverband angeboten weden können.

### Vorschlag:

* Menü allen zur Verfügung stellen, da alle irgendwo exportieren können (zumindest eigene Angaben).
* Möglichkeit geben, nur die selbst definierten Ettikettenformate anzuzeigen.

Insgesamt brauchen wir längerfristig allgemeine Benutzereinstellungen.

**Comment by RolandStuder** [comment]
Varianten
![](https://wearecube.mybalsamiq.com/mockups/5219421.png)
edit https://wearecube.mybalsamiq.com/projects/hitobito/76%2077%20Etikettenformat

**Comment by RolandStuder** [comment]
3 Dinge nach Priorität

1. Übername -> Identität (gehört dazu, dass ich mit Pfadiname angeschrieben werde)
2. PP mit einer bestimmten Postleihzahl (damit ich diese bei einer bestimmten Poststelle abgeben kann). Muss auch auf Etikett draufpassen können, darf direkt in der Adresszone des Briefs eingedruckt werden. siehe 203.82 PP Frankierung -> als spezifische Felder umsetzen.

**Comment by adriananderegg** [comment]
https://www.post.ch/-/media/post/gk/dokumente/briefe-pp-frankieren-factsheet.pdf?la=de&vs=3

Eine Zeile mit PP Informationen, komplett Userdefiniert.

**Comment by RolandStuder** [comment]
@adriananderegg Bereit zum Testen

**Comment by PBS-MichaelBurkhardtKauri** [comment]
Feld PP-Zeile: Die Postleitzahl "3030 Bern" gibt es nicht. Bitte ein realistisches Beispiel nehmen. Oder ist das Absicht?

**Comment by PBS-MichaelBurkhardtKauri** [comment]
Der Begriff "Übername" kommt mir komisch vor. Wenn der Pfadiname gemeint ist, bitte "Pfadiname" (= Bezeichnung auf Profil) schreiben.

**Comment by MartinGantenbein** [comment]
Übername kann in Hitobito-Core verwendet werden, da dieses Feld auch in Nicht-Pfadi-Organisationen Sinn macht. Felder wie "Pfadiname" sind nicht allgemein gültig und sollten daher im Pfadi-Wagon definiert werden.

**Comment by RolandStuder** [comment]
@PBS-MichaelBurkhardtKauri Wie Martin erwähnt, wir haben diese Funktion im ganzen hitobito aufgenommen. Wir müssen das explizit überschreiben im Pfadi-Wagon. Ich frage mal nach, wie aufwändig das ist.
