### ISSUE TITLE
Metriken mittels prometheus_exporter sammeln (10h)

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito#767]
- [x] Prometheus exporter gem integrieren
- [x] Openshift deployment anpassen
- [x] Dashboards erarbeiten

**Comment by severinraez** [comment]
Beispiel-Setup siehe https://gitlab.puzzle.ch/pitc_ruby/puzzletime-configmanagement/blob/master/base/rails-metrics-exporter.yaml (verwendet das Gem prometheus_exporter)

**Comment by amaierhofer** [comment]
Ist auf der pbs Integration umgesetzt
