### ISSUE TITLE
Optionen für Etiketten für Übername & P.P.

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito#77]
Etikettenformat wird erweitert um

## Übername / Pfadiname / Vulgo

Per Checkbox kann ich sagen, ob ich den Übernamen auf der Etikette / auf dem Couvert verwenden will. Dieser wird vor dem Namen der Person auf einer Separaten Zeile aufgeführt.

## PP Zeile 

Spez siehe: https://www.post.ch/-/media/post/gk/dokumente/briefe-pp-frankieren-factsheet.pdf?la=de&vs=3

Dort sind auch Angaben zu Schriftgrösse usw. drin.
Es gibt zwei Pflichtangaben, das P.P. und die Angabe Post CH AG. Diese bereits anbieten. Diese mit prependen / appended form controls umsetzen siehe: http://getbootstrap.com/2.3.2/base-css.html#forms

* Wichtig: Wenn die PP Zeile leergelasen wird, wird auf der Etikette der entsprechende Platz verwendet. (sonst machen wir bestehende Adressformate kaputt)
* Placeholder mit Beispiel "CH-3030 Bern"
* Feldlänge gemäss Sepzifikation beschränken

![](https://wearecube.mybalsamiq.com/mockups/5219421.png)
edit https://wearecube.mybalsamiq.com/projects/hitobito/76%2077%20Etikettenformat

**Comment by RolandStuder** [comment]
Passt das noch alles ins Thema Etikettentext, machen wir nicht einfach besser einen Switch: Mit / Ohne Übername beim definierten Format. Brauchen wir wirkliche mehr?

**Comment by RolandStuder** [comment]
* Admin auf Einstellungen umbennen

**Comment by RolandStuder** [comment]
@adriananderegg Wäre es nicht besser, dem Benutzer die Pflichteile abzunehmen und etwas zu helfen beim P.P.? Sieh mal die aktualisierte Spez.

**Comment by adriananderegg** [comment]
@RolandStuder für mich ok.

**Comment by RolandStuder** [comment]
@adriananderegg Bereit zum Testen

**Comment by PBS-MichaelBurkhardtKauri** [comment]
Der Begriff "Übername" kommt mir komisch vor. Wenn der Pfadiname gemeint ist, bitte "Pfadiname" (= Bezeichnung auf Profil) schreiben.

**Comment by RolandStuder** [comment]
@PBS-MichaelBurkhardtKauri wird noch angepasst, dass dort Pfadiname steht.
