### ISSUE TITLE
SportDB Export: NDBJS_PERS_NR leer

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito#775]
Im SportDB Export sollte die Spalte NDBJS_PERS_NR eigentlich die J+S-Leiter-Nummer beinhalten. Im Export mit CSV und Excel sowie für die SportDB wie auch die NDBJS ist die Spalte aber immer leer.

**Comment by kronn** [comment]
@nchiapol Ich kann diesen Fehler leider nicht nachvollziehen, was das Beheben etwas schwierig macht. In meinen Tests wird die Nummer korrekt ausgelesen und in das CSV/Excel übertragen. Es wird nur das Format insofern angepasst, dass lediglich Ziffern übernommen werden.

Gibt es ein Beispiel, anhand dessen das fehlerhafte Verhalten direkt sehen kann?

**Comment by maede97** [comment]
Zum Beispiel:
https://cevi.puzzle.ch/groups/306/events/1099/participations?returning=true
Die Person https://cevi.puzzle.ch/groups/306/people/3064.html hat als J+S-Nummer 123456 eingetragen. Diese wird nicht im Output des Events oben angezeigt.

**Comment by kronn** [comment]
Der Bugfix wurde als Hotfix bei cevi, pbs und jubla gestern nachmittag (2019-06-12) in die produktive Instanz übernommen.
