### ISSUE TITLE
SBV: CSV Untergruppen erweitern

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#776]
CSV Untergruppen beim SBV soll wie folgt erweitert werden:
- Angaben zur Kontaktperson (falls vorhanden)
- Spalte "Kantonalverband"

**Comment by RolandStuder** [comment]
Es wäre zu überlegen, ob man nicht allgemein beim Export der Gruppenliste pro Typ von Parent-Layer eine Spalte exportieren möchte, welche sagt, wo die Gruppe dazugehört.

**Comment by RolandStuder** [comment]
@KunoKunz Ich habe mir das schon mal angeschaut, aktuell werden offenbar nur noch  folgende Spalten exportiert:

Name | Gruppentyp | Adresse | PLZ | Ort | Land | Gemeldete Mitglieder

Im früheren Customizen des Exports, der abgelöst aber nicht ersetzt wurde, wurden folgende Spalten exportiert:


Id | Elterngruppe | Name | Kurzname | Gruppentyp | Haupt-E-Mail | Adresse | PLZ | Ort | Land | Ebene | Beschreibung | Vereinssitz | Gründungsjahr | Korrespondenzsprache | Besetzung | Klasse | Unterhaltungsmusik | Subventionen | Gemeldete Mitglieder | Swoffice | sekundär | weitere | Erfasste Mitglieder

Ich nehme an, die Wahrheit liegt irgendwo zwischendrin. Wäre ja schon eigenartig, wenn Besetzung, Klasse, Unterhaltungsmusik gar nicht mehr drin wären, oder?

Es wäre gut eine vollständige Liste zu haben, was genau rein soll, auch:

* Welche Angaben der Kontaktperson (inkl. Telefonnummer / Social Media / weitere e-Mailadressen?)
* Sollen Spalten Besetzung | Klasse | Unterhaltungsmusik auch rein?
* Soll nur die primäre Zuordnung rein, oder sollen auch die Zuordnung zu weiteren Kantonalverbänden erscheinen?

**Comment by RolandStuder** [comment]
Aktuell ist es so umgesetzt:

Name | Gruppentyp | Mitgliederverband | Kontaktperson | Adresse | PLZ | Ort | Land | Gemeldete Mitglieder | Besetzung | Klasse | Unterhaltungsmusik
