### ISSUE TITLE
Initialimport Chöre 

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#778]
Initialübernahme der Chöre des Schwyzer Kantonal-Chorverbands [0] gemäss separater Datei [1]. Pro Zeile soll ein Chor erstellt- und die entsprechende Person als Administrator und SUISA-Verantwortlicher zugeordnet werden.

- Das Feld "Status" im csv kann als Beschreibung gespeichert werden.
- Als Geburstsdatum der Personen 01.01.1900 verwenden

[0] https://db.windband.ch/de/groups/16789/people?returning=true
[1] https://files.puzzle.ch/remote.php/webdav/SOL_Open_Source_L%C3%B6sungen/Hitobito/export%20Hitobito%20Schwyz.csv

**Comment by KunoKunz** [comment]
Es ist möglich, dass Chöre und/oder Personen bereits vorhanden sind.
 
- "Chor und Administrator erfasst"  --> mutieren, wenn abweichende Attribute festgestellt werden
- "Chor erfasst, aber Administrator nicht" --> Chor mutieren, wenn abweichende Attribute festgestellt werden und Administrator/SUISA-Verantwortlichen anlegen, bestehende Personen, die nicht auf dem File sind, ignorieren
- "Chor nicht erfasst, aber Administrator ist als Person schon im System" --> Chor anlegen und betreffende Person mutieren, wenn abweichende Attribute festgestellt werden und Rollen Administrator/SUISA vergeben

**Comment by kronn** [comment]
Die Daten sind importiert.
