### ISSUE TITLE
SPORTdb CSV-Export um AHV_NR ergänzen

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#779]
In Lagern in hitobito_youth, die bei J+S angemeldet werden, muss der J+S-Coach vor Beginn des Lagers die Teilnehmer bei J+S erfassen. Da die Teilnehmer auch in hitobito im Lager erfasst sind, gibt es die Möglichkeit, eine CSV-Datei mit den benötigten Teilnehmerdaten und im benötigten Format aus hitobito herunterzuladen, und diese Datei dann in der SPORTdb hochzuladen. So muss der J+S-Coach nicht jeden Teilnehmer einzeln in einem Formular erfassen. Dieser Workflow funktioniert aber seit dem neuesten Deployment der SPORTdb vom Mi 5.6.19 nicht mehr.

**Steps to reproduce**
* In einer hitobito_youth Instanz ein Lager mit Teilnehmern erstellen.
* Auf dem Teilnehmende-Tab via Export -> CSV -> SPORTdb das SPORTdb-CSV mit den Teilnehmenden-Daten herunterladen
* Das CSV ohne Änderung in ein bewilligtes NG3-Lager auf der SPORTdb hochladen (erlaubtes Format ist [hier](https://www.jugendundsport.ch/content/jus-internet/de/infos-fuer/j-s-coaches/sportdb--hinweise-hilfe-/angebot-anmelden/_jcr_content/contentPar/accordion_copy/accordionItems/merkbl_tter_zum_teil/accordionPar/downloadlist/downloadItems/47_1456398355913.download/3_Anforderungen_SPORTdb_d.pdf) beschrieben, [Muster-CSV](http://www.jugendundsport.ch/content/jus-internet/de/infos-fuer/j-s-coaches/sportdb--hinweise-hilfe-/angebot-anmelden/_jcr_content/contentPar/accordion_copy/accordionItems/merkbl_tter_zum_teil/accordionPar/downloadlist/downloadItems/46_1456398330849.download/musterdatei_teilnehmerimport_sportdb_d.csv))

**Expected Behavior**
Der Import funktioniert ohne Fehler (sofern alle Pflichtfelder korrekt in hitobito ausgefüllt sind). Die `AHV_NR`-Spalte ist im CSV vorhanden, aber immer leer, da die AHV-Nummer nicht in hitobito gespeichert wird (zumindest für PBS).

**Actual Behavior**
Der Import versucht die Strasse-Spalte als `AHV_NR`-Spalte zu interpretieren und alle späteren Spalten werden entsprechend vorverschoben, was in diversen Fehlern resultiert. Das CSV kann in dieser Form nicht importiert werden. (Gleiches gilt für den Excel-Export SPORTdb, um die beiden Optionen konsistent zu halten, obwohl die SPORTdb nur CSV Dateien akzeptiert)

**Manual workaround**
Im heruntergeladenen CSV manuell eine leere Spalte `AHV_NR` zwischen `GEB_DATUM` und `STRASSE` einfügen.

**Comment by diegosteiner** [comment]
https://github.com/hitobito/hitobito_youth/pull/4/files

**Comment by diegosteiner** [comment]
Oh, wohl ein Tick zu spät :(

**Comment by kronn** [comment]
Der Bugfix wurde als Hotfix bei cevi, pbs und jubla gestern nachmittag (2019-06-12) in die produktive Instanz übernommen.
