### ISSUE TITLE
Hauptgruppen-ID und Personen-ID im CSV-Export anzeigen

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito#78]
## Akzeptanzkriterien

* [ ] Bei der PBS sollen für 
   * [ ] full person export
   * [ ] und adress list export zusätzlich folgende Spalten bereitstehen:
   * [ ] personen ID: Label: id
   * [ ] formatierte personen ID (PBS Personennummer) label: Personennummer
   * [ ] id der Ebene der Hauptgruppe: label: Ebene der Hauptgruppe

## Beschreibung
 
Für die Administration von grossen Versänden sollte die ID der Hauptgruppe einer Person sowie die ID der Person im CSV ausgegeben wird. 

## Hintergrund: 
Versand erfolgt mehrmals jährlich zentral an alle Mitglieder in der Schweiz. Post retourniert die nicht zustellbaren Sendungen an den zentralen Verband. Dieser kann auf Grund der Zugriffseinschränkungen die einzelnen Mitglieder aber nicht sehen und so mit den falschen Adressen nichts weiter anfangen. Mit den IDs von Hauptgruppe und Person könnte er die zuständigen Adressverwalter auf die falschen Adressen aufmerksam machen.

Pull Request überprüfen und einbauen: https://github.com/hitobito/hitobito_pbs/pull/15 (Kommentar rstuder: Die Pull Requests hatten Fehler und man musste jeweils noch was korrigieren, und müssten sowieso umgeschrieben werden).

**Comment by RolandStuder** [comment]
Fragen:
- Auch für Export bei der Personenliste?
- Was bietet die API heute diesbezüglich an?
- Gibt es andere Lösungsmöglichkeiten?
- Wäre vielleicht URL zur Gruppe / URL zur Person für diesen konkreten Fall praktischer?
- In welcher Form kommen die retournierten Sendungen, erhält man eine Liste dazu? (Wie können wir den Abgleich zwischen retournierten Sendungen und den Personen in der DB möglichst einfach machen)

**Comment by adriananderegg** [comment]
kann kurzfristig relativ simpel gelöst werden, vgl. pull_request im hitobito_pbs
https://github.com/hitobito/hitobito_pbs/pull/15

**Comment by RolandStuder** [comment]
Habe ich mit Adrian besprochen, hier braucht es wirklich nur, was im Pull-Request (https://github.com/hitobito/hitobito_pbs/pull/15) abgebildet ist. 

Es geht hauptsächlich um den Sarasani Versand, wo der Dachverband viele Rücksendungen, wegen falschen Adressen erhält, und aber nicht Zugriff auf diese Personen hat und somit die Adressen nicht korrigieren kann . Mit der Hauptgruppen ID und der Personen ID kann der Dachverband die Gruppen anschreiben und sie informieren, welche Personen eine ungültige Adresse haben.

**Comment by RolandStuder** [comment]
@adriananderegg Du hast die Attribute beim Full Person Export hinzugefügt. Allerdings benötigst du die Attribute doch Versände, dort wird aber der Adress List Export verwendet. Da für den Versand ja nicht die vollen Daten notwendig sind.

Siehe https://github.com/hitobito/hitobito/blob/92db15a8e375d93f9634c3138335169e8dd6b76a/app/controllers/subscriptions_controller.rb#L47

Ich glaube, wenn ihr also euer Ziel erreichen wollte. Müsste man das noch anpassen.

**Comment by PBS-MichaelBurkhardtKauri** [comment]
Ich konnte beim Testing leider nicht bewerkstelligen, dass die Hauptgruppen-ID im Export ausgegeben wurde. Die Sache ist der Geschäftsstelle wie gesagt wichtig, um die Datenqualität (und den Sarasaniversand) zu verbessern.

**Comment by RolandStuder** [comment]
@PBS-MichaelBurkhardtKauri Die Exportattribute wurde von @adriananderegg am falschen Ort hinzugefügt. Ich habe das einen entsprechende Anpassung als Pull Request gemacht (die Entwickler werden das nochmals kurz überprüfen). Allerdings bedeutet dies, dass diese Attribute neu bei allen Adresslisten erscheinen werden, auch wenn man einen Adresslistenexport von einer Personenliste macht, was halt etwas unschön ist.

Wir schreiben, dir wenn das angepasst ist.

**Comment by psunix** [comment]
Implemented, Code Review durch @kronn
@RolandStuder bitte noch auf int testen

**Comment by RolandStuder** [comment]
Ist bereits deployed
