### ISSUE TITLE
insieme: fehlende Angabe "Firmenname" beim Etikettendruck

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#780]
Gemeldet von insieme Schweiz: Beim Export von Etiketten wird der Firmenname nicht mehr angegeben, was für sie ärgerlich ist, weil dann z.B. die Adressen der Regionalvereine nicht mehr funktionieren.

Zeitlich könnte dies mit den Umstellungen zu #725 #763 zusammenhängen. Gemäss insieme  wurde bei einem Versand im April das Feld "Firmenname" noch auf die Etiketten exportiert.

**Comment by RolandStuder** [comment]
Hat vielleicht eher ein Zusammenhang mit dem hier: https://github.com/hitobito/hitobito/pull/748

**Comment by KunoKunz** [comment]
Zum Export-Problem hat insieme noch folgende Ergänzungen:
- Der Firmenname erscheint nur auf der Etikette, wenn ein Eintrag als "Firma" markiert ist.
- Wir möchten aber den Firmennamen auch dann, wenn ein Eintrag einer Person zusätzlich diesen enthält (so war es auch vor zwei Monaten schon).
- Wir haben den Verdacht, dass dies nicht mehr so ist, seit die "Spaltenauswahl" beim Export möglich ist.

**Comment by RolandStuder** [comment]
@KunoKunz Bitte schau den Hinweis oben an das wurde mit einem Pull Request explizit geändert: #748

**Comment by nchiapol** [comment]
Einfach zur Info: Dass der Firmenname nur angezeigt wird, wenn Firma markiert ist, ist nach wie vor das gewünschte Verhalten für uns. Zusätzlich zum Missverständnis mit dem Arbeitsgeber nutzen gerade jüngere Cevianer das Feld immer wieder für Spasseinträge oder ihre Ortsgruppe oder ...
