### ISSUE TITLE
Nachmigration weiterer Felder aus Swoffice

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#781]
Können folgende Personeninformationen aus Swoffice nachträglich noch zugeordnet werden?

- Adresszusatz
- Sprache

**Comment by kronn** [comment]
Die Personen kann ich nur via email (ideal, weil eindeutig) oder über {vorname, name, geburtsdatum} finden und zuordnen. Es geht, aber vielleicht nicht in jedem Fall.

**Comment by kronn** [comment]
Die Daten sollen manuell erfasst werden.
