### ISSUE TITLE
Logoupload pro Gruppe ermöglichen

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#784]
Es soll möglich sein, pro Gruppe ein Logo hochzuladen. Dies soll dann für diese Gruppe und alle untergeordneten Gruppen verwendet werden. Abhängig davon, was einfacher ist kann dies entweder nur bestimmten Gruppen erlaubt sein (Dachverbände) oder auf allen Hierarchiestufen möglich sein.

- [x] Upload
- [x] Anzeige auf Gruppe
- [x] Anzeige in Untergruppen
- [ ] Checkbox für weiße Hintergrund

Teil von #651

**Comment by RolandStuder** [comment]
siehe Issue schon #90

**Comment by kronn** [comment]
Die Checkbox, ob ein weißer HIntergrund angezeigt wird, lasse ich bewusst sein. Aktuell ist es eine Einstellung, die für die ganze Instanz gilt. Der Hintergrund des Logos ist auch nicht immer weiß, sondern stark abhängig von der Farbgebung der gesamten Instanz.
