### ISSUE TITLE
Domains auf bestimmte Gruppen zeigen lassen

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#785]
Ähnlich wie schon für die mandantenfähige Version soll die verwendete Domain auf eine bestimmte Gruppe zeigen. Im Fall der mandantenfähigen Version wird die gesamte Struktur eingeschränkt. Hier soll nur die korrekte Unterstruktur der Superstruktur gewählt werden. Es kann sein, dass die durch die Berechtigungen des eingeloggten Benutzers bereits erledigt wird. In jeden Fall muss die Loginseite die Domain widerspiegeln.

- [x] Loginseite nach Domain
- [x] Gruppensichtbarkeit prüfen

Teil von #651

**Comment by kronn** [comment]
Die Gruppensichtbarkeit wird nicht weiter eingeschränkt. Die Struktur ist sichtbar, die Personen darin (und deren Kontaktdaten) nur, wenn man dafür berechtigt ist.

**Comment by KunoKunz** [comment]
In der Testversion scheint das noch nicht überall zu klappen. Beim Erstellen von Events wird z.B. nicht die URL des Verbands der Testperson verwendet (https://sbv.puzzle.ch/de/groups/16409/public_events/16). Erstellt als https://sbv.puzzle.ch/de/groups/16409/people/71326 für die Chorvereinigung. Könntest du dir das bitte noch einmal anschauen, @kronn ?

**Comment by KunoKunz** [comment]
> Die Gruppensichtbarkeit wird nicht weiter eingeschränkt. Die Struktur ist sichtbar, die Personen darin (und deren Kontaktdaten) nur, wenn man dafür berechtigt ist.

Ich würde dies noch einmal überdenken wollen, insbesondere die oberste (Super-)Struktur braucht es m.E. nicht sichtbar zu sein.

**Comment by olibrian** [comment]
Keine weiteren Aktionen geplant.
