### ISSUE TITLE
E-Mailversand bei mehreren Domains korrekt beachten (8h)

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#787]
Wie in #651 spezifiziert:

> Mailinglisten von mehreren Domains abholen und korrekt verteilen (dachverband@db.windband.ch ist eine andere Mailingliste als dachverband@db.jodler.ch)

- [ ] Lösung von hitobito_tenants übernehmen und anpassen
- [ ] Dokumentation für die Integration einer neuen Domain schreiben

Siehe auch #785

**Comment by kronn** [comment]
Es ist nach Rücksprache mit dem SBV nicht notwendig, dass gleiche mailinglisten-namen bei unterschiedlichen Domains unterstützt werden.

**Comment by ThomasEllenberger** [comment]
Da durch den SBV aktuell nicht gewünscht, schliessen wir dieses Issue.
