### ISSUE TITLE
Dachverband Platzhalter bei Login Senden und Meldeliste (8h)

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#788]
Bei den Emails "Login Senden" und "Meldeliste: E-Mail Erinnerung" soll der Gruppen Name des Dachverbands als Platzhalter verwendet werden können.

Siehe #651

**Comment by ThomasEllenberger** [comment]
Da durch den SBV aktuell nicht priorisiert, schliessen wir dieses Issue.
