### ISSUE TITLE
Datencockpit

### ISSUE THREAD

**Issue by adriananderegg** [hitobito/hitobito#79]
Ausgangslage
Ein Tool zur Überprüfung der Datenqualität wäre wünschenswert. Hierbei geht es nicht um ein Dashboard sondern lediglich um die Nachvollziehbarkeit in welchen Abteilungen/KV’s Mutationen an den Datensätzen vorgenommen wurden. 

Ziel / UserStory
Als Benutzer möchte ich einen Überblick über die Datenqualität in der MiData erhalten. Zudem soll es möglich sein zu identifizieren wie aktiv eine Gruppe ist und wie aktuell die Daten sind.
Mögliche Daten welche relevant erscheinen:
-	Anzahl Personen die in der MiData erfasst sind
-	Anzahl Personen die in der MiData erfasst sind und eine Rolle besitzen
-	Anzahl Personen gemäss Bestandesmeldung
-	Grad der Besetzung von definierten Rollen (z.B. jede Abteilung hat einen Coach; jeder KV hat einen Krisenverantwortlichen)
-	Anzahl Gruppen
-	Anzahl Abteilungen
-	Anzahl Logins pro Layer (Bund, KV, Region, Abteilung)
-	Anzahl Mutationen pro Layer
-	Anzahl Mutationen pro Gruppe

 
Variante 1 (Einfache Datenauswertung)
Die Serverlog Files und CSV Exports aus der MiData werden einmalig offline ausgewertet. Der Zeithorizont ist fix definiert. Mit einem gewissen Aufwand lässt sich die Auswertung wiederholen. Die Herausforderung besteht insbesondere bei der richtigen Interpretierung der Serverlog Files. So muss beispielsweise die betroffene Layer identifiziert werden.
Vorteil: Geringer Aufwand; kann Ehrenamtlich erfolgen
Nachteil: Aufwand erfolgt pro Auswertung; Auswertung ist eine Momentaufnahme
Variante 2 (Dashboard)
Zusätzliche Daten welche bei einer Auswertung direkt in der MiData relevant sind:
-	Letzte Änderung im Layer / Gruppe
-	Grösse der Untergruppen
-	Übersicht der aktuellen Rolle (abhängig vom Layer)
-	Verlauf der Mitglieder über die Zeit
-	Organigramm der Untergruppen
-	Geo-Location Information
Vorteil: Aufwand ist nur einmalig und die Auswertung kann wiederholt werden; zugänglich für alle Benutzer der MiData
Nachteil: Entwicklungsaufwand; Spezifikation des Dashboards

Variante 2a (Entwicklung eines Dashboards)
Ansicht ist statisch und kann nicht vom Benutzer angepasst werden.
Variante 2b (Integration eines bestehenden Frameworks)
Integration eines bestehenden Frameworks. Das Dashboard kann, soweit dies das Framework zulässt, vom Benutzer angepasst werden.

**Comment by RolandStuder** [comment]
Ich bin nicht sicher, ob das Anliegen hinter dem Dashboard richtig verstehe. Es hat ja nicht nur mit Datenqualität zu tun. Ich werde versuchen noch etwas zu erfahren, inwiefern Logs nach diesen Daten ausgewertet werden können. Evtl. wäre ein bestehendes Monitoring-Tool, dass man über APIs anbindet eine bessere Lösung.

Ich denke, da müssen wir die Teilaspekte ein bisschen auseinandernehmen.

Mockup, damit wir nachher drauf zeichnen können:
https://wearecube.mybalsamiq.com/mockups/4968568.png

https://wearecube.mybalsamiq.com/projects/hitobito/Dashboard

**Comment by RolandStuder** [comment]
Erste Drei unnötig

* Grad der Besetzung über die Ebene hinaus -> Momentaufnahme
* Personen mit einem Zugriffsaccount (gesetzes Passwort) Anzahl Personen > 1 Login erfolgt. -> aktiv im letzten Jahr / letzen Monat....
* Mutationen pro Layer.
* Ein Design, eine sinnvolle Einbettung in bestehende Bestandesmeldung und Statistik.

**Comment by RolandStuder** [comment]
Ich schliesse diese Issue und markiere es als `stale` war kein Thema mehr.
