### ISSUE TITLE
Jubla: gelöschte Person wiederherstellen

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#793]
Das Profil und damit auch seine sämtlichen Rollen von Gio Cettuzzi (gio.cettuzzi@jubla.ch) wurde am Vormittag des 25.06.2019 gelöscht. Bitte diese Daten aus einem Backup heraus wiederherstellen.

**Comment by olibrian** [comment]
Kann gemäss Meeting mit der Jubla am 10.9.2019 geschlossen werden.
