### ISSUE TITLE
"Lager durchgeführt im Kanton" zeigt falsche Lager

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#799]
Beim Kantonalverband gibt es die Lager-Ansicht "durchgeführt im Kanton". Diese sollte nur die Lager anzeigen, die im Feld "Kanton / Land" den entsprechenden Kantonalverband ausgewählt haben. Tatsächlich werden im Moment aber dieselben Lager angezeigt wie bei der Ansicht "Alle".

Für die Krisenteams und Kantonalverbände ist die Ansicht gerade jetzt in der Lagersaison unverzichtbar.

Zu beachten ist, dass ein Kantonalverband aus mehreren Kantonen bestehen kann. Die Kantone können pro Kantonalverband konfiguriert werden (Gruppe bearbeiten).

Siehe auch:
https://github.com/hitobito/hitobito/issues/517

**Comment by Michael-Schaer** [comment]
Vielleicht noch für Verständnis: Die Ansicht zeigt normalerweise auch Lager aus anderen Kantonalverbänden, nicht nur die eigenen.

**Comment by amaierhofer** [comment]
@Michael-Schaer Ich habe den Fehler korrigiert und auf Integration deployed. Bitte prüfe das Verhalten dort. Wann wäre ein günstiger Zeitpunkt für euch ist, diese isolierte Änderung auf Produktion zu deployen?

**Comment by Michael-Schaer** [comment]
Merci fürs Update!

Jetzt werden zwar die Lager auf den Kanton gefiltert. Lager von anderen Kantonalverbänden werden aber noch nicht angezeigt. Z.B. das Lager [hier](https://pbs.puzzle.ch/de/groups/594/events/1040) sollte in den [Lagern durchgeführt im Kanton bei Zürich](https://pbs.puzzle.ch/de/groups/3/events/camp?filter=canton&year=2019) angezeigt werden.

**Comment by amaierhofer** [comment]
@Michael-Schaer Danke fürs Feedback. Ich habe nochmal etwas angepasst, allerdings wird das Lager nur dann angezeigt, wenn der entsprechende Kantonalverband (in dem Fall Aargau) dem Kanton Zürich zugeordnet ist. Macht dies Einschränkung Sinn oder soll die auch noch entfernt werden? Die Performance wäre sicher besser, wenn man die Kantone explizit zuordnen würde.

**Comment by Michael-Schaer** [comment]
Ein Kantonalverband stellt sich die Frage: "Welche Lager finden im Gebiet unseres Kantonalverbandes statt?" Die "fremden" Lager sind eigentlich das wichtigste an der Ansicht. Die aktuelle Einschränkung auf eigene Lager macht also keinen Sinn.

Ich kann leider nicht genau sagen, seit wann diese Ansicht nicht mehr stimmt. Laut [diesem Ticket](https://github.com/hitobito/hitobito/issues/517) hat sie am 6.4.2018 gestimmt. Bitte auch einen Abgleich mit dem Stand machen, für den Fall dass wir jetzt etwas vergessen.
