### ISSUE TITLE
Spendenverwaltung

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#80]
**Ziel:** 
Auf einer Webseite kann einfach eine Online Spende via Payrexx erfolgen. Integration eines Zahlungsprovider für Online-Spenden.

**User Story**

1. Einfache Online Zahlung auf der Webseite
2. Übermittlung von Name, Vorname, Mailadresse, Zahlungszweck
3. Zahlung wird in Hitobito übernommen. Falls es aufgrund der Mailadresse ein Match mit einer bestehender Person gibt, wird diese Spende der Person angehängt. Falls kein Match gibt, wird eine neue Person angelegt.

**Mögliche zukünftige Erweiterungen**

- Pro Instanz mehrere Payments-Accounts zulassen. Dies wenn eine Organisation pro Gruppe unterschiedliche Payment-Accounts hat. Beispiel pro Kantonalverband ein Account.
- Weitere Zahlungsprovider anbinden (Raisenow, weitere?)
- Auswertung der Spenden (Wie viel wurde im Jahr gespendet, Aufschlüsselung nach Zahlungszweck)
- Segmentieren der Spenden. Zum Beispiel alle Spender, die früher gespendet haben, aber nichts mehr in den letzten 12 Monaten.
- Spendenbescheinigung
- Automatische, jährliche Spendenbescheinigung

**Comment by RolandStuder** [comment]
Aktuell wieder in Diskussion unter: https://hitobito.discoursehosting.net/t/spenden-und-goenner-verwalten/61

**Comment by ThomasEllenberger** [comment]
Issue Closed, da wir im Moment RaiseNow als Spendentool weiterverfolgen.
INVOICES: RaiseNow Integration (https://github.com/hitobito/hitobito/issues/2023)
