### ISSUE TITLE
Kursabschluss Kurse, LK Treffpunkt (12h)

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#800]
Kursabschluss (Kurse) grundsätzlich analog «Semester- / Jahreskurs, die durchgestrichenen Punkte können ausgeblendet oder entfernt werden)

- Leistungskategorie
- Fachkonzept
- Subventioniert
- ~Kursart~
- Kursdauer in Stunden (Hinweis in Grau: «inkl. 1h Vor- und Nachbereitung)
- Reporting im Jahr
- Effektiv Teilnehmende
    - Behinderte (mit Kantonsauswahl & «davon Mehrfachbehinderte»)
    - Angehörige (mit Kantonsauswahl)
    - Weitere, nicht Beitragsberechtigt
- ~Total TeilnehmerInnenstunden~
- NEU: Total Betreuungsstunden
    - Betreuungsstunden [Berechnet aus Anzahl Betreuungspersonen x Kursdauer in Stunden]
- BetreuerInnen
    - Betreuungspersonen
    - Betreuungsschlüssel
- ~Personal ohne Betreuungsfunktion~
- Direkter Aufwand
    - Honorare inkl. Sozialversicherung
    - Unterkunft / Raumaufwand
    - Übriges inkl. Verpflegung
- Ertrag
    - Beiträge TN
- Auswertungen
- Total direkte Kosten
    - Gemeinkostenanteil
    - Total Vollkosten
    - Anzahl tatsächliche LE
    - Vollkosten pro LE
    - ~Zugeteilte Kategorie~

**Comment by cimnine** [comment]
Wurde hier bewusst auf "Kursdauer in Stunden" geschrieben? Weil die anderen Kurse (Blockkurs, Tageskurs, Sammelkurs) kennen alle nur "Kursdauer in Tagen".

Wenn das so ist, wie sollen in diesem Fall die Stunden gespeichert werden?

Mir kommen folgende Vorschläge in den Sinn:

* Eine eigene Tabelle `block_course_records` mit einem entsprechenden Modell analog `event_course_records`. Darin wird die Zeit jeweils in Stunden statt in Tagen gespeichert und gerechnet.
  * Vorteile: Saubere Trennung zwischen Rechnung in Stunden und Tagen
  * Nachteile: Viel Aufwand; viel Funktionalität die - bis auf den Unterschied Tage / Stunden - eigentlich gleich ist; in den Controllern / Views muss - je na Kursart - zwischen zwei Models unterschieden werden
* Eine Umrechnung von Stunden in Tagen, z.B. 12h = 0.5d.
  * Vorteile: Viel Code kann direkt wiederverwendet werden
  * Nachteile: Wie lange geht ein Tag? (8h? 24h?) In den Views muss - je nach Fall - die Zeit von Tagen wieder in Stunden umgerechnet werden. Dies gibt allenfalls Rundungsverluste (z.B. 8h = 0.333333333... Tage, bei 24h pro Tag, was - je nach Rundung - 0.79999h ergibt)
* Die kleinste Einheit ist Tage und es wird keine Stunden geben, die Spezifikation wird entsprechend angepasst.

**Comment by kronn** [comment]
Da für diese Leistungkategorie nur die Kursdauer als Zeit eingetragen wird, speichern wir dieses erstmal in einer neuen Spalte `kursdauer_stunden`. Damit umgehen wir die Umrechnungsprobleme und auch eine unnötige Doppelung im Code.

**Comment by cimnine** [comment]
Ich habe noch eine andere Kategorie gefunden, die auch mit Stunden arbeitet. Im `Event::CourseRecordDecorator` wird zwischen Stunden und Tagen unterschieden. Schön ist auch das nicht, aber das existiert so schon.

**Comment by kronn** [comment]
Hmm... ja, das ist tatsächlich ein Argument. Letztlich sagt "Kursdauer" ja auch nichts über die Einheit aus.
