### ISSUE TITLE
Mail wird als Spam deklariert

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#803]
Mails welche an ein Abo geschickt werden, landen bei der Jubla als Spam.

Vermeintliches Mail:
```
Von: <bulei-bounces+monika.elmiger=jubla.ch@db.jubla.ch> im Auftrag von Monika Elmiger <monika.elmiger@jubla.ch>
Datum: Montag, 15. Juli 2019 um 08:11
An: "bulei@db.jubla.ch" <bulei@db.jubla.ch>
Betreff: Arbeitszeit Apéro Vince
```

Mailversand von monika.elmiger@jubla.ch an den Mailverteiler bulei@db.jubla.ch

**Comment by kronn** [comment]
Der Mailserver wurde umgestellt. Damit sollte das Problem erstmal behoben sein.

**Comment by olibrian** [comment]
Gemäss Kunde landen immer noch einige Mails im Spam Ordner. Das Abo bulei@db.jubla.ch scheint zu funktionieren. Bei den folgende Abos landet jedoch das Mail im Spam: ch.fg.ausbildung@db.jubla.ch; ch.fg.ehemalige@db.jubla.ch

**Comment by olibrian** [comment]
Server auf der Whiteliste eingetragen und SPF Eintrag erstellt. Kann in Absprache mit Anna geschlossen werden.
