### ISSUE TITLE
Übersicht "Meine Abos" (22h)

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#805]
Ausgangslage: Als Benutzer habe ich heute keine Übersicht, für welche Abos ich mich überhaupt anmelden kann und welche davon ich abonniert habe. Ein bestehender Kunde möchte, dass wir da etwas machen.

**Anforderung: Eine Übersicht über alle Abos, für die ich mich an- oder abmelden darf**
-> Heute gibt es bereits die Checkbox "Abonnenten dürfen sich selbst an-/abmelden". Gibt es Einwände, dass wir uns darauf abstützen? Z.B. für Mailinglisten aus anderen Regionen, auf die ich sonst gar keinen Zugriff habe? Ansonsten könnte ja eine zusätzliches Feld (z.B. "öffentliches Abo") eingefügt werden.

**Anforderung: Übersichtliche Darstellung**
Die Übersicht sollte u.U. aufgeteilt werden, damit diese übersichtlich bleibt. Z.B. zuerst die Abos auf auf meiner Stufe und allen darüberliegenden Stufen anzeigen. Evtl. mit einem weiteren Klick danach auch die "öffentlichen" Abos aus anderen Stufen/Regionen angezeigt werden.

**Anforderung: Einfache An-/Abmeldung über einen Button**
-> Die An- und Abmeldung soll mit einem Klick in der Liste erfolgen. Abos, für die ich bereits angemeldet sind, sollten als solche ersichtlich sein.

**Anforderung: Filter-/Suchfunktion nach Name/Region, Sektion, Stufe etc.**

**Comment by amaierhofer** [comment]
Folgenden Vorschlag ohne Suche schätze ich auf (14h)

- Neuer "Abos" Tab auf der Person (2h)
- Auflistung aller öffentlichen MailingListen, gruppiert nach Ebenen, eventuell Ebene der primär Gruppe zuerst? (8h)
- Anmelden / Abmelden Buttons, feststellen ob schon angemeldet (4h)
- Such oder Filter? Wonach genau?

**Comment by olibrian** [comment]
Wurde mit https://github.com/hitobito/hitobito_glp/issues/2 gelöst und steht via Config auf für alle Wagons zur Verfügung.
