### ISSUE TITLE
Zusätzliche Datenfelder Person (12h)

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#806]
Der Generic-Wagon soll um folgende Felder ergänzt werden:
• Titel (Dr., Prof., BA, BSc, MA, MSc)
• Korrespondenzsprache (Deutsch, Französisch, Italienisch, Englisch)
• weitere Sprachen 
• Nationalität
• Werbung erlaubt (Nein / Ja, durch Mitglieder / Ja, durch Mitglieder und Dritte )
[edit 21.08: Anrede wird nicht benötigt, da die Unterscheidung über das Geschlecht erfolgen kann]

**Comment by nchiapol** [comment]
Wir haben das im Cevi diskutiert und sind grundsätzlich einverstanden, dass die Felder im Core ergänzt werden. Unklar ist uns was ihr mit den Daten in den Bestehenden Feldern macht. Wir haben bereits folgende Felder
 * Anrede (Sie/Du/unbekannt) - Neu: Anrede (Frau, Herr) [1]
 * Titel (Freies Textfeld) - Neu: Titel (Dr., Prof., BA, BSc, MA, MSc)
 * Korrespondenzsprache (Freies Textfeld) - Neu: Korrespondenzsprache (Deutsch, Französisch, Italienisch, Englisch)

Bei den Textfeldern könnt ihr wohl besser beurteilen, ob die bestehenden Werte auf eure Auswahlen abgeblidet werden können.

[1] das Geschlecht ist bereits über das Feld Geschlecht abgedeckt - Entsprechend scheint dieses neue Feld ziemlich sinnlos. Für Labels/Exporte kann der korrekte Wert ja berechnet werden.

**Comment by amaierhofer** [comment]
Hier eine Aufstellung der Wagon spezifischen Personen attribute als Grundlage zur Diskussion welches Feld wohin soll und ob eventuell zwischen Wagons vereinfacht werden kann.

## CEVI
- ahv_number
- ahv_number_old
- canton
- confession
- correspondence_language
- j_s_number
- joined
- member_card_number
- name_parents
- nationality
- nationality_j_s
- old_data
- ortsgruppe_id
- profession
- salutation
- salutation_parents
- title

## DSJ
- contact_number
- correspondence_language
- current_secondary_appointment
- financial_support
- function
- political_party
- salutation
- salutation_addition
- website


## GLP
- joined_at
- joining_journey
- left_at
- occupation
- paperless
- place_of_origin
- preferred_language
- second_factor_code
- second_factor_generated_at
- second_factor_unsuccessful_tries
- title
- website_url

## INSIEME
- ahv_number
- canton
- correspondence_language
- dossier
- language
- number
- reference_person_number
- salutation

## PBS
- ahv_number
- brother_and_sisters
- correspondence_language
- entry_date
- grade_of_school
- j_s_number
- kantonalverband_id
- leaving_date
- nationality_j_s
- pbs_number
- salutation
- title

## PRO NATURA
- adress_nummer
- ahv_number
- j_s_number
- language
- nationality_j_s

## SBV
- active_role
- active_years
- correspondence_language
- personal_data_usage
- profession

**Comment by olibrian** [comment]
Attribute wurden im Generic Wagon ergänzt. Corespondence Language ist harmonisiert. Salutation ist noch offen im Ticket: https://github.com/hitobito/hitobito/issues/1141
