### ISSUE TITLE
Fehlerseite bei ICS-Export

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#807]
Der folgende Aufruf führt zu einem Fehler:

https://db.scout.ch/de/groups/2/events/9734.ics

> 500 Internal Server Error
> If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.

Die Fehlerseite ist sehr unschön und die Funktion sollte gefixt werden. Dringend ist es aber nicht.

Siehe auch https://github.com/hitobito/hitobito/issues/475

**Comment by amaierhofer** [comment]
Ist im aktuellen master bereits behoben
