### ISSUE TITLE
Zusammenfassung Rückmeldungen Rechnungsmodul 

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#809]
Die Issues dafür müssten noch geschätzt werden:

- Bugreport Tests PBS: https://github.com/hitobito/hitobito/issues/697 und https://github.com/hitobito/hitobito/issues/744
- Bugreport Tests Cevi: https://github.com/hitobito/hitobito/issues/718
- Wünsche/Feedback Jubla wie z.B. Konfigurierbarkeit der Adresse https://github.com/hitobito/hitobito/issues/676 -> wird zur Zeit nicht umgesetzt.
- Internationalisierung: Damit wir die SaaS-Lösung auch international anbieten können, müssten Angaben wie Währung etc. konfigurierbar gemacht werden: https://github.com/hitobito/hitobito/issues/611

**Comment by olibrian** [comment]
Schätzung vorhanden. Folgende Issue:

- Bugreport Tests PBS: https://github.com/hitobito/hitobito/issues/697 und https://github.com/hitobito/hitobito/issues/744
- Bugreport Tests Cevi: https://github.com/hitobito/hitobito/issues/718
- Internationalisierung: Damit wir die SaaS-Lösung auch international anbieten können, müssten Angaben wie Währung etc. konfigurierbar gemacht werden: https://github.com/hitobito/hitobito/issues/611

#697 #744 #718 #611
