### ISSUE TITLE
Firmen verwalten

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#81]
Heute kann auf einer Person nur mit einer Checkbox bestimmt werden, ob es sich um eine Firma handelt. Neu sollen Firmen erfasst und dieser auch mehrere Personen zugeordnet werden können.

**Comment by RolandStuder** [comment]
Für die DSJ haben wir gemacht, dass Personen, die im Feld Firma den gleichen Eintrag haben bei den Personen unter Mitarbeiter angezeigt werden. Das deckt zumindest ab, dass man sieht wer zusammengehört. Ich schliesse diese Issue damit, siehe https://github.com/hitobito/hitobito/issues/187, ist seit Version 1.15 drin
