### ISSUE TITLE
Rollenanzeige wird nach Direktbearbeitung falsch aktualisiert

### ISSUE THREAD

**Issue by cdn64** [hitobito/hitobito#812]
Wenn in der Personenliste einer Gruppe eine Rolle direkt geändert wird (mit dem Bearbeiten-Icon-Popover), lädt Hitobito die geänderte Rollenliste nach und zeigt sie an. Dabei werden aber die Rollen aller Gruppen geladen, nicht nur die Rollen in der aktuellen Gruppe.

**Steps to reproduce**:
1. Öffne https://demo.hitobito.ch/en/users/sign_in
1. Logge dich als admin@hitobito.ch ein 
1. Gehe zur Gruppe "Efficiency Club Bern/Mitlieder" (sic)
1. Ändere die eigene Rolle per Bearbeiten-Popover [1]

**Expected outcome**: Geänderte Rolle in dieser Gruppe wird nachgeladen
**Actual outcome**: Alle Rollen der eingeloggten Person werden nachgeladen [2]

---

[1] 
![grafik](https://user-images.githubusercontent.com/656013/64011493-126a7400-cb1c-11e9-89f9-bcc6131d02a8.png)
[2] 
![grafik](https://user-images.githubusercontent.com/656013/64011508-1c8c7280-cb1c-11e9-85dd-37359085f771.png)

**Comment by carlobeltrame** [comment]
Siehe auch PR https://github.com/hitobito/hitobito/pull/382 in dem dasselbe Problem schon einmal gefixt wurde
