### ISSUE TITLE
Mailchimp-Export für GLP erweitern (24h)

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#815]
Die Exporte nach Mailichimp sollen um folgende Attribute ergänzt werden:
■ Sprache
■ Adresse (Optional)
■ PLZ
■ Ort (Optional)
■ Tags*
■ Geschlecht
■ Rollen
■ Geburtsdatum
■ Paperless

Rollen: "Symp", "Mitglieder", "Medien und Dritte"

* [x] Tags: noch mit Sam abklären, welche Informationen dort wofür verwendet werden müssen? Problem von mehreren Tags, welche danach nicht sauber importiert werden können (= Zuordnung in Mailchimp nicht klar)

**Comment by KunoKunz** [comment]
Es sollen sämtliche Tags exportiert werden. Hier stellt sich u.U. das Problem, das einzelne Werte mit Semikolon und andere mit Komma exportiert werden. Dies muss für die Integration bei Mailchimp noch berücksichtigt werden.

**Comment by amaierhofer** [comment]
Folgende Felder (Geschlecht, Rollen Paperless) können nicht direkt im API abgebildet werde, wir müssen noch festlegen wie die abgebildet werden sollen.

**Comment by KunoKunz** [comment]
@amaierhofer wäre es möglich, die Jobs für das Abgleichen regelmässig automatisch anzustossen? Würde dies viel zusätzlichen Aufwand bedeuten?

**Comment by amaierhofer** [comment]
Ja, wäre kein grosser Aufwand, ca 2h

**Comment by olibrian** [comment]
Gelöst durch:
https://github.com/hitobito/hitobito_glp/issues/11
https://github.com/hitobito/hitobito_glp/issues/6
