### ISSUE TITLE
Testrückmeldung insieme

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#816]
Etwas müsste möglichst schnell geflickt werden, damit wir testen können: Wenn ich einen Kurs oder Sammelkurs erstellen oder bearbeiten will, komme ich jeweils nur hierhin:

Entschuldigung, da ging etwas schief (500)

**Comment by kronn** [comment]
Der Fehler lag an einer Fehlkonfiguration, welche die notwendigen Änderungen an der Datenbank nicht ausgeführt hat. Der Fehler ist behoben und die Datenbank ist jetzt im richtigen Stand.
