### ISSUE TITLE
Testrückmeldungen Formular GLP

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#817]
Bei der GLP kann man sich über verschiedene Formulare (als potenzielles Mitglied oder Sympathisant/Abonnent) anmelden. Dabei erfolgt eine Zuordnung über die PLZ auf die entsprechende Gruppe. Neu soll dies auch für Menschen im Ausland möglich sein.

Bei den Tests der GLP sind folgende Punkte festgestellt worden:

- PLZs aus dem Ausland zulassen
        DE       Funktioniert nicht!
        FR       Funktioniert nicht!
        IT        Funktioniert nicht!

*[ ] bei beiden Formularen prüfen, ob das Land noch mitgegeben werden muss. "Schweiz" ist offenbar voreingestellt. Alternativ auch ohne die Prüfung der PLZ auf CH.

- Checkbox für JGLP + mail an jglp
        DE       keine Checkbox im Formular nur Link in Mail
        FR       keine Checkbox im Formular nur Link in Mail
        IT        keine Checkbox im Formular nur Link in Mail

Checkbox sollte nur bei Mitglieder-Formularen (de, fr, it) vorhanden sein, nicht bei den anderen. Text Chechbox "Ich bin unter 26 und möchte Mitglied bei der JGLP werden" https://grunliberale.ch/formulartest_mitglied/formulartest_symp-news

**Comment by KunoKunz** [comment]
* [ ] Zugriff auf Formular(e) (ak), bestenfalls auf Staging-Ebene
* [ ] Gestaltung Checkbox bei GLP oder Zeilenwerk?
* [ ] Ansprechperson GLP
* [ ] Testrückmeldung hier anhängen (ak)

**Comment by amaierhofer** [comment]
@KunoKunz wie ist der status? Können wir das schliessen?

**Comment by olibrian** [comment]
Wir schliessen hier dieses Ticket. ZW beschreibt noch die offenen Task.
