### ISSUE TITLE
Mailchimp-Export Abgleich der Kontaktdaten

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#818]
Der Mailchimp-Abgleich bei der GLP kann heute folgende Situation ergeben:
Aus glp-community wurde Person gelöscht. In MailChimp ist diese aber auch nach diversen Exporten immer noch drin.

Folgende Methode synchronisiert von hitobito aus die Mailingliste/Abo mit der Audience (?) in Mailchimp.
https://github.com/hitobito/hitobito/blob/d03b299bf25331a854c7f9c8055077c8f3a12c67/app/domain/synchronize/mailchimp/synchronizator.rb

About Audiences in Mailchimp:

 "Audience

Your audience should be your total collection of contacts, so you should only need one overall audience. If you still choose to create multiple audiences, be aware that audiences are independent of each other. They don’t share data or contact information. For example, if freddie@address.com is in two of your audiences, we count that as two contacts. It’s almost always best to have a single audience, and use our audience organization tools to separate and manage contacts. [https://mailchimp.com/help/create-audience/]"

Offenbar wird bei jedem Export eine neue Audience erstellt. Wie oben beschrieben, sind diese unabhängig voneinander. 

Möglicher organisatorischer Workaround: via Mailchimp austragen (unsubscribe funktioniert gemäss Aussage der GLP. 

*[ ] ak->GLP: gibt es für das Austragen in Mailchimp verschiedene Optionen (eine/alle Mailinglisten)?

Gewünschtes Verhalten:
Es gibt m.E. drei Anwendungsfälle:
- Person wird aus DB gelöscht -> in Mailchimp aus allen Audiences löschen
- Person hat entsprechendes Flag nicht mehr -> in Mailchimp aus allen Audiences löschen
- Person wird von einem Abo ausgetragen -> in entsprechender Mailchimp Audience löschen

**Comment by amaierhofer** [comment]
Folgende Code Anpassungen wären aus meiner Sicht zwingend notwendig

- Neuer Job, der nächtlich die bestehenden Listen mit mailchimp synchronisiert
- Paging im synchronisierungs code berücksichtigen

**Comment by cdn64** [comment]
> Aus glp-community wurde Person gelöscht. In MailChimp ist diese aber auch nach diversen Exporten immer noch drin.

Ich sehe es gleich wie Du @amaierhofer – das oben geschriebene Problem scheint mir mit der Paginierung der MC-API zusammenzuhängen und ist genau das Problem, was in #791 mitigiert wird. Können wir diesen PR vorantreiben? @kronn hat den ja schon approved…

**Comment by amaierhofer** [comment]
Der PR wurde gemerged und auf glp prod deployed. Falls jetzt noch immer Probleme bestehen, bitte neues Ticket erfassen. Diese kann aus meiner sicht geschlossen werden.
