### ISSUE TITLE
Schnittstelle Newsletter-Tools

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#82]
Schnittstellen zu Mailchimp (Wunschliste WeShapeTech):
- Alle neuen Mitglieder und Newsletter-Anmeldungen sollten direkt in der Mailchimp Liste aktualisiert werden und umgekehrt.
- Bei der Abmeldung vom Newsletter werden die Person als abgemeldet gekennzeichnet und in einer separaten Liste gespeichert.
- im CRM ist ersichtlich wer sich für den Newsletter angemeldet hat.

**Comment by RolandStuder** [comment]
Eine Mailchimp Integration urde umgesetzt, allerdings ist es ein manueller Aktion das abzugelichen. siehe https://hitobito.readthedocs.io/de/latest/mailing_lists_mailchimp_export.html Umgesetzt in 1.19
