### ISSUE TITLE
SBV: Aktivjahre beim Listenimport nicht berücksichtigen

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#821]
Beim manuellen Import von Mitgliedern über die Funktion "Liste importieren" soll das Attribut "Aktivjahre" nicht angezeigt/importiert werden. Dieser Wert wird aufgrund der Mitgliedschaft durch die Applikation berechnet.

**Comment by olibrian** [comment]
Feld wird in der Zwischenzeit nicht mehr angezeigt, da dieses Feld von der Applikation berechnet wird.
