### ISSUE TITLE
Lagerhierarchien

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#829]
Für das Bundeslager 2021 der PBS soll es in hitobito möglich sein, hierarchische Lagerstrukturen abzubilden. Konkret sollen die Einstellungen des Lagers nach unten kaskadiert werden können (aber von jedem Lager für sich überschrieben werden können) sowie Teilnehmerinformationen in beschränktem Masse nach oben weitergegeben werden. Es sind mehrere Hierarchiestufen möglich.

**Comment by carlobeltrame** [comment]
Wie speichern wir die Hierarchie-Struktur in der Datenbank? Mit parent-relation? Mit acts_as_nested_set? Wie in Gruppen mit beidem? Kann es in acts_as_nested_set überhaupt mehrere root nodes geben?

**Comment by kronn** [comment]
das nested-set, das wir bei den Gruppen verwenden unterstützt beides und kann (daher) auch mit mehreren root-nodes umgehen. Als erste näherung würde ich nur eine `parent_id` speichern. Wenn sich beim Auslesen dann ein nested-set mehr eignet, ist der migrationspfad mit `Event::Camp.rebuild!` sehr leicht.

**Comment by olibrian** [comment]
Können wir #https://github.com/hitobito/hitobito_pbs/pull/109 noch für den Release mergen?

**Comment by Michael-Schaer** [comment]
Hier noch die gewünschten Anpassungen nach Priorität:

1. Offene PR zum API mergen (insbesondere hitobito_pbs 96 und 127)

2. API Endpunkt für die Unterlager
-> @diegosteiner erstellt einen Pull Request, bitte mergen, sobald bereit

3. Unterlager nur im Status Erstellt abhängen/umhängen können
Bitte Komentar hier noch umsetzen: https://github.com/hitobito/hitobito/issues/848

4. Die Liste der Hauptlager kann unübersichtlich werden
Problem: Wenn ein vergangenes Lager den gleichen Titel wie ein aktuelles hat, ist unklar, welches gewählt werden soll.
Es sollen darum nur Hauptlager zur Auswahl stehen, die das Datum in der Zukunft haben (zusätzlich zum jetzigen Filter "Status Erstellt").

5. Übernahme der Datum-Felder
Vorschlag: Warnung, wenn das Datum des Unterlagers gar nicht mit dem Hauptlager überlappt

6. Bitte das Ticket hier auch noch anschauen, falls immer noch offen:
https://github.com/hitobito/hitobito/issues/855

**Comment by carlobeltrame** [comment]
Merci für die Auflistung, so ist es sicher einfacher, den Überblick zu behalten.

Zum Punkt 5, die Daten des Unterlagers werden beim Verbinden momentan nicht "gematcht", sonder einfach die Daten (Teile) des Hauptlagers hinzugefügt. So entstehen immer gültige Einträge (allenfalls Duplikate, welche aber jederzeit problemlos gelöscht werden können). Automatisch zu erkennen welcher Teil des Unterlagers zu welchem Teil des übergeordneten Lagers werden soll wäre sehr kompliziert wegen der vielen Edge-Cases die dabei entstehen können.

Die erläuterte Validierung wäre aber tatsächlich möglich. Falls diese wirklich gewünscht ist, könnte sie wohl nur während dem Verbinden überprüft werden, später nicht mehr, da sich theoretisch auch die Daten des Überlagers ändern können.

**Comment by Michael-Schaer** [comment]
Merci für die Rückmeldung! Punkt 5 und 6 können wir für den Moment streichen.

**Comment by carlobeltrame** [comment]
Die Punkte 1-4 und 6 sind erledigt, und 5 wird wie diskutiert momentan nicht umgesetzt.
