### ISSUE TITLE
Lagerhierarchien: übergeordnetes Lager erstellen

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#830]
Lager können als übergeordnetes Lager definiert werden, indem untergeordnete Lager zugelassen werden. Bei übergeordneten Lagern wird die Checkbox “untergeordnete Lager zulassen” ausgewählt.

![image3](https://user-images.githubusercontent.com/72198/64858529-f4c30180-d627-11e9-882e-5ae6beadec63.png)

- [x] Tabelle events erweitern: allow_sub_camps (bool)
- [x] Checkbox im View anzeigen
- [x] Checkbox verarbeiten
- [x] Checkbox kann nur geändert werden, wenn keine untergeordneten Lager angeschlossen sind.
- [x] Übersetzungen anpassen

See #829

**Comment by kronn** [comment]
Es ist im Rahmen dieses Issue aufgefallen, dass das Löschen von übergeordneten Lagern nicht klar definiert ist. Insbesondere: Was soll passieren, wenn ein übergeordnetes Lager gelöscht werden soll, obwohl es noch untergeordnete Lager hat? Was wäre hier das richtige Verhalten, @Michael-Schaer ?

**Comment by Michael-Schaer** [comment]
Guter Punkt!

Ich könnte mir vorstellen, dass man Lager gar nicht löschen kann, solange noch ein untergeordnetes Lager angeschlossen ist. 

Die Frage ist dann auch noch, wer das Unterlager wieder entfernen kann. Da würde ich erst mal nur die Leitung des übergeordneten Lagers berechtigen.

@diegosteiner Wie siehst du das?

**Comment by diegosteiner** [comment]
> Guter Punkt!
> 
> Ich könnte mir vorstellen, dass man Lager gar nicht löschen kann, solange noch ein untergeordnetes Lager angeschlossen ist.

Ich stimme dir zu und würde einfach mal ```:restrict_with_error``` machen. Die Berechtigung untergeordnete Lager zu löschen würde ich aber nicht erteilen.

**Comment by carlobeltrame** [comment]
Ich denke das untergeordnete Lager komplett zu löschen sollte sicher nicht in der Kompetenz der übergeordneten Lagerleitung sein. Aber wir könnten beiden Lagerleitungen (also allen die entweder das übergeordnete oder das untergeordnete Lager bearbeiten können) die Berechtigung erteilen, die Zuordnung zwischen den beiden Lagern zu beenden.

**Comment by Michael-Schaer** [comment]
@carlobeltrame Da sehe ich das Problem der Verbindlichkeit. Wenn sich ein untergeordnetes Lager zwei Wochen vor dem Event abmeldet, merkt es das Hauptlager vielleicht gar nicht oder verliert den Überblick, wie viele Personen mal angemeldet waren.

Wenn schön müsste das selbst-Abmelden z.B. nach der Anmeldefrist deaktiviert werden, oder?

**Comment by kronn** [comment]
:tada: `:restrict_with_error` war auch der Weg, den wir initial gewählt haben. Damit wird das Löschen des übergeordneten Lagers mit einer Fehlermeldung abgelehnt. Schön, dass wir da auf der gleichen Wellenlänge sind (und ich nichts daran ändern muss :wink: )

**Comment by carlobeltrame** [comment]
@Michael-Schaer Guter Punkt, aber das gleiche Problem haben wir ja mit spontanen Neu-Zuordnungen, nicht? Es ist bisher nicht spezifiziert dass ein Lager sich ab einem bestimmten Zeitpunkt nicht mehr einem anderen unterordnen darf.
Plus wenn wir da eine Frist einführen, wie ist es dann mit mehreren Hierarchiestufen? Z.B. BuLa setzt An-/Abmeldefrist 12 Monate vorher, eines der Unterlager aber nur 9 Monate vorher. Dann kann sich 10 Monate vor dem Lagerdatum noch eine Abteilung im Unterlager ein- oder austragen, was auch die Teilnehmerzahl etc. im BuLa ändert.

Falls solche Sperrfristen wirklich benötigt werden, muss man aus meiner Sicht folgende Dinge beachten:
* Die Unterlager-An-/Abmeldefrist muss nach unten kaskadiert werden und darf weiter unten in der Hierarchie höchstens verschärft (also verfrüht) werden. Das bedeutet auch, wenn das Überlager die Frist vorverschiebt, dass alle Fristen der untergeordneten Lager auf spätestens diese neue Frist vorverschoben werden müssen.
* Man könnte die Frist gleichsetzen mit der Anmeldefrist für Teilnehmende. Dann hätte man Gewissheit dass sich die Teilnehmerzahl ab dann nicht mehr von unten her ändern kann. Allerdings könnte es im allgemeinen Fall aus auch Sinn machen, zuerst die Lager-Hierarchie festzulegen und den Teilnehmern noch mehr Zeit für die Anmeldung zu geben. Dieser Prozess müsste mit Fachverantwortlichen geklärt werden (fürs BuLa und für normale z.B. abteilungsübergreifende Lager die die Funktion verwenden wollen).
* Falls die Unterlager-Anmeldungs-Frist separat von der Teilnehmer-Anmeldungs-Frist geführt werden soll:
  * Man könnte die Frist in einem weiteren Feld gleich bei der Checkbox "untergeordnete Lager zulassen" einfügen, etwa mit dem Namen "An- / Abmeldefrist für untergeordnete Lager"
  * Die Frist könnte auch (bei normalen abteilungsübergreifenden Lagern, nicht dem BuLa) unerwünscht sein, sollte also optional sein.

**Comment by kronn** [comment]
Deinen Ansatz, @carlobeltrame, finde ich gut. Aber ich schlage vor, das Problem zumindest vorerst nicht mit Programmierung zu lösen. Einerseits würde das den Rahmen etwas ändern, andererseits (und wichtiger) fände ich es in dem Fall besser, die Verwalter der teilnehmenden Lager über die Regeln zu informieren. Ich denke, dass jedem (der Lager organisiert) der Aufwand von solch grossen Lagern klar ist, daher sollte es nicht schwer sein, dieses Problem erstmal sozial zu lösen. Wenn man hitobito diese Regeln beibringen möchte, könnte man das auch nach der ersten Implementierung der Lagerhierarchien noch hinzufügen.

Erstmal würde ich daher das Löschen von Lagern verbieten, sobald man es einem anderen Lager zugeordnet hat.

**Comment by Michael-Schaer** [comment]
Eine weitere Lösung wäre noch, eine E-Mail-Benachrichtigung, wenn ein Lager sich an- oder abmeldet. Dazu eine Checkbox, um diese Meldungen zu toggeln, da nicht immer erwünscht. 

Ich bin aber einverstanden, dass wir das erstmal weglassen und und das Löschen verbieten.

**Comment by diegosteiner** [comment]
@carlobeltrame gut mitgedacht! Fristen wären aus meiner Sicht ein overkill. Wie wäre es, wenn man sich nur einem Lager anschliessen kann, das im Status "Erstellt" ist? So kann man das flexibel steuern und der Umsetzungsaufwand ist minimal.
