### ISSUE TITLE
Lagerhierarchien: übergeordnetes Lager ansehen

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#831]
Wenn die Checkbox “untergeordnete Lager zulassen” ausgewählt ist, erscheint der Reiter “Untergeordnete Lager”. Direkt untergeordnete sollen angezeigt werden bereits verlinkt angezeigt. Bei den untergeordneten Lagern wird **stattdessen** das übergeordnete Lager verlinkt

![image2](https://user-images.githubusercontent.com/72198/64858793-a5310580-d628-11e9-851d-682c61fbef8f.png)

- [x] Tab "untergeordnete Lager" anzeigen, wenn zugelassen
- [x] direkt angeschlossene Lager auf "Info"-Tab (übergeordnetes, wenn vorhanden, ansonsten die direkt untergeordneten)

See #829

**Comment by olibrian** [comment]
@diegosteiner Die Liste mit den untergeordneten Lager kann auf der Info Seite des Lager die Liste sehr lang werden. Vom GUI her wird es wohl ab < 8 Lager etwas unübersichtlich.
Welche untergeordneten Lager es gibt ist im #832 sichtbar und auch entsprechend filterbar.

Sollen wir dies wie geplant umsetzten? Oder nur das übergeordnete Lager anzeigen, falls eines vorhanden ist?

**Comment by diegosteiner** [comment]
Nein, lasst es ruhig weg. Es hat keinen eigentlichen Zweck dahinter.
