### ISSUE TITLE
Lagerhierarchien: Export der untergeordneten Lager

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#833]
Im Export werden alle bisherigen Lagerdaten exportiert (wie bisher), sowie
- Der eindeutige Link auf das Lager (z.B. “/groups/646/events/1117”)
- Voraussichtliche TN Anzahl
- Anzahl TN nach Rolle (analog Voraussichtliche TN Anzahl)
- Angaben des Lagerleiters und der Betreuungsperson
  - Name, Vorname, Pfadiname
  - Emailadressen, Telefonnummern
  - Adresse
  - Geburtsdatum
  - Geschlecht
  - AHV-Nr., J+S Nummer, usw.
- Rechnungsadresse (diese muss allenfalls als weiteres Feld bei der Lagerhierarchie
hinzugefügt werden

See #829, #832

**Comment by diegosteiner** [comment]
@lukaseisenring und ich haben gerade noch folgende Punkte diskutiert:

- Angaben des Lagerleiters und der Betreuungsperson müssen hier nicht nochmals vollständig implementiert werden müssen, sofern die Leitung des übergeordneten Lagers auch auf den Lagerleiter selbst zugreifen und dessen Informationen daraus ziehen kann. In diesem Fall würde die PBS-Personennummer hier genügen. 
- Rechnungsadresse ist ein mehrzeiliges Textfeld

@Michael-Schaer & @js4gh bitte approven

**Comment by Michael-Schaer** [comment]
Die Spezifikation ist da zwar nicht ganz deutlich, aber ich würde auch davon ausgehen, dass die Leitung und Betreuung des untergeordneten Lagers für die Leiter des übergeortneten Lager sichtbar sind. 

Z.B. hier: https://github.com/hitobito/hitobito/issues/832#issue-493306992

Also wenn wir die Lagerleitung und Betreuungsperson noch im Issue 832 erwähnen können, bin ich einverstanden, dass wir das hier beim Export weglassen können. @kronn Was denkst du?

**Comment by ThomasEllenberger** [comment]
@Michael-Schaer dieses Issue wurde wohl im Hinblick auf das Bu-La erstellt.
Ist dieses für euch noch relevant, oder können wir dieses schliessen?

**Comment by Michael-Schaer** [comment]
Ja, kann geschlossen werden.
