### ISSUE TITLE
Lagerhierarchien: untergeordnetes Lager erstellen

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#834]
Bei Erstellen/Bearbeiten eines Lagers erscheint ein neuer Abschnitt “Lagerhierarchie”. Der Knopf “an übergeordnetes Lager anschliessen” führt auf einen Wizard:

1. ein übergeordnetes Lager aussuchen. Es gibt eine Liste von Lagern auf den übergeordneten Ebenen welche “untergeordnete Lager zulassen” eingeschaltet haben sowie eine Suchmaske, wo alle Lager die “untergeordnete Lager zulassen” eingeschaltet haben angezeigt werden können
2. alle Lagerinformationen werden mit den Daten aus dem übergeordneten Lager vorausgefüllt. Die Daten können geändert/überschrieben werden (aber nicht unbedingt im Wizard).
  - Durchführungsdaten werden mit dem Erstellen kopiert
  - Anmeldungs- und Administrationsangaben werden mit dem Erstellen kopiert
und gemäss Abschnitt “Untergeordnetes Lager - Anmeldeangaben”
angezeigt
  - Voraussichtliche TN Anzahl wird immer leer gelassen
  - Das ganze Tab Betreuung wird leer gelassen
3. die weiterzugebenden Kontaktangaben gemäss Abschnitt “Untergeordnetes Lager - Kontaktangaben” angezeigen

Die Funktion “Lager einreichen” muss weiterhin gewährleistet sein.

![image4](https://user-images.githubusercontent.com/72198/64861966-a74b9200-d631-11e9-9310-b3a8601ef311.png)

- [x] übergeordnetes Lager auswählen
- [x] nach übergeordnetem Lager suchen
- [x] Daten kopieren
- [x] Test für "camp_submitted_at" erweitern
- [x] Es sollen nur Lager auswählbar sein, die "Erstellt" sind (siehe #830)
- [x] Name des untergeordneten Camps automatisch generieren

See #829

**Comment by carlobeltrame** [comment]
@Michael-Schaer @diegosteiner Welche der Lagerinformationen sollen standardmässig vom übergeordneten Lager übernommen werden? Grundsätzlich steht in der Spezifikation "alle Lagerinformationen" der ersten drei Tabs, aber bei den folgenden bin ich mir nicht sicher ob das wirklich Sinn macht:
* Tab Allgemein
  * Name
  * Lagerstatus
  * Beschreibung
  * Kosten
  * J+S-Rahmen
  * Sicherheitsbereiche
* Tab Anmeldung
  * Maximale Teilnehmerzahl

**Comment by Michael-Schaer** [comment]
Hier mein Vorschlag (die mit Kreuz sollen übernommen werden):

Tab Allgemein
- [ ] Name (Für die Suche ist es recht blöd, wenn alle BuLa-Lager gleich heissen)
- [ ] Lagerstatus (Der ändert sich ja sowieso wieder)
- [ ] Beschreibung 
- [x] Kosten (Kann mir vorstellen, dass ein Hauptlager die Kosten fix definieren will)
- [x] J+S-Rahmen
- [x] Sicherheitsbereiche

Tab Anmeldung
- [ ] Maximale Teilnehmerzahl (Hat beim übergeordneten Lager eigentlich immer einen höheren Wert als beim untergeordneten, oder?)

**Comment by diegosteiner** [comment]
Schliesse mich in den meisten Punkten an. Allerdings:

- [x] Name, aber in einer generierten Form: "<Name übergeordnet>: <Name der aktuellen Gruppe>". Ich denke gute Defaults sind wichtig, das passt sonst niemand an.
- [x] Beschreibung: Hier könnte man als übergeordnetes etwas mitgeben für die untergeordneten Lager (Anweisungen, Bedingungen, etc.) sonst ist das gar nicht möglich.

**Comment by carlobeltrame** [comment]
Bei der Beschreibung stimme ich dir zu, aber beim Namen bin ich nicht so sicher.
Der Lagername ist das einzige Pflichtfeld, das man nach der Variante von Michael noch von Hand ausfüllen muss, alle anderen Pflichtfelder können vom übergeordneten Lager übernommen werden. Wenn wir da automatisch "BuLa: " reinschreiben, dann erleichtern wir die Speicherung von ganz vielen Lagern mit genau demselben unsinnigen Namen "BuLa: ". Wie du sagst, das passt niemand mehr an wenn man nicht dazu aufgefordert wird, und wie Michael sagt, ist es recht blöd, wenn alle BuLa-Lager gleich heissen.

Anders formuliert: Wenn ich mir überlege, ob ein Feld vom übergeordneten Lager übernommen werden soll, frage ich mich: Soll das Feld in keinem Fall den gleichen Wert wie im übergeordneten Lager annehmen? Bsp. Maximale Teilnehmeranzahl: Die Zahl vom Hauptlager ist wohl nie korrekt für die Unterlager, also nicht übernehmen. Bsp. Kosten: Es kann durchaus sein dass die Kosten vom Hauptlager auch für die Unterlager gelten (oder auch nicht), also übernehmen. Bsp. Lagername: Der Lagername des Unterlagers sollte eigentlich nie gleich sein wie der des Hauptlagers.

**Comment by lukaseisenring** [comment]
Bezüglich des Lagernamens würde ich vorschlagen eine Kombination aus dem Originalnamen und dem Namen des Layers zu verwenden. Z.B.:

Abteilungsname: BuLa/CaFé 2021 Wolfsstufe

Dies gäbe im übergeordneten Lager dann eine schöne Auflistung.

**Comment by carlobeltrame** [comment]
Merci für den Input! Im übergeordneten Lager auf dem neuen Tab ist die Liste von Unterlagern aber ja so oder so nach Abteilung (Gruppe) sortierbar (#832)..? Und auf dem Info-Tab (#831) könnte man diesen zusammengezogenen Namen ja problemlos so rendern, wenn man nur den separaten reinen Lagernamen in der Datenbank gespeichert hat. Mir widerstrebt es einfach, den Namen des übergeordneten Lagers in der Datenbank zu duplizieren, zumal vermutlich einzelne Lagerleiter trotzdem den Lagernamen anpassen werden und die schöne Auflistung dann nicht mehr aufgeht.

Bei mehreren Hierarchiestufen wird das zudem auch schnell sehr schwer lesbar:
```
BuLa/CaFé 2021
Pfadi Kanton Bern: BuLa/CaFé 2021 Unterlager 2
Schekka: Pfadi Kanton Bern: BuLa/CaFé 2021 Unterlager 2 Abteilungslager
Mogli: Schekka: Pfadi Kanton Bern: BuLa/CaFé 2021 Unterlager 2 Abteilungslager Wolfsstufe
```
Wenn man die dritte Zeile jemals auf `Schekka: Unterlager 2 Abteilungslager` abkürzen will, muss "Unterlager 2" irgendwo einzeln in der Datenbank gespeichert sein, ohne die Anhängsel "Pfadi Kanton Bern: BuLa/CaFé 2021 Unterlager 2".

Wenn ich aber der einzige bin der das so sieht, müsstet ihr euch auf eine einzige Lösung einigen die ich implementieren kann.

**Comment by diegosteiner** [comment]
Da hats bei mir wohl einen Teil verschluckt. Ich hatte auch gemeint:

`Name, aber in einer generierten Form: "<Name übergeordnet>: <Name der aktuellen Gruppe>".`

Ich sehe aber auch ein dass es bei vielen hierarchiestufen unübersichtlich werden kann. Die Abteilung scheint mir fast die zentralste Information zu sein (bzw. der Kantonalverband falls ausserhalb einer Abteilung)

**Comment by Michael-Schaer** [comment]
Ist die Übersetzung des übergeordneten Lagers "Supercamp" gewollt? Oder ist da noch kein Text drin?
![Text Supercamp](https://user-images.githubusercontent.com/1799621/69972648-4a6dc280-1522-11ea-86e2-583fe91059f2.jpg)

z.B. hier:
https://pbs.puzzle.ch/de/groups/69/events/1000/edit

**Comment by carlobeltrame** [comment]
Die gewünschten Änderungen sind implementiert und sind ab morgen auf Integration testbar.
