### ISSUE TITLE
Testrückmeldungen insieme 

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#837]
Wir haben die Änderungen im insieme desk getestet und einige Rückmeldungen. Grundsätzlich sieht es gut aus, wie Lösung, wie Fachkonzept und Leistungskategorie verknüpft sind (Fehlermeldung, wenn nicht kongruent), finde ich sehr gut. Folgende Punkte sind noch nicht ganz fertig umgesetzt:

 

Kurse

-          Kurs erfassen / bearbeiten

o   Statt „Fachkonzept“ à „Kursinhalt“

-          Kursabschluss „Treffpunkt“

o   „BetreuerInnen“: Nur ein Feld „Betreuungspersonen“, keine Aufteilung in verschiedene Gruppen

o   „Kursinhalt“ fehlt à Ist es möglich, hier das Drop-Down-Menü von „Kurs bearbeiten“ einzufügen, so dass der Kursinhalt auch hier bearbeitet werden kann?

o   Auswertungen: Die „Anzahl tatsächliche LE“ wird noch wie bei den Kursen berechnet (TN x Zeit). Neue Berechnung: Betreuungsstunden, also Anzahl Betreuungspersonen x Zeit.

-          Kursabschluss Semesterkurs / Tageskurs / Blockkurs

o   „Kursinhalt“ fehlt à Ist es möglich, hier das Drop-Down-Menü von „Kurs bearbeiten“ einzufügen, so dass der Kursinhalt auch hier bearbeitet werden kann?

 

Sammelkurse

-          Kurs erfassen / bearbeiten

o   Statt „Fachkonzept“ à „Kursinhalt“

-          Kursabschluss „Treffpunkt“

o   „Kursdauer in Stunden“: Hinweis „inkl. 1h Vor- und Nachbereitung pro Durchführung“ fehlt (wie er bei den Kursen drin ist)

o   „BetreuerInnen“: Nur ein Feld „Betreuungspersonen“, keine Aufteilung in verschiedene Gruppen

o   „Kursinhalt“ fehlt à Ist es möglich, hier das Drop-Down-Menü von „Kurs bearbeiten“ einzufügen, so dass der Kursinhalt auch hier bearbeitet werden kann?

o   Auswertungen: Die „Anzahl tatsächliche LE“ wird noch wie bei den Kursen berechnet (TN x Zeit). Neue Berechnung: Betreuungsstunden, also Anzahl Betreuungspersonen x Zeit.

-          Kursabschluss Semesterkurs / Tageskurs / Blockkurs

o   „Kursinhalt“ fehlt à Ist es möglich, hier das Drop-Down-Menü von „Kurs bearbeiten“ einzufügen, so dass der Kursinhalt auch hier bearbeitet werden kann?

 

Umlage Gemeinkosten

-          Hier gibt es bereits ein Feld für Treffpunkte. Ist dies aus technischen / rechnerischen Gründen nötig? Es könnte unsere User für das Reporting 2019 verwirren. Besser wäre es, wenn dieses Feld noch nicht angezeigt wird und wir es erst mit den Änderungen im Sommer 2020 einfügen. Wäre das möglich?

 

Französisch

-          Catégorie de prestations

o   Treffpunkt à Lieux d’accueil

-          Fachkonzept (neu: «Kursinhalt») à Contenu du cours

o   Freizeit Kinder & Jugendliche à loisirs enfants et jeunes

o   Freizeit Erwachsene & altersdurchmischt à loisirs adultes et personnes d'âge mixte

o   Sport Kinder & Jugendliche à sports enfants et jeunes

o   Sport Erwachsene & altersdurchmischt à  sports adultes et personnes d'âge mixte

o   Förderung der Autonomie / Bildung à aide à l’entraide / éducation

o   Treffpunkt à Lieux d’accueil

 

Bis wann könnt ihr diese Sachen einarbeiten? Merci für dein Feedback. Falls etwas unklar ist, können wir gerne telefonieren.

12.9.
Austausch W+S bs, insieme, 

15.9.
1h Vorb Woche

16.9
0.5 GLP Vorbereitungsaufgaben WS
CH Open PM

Wir haben die Änderungen im insieme desk getestet und einige Rückmeldungen. Grundsätzlich sieht es gut aus, wie Lösung, wie Fachkonzept und Leistungskategorie verknüpft sind (Fehlermeldung, wenn nicht kongruent), finde ich sehr gut. Folgende Punkte sind noch nicht ganz fertig umgesetzt:

 

Kurse

- Kurs erfassen / bearbeiten
	Statt „Fachkonzept“ à „Kursinhalt“

- Kursabschluss „Treffpunkt“
	„BetreuerInnen“: Nur ein Feld „Betreuungspersonen“, keine Aufteilung in verschiedene Gruppen

	„Kursinhalt“ fehlt à Ist es möglich, hier das Drop-Down-Menü von „Kurs bearbeiten“ einzufügen, so dass der Kursinhalt auch hier bearbeitet werden kann?

	Auswertungen: Die „Anzahl tatsächliche LE“ wird noch wie bei den Kursen berechnet (TN x Zeit). Neue Berechnung: Betreuungsstunden, also Anzahl Betreuungspersonen x Zeit.

- Kursabschluss Semesterkurs / Tageskurs / Blockkurs

	„Kursinhalt“ fehlt à Ist es möglich, hier das Drop-Down-Menü von „Kurs bearbeiten“ einzufügen, so dass der Kursinhalt auch hier bearbeitet werden kann?

 

Sammelkurse

- Kurs erfassen / bearbeiten
	Statt „Fachkonzept“ à „Kursinhalt“

- Kursabschluss „Treffpunkt“
	„Kursdauer in Stunden“: Hinweis „inkl. 1h Vor- und Nachbereitung pro Durchführung“ fehlt (wie er bei den Kursen drin ist)

	„BetreuerInnen“: Nur ein Feld „Betreuungspersonen“, keine Aufteilung in verschiedene Gruppen

	„Kursinhalt“ fehlt à Ist es möglich, hier das Drop-Down-Menü von „Kurs bearbeiten“ einzufügen, so dass der Kursinhalt auch hier bearbeitet werden kann?

	Auswertungen: Die „Anzahl tatsächliche LE“ wird noch wie bei den Kursen berechnet (TN x Zeit). Neue Berechnung: Betreuungsstunden, also Anzahl Betreuungspersonen x Zeit.

- Kursabschluss Semesterkurs / Tageskurs / Blockkurs

	„Kursinhalt“ fehlt à Ist es möglich, hier das Drop-Down-Menü von „Kurs bearbeiten“ einzufügen, so dass der Kursinhalt auch hier bearbeitet werden kann?

 

Umlage Gemeinkosten

- Hier gibt es bereits ein Feld für Treffpunkte. Ist dies aus technischen / rechnerischen Gründen nötig? Es könnte unsere User für das Reporting 2019 verwirren. Besser wäre es, wenn dieses Feld noch nicht angezeigt wird und wir es erst mit den Änderungen im Sommer 2020 einfügen. Wäre das möglich?

 

Französisch

- Catégorie de prestations
	Treffpunkt à Lieux d’accueil

- Fachkonzept (neu: «Kursinhalt») à Contenu du cours
	Freizeit Kinder & Jugendliche à loisirs enfants et jeunes
	Freizeit Erwachsene & altersdurchmischt à loisirs adultes et personnes d'âge mixte
	Sport Kinder & Jugendliche à sports enfants et jeunes
	Sport Erwachsene & altersdurchmischt à  sports adultes et personnes d'âge mixte
	Förderung der Autonomie / Bildung à aide à l’entraide / éducation
	Treffpunkt à Lieux d’accueil

 

Bis wann könnt ihr diese Sachen einarbeiten? Merci für dein Feedback. Falls etwas unklar ist, können wir gerne telefonieren.

**Comment by kronn** [comment]
Zusammengefasste To-Dos:

- [ ] Übersetzung anpassen: Fachkonzept -> Kursinhalt
- [ ] Kurse: Treffpunkt - Kursabschluss
  - [ ] Betreuungspersonen und -schlüssel
  - [ ] Kursinhalt bearbeitbar durch Dropdown
  - [ ] Auswertung: Betreuungsstunden = Anzahl Betreuungspersonen x Zeit
- [ ] Sammelkurse und Kurse: Semesterkurs / Tageskurs / Blockkurs - Kursabschluss
  - [ ] Kursinhalt bearbeitbar durch Dropdown
- [ ] Sammelkurse: Treffpunkt - Kursabschluss
  - [ ] Hinweis bei Kursdauer fehlt (wie er bei den Kursen drin ist)
- [ ] Umlage Gemeinkosten
  - [ ] Treffpunkte erst ab Sommer 2020 anzeigen
- [ ] Französiche Übersetzungen einpflegen

**Comment by KunoKunz** [comment]
Aktuell sind immer noch ein paar Punkte offen:

Kurse:
- Kursabschluss „Treffpunkt“
o   Betreuungsschlüssel: Die Berechnung ist falsch
o   Auswertungen: Die „Anzahl tatsächliche LE“ wird noch wie bei den Kursen berechnet (TN x Zeit). Neue Berechnung: Betreuungsstunden, also Anzahl Betreuungspersonen x Zeit.

Sammelkurse
- Kurs erfassen / bearbeiten
o   Statt „Fachkonzept“ à „Kursinhalt“
-          Kursabschluss „Treffpunkt“
o   Betreuungsschlüssel: Die Berechnung ist falsch
o   Auswertungen: Die „Anzahl tatsächliche LE“ wird noch wie bei den Kursen berechnet (TN x Zeit). Neue Berechnung: Betreuungsstunden, also Anzahl Betreuungspersonen x Zeit.
