### ISSUE TITLE
Person endgültig löschen (Datenschutz)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#84]
Endgültiges Löschen einer Person, um dem Datenschutzforderung nach einer kompletten Löschung der eigenen Daten gerecht werden zu können.

Wichtige Aspekte:
- Sollen Logs auch korrigiert werde? (X hat Y geändert).
- Wer hat die Berechtigung dazu?
- Statistiken müssen erhalten bleiben
- Nach dem Löschen müssen allfällige Statistiken (Anzahl Kursteilnehmer, Bestandesmeldung, ...) trotzdem erhalten bleiben. Ggf. Person anonymisiert weiter bestehen lassen.
- Was passiert mit allen assozierten Objekten, hier als Referenz die assozierten Modelle:
  
      has_many :roles, inverse_of: :person
      has_many :groups, through: :roles
    
      has_many :event_participations, class_name: 'Event::Participation',
                                      dependent: :destroy,
                                      inverse_of: :person
      has_many :event_applications, class_name: 'Event::Application',
                                    through: :event_participations,
                                    source: :application
      has_many :event_roles, class_name: 'Event::Role',
                             through: :event_participations,
                             source: :roles
      has_many :events, through: :event_participations
    
      has_many :qualifications, dependent: :destroy
    
      has_many :subscriptions, as: :subscriber, dependent: :destroy
    
      has_many :relations_to_tails, class_name: 'PeopleRelation',
                                    dependent: :destroy,
                                    foreign_key: :head_id
    
      has_many :add_requests, dependent: :destroy
    
      has_many :notes, class_name: 'Note',
                       dependent: :destroy
    
      has_many :authored_notes, class_name: 'Note',
                                foreign_key: 'author_id',
                                dependent: :destroy
    
      has_many :tags, as: :taggable, dependent: :destroy

**Comment by RolandStuder** [comment]
Lösungvorschlag von 

Lösungsvorschlag:

Personen ohne aktive Rolle sind bei der Gruppe, wo Sie zuletzt aktiv waren, im Menüpunkt "Gelöscht" sichtbar. Rechte für die Sichtbarkeit gemäss der letzten aktiven Rolle.
Will jemand Zugriff auf eine "gelöschte Person" bekommen (hinzufügen in Gruppe, Abo, ...), so gelten die gleichen Freigabe-Prinzipien wie bei Personen mit aktiven Rollen. Die zuletzt gelöschte Rolle ist für die (allfällige) Freigabe relevant.
Im Menüpunkt "Gelöscht" existiert die Möglichkeit, die Daten "endgültig" zu löschen. Dies geht nur sofort, falls die Person über keine "speziellen" Rechte besass und dadurch Daten modifizieren konnte . Andernfalls besteht eine Sperrfrist von 12 (?) Monaten (Sicherstellung der #Nachvollziehbarkeit).
Nach dem Löschen müssen allfällige Statistiken (Anzahl Kursteilnehmer, Bestandesmeldung, ...) trotzdem erhalten bleiben. Ggf. Person anonymisiert weiter bestehen lassen.

**Comment by RolandStuder** [comment]
Diksussionspunkte:

- Ist es die richtige Lösung, dass das immer über die Gruppe der letzten aktiven Rolle läuft. Ich nehme an, in der Regel würde eine endgültige Löschung eher passieren wenn jemand das explizit verlangt, z. B. beim Kanton, wie findet dann der Adressverwalter diese Person überhaupt
- Sollen auch Adressverwalter von lokalen Gruppen die Möglichkeit haben Personen endgültig zu löschen. Ist das nicht eher eine Aufgabe der Adminstratoren des gesamten Organisation? Dann wäre die Lösung möglich dass Personen mit :admin die Person über die Suche finden könnten.
- Sperrfrist steht im Widerspruch zur Anforderung, dass man die Daten sollte löschen können, wenn jemand dies verlangt.

Frage ist auch, wieviel Gewicht wir dem geben. Wie elegant muss die Lösung sein, angesichts der Sache, das dies wohl eher selten vorkommt? Haben wir dazu daten?

**Comment by nchiapol** [comment]
So wie ich den EDÖB lese, müssen wir die Daten nicht vollständig löschen sondern nur verhältnismässig: 

https://www.edoeb.admin.ch/datenschutz/00683/01173/index.html?lang=de

Um Probleme mit der Konsistenz der Datenbank zu vermeiden, würde ich wohl alle Felder ausser Namen und Vornamen löschen, die Person dann aber bestehen lassen. Das Log sollte dann ersetzt werden durch "Details auf Wunsch gelöscht" oder etwas in der Art.
Ich glaube als Organisation haben wir ein berechtigtes Interesse, an einer nachvollziehbaren Datenbank und der Geschichte über unsere Mitglieder.

**Comment by RolandStuder** [comment]
Es gibt hier verschiedene Varianten:

Das eine betrifft den Löschmodus:

* endgültig, echtes Löschen
* erhaltendes löschen mit Anonymisierung

@nchiapol Was ist die Idee hinter Namen / Vornamen erhalten. Wenn für den Verband etwas interessant ist, das sind es die Daten hinter der Person wie Anmeldungen und frühere Rollen. Eine Name / Vorname bringt nicht viel.

Das andere die Berechtigung:

* Wer darf löschen? Nur explizit berechtigte Personen (:admin).
* Oder jede Person, vorrausgesetzt, sie hat Zugriff auf die entsprechenden Rollen

Es geht hier auch ein bisschen um die Grundsatzfrage, wer die Hohheit über die Daten hat. In Gesprächen mit AL beim Bezirk Sense Seeland habe ich den Eindruck erhalten, dass der Wunsch nach Kontrolle über die Daten sehr gross ist und dass die Akzeptanz vielleicht tiefer ist, als ich gedacht hätte.

## Löschmodus

### Endgültiges echtes Löschen nur durch Admins

* Endgültiges Löschen nur durch Personen mit :admin Berechtigung
* echtes Löschen ohne Erhaltung der Daten
* keine Restriktion auf Vorbedingungen (jede Person kann unabhängig der bestehenden Rollen gelöscht werden.)
* Ist technisch auch am einfachsten.
* Wichtig ist, dass man auf die Person überhaupt eine Ansicht hat. Was bei Personen ohne Rollen ja nicht der Fall ist.
* Dort wo wichtig (z. B. Bestandesmeldung) werden die Daten sowieso historisiert

### Anonymisierung der Person

* Setzen auf einen speziellen Namen "Gelöscht" (kann nur mit Aufwand dann auch übersetzt werden).
* Setzen eines gelöscht Flags (die Person soll ja dann nicht bei Suchen usw. berücksichtigt werden) -> bedeutet zusätzlichen Aufwand
* Rollen müssen alle beendet (Enddatum Löschzeitpunkt) werden.
* Dies könnte etwas aufwändiger, da dann das gelöscht Flag als Logik an einigen Orten berücksichtigt werden muss, wobei mir im Moment nur die Personensuche zum hinzufügen in den Sinn kommt.

## Berechtigung

### Nur durch Admins

* Könnte einfach in den Berechtigungen abgebildet werden.
* Dies ist eine Verbandsspezifische Sicht. Den Abteilungen hilft das direkt wenig, wenn sie dafür der Dachverbandsgeschäftsstelle schreiben müssen, wenn sie ein Kind löschen sollen. Das dann eigentlich für sie auch gar nicht sichtbar ist wegen Restriktionen :not_visible_from_above.
* Scheint mir nach längerem Überlegen eine etwas kurzsichtige Kösung.

### Durch beliebe Personen mit Schreibberechtigung 

Tricky ist hier, dass wir beachten müssen, dass Anmeldungen an Anlässen auch via die Person gehen, das muss berücksichtigt werden.

Vorschlag:

* Ich kann eine Person löschen, wenn ich die Berechtigung habe, alle Rollen zu löschen/editieren inkl. vergangener Rollen.
* Wir müssen dabei auch Eventteilnahmen berücksichtigen. Hier würde ich es nicht abhängig machen von der Berechtigung Teilnahmen zu löschen, sonder einfach ob ich auf der entsprechenden Gruppe Schreibberechtigunge habe.
* Bei der Löschung erhalte ich die Auswahl, ob ich alle aktuellen Rollen löschen möchte oder ob ich die Person komplett aus der DB entfernen möchte.

Einfacherer, aber weniger robuster Vorschlag:

* Ich darf Personen löschen, wenn ich die aktuellen Rollen oder die letzte aktive Rolle löschen darf.

Erweiterungsüberlegungen:

* Für Fälle, wo ich zu wenig Berechtigung habe, könnten wir ein Anfrageverfahren auslösen. Damit die Person, mit zu wenig Berechtigungen den Löschprozess trotzdem beantragen kann.

## Warnungen/Fragen:

* Ist bei Insieme die Übernahme von Kursdaten und Teilnehmer auch historisiert?
* Beachte #64

**Comment by RolandStuder** [comment]
Und dann noch die Frage: Was machen wir, wenn die Person ein Login hat. Auch im Hinblick auf einen Account der für Anmeldungen verwendet werden kann.

**Comment by nchiapol** [comment]
@RolandStuder: Sorry, das war nicht klar genug ausgedrückt. Ich würde alle Attribute der Person ausser Vorname + Name löschen. Beziehungen wie Anmeldungen und frühere Rollen würde ich aber erhalten. Wie du richtig schreibst sind das die relevanten Daten, die auch aus historischer Perspektive von Interesse sind. 
Das Log müsste aber mindestens zum Teil verschwinden, denn es nützt nichts, wenn wir die Adresse löschen, diese aber noch im Log seht.

Entsprechend wäre mein Löschmodus noch etwas schwächer als dein Anonymisieren, bis auf den Erhalt des Namens aber weitgehend identisch.

**Comment by RolandStuder** [comment]
@nchiapol Wir setzen das vorläufig wie folgt um: #123 Ich verstehe an deinem Vorschlag noch nicht, was wir damit wirklich erreichen. In welchem Fall würdest du dies tun wollen?

**Comment by nchiapol** [comment]
@RolandStuder: #123 sieht soweit sinnvoll aus. Ich kann auch damit Leben. Wir werden diese Löschung wohl nur sehr restriktiv anwenden.

Aus meiner Sicht erreicht mein Vorschlag die begründeten Interessen der betroffenen Person:
  * die weitere Datenbearbeitung wird unmöglich
  * Personendaten können nicht mehr an Dritte bekannt gegeben werden
  * wir vernichten jene Personendaten, die veralten könnten

Gleichzeitig gewährleisten er aber auch die "Erinnerung" unserer Organisationen. Wie im ersten Post erwähnt, halte ich das für ein berechtigtes Interesse unserer Verbände das einer totalen Löschung entgegensteht. 

Für die Dinge, die wir in den Atributen zu einer Person speichern, überwiegt aus meiner Sicht das Interesse der Person an ihren Daten. Für die "Meta-Daten" wie Gruppenzugehörigkeiten oder Kursbesuche gewichte ich hingegen das Interesse des Verbands höher. (Schwierig wird es dann bei den Details wie dem Vorgehen bei nicht bestandenen J+S-Kursen).

**Comment by RolandStuder** [comment]
Ich schliesse dieses Issue zugunsten von #123 und https://github.com/hitobito/hitobito/issues/139
