### ISSUE TITLE
NoMethodError in DashboardController#index bei Neuinstallation

### ISSUE THREAD

**Issue by electronix** [hitobito/hitobito#844]
Ich habe eine neue Installation des Hitobito aufgesetzt (mittels https://github.com/fujexo/hitobito-docker) und das Passwort des Hauptbenutzers zurückgesetzt. Soweit alles super.

Bei nächsten Refresh erhalte ich die Fehlermeldung 'NoMethodError in DashboardController#index'  (siehe Screenshot).
<img width="499" alt="hitobito_noMethodError" src="https://user-images.githubusercontent.com/2134864/65795110-d00f7380-e169-11e9-9773-9828837eb4b9.PNG">

Was mache ich falsch? Danke und Gruss

**Comment by carlobeltrame** [comment]
`Group.root`ist `nil`, das passiert wenn die Datenbank nicht geseedet wird. Probiers mal mit `bundle exec rake db:seed wagon:seed` in startup.sh, oder benutze stattdessen den etwas aktuelleren Docker-Setup von https://github.com/nxt-engineering/hitobito-docker

**Comment by electronix** [comment]
Danke Carlo für die rasche Rückmeldung. Beim Docker-Setup von nxt-engineering bekomme ich den genau gleichen Fehler :-( Werde es aber bei Gelegenheit noch einmal probieren.

Habe unterdessen eine Installation ohne Docker auf einem Debian 9 machen können. Vielleicht widme ich mich sogar noch dem Schreiben von einem how-to.

**Comment by carlobeltrame** [comment]
@btemperli @electronix Ich konnte das Problem mit nxt-engineering/hitobito-docker reproduzieren, es liegt daran dass das Wagonfile während dem Seeding fehlt. Daher werden nie die Wagon-spezifischen Seeds ausgeführt, und somit fehlt die Root-Gruppe nach dem ersten Login (ein erster User hingegen wird auch schon ohne Wagons im den Core Seeds erstellt).

Das Problem wurde in https://github.com/nxt-engineering/hitobito-docker/pull/2 schon letzte Woche reported, und in https://github.com/nxt-engineering/hitobito-docker/pull/5 habe ich den Maintainers jetzt noch eine weitere Lösung dafür vorgeschlagen. Bis diese den Fix mergen könnt ihr es mit meinem Fork https://github.com/carlobeltrame/hitobito-docker versuchen.

Löst das euer Problem?

**Comment by electronix** [comment]
Danke @carlobeltrame für Deinen Einsatz.

Ich habe Deinen Fork geklont und das docker-compose aufgerufen. Im Log sehe ich die neue Meldung `Creating Wagonfile from defaults because it doesn't exist yet`, allerdings sehe ich beim ersten Login (nach dem Ändern des Passworts) immer noch den gleichen Fehler.

Daher funktioniert der Fix bei mir noch nicht richtig. Werde bei Gelegenheit auch mal reinschauen.

**Comment by carlobeltrame** [comment]
Kein Problem, ich bin auch interessiert an einem "it just works" Setup.

Ich habe bemerkt dass der rake task `wagon:file` ein seltsames Wagonfile erstellt das ein vendor Verzeichnis referenziert. Habe das in meinem PR und Fork ersetzt durch einfaches Kopieren des Wagonfile.ci.

Zum Testen habe ich bei mir Docker aufgeräumt und folgende Befehle ausgeführt und es klappt:
```
git clone git@github.com:carlobeltrame/hitobito-docker.git
cd hitobito-docker/
git clone git@github.com:hitobito/hitobito.git
git clone git@github.com:hitobito/hitobito_youth.git
git clone git@github.com:hitobito/hitobito_cevi.git
docker-compose up app
# Sobald "Listening on 0.0.0.0:3000" angezeigt wird, in einer anderen Konsole:
echo 'p=Person.first; p.update(password: "password"); "You can now login as #{p.email} with the password \"password\""' | docker-compose run --rm -T app rails c
echo "http://$(docker-compose port app 3000)"
```

**Comment by btemperli** [comment]
Hi @carlobeltrame 

Danke für die Anpassungen. Mit reseed etc hat es bei mir nun geklappt und funktioniert! 👍 

So stell ich mir das vor 😄

**Comment by electronix** [comment]
@carlobeltrame Super. Läuft auch bei mir perfekt durch. Hast ein 🍺 verdient!!

Jetzt gibts eine super einfache Lösung für alle, die Hitobito ausprobieren wollen. Danke!
