### ISSUE TITLE
Personenimport mit Korrespondenzsprache schlägt fehl

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#845]
Information von der DSJ:

Beim Import von Adressen aus einem Excel erhalten wir immer eine Fehlermeldung bezüglich der Sprache (siehe Datei im Anhang). Wir haben auch schon versucht, die Sprache nur mit DE oder D auszufüllen, erhalten aber immer dieselbe Fehlermeldung:

![import-schlaegt-fehl](https://user-images.githubusercontent.com/72198/65892645-f110d800-e3a6-11e9-82f1-308c5eb06527.jpg)

**Comment by carlobeltrame** [comment]
Klingt als wären die Spalten verschoben, also als würden die Daten einer anderen Spalte in die Sprache-Spalte geladen. Das könnte mit Kommas in vorangehenden Feldern im CSV zu tun haben (z.B. in Name etc.). Gibt es hier ein anonymisiertes Beispiel-CSV um es zu reproduzieren?

**Comment by kronn** [comment]
Ganz vergessen, das hier zu kommentieren: Die Ursache ist, dass das Sprachkürzel in Kleinbuchstaben vergeben werden muss. Also: "DE" geht nicht, "de" geht schon. Lustigerweise ist damit "deutsch" gültig, weil es mit den richtigen Buchstaben anfängt. Dieses Verhalten ist jetzt dokumentiert und auch schon auf der dsj-integration deployed.
