### ISSUE TITLE
Export der Untergruppen funktioniert nicht

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#846]
Information der DSJ

Der Export von Untergruppen funktioniert überhaupt nicht mehr. Es erscheint immer nur die Meldung "Export wird im Hintergrund gestartet und nach der Fertigstellung heruntergeladen". Der Export wird aber nicht fertiggestellt.

**Comment by olibrian** [comment]
Nicht nachvollziehbar. Export funktioniert.
