### ISSUE TITLE
Lager löschen/absagen

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#848]
Wenn ein Lager nicht durchgeführt wird oder gelöscht wird, ist aktuell nicht ganz eindeutig, was noch passieren sollte. Zu einem müssten Anmeldungen beachtet und behandelt werden (siehe #847), zum anderen ist das Verhalten bei Lagerhierarchien (siehe #829, #830) nicht unproblematisch. Eine Diskussion ist in https://github.com/hitobito/hitobito/issues/830#issuecomment-537944101 vorhanden, die man hier vielleicht etwas allgemeiner und losgelöster weiterführen kann.

@Michael-Schaer @diegosteiner @carlobeltrame

**Comment by Michael-Schaer** [comment]
Nur wenn das Hauptlager im Status “Erstellt” ist, sollen die Unterlager sich frei anschliessen oder abtrennen können. Sobald das Hauptlager den Status ändert, können sich die Lager unterhalb nicht mehr abtrennen (ausser durchs Löschen des Unterlagers).

**Comment by carlobeltrame** [comment]
Ist implementiert und ab morgen auf Integration testbar.
