### ISSUE TITLE
Abos: Antworten an alle

### ISSUE THREAD

**Issue by Chnebu** [hitobito/hitobito#854]
Hallo zusammen

Ich glaube, einen Bug gefunden zu haben. Und zwar funktionieren die Kästchen in den Abos nicht richtig, bzw. sie bewirken nichts. Ich habe auf dem Live-System MiData der Pfadi getestet, einfach als Empfänger nur die Rolle "Einheitsleiter" zugewiesen. Danke schonmals für Anregungen/Antworten:)

1. Abonnenten dürfen auf die Mailingliste schreiben:
Dieses Häkchen bewirkt irgendwie nichts! Obwohl ich es rausnehme, können z.B. die Adressen des Einheitsleiters immer noch Mails an die Liste schicken, die dann verteilt werden. Der Sender erhält  die Sendebestätigung. (Wir wollen "Antworten an alle"-Fälle vermeiden , da dies bei grossen Mitgliederzahlen ein Ärgernis darstellen kann.)

Nicht prioritär / gross störend aber trotzdem etwas Fraglich sind die anderen 3 Kästchen:

2. Beliebige Absender/-innen dürfen auf die Mailingliste schreiben:
Ob dieser Haken gesetzt ist oder nicht, bewirkt auch nichts. "Fremde" Absender werden in beiden Zuständen abgewiesen.

3. Abonnenten dürfen sich selbst an-/abmelden:
Ich sehe nirgends einen Button zum abmelden im Testmail oder in den Benutzereinstellungen auf MiData.

4. E-Mail mit Bestätigung an Absender schicken:
Obwohl da der Haken nicht platziert ist, kommen trotzdem Bestätigungen über den Mailversand.

**Comment by Michael-Schaer** [comment]
Hallo Chnebu

Ich melde mich nochmal zu deiner Fragen:

1. Wenn du eine Rolle mit Schreibrechten auf der Gruppe hast (z.B. Adressverwalter oder Sekretariat), dann kannst du unabhängig von den gesetzten Optionen auf die Listen innerhalb der Gruppe schreiben. Kann es sein, dass der Einheitsleiter auch die Rolle Adressverwalter hat?

2. Die Option funktioniert bei mir. Kannst du mehr Infos dazu geben, in welchem Fall es nicht funktioniert?

3. Abonnenten dürfen sich selbst an-/abmelden:
Der Button ist direkt auf dem Abo unter Info. Wenn die Checkbox aktiviert ist, können sich einzelne Personen dafür an und abmelden.

4. Das kann ich auch nicht nachstellen. Ich erhalte keine Bestätigungs-Mail mehr, wenn ich die Checkbox deaktiviere. In welchem Fall hat das bei dir nicht geklappt?

Liebe Grüsse
Safari
