### ISSUE TITLE
Lagerhierarchien: Lager sollte sich nicht selbst zuordnen können

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#855]
Mir ist aufgefallen, dass sich ein übergeordnetes Lager an sich selbst anschliessen kann. Sicherlich will das keiner, aber es sollte auch nicht versehentlich möglich sein.

Siehe #829 und #834

**Comment by carlobeltrame** [comment]
Good catch, als Validation könnte man das auch noch führen. Zudem sollte keine kreisförmige Struktur möglich sein (Lager A -> Lager B -> Lager C -> Lager A).

Wenn ich Lager A einem anderen unterordnen will, wird im Auswahl-Modal momentan bereits [Lager A ausgeschlossen](https://github.com/hitobito/hitobito_pbs/pull/116/files#diff-4f1eccd1dc8eb30f9b9a4ead4ddd317dR51), aber noch nicht dessen untergeordnete Lager.

**Comment by olibrian** [comment]
@Michael-Schaer Reicht dir im Moment, wenn verhindert wird, das sich ein Lager direkt sich selber zugeorndet werden kann? Die ganze Kette abzufangen wäre wohl etwas komplexer und eher eine Ausnahme. Können wir dieses Issue so schliessen?

**Comment by Michael-Schaer** [comment]
Ja, wenn es nicht zu technischen Problemen führt, muss es im Moment nicht abgefangen werden. Ich würde vorschlagen, dass wir das zurückstellen und bei einer nächsten Iteration fixen.
