### ISSUE TITLE
GLP-Erweiterungen für hitobito Core (5d)

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#859]
Die Erweiterungen für Mailchimp-Exporte sowie das externe Formular (mit der Übernahme der Daten in hitobito) sollten in den hitobito Core integriert werden.

Ein weiteres Feature ist die 2FA, welche übernommen werden könnte. Ist es möglich, dies optional zuzulassen?

**Comment by amaierhofer** [comment]
- Optionale 2FA authentifizierung (1d)
- Mailchimp Exporte (2d)
- Externe Formulare (2d)

**Comment by Michael-Schaer** [comment]
Zwei Ideen zu 2FA:
- Gibt es die Möglichkeit, 2FA für Rollen mit vielen Rechten zu erzwingen?
- Ist auch eine Anbindung an Authenticator-Apps geplant (Microsoft, Google, FreeOTP)?

Bei MailChimp und den Formularen würde uns interessieren, was da genau mitkommt.

**Comment by olibrian** [comment]
2FA wird im Ticket: https://github.com/hitobito/hitobito/issues/361 weiterverfolgt
Mailchimp steht allen zur Verfügung.
Externe Fromulare: Andere angehensweise, eher über API lösen #527
