### ISSUE TITLE
Rolle "Adressverwaltung" auf Gruppentyp "Region/Kanton" für MT-Instanzen

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#863]
Im Generic Wagon soll noch die Rolle "Adressverwaltung" auf dem Gruppentyp "Region/Kanton" erstellt wrden.

**Comment by RolandStuder** [comment]
Ich nehme an mit der Berechtigung :group_and_below_full, oder? Brauchst du das bis zu einem bestimmten Zeitpunkt?

**Comment by KunoKunz** [comment]
Wie es scheint, habe ich da etwas falsch verstanden. Ich dachte, die Rolle sei Explizit nur für das Verwalten von Adressen erstellt worden (ohne weitere Berechtigungen auf der Gruppe). Das wäre eigentlich die Anforderung beim Kunden. Gibt es eine (einfache) Möglichkeit, dies umzusetzen, @amaierhofer oder @kronn ?

**Comment by amaierhofer** [comment]
Ich denke am ehersten wären das die Permissions `group_read` und `contact_data`, siehe auch https://github.com/hitobito/hitobito/blob/master/doc/architecture/08_konzepte.md#berechtigungen

**Comment by RolandStuder** [comment]
Wie ich @KunoKunz verstanden habe, will er eine Rolle, die lediglich berechtigt ist, Personendaten zu ändern, aber nicht Eventdaten, die Gruppe selbst oder sonst irgendwelche anderen Berechtigungen auf der Gruppe.

**Comment by amaierhofer** [comment]
@KunoKunz Diese Berechtigung existiert nicht, am ehersten wäre es `group_full`, aber das schliesst Anlässe, MailingListen und das bearbeiten sämtlicher Attribute aller Gruppenmitglieder mit ein.

**Comment by olibrian** [comment]
@KunoKunz ist dies noch aktuell?

**Comment by KunoKunz** [comment]
@olibrian Nein - ich schliesse das Ticket.
