### ISSUE TITLE
Unterstützung für UTF-8 Zeichen

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito#864]
Die Datenbank wird aktuell mit latin1 characeter set betrieben, daher werden keine Zeichen aus dem erweiterten latin1 set, zb [``ï``](https://unicode-table.com/en/00EF), zwar persistiert aber nicht mehr wieder richtig dargestellt. Zudem können solche Datensätze nicht mehr verändert werden.

```
mysql>  SHOW VARIABLES WHERE Variable_name LIKE 'character\_set\_%' OR Variable_name LIKE 'collation%';
+--------------------------+-------------------+
| Variable_name            | Value             |
+--------------------------+-------------------+
| character_set_client     | latin1            |
| character_set_connection | latin1            |
| character_set_database   | latin1            |
| character_set_filesystem | binary            |
| character_set_results    | latin1            |
| character_set_server     | latin1            |
| character_set_system     | utf8              |
| collation_connection     | latin1_swedish_ci |
| collation_database       | latin1_swedish_ci |
| collation_server         | latin1_swedish_ci |
+--------------------------+-------------------+
10 rows in set (0.05 sec)
```

siehe auch #398

**Comment by js4gh** [comment]
Aus meiner Sicht ist die Unterstützung für UTF-8 Zeichen nicht wichtig oder Priorität. Allerdings währe es zwingend, das Hitobito verhindert das ein User nicht unterstützte Zeichen eintragen kann. Für mich ist das ein Bug. Entsprechend verstehe ich nicht warum @RolandStuder #398 geschlossen hat?

**Comment by kronn** [comment]
Wurde mit "PR 1052 / Convert to UTF8mb4" behoben.
