### ISSUE TITLE
Exporte für Rechnungen anpassen und erweitern (5h)

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#866]
* [ ] Die Angabe "CHF" sowie die Tausenderstriche sollen weggelassen werden
* [ ] Folgende Felder sollen zusätzlich exportiert werden: 
- Konto
- Kostenstelle
- Datum Zahlungseingang

**Comment by amaierhofer** [comment]
`Konto` und `Kostenstelle` würden wir vom `RechnungArtitkel` kopieren, für bestehenden Rechnungen wird das schwierig. Weiters kann es potentiell mehrere Zahlungseingänge geben, wollen wir hier alle oder nur den letzten?

**Comment by MrTinnysis** [comment]
Es müssten zwingend alle Zahlungseingänge (Betrag, Datum) drin sein, da sonnst eine Fehlersuche in der Buchhaltung sehr schwierig wird (nicht die einzelnen Monats Abschlüsse kontrollierbar)

**Comment by olibrian** [comment]
Gemäss Mail vom 11.11.19 von Lois werden Kostenstelle und Konto nur bei neu erstellten Rechnungen im Export aufgenommen. Bei bereits bestehenden Rechnungen wird diese Information fehlen.

**Comment by MrTinnysis** [comment]
Passt so, und kann geschlossen werden.
