### ISSUE TITLE
Anzeige der Rechnungen nach Jahren gliedern (4h)

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#867]
Die Rechnungsübersicht (z.B. https://cevi.puzzle.ch/groups/6/invoices) wird bei mehreren 100 oder noch mehr Rechnungen pro Jahr rasch unübersichtlich. Deshalb soll die Anzeige (analog den Kursen) nach Jahren unterteilt werden. Für die Einteilung massgebend ist das Datum der Rechnungserstellung.

**Comment by amaierhofer** [comment]
Die Gruppierung verwendet das Datum der Rechnungsstellung `issued_at`. Rechnungen die noch nicht gestellt wurden sind aus der Gruppierung ausgenommen, d.h. sie tauchen bei allen Jahren auf.

**Comment by nchiapol** [comment]
sollten noch nicht gestellte Rechnungen nicht einfach im aktuellen Jahr aufgeführt werden? Ich finde es verwirrend, wenn ich historische Rechnungen nachschaue und dann neue Rechnungen finde. 
(scheint mir aber nicht zentral)

**Comment by KunoKunz** [comment]
> sollten noch nicht gestellte Rechnungen nicht einfach im aktuellen Jahr aufgeführt werden? Ich finde es verwirrend, wenn ich historische Rechnungen nachschaue und dann neue Rechnungen finde.
> (scheint mir aber nicht zentral)

Würde wohl noch eher Sinn machen. Wir gehen davon aus, dass es im Alltag gar nicht viele Rechnungen gibt, die länger in diesem Status sind.

**Comment by amaierhofer** [comment]
Wurde angepasst und auf integration deploy, bitte Ticket schliessen falls das jetzt für dich so stimmt @nchiapol

**Comment by nchiapol** [comment]
passt für mich
