### ISSUE TITLE
Anmeldeangaben Stringlänge

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#872]
Wenn ich bei den Anmeldeangaben einen langen Text erfasse, wird das Spaltenmenu sehr lang.

Auf dem Desktop ist das nicht tragisch, aber in der Mobile-Ansicht kann dann effektiv nichts mehr ausgewählt werden (Scrolling ist deaktiviert).

Pragmatischer Vorschlag: Text im GUI auf z.B. 30 Zeichen schneiden

## Mobile
![Anmeldeangaben_m](https://user-images.githubusercontent.com/1799621/68577379-434a1c00-0470-11ea-9d9b-54ef754478d6.jpg)

## Desktop
![Anmeldeangaben](https://user-images.githubusercontent.com/1799621/68577377-434a1c00-0470-11ea-8257-1d3924dfbb5d.png)

**Comment by Michael-Schaer** [comment]
Merci für den Fix! Ist das schon auf dem Testsystem drauf?

**Comment by amaierhofer** [comment]
Change war nicht vollständig, ich habe noch ergänzt und deploye heute nachmittag nochmal

**Comment by amaierhofer** [comment]
Ist jetzt deployed

**Comment by Michael-Schaer** [comment]
Das ist schon eine Weile her. Merci für den Fix
