### ISSUE TITLE
Extra Zeilenumbrüche in Emails

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito#874]
Gemäss Rückmeldung von @Michael-Schaer werden beim MailingListen versand zusätzliche Zeilenumbrüche eingefügt. 

Dies soll auf integration geprüft (#873) werden und Mailversand entsprechend angepasst werden.

**Comment by Michael-Schaer** [comment]
Wurde der Fehler unterdessen gefunden?

Auf dem Testsystem kann ich den Status nicht überprüfen, da die Mails nicht verschickt werden oder nicht im Mailtrap landen. Bitte um Rückmeldung!

**Comment by carlobeltrame** [comment]
Ich weiss nicht, ob jemand etwas daran geändert hat, aber auf Integration kann ich das Problem nicht (re-)produzieren. Mails landen erwartungsgemäss im Mailtrap und haben keine extra Zeilenumbrüche, sowohl bei Plain Text als auch HTML body.
Ich schliesse das Ticket, falls der Fehler wieder auftritt gerne wieder eröffnen.

**Comment by Michael-Schaer** [comment]
Ich würde da gerne noch etwas nachtesten. Ich vermute auch einen Zusammenhang mit dem E-Mail-Client des Absenders.

Meine E-Mail-Adresse wird aber im Testsystem weiterhin abgelehnt. Ich habe euch dazu im [internen Ticketing](https://help.puzzle.ch/#ticket/zoom/1101) einen Log geschickt. Es wäre toll, wenn wir da noch etwas herausfinden würden.

**Comment by carlobeltrame** [comment]
Hast du im Abo an welches du Mails schickst auch deine Absender-Email auf die Whitelist eingetragen?
