### ISSUE TITLE
Impersonate führt zu Fehler auf Testsystem

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#875]
z.B. folgende Person Imitieren:
https://pbs.puzzle.ch/de/groups/2/people/62

### Personenansicht
![Imitieren_1](https://user-images.githubusercontent.com/1799621/68682221-0dd32a80-0565-11ea-9f30-250dab368cc6.PNG)

### Fehler
![Imitieren_error](https://user-images.githubusercontent.com/1799621/68682222-0dd32a80-0565-11ea-86ac-5b60bf55e0a7.PNG)

**Comment by carlobeltrame** [comment]
Wie es aussieht hängt das mit einer Fehlkonfiguration der Mailserver auf Integration zusammen.

**Comment by carlobeltrame** [comment]
Workaround: Der imitierten Person die Haupt-E-Mail wegnehmen, dann wird kein Mail ausgelöst und der Fehler tritt nicht auf.

**Comment by carlobeltrame** [comment]
Fixed. Thanks @amaierhofer!
