### ISSUE TITLE
Encoding Problem beim CSV export 

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito#876]
Ich habe das Problem auf Produktion bei dem CSV Export der Bundesleitung nachstellen können. 

Das Problem besteht, da die Einträge in der Liste nicht in dem voreigenstellten Encoding (ISO-8859-1) sind. Soweit ich sollten daten in UTF-8 gespeichert und beim Export nach ISO-8859-1 konvertiert werden

Interessanterweise konnte ich das problem mit dem prod DB Dump auf meiner lokalen Maschine nicht reproduzieren, eventuell hat es also was mit den dbs auf appuio zu tun. Vielleicht auch damit hitobito#868

**Comment by olibrian** [comment]
@kronn Haben wir in Zwischenzeit alles auf UTF-8 umgestellt?

**Comment by olibrian** [comment]
Gehe davon aus, dass wir alle Umgebungen updaten werden und in diesem Ticket keine Aktionen mehr notwendig sind.
