### ISSUE TITLE
Timeout bei SUISA-Auswertungen (5h)

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#879]
CSV- und Excelexporte bei grösseren Verbänden wie z.B. AMV laufen in einen Timeout:

504 Gateway Time-out
The server didn't respond in time.

**Comment by olibrian** [comment]
@severinraez hat bereits das Timeout erhöht. Leider reicht dies noch nicht. Was haben wir für Optionen für die Performance Verbesserung oder Asynchroner Job für den Export?

**Comment by amaierhofer** [comment]
@KunoKunz  @olibrian Könnt ihr sagen um welchen Export auf welcher Gruppe es konkret geht? Timeouts können schnell am cluster erhöht werden, die Nachhaltiger Lösung ist aber den Export asynchron zu machen, gibt ca 2 Stunden Aufwand

**Comment by olibrian** [comment]
Exporte welche viele Daten beinhalten (z.b. Bernischer Kantonal-Musikverband) fallen in ein Timeout. Einzelne kleinere Gruppen (z.B. Emmentalischer Musikverband) funktionieren gut.

**Comment by olibrian** [comment]
Kunde ist sehr happy mit dem Fix. Export geht noch ca 3s für die komplette SUISA Liste. Well done!
