### ISSUE TITLE
API Rechnungen (8h)

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#884]
Bestehende Daten von einer Rechnung sollen zusätzlich als API Endpunkt in einem JSON Format zur Verfügung gestellt werden. Nur lesende Abfragen. Analog der Liste /groups/X/invoices

**Comment by amaierhofer** [comment]
- JSON Representation definieren
- Test schreiben
- Dokumentation

**Comment by amaierhofer** [comment]
@MrTinnysis @nchiapol  Die Änderungen sind auf integration gedeployed. Sind die enthaltenen Attribute für euch ausreichend?

**Comment by MrTinnysis** [comment]
Ich habe den invoices Endpunkt kurz angetestet.
> Sind die enthaltenen Attribute für euch ausreichend?
Meiner Meinung nach passen die Attribute so. Passend wäre noch ein total_payed mit dem bereits bezahlten Betrag sinnvoll um rasch festzustellen ob eine Rechnung überzahlt ist ohne die zugehörigen Beträge zusammen zu rechnen.

**Comment by MrTinnysis** [comment]
@amaierhofer Da dieser Endpunkt wohl in erster Linie von Service Accounts (beispielsweise für die Anbindung eines Buchhaltungstools) verwendet wird, finde ich dass dieser Endpunkt auch für Service Tokens zur Verfügung stehen sollte.
Vorschlag: Neues Recht für Service Tokens: "Rechnungen dieser Ebene"

**Comment by amaierhofer** [comment]
@MrTinnysis Habe Rechnungen in ServiceTokens mitaufgenommen und neu deployed.

**Comment by MrTinnysis** [comment]
@amaierhofer Der Zugriff mit dem Service Token auf den entsprechenden Endpunkt funktioniert soweit. Ich bin aber stark der Meinung das ein Service Token nur auf die Rechnungen des Entsprechenden Layers Zugriff haben sollte und nicht Layer and below. Analog des Rechts "Personen dieser Ebene". Im Idealfall würde mann wohl beide Optionen anbieten, obwohl ich aktuell keinen nachvollziehbaren Grund für den Zugriff auf Rechnungen der Untergeordneten Ebenen sehe.

**Comment by tschuepbach** [comment]
> @amaierhofer Der Zugriff mit dem Service Token auf den entsprechenden Endpunkt funktioniert soweit. Ich bin aber stark der Meinung das ein Service Token nur auf die Rechnungen des Entsprechenden Layers Zugriff haben sollte und nicht Layer and below. Analog des Rechts "Personen dieser Ebene". Im Idealfall würde mann wohl beide Optionen anbieten, obwohl ich aktuell keinen nachvollziehbaren Grund für den Zugriff auf Rechnungen der Untergeordneten Ebenen sehe.

Möglicher use case?
- API-Key auf Ebene "Ortsgruppe"
- Somit Zugriff auf Rechnungen der Ebenen "Jungschar" und "Verein"

**Comment by nchiapol** [comment]
Ich bin mit MrTinnysis einverstanden, der Zugriff sollte nur für "diese Ebene" gelten. 

Die Ortsgruppen sind wohl wirklich der einzige Fall in dem eine Zugriff auf Unterebenenen sinnvoll sein könnte. Und dort ist der Aufwand mehrere API-Keys zu erstellen vertretbar. In allen anderen Fällen scheint mir der Zugriff auf Unterebenen problematisch. 

Entsprechend möchte ich auch nicht, dass die Option Untergeordneten Ebenen überhaupt verfügbar ist. (Ich sehe dann ja nicht, wer sich  Zugriff auf meine Rechnungen gibt.)

**Comment by amaierhofer** [comment]
Wurde angepasst und auf integration deployed, bitte Ticket schliessen falls das jetzt für dich so stimmt @nchiapol @MrTinnysis

**Comment by nchiapol** [comment]
gut für mich @MrTinnysis bitte schliessen, wenn das auch für euch passt.

**Comment by MrTinnysis** [comment]
Passt für uns auch so!
Ich kann den Status nicht ändern...
@olibrian Kannst das Issue schliessen.
