### ISSUE TITLE
Login schicken geht nicht - keine Berechtigung?

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#888]
Beim Versuch, den neuen Admins beim DSJ ein Login zukommen zu lassen, erhalte ich die Meldung "Sie sind nicht berechtigt, diese Seite anzuzeigen". Das gleiche passiert auch in unserer team.hitobito.com-Instanz. Ich sollte dazu aber eigentlich berechtigt sein..

**Comment by Vento-Nuenenen** [comment]
Nach meiner Erfahrung auf dem System der PBS, funktioniert das Login zusenden nur wenn man eine höhere Berechtigungsstufe hat als der neue Benutzer.

**Comment by KunoKunz** [comment]
Danke für den Hinweis. Da mir noch von anderer Seite ein Problem gemeldet wurde, scheint hier schon etwas nicht ganz zu stimmen.

**Comment by KunoKunz** [comment]
Meldung des SBV: "Guten Tag,

Zugriff auf das System läuft nicht mehr korrekt.
Die Seite um ein neues Passwort zu setzen (https://db.windband.ch/de/users/password/new) geht nach eine weisse Seite und kein Mail ist geschickt.

Auch mit einem Druck auf das Button "Login schicken" bekommt die Person kein Mail !

Bitte setzen sie das System schnell wieder voll in Betrieb !  Die User müssen für die SUISA Meldungen arbeiten können."

**Comment by KunoKunz** [comment]
Das Problem hing vermutlich mit dem Ausfall zusammen. Das Versenden der Logins funktioniert wieder.
