### ISSUE TITLE
Abteilung bearbeiten (Testsystem)

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#890]
Beim Bearbeiten einer Abteilung erscheint ein Fehler auf dem Testsystem PBS.

Nachstellen:
- Einloggen als Admin (Hussein Kohlmann)
- Gruppe öffnen: https://pbs.puzzle.ch/de/groups/19
- Gruppe Bearbeiten
-> Fehlerseite 404

Bitte fixen!

**Comment by amaierhofer** [comment]
Die Seed Daten hatten gefehlt, das Deployment wurde entsprechend angepasst und neu deployed.

**Comment by Michael-Schaer** [comment]
Super, merci!
