### ISSUE TITLE
SBV: Texte auf Stufe Dachverband einstellbar machen

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#892]
Die Texte unter dem Menupunkt Einstellungen sind mit der Superstruktur erst global definierbar. Diese sollten neu pro Verband editierbar sein und angezeigt werden (z.B. Login-Info).

**Comment by ThomasEllenberger** [comment]
Issue ist bereits über drei Jahre alt.
Gehe davon aus, dass dies aktuell kein dringendes Bedürfniss mehr ist.
-> Closed
