### ISSUE TITLE
Migrationen in OpenShift-Job ausführen

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#893]
Migrationen in OpenShift-Job ausführen und den Rails-Pod genau wie DelayedJob auf eine fertig migrierte DB warten lassen.

Ebenfalls Seeding in einen OSE-Job verschieben, um Zeit im Deployment zu sparen. Das Seeding sollte dabei "wait-for-migrations" beinhalten, um die Abhängigkeiten sauber aufzulösen.

Der Migration-Job sollte bewusst nicht die Seeds laden, auf diese kann die Applikation kurz warten.

**Comment by carlobeltrame** [comment]
@kronn das hast du inzwischen umgesetzt oder?

**Comment by kronn** [comment]
ja, es ist umgesetzt, aber leicht anders: 
1. Die Seeds werden geladen, aber die App wartet nur auf die Migrationen. Solange keine neuen Migrationen dazukommen, startet die App damit schneller.
2. Die Migrationen und Seeds werden in einem Deployment ausgeführt. Damit startet das automatisch neu, wenn ein neuer Release vorhanden ist.
