### ISSUE TITLE
Übersetzungen PBS

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito#894]
* Anstossen, damit aktuelle Übersetzungen durch die PBS gemacht werden können.
* Gibt es eine Möglichkeit, Transifex bei deployment der Integration anzustossen?

-> nightly Build konfigurieren

**Comment by kronn** [comment]
Es werden beim Integrationsdeployment die aktuellen Übersetzungen von transifex geholt. Oder was meinst du mit "transifex anstossen"?

**Comment by carlobeltrame** [comment]
Das Problem ist, dass neu hinzugefügte Keys bisher nicht automatisch auf Transifex gepusht wurden. Ich glaube das hat @amaierhofer inzwischen gefixt.
