### ISSUE TITLE
"Migration" auf Superstruktur?

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#896]
Mit der Superstruktur werden heutige Mitgliederverbände wie https://db.windband.ch/de/groups/16778/people?returning=true zu einem Dachverband. @kronn - brauchen wir da noch eine kleine Migration? In der Testversion konnte ich einige Gruppen verschieben, andere nicht. Folgt dies einer bestimmten Regel? Merci!

**Comment by KunoKunz** [comment]
Auf die gleiche Stufe wie der SBV kommen neu zwei heutige Unterverbände:

**Akkordeon Schweiz** https://db.windband.ch/de/groups/218/people?returning=true
- hier braucht es keine zusätzliche Zwischenstufe (Dachvberband und danach kommen gleich die angegliederten Vereine)

**Schweizer Chorverereinigung** https://db.windband.ch/de/groups/16778/people?returning=true
- die heutigen Regionalverbände sind neu als Mitgliederverbände zu führen

* [ ] @kronn haben wir für diese Verbände die nötigen Angaben (URL, Mail etc für die Produktion)?

**Comment by KunoKunz** [comment]
* [ ] Während der Migration respektive der Downtime der Applikation soll ein sinnvoller Text angezeigt werden

**Comment by kronn** [comment]
Die Berechtigungen müssen nicht angepasst werden. Wenn etwas nicht funktioniert, ist es besser, die betreffende Rolle zu löschen und neu zu vergeben. 

Wer muss die DNS-Umstellungen machen? Anders gefragt: Wann und wie können wir das TODO aus dem letzten Kommentar abhaken?

**Comment by KunoKunz** [comment]
@kronn Die Konfiguration wurde durch die Web-Admins der Verbände vorgenommen und ist somit auch erledigt. Merci viu mau!
