### ISSUE TITLE
SBV: Falsche Verknüpfung von Untergruppen

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#898]
Bei der MG Zimmerwald-Niedermuhlern gibt es seltsame Verknüpfungen:

In der Navigation (links) wird der Verein (https://db.windband.ch/de/groups/3824) auch als Untergruppe aufgeführt. Im Tab "Info" wird dafür die Untergruppe "Kontakte" aufgeführt, welche jedoch auf einen anderen Verein https://db.windband.ch/de/groups/3339 verweist.

* [x] Bitte diese beiden Verknüpfungen löschen

**Comment by kronn** [comment]
Die Gruppenstruktur ist durcheinander geraten. Ich habe sie neu aufgebaut und sortiert.
