### ISSUE TITLE
SBV: Aktivjahre falsch berechnet

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#899]
Bei der Person https://db.windband.ch/de/groups/9182/people/49050/history werden die Mitgliedsjahre falsch berechnet.

Die Person sollte aktuell 34 Aktivjahre ausweisen:
- Mitgliedschaften sind von 01.01.1984 bis 31.12.2013 und danach ab 1.2.2014

Berechnet werden allerdings 35 Jahre

**Comment by kronn** [comment]
Ich habe die Berechnung noch mal geprüft und keinen Fehler finden können. Laut der [Regelung der Berechnung der Veteranenjahre](https://www.windband.ch/media/1067/regelung_der_berechnung_der_veteranenjahre_sbv_2013_juni_d.pdf) sind im oben genannten Fall tatsächlich 35 Jahren vorhanden, weil kein ganzes Jahr Unterbruch enthalten ist.  Wörtlich heißt es in der Regelung

> Massgebend sind nur die im Musikerpass eingetragenen Jahrgänge –Tage und Monate sind nicht zu berücksichtigen.

Beim Berechnen der Aktivjahre wird daher aus "1984 bis 2013" + "2014 bis 2019" die Zeitspanne "1984 bis 2019", was die erwähnte 35 Jahre ergibt. 

Wenn hierzu ein aktuelleres, davon abweichendes Reglement existiert, welches ich übersehen habe, kann die Berechnung natürlich gerne entsprechend angepasst werden.

**Comment by bsantschi** [comment]
Danke für die detaillierte Erläuterung, Matthias! Ich werde mit Bernhard sprechen.

**Comment by olibrian** [comment]
Rückmeldung:

> Wenn ein Musikant am 10.1.2010 in einen Verein eintritt, dann hat er heute 11 Jahre Mitgliedschaft.
> Siehe Beispiel. Rinderbach, Mitglied Beispiel 2aa. Die Maschine sagt aber er ist nur 10 Jahre dabei.
> Der Fehler ist wie folgt: Das Jahr 2010 zählt als volles Mitgliedsjahr, das Jahr 2020 aber auch.
> Deshalb stimmt die Berechnung nicht.
> 
>  
> 
> Liebe Grüsse

In der Testumgebung habe ich es mit meinem User ausprobiert: https://sbv.puzzle.ch/de/groups/1/people/71389.html
Wenn ich eine aktive Rolle (z.b. Mitglied) mit einem Eintrittdatum im Jahr 2019 erstelle gibt dies Mitgliedsjahr 1 zurück. Wenn ich ein Eintrittsdatum im Jahr 2020 wähle erhalte ich Mitgliedsjahr 0 zurück.
