### ISSUE TITLE
Roletype (classname) instead of the localisation in JSON

### ISSUE THREAD

**Issue by gamba** [hitobito/hitobito#9]
person json ( /ll/groups/xxx/people/yyyy.json ) shows among the roles fields the localised name of the role. 

_role_type_ and _group_type_ are localised informations in the json file and depends of the translations. 
It would be interesting to add the class name for roles and groups in order to have a consolidated and permanent information in the json responses. 

```
{
...
"role_type": "amministratore degli indirizzi",
"role_classname": "Group::Abteilung::Adressverwaltung",
"label": "",
...
}
```

```
{
...
"group_type": "sezione",
"group_classname": "Group::Abteilung"
}
```

**Comment by codez** [comment]
For the moment, please contact your organisation's application responsible directly for feature requests.

**Comment by RolandStuder** [comment]
Valid wish, we would accept a pull request for this, but currently I mark this issue as stale.
