### ISSUE TITLE
Logo von Organisation hochladen können (6h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#90]
- Für jede hitobito Instanz sollte im Admin Bereich ein Logo hinterlegt werde können, das dann oben links erscheint.

**Comment by RolandStuder** [comment]
@codez für estimate

**Comment by codez** [comment]
estimate 6h

**Comment by RolandStuder** [comment]
@KunoKunz Soll ich das offen lassen, wenn du mehr Richtung Multitenant machen willst, dann ist das wohl noch interessant. Oder?

**Comment by amaierhofer** [comment]
Ersetzt durch #784
