### ISSUE TITLE
Bug persönlicher iCal Feed

### ISSUE THREAD

**Issue by Vento-Nuenenen** [hitobito/hitobito#904]
Ich schätze, ich habe einen Bug im persönlichen iCal-Feed gefunden:
Wenn man in der Linken Navigation auf "Einstellungen" > "Kalender integrieren" klickt, verschwinden alle anderen Menüpunkte von den Einstellungen.
Bei allen anderen Einstellungen passiert das nicht.

Vorher:
![Bildschirmfoto 2020-01-10 um 13 10 48](https://user-images.githubusercontent.com/35610192/72152396-21efa880-33ab-11ea-9475-a32ff2cd17e8.png)

Nachher:
![Bildschirmfoto 2020-01-10 um 13 10 56](https://user-images.githubusercontent.com/35610192/72152401-261bc600-33ab-11ea-9834-c1923093be6a.png)

**Comment by Vento-Nuenenen** [comment]
@Michael-Schaer Fyi

**Comment by carlobeltrame** [comment]
Merci, schau ich mir nächste Woche an.

**Comment by Vento-Nuenenen** [comment]
Jo, klappt jetzt wie erwartet.
