### ISSUE TITLE
Dringend: SUISA-Abschluss - Listen sind nicht gesperrt!

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#912]
Nachdem das Erfassungsjahr 2019 vor der Einführung der Superstruktur abgeschlossen wurde, ist es immer noch möglich, Aufführungen vom 2019 zu editieren. Dies darf nicht sein!

In der produktiven Version wurden unterdessen 2019er Aufführungen editiert. Diese werden nun fälschlicherweise in der 2020er Periode aufgeführt. Die entsprechenden  Einträge sind korrekt 2019 zuzuordnen.

Nach dem Drücken das "Abschliessen"-Knopfes ist der Bildschirm weiss geblieben. Ist allenfalls der Job nicht richtig durchgelaufen?

**Comment by kronn** [comment]
Ich habe die Daten manuell korrigiert und den Code angepasst, so dass der nächste Abschluss sauber durchläuft. Da der nächste SUISA-Abschluss noch etwas entfernt ist, habe ich keinen Hotfix ausgerollt.
