### ISSUE TITLE
Lagerhierarchien - Fehler beim Anhängen

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#913]
Hallo zusammen

Ich wollte mir heute noch etwas Zeit nehmen, um "Monkey-Mässig" im Testsystem mit den Lagerhierarchien herumzuklicken. Dabei bin ich aber gar nicht weit gekommen.

Wenn ich ein Lager einem anderen anhängen will, erscheint nur eine leere Seite. Hat das ev. mit dem Stack-Upgrade zu tun?

Nachstellen:
 - Login als Hussein Kohlmann / Consequuntur
 - Lager erstellen auf Bundesebene oder Kantonsebene
 - Lager direkt anhängen an eines der vorhandenen übergeordneten Lager
-> Weisse leere Seite erscheint

Könnt ihr noch mal kontrollieren, was los ist?

**Comment by amaierhofer** [comment]
Ja, das hat mit dem Stack upgrade zu tun, ich werde das morgen anschauen.

**Comment by amaierhofer** [comment]
Ich habe den Fehler gefunden und die Integrationsumgebung neu deployed.

**Comment by Michael-Schaer** [comment]
Merci für den Fix. Beim Test von heute klappt alles.
