### ISSUE TITLE
hitobito Signups komplett automatisieren

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#914]
Der Signup-Prozess für eine neue hitobito SaaS-Instanz läuft aktuell nicht mehr ganz sauber durch. Die Ursachen dafür kenne ich nicht im Detail.

Eine Ursache liegt womöglich darin, dass die E-Mail-Adressen noch nicht richtig hinterlegt sind (wird mit #908 erledigt). 

Um die administrativen Arbeiten noch weiter zu reduzieren, soll der Signup-Prozess soweit möglich durchautomatiisert werden. @RolandStuder hat da schon was angefangen, worauf m.E. aufgebaut werden könnte.

Hätte jemand Interesse, sich dem anzunehmen? in einem zweiten Schritt könnte allenfalls auch gleich der Bezahlprozess (z.B. analog Swissflirt) eingebaut werden.

**Comment by olibrian** [comment]
wird durch https://github.com/hitobito/hitobito/issues/1907 gelöst
