### ISSUE TITLE
Qualifikationen aktualisieren

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#915]
Vermutlich wieder ein Bug vom Stack-Upgrade (siehe auch https://github.com/hitobito/hitobito/issues/913):

Wenn ich folgende Aktion durchführe, erhalte ich auch eine leere Seite:
 - Seite öffnen: https://pbs.puzzle.ch/de/groups/1/events/1348/qualifications
 - Alles ankreuzen 
 - Qualifikationen aktualisieren

-> Leere Seite

Wenn möglich bitte auch bei den Specs aufnehmen!

**Comment by amaierhofer** [comment]
Wie auch schon bei #913 bestand hier ein Problem mit den Formular spezifischen CSRF Tokens. Diese habe ich jetzt deaktivert (https://github.com/hitobito/hitobito/commit/f1623c43d10bd7a1b7a8311b60c57ec61f79507e) damit wir nicht in noch mehr solcher Problem laufen.

**Comment by Michael-Schaer** [comment]
Sowohl auf Test, wie auch auf Produktion erhalte ich beim Absenden einer Qualifikation wieder eine leere Seite. Ist da der falsche Stand ausgeliefert worden?

**Comment by amaierhofer** [comment]
Der Stand war der korrekte aber der angedachte Bugfix (Feature disablen) hat in diesem Fall nicht ausgereicht. Ich denke ich habe das Problem jetzt korrekt gelöst. Einen neuen Stand habe ich auf integration gepushed.
