### ISSUE TITLE
Unsubscribe Link for Abos

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#92]
If an Abo is configured, so people can subscribe / unsubscribe themselves via hitobito. 

- Wenn erlaubt ist, sich von Abo selbst abzumelden, soll an Email ein Link auf die Abo Seite angehängt werden. (Wo sich die Person dann abmelden kann).
- Bei Text-Emails: > Abmelden: [url]
- Bei HTML-Emails: > <p style=""><a href="...">Abmelden / Unsubscribe</a></p>
- Übersetzungen? Link in allen Sprachen bereitstellen.
- Encoding

**Comment by codez** [comment]
Vorgehen:
* Plain E-Mails: Text mit zwei Leerzeilen unten anhängen
* Multipart E-Mails: Zusätzlicher Inline Part anhängen

Listenname ebenfalls anzeigen?

**Comment by codez** [comment]
Schätzung: 1PT

**Comment by RolandStuder** [comment]
@KunoKunz Link zur Liste zum Abmelden von Abos lasse ich auch mal offen, denke wäre wichtig hier etwas zu machen, wegen Datenschutz.
