### ISSUE TITLE
Gestaltungsmöglichkeiten für Rechnungen

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#921]
Zusammenfassung der Wünsche eines potentiellen SaaS-Kunden. Schätzungen stammen aus dem Ticket #676 für die Jubla.

- Logo / Briefpapier für E-Mail-Versand der Rechnungen
-    Kommt Stark auf die Implementierung drauf an:
      * Mit Konfigurierbarem Logo (3PT)
      * Mit Standard Logo (1PT)
- Schriftart auf Century Gothic ändern (CI/CD Jubla) (2h)

- [ ] Was würde es bedeuten, die Schriftart konfigurierbar zu machen?

**Comment by nchiapol** [comment]
Bei uns (Cevi) besteht auch der Wunsch für ein Logo auf der Rechnung. Unsere Vorschlag wäre dafür das Gruppenlogo zu verwenden, falls in der DB eines hinterlegt ist.

**Comment by ThomasEllenberger** [comment]
Eine Umsetzung ist durch Puzzle aktuell nicht geplant.
@nchiapol wir würden dieses Issue schliessen. 
Wenn dies für euch aktuell wird können wir dies auf Basis von https://github.com/cevi/hitobito_cevi/issues/170 weiterverfolgen.
