### ISSUE TITLE
Gateway Time-out bei Etiketten-Export

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#923]
Anders als der Excel- und CSV-Export geschieht wird der Ettiketten-Export im Vordergrund ausgeführt. Ab einer gewissen Anzahl Personen wird aktuell nur noch ein Gateway-Timeout angezeigt.

z.B. beim Format "3474":
[db.scout.ch/de/groups/...](https://db.scout.ch/de/groups/2/mailing_lists/1078/subscriptions.pdf?household=false&label_format_id=6&returning=true)

Fehlermeldung: `504 Gateway Time-out`

**Comment by amaierhofer** [comment]
Ich habe das Timeout entsprechend erhöht. Der export klappt nun bei mir.

**Comment by Michael-Schaer** [comment]
Danke für den Fix. Würde es Sinn machen, diese Exports auch im Hintergrund laufen zu lassen? Ich kann mir gut vorstellen, dass die Etiketten auch mal für 500 Personen oder mehr exportiert werden sollen.
