### ISSUE TITLE
Force SSL in Production

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito#927]
In config/environments/production.rb sollte das Setting force_ssl gesetzt werden, damit Cookies und Headers die vollen Sicherheitsvorkehrungen berücksichtigen.

Standardumsetzung mit Umgebungsvariable RAILS_HOST_SSL, welche in den entsprechenden Deployments gesetzt werden muss (Am besten global im base rails-web.yaml):

```
  ssl = %w[true yes 1].include?(ENV['RAILS_HOST_SSL'])
  config.force_ssl = ssl
  config.ssl_options = {
    redirect: { exclude: ->(request) { request.path =~ /healthz/ } }
  }
```

**Comment by amaierhofer** [comment]
Config und deployment habe ich entsprechend angepasst und auf Integration ausgerollt.
