### ISSUE TITLE
Event Pagination

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#929]
Ein kleiner Fehler bei der Eventliste: Die zweite Seite wird angezeigt, obwohl eine gerade ausreichen würde:

![event_pagination](https://user-images.githubusercontent.com/1799621/76611973-ae3d5980-651b-11ea-9b81-a876a8e97047.png)

**Comment by olibrian** [comment]
Kann dieser Bug weder in der Prod noch in der Int nachstellen.
