### ISSUE TITLE
Appuio Mail Server  limits

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito#930]
Wenn viele Emails kommen laufen wir in limits auf appuio

```
Sent mail to vel@db.cevi.ch (66.8ms)
BULK MAIL vel-bounces+japura=cevi-veltheim.ch@db.cevi.ch 'Cevi Veltheim organis' | initial send failed: 421 4.7.0 mxout1.prod.zrh.appuio.ch Error: too many connections from 5.102.147.130

421 4.7.0 mxout1.prod.zrh.appuio.ch Error: too many connections from 5.102.147.130
```

siehe auch https://sentry.puzzle.ch/pitc/hitobito-backend/issues/9388/?query=is:unresolved%20project:pbs

Diese emails bleiben dann im status `bulk_delivering` und verstopfen die mail queue

**Comment by amaierhofer** [comment]
Habe bei vshn ein [Ticket](https://control.vshn.net/tickets/APPU-2670) erstellt.

**Comment by amaierhofer** [comment]
Hier die Antwort, neue Frage, ist der mxout für uns der richtige mail server?

> Hi Andreas,
> 
>     Can you please explain what the limits are, i.e. how many emails are we allowed to send from a single pod within a given time frame?
> 
> There are no limits specific to pods, the mxout implements overall limits for the APPUiO public platform. So even if we disclose this limits, they would be of not much use as other customers mail load will affect those limits as-well.
> 
> We increased the limits a bit, so you should not run into the limits as often as before.
> 
> However Please note that the mxout is a best-effort service without any guaranteed delivery and as it is a service shared across multiple users, misbehaving customers will have an impact on its reputation. If you need a reliable e-mail sending service, please use an external service such as Amazon SES, Sparkpost, Mailgun, Sengrid or any similar service. These usually also provide proper APIs that can help you track issues.
> 
> Regards
> André

**Comment by psunix** [comment]
bei cevi prod werden immer die mails an 15 empfänger gesendet und dann wird 5s gewartet bevor der nächste Batch durchläuft.

das Ganze lässt sich über die beiden Settings Settings.email.bulk_mail.bulk_size und Settings.email.bulk_mail.batch_timeout pro Instanz konfigurieren.

Diese Funktionalität wurde implementiert damit eben die Limits der Mailserver nicht erreicht werden. 

War der Appuio Mailserver zu diesem Zeitpunkt einfach sonst ausgelastet? Für mich scheinen die konfigurierten Werte sinn zu machen und es sollte eigentlich nicht zu diesem Fehler führen.

Falls dies immer noch öfters auftritt, könnte man diesen spezifischen Fehler handeln. z.B. retry nach 10min. 

ich schliesse dieses Ticket mal ... falls hier weiterer Handlungsbedarf ist, einfach wieder öffnen.
