### ISSUE TITLE
Anpassungen am Mailversand

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito#932]
Wir wollen den Versand so umstellen, dass pro Email ein Job zum versenden verwendet wird. Grundsätzlich könnte das so funktionieren
 
- [ ] Emails abholen zusammen mit dem MailLog persistieren (im pv, unter mail_hash)
- [ ] Neuer Job pro MailLog der
  - [ ] Emails versendet
  - [ ] MailLog aktualisiert
  - [ ] Email vom PV entfernt löscht
  - [ ] Im Fehlerfall soll das Email am PV bleiben
- [ ] Metriken ergänzen, sodass fehlerhafte Emails aufscheinen

**Comment by kronn** [comment]
Vielleicht noch

- [ ] Im Fehlerfall EMail in einen "failing"-Ordner verschiebt, um debugging zu erleichtern
- [ ] Metrik fürs Dashboard, wieviele "failing"-Mails vorhanden sind (via prometheus oder `/healthz/mail`-Endpoint)

**Comment by psunix** [comment]
folgende Exceptions traten beim BulkMail-Versand in den letzten Monaten auf:

## 1. Net::SMTPSyntaxError 
### 1.1 Bad sender address syntax

`Net::SMTPSyntaxError: 501 5.1.7 Bad sender address syntax`

## 2. Net::SMTPUnknownError
### 2.1  too many emails per second

`Net::SMTPUnknownError: could not get 3xx (550: 550 5.7.0 Requested action not taken: too many emails per second)`

**Comment by psunix** [comment]
Hauptsächlich scheint es folgende Probleme zu geben:

1. Ungültige Mailadressen
2. SMTP Server nicht erreichbar
3. Zu viele Verbindungen/Mails an SMTP Server

**Comment by kronn** [comment]
Ich glaube, dass die meisten Probleme zumindest isoliert werden können, wenn man pro MailLog einen neuen Job anlegt, der normal von DJ im Fehlerfall wiederholt wird. Vielleicht ist es auch sinnvoll, für jeden Mailversand einen eigenen Job anzulegen, um hier feingranulareres Fehlerhandling zu bekommen. Insbesondere hätte man ein kleineres Retry-volumen, wodurch weniger Mails doppelt verschickt werden.

**Comment by psunix** [comment]
gerade noch dieses Gem entdeckt: https://github.com/rubygarage/truemail
ich schaue mir mal an ob man die mailadressen damit validieren kann. sowohl empfänger als auch sender adressen.

**Comment by psunix** [comment]
e-mail adress validierung ist implementiert. mal schauen wie sich das in der Praxis/Produktion bewährt.
