### ISSUE TITLE
Mehrfachauswahl-Aktion Veranstaltungsteilnahmen ungültige CSRF-Tokens

### ISSUE THREAD

**Issue by simfeld** [hitobito/hitobito#934]
In Zusammenhang mit #915, #913

Die Mehrfachauswahl-Aktion zum Hinzufügen von Personen zu Anlässen, Lagern oder Kursen funktioniert aktuell nicht.

Seit dem Stack-Update haben wir CSRF-Tokens pro Form, vgl. https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#per-form-csrf-tokens. In diesem Fall wird die Action des Forms überschrieben mit der Auswahl des Anlasses, zum Zeitpunkt der Generierung ist aber die ID uf -1 gesetzt, z. B. `/de/groups/13/events/-1/participation_lists`. Dadurch ist das Token ungültig.

Fix möglicherweise wie in https://github.com/hitobito/hitobito_pbs/commit/f58172bc501492f7d12522328746927034f1ec10, oder alternativ im Controller das Feature abstellen mit `self.per_form_csrf_tokens = false`.

**Comment by carlobeltrame** [comment]
Ist auf Integration behoben. Merci nochmals für den Fix!
