### ISSUE TITLE
Bessere/eigene Sicht auf Firmen und Mitarbeitende (5d)

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#936]
- Wenn Checkbox "Firma" angeklickt wird, sollen nur firmenspezifische Felder angezeigt werden (= Name, Vorname und Übername nicht anzeigen)
- Im Tab "Mitarbeiter-Innen" sollen nur Personen aufgeführt werden, die dieser Firma zugeordnet sind (Firma selber nicht)
- Möglichkeit, auch auf diesem Tab eine neue Person hinzuzufügen
- Massenoperationen für Personen einer Firma
- Pro Firma sollen mehrere Standorte (Adressen) erfasst werden können. und dort danach Personen zuteilen (Unterteilung nach Hauptsitz und Standorte).

**Comment by amaierhofer** [comment]
Das Konzept "Firma" existiert aktuell nur auf der Person. Gemäss Beschreibung (Standorte usw) wäre das aber eher ein Gruppen Konzept. Dort könnten dann die Mitarbeiter (analog Mitglieder) abgebildet werden. Was meinst du @KunoKunz

**Comment by carlobeltrame** [comment]
@amaierhofer Wenn man bei einer Person das Feld "Firma" (`company_name`) einträgt, dann wird auf der Person bereits aktuell ein Tab "Mitarbeiter/-innen" angezeigt (Route `/groups/{groupId}/people/{personId}/colleagues`). Ich denke das ist gemeint.

**Comment by ThomasEllenberger** [comment]
Issue geniesst aktuell keine Priorität und wird zur Zeit nicht umgesetzt.
-> Closed
