### ISSUE TITLE
Kursaufgebote erweitern

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#938]
Für Teilnehmende von Kursen können heute bereits Aufgebote/Bestätigungen versendet werden. Diese sollen um bestimmte Feautures erweitert werden:

- Gestaltung Layout/Logo
- zusätzliche Angaben zur Firma
  - Berufsbildner
  - Schulort, Lehrart (als Tags?)
- Möglichkeit, Aufgebote als E-Mail zu versenden oder ein "Massendruck" von Aufgeboten für einen gesamten Kurs

**Comment by ThomasEllenberger** [comment]
Issue wird aktuell nicht weiter verfolgt.
-> Closed
