### ISSUE TITLE
Konfigurierbarkeit der Rechnungsnummer (1d)

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#939]
Beim Erstellen von Rechnungen wird die Nummer automatisch generiert. Nach welchen Regeln geschieht dies (z.B. Nummernkreis pro Jahr, fortlaufenden Nummerierung über die Jahre hinweg etc.)?

Der Aufbau der Rechnungsnummer soll konfiguriert werden können. z.B. ein genereller Präfix, danach das Jahr und dann erst die fortlaufende Nummerierung.

**Comment by amaierhofer** [comment]
Dabei handelt es sich aktuell um die Nummer der Gruppe, zusammen mit einer pro Ebene fortlaufenden Nummer, siehe https://github.com/hitobito/hitobito/blob/0595eb8f56b93e001af18b452e0063337921c30c/app/models/invoice.rb#L200

**Comment by ThomasEllenberger** [comment]
Wird aktuell nicht weiter verfolgt.
-> Closed
