### ISSUE TITLE
Rechnungseinstellung allgemein; Zahlungszweck fehlt (16h)

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#943]
Die Rückmeldungen betreffen Felder, die im Zuge von #589 nicht mehr nötig sind. Da der neue Standard ab 30.6.2020 eingeführt wird, macht es Sinn, die Anforderungen darauf auszurichten.

* [x] Neue Einzahlungsscheinart "QR-Rechnung"

Allgemein
Absender Adresse 1: Für die Absender Adresse gibt es zwei Felder. Einmal unter den allgemeinen Einstellungen (für den Briefkopf) und einmal unter Einzahlungsschein. Momentan wird die Adresse nur gespeichert, wenn diese bei 'Absender Adresse' unter 'Einzahlungsschein' eingegeben wird. Gibt man eine Adresse nur im allgemeinen Feld ein, wird diese nicht gespeichert. Das Feld 'Absender Adresse' unter Einzahlungsschein ist eigentlich unnötig und sollte für keinen Einzahlungsschein verwendet werden.

* [x] Feld "Einzahlung für" in Name/Firma umbenennen
* [x] Feld "Adresse" neu auch für den ES übernehmen
* [x] Auf Briefkopf richtige Adresse anzeigen

Absender Adresse 2: Sobald Absender Adressen mit mehr als drei Zeilen eingegeben werden, wird die Rechnung auf zwei Seiten aufgeteilt.
* [ ] Zeichenbeschränkungen von QR-Rechnung übernehmen

Die übrigen Punkte beziehen sich auf Pflichtfelder und Andruck bei den verschiedenen ES-Typen. Diese werden mit der QR-Rechnung vereinheitlicht.

* [x] Feld "Kontonummer" ist neu immer optional und wird höchstens auf der Rechnung noch angedruckt
* [ ] Feld IBAN wird für die QR-Rechnung verwendet (sollte aber für ausl. keine Pflicht sein)
* [ ] Teilnehmernummer entfällt 
* [ ] Feld "Zahlungszweck" wird auf dem neuen ES entweder als "Unstrukturierte Mitteilung" (Ustrd) oder als Teil der Struktur der "Rechnungsinformationen" verwendet.

**Comment by amaierhofer** [comment]
@KunoKunz Wenn ich das richtige verstehe, dann macht es Sinn #589 vorzuziehen und dann die restlichen Punkte aus diesem Ticket zu bearbeiten. Wie siehst du das?

**Comment by KunoKunz** [comment]
ja, denke ich auch. Ruf mich am einfachsten an, wenn Fragen auftauchen.
