### ISSUE TITLE
Standardtexte für Mahnungen (3h)

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#944]
Bei neuen Instanzen sollen folgende Standardtexte bei den Mahnungen hinterlegt werden:

1. Mahnung
Titel: Zahlungserinnerung
Text: Im hektischen Alltag kann es schnell mal vorkommen, eine fällige Zahlung zu übersehen. Vielleicht ist es Ihnen schon aufgefallen, dass Sie unsere letzte Rechnung noch nicht beglichen haben.
Danke, dass Sie die Überweisung in den nächsten Tagen vornehmen. Sollten Sie die Zahlung bereits veranlasst haben, betrachten Sie bitte dieses Schreiben als gegenstandslos.
Tage bis Fällig: 30

2. Mahnung
Titel: Zweite Mahnung
Text: Trotz unserer Zahlungserinnerung haben Sie unsere Rechnung noch nicht beglichen.
Wir bitten Sie den fehlbaren Betrag zu begleichen.
Tage bis Fällig: 14

3. Mahnung
Titel: Dritte Mahnung
Text: Wir fordern Sie nun ein letztes Mal auf, den offenen Betrag innert Wochenfrist, zu begleichen.
Tage bis Fällig: 5

**Comment by amaierhofer** [comment]
@KunoKunz Ich habe beim ersten Text den Satz "Vielleicht ist es Ihnen schon aufgefallen, dass Sie unsere letzte Rechnung noch nicht beglichen haben." gestrichen damit er in die besteheden Spalte passt. Falls der Satz wesentlich ist, würde ich die Spalte vergrössern, wie siehst du das?

**Comment by KunoKunz** [comment]
@amaierhofer Das passt. Ich denke, der eine Satz ist nicht wesentlich und falls du die Spalte vergrössern würdest, müsste danach ja die Pdf-Rechnung/Mahnung auch noch angepasst werden.

**Comment by KunoKunz** [comment]
Auf der Testinstanz sind auf der obersten Ebene noch andere Texte drin. Beim Eröffnen einer Unterregion wurden danach die neuen Texte (inkl. Kommafehler) übernommen. Wenn das bei neuen Tenants auch auf oberster Stufe funktioniert, kann das Ticket geschlossen werden.
