### ISSUE TITLE
Haushalt via API auslesen

### ISSUE THREAD

**Issue by Tschet1** [hitobito/hitobito#945]
Als Nutzer der Datenbank, möchte ich mittels API eine Adressliste erstellen können, bei der vermerkt ist, welche Personen im gleichen Haushalt leben. Dafür kann beispielsweise der "household_key" beim Abfragen einer Person zurückgegeben werden.

Wenn diese Änderung befürwortet wird, kann ich einen PR mit den nötigen Änderungen vorbereiten.

**Comment by js4gh** [comment]
währe aus meiner Sicht absolut sinnvoll.

**Comment by Michael-Schaer** [comment]
Ja für mich macht das auch Sinn. Ich habe mich noch gefragt, ob die Berechtigungen ein Problem sein könnten. Wenn der Zugriff aber pro Person geregelt ist, sollte das eigentlich bereits passen (Irrtum vorbehalten).

**Comment by simfeld** [comment]
Würde ich auch unterstützen. Wenn auf der Person der `household_key` mitgegeben wird, sehe ich kein Berechtigungsproblem.

**Comment by carlobeltrame** [comment]
@Tschet1 sieht so aus als wäre ein PR willkommen. Zwar alle Rückmeldungen bisher aus der Pfadi, aber denke das ist im Core sicher gut aufgehoben.

**Comment by nchiapol** [comment]
Ja, wir vom Cevi hätten das auch gerne im Core. :-)
