### ISSUE TITLE
Fehler 404 beim anzeigen von Verlauf und Journal

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#947]
Bei der Anzeigen von dem Verlauf oder Journal wird ein 404 ausgegeben. Verdacht: es gibt einige gelöscht Gruppen wo die Person mal Mitglied war.

Zeitpunkt: 20.04.2020 16:49
Link: https://guild42.hitobito.com/de/groups/1/people/1/history

**Comment by carlobeltrame** [comment]
Der Root User hat etwas spezielle Eigenschaften, daher funktioniert das bei dieser Person nicht. Bei allen anderen Personen funktioniert der Verlauf und das Log aber.
Wir haben besprochen, dass wir da nicht weiter tief hineinschauen, Demos sollten in Zukunft eher von anderen Usern aus gemacht werden. Somit schliesse ich dieses Issue.
