### ISSUE TITLE
Ansicht neu registrierte Personen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#948]
# Ist

Wenn ich mich als externer User auf ein Event anmelde sehe ich anschliessend die komplette Applikation inkl. Gruppenstruktur, Events, Kurse, Einstellungen, etc. 

![image](https://user-images.githubusercontent.com/655627/103520932-41af9480-4e78-11eb-9f4d-beb8df7eb5c8.png)

Externer User = Person die noch nicht im System erfasst ist und sich mit der Event-Anmeldung registriert.

bei der externen Anmeldung wir die Person neu im System erstellt. Diese hat dann noch keine Rollen und wird der Root Gruppe angehängt.

# Soll

Nicht möglich:
- Solange einer neuen Person/Benutzer keine Rolle zugewiesen wurde sieht diese die Navigation auf der linken Seite nicht. inkl. Anlässe, Kurse, Einstellungen, etc
- Die Suchbar ist ebenfalls nicht vorhanden in diesem Fall
- Die Person kann natürlich auch nicht über Links auf Seiten zugreifen die in der Navigation bei Benutzern mit aktiven Rollen angezeigt werden. z.B. /de/groups/1

Möglich/Sichtbar
- Zugriff auf Sprachauswahl 
- Eigenes Profil anzeigen und bearbeiten
-  Tab auf Profil: Info, Abos, Rechnungen, Verlauf, Log

# Zugriff auf Log/Verlauf

Die neue Person lässt sich auch im System finden, jedoch kann nicht auf den Verlauf/Log zugegriffen werden. Dies sollte ebenfalls noch gefixt werden.

**Comment by psunix** [comment]
bei der externen Anmeldung wir die Person neu im System erstellt. Diese hat dann noch keine Rollen und wird der Root Gruppe angehängt. Die Person lässt sich auch im System finden, jedoch kann nicht auf den Verlauf/Log zugegriffen werden.

**Comment by psunix** [comment]
![image](https://user-images.githubusercontent.com/655627/103520877-293f7a00-4e78-11eb-9c46-e46c71528d6c.png)

**Comment by olibrian** [comment]
Gründe wieso eine Person keine Rolle mehr hat:
* Externer User (hat sich an einem Event, welcher für externe offen ist, angemeldet)
* Letzte Rolle wurde gelöscht

**Comment by psunix** [comment]
# Aktueller Workflow externe Anmeldung

## Öffentliche Eventseite

![Screen Shot 2021-01-04 at 12 02 54](https://user-images.githubusercontent.com/655627/103529079-53e3ff80-4e85-11eb-82b1-b64d86c5277b.png)

## Login / Registrierung

![Screen Shot 2021-01-04 at 12 03 55](https://user-images.githubusercontent.com/655627/103529110-5cd4d100-4e85-11eb-8a3f-082cf6859b15.png)

## Kontaktdaten erfassen

![Screen Shot 2021-01-04 at 12 04 20](https://user-images.githubusercontent.com/655627/103529139-6a8a5680-4e85-11eb-8d39-752fdac241f3.png)

## Anmeldung als Teilnehmer

![Screen Shot 2021-01-04 at 12 04 37](https://user-images.githubusercontent.com/655627/103529180-7d9d2680-4e85-11eb-8a47-86824a80a536.png)

## Anmeldedetails

![Screen Shot 2021-01-04 at 12 04 50](https://user-images.githubusercontent.com/655627/103529212-8d1c6f80-4e85-11eb-91b1-dda45be965a2.png)
