### ISSUE TITLE
Duplikatsvermeidung bei Etikettendruck funktioniert nicht zuverlässig

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#95]
z. B. https://db.scout.ch/de/groups/1129/people?kind=layer&name=Gesamte+Ebene&role_type_ids=37-38-52-39-48-63-49-47-40-54-55-56-57-58-59-44-51-50-64-41-60-61-62-53-5-6-7-8-3-4-9-10-11-12-13-14-15-16-17-18-19-20-21-22-27-28-29-30-31-32-33-34-35-36

siehe Leimbacher

relevanter Pullrequest: https://github.com/hitobito/hitobito/pull/13

**Comment by RolandStuder** [comment]
Also ein Aspekt ist, dass das der Link für das letzte verwendete Format nicht korrekt gesetzt wird.

Zum reproduzieren:
- Checkbox Duplikatsvermeidung setzten
- Ein neues Etikettformat auswählen.
- Seite der Personenliste neu laden
- Obersten Link (letztes verwendetes Format verwenden) anwählen

Der Link hat falschen Parameter -> people.pdf?condense_labels=false

**Comment by RolandStuder** [comment]
Aber auch dann werden nicht alle gemerged. Leimbacher eben z. B. nicht, Leonhardt schon. Kann kein Muster erkennen.

**Comment by diegosteiner** [comment]
Ich würde mich um das Problem kümmern, bräuchte allerdings:

1. Das PDF der Etiketten 
2. Die Daten in CSV-Form

Ich denke wir müssten allerdings die betroffene Abteilung um Erlaubnis fragen. Ich kenne einen AL der betroffenen Gruppe, ich kann sie beten, euch die Erlaubnis zu geben, mir das weiterzuleiten, falls das gewünscht ist.

**Comment by adriananderegg** [comment]
Dokumente an @diegosteiner gesandt

**Comment by RolandStuder** [comment]
@diegosteiner you rock, danke für die Korrekturen!
