### ISSUE TITLE
IP reputation ratelimit 

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito#953]
Wir haben Berichte von Problemen beim Versand von Listen-Mails erhalten. Beispiel einer Fehler-Nachricht:

```
Betreff: Undelivered Mail Returned to Sender
Datum: 03.05.2020 23:07
Von: MAILER-DAEMON-mxout1.prod.zrh.appuio.ch@relay.vshn.net (Mail Delivery System)
An: veltheim@[...]

This is the mail system at host mxout1.prod.zrh.appuio.ch.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

The mail system

<a[...]r@bluewin.ch>: host mxbw.lb.bluewin.ch[195.186.227.50] said:
554 5.2.0 sc969: IP reputation ratelimit in effect -
 https://support.bluewin.ch/provider/bounce/aXA9NS4xMDIuMTQ1LjIzO2M9c2M5Njk7aWQ9VkxwTGplU2ZXMEVmalZMcExqWFFZYTt0cz0xNTg4NTQwMDI3
(in reply to end of DATA command)

[...]
```

**Comment by olibrian** [comment]
Kontakt mit Bluewin aufgenommen. Entsprechendes Formular ausgefüllt.

**Comment by olibrian** [comment]
----------------------------------------
Antwort von Support am 2020-05-13 09:50:37.639112+00:00:
Da sich die Bluewin E-Mail Plattform um ein Residential Produkt handelt, werden sämtliche Domains gleich behandelt (basierend auf ihrer Reputation). Die maximale Anzahl an gesendeten E-Mails an unsere Plattform wurde überschritten. Die E-Mails wurden nicht abgelehnt, sondern verzögert versendet. Bitte beachten Sie, dass Ihre IP-Adressen nach einem Reputations-Management beurteilt wird. Daher ist es wichtig neue IP-Adressen zuerst aufzuwärmen, bevor grosse Mail-Mengen darüber versendet werden.

Schauen Sie unsere Postmaster-Seite an. Dort finden Sie das FAQ und Informationen, welche bei Ihrem Anliegen weiterhelfen können. https://postmaster.bluewin.ch/de/

Freundliche Grüsse
Bluewin Support
Swisscom (Schweiz) AG
