### ISSUE TITLE
Rechnungsadresse mit einem Slash

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#954]
Beim erstellen von einer Rechnung wird in der Adresse zwischen PLZ und Ort ein `/` eingefügt.

Diese kommt sowohl in der View wie auch in den generierten PDF's

Zu sehen:
https://puzzle.hitobito.com/de/groups/1/invoices/8
![Screenshot from 2020-05-12 09-33-00](https://user-images.githubusercontent.com/9592347/81652201-a7f02e80-9433-11ea-8f39-49ce7df4b12c.png)

Gibt es hierzu einen Grund? Weisst du da noch was @KunoKunz ?

**Comment by KunoKunz** [comment]
Nein, das ist mir bisher noch nie aufgefallen. Allenfalls wenn einzelne Felder leer sind oder zuvor leer waren? Bei https://puzzle.hitobito.com/de/groups/1/invoices/7 hat es ja funktioniert.

**Comment by olibrian** [comment]
Danke @KunoKunz für die Rückmeldung. Wenn die Adresse auf der Rechnung angepasst wird, wird der Slash nicht mehr angezeigt. Der Slash kommt aber, wenn ich eine neue Rechnung erstelle auf einer Person, auch wenn diese eine korrekte Adresse hat.
Beispiel ist https://puzzle.hitobito.com/de/groups/1/invoices/8

**Comment by KunoKunz** [comment]
Vielleicht könnte sich dies Andreas im Rahmen seiner Arbeiten für das Rechnungsmodul anschauen. Ich habe aktuell keine Erklärung dafür.

**Comment by olibrian** [comment]
Getestet mit https://demo.hitobito.com/de/groups/1/invoices/252
Merci!
