### ISSUE TITLE
Error-Message on API on demo.hitobito.ch

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#956]
when i use the following command (like suggested in the documentation) to log into the demo-plattform

> curl -d "person[email]=mitglied@hitobito.ch" \
>      -d "person[password]=demo" \
>      https://demo.hitobito.ch/users/sign_in.json

i get the following error-message:

> To allow requests to demo.hitobito.ch, add the following to your environment configuration: config.hosts &lt;&lt; "demo.hitobito.ch"

Am i doing anything wrong?

Have a nice day!

**Comment by amaierhofer** [comment]
We are phasing out `demo.hitobito.ch`, please use `demo.hitobito.com`

**Comment by chrusu** [comment]
Thanks, that fixed it for me.

You should consider updating your documentation, as it still references to `demo.hitobito.ch` in the example-calls.

Best Regards
