### ISSUE TITLE
Verlängerung der Annerkennungen J+S

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#959]
Hallo zusammen

J+S hat diese Woche neue Bedingungen kommuniziert, um die Annerkennungen wegen der ausfallenden Kurse zu verlängern. Sobald die Daten in der JS-Datenbank angepasst sind, sollten wir diese auch in Hitobito aktualisieren, damit die Datenstände übereinstimmen. 

Ich gehe davon aus, dass alle Jugendverbände davon betroffen sind und würde mich für eine Community-Lösung einsetzen. Die Regel dafür scheint mir gut als Datenbank-Script umsetzbar. 

Hier der entsprechende Auszug aus der Info von J+S:

> ### 1 Anerkennung/Einsatzberechtigung
>
> #### 1.1 Ausserordentliche Verlängerung der Einsatzberechtigung
> Der Bundesrat hat entschieden, die Einsatzberechtigung der J+S-Kader (J+S-Leiter/in, J+S-Expert/in, J+S-Coach, J+S-Coach-Expert/in), die im Status «weggefallen seit 01.01.2019», «weggefallen seit 01.01.2020» und «gültig bis 31.12.2020» sind, ausserordentlich bis Ende 2021 zu verlängern. 
> #### 1.2 Ordentliche Verlängerung der Anerkennung
> Wer in diesem Jahr ein Weiterbildungsmodul besucht, bekommt die Anerkennung(en) bis 31.12.2022 regulär verlängert."

**Comment by nchiapol** [comment]
Der Cevi ist hier ebenfalls an einer Community-Lösung interessiert. 

Persönlich fände ich es sinnvoll, wenn diese ausserordentliche Verlängerung im Verlauf sichtbar ist. Technisch könnte man das wohl am einfachsten mit einem "Pseudo-Kurs" lösen, dem man alle Betroffenen zusweist. (Das können wir im Moment aber nicht selbst, da wir nicht effizient nach den drei betroffenen Stati filtern können.)

**Comment by Michael-Schaer** [comment]
Der J+S hat die Verlängerungen in der Datenbank eingetragen. Die Anpassung sollte also jetzt auch in Hitobito gemacht werden, damit die Daten synchron bleiben.

Aus Sicht PBS ist kein Pseudo-Kurs nötig. Stattdessen würden wir das Feld "Ursprung" bei der Qualifikation verwenden, um einen Text zu hinterlegen. Dieser könnte beispielsweise "Ausserordentliche Corona-Verlängerung 2020" lauten.

Hier noch ein Snippet zum Feld "Ursprung", vielleicht ist so klarer, was gemeint ist:
![image](https://user-images.githubusercontent.com/1799621/84031606-42da1b00-a996-11ea-8d51-f2da561edfb6.png)

Angepasst werden sollen die folgenden Qualifikationen:
- Leiter*in LS/T Kindersport
- Leiter*in LS/T Jugendsport
- J+S Experte
- J+S-Coach
- J+S Coachexperte

Die Einschränkung des Datums können wir wohl auch einfacher formulieren, als der Artikel oben vom J+S:
> Die entsprechenden Qualifikationen, die entweder am 31.12.2019 oder am 31.12.2020 ablaufen würden, sollen so gesetzt werden, dass sie am 31.12.2021 ablaufen.

**Comment by fossil12** [comment]
@Michael-Schaer Ich glaube korrekt ist:

> Abgelaufen am 31.12.2018 oder 31.12.2019, oder Ablaufdatum vom 31.12.2020.

**Comment by nchiapol** [comment]
@Michael-Schaer Der Nachteil einer von Hand erstellten Qualifikation mit passendem Ursprung ist, dass die (wenn ich das richtig verstehe) in 3-4 Jahren nicht mehr sichtbar ist und der Verlauf dann Lücken enthält. Bei uns gibt es einige Personen (z.B. unser LKB) die viel Wert auf vollständige Verläufe legen. 

Wenn wir uns als Community auf eine andere Lösung einigen, können wir aber sicher auch damit leben. Der massgebliche Verlauf ist ja sowieso der in der SportDB. Wisst ihr gerade wie diese Verlängerung dort dargestellt wird?

**Comment by olibrian** [comment]
Betrifft **nur** die Qualifikation der PBS Gemäss Michael:

-     Leiter*in LS/T Kindersport
-     Leiter*in LS/T Jugendsport
-     J+S Experte
-     J+S-Coach
-     J+S Coachexperte

Achtung ohne LKB Qualifikation.

Aus Gründen der Nachvollziehbarkeit vor dem Update noch ein Select durchführen.

**Comment by anna-s-jubla** [comment]
Hallo zusammen! 
Ich bin aufgrund [dieses Eintrages](https://github.com/hitobito/hitobito/issues/959#issuecomment-644761511) etwas verunsichert, wie wir nun vorgehen, um die Anpassungen bei allen Jugendverbänden zu machen. @olibrian: Benötigst du spezielle Infos von uns, sodass die Anpassungen auch bei uns gemacht werden können? Kann ich sonst irgendwie unterstützen? Technisch kenne ich mich leider zu wenig aus, um eine Lösung vorzuschlagen. Danke für die Rückmeldung.

**Comment by olibrian** [comment]
Qualifikationen Jubla:
Betrifft bei der Jubla folgende Qualifikationen (analog PBS):

    J+S Leiter/in LS/T Kindersport
    J+S Leiter/in LS/T Jugendsport
    J+S-Experte/Expertin LS/T
    J+S Coach
    J+S Coach-Experte/Expertin

 

Betrifft Qualifikationen mit folgenden Ablaufdaten:

    Abgelaufen am 31.12.2018
    Abgelaufen am 31.12.2019
    Ablaufdatum am 31.12.2020

    Verlängerung bis 31.12.2021

**Comment by nchiapol** [comment]
Geht mir ähnlich wie der Jubla. Was ist nun hier der Stand und das weitere Vorgehen? Wäre schön, wenn Diskussionen zu Issues hier jeweils vollständig und für alle Mitglieder der Community nachvollziehbar abgebildet wären.

**Comment by olibrian** [comment]
Qualifikationen CEVI:
Alle mit Gültigkeit 2 Jahre:
  - J+S-Coach		
  - J+S-Coach-Experte
  - J+S-Experte Kursleiter LS/T	
  - J+S-Experte LS/T
  - J+S-Lagerleiter/-in LS/T
  - J+S-Leiter/-in Jugend LS/T
  - J+S-Leiter/-in Kinder LS/T

**Comment by carlobeltrame** [comment]
Ich habe entsprechende Migrationen für alle 3 Wagons vorbereitet. Diese sind noch in Code Review.

Nach aktuellem Stand werden die folgenden Mengen an Qualifikationen verlängert werden. Die genauen Zahlen können sich noch geringfügig ändern wenn z.B. Personen gelöscht werden.
PBS: 13668
Jubla: 8691
CEVI: 2197

Anmerkungen:
* **Bitte die Namen der Qualifikationen nicht mehr ändern, bis die Verlängerung produktiv ausgerollt ist** (oder hier kurz melden). Ich sage das weil die PBS gerade am Gender-Bezeichnungen ändern ist, und keine der Bezeichnungen in der [PBS Rollen-Liste](https://github.com/hitobito/hitobito/issues/959#issuecomment-644761511) momentan in der Produktion exakt so geschrieben ist.
* Die Weiterbildungsmodule in 2020 werden von der Migration nicht abgeändert, da diese noch laufend während diesem Jahr dazukommen können. Ich schlage vor, diese Anfang 2021 noch nachträglich zu verlängern.
(Verlängerungen sind nebenbei auch schwieriger von neu erworbenen Qualifikationen zu unterscheiden: in hitobito ist eine "Verlängerung" einfach eine neue Qualifikation; im `origin` Feld speichern wir nur den Namen des Kurses bzw. Weiterbildungsmoduls, aber nicht die ID. Einzig bei der PBS speichern wir seit den Kursbestätigungen zusätzlich die ID der Event-Teilnahme die die Qualifikation verursacht hat, aber auch dort nicht rückwirkend vor Herbst 2019.)
* @nchiapol: Lagerleiter/-in sowie Kursleiter sind bei J+S Zusätze die auf die Leiter- bzw. Experten-Anerkennung geschrieben werden. Diese Anerkennungen können somit aus J+S-Sicht weder einzeln ablaufen noch unabhängig "verlängert" werden. Sie werden vielmehr automatisch mit der zugrundeliegenden Qualifikation verlängert. Beim CEVI sollte man vielleicht bei Gelegenheit einmal diese Qualifikationsarten auf "unbeschränkte" Gültigkeit umschalten. Ich verlängere jetzt aber in der Migration die existierenden Lagerleiter- und Kursleiter-Anerkennungen der CEVI noch.

**Comment by nchiapol** [comment]
@carlobeltrame betreffend Lagerleiter/Kursleiter: Uns ist natürlich bewusst, wie das bei J+S gelöst ist (ich habe selbst beide Zusätze). Unsere Lösung macht die Konfiguration der Kurstypen etwas aufwändiger aber danach die Suche nach Lager- und Kursleitern einfacher und flexibeler. Das war deshalb ein bewusster Entscheid.
