### ISSUE TITLE
CORS Settings Service Accounts (6h)

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito#961]
Bei CEVI und SBV soll die CORS-Policy: Acces-Control-Allow-Origin aktiviert werden.

Da ein potentieller Angreifer mit CORS und der USER-API in Zusammenhang mit dem entsprechenden Cookie zuviel Daten auslesen könnte, muss diese im selben Zug deaktiviert werden.

## Techspec

- [ ] AllowedOrigins Feld zu ServiceToken hinzufügen
- [ ] rack-cors Gem verwenden
- [ ] Authenticatable::normalize_user_params in eine Middleware-kompatible Domain-Klasse auslagern
- [ ] Domain-Klasse in rack-cors initializer verwenden (origins mit Block) um Token zu finden und nach erlaubten Origins zu befragen

## Original Story

Ich habe eben mit einer JavaScript-Anwendung zur Darstellung der Kursinfos gespielt und scheitere dabei an folgender Fehlermeldung:
```
Access to XMLHttpRequest at 'https://db.cevi.ch/[...]' from origin '[...]' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
Wenn ich das richtig verstehe fehlt dieser Header auf Seiten von Hitobito und ohne können die Service Accounts nicht via JavaScript genutzt werden. Im Moment wäre wohl ein freier Access ok. Längerfristig wäre es aber wohl sinnvoller, wenn man die erlaubten Origin beim API-Key definieren könnte.

**Comment by carlobeltrame** [comment]
Ja, CORS ist im Moment nicht implementiert, das hatte ich schon bei der ursprünglichen Einführung bemerkt (siehe Punkt 4 unter https://gist.github.com/carlobeltrame/8dd5b5e6279d91d1e3c181cb9086666a#gistcomment-2787645).
In meinen Augen ist freier Access nicht ok, da wir sonst einen Angriffsvektor für Datenklau der verwalteten Personendaten öffnen. Ich würde mich auch für die Lösung mit erlaubten Origins pro API-Keys aussprechen. Eine dritte, nur marginal simplere Lösung wäre, die erlaubten Origins global konfigurierbar zu machen, ähnlich wie es bei den OAuth Applikationen abläuft.

**Comment by nchiapol** [comment]
Vielen Dank für das rasche Feedback und den Pointer zu Gist. Wäre sicher praktisch, wenn das auch in der Doku (https://github.com/hitobito/hitobito/blob/master/doc/development/07_service_accounts.md) erwähnt wäre. Sobald ich dazu komme mich etwas mehr mit meinem Projekt zu beschäftigen, erstelle ich auch einen entsprechenden Pull-Request.

Betreffend Angriffsvektor: Dieses Argument halte ich für wenig stichhaltig. Der Vorteil die Attacke via Browser und JavaScript statt mit curl auszuführen scheint mir minimal.

**Comment by carlobeltrame** [comment]
In der Dokumentation ist es bereits unter https://github.com/hitobito/hitobito/blob/e096dbce7e50cba1a6ec1fd07177be52e9e6cd40/doc/development/05_rest_api.md im einleitenden Abschnitt erwähnt. Aber gut zu wissen dass du das eher bei der service accounts Doku gesucht hast, dann wäre es wohl sinnvoll das dort auch noch zu erwähnen.

JavaScript im Browser (auf Seiten die vom Angreifer kontrolliert werden) hat gegenüber curl den "Vorsprung", dass der Browser bei Cross-Origin Requests die Cookies der Zieldomain mitsendet.

Ein Beispiel: Wenn ein User dann bereits in hitobito eingeloggt ist (ein session cookie hat) und dann auf eine Seite des Angreifers navigiert, kann der Angreifer via XHR mit `withCredentials` im Namen des Users die API verwenden. Der Browser gibt dabei dem Angreifer die Cookies nicht bekannt, sendet diese aber an die API, für die API sieht also alles normal aus. Wenn wir nun bei jedem API-Request den `Access-Control-Allow-Origin: *` zurückliefern, dann gibt der Browser die Response auch an den Javascript-Code des Angreifers zurück. Denselben Effekt könntes der Angreifer nur mit curl nicht erreichen, da curl das Session-Cookie des Users nicht kennt.

Bei Service Accounts ist das natürlich weniger ein Problem, da diese nicht via Cookies sondern via Bearer Token authentifiziert sind. Man könnte den `Access-Control-Allow-Origin: *` header nur dann setzen wenn via Token (im Header oder in der URL) zugegriffen wird. Aber dann sind wir nicht mehr so weit entfernt davon, es gleich richtig zu machen, mit einer abschliessenden Liste von erlaubten Origins.

**Comment by nchiapol** [comment]
Danke für die Ausführungen und sorry für die lange Reaktionszeit. Solange die User-API noch läuft, wäre ein `Access-Control-Allow-Origin: *` wirklich keine gute Idee. Unser Verständnis ist grundsätzlich, dass die User-API möglichst nicht mehr verwendet werden soll und mittelfristig deaktiviert wird.

Wir werden uns nun aber vorerst mal mit der aktuellen Situation arrangieren und das Anliegen allenfalls in einem nächsten Sprint aufnehmen.

**Comment by betsim** [comment]
Ich verstehe die Problematik, weshalb `Access-Control-Allow-Origin: *` in Kombination mit der User-API keine gute Idee ist. Ich sehe allerdings auch, dass aus Anwender-Sicht es sehr oft keine Alternative ist, die API-Calls serverseitig zu lösen, weil schlicht das Wissen fehlt. JavaScript ist m.E. aktuell nunmal _die_ Sprache bei Webapplikationen. Im SBV ist es zudem eine zwingende Anforderung, dass z.B. Kurse aus hitobito einfach auf den Websites der Kantonal- oder Regionalverbände angezeigt werden können. 

Daher meine Frage: kann die User-API für den SBV mit wenig Aufwand deaktiviert und dafür `Access-Control-Allow-Origin: *` aktiviert werden oder bedarf das eines grösseren Eingriffs?

**Comment by carlobeltrame** [comment]
Schätzung (6h):
* AllowedOrigins Feld zu ServiceToken hinzufügen
* rack-cors Gem verwenden
* `Authenticatable::normalize_user_params` in eine Middleware-kompatible Domain-Klasse auslagern
* Domain-Klasse in rack-cors initializer verwenden (`origins` mit Block) um Token zu finden und nach erlaubten Origins zu befragen
