### ISSUE TITLE
Währung in den Rechnungseinstellungen konfigurierbar (3h)

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito#970]
- [ ] currency:string, not null auf Rechnung und Rechnungseinstellungen
- [ ] Migration mit bestehendem Wert aus Settings
- [ ] Überall currency von Rechnung und nicht mehr aus den Settings lesen

**Comment by KunoKunz** [comment]
Beim Erstellen einer Rechnung auf einer Person sind die Betragsangaben unten immer noch Fix drin. Weiss nicht, ob der Link hilft: /de/groups/1/invoice_list/new?invoice%5Brecipient_ids%5D=6

**Comment by amaierhofer** [comment]
Danke @KunoKunz, hab das Problem gefunden und behoben
