### ISSUE TITLE
Fehlerhafte Participant Counts 

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito#971]
Bei manchen Events stimmt der Wert der cache_column `events#participant_count` nicht mit dem tatsächlichen Wert überein. Das kann immer wieder mal passiern, wenn beim An oder Abmelden ein Fehler auftritt oder bsp auch die Datenbank Verbindung verloren geht. 

Wie wollen wir mit dem Problem umgehen? Betroffen sind ca 1% der Events 

- Leitungs Rollen via Button die Möglichkeit geben Zahlen neu zu berechnen? 
-  Zahlen periodisch prüfen und ggf korregieren? 
- weiter Ideen?

**Comment by carlobeltrame** [comment]
Brauchts denn diese materialisierte Cache-Spalte überhaupt? Könnte man die nicht dynamisch berechnen? Bei einer kurzen Suche im Core habe ich nur zwei wirkliche Verwendungen gefunden, einmal in SQL im Scope `application_possible`, wo man es einfach durch ein `COUNT(event_participations)` plus join ersetzen könnte, und einmal in `application_possible?` was genau dieselbe Logik parallel in Ruby implementiert. Solange man einen Index auf `event_participations.event_id` hat sollte das doch live machbar sein, wir laden ja auch die (paginierte) Liste von `event_participations` um sie anzuzeigen?

**Comment by amaierhofer** [comment]
Der in cevi/hitobito_cevi#99 beschrieben Fehler, dass nach dem Ändern der Rolle (i.e. von Teilnehmer auf Leiter oder umgekehrt) die counts nicht neu berechnet wurden, ist jetzt behoben. Zudem habe ich einen Rake Task `event:refresh_participant_counts` ergänzt, mit welchem sich die counts in einem bestimmten Jahr von der Console aus einfach aktualisieren lassen.
