### ISSUE TITLE
Unicode-Bemerkung bei Anlass-/Kursanmeldung wirft Exception

### ISSUE THREAD

**Issue by hupf** [hitobito/hitobito#98]
Der folgende String mit Unicode Character als Wert für `Event::Participation#additional_information` führt bei Jubla Produktion zu einer Exception:

```
Vegetarier😝
```

Errbit Error: https://errbit.puzzle.ch/apps/51e3cc00de7748233f0007c3/problems/58011805de77482dd0000e92

Reproduzierbar auch auf Jubla- und PBS-Integration, lokal mit Sqlite tritt das Problem nicht auf.

In der Produktionsdatenbank von Jubla ist bereits auf der `additional_information` Spalte `COLLATE utf8_general_ci` definiert, trotzdem tritt der Fehler auf.

**Comment by hupf** [comment]
Ich denke das Problem ist ganz grundsätzlicher Natur und hat mit unserem MySQL Setup zu tun. Es tritt immer wieder an verschiedenen Stellen auf (siehe z.B. https://errbit.puzzle.ch/apps/529c60a2de77482d71027b0a/problems/5813b4f9de774844a3000c84).

**Comment by RolandStuder** [comment]
Mit eingesetzter MySQL Version geht das nicht. 

- evtl. ginge es mit einem speziellen Spaltentypen, theoretisch sollte es gehen, wenn man den richtigen Datentype setzt.
- Aber könnte bedeuten, dass man DB neu setzen muss.

Wird relativ aufwändig. Emojis müssen wir als Feature anschauen.

**Comment by kronn** [comment]
Ab MySQL-Version 5.5.3 gibt es das charset `utf8mb4`, welche Unicode-Zeichen mit 4 Byte (also Emoji) speichern kann. Eine passende MySQL-Version vorausgesetzt können die fragliichen Spalten konvertiert werden und dann auch Emoji (und andere Unicode-Zeichen aus den höheren Regionen) speichern. Weiterhin muss auch die Anwendung richtig mit der DB sprechen, damit die Emoji auch verlustfrei übertragen werden können. Für MySQL-Indizes muss auch noch die Spaltenlänge von 255 auf 191 Zeichen reduziert werden. Inwieweit sphinx damit umgehen kann, muss noch separat geklärt werden. Vermutliich reicht es aus. die entsprechende Unicode-Range auf ein Leerzeichen oder ähnlich zu mappen. Eine Suche nach Emoji mit einem Emoji ist damit vermutlich nochmal ein ganz neues Feature.

Siehe:

- http://stackoverflow.com/a/8109948/674840
- https://blog.arkency.com/2015/05/how-to-store-emoji-in-a-rails-app-with-a-mysql-database/

**Comment by hupf** [comment]
Diesmal ist es bei Jubla mit dem 🦄 Emoji aufgetreten ;-)

**Comment by RolandStuder** [comment]
@hupf Ist das etwas, was wir nach einer Migration nach OpenShift3 einfach lösen können?

**Comment by kronn** [comment]
Ich denke, dass dies mit einem Release einer neuen Version zumindest eingegrenzt ist, da dann der Fehler abgefangen wird. Mit der Migration nach OS3 bekommen wir vermutlich eine neue MySQL-Version, mit der wir die Emoji speichern können. Dies müsste natürlich immer noch eingebaut werden. Mit den oben verlinkten commits wird erstmal nur eine etwas freundlichere Fehlermeldung ausgegeben.

**Comment by RolandStuder** [comment]
Ich schliesse das, da der Benutzer gewarnt wird. Betrachen wir evtl. mit der Migration auf OS3 wieder.

**Comment by carlobeltrame** [comment]
Das ist wieder aufgetaucht, diesmal im TagsController. Wir könnten natürlich in allen Models diese Fehler abfangen und dem User Validation Messages anzeigen. Aber inzwischen sind wir auf OpenShift 3 und MySQL 14, was utf8mb4 schon lange unterstützt. Vielleicht könnten wir also den Vorschlag von @kronn umsetzen?

**Comment by psunix** [comment]
ist wieder aufgetaucht, diesmal hat ein user versucht beim Rollen-Label ein Emoji einzufügen.

ich fände es cool wenn wir Emojis bei den meisten Feldern ermöglichen könnten.

**Comment by kronn** [comment]
Siehe auch #864
