### ISSUE TITLE
localhost (ohne SSL) für OAuth Applikationen

### ISSUE THREAD

**Issue by wp99cp** [hitobito/hitobito#989]
Ich wollte zu Testzwecken `http://localhost:4200` als `redirect_uri` für die OAuth Eintragen. Gemäss Dokumentation sollte dies möglich sein: `The URLs must have the https:// protocol, except for localhost URLs, which are allowed to use http:// (for testing and development purposes)` (https://github.com/hitobito/hitobito/blob/master/doc/development/08_oauth.md). 

Dies führt aber beim Speichern zu einem Fehler: `Redirect URIs muss ein HTTPS/SSL URI (Identifier) sein`. Auch der Eintrag `urn:ietf:wg:oauth:2.0:oob` führt nicht dazu, dass Requests mit `http://localhost `als `redirect_uri` akzeptiert werden.

Ich denke es handelt sich hierbei um einen Fehler. Oder es sollte zumindest in der Dokumentation besser beschrieben werden.

**Comment by carlobeltrame** [comment]
Auf welcher Instanz von hitobito hast du das getestet? Auf der [PBS Integrationsumgebung](https://pbs.puzzle.ch) kann ich `http://localhost:4200` ohne Probleme eintragen, sowohl bei neuen als auch bei bestehenden OAuth Applikationen.

**Comment by wp99cp** [comment]
Zuerst auf https://demo.hitobito.com und anschliessend noch https://db.cevi.ch/ (also die Version des Cevi). Bei beiden kam die Fehlermeldung (vgl. Screen-Shot von https://demo.hitobito.com/).
Das `http://localhost:4200` auf einer Live-Instanz ggf. nicht zur Verfügung steht, verstehe ich, aber auf https://demo.hitobito.com sollte es eigentlich funktionieren, oder?

![image](https://user-images.githubusercontent.com/34008738/89418501-6c15ee00-d730-11ea-8fe6-f94091adb3a0.png)

**Comment by carlobeltrame** [comment]
Beide diese Umgebungen zählen als Produktionsumgebungen, und http://localhost ist nur auf Integrationsumgebungen freigeschaltet. In deinem Fall würde ich dir die CEVI-Integrationsumgebung unter https://cevi.puzzle.ch empfehlen. Den Login kannst du bei deiner Verbandsleitung bekommen @btemperli @nchiapol, diese müssen deine Applikation dann später ohnehin auf Produktion für dich eintragen.

**Comment by wp99cp** [comment]
Besten Dank für die Antwort! Ich konnte mein Problem nun auch ohne localhost lösen. In meine Augen macht es aber Sinn, dies in der Dokumentation zu ergänzen. Denn gerade als Outsider, der sich vorher noch nicht im Detail mit hitobito beschäftigt hat, führt dieses zu Verwirrung. 

**Mein Vorschlag:**
`The URLs must use the https:// protocol. In an integration environment localhost URLs are also allowed to use http:// (for testing and development purposes)`

**Comment by carlobeltrame** [comment]
Ist erledigt, merci für den Hinweis! Und gut zu hören dass es geklappt hat.
