### ISSUE TITLE
Globale Suche um Suche nach Anlässen erweitern

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#99]
SOLL: In der globalen Suche erscheinen auch Kurse, Lager oder andere Events. inbsondere soll auch nach Kursnummer gesucht werden können.

Herausforderung: 
- Wenn wir nur suche nach Kursnummer entspricht das wohl kaum der Benutzererwartung.
- Wenn wir allgemein aber Suche nach Lager zulassen, hat man wohl sehr viele ähnliche Resultate.
- Wir müssen das zeitlich sinnvoll einschränken.

Vorschlag: 
- Alle Events auffindbar machen, allerdings nach Durchführung ordnen, so dass die neusten zuerst kommen.

Originalissue: http://feedback.jubla.ch/issues/61

**Comment by fossil12** [comment]
Da in der Kurswesenanpassung 2017 von der Pfadi ähnliches geplant ist sollte dies direkt zusammen umgesetzt werden. Wir warten entsprechend auf nächstes Jahr: https://github.com/hitobito/hitobito_pbs/issues/37

Wir finden aber grundsätzlich, dass die Event-Ergebnisse auch nach Relevanz (eigene Rollen/Mitgliedschaften usw.) geordnet sein sollten.

**Comment by RolandStuder** [comment]
Wurde umgesetzt im Rahmen der Kurswesenanpassung 2017 PBS.
