### ISSUE TITLE
Anpassen der Berechtigung "Impersonate"

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#992]
Weiter einschränken der Berechtigung "Impersonate"

Möglichkeiten:
* Anfragen vor der Impersonate wenn die Zielperson mehr Rechte hat
* Nur Personen wo schreibrechte können impersoniert werden

**Comment by Michael-Schaer** [comment]
Für die PBS ist die Impersonierung von einer beliebigen Person besonders auf dem Testsystem nützlich. Das Testing wird so sehr viel einfacher, weil man mit dem Admin in Kürze alle Perspektiven einnehmen kann.

Auch auf dem produktiven System kommt es hin- und wieder zu einer Impersonierung, wenn jemand nicht weiter kommt. Von daher passt das System für uns eigentlich recht gut, so wie es ist.

Beim Impersonieren wird auch eine E-Mail verschickt, um Missbrauch zu verhindern.

**Comment by olibrian** [comment]
Anpassungsvorschläge von der Jubla:

Variante 1: Anpassung, dass nur Personen in der eigenen Ebene und in allen darunter liegenden Ebenen imitiert werden können (z.B.: Die kantonale Arbeitsstelle des Kt. Bern kann nur Personen imitieren, die im Kt. Bern oder in einer Untergruppe des Kt. Bern positioniert sind. Personen aus dem Kt. Aargau könnten also nicht imitiert werden.).
Variante 2: Personen, die imitiert werden sollen, müssen einen Bestätigungscode generieren. Nur mit diesem ist es möglich die Person zu imitieren. (z.B.: Person A soll von Person B imitiert werden. Dazu generiert Person A einen Bestätigungscode. Person B braucht diesen Code, um Person A zu imitieren.)

**Comment by nchiapol** [comment]
Bei uns war das bisher auch kein Problem. Allerdings konnte ich im Moment auch nicht herausfinden, wer  bei uns ausser den Dachverband-Admins überhaupt zu Impersonate berechtigt ist.

Variante 2 scheint auf dem Testsystem nicht besonders hilfreich. Ich kann damit ja keinen zufälligen Kontakt mehr übernehmen. Auch im Produktiv-System macht das den Support viel komplizierter.

Variante 1: finde ich ok. Ändert für den Dachverband-Admin ja nichts...

**Comment by Michael-Schaer** [comment]
Variante 1 ist für uns auch in Ordnung. Aktuell kann bei uns nur eine Rolle auf Bundesebene imitieren. Wenn wir das mal auf Rollen der KVs ausweiten wollen, ist es sicher gut, wenn nur darunterliegende Personen imitiert werden können.

**Comment by olibrian** [comment]
Schliesse dieses Issue, Umsetzungsissue ist #1250
